### ISSUE TITLE
AddTrack in Background not working on 13.5.1

### ISSUE THREAD

**Issue by FrankFundel** [DoubleSymmetry/react-native-track-player#1001]
**Describe the bug**
I have an event listener listening on remoteSkip and then executing: TrackPlayer.reset(); TrackPlayer.add(...); TrackPlayer.play();
On iOS 13.3 it works and plays the other track, on iOS 13.5.1 the player turns straight off.

**Environment (please complete the following information):**
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 2.42 GB / 7.88 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Users\frank\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

What `react-native-track-player` version are you using? 2.0.0-rc12
Real devices one on 13.3 and one on 13.5.1

**Comment by melodymorgan** [comment]
I am also experiencing a similar issue on iOS where the `reset()` call in the background is disabling the player.  My app is using version 1.2.3.  I am not clear if the bug is iOS Version specific but I will be doing a deeper investigation into root cause this week and will update this thread.

**Comment by FrankFundel** [comment]
@melodymorgan have you found out anything?

**Comment by jeffmon** [comment]
Using version `1.2.3`, I realized that calling `TrackPlayer.reset()` **always** kills the player. I listen for `playback-queue-ended`, and when it's called, I just `TrackPlayer.add({media}).then(() => TrackPlayer.play())`. Works great on my end!

**Comment by FrankFundel** [comment]
I haven't tried that but I want to add a song to the queue in background and then, while still playing, skip to the next. So instead of your code: "`TrackPlayer.add({media}).then(() => TrackPlayer.play())`", I want to do this: `TrackPlayer.add({media}).then(() => TrackPlayer.skipToNext())` which is not working. The played gets killed.

**Comment by jeffmon** [comment]
Have you tried `TrackPlayer.play()` first, then `skipToNext()`?

**Comment by FrankFundel** [comment]
I have a workaround now, but sometimes it does not work. I want `TrackPlayer.reset(); TrackPlayer.add(...); TrackPlayer.play();` to work again like in a earlier version :(
