### ISSUE TITLE
When a queue finishes playing, state is `paused` instead of `idle`.

### ISSUE THREAD

**Issue by lukepighetti** [DoubleSymmetry/react-native-track-player#1002]
It seems to me that when you play a fixed-length track and it ends with an empty queue, the state emitted on completion should be `idle`. Currently it emits `paused` but you are not able to press play to get audio playing again.

**Comment by maxckelly** [comment]
Also facing this issue.

**Comment by Sanjaya94** [comment]
Please provide the functions that you are using to add tracks and toggle play /pause. I managed to find a solution for this
