### ISSUE TITLE
`playback-track-changed` fires on track end, not track start

### ISSUE THREAD

**Issue by lukepighetti** [DoubleSymmetry/react-native-track-player#1004]
`playback-track-changed` only fires when a track ends. so `track` is the previous track and `nextTrack` is really the current track. This makes it very difficult to show the currently playing track and the next track, which seems to be the purpose of this event.

Note: this issue was created when developing on Android.

**Comment by faycito** [comment]
same

**Comment by mahmed0715** [comment]
same
