### ISSUE TITLE
getCurrentTrack is returning undocumented object

### ISSUE THREAD

**Issue by lukepighetti** [DoubleSymmetry/react-native-track-player#1005]
The documentation states that `getCurrentTrack` is a `Promise<string>`, however, when I call `TrackPlayer.getCurrentTrack()` on Android (didn't try other platforms) it returns this data.

```
{"_40": 0, "_55": null, "_65": 0, "_72": null}
```

Here is the documentation in question https://react-native-track-player.js.org/documentation/#getcurrenttrack

**Comment by SiddigHope** [comment]
is there's any update on this?

**Comment by lukepighetti** [comment]
I have not found a solution to this issue. If your project is greenfield I would recommend switching your stack to Flutter and using the excellent `just_audio` and `audio_service` packages.

**Comment by SiddigHope** [comment]
I have finally found a solution for this bug, but it only gives me the id of the track not the whole info..
it's too stupid, just you have to use an async function and awiat the result of getCurrentTrack method..
it worked fine for me
