### ISSUE TITLE
Not working with React Native 0.63.2

### ISSUE THREAD

**Issue by farshed** [DoubleSymmetry/react-native-track-player#1006]
React-native-track-player doesn't work with React Native 0.63.2 on Android. When I try to play something, nothing happens. No errors, no warnings, just silence. Please do note that it was working perfectly with 0.62.1. I just created a fresh project and moved my source code.

**To Reproduce**
Create a new project with React Native 0.63.2 and try to play something.

**Environment (please complete the following information):**
- Run `react-native info` in your project and share the content.
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 345.14 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_261 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

- What `react-native-track-player` version are you using?
Tried with both 1.2.2 and 1.2.3

- Are you testing on a real device or in the simulator? Which OS version are you running?
Tested on Emulator with Android 10.0 and a real device also running Android 10.

**Comment by mohity777** [comment]
yeah not working with android version 10. working fine with version 9 in my case

**Comment by farshed** [comment]
@mohity777 can you think of a reason why it's not working on some phones? Maybe library or android version is different?

**Comment by farshed** [comment]
Can confirm the issue is with React Native 0.63.x. I downgraded my project to 0.62.2 and everything's working again

**Comment by oleksiikiselov** [comment]
Facing the same issue, would be nice to find a workaround

**Comment by roman-gula** [comment]
I have the same issue (rn 0.63.2) but only on Android 4.x and 5.x (tried only on emulators). Track is buffered, but playing is not started.

**Comment by roman-gula** [comment]
Finally I got it worked. Seems it was caches problem in my case. 
I had some crash not connected to **react-native-track-player**. 
While solving it I tried to remove different caches like `rm -rf $HOME/.gradle/caches/`, removed `node_modules` and reinstall packages, but nothing helped. 
Finally I ran `cd android && ./gradlew clean` and that crash disappeared. Then I noticed that player got work in all versions of Android!

I am not sure what helped exactly, but try these solutions, hope it help somebody.

**Comment by DZakh** [comment]
For me, it works with "0.63.2". I came here only because I forgot to run `TrackPlayer.play()` after I added some tracks to the list. Maybe you have the same silly issue?

**Comment by clementinoux** [comment]
> Can confirm the issue is with React Native 0.63.x. I downgraded my project to 0.62.2 and everything's working again

Hey guys, any new clue about the lib not working with RN 0.63.2 ? The player works very well on simulator (for remote and local urls), on device, everything seems to load (tracks uploaded and recognised by the player) but the play() doesn't seem to work, no sound, no progress... It behaves a bit like an instant pause after play.

Any tips ? 
Thanks a lot

**Comment by andry1001** [comment]
Version 1.2.3 doesn't work on iOS for me, but works on Android. RN 0.62.2

**Comment by favianrizqulloh** [comment]
I tested and works well when I'm on debug mode, but when I'm on release/final production:
- using Android 10 audio from stream not playing at all
- using Android 6.0.1, stream works normally

React Native 0.63 with Gradle 6.7.1
