### ISSUE TITLE
Remote Duck gets fired on Android Notification

### ISSUE THREAD

**Issue by ShivamJoker** [DoubleSymmetry/react-native-track-player#1009]
# When I receive a WhatsApp message the `remote-duck` is getting fired and it triggers the music play/pause for that time

Enable remote ducking with v2

**Environment (please complete the following information):**
```sh
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 2.52 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.npm-global/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 26.0.2, 28.0.1, 28.0.3, 29.0.2, 29.0.3
      System Images: android-25 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

What `react-native-track-player` version are you using? 
`^2.0.0-rc13`

Are you testing on a real device or in the simulator? Which OS version are you running?

I am running it on real device (Xiaomi Poco F1)
Android 10 with MiUi 11

**Code**

```js
//config
   await TrackPlayer.updateOptions({
        stopWithApp: false,
        alwaysPauseOnInterruption: true,
        capabilities: [
          Capability.Play,
          Capability.Pause,
          Capability.SkipToNext,
          Capability.SkipToPrevious,
        ],
      });

// monitor intterupt when other apps start playing music
      TrackPlayer.addEventListener(Event.RemoteDuck, (e) => {
        // console.log(e);
        if (e.paused) {
          // if pause true we need to pause the music
          TrackPlayer.pause();
        } else {
          TrackPlayer.play();
        }
      });
```

**Comment by dungle27** [comment]
same this issue, Please help us fix it

**Comment by thorbenprimke** [comment]
@ShivamJoker - did you resolve this by setting `alwaysPauseOnInterruption` to false?

**Comment by mitchdowney** [comment]
@dcvz @thorbenprimke did this issue ever get resolved? Also, is setting alwaysPauseOnInterruption to false really a fix? Doesn't that prevent remote-duck events from firing entirely?

**Comment by ShivamJoker** [comment]
I have reopened this as users are saying it is not working. It should be addressed and fixed. Its been more than a year.

**Comment by mitchdowney** [comment]
@ShivamJoker actually, sorry it seems like I was wrong 😬 Android calls `remote-duck` no matter what value `alwaysPauseOnInteruption` is. I'm actually not sure how alwaysPauseOnInterruption is supposed to work...

In any case, it seems like our real issue with notifications not pausing or playing at the correct times on remote-duck events can be solved by setting and checking a wasPausedByDuck variable, like @dcvz explains in this issue https://github.com/DoubleSymmetry/react-native-track-player/issues/1263#issuecomment-921275153.

Here's the code Podverse is using that seems to be working as expected now:

```
let wasPausedByDuck = false
  PVAudioPlayer.addEventListener('remote-duck', (x: any) => {
    (async () => {
      const { paused, permanent } = x
      const currentState = await audioGetState()
      const isPlaying = audioCheckIfIsPlaying(currentState)
      if (permanent && isPlaying) {
        audioHandleStop()
      } else if (isPlaying && paused) {
        wasPausedByDuck = true
        audioHandlePauseWithUpdate()
      } else if (!permanent && wasPausedByDuck) {
        wasPausedByDuck = false
        audioHandlePlayWithUpdate()
      }
    })()
  })
```

**Comment by ShivamJoker** [comment]
@mitchdowney seems like a lot of work, should be handled by library internally.

I saw the maintainers are working on the kotlin version so I am hoping it might be not there.

**Comment by dcvz** [comment]
Currently, the Kotlin rewrite will have the same API as v2.
We're thinking about bringing automatic handling of ducking into the lib itself a bit further down the line though

@ShivamJoker do you know if you still experience this issue with WhatsApp in the Kotlin betas?

**Comment by ShivamJoker** [comment]
@dcvz I haven't tried the kotlin version, is it published anywhere?
Will give it a shot if you can tell me how to install it.

**Comment by dcvz** [comment]
@ShivamJoker we've been releasing betas for this new version: You can find the information here: https://github.com/DoubleSymmetry/react-native-track-player/discussions/1264
