### ISSUE TITLE
Dismissable notifications

### ISSUE THREAD

**Issue by trustedtomato** [DoubleSymmetry/react-native-track-player#1010]
**Is your feature request related to a problem? Please describe.**
Currently, the user can only dismiss the notification via pressing the stop capability.

**Describe the solution you'd like**
In Android 8.1, the common practice seems to be to have dismissable notifications, which are only dismissable when no audio is playing.

![Example image](https://lh3.googleusercontent.com/pw/ACtC-3djjgUDJkQKYch2TlHPrDhYokS9iUzwtTy0tWyg3aptTgk8xuaXaKbNTjhi9UIs2GmEzwKMEniuiuGG56iUXR6H5l3As73hdfWS2DTP0ubvoxLJrGb6t_QLriNrPeqElHonBF7r_MlubsaQmhXsAyDz=w541-h961-no?authuser=0)

A `dismissable: boolean` (defaults to `false`) could be added to `TrackPlayer.updateOptions`.

**Comment by fritzfr** [comment]
Indeed, this would be very nice to have.
