### ISSUE TITLE
HLS Streaming is not working on iOS

### ISSUE THREAD

**Issue by iMJumpmxn** [DoubleSymmetry/react-native-track-player#1013]
**Describe the bug**
If i try to stream an HLS File, it doesn't play any sound

**To Reproduce**
Add the m3u8 to the Queue and try to play it.

**Environment (please complete the following information):**
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 2.72 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^4.0.1 => 4.0.1 
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

Device: Simulator iOS 13.6
react-native-track-player: 1.2.3
**Code**
      TrackPlayer.add({
        url: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8',
        type: 'hls',
        id: this.props.data?.id,
        title: this.props.data?.name,
        artist: this.props.data?.artists[0].name
      });
      TrackPlayer.play();

**Comment by kleysonmorais** [comment]
same problem here, `react-native-track-player` seems unsupported to type `HSL` in devices iOS

more info [Stream Types](https://react-native-track-player.js.org/platform-support/#stream-types)

**Comment by imchintan** [comment]
I am facing the same issue in iOS, HLS Streaming is not working. [As per document](https://github.com/react-native-kit/react-native-track-player/blob/dev/docs/Platform-Support.md#stream-types) supports in the latest version. I use HLS m3u8.

Please help!

**Comment by gilsonviana-modus** [comment]
@iMJumpmxn have you found a possible workaround for this issue? Thanks

**Comment by jackyfish516** [comment]
Hi guys, are there any update on this issue? Tks!

**Comment by surhidamatya** [comment]
Hey,
guys any update on this I am using v1.2.7 Android device does not load HLS m3u8 file but it does load in simulator

**Comment by akhilumapathe** [comment]
Any update on this? Im facing the same issue.

`await TrackPlayer.setupPlayer({
  waitForBuffer: true,
  playBuffer: buffer,
  minBuffer: buffer * 2,
  maxBuffer: buffer * 5,
  iosCategory: IOSCategory.Playback,
  iosCategoryMode: IOSCategoryMode.Default,
});

await TrackPlayer.updateOptions({
  capabilities: [Capability.Play, Capability.Pause, Capability.Stop],
  progressUpdateEventInterval: 2,
});

await TrackPlayer.add({
  id: "1",
  url: "https://URL/TO/play/audio.m3u8",
  title: "Test Stream",
  artist: "Beta Devs",
  isLiveStream: true,
  type: TrackType.HLS, 
});

const state = await TrackPlayer.getPlaybackState();
if (state.state !== State.Playing) await TrackPlayer.play();
if (state.state == State.Playing) await TrackPlayer.pause();
`

Works well on Android.
