### ISSUE TITLE
Conflict between react-native-audio-toolkit and react-native-track-player

### ISSUE THREAD

**Issue by nenjamin2405** [DoubleSymmetry/react-native-track-player#1014]
**Describe the bug**
**Steps To Reproduce**
Hi guys, really appreciate your efforts in this super cool Audio Library. My below explanation will be long to clarify my current issue, and I believe it's also a frustration of most React Native developers when they handle complex Audio Player.

I'm developing a guided meditation app. The app allows users to select a meditation sound to play, and also has a background sound embedded to each meditation (a background sound can be soft music, ambiance, ...). Another requirement for this app is supporting background mode (when user locks the screen, he/she can need to continue hearing both sounds of meditation and background sound played in background, and can also control the player via the controller on the lock screen of iOS )

The image below is to illustrate background mode
![image](https://user-images.githubusercontent.com/16648769/89753638-2d52b000-db03-11ea-8e2a-fa60380a5b3a.png)

Because the meditation sound's duration is long (some sound can be over 1 hour length) and the requirement is background mode, I need a library which supports both streaming and background controller, that's why I chose `react-native-track-player`, and it works fine.

However, I also need to handle the background sound which is played concurrently with the main track of meditation, and react-native-track-player didn't support multitrack playing (you can see this issue: https://github.com/react-native-kit/react-native-track-player/issues/172#issue-311190689). 

That's why I need to find another library to handle the background sound, at the beginning, I chose `react-native-sound` to handle it, however, `react-native-sound` didn't support streaming, and some background sounds are over 4 minutes and they take a lot of time for `react-native-sound` to load the whole sound before playing it. 

Then I found `react-native-audio-toolkit` which supports streaming, I changed all of my logic of `react-native-sound` to `react-native-audio-toolkit`, and yes, it solves my slow loading speed issue, but I found another issue between `react-native-audio-toolkit` and `react-native-track-player`. Whenever the background sound handled by `react-native-audio-tookit` is played, it killed the `background-mode` functionality of `react-native-track-player` (the main sound handled by react-native-track-player is still playing, but the controller on the lock screen is disappeared)

The image below is to illustrate what it looks like when the controller on lock screen is disappeared
![image](https://user-images.githubusercontent.com/16648769/89753659-40fe1680-db03-11ea-969d-f207cb506c7d.png)

So my question: Is there any solution for this, I'm not sure whether it's because of the race condition between 2 libraries when they both support background mode playing. I'm super frustrated now and can't know how to solve this issue. 

Thanks for your time of reading this long explanation.

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 449.00 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

What `react-native-track-player` version are you using? "react-native-track-player": "^1.2.3",
Are you testing on a real device or in the simulator? Real Device
Which OS version are you running? iOS 13.6

**Code**
As soon as the snippet `sound.play()` from `react-native-audio-toolkit` is triggered, the background controller of the `react-native-track-player` is disappeared

**Comment by axelraymundo** [comment]
I have the same implementation and when I add a background music using rn audio toolkit, the player controls disappear from the lockscreen or. Did you ever find a fix for this @nenjamin2405 ?

**Comment by gavrichards** [comment]
I'm also having the exact same problem with the conflict between the these libraries and the disappearing lock screen controls. Would love to know if anyone found a solution.

**Comment by closetothe** [comment]
I have the same problem. Similarly, I'm also using expo (with custom module) and it seems that whenever expo a/v runs it messes with the trackplayer background service as well. If there was a way to "refresh" it, even manually that would be wonderful!
