### ISSUE TITLE
Removes a bunch of tracks from queue works wrong

### ISSUE THREAD

**Issue by shredder-rull** [DoubleSymmetry/react-native-track-player#1015]
**Describe the bug**
[remove](https://react-native-track-player.js.org/documentation/#removetracks) works wrong for bunch of track ids, but works correct for single track id.
I've tried to remove all tracks from queue with the exception of current track. In my case there is 9 tracks in queue. After removing 5 track remains. But only current track should remains. I think it happens because of removing by index [here](https://github.com/react-native-kit/react-native-track-player/blob/dev/ios/RNTrackPlayer/RNTrackPlayer.swift#L332)

**To Reproduce**
Try to clear queue by passing track ids to remove method

**Environment (please complete the following information):**
```
System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 832.48 MB / 16.00 GB
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v8.17.0/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.2, 27.0.3, 28.0.1, 28.0.2, 28.0.3
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
      Android NDK: 19.0.5232133
  IDEs:
    Android Studio: 3.1 AI-173.4819257
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Version of react-native-track-player is 1.2.3
I'm testing on simulator:
`react-native run-ios --simulator='iPhone 11'`

**Code**

```typescript
  const queue = await TrackPlayer.getQueue()
  const idsToRemove = queue.map(track => track.id)
  await TrackPlayer.remove(idsToRemove)
```

Workaround
```typescript
  const queue = await TrackPlayer.getQueue()
  const idsToRemove = queue.map(track => track.id)
  for (const id of idsToRemove) {
      await TrackPlayer.remove([id])
  }
```

**Comment by iwater** [comment]
same as above, but single id also fail sometimes
