### ISSUE TITLE
Expose battery background restriction (Android)

### ISSUE THREAD

**Issue by matt-dalton** [DoubleSymmetry/react-native-track-player#1019]
**Is your feature request related to a problem? Please describe.**
I couldn't find an existing issue for this, so sorry if I'm duplicating.

We get lots of complaints from Android users who (unknowingly) have battery background restriction settings turned on for our app. They then try and play audio in the background and find it turns off after a few minutes. Once they turn this setting off, everything works fine.

**Describe the solution you'd like**
Would it make sense to expose this setting via the API so we could handle it accordingly? There might be other libraries that do this (although I couldn't find any obvious ones), but it seems closely related enough to the audio functionality that it would make sense as an option.

**Describe alternatives you've considered**
I'm looking for another way of accessing this permission through RN, but I still think having it here would be useful in case we wanted to change the audio logic. Would also be nice not to have to install an extra library just for that one purpose.

**Additional context**
Here's an example of how to find these settings for various [phones](https://support.onfleet.com/hc/en-us/articles/360035454452--Battery-Optimization-Background-Restrictions#:~:text=Open%20the%20Settings%20menu%20on,and%20choose%20Don't%20Optimize.)

**Comment by dineshucreate** [comment]
@matt-dalton I am also facing the same issue on some of the Android devices and I am curious to know how other native music Apps are handling the same thing.

**Comment by dineshucreate** [comment]
@matt-dalton I think it's related to this issue: https://github.com/react-native-kit/react-native-track-player/issues/473

**Comment by fritzfr** [comment]
This could be of help:
https://github.com/voximplant/react-native-foreground-service
