### ISSUE TITLE
Android Notification Player metadata not updating correctly on local file

### ISSUE THREAD

**Issue by newfylox** [DoubleSymmetry/react-native-track-player#1020]
Hi guys. When I only play a track from a remote destination (https), I feed metadata with title, id, etc. and when the player is ready, it shows correctly those informations in the Android notification player. When I do the same with a local file (saved MP3 file on the device and saved JPG artwork), it also works but the artwork is not showing.

But the real issue is when I play first a remote track and then skip to a local track, the notification player doesn't update its metadata and even if I hear the good track, the informations are wrong. It's like it was too fast for the player to assimilate the new metadata that I sent it. To fix that, I have to pause the track, so the notification player shows the good informations (title, etc.). If I go back from a local track to a remote track, when the stream begins, the player updates its informations correctly at the moment the track starts. But if I switch back to a local track, it goes too fast (and that's what we want because it's local) but the informations stay on the previous track as long as I don't hit "pause", and then it updates.

System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
    Memory: 2.14 GB / 7.70 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /home/linuxbrew/.linuxbrew/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3
      System Images: android-28 | Intel x86 Atom_64
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.6 => 0.60.6

react-native-track-player@1.2.3

Tested on my Google Pixel 3XL, Android 10

```javascript
// same code and same podcast informations if using remote or local podcast.
TrackPlayer.reset()
      .then(() =>
        TrackPlayer.add({
          id: podcast.id,
          url: podcast.src, // http:// if remote, file:/// if local
          title: podcast.title,
          artist: podcast.artist,
          artwork: podcast.image, // http:// if remote, file:/// if local
        }),
      )
      .then(() => TrackPlayer.play())
```

**Comment by lyswhut** [comment]
v1.2.7 the same problem, do you have any good solutions?

**Comment by newfylox** [comment]
Not sure but I think I fixed the problem updating the player every time I start a new track. (`TrackPlayer.updateOptions`)
