### ISSUE TITLE
Extracting ShoutCast Metadata tags missing and protocal

### ISSUE THREAD

**Issue by BryonConley** [DoubleSymmetry/react-native-track-player#1021]
Hi,
Firstly, thank you for putting together a high quaity project for all of us.   I have two items under the Shoutcast metadata extraction issue.   I used the code snippet you gave to another user which I will incude here.  With that code snippet, I added a debug line "console.log(Objet.kets(e)) within you snippet as I was not able to obtain a tracklength/duration meta data at all.  That being said, we do have a radio player on our HTM website from the vendor that is getting the duration value  of the current track being played.  When I do the debug line, I see these keys on the object (e) as follows:
["genre", "album", "date", "artist", "source", "title", "url"]

Two things that are apprent,  namely the missing duration metadata key -- If we're not getting this in this array, then where is the other radio player getting this deata and how do I extract it for our app?

Second part of this same question,  ShoutCast brodcast the Artwork metadata about a minute after the track is played,  That being said, how do I setup a listener to capture it specifically?  Does this ShoutCast broad ast thee entire data, or does it 'bit-torrent' it for the entire minute and then we have this data?   Either way, is the react-native-track-player capable of capturing this and passing it for us to render.  How do I render this image correctly.

the code snppet I am referring to:
TrackPlayer.addEventListener('playback-metadata-received', async e => {

    console.log( Object.keys(e));

    const currentTrack = await TrackPlayer.getCurrentTrack();
    TrackPlayer.updateMetadataForTrack(currentTrack, {
        title: e.title,
        artist: e.artist,
	duration: e.length
    });
});

I cannot tell what version I have of the react-native-track-player, however, I installd the package two weeks ago (arouund Aug 24, 2020) through npm install react-native-track-player command.

**Comment by thecluff** [comment]
You can check the version of react-native-track-player by looking at package.json.
I'm not sure what your Shoutcast server looks like, but for me, I'm currently grabbing meta data by from the "streaminfo.get" file on the shoutcast server. The following fetches the song title and artist, which I then display in the app, and pass to TrackPlayer.. However, I need to refactor the react-native-track-player side of things, as the song title and artist dont update into the control center/lock screen. So, at most this could be a starting point for you.. I'm still looking around for a solid example of using react-native-track-player for shoutcast streams..

```

const [song, setSong] = useState('');
const [musician, setMusician] = useState('');

useEffect(() => {
      let repeat;
      async function fetchData() {
          try {
              const res = await fetch("*my shoutcast server*/streaminfo.get");
              const json = await res.json();
              setSong(json.data[0].track.title);
              setMusician(json.data[0].track.artist);
              repeat = setTimeout(fetchData, 26000);
          } catch (error) {
              console.error(error.message)
          }
      }
      fetchData();
      return () => {
          if (repeat) {
              clearTimeout(repeat);
          }
      }
}, []);

```
