### ISSUE TITLE
Progress is not reset when playing audio in single loop mode when screen is lock on iOS

### ISSUE THREAD

**Issue by genglei01** [DoubleSymmetry/react-native-track-player#1024]
**Describe the bug**
1.Play audio in single-loop mode on ios
2.lock screen.

The progress display well in first time, and become 100% when complete playing.
And progress is not reset to 0 when starting the second time playing

**To Reproduce**
implement a function as the following:

```
function onComplete(){
await TrackPlayer.skip(traceId);
await TrackPlayer.play();
      await TrackPlayer.seekTo(0);
}
```

call `onComplete` when complete one time playback

**Environment (please complete the following information):**
    "react-native": "0.61.5",
"react-native-track-player": "https://github.com/react-native-kit/react-native-track-player.git#dev",

Are you testing on a real device or in the simulator? Which OS version are you running?
Real Device

**Comment by jplandry908** [comment]
I am experiencing the same issue on v1.2.7. The song repeats correctly, but the progress bar gets stuck at 100%. If you pause and then un-pause the song, it goes to the correct location. I have even tried adding the same song multiple times to a queue, but the same thing happens. It does seem to reset correctly after the first song, but it gets stuck at 100% after the second song and never resets.

**Comment by Artem2001S** [comment]
Same issue
