### ISSUE TITLE
App crash when add new track to queue

### ISSUE THREAD

**Issue by tranhoang123** [DoubleSymmetry/react-native-track-player#1033]
**Describe the bug**
App crash on Release apk, and i only read log by Firebase Crashlystic 

com.guichaguri.trackplayer.service.player.LocalPlayback.add (LocalPlayback.java:77)
com.guichaguri.trackplayer.module.MusicModule.lambda$add$2$MusicModule (MusicModule.java:221)
com.guichaguri.trackplayer.module.-$$Lambda$MusicModule$_ISdZH9TdEnxpJjDTOZheGphQlE.run (Unknown Source:8)

on android studio log

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.newapp.h2lapp, PID: 25975
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.guichaguri.trackplayer.service.player.ExoPlayback com.guichaguri.trackplayer.service.MusicBinder.getPlayback()' on a null object reference
        at com.guichaguri.trackplayer.module.MusicModule.lambda$add$2$MusicModule(MusicModule.java:202)
        at com.guichaguri.trackplayer.module.-$$Lambda$MusicModule$_ISdZH9TdEnxpJjDTOZheGphQlE.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

App work fine when i run with debug mode.

Environtment: 
- Android 11, sdk 29,
-  "react-native-track-player": "^2.0.0-rc13",
- "react-native": "0.62.2"

**Comment by maxckelly** [comment]
@tranhoang123 - Is your crash log similar to this? I'm also facing a crash on release and only appears after a certain time the app has been downloaded (I believe). 

```
Thread 2 name:
Thread 2 Crashed:
0   A Life Lived                  	0x00000001002ec92c MediaURL.init(object:) + 1512 (MediaURL.swift:28)
1   A Life Lived                  	0x000000010030565c Track.init(dictionary:) + 668 (Track.swift:38)
2   A Life Lived                  	0x00000001002fa038 Track.__allocating_init(dictionary:) + 8 (<compiler-generated>:0)
3   A Life Lived                  	0x00000001002fa038 RNTrackPlayer.add(trackDicts:before:resolve:reject:) + 688
4   A Life Lived                  	0x00000001002fa038 0x1000e4000 + 2187320 (RNTrackPlayer.swift:290)
5   A Life Lived                  	0x00000001002fabe0 @objc RNTrackPlayer.add(trackDicts:before:resolve:reject:) + 220 (<compiler-generated>:0)
6   CoreFoundation                	0x0000000198f9bfc4 __invoking___ + 148
7   CoreFoundation                	0x0000000198e657d0 -[NSInvocation invoke] + 408 (NSForwarding.m:3312)
8   CoreFoundation                	0x0000000198e663f0 -[NSInvocation invokeWithTarget:] + 80 (NSForwarding.m:3418)
9   A Life Lived                  	0x00000001001ef670 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 460 (RCTModuleMethod.mm:569)
10  A Life Lived                  	0x00000001001f175c facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&) + 244 (RCTNativeModule.mm:108)
11  A Life Lived                  	0x00000001001f14c0 facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const + 44 (RCTNativeModule.mm:73)
12  A Life Lived                  	0x00000001001f14c0 invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) + 88 (RCTNativeModule.mm:65)
13  libdispatch.dylib             	0x0000000198c36134 _dispatch_call_block_and_release + 32 (init.c:1408)
14  libdispatch.dylib             	0x0000000198c375ac _dispatch_client_callout + 20 (object.m:495)
15  libdispatch.dylib             	0x0000000198c3da64 _dispatch_lane_serial_drain + 568 (inline_internal.h:2484)
16  libdispatch.dylib             	0x0000000198c3e498 _dispatch_lane_invoke + 400 (queue.c:3863)
17  libdispatch.dylib             	0x0000000198c47a5c _dispatch_workloop_worker_thread + 584 (queue.c:6445)
18  libsystem_pthread.dylib       	0x0000000198c9d718 _pthread_wqthread + 276 (pthread.c:2352)
19  libsystem_pthread.dylib       	0x0000000198ca39c8 start_wqthread + 8
```

**Comment by tranhoang123** [comment]
> @tranhoang123 - Is your crash log similar to this? I'm also facing a crash on release and only appears after a certain time the app has been downloaded (I believe).
> 
> ```
> Thread 2 name:
> Thread 2 Crashed:
> 0   A Life Lived                  	0x00000001002ec92c MediaURL.init(object:) + 1512 (MediaURL.swift:28)
> 1   A Life Lived                  	0x000000010030565c Track.init(dictionary:) + 668 (Track.swift:38)
> 2   A Life Lived                  	0x00000001002fa038 Track.__allocating_init(dictionary:) + 8 (<compiler-generated>:0)
> 3   A Life Lived                  	0x00000001002fa038 RNTrackPlayer.add(trackDicts:before:resolve:reject:) + 688
> 4   A Life Lived                  	0x00000001002fa038 0x1000e4000 + 2187320 (RNTrackPlayer.swift:290)
> 5   A Life Lived                  	0x00000001002fabe0 @objc RNTrackPlayer.add(trackDicts:before:resolve:reject:) + 220 (<compiler-generated>:0)
> 6   CoreFoundation                	0x0000000198f9bfc4 __invoking___ + 148
> 7   CoreFoundation                	0x0000000198e657d0 -[NSInvocation invoke] + 408 (NSForwarding.m:3312)
> 8   CoreFoundation                	0x0000000198e663f0 -[NSInvocation invokeWithTarget:] + 80 (NSForwarding.m:3418)
> 9   A Life Lived                  	0x00000001001ef670 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 460 (RCTModuleMethod.mm:569)
> 10  A Life Lived                  	0x00000001001f175c facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&) + 244 (RCTNativeModule.mm:108)
> 11  A Life Lived                  	0x00000001001f14c0 facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const + 44 (RCTNativeModule.mm:73)
> 12  A Life Lived                  	0x00000001001f14c0 invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) + 88 (RCTNativeModule.mm:65)
> 13  libdispatch.dylib             	0x0000000198c36134 _dispatch_call_block_and_release + 32 (init.c:1408)
> 14  libdispatch.dylib             	0x0000000198c375ac _dispatch_client_callout + 20 (object.m:495)
> 15  libdispatch.dylib             	0x0000000198c3da64 _dispatch_lane_serial_drain + 568 (inline_internal.h:2484)
> 16  libdispatch.dylib             	0x0000000198c3e498 _dispatch_lane_invoke + 400 (queue.c:3863)
> 17  libdispatch.dylib             	0x0000000198c47a5c _dispatch_workloop_worker_thread + 584 (queue.c:6445)
> 18  libsystem_pthread.dylib       	0x0000000198c9d718 _pthread_wqthread + 276 (pthread.c:2352)
> 19  libsystem_pthread.dylib       	0x0000000198ca39c8 start_wqthread + 8
> ```

yes, i think the error happen when i try add new track to queue, but app crash even I put this function on try-catch block.

**Comment by maxckelly** [comment]
Yeah I agree, crash is happening in the two areas that have the new track call. I'm starting to think it might be because of the url but I can't seem to see what's being passed through seeing its on release.

I can manage to reproduce it on one device but not another. I'm stuck now though.

**Comment by tranhoang123** [comment]
> Yeah I agree, crash is happening in the two areas that have the new track call. I'm starting to think it might be because of the url but I can't seem to see what's being passed through seeing its on release.
> 
> I can manage to reproduce it on one device but not another. I'm stuck now though.
> 
> > > @tranhoang123 - Is your crash log similar to this? I'm also facing a crash on release and only appears after a certain time the app has been downloaded (I believe).
> > > ```
> > > Thread 2 name:
> > > Thread 2 Crashed:
> > > 0   A Life Lived                  	0x00000001002ec92c MediaURL.init(object:) + 1512 (MediaURL.swift:28)
> > > 1   A Life Lived                  	0x000000010030565c Track.init(dictionary:) + 668 (Track.swift:38)
> > > 2   A Life Lived                  	0x00000001002fa038 Track.__allocating_init(dictionary:) + 8 (<compiler-generated>:0)
> > > 3   A Life Lived                  	0x00000001002fa038 RNTrackPlayer.add(trackDicts:before:resolve:reject:) + 688
> > > 4   A Life Lived                  	0x00000001002fa038 0x1000e4000 + 2187320 (RNTrackPlayer.swift:290)
> > > 5   A Life Lived                  	0x00000001002fabe0 @objc RNTrackPlayer.add(trackDicts:before:resolve:reject:) + 220 (<compiler-generated>:0)
> > > 6   CoreFoundation                	0x0000000198f9bfc4 __invoking___ + 148
> > > 7   CoreFoundation                	0x0000000198e657d0 -[NSInvocation invoke] + 408 (NSForwarding.m:3312)
> > > 8   CoreFoundation                	0x0000000198e663f0 -[NSInvocation invokeWithTarget:] + 80 (NSForwarding.m:3418)
> > > 9   A Life Lived                  	0x00000001001ef670 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 460 (RCTModuleMethod.mm:569)
> > > 10  A Life Lived                  	0x00000001001f175c facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&) + 244 (RCTNativeModule.mm:108)
> > > 11  A Life Lived                  	0x00000001001f14c0 facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const + 44 (RCTNativeModule.mm:73)
> > > 12  A Life Lived                  	0x00000001001f14c0 invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) + 88 (RCTNativeModule.mm:65)
> > > 13  libdispatch.dylib             	0x0000000198c36134 _dispatch_call_block_and_release + 32 (init.c:1408)
> > > 14  libdispatch.dylib             	0x0000000198c375ac _dispatch_client_callout + 20 (object.m:495)
> > > 15  libdispatch.dylib             	0x0000000198c3da64 _dispatch_lane_serial_drain + 568 (inline_internal.h:2484)
> > > 16  libdispatch.dylib             	0x0000000198c3e498 _dispatch_lane_invoke + 400 (queue.c:3863)
> > > 17  libdispatch.dylib             	0x0000000198c47a5c _dispatch_workloop_worker_thread + 584 (queue.c:6445)
> > > 18  libsystem_pthread.dylib       	0x0000000198c9d718 _pthread_wqthread + 276 (pthread.c:2352)
> > > 19  libsystem_pthread.dylib       	0x0000000198ca39c8 start_wqthread + 8
> > > ```
> > 
> > 
> > yes, i think the error happen when i try add new track to queue, but app crash even I put this function on try-catch block.

I tested on iOS device, it working fine. So I think the problem is exoplayer of android system, the error not happen with debug mode, so i don't know what exactly happen

**Comment by maxckelly** [comment]
I'm testing on iOS but same thing not happening in debug mode

**Comment by maxckelly** [comment]
@tranhoang123 - I've found out a bit more about it. Unsure if its the case for you but for me its caused due to putting the app in the background then reopening it. It causes a refresh I believe and that then throws an error. 
See image 
<img width="2273" alt="Screen Shot 2020-09-21 at 1 29 11 pm" src="https://user-images.githubusercontent.com/33044453/93730984-702d9a80-fc0e-11ea-9414-0ca6e32b7109.png">

**Comment by freudibili** [comment]
Hello everyone.

We just realeased an app and I saw the same error. @maxckelly did you find a workaround to fix that ?
