### ISSUE TITLE
Suggestion: Can we have a HeadSet Event which will fire when HeadSet is connected or disconnected?

### ISSUE THREAD

**Issue by ankitsinghania94** [DoubleSymmetry/react-native-track-player#104]

**Comment by Guichaguri** [comment]
We already automatically trigger the pause event when the headset is disconnected. Is there a specific reason that you might need those two events?

**Comment by ankitsinghania94** [comment]
@Guichaguri I have created ear piece speaker function by bridging (fork this repo). Now i need to destroy my proximity sensor listener when headset is connected. It would be better if there is some event for that. Is it possible to have a separate listener for this?

**Comment by ankitsinghania94** [comment]
@Guichaguri I have bridged the headset event. I'm not good with the native code, this is the link of my forked repo `https://github.com/ankitsinghania94/react-native-track-player`. May be you can help me with this or can add as a enhancement. Also, i have added some events like playWithEarPiece() something like whatsapp voice message.

**Comment by bradleyflood** [comment]
Closing this as an outdated issue :)
