### ISSUE TITLE
[iOS only] Codepush deployment breaks audio-player

### ISSUE THREAD

**Issue by christophemenager** [DoubleSymmetry/react-native-track-player#1044]
**Describe the bug**
On iOS, when deploying anything with codepush (features not related with sound or with the audio-player), no sound is heard
This bug is only on iOS, no issue on android.

**To Reproduce**
device : iPhone X, iOS 13.4.1
"react-native-code-push": "^6.3.0"
command used to deploy with codepush : `appcenter codepush release-react`

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
What `react-native-track-player` version are you using?
Are you testing on a real device or in the simulator? Which OS version are you running?

*Investigation*
1. I focused on assets that could be missing on wrongly erased by the deployment : looks like a dead-end as all mp3 assets are in the bundle deployed by codepush
2. I focused on something that could break the audio-player after a codepush deployment. After looking at the logs before and after a codepush deployment : 
**before (normal behaviour) :** 

15:40:53.109004+0200	mediaremoted	[MediaServerNowPlayingDataSource] Some session is playing did change notification received. SomeSessionIsPlaying = (
)
15:40:53.109945+0200	mediaremoted	[MRDNowPlayingOriginClient] Searching for new inferred now playing client matching com.xxx.staging-3784
15:40:53.110228+0200	mediaremoted	[MRDNowPlayingOriginClient] _reevaluateStateWithReason reloadNowPlayingClientFromDataSource
15:40:53.110440+0200	mediaremoted	[MRDNowPlayingOriginClient] Current client origin-iPhone de XXX/client-com.xxx.staging-3784 /player-MediaRemote-DefaultPlayer.
15:40:53.110594+0200	mediaremoted	[MRDNowPlayingOriginClient] _calculateActiveNowPlayingClient choosing inferred client origin-iPhone de XXX/client-com.xxx.staging-3784 /player-MediaRemote-DefaultPlayer.

**after codepush deployment (abnormal behaviour) :** 
None of these logs are seen

**In both cases**
I see those three logs (we looks normal, I want to start playing backgroundMusic.mp3 ), it's just to be as complete as possible

15:52:28.092988+0200	mediaremoted	Set: origin-iPhone de XXX/client-com.xxx.staging-3784 ()/player-MediaRemote-DefaultPlayer setting playbackQueue to <{
    contentItem = "item:<C786CD9E-FDF3-4026-ADA7-F5E7F38B47E9/backgroundMusic.mp3/PlaybackRate: 0.000000>\n";
    contentItems =     (
                {
            identifier = "C786CD9E-FDF3-4026-ADA7-F5E7F38B47E9";
            metadata =             {
                "__playbackRate" = 0;
                "__title" = "backgroundMusic.mp3";
                artworkAvailable = 0;
                "custom: calculatedElapsedTime" = "00:00:00 (0.000000)";
                "custom: delta" = "00:00:00 (0.004014)";
                "custom: remainingTime" = "00:00:00 (0.000000)";
                duration = "00:00:00 (0.000000)";
                elapsedTime = "00:00:00 (0.000000)";
                elapsedTimeTimestamp = "2020-10-13 13:52:28 +0000";
                nowPlayingInfo =                 {
                };
                playbackRate = 0;
                title = "backgroundMusic.mp3";
                trackArtistName = XXX;
            };
        }
    );
    location = 0;
}>
15:52:28.093734+0200	mediaremoted	Set: origin-iPhone de XXX/client-com.xxx.staging-3784 /player-MediaRemote-DefaultPlayer setting nowPlayingItem to <<MRContentItem: 0x139e14260> {
    identifier = "C786CD9E-FDF3-4026-ADA7-F5E7F38B47E9";
    metadata =     {
        "__playbackRate" = 0;
        "__title" = "backgroundMusic.mp3";
        artworkAvailable = 0;
        "custom: calculatedElapsedTime" = "00:00:00 (0.000000)";
        "custom: delta" = "00:00:00 (0.005330)";
        "custom: remainingTime" = "00:00:00 (0.000000)";
        duration = "00:00:00 (0.000000)";
        elapsedTime = "00:00:00 (0.000000)";
        elapsedTimeTimestamp = "2020-10-13 13:52:28 +0000";
        nowPlayingInfo =         {
        };
        playbackRate = 0;
        title = "backgroundMusic.mp3";
        trackArtistName = XXX;
    };
}>
15:52:28.093949+0200	mediaremoted	Set: origin-iPhone de XXX/client-com.xxx.staging-3784 ()/player-MediaRemote-DefaultPlayer setting nowPlayingItem from <item:<830722ED-4EF6-42CA-BDCE-86AAA7868C36>> to <item:<C786CD9E-FDF3-4026-ADA7-F5E7F38B47E9/backgroundMusic.mp3/PlaybackRate: 0.000000>>

**Comment by mynameisguy** [comment]
Having the same issue

**Comment by christophemenager** [comment]
Does anyone have an idea on this issue ? :)
Do someone know if codepush already worked with this library in a previous version ?
