### ISSUE TITLE
I can't close the background mode when my application is in the background

### ISSUE THREAD

**Issue by Cuervo20** [DoubleSymmetry/react-native-track-player#1048]
**Describe the bug**
The problem is when my application is in the background, I would like to see if there is any way to close the background mode since there is only the option to stop

**To Reproduce**
[
![image](https://user-images.githubusercontent.com/67650423/96353374-e77d0f80-1090-11eb-928e-03daf941af5c.png)
](url)
I would like the background mode to look something like this with an icon to close it

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
react-native: 0.63.2
What `react-native-track-player` version are you using?
1.2.3
Are you testing on a real device or in the simulator? Which OS version are you running?
Android 9.0
**Code**
        await TrackPlayer.updateOptions({
          stopWithApp: true,
          capabilities: [
            TrackPlayer.CAPABILITY_PLAY,
            TrackPlayer.CAPABILITY_PAUSE,
            TrackPlayer.CAPABILITY_STOP,
            TrackPlayer.CAPABILITY_JUMP_FORWARD,
            TrackPlayer.CAPABILITY_JUMP_BACKWARD,
          ],
          compactCapabilities: [
            TrackPlayer.CAPABILITY_PLAY,
            TrackPlayer.CAPABILITY_PAUSE
          ]
        });

**Comment by fritzfr** [comment]
Is this the same as this https://github.com/react-native-kit/react-native-track-player/issues/1010?
