### ISSUE TITLE
HLS support for ios

### ISSUE THREAD

**Issue by marcinkieruzel** [DoubleSymmetry/react-native-track-player#1051]
Hi, 
as I can see in docs RNTP doesn't support HLS streams in IOS. From my point of view – HLS is working but sometimes not stable. For example it crashes on TrackPlayer.stop. It's stable only when you use just play and pause controls. Do you plan to add full support for hls in IOS?

**Comment by asmmahmud** [comment]
W're also using the hls in our app which is in development without any issue so far.

**Comment by charneykaye** [comment]
Just chiming in that I have been having a %$#! time trying to get RNTP to play HLS on either Android or iOS. Maybe my stream is #%$@ since others seem to believe that this is supposed to work.

**Comment by bradleyflood** [comment]
Appears this is resolved? Thanks all
