### ISSUE TITLE
Using Xcode 12 can cause build failures

### ISSUE THREAD

**Issue by jasontproject** [DoubleSymmetry/react-native-track-player#1056]
**Describe the bug**
Using Xcode 12 to build a react native project that uses react-native-track-player can fail with several build problems.
For more details see https://github.com/facebook/react-native/issues/29633

Here is the required fix, within react-native-track-player.podspec:
```
-  s.dependency 'React'
+  s.dependency 'React-Core'
```
Also see https://github.com/facebook/react-native/issues/29633#issuecomment-694187116

**Comment by mikeislearning** [comment]
@jasontproject This fix didn't seem to work for me. Is there anything else you are supposed to do besides modify the podspec file?

I followed this guide [https://react-native-track-player.js.org/install/#ios-enable-swift-library-not-found-for--lswiftcoreaudio-for-architecture-x86_64](url) but it only allows it to work in the simulator. I'm not able to deploy it to the app store.
