### ISSUE TITLE
iOS Notification Disappears After Pausing 

### ISSUE THREAD

**Issue by davidsalib** [DoubleSymmetry/react-native-track-player#1058]
**Describe the bug**
When the app goes into background, then the audio is paused, it disappears from the background within 1 minute. 
The notification consistently disappears on iOS within a minute of the audio being paused.

**To Reproduce**
1. Play audio in app 
2. Background the app 
3. Pause the audio from notification 
4. Wait 1 min 
5. Notification disappears

**Environment (please complete the following information):**
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Memory: 31.82 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1

What `react-native-track-player` version are you using?
"react-native-track-player": "^1.2.3",

Are you testing on a real device or in the simulator? Which OS version are you running?
Real Device - iOS 13 

**Code**
Background Mode - no related code.

**Comment by puckey** [comment]
Did you test how other apps behave after pausing audio to make sure this is not standard iOS behaviour?

**Comment by davidsalib** [comment]
Yes, tested with Spotify. It stays well over 10 minutes after pausing.

**Comment by puckey** [comment]
Could you try setting `iosCategory` to `"playback"`: https://react-native-track-player.js.org/documentation/#lifecycle-functions

**Comment by JonahElbaz** [comment]
I have this issue, except as soon as I hit pause the controls completely disappear unless I go back into my app and hit play

**Comment by davidsalib** [comment]
@puckey, I tested `iosCategory: 'playback'` - didn't change anything. 
It's important to note that this only happens when the app is published on the store. 

If I make a Release build from Xcode, the notification persists. 

For now, I use a BackgroundTimer to play a silent 1 second MP3 file. This keeps the notification alive indefinitely until the app is closed - not ideal, but it works for now.

**Comment by davidsalib** [comment]
Has there been any thought for a fix here?

**Comment by rajpootathar** [comment]
Any solution to this issue?
Notification disappear after one min
