### ISSUE TITLE
Getting wrong duration and position of song in ios.

### ISSUE THREAD

**Issue by rahutwr33** [DoubleSymmetry/react-native-track-player#1063]
**Describe the bug**
Getting wron duration and position of song in ios.working fine in android

**To Reproduce**
React native 62

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
"react-native-track-player": "^1.1.4",
Are you testing on a real device or in the simulator? Which OS version are you running?
*Simulator and phone both
**Code**
 export const addplaylist = async (song, currentsongid) => {
  await TrackPlayer.reset();
  await TrackPlayer.add(song);
  const getsong = await new Promise(async (resolve, reject) => {
    TrackPlayer.skip(String(currentsongid)).then(() => {
      resolve({success: true});
    });
  });
  if (getsong.success) {
    await TrackPlayer.play().then((res) => {
      return {success: true};
    });
  }
};

**Comment by MJahanzaibKhan** [comment]
I'm also getting the wrong track player duration there is any solution?

**Comment by sandeepkundu4344** [comment]
any solution to this issue I am getting same bug in IOS for longer audios, if audio is longer than 30 mins or 1 hour then duration does not come correct, I attached a screenshot. I am version 1.2.7 of the track player
![Screenshot_2021-10-18_at_7 09 06_PM](https://user-images.githubusercontent.com/8801971/137852547-62ad7fd4-9bda-423c-a90a-94f6ba5d527b.png)

**Comment by Thomascogez** [comment]
@sandeepkundu4344 @MJahanzaibKhan @rahutwr33, I was actually facing the same issue on ios and struggle a lot with it, I solved it.
I stream audio from my own server and adding codec inside `Content-type` solved my issue !
(Example for mp4: `Content-type audio/mp4 codecs="mp4a.40.2"`). With that song length is correctly displayed in app and on control center 👍
Hope that can help to solve your issue

**Comment by fukemy** [comment]
it's really big problem, any solution?

**Comment by mattperls-code** [comment]
Having this issue too. Even when the Track Object is added with the correct duration, the lock screen player always has the wrong duration.

**Comment by marc4m** [comment]
Having this issue too. Anyone has any solution? I used v3.2.0

**Comment by tomasescobar** [comment]
This is also happening to me, but not always. It depends on the track, some tracks report the correct duration and skip to the correct seconds, and others when skipping to X seconds, fail to do so to the correct time, always having and offset.
Setting the duration in the Track objects makes no difference. I imagine it has something to do with the underlying iOS bridge library and code, but haven't isolated the origin of the issue yet.

**Comment by tomasescobar** [comment]
Looking into other libs, found this in Expo AV https://docs.expo.dev/versions/latest/sdk/av/#what-is-seek-tolerance-and-why-would-i-want-to-use-it-ios-only
It could be possible that this is the default behaviour in iOS based on https://developer.apple.com/documentation/avfoundation/avplayer/1387741-seek#discussion

If precision is important, we need to specify the tolerance with which the player will seek. There's no code to do so from this library, we would need to add support for this.

**Comment by nitinchavhanps2** [comment]
import TrackPlayer, { useProgress } from 'react-native-track-player'; //import useProgress

// Add this funtion

const formatTime = (seconds) => {
    const minutes = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${String(minutes).padStart(2, '0')}:${String(secs).padStart(2, '0')}`;
};

//return start time and end time duration

const ProgressDisplay = () => {
    const { position, duration } = useProgress();

    return (
        <View style={styles.progressLevelDuration}>
            <Text style={styles.progressLabelText}>
                {formatTime(position)}
            </Text>
            <Text style={styles.progressLabelText}>
                {formatTime(duration - position)}
            </Text>
        </View>
    );
};
