### ISSUE TITLE
iOS player stops after minimize

### ISSUE THREAD

**Issue by JonahElbaz** [DoubleSymmetry/react-native-track-player#1064]
I'm getting an issue on iOS where when I open the app, I add a bunch of songs to the queue and hit play. The first song plays. I then pause and minimize the app. I wait about 1 minute, then reopen the app and hit play again - nothing happens. The progress of the app doesn't go up, no audio comes out. If i check the notification bar i see the progress bar going and it says its playing but no audio is released.
This is issue is on iOS and only happens after the app is minimized for about a minute, otherwise after hours of trying, i cant reproduce it any other way.

I resolve this issue by skipping to the next track and everything starts up again.

**Environment (please complete the following information):**
```
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 819.48 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 26, 27, 28
      Build Tools: 27.0.3, 28.0.3
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_202 - /usr/bin/javac
    Python: 3.8.3 - /opt/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.14.0 => 16.14.0
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
`react-native-track-player ^1.2.3`
Testing on a real device: iPhone XR - 14.1

I'm not sure what code to share specifically to help with this. Let me know what would be helpful

Thanks in advance for any help! Really urgent!

**Comment by JonahElbaz** [comment]
Related to this: https://github.com/react-native-kit/react-native-track-player/issues/687

**Comment by JonahElbaz** [comment]
Issue #687 says that when the UI is brought back to the foreground it sends the `permanent` tag in with `remote-duck` this is true (and unexpected) when the audio is paused. However if i don't bring it back to the foreground, that doesn't get triggered, but if i try and play the audio from the notification controls (which are still visible and accurate), the progress starts but no audio comes out (and when i hit pause, the progress that was made is undone).

This is very odd behaviour and im still not sure how to handle it, i could really use some help.

**Comment by JonahElbaz** [comment]
As it turns out this only occurs with HLS. If i use an mp3 hosted file everything works as expected, similarly everything is currently working as expected on android. So this seems to be related to the instability of HLS

**Comment by nullmu0** [comment]
I use (react-native-track-player@next) IOS will pause when minimized
