### ISSUE TITLE
State == Ready while playing

### ISSUE THREAD

**Issue by davidsalib** [DoubleSymmetry/react-native-track-player#1067]
**Describe the bug**
After calling `.play()` on the audio, when I check the state using `.getState()`, it returns `TrackPlayer.STATE_READY`.

In this screenshot, `playing podcast` is logged when the podcast plays, `playbackstate` comes from the event listener on `playback-state`, and `new state is ready` is logged 500ms after the state is set to ready. I thought maybe after 500ms the state would definitely be `TrackPlayer.STATE_PLAYING`, however it is still ready.
![image](https://user-images.githubusercontent.com/10209934/98458281-f8cfae00-215c-11eb-8306-70808cc74253.png)

**To Reproduce**
1. Play an audio file
2. Reset the TrackPlayer
3. Play another audio file
4. Sometimes the state sticks to "ready"

**Environment (please complete the following information):**
System:
OS: macOS 10.15.5
CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
Memory: 31.82 MB / 16.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 12.18.2 - /usr/local/bin/node
npm: 6.14.5 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
IDEs:
Android Studio: 4.0 AI-193.6911.18.40.6514223
Xcode: 11.7/11E801a - /usr/bin/xcodebuild
npmPackages:
react: 16.9.0 => 16.9.0
react-native: 0.61.1 => 0.61.1

What react-native-track-player version are you using?
"react-native-track-player": "^1.2.3",

Are you testing on a real device or in the simulator? Which OS version are you running?
Real Device - iOS 13

**Comment by fritzfr** [comment]
Can confirm, having the same issue. @davidsalib

**Comment by uzegonemad** [comment]
I added a workaround in SwiftAudio using patch-package, which has seemed to work so far.

```diff
diff --git a/node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/SwiftAudio/Classes/AVPlayerWrapper/AVPlayerWrapper.swift b/node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/SwiftAudio/Classes/AVPlayerWrapper/AVPlayerWrapper.swift
index d17c936..acddef1 100755
--- a/node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/SwiftAudio/Classes/AVPlayerWrapper/AVPlayerWrapper.swift
+++ b/node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/SwiftAudio/Classes/AVPlayerWrapper/AVPlayerWrapper.swift
@@ -134,6 +134,11 @@ class AVPlayerWrapper: AVPlayerWrapperProtocol {
 
     func play() {
         avPlayer.play()
+
+         // workaround for state staying in ready state
+        if self._state == .ready {
+            self._state = .playing
+        }
     }
 
     func pause() {
```

**Comment by ronal2s** [comment]
Facing the same issue in version 3.1.0
