### ISSUE TITLE
[Android] - Crash - android.app.RemoteServiceException Crash - IllegalStateException (MusicModule.waitForConnection)

### ISSUE THREAD

**Issue by dungle27** [DoubleSymmetry/react-native-track-player#1070]
Hello,
I'm using latest version: 1.2.3
But I still get errors:
-  Crash - android.app.RemoteServiceException
- Crash - IllegalStateException (MusicModule.waitForConnection)

I checked it fixed by : https://github.com/react-native-kit/react-native-track-player/pull/903
But dev branch seem not yet fix it.

Please help me resolve this problem
thanks!

**Comment by Bang9** [comment]
https://github.com/soundgym/react-native-track-player/commit/ea3909d5771287b18ad72c82f59befef535d05bf
this line should be fix your issue, check the repo
