### ISSUE TITLE
[iOS] Playback issues with CAF Opus files (wrong state reported)

### ISSUE THREAD

**Issue by fritzfr** [DoubleSymmetry/react-native-track-player#1071]
**Describe the bug**
There is an issue with the `playback-state` reporting when scrubbing/seeking through somewhat larger .caf opus files.

Example:
You tap on a 1 hour long track, it starts playing. Then you scrub to like 95% of the length, the state will change from `paused` to `playing` immediately, **but nothing is playing**. It takes another 5-10 seconds or so for it to actually start playing. When it does, there is no new `playback-state` update. I can reproduce this 100% of the time.

If I switch out the caf file for an MP3 file (same length, same audio content), this is not a problem.

**To Reproduce**
1. Get hold of a somewhat bigger opus encoded caf file, or take mine as an example (`https://cdn.voicehub.dev/snippets/caf/5fae559cb7178d7ce5ec037e.caf`).
2. Start Playing, the `playback-state` event listener will report in this order: `loading, ready, buffering, playing` and it will start playing.
3. Scrub to almost the end, it will report `paused, playing`, but nothing is playing for another few seconds.

**Environment (please complete the following information):**
```
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 158.61 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.4 - /usr/local/opt/node@12/bin/node
    Yarn: Not Found
    npm: 6.14.6 - /usr/local/opt/node@12/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.1 => 0.63.1 
  npmGlobalPackages:
    *react-native*: Not Found
```
What `react-native-track-player` version are you using? 1.2.3
Are you testing on a real device or in the simulator? Which OS version are you running? iOS 14, both Sim and Device

**Comment by chrisvire** [comment]
Is your opus audio inside the caf file variable bitrate (VBR) or constant bitrate (CBR)? Is it different than the mp3?  To me, if you are having issues with scrubbing, it might have to do with how the time to byte offset is calculated. We force CBR on our audio files so we don't run into this issue.
