### ISSUE TITLE
iOS: usePlaybackState returns paused on skip to id

### ISSUE THREAD

**Issue by Johkade** [DoubleSymmetry/react-native-track-player#1079]
**Describe the bug**
When player is playing a track in the queue and the function Trackplayer.skip(<id>) is called, the playbackstate passes all these states in about 500ms:

[Sun Nov 29 2020 10:21:12.124]  LOG      state:  paused
[Sun Nov 29 2020 10:21:12.220]  LOG      state:  loading
[Sun Nov 29 2020 10:21:12.309]  LOG      state:  paused
[Sun Nov 29 2020 10:21:12.404]  LOG      state:  ready
[Sun Nov 29 2020 10:21:12.494]  LOG      state:  buffering
[Sun Nov 29 2020 10:21:12.789]  LOG      state:  playing

The same happens for skipToPrevios and skipToNext

In my PlayButtonComponent I show play/pause depending on usePlaybackState.
The above sequence makes the button's icon (play/pause) flicker on each skip()-call.

**Expected Behavior**
usePlaybackState passes only these states when skipping to another track:
STATE_PLAYING (skip) -> STATE_BUFFERING -> STATE_PLAYING

((these are the states passed on Android on Trackplayer.skip(<someId>)

**To Reproduce**
usePlaybackState on iOS (works as expected on android)
execute TrackPlayer.skip(<someIdInQueue>)

**Environment (please complete the following information):**
react native 0.63, react-native-track-player - 1.2.3. Platform is iOS

**Comment by dev-apps-code** [comment]
any updates on this?
