### ISSUE TITLE
Song isnt staring in samsung and xiomi device

### ISSUE THREAD

**Issue by kaneki666** [DoubleSymmetry/react-native-track-player#1081]
same code works on my pixel device..but its not working o Samsung s9,, i am consoling the song its there but not working in Samsung  but working properly in pixel 2

      

  useEffect(() => {
    setup().then((res) => togglePlayback());
  }, []);

        async function setup() {
    await TrackPlayer.setupPlayer({});
    await TrackPlayer.updateOptions({
      stopWithApp: true,
      capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
        TrackPlayer.CAPABILITY_STOP,
      ],
      compactCapabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
      ],
    });
  }

  async function togglePlayback() {
    const currentTrack = await TrackPlayer.getCurrentTrack();

    if (currentTrack == null) {
      await TrackPlayer.reset();

      await TrackPlayer.add({
        id: `${song.id}`,
        url: `file://${song.path}`,
        title: `${song.title}`,
        artist: `${song.artist}`,
        artwork: `${song.cover}`,
      });
      await TrackPlayer.play();
    } else {
      if (songstate === TrackPlayer.STATE_PAUSED) {
        await TrackPlayer.play();
      } else {
        await TrackPlayer.pause();
      }
    }
    await TrackPlayer.updateOptions({
      stopWithApp: true,
    });
  }

**Comment by alan-dx** [comment]
I found the same problem, do you have find any solution? The app don't work on xiaomi devices, It starts the track but closes right away.
