### ISSUE TITLE
remote-duck event is not called on instagram

### ISSUE THREAD

**Issue by fpgce** [DoubleSymmetry/react-native-track-player#1083]
remote-duck event is called only one time:
1- when i play some instagram audio

On IOS the event is called four times:
1- when i play some audio on chat 
2- when audio is finished or paused
3- when i start audio rec into chat
4- when i finish audio rec into chat

The problem is only in Instagram. i`m use in another apps how Telegram and Whatsapp and works fine, thanks.

**To Reproduce**
first you need setup track player
```
TrackPlayer.setupPlayer, {
    waitForBuffer: Platform.OS === 'ios',
    stopWithApp: true,
    playBuffer: 1,
    alwaysPauseOnInterruption: false,
  });
```
second you need create eventListener remote-duck:
```
TrackPlayer.addEventListener(
      'remote-duck',
      props=> console.log(props),
    );
```
 
**Environment (please complete the following information):**
    "react-native-track-player": "^1.2.3",

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 71.26 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.14.0 - ~/.nvm/versions/node/v14.14.0/bin/node
    Yarn: 1.22.5 - ~/dev/usabit/cbn-react-native-app/node_modules/.bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-19 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

**Comment by shiroze** [comment]
![image](https://user-images.githubusercontent.com/6022114/107005546-6cb43d80-67c2-11eb-9c88-3a30de6bdc85.png)
Work fine for me on instagram and youtube.
for now im testing autoplay after no audio play
