### ISSUE TITLE
playback-metadata-received

### ISSUE THREAD

**Issue by KrimskiyMaxim** [DoubleSymmetry/react-native-track-player#1085]
Hello. Hi. can't get "playback-metadata-received" to work. Could you please show an example
 
`playback-metadata-received is not a supported event type for RNTrackPlayer. Supported events are: playback-queue-ended, playback-state, playback-error, playback-track-changed, remote-stop, remote-pause, remote-play, remote-duck, remote-next, remote-seek, remote-previous, remote-jump-forward, remote-jump-backward, remote-like, remote-dislike, remote-bookmark`

**Comment by kenshinman** [comment]
Hey, @KrimskiyMaxim Thanks for the work you are doing here. Has this been fixed? I have the same bug

**Comment by Tavernari** [comment]
Same here! 
I am trying to get the metadata with this event and I am getting the same error here.
