### ISSUE TITLE
Set position for streaming source

### ISSUE THREAD

**Issue by PiR1** [DoubleSymmetry/react-native-track-player#1086]
**Is your feature request related to a problem? Please describe.**
I want to make a player for a webradio. So, when you go on open the stream the position in the music is not at 0.
There no way to set up the position.

**Describe the solution you'd like**
I want to pass the position to the `useTrackPlayerProgress` hook or to have a method: `setProgress`.

**Describe alternatives you've considered**
I'm open to other suggestions

**Additional context**
None

**Comment by josh-deprogram** [comment]
you should be able to use the `.seekTo(position)` method for this use case, call this immediately after or before play

**Comment by bgoldsworthy** [comment]
You cannot .seek right away. It does not register and starts the track from the beginning.
I don't know why this bug was closed.
https://github.com/DoubleSymmetry/react-native-track-player/issues/1157

**Comment by bgoldsworthy** [comment]
I see it was closed proactively because this PR seemed ready, though it hasn't been merged yet
https://github.com/DoubleSymmetry/react-native-track-player/pull/713

**Comment by bgoldsworthy** [comment]
Oh, I see, it was closed proactively because this PR seemed ready, though it hasn't been merged yet
https://github.com/DoubleSymmetry/react-native-track-player/pull/713

**Comment by bradleyflood** [comment]
Thanks everyone. I've added this to our high priority list and I'll discuss it with some more of the contributors.

Hopefully we can get this PR merged or the topic reviewed in general. 

I'm going to close with Issue as we have several locations of tracking this now.

Thank you !

https://github.com/DoubleSymmetry/react-native-track-player/issues/1157
https://github.com/DoubleSymmetry/react-native-track-player/issues/1157
