### ISSUE TITLE
Pass AVAudioSessionInterruptionWasSuspendedKey to remote-duck event

### ISSUE THREAD

**Issue by gilbertl** [DoubleSymmetry/react-native-track-player#1088]
**Is your feature request related to a problem? Please describe.**
As per this thread, iOS will send remote-duck event with AVAudioSessionInterruptionWasSuspendedKey key to app if the app was suspended and is now resuming audio.

https://stackoverflow.com/questions/39184859/avplayer-audiosessiongotinterrupted-notification-when-waking-up-from-background

Not being able to detect this is problematic because - as per thread - if the app

1. goes to background
2. pauses audio
3. gets suspended
4. plays audio (through lock screen play button)

then a remote-play event will be immediately followed by remote-duck event

Without AVAudioSessionInterruptionWasSuspendedKey, our app currently pauses the audio again after briefly playing it. 

**Describe the solution you'd like**
react-native-track-player should either handle the AVAudioSessionInterruptionWasSuspendedKey key in the code, or pass that info along downstream

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bradleyflood** [comment]
@gilbertl is this still relevant in v2?

Closing for now if not. Thank you :)
