### ISSUE TITLE
Chromecast for iOS

### ISSUE THREAD

**Issue by JakeMotta** [DoubleSymmetry/react-native-track-player#1095]
Hi! Scrubbing through the docs, I see that Chromecast support has been implemented for Android, but not yet for iOS. Is there any plan for this happening soon? There doesn't seem to be a lot of (active) Chromecast discussion on this repo.

**Comment by Anjasomc** [comment]
It looks like this library doesn't support Chromecast, despite what the [docs](https://react-native-track-player.js.org/cast/) say. The [react-native-track-casting](https://github.com/react-native-kit/react-native-track-player/issues/230#issuecomment-405033928) library was started to support Chromecast, but [seems to have stalled](https://github.com/react-native-kit/react-native-track-casting/issues/1]).

**Comment by JakeMotta** [comment]
Another question related to this. I implemented react-native-google-cast on top of react-native-track-player (RNTP). With RNTP, I'm able to still have my JS run in the background so that I can send / receive POST requests, which are critical to my app. But after implementing Google Cast, the background audio from RNTP is killed if I try to have RNTP audio while my device is locked (if GC is active). 

**What I Want:**
My app to keep playing audio in the background from RNTP, while also casting to a device using react-native-google-cast. RNTP is needed so I can keep my app alive in background and get updates from my server. (_Note_: This logic is working w/ RNTP alone)

**What's Happening**
If I connect to a device using react-native-google-cast, then lock my phone, the actively playing RNTP track will stop playing, as if the audio being overridden by react-native-google-cast, even though my app is just supplying music for Google Cast receiver, not actually playing it, so there shouldn't be a conflicting audio source (I'd imagine). 

Any ideas on why this may be occurring? I've tried digging through Git issues all over, and the docs, but can't really find any solid leads to this...

**Comment by neoassyrian** [comment]
> Another question related to this. I implemented react-native-google-cast on top of react-native-track-player (RNTP). With RNTP, I'm able to still have my JS run in the background so that I can send / receive POST requests, which are critical to my app. But after implementing Google Cast, the background audio from RNTP is killed if I try to have RNTP audio while my device is locked (if GC is active).
> 
> **What I Want:**
> My app to keep playing audio in the background from RNTP, while also casting to a device using react-native-google-cast. RNTP is needed so I can keep my app alive in background and get updates from my server. (_Note_: This logic is working w/ RNTP alone)
> 
> **What's Happening**
> If I connect to a device using react-native-google-cast, then lock my phone, the actively playing RNTP track will stop playing, as if the audio being overridden by react-native-google-cast, even though my app is just supplying music for Google Cast receiver, not actually playing it, so there shouldn't be a conflicting audio source (I'd imagine).
> 
> Any ideas on why this may be occurring? I've tried digging through Git issues all over, and the docs, but can't really find any solid leads to this...

I would raise this with react-native-google-cast. They might need to add similar feature for getting calls when the UI is not mounted or the screen is locked.

**Comment by bradleyflood** [comment]
Thanks everyone. I've added a feature request for review in our Project, and I'll discuss it with the team.

**Comment by jspizziri** [comment]
Related to this issue https://github.com/doublesymmetry/react-native-track-player/issues/1095
