### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by maartenvandillen** [DoubleSymmetry/react-native-track-player#1096]
**Describe the bug**
Sometimes everything works fine, but sometimes the app crashes with the following exception:

E/RNTrackPlayer: An error occurred while destroying the service
    java.lang.IllegalArgumentException: Receiver not registered: com.guichaguri.trackplayer.service.MusicManager$1@836bd04
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1489)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1708)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:733)
        at com.guichaguri.trackplayer.service.MusicManager.destroy(MusicManager.java:350)
        at com.guichaguri.trackplayer.service.MusicService.destroy(MusicService.java:56)
        at com.guichaguri.trackplayer.service.MusicBinder.destroy(MusicBinder.java:53)
        at com.guichaguri.trackplayer.module.MusicModule.destroy(MusicModule.java:168)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:246)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:923)

**To Reproduce**
Project is setup following all instructions. Player works fine, but after hitting my start / stop button a couple of times (sometimes 2, sometimes 4 or 5) it crashes with an exception (see above).

**Environment (please complete the following information):**
10:19 $ react-native info
info
  React Native Environment Info:
    System:
      OS: macOS 10.15.7
      CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
      Memory: 63.66 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.3, 29.0.0, 29.0.2
        System Images: android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2

What `react-native-track-player` version are you using?
    "react-native-track-player": "^1.2.3",

Are you testing on a real device or in the simulator? Which OS version are you running?
Real Android device, Samsung Galaxy S20+

**Code**
  onPlayPress = () => {
    const { status } = this.state

    console.log("onPlayPress", status)

    if (status == Status.Playing) {
      //currently playing, stop player
      this.setState({ status: Status.Stopped })
      TrackPlayer.stop()
      TrackPlayer.destroy()
      console.log("onPlayPress", Status.Stopped)
    } else {
      //currently not playing, start player
      TrackPlayer.setupPlayer({ waitForBuffer: true }).then(() => {
        console.log("TrackPlayer initialized")
        //init remote controls
        TrackPlayer.updateOptions(playerOptions)
        console.log(playerOptions)
        //add url
        const track = this.createTrack(this.props.bitrateHigh)
        TrackPlayer.add(track).then(() => {
          console.log("track added", track)
          //start playing
          this.setState({ status: Status.Playing })
          TrackPlayer.play()
          console.log("status", Status.Playing)
          this.refresh()
        })
      })
    }
  }

**Comment by mrigo** [comment]
Same here. Any solution?

**Comment by anarthal** [comment]
I've also encountered this issue. Tracking down to the Java code, I've proposed a workaround in this PR: https://github.com/react-native-kit/react-native-track-player/pull/1167

**Comment by mohity777** [comment]
I am facing this issue too.

**Comment by mohity777** [comment]
Any Update?

**Comment by anarthal** [comment]
We're running a fork of this project with the PR applied and haven't found any crash yet.

**Comment by mohity777** [comment]
I tried your solution , added try/catch on destroy but still  still having crashes like  An error occurred while unregistering the noisyReceiver:   java.lang.IllegalArgumentException: Receiver not registered: com.guichaguri.trackplayer.service.MusicManager$1@442d25c.

Also if i setUpPlayer and destroy multiple times,  setUpPlayer stops working.

**Comment by mohity777** [comment]
Now it is not crashing any more, I was reseting player using TrackPlayer.reset after TrackPlayer.setUpPlayer. After moving TrackPlayer.reset before TrackPlayer.setUpPlayer and also making the changes that @anarthal suggested , it  stopped crashing.

**Comment by freudibili** [comment]
I'm facing the same issue. It crashed after the second time. I tried what you suggest @mohity777 & @anarthal but crashes are still here

**Comment by mohity777** [comment]
Bro, It still crashing for me also, But it is not as often as earlier.

**Comment by mohity777** [comment]
It should not be closed either.

**Comment by kioopi** [comment]
Is there a workaround or an update coming or why is this closed?

**Comment by dcvz** [comment]
Can someone confirm whether this is still an issue on v2?

**Comment by mattiaefesto** [comment]
I can confirm this is still an issue on v2!

**Comment by dcvz** [comment]
I've reopened the issue! We're looking at Android stability and crashes on our current Android rewrite beta. I'd appreciate if any of you are able to give it a spin and see if that's an issue there. 

I want to fix and prioritize as many crashes as I can as part of that effort.

**Comment by ramisalem** [comment]
Same here, I am getting the issue in production

here is the report from firebase crashlytics 
 

![Screenshot 2021-12-20 at 2 32 52 PM](https://user-images.githubusercontent.com/25037017/146741016-815bee5f-c68f-4362-a07f-b9989dcc0bf2.png)

**Comment by bradleyflood** [comment]
Thank you everyone. We are doing a major rewrite on the android side, please see the discussion here https://github.com/DoubleSymmetry/react-native-track-player/discussions/1264

We would love your help to test it. The above problems should be resolved in these updates. Please let us know!
