### ISSUE TITLE
Ios Mpeg format 

### ISSUE THREAD

**Issue by nagaraj95** [DoubleSymmetry/react-native-track-player#1103]
**Describe the bug**
 While trying to play the mpeg format in iOS the player is not supporting and in android it is working perfectly
. The response of the state is either { state: 'loading' } or { state: 'buffering' }. Please post some answer. Thanks in advance @puckey @dcvz @Guichaguri

**Environment (please complete the following information):**
I have tested through simulator and real device.

**Code**
             ```
               const trackplayerDetails = {
                   id: item.unique_id,
                    url: "file://" + audioFile,
                    title: 'Title',
                    artist: "Sample",
             }
                await TrackPlayer.add(trackplayerDetails);
                await TrackPlayer.play();
                ```

**Comment by dcvz** [comment]
@nagaraj95 can you attach a sample project with the url of the item in question?
