### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by vyancharuk** [DoubleSymmetry/react-native-track-player#1105]
Hello, 
Looks like this project is not supported yet.
@Guichaguri @dcvz could you share your thoughts and plans for `react-native-track-player`? There are plenty open issues and open PRs. Do you plan to add other maintainers with necessary rights for this repo? Also, I'm curious about potential release dates?
Thanks in advance!

**Comment by rdhox** [comment]
Up for this issue. This library seems used by lot of people, sure we can add other maintainers to help.
Thanks!

**Comment by JakeMotta** [comment]
Likewise. This is a great library, but haven't seen any real updates in a while.

**Comment by Guichaguri** [comment]
Not currently. I'd love to get back into maintaining the module, but I don't have enough time for it.

Either way, I think we should add new maintainers, the project has got really big, there are a lot of issues open and pull requests not reviewed, and even if all current maintainers were active, it would take months for us to work on all of these.

**Comment by maendamedia** [comment]
I think indeed that it would be wise to get some more maintainers, as we have a lot of apps running with this module (which is really great), but most of them see issues when updating the iOS versions etc. Updating the module does not fix it then, so we need to check for alternatives and that is not easy .

**Comment by pabloromeu** [comment]
Could you simply add a "call for maintainers" at the README? Or add permissions to volunteers?

**Comment by gavrichards** [comment]
Please could we have some clarification around the status of this project? I can see an update has been released in the last hour (which is very welcome) by @curiousdustin who earlier in this thread said they don't have any time to spare anymore. I rely on this project for my app but I don't feel I have much confidence in it from this mixed messaging. Thanks!

**Comment by curiousdustin** [comment]
I understand the concern @gavrichards. 

As for today's release, there were quite a few minor updates that had been completed by various people over the past 10 months, but never released. I found enough time to compile those into a release.

Unfortunately, I still will not be able to pay a large amount of attention to this project for the foreseeable future.

**Comment by gavrichards** [comment]
Thanks for the clarification @curiousdustin. Would you consider the idea of widening the pool of maintainers or soliciting for help on the readme?

**Comment by curiousdustin** [comment]
Yes, I believe we would be open to that.

However, this would really be up to @Guichaguri who is the founder of this project. I have only helped out relatively recently, and to a relatively small degree.

**Comment by gavrichards** [comment]
That's great to hear. I wish I was more qualified but sadly I know very little about the native code side of things. Hopefully there will be some willing volunteers.

**Comment by vyancharuk** [comment]
Thanks, @curiousdustin for recent releases, would be great to see more releases soon!

**Comment by vyancharuk** [comment]
Hello @Guichaguri @curiousdustin, do you mind adding `help wanted` topic to repository https://github.com/topics/help-wanted, so it will be visible for potential maintainers? Also would be great to have a similar section in readme https://github.com/austinhuang0131/barinsta#we-need-maintainers, along with contributors below?
