### ISSUE TITLE
[android] unable to resume track or play another track after first track 

### ISSUE THREAD

**Issue by Karanchamp** [DoubleSymmetry/react-native-track-player#1108]
unable to resume track or play another track after first track 
First track work perfect

System:
    OS: macOS 11.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 51.09 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.5.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.3.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 

react-native-track-player  version  :      "react-native-track-player": "^1.2.3",

Code: 
import TrackPlayer from 'react-native-track-player';

TrackPlayer.play()

**Comment by Goden4you** [comment]
Can you add more code? I think, you just didn't add tracks to the queue

**Comment by Karanchamp** [comment]
I already add track to the queue before calling play function 

//add tracks using below code 
TrackPlayer.add(data)

**Comment by AdamSheaHewett** [comment]
I am getting this problem as well, only on iOS.

It seems that when stop() is called on iOS it flushes the queue.

Or it could be something else. After stop() is called there is a state change event and it registers as State.None.

**Comment by AdamSheaHewett** [comment]
Ok I just confirmed that it does indeed empty the queue on iOS when TrackPlayer.stop() is called.

**Comment by Atom54** [comment]
@AdamSheaHewett Did you find a fix in the end ?
We have the exact same problem on iOS as well ..

**Comment by AdamSheaHewett** [comment]
@Atom54 no I am still using the workaround I posted

**Comment by Atom54** [comment]
Ok thank you @AdamSheaHewett !
I checked your profile and discovered that you're the creator of the brain.fm app 🤩  
I've been using it for years, I'm one of your subscribers ! It really improves my focus, thank you for the awesome work!

**Comment by AdamSheaHewett** [comment]
> Ok thank you @AdamSheaHewett !
> I checked your profile and discovered that you're the creator of the brain.fm app 🤩  
> I've been using it for years, I'm one of your subscribers ! It really improves my focus, thank you for the awesome work!

Thanks so much! Glad you like my work
