### ISSUE TITLE
Android - Notification Controls not Works

### ISSUE THREAD

**Issue by shiroze** [DoubleSymmetry/react-native-track-player#1114]
**Describe the bug**
Android Notification Controls not working as expected when using **waitforBuffer** and **alwaysPauseOnInterruption**

**To Reproduce**
Play and pause music from notification, and I want implement remote-ducks for music play.

**Environment (please complete the following information):**

> 
>     "react": "16.13.1",
>     "react-native": "0.63.2",
>     "react-native-track-player": "github:puckey/react-native-track-player#ios-playback-metadata-received",
> 

**Code**
This code works normally without problem.

```
yield call(TrackPlayer.setupPlayer);

  // TrackPlayer.setupPlayer({
  //   waitForBuffer: true,
  //   iosCategory: 'playback',
  // });

  TrackPlayer.updateOptions({
    stopWithApp: true,
    // alwaysPauseOnInterruption: false,
    capabilities: [TrackPlayer.CAPABILITY_PLAY, TrackPlayer.CAPABILITY_PAUSE],
    notificationCapabilities: [
      TrackPlayer.CAPABILITY_PLAY,
      TrackPlayer.CAPABILITY_PAUSE,
    ],
    compactCapabilities: [
      TrackPlayer.CAPABILITY_PLAY,
      TrackPlayer.CAPABILITY_PAUSE,
    ],
  });
```

**Comment by devWaleed** [comment]
I have the following code in componentDidMount of a component:


`
TrackPlayer.setupPlayer().then(() => {

				TrackPlayer.add({
					url: 'http://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3',
					title: 'Avaritia',
					artist: 'deadmau5',
					album: 'while(1<2)',
					genre: 'Progressive House, Electro House',
					date: '2014-05-20T07:00:00+00:00', // RFC 3339
				});

				TrackPlayer.play();

			});

			TrackPlayer.updateOptions({
				capabilities: [TrackPlayer.CAPABILITY_PLAY, TrackPlayer.CAPABILITY_PAUSE],
				notificationCapabilities: [
					TrackPlayer.CAPABILITY_PLAY,
					TrackPlayer.CAPABILITY_PAUSE,
					TrackPlayer.CAPABILITY_STOP
				],
				compactCapabilities: [
					TrackPlayer.CAPABILITY_PLAY,
					TrackPlayer.CAPABILITY_PAUSE,
					TrackPlayer.CAPABILITY_STOP
				],
			});

			TrackPlayer.addEventListener('remote-play', () => TrackPlayer.play());

			TrackPlayer.addEventListener('remote-pause', () => TrackPlayer.pause());

			TrackPlayer.addEventListener('remote-stop', () => {
				TrackPlayer.destroy();
				console.log('test');
			});
`

Clicking on pause or stop doesnt work from notification

**Comment by WNemencha** [comment]
NotiOn my sode, notifications works well with almost the same code. I just don't have the ''notificationCapabilities''.

![Screenshot_20210212_213131_com.muzify.jpg](https://user-images.githubusercontent.com/40295432/108267901-181ea400-716c-11eb-81ab-9fe3f4208b04.jpg)

**Comment by shiroze** [comment]
> On my side, notifications works well with almost the same code. I just don't have the ''notificationCapabilities''.
> 
> ![Screenshot_20210212_213131_com.muzify.jpg](https://user-images.githubusercontent.com/40295432/108267901-181ea400-716c-11eb-81ab-9fe3f4208b04.jpg)

wow it's work. Thanks, notificationCabilities may be the problem.

**Comment by shiroze** [comment]
> On my side, notifications works well with almost the same code. I just don't have the ''notificationCapabilities''.
> 
> ![Screenshot_20210212_213131_com.muzify.jpg](https://user-images.githubusercontent.com/40295432/108267901-181ea400-716c-11eb-81ab-9fe3f4208b04.jpg)

still not working, I'm Changed the code become this

```
TrackPlayer.updateOptions({
    stopWithApp: true,
    alwaysPauseOnInterruption: true,
    capabilities: [TrackPlayer.CAPABILITY_PLAY, TrackPlayer.CAPABILITY_PAUSE],
    compactCapabilities: [
      TrackPlayer.CAPABILITY_PLAY,
      TrackPlayer.CAPABILITY_PAUSE,
    ],
  });
```

**Comment by WNemencha** [comment]
Here's what I'm doing on my side:

```js
export const TRACK_PLAYER_CONTROLS_OPTS = {
  ratingType: TrackPlayer.RATING_HEART,
  capabilities: [
    TrackPlayer.CAPABILITY_PLAY,
    TrackPlayer.CAPABILITY_PAUSE,
    TrackPlayer.CAPABILITY_STOP,
    TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
    TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
    TrackPlayer.CAPABILITY_SEEK_TO,
  ],
  compactCapabilities: [
    TrackPlayer.CAPABILITY_PLAY,
    TrackPlayer.CAPABILITY_PAUSE,
    TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
    TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
  ],
};

// In my redux actions
await TrackPlayer.updateOptions(TRACK_PLAYER_CONTROLS_OPTS);
```

**Comment by shiroze** [comment]
> Here's what I'm doing on my side:
> 
> ```js
> export const TRACK_PLAYER_CONTROLS_OPTS: MetadataOptions = {
>   ratingType: TrackPlayer.RATING_HEART,
>   capabilities: [
>     TrackPlayer.CAPABILITY_PLAY,
>     TrackPlayer.CAPABILITY_PAUSE,
>     TrackPlayer.CAPABILITY_STOP,
>     TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
>     TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
>     TrackPlayer.CAPABILITY_SEEK_TO,
>   ],
>   compactCapabilities: [
>     TrackPlayer.CAPABILITY_PLAY,
>     TrackPlayer.CAPABILITY_PAUSE,
>     TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
>     TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
>   ],
> };
> 
> // In my redux actions
> await TrackPlayer.updateOptions(TRACK_PLAYER_CONTROLS_OPTS);
> ```
> 
> EDIT: Are you sure you correctly linked the `react-native-track-player` module in your Android native code (should auto link normally, if you use React 0.60+)

if you use the code like mine it works normally without problem, but if you add `alwaysPauseOnInterruption: true,` your notification controls not working.

**Comment by WNemencha** [comment]
Yeah because `alwaysPauseOnInterruption: true` isn't part of the `MetadataOptions` type. I think this should goes to the initial `setupPlayer(opts)` options instead.

**Comment by shiroze** [comment]
> Yeah because `alwaysPauseOnInterruption: true` isn't part of the `MetadataOptions` type. I think this should goes to the initial `setupPlayer(opts)` options instead. Or the typings are out-of-date, maybe.

okay gonna try some and report what I found.
I was following this [doc](https://react-native-track-player.js.org/documentation/#player-functions)

**Comment by ramsuthar305** [comment]
For v2.1 putting foreground permission worked for me. Put below line in your AndroidManifest.xml file
`<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />`

**Comment by amirbhz86** [comment]
notification controller wasnt working for me
and it solved with create service file for control remote action

fallow this steps 
http://react-native-track-player.js.org/getting-started/#example-1

**Comment by dalugoda** [comment]
Had the same problem and solved it by adding the following code to the track service file as mentioned in the documentation.

`// This needs to go right after you register the main component of your app
// AppRegistry.registerComponent(...)
TrackPlayer.registerPlaybackService(() => require('./service'));`

`// service.js
module.exports = async function() {

    TrackPlayer.addEventListener('remote-play', () => TrackPlayer.play());

    TrackPlayer.addEventListener('remote-pause', () => TrackPlayer.pause());

    TrackPlayer.addEventListener('remote-stop', () => TrackPlayer.destroy());

    // ...

};`

**Comment by araujobarret** [comment]
Changing the Manifest file worked for my case, was stuck with the same issue.

Should we update the official docs to add this extra Android step?

**Comment by saravanakumargn** [comment]
We should register `registerPlaybackService` service as per doc here. https://github.com/doublesymmetry/react-native-track-player/blob/main/example/index.js#L9
