### ISSUE TITLE
iOS not playing audio without .mp3 extension 

### ISSUE THREAD

**Issue by Shadabhussainjaani** [DoubleSymmetry/react-native-track-player#1115]
**Describe the bug**
react-native-track-player play ("http://russprince.com/hobbies/files/13%20Beethoven%20-%20Fur%20Elise.mp3) but not playing ("https://r8---sn-gwpa-w5pd.googlevideo.com/videoplayback?expire=1612542107&ei=OxwdYLisJYn54-EP05Ga4Ac&ip=49.36.246.217&id=o-AHO45l9qySv7aCBt9AukI9_dQHVRn9iZajwJheSkcchC&itag=251&source=youtube&requiressl=yes&mh=n1&mm=31%2C29&mn=sn-gwpa-w5pd%2Csn-gwpa-qxaz&ms=au%2Crdu&mv=m&mvi=8&pl=21&initcwndbps=221250&vprv=1&mime=audio%2Fwebm&ns=Udm9Rm8v7DmSKnDZVRcf5mgF&gir=yes&clen=3761304&dur=224.781&lmt=1570326551315696&mt=1612520200&fvip=8&keepalive=yes&c=WEB&txp=5531432&n=hI4oRekcy3AD14ZqG&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgT4Xqk1xevDCwStjZWLUVJfw8Brd7tBl0qyE68Dy4bR4CIQD8yxzVQvnTrcvTXhCpk4D8778d6wL7r-hBiXWdegmNTw%3D%3D&ratebypass=yes&sig=AOq0QJ8wRQIgUHHtEVMwh41hPUm0jdS484PuBjI4Liz6WEo2LM35PwMCIQC4dxUEpCXbHv8DXzbew-nNMH9LkzbvnHrQl6K5Y74Mkg%3D%3D").

**To Reproduce**

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
What `react-native-track-player` version are you using?
Are you testing on a real device or in the simulator? Which OS version are you running?

**Code**
Please, share the code that is causing the issue

**Comment by WNemencha** [comment]
Cannot confirm this. I've been successfully streaming audio/mp3 and audio/mp4 mime types without any extension. Make sure the Google video link is serving the correct Content-Type header, and if it does not, you'll need to stream from a custom backend (node/express is pretty good for that) while adding the required headers by yourself.

**Comment by jossydeleon** [comment]
@Shadabhussainjaani Did u solve it?
