### ISSUE TITLE
null is not an object (evaluating 'TrackPlayer.STATE_NONE') when package is used with Expo

### ISSUE THREAD

**Issue by BR4VE** [DoubleSymmetry/react-native-track-player#1119]
I get the error in the title when I try run my app using my Android Phone (Expo Go) or IOS simulator in my mac. I'm using **Expo Bare Workflow**. I checked other tickets related to this problem but none of them solved my issue

**Environment (please complete the following information):**
- Expo Bare Workflow
- react-native info:

System:
    OS: macOS 11.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 141.82 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.8.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

react-native-track-player version: 1.2.3

![Screenshot_2021-02-22-15-12-20-277_host exp exponent](https://user-images.githubusercontent.com/24623852/108707297-d9e50400-7520-11eb-9547-949699aaea11.jpg)

**Comment by elliotdickison** [comment]
I'm getting the same thing. It does seem to be related to running within the Expo app. When I launch my project as a standalone app in an emulator (using `yarn android`) everything works fine.

react-native-track-player version: 1.2.6

Sys info (`expo diagnostics`):
```
Expo CLI 4.3.0 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.11.0 - ~/.nvm/versions/node/v15.11.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.11.0/bin/yarn
      npm: 7.6.0 - ~/.nvm/versions/node/v15.11.0/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 25, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-25 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-S | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.3.0
    Expo Workflow: bare
```
