### ISSUE TITLE
useTrackPlayerProgress does not update position in background on Android

### ISSUE THREAD

**Issue by sopranolinist** [DoubleSymmetry/react-native-track-player#1121]
**Describe the bug**
`useTrackPlayerProgress` hook does not update position when app is backgrounded on Android.

**To Reproduce**
Monitor `position` values returned by `useTrackPlayerProgress` - when an audio track is playing and then my app is backgrounded on Android, the `position` values returned each interval remain exactly the same as they were when the app was first backgrounded. Only when I foreground the app again do the values update. On iOS, the `position` values continue to update as expected while the app is backgrounded and the track continues to play.

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
```
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 22.04 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.1 - /var/folders/hm/blqgpkmn55qb8ntnxhf_0rwm0000gp/T/yarn--1614055513843-0.29919207481709087/node
    Yarn: 1.22.4 - /var/folders/hm/blqgpkmn55qb8ntnxhf_0rwm0000gp/T/yarn--1614055513843-0.29919207481709087/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Google X86_ARM Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6776251
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
```
What `react-native-track-player` version are you using?
`1.2.3`
Are you testing on a real device or in the simulator? Which OS version are you running?
Real device - Android 11

**Code**
```
const result = useTrackPlayerProgress(1000);
 console.log({ result });
```

**Comment by elirangoshen** [comment]
+1

same for ios 

also we cannot use it if track is not playing

**Comment by nickmcmillan** [comment]
Same issue here. 
When the audio file is playing and the app is backgrounded on **Android**, the `useTrackPlayerProgress` hook no longer updates.
When the audio file is playing and the app is backgrounded on **iOS**, the hook continues updating with the correct position value.

**Comment by kanzitelli** [comment]
I am facing the same issue as I want to implement timer functionality and it needs to be updated if the app is in the background. iOS works fine.

After looking into the code, I have realized that `useTrackPlayerProgress` uses `setInterval` which doesn't work on Android in background mode. So I have come up with a workaround using [`react-native-background-timer`](https://github.com/ocetnik/react-native-background-timer).

Define `BackgroundTimer.setInterval` somewhere globally, for example, in player service:
```
BackgroundTimer.setInterval(async () => {
  if (this.isPlayerSetUp) {
    const state = await TrackPlayer.getState();

    if (state === STATE_PLAYING || state === STATE_BUFFERING) {
      const [position, bufferedPosition, duration] = await Promise.all([
        TrackPlayer.getPosition(),
        TrackPlayer.getBufferedPosition(),
        TrackPlayer.getDuration(),
      ]);
  
      console.log(position, bufferedPosition, duration);
      playerStore.setPosition(position);
    }
  }
}, 1000);
```

And then use `useTrackPlayerProgress`'s position for iOS and `playerStore`'s position for Android inside a component:
```
const { position } = useTrackPlayerProgress(1000);
const finalPosition = Platform.OS !== 'android' ? position : playerStore.position;

useEffect(() => {
    if (playerStore.timer === 0) player.pause();
    playerStore.timerDec();
}, [finalPosition]);
```
