### ISSUE TITLE
iOS: In lock screen player on pause move to past position

### ISSUE THREAD

**Issue by wesydi** [DoubleSymmetry/react-native-track-player#1122]
**Describe the bug**
If on iOS in lock screen tap on pause then slider move to past position and after move to current position.

**To Reproduce**
1. Play music in player
2. Lock device
3. Unlock device
4. On lock screen tap on pause

**Environment (please complete the following information):**
```
System:
    OS: macOS 11.2
    CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
    Memory: 100.31 MB / 4.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```
**What react-native-track-player version are you using?**
`1.2.3`
**Are you testing on a real device or in the simulator? Which OS version are you running?**
Real device - iPhone 5s

https://user-images.githubusercontent.com/51164434/109004855-57904780-76ba-11eb-86f4-c24f55e8b221.mp4

**Comment by rhoehener** [comment]
Still a problem in 1.2.7. iPhone 12 Pro Max. iOS 14.6.

Does anyone have a reliable way to workaround this? I have tried with seeking before and after play/pause, but can never quite seem to make it smooth. Next I'm thinking about keeping track of the position myself and pushing it on every play/pause action.

**Comment by rhoehener** [comment]
Same as https://github.com/DoubleSymmetry/react-native-track-player/issues/1046.

One suggestion is to set the capabilities correctly.

Another comment mentions inherent seeking problems with MP3 file formats: https://exoplayer.dev/troubleshooting.html#why-is-seeking-inaccurate-in-some-mp3-files

I can convert my audio files to any format. What would be the perfect format settings to use with FFmpeg to ensure perfect seeking?

**Comment by SintoAntony** [comment]
is there any work around for the issue in lock screen player progress on iOS.
