### ISSUE TITLE
iOS Dash Support?

### ISSUE THREAD

**Issue by chrisvire** [DoubleSymmetry/react-native-track-player#1124]
I am interested is serving multiple bitrates (16, 32, and 64Kbps) of recorded speech via Ogg Opus since it provides superior quality at low bitrates.  I would like to use react-native-track-player for this Android/iOS app. I would like to offering streaming. HLS doesn't officially support Ogg Opus, but MPEG-DASH does support Ogg Opus.  However, your platform documentation shows that the iOS side doesn't support MPEG-DASH. I know that iOS can support Ogg Opus via .caf files (I currently use mobile-ffmpeg to convert webm files to caf and then play them with AVPlayer in another app). Has anyone considered how to support MPEG-DASH on iOS?

I would be willing to submit a pull request to implement MPEG-DASH if there is a reasonable way forward.

My other alternative is to use ACC with HLS, but I would prefer Ogg Opus at 16Kbps.

**Comment by bradleyflood** [comment]
Hi @chrisvire and thank you. I've added this to our Feature Requests project. Everyone here is at full capacity so I can't imagine anyone will work on this. Of course we are always keen for PRs. Thank you and best of luck!
