### ISSUE TITLE
iOS: NSInternalInconsistencyException and RCTEventEmitter error (maybe RCTBridge)

### ISSUE THREAD

**Issue by newfylox** [DoubleSymmetry/react-native-track-player#1139]
I have this error when building a new app. The only changes that I did was upgrading `react-native-track-player` from **1.2.3** to **1.2.5** and upgrading `react-navigation` from 3 to 5. Don't know if it may help.

**react-native**: 0.60.6
**react-native-track-player**: 1.2.5
**OS**: Mojave 10.14.6
**Xcode**: 11.3.1

```
Terminating app due to uncaught exception 'NSInternalInconsistencyException',
reason: 'Error when sending event:
playback-state with body: {
    state = ready;
}. 
Bridge is not set. This is probably because you've explicitly synthesized
the bridge in RNTrackPlayer, even though it's inherited from RCTEventEmitter.'
```

**Comment by curiousdustin** [comment]
May be unrelated, but did you do a `pod install` after updating?

**Comment by newfylox** [comment]
I did a `npx pod-install` thinking that your library is set with auto-linking and not having the necessity of doing a `react-native link` because using the auto-linking on Android works well but the other command breaks it.

Can you confirm that it auto links on iOS as well?

**Comment by curiousdustin** [comment]
correct, you should not need to use `react-native link`.

**Comment by newfylox** [comment]
Just cleaned everything (Xcode, node_modules) and reinstall everything (yarn, npx pod-install) and I just noticed that a pod was missing `RNCMaskedView (0.1.10)`

Hope it will fix the problem. Keep you in touch.

**Comment by newfylox** [comment]
Unfortunately, I had this issue again. I don't know what's triggering this. But it's always this message

```
'NSInternalInconsistencyException', reason: 'Error when sending event: playback-state with body: {
    state = ready;
}. Bridge is not set. This is probably because you've explicitly synthesized the bridge in RNTrackPlayer, even though it's inherited from RCTEventEmitter.'
```

If there is something I can (or should) add in my AppDelegate.m (or make sure is present), just tell me. Meanwhile I will try to update other packages (or even React-Native to a newer one because it's an old project)

**Comment by curiousdustin** [comment]
Can you try out the example app? And if it works as expected, compare with your app?

**Comment by newfylox** [comment]
Sure! I guess it's on my side too!

**Comment by curiousdustin** [comment]
I randomly ran into this today as well. However only happened once and I'm not sure of the cause.

I restarted my debugger and it resolved.

Do you experience this every single time you launch your app?

Are you using debug mode? Are you on a real device, or simulator?

**Comment by newfylox** [comment]
Only on a simulator and more often on an iPhone SE 10 than an iPhone X 13, but it can happen too. Also, it's when I'm using hot reloading and debug js mode.

But didn't have this with Track Player 1.2.3 before. Maybe it shows a bad setting in my project that was "hidden" or maybe it's something new?

Just hoping it doesn't happen on a real device or debug mode disabled.

**Comment by newfylox** [comment]
I forgot to mention that I have other warnings or bugs before this one like those:

`[RCTCxxBridge.mm:502] Unable to find module for UIManager`

`RCTBridge required dispatch_sync to load RNGestureHandlerModule. This may lead to deadlocks`

**Comment by curiousdustin** [comment]
I'm not certain, but I suspect this may be related to debug + refreshing after code changes.

Sorry I do not have anything more helpful at the moment, and no time to investigate.

**Comment by newfylox** [comment]
Yeah I understand and I keep on my side looking for this too.

Good point about first launch app, I'll try this

**Comment by eli-stewart** [comment]
I am also experiencing this error fairly frequently but not with a regular pattern

**Comment by faraza** [comment]
This happens to me 100% of the time if I 1) start playing audio 2) restart the app through expo BUT NOT Xcode 3) try playing audio again. After step 2, the audio still continues to play even though my app is in its null state. Sometimes, I'll get double overlapping audio playing for a few seconds before the crash. I'm assuming it's got something to do with tearing down the TrackPlayer. I set 'stopWithApp: true' in updateOptions, but maybe expo updates don't count?

**Comment by hbarylskyi** [comment]
I just updated to 2.1.2 and found that this happens a lot. Seems like there wasn't a fix for this? @dcvz should the issue be reopened?

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: playback-track-changed with body: {
nextTrack = 7;
position = "59.89625850340136";
track = 6;
}. Bridge is not set. This is probably because you've explicitly synthesized the bridge in RNTrackPlayer, even though it's inherited from RCTEventEmitter.'```

**Comment by martinmidtsund** [comment]
I just got something similar, in development mode. Version 2.1.2.

`Thread 360: "Error when sending event: playback-state with body: {\n    state = paused;\n}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in RNTrackPlayer, even though it's inherited from RCTEventEmitter."`

**Comment by andrewdang17** [comment]
Same here on 2.1.3. Lock screen controls don't work for me so basically any `remote-` event

**Comment by lucidprojects** [comment]
I know this is a pretty stale thread, but did the consensus on this end up being related to development builds?

I having the same issue with a different react lib.  🍿 incase a solution or further information comes about
