### ISSUE TITLE
Update track metadata from radio stream while app is closed but the player is still functional

### ISSUE THREAD

**Issue by matetami96** [DoubleSymmetry/react-native-track-player#1140]
Good day, I am developing a radio application using this package, in there when setting up the player I am adding only one track with a URL pointing to a radio stream. As long as the application runs either in foreground or in the background I can update the track title and artist by fetching data from a 'nowplayingjson.php' file then using Trackplayer.updateMetadataForTrack. My question is the following: when the application is closed completely, but 'stopWithApp' is set to false during Trackplayer.updateOptions meaning the notification is still active (after the app is closed) so the user can still play/pause or stop the service from the notification, is it possible to update the metadata in the notification during this time (again the app is not running only the playback service)? I tried setting up an interval in the service.js file which is registered as playbackservice but that only works when the app is running too. Any replies are appreciated, and please let me know if the way I asked my question is misleading or incorrect.

**Comment by rigerous** [comment]
Hi, I have same problem. Perhaps this solution with a promise&sleep in player background service will work for us. I tried it on Android, it works well (updateMetadataForTrack refresh data in notification when app in background or shutdowned), but I haven't tried it on IOS.

https://codeburst.io/the-definitive-guide-to-react-native-background-processing-51df02540433
