### ISSUE TITLE
getPosition() returns the same value even though player keeps playing

### ISSUE THREAD

**Issue by sslash** [DoubleSymmetry/react-native-track-player#1142]
Hi! Happy react-native-track-player user here. This issue might be somewhat rare, but still a huge problem for us. 

**Describe the bug**
Occasionally the call to `getPosition()` returns the same value over and over again, even though the player keeps playing normally. E.g 60 seconds in, the call to `getPosition` would just start yielding the same position value over time. When it happens, it will be when I pause the track-player to play some other sound (through another iOS music player implementation), then pause that and resume the rn-track-player.  

**To Reproduce**
Listen to a podcast episode, such as `https://traffic.libsyn.com/secure/syntax/Syntax336.mp3?dest-id=532671`. Add another music-source implementation and create a timer that every second switch over to that and let it play a sound in 60 seconds, then switch back and continue playing the podcast. Do this on repeat until the call to `getPosition` starts emitting the same value every secon.

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
What `react-native-track-player` version are you using?
Are you testing on a real device or in the simulator? Which OS version are you running?
This happens on iOS only, both simulator and on real device. React-native version: 0.63.2, react-native-track-player version: 2.0.0-rc13

**Code**
```
let seconds = 0
let isPodcastPlaying = true
setInterval(() => {
    seconds++

    if (isPodcastPlaying) {
        console.log("Podcast position: " + (await trackPlayer.getPosition()))
    }

    if (seconds % 60) {
        if (isPodcastPlaying) {
            isPodcastPlaying = false
            await trackPlayer.pause()
            await someOtherPlayer.resume()
        } else {
            isPodcastPlaying = true
            await someOtherPlayer.pause()
            await trackPlayer.resume()
        }
    }
}, 1000)

```

Note that we've used this lib with great success for years. It's only until recently (not sure how long back though), this has started to become a problem, as it's not reliable to save the podcast position for the user.

Any ideas for helping us debug this issue would be highly appreciated! I've made sure the call on the native side (getting ` player.currentTime`) for sure yields the same position over time, even though the player keeps playing normally. No error is thrown

**Comment by curiousdustin** [comment]
Can you try a 1.x version?

Also when you say another music player, are you meaning you switch to another app and play music, then switch back to your app and resume? Or something different?
