### ISSUE TITLE
iOS - Stop playing (no sound) when not in foreground

### ISSUE THREAD

**Issue by newfylox** [DoubleSymmetry/react-native-track-player#1143]
**react-native**: 0.60.6
**react-native-track-player**: 1.2.6
**iOS**: 14
**iPhone**: 12

On simulator, I only have iPhones until 11 (not having 12) and only iOS 13.3 (or previous). Everything works fine when I put my app on background (not focused) or even not active (put the screen off by pressing the button)

Now my friends are testing the app on TestFlight and they tell me that when they quit the app (background), it stops playing. They also tell me that on lock screen, they see the player, they click on play, the timeline moves but there is no sound. I cannot test because I don't have an iPhone 12, neither iOS version 14.

My question is that one: is it related to iPhone 12? Or related to iOS 14? Or both? Is there an option I can turn on/off to test with my friends on TestFlight?

The only thing I'm thinking of is the option `stopWithApp: true`. But it's meaningful when we close app on multitask view (or in settings with force stop). Also, it works fine with my simulators (from iPhone SE iOS 10 to my iPhone 11 iOS 13)

Thanks

**Comment by newfylox** [comment]
It seems that it's random. It works well on iPhone 12 pro iOS 14.4.1 and iPhone 6 iOS 14.3 but it turns off in background with iPhone 12 iOS 14.4.1 and iPhone 8 Plus 14.4.1

**Comment by mchandleraz** [comment]
After upgrading from 1.2.3 to 1.2.6, my users are reporting that our app is affected by the hardware "silent mode" switch on iPhones. Might be worth talking to your testers about whether they've got the switch on Silent.

**Comment by curiousdustin** [comment]
Might be related to this change: https://github.com/react-native-kit/react-native-track-player/pull/976/files

**Comment by curiousdustin** [comment]
Using the example app to test, background mode behaves as expected. Unaffected by mute switch, and does not pause when backgrounding.

Make sure you [add the Background Modes capability](https://react-native-track-player.js.org/background/#ios).

**Comment by newfylox** [comment]
The background mode capability is enabled since years, but thanks pointing this. One of my tester told me that it's working now and I did nothing new. Probably the silent mode thing OR a cache thing with JS Bundle from switching to my old app to a new one?

Will do more tests.

**Comment by newfylox** [comment]
Ok, a lot of our users had our new app update this weekend and some of them had the issue with their iPhones.

The solution is somewhere between those 2 ideas (not sure which one or if both is needed)

* kill all apps in Multitask view and fully restart iPhone
* Toggle multiple times silent mode on/off even if they were not on silent mode enabled at the beginning

**Comment by ouabing** [comment]
Just got into a similar issue, can't ignore silent mode switch and can't play in background. Later I found this is related to `react-native-video`.

My app calls `TrackPlayer.setupPlayer` in the start time, then it will play a muted video using react-native-video as a welcome page, with ignoreSilentSwitch set to "obey". Then I found all the `TrackPlayer.play` calls won't play in background and silent mode any more.

If I call `TrackPlayer.setupPlayer` after playing the video, the issue gone.

So my guess is playing a video/audio by another playback library may mess up the iOS category settings you set by `TrackPlayer.setupPlayer`. Have no time to dig into `react-native-video` yet, I will check it later.

**Comment by newfylox** [comment]
This is interesting. Thanks for sharing your informations.

I'm only using audio. Maybe there's an "empty" play in my code that could trigger a false video playback?

Anyways, my `TrackPlayer.setupPlayer({})` is plain, without any options. Is there something I can set to ignore what you pointed out and always force the audio to output?

**Comment by ouabing** [comment]
@newfylox  you can config `AVAudioSession` in [setupPlayer](https://react-native-track-player.js.org/documentation/#setupplayeroptions), by default it uses some default settings.

I checked `react-native-video`'s code, [it will always call `setCategory`](https://github.com/react-native-video/react-native-video/blob/88b636f158f6287daa2a4286c7498c5f5a8f2255/ios/Video/RCTVideo.m#L939) when start playing video. Once we set `ignoreSilentSwitch` to `obey` in RNVideo side, the category will switched to `AVAudioSessionCategoryAmbient` forever. @curiousdustin maybe we should always reconfigure category before start playing like what `react-native-video` do in case that the `AVAudioSession` may be changed by other playback libs after `setupPlayer`? I'm not familiar with AVPlayer so I don't know if there is any performance issue if we always reconfigure `AVAudioSession`.

I found there are several issues about inconsistent behaviour even though by default `setupPlayer` will let the player work in background mode. Don't know if these are the same cases like mine, but this problem is really imperceptible.

**Comment by ouabing** [comment]
@newfylox try calling `setupPlayer` right before you start playing audio, to avoid any accidental changes of `AVAudioSession` before. If this can't solve you problem, I'm afraid we are not in the same case.

**Comment by DucSkt** [comment]
same issue

**Comment by JDMathew** [comment]
I had the same issue and fixed it by adding the audio UIBackgroundMode. Either add audio to UIBackgroundModes directly in `Info.plist`:
```xml
<key>UIBackgroundModes</key>
  <array>
  <string>audio</string>
</array>
```

Or tick the audio check box in xcode:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/17250443/160653723-15d13504-6291-4d8b-9acb-7c2114c2d51a.png">

**Comment by kiranNegiloni** [comment]
> **react-native**: 0.60.6 **react-native-track-player**: 1.2.6 **iOS**: 14 **iPhone**: 12
> 
> On simulator, I only have iPhones until 11 (not having 12) and only iOS 13.3 (or previous). Everything works fine when I put my app on background (not focused) or even not active (put the screen off by pressing the button)
> 
> Now my friends are testing the app on TestFlight and they tell me that when they quit the app (background), it stops playing. They also tell me that on lock screen, they see the player, they click on play, the timeline moves but there is no sound. I cannot test because I don't have an iPhone 12, neither iOS version 14.
> 
> My question is that one: is it related to iPhone 12? Or related to iOS 14? Or both? Is there an option I can turn on/off to test with my friends on TestFlight?
> 
> The only thing I'm thinking of is the option `stopWithApp: true`. But it's meaningful when we close app on multitask view (or in settings with force stop). Also, it works fine with my simulators (from iPhone SE iOS 10 to my iPhone 11 iOS 13)
> 
> Thanks

Hi @newfylox - I am facing exact issue that you have mentioned related to the testflight. Kindly let me know the fix that you applied. I have background capabilities applied. Things are not working after uploading the app to the testflight. Thanks in advance.

**Comment by newfylox** [comment]
> Hi @newfylox - I am facing exact issue that you have mentioned related to the testflight. Kindly let me know the fix that you applied. I have background capabilities applied. Things are not working after uploading the app to the testflight. Thanks in advance.

Hi @kiranNegiloni,

I'm sorry to tell you that I no longer develop this app for my client. Also, I didn't find a fix in my previous research. Sorry about that!

**Comment by chhotu50** [comment]
I am facing the same issue.
