### ISSUE TITLE
TrackPlayer.seekTo not working while player is paused

### ISSUE THREAD

**Issue by elirangoshen** [DoubleSymmetry/react-native-track-player#1146]
**Describe the bug**
In android, when im' using TrackPlayer.seekTo method, the player position is still in the old position and not the one i wanted to seek to. 

**To Reproduce**
in android use seekTo method and while player is not playing.

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 129.54 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.13.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
What `react-native-track-player` version are you using? v1.2.6
Both. API 29

**Code**
```
  const {position} = useTrackPlayerProgress(500, [
    TrackPlayer.STATE_BUFFERING,
    TrackPlayer.STATE_NONE,
    TrackPlayer.STATE_PLAYING,
    TrackPlayer.STATE_PAUSED,
    TrackPlayer.STATE_READY,
    TrackPlayer.STATE_STOPPED,
  ]);

// run this method with some value
const onPlayerSeek = () => {
     console.log('position before seeking', position);
    TrackPlayer.seekTo(destination).then(() => { 
// position is the same and not the destination - so seekTo didn't work 
    console.log('position after seeking', position);
    );
}
```

**Comment by OmkarK45** [comment]
Did you find any solution to this issue ?

**Comment by LozytskyiA** [comment]
What is solution?

**Comment by kiranNegiloni** [comment]
Same issue, Kindly let me know if any solution to the problem. In pause mode, When trying to seekTo player state is getting changed to "Ready"
