### ISSUE TITLE
Track player event listener

### ISSUE THREAD

**Issue by nagaraj95** [DoubleSymmetry/react-native-track-player#1148]
**Describe the bug**
 I am using the Trackplayer as an audio model in my app. I am having the feature of repeating the songs with the help of Trackplayer event listener , at some point of view I can't able to get the callback from the event listener. So, I can't able to perform some actions in my app. The problem appears in Android OS.

**To Reproduce**
Not able to reproduce the way while in production mode the bug arises.

Please post some solution for this. Thanks in advance

**Comment by newfylox** [comment]
@curiousdustin 

**version**: 1.2.7

don't know if it's related to the new version and cannot say I have the same issue but I can confirm that `playback-state` event is not fired on fresh new install on **Android**.

If I `force stop` the app and restart it, `playback-state` will start working, but only if I use `force stop` (killing it in multitasks view won't work). After this, application will work normally.

**Comment by curiousdustin** [comment]
@newfylox debug or release builds? (connected to the bundler or not)

**Comment by newfylox** [comment]
First, I discovered this problem on release mode (internal testing on Google Play Console) and I was wondering why I didn't have this issue before. Then I realized it was because it was a fresh new install (because I uninstalled the app to test the internal version)

Then I tried it on debug mode. I uninstalled everything, launch the app (react-native start and android-run) and discovered the same issue.

**Comment by newfylox** [comment]
I will try many previous versions. Probably it's on my side too. Will keep you in touch.

**Comment by newfylox** [comment]
Ok it seems on my side. Even if I downgrade until 1.2.3 I still have this issue. It only happens on fresh install (or clear cache and data).

I will try to find out what is my mistake and explain it if it can help others.

**Comment by newfylox** [comment]
Ok everything is fixed for me using `addEventListener` instead of `registerEventHandler`. Also, I need to update my redux store so I'm using this example below to make it work properly.

```js
// registering my handler where store is imported for the first time (probably in App.jsx or index.js)
TrackPlayer.registerPlaybackService(() => require('./src/handler.js')(store));

...

// my handler located in ./src/handler.js
module.exports = (store) => {
  return async () => {
    TrackPlayer.addEventListener('playback-state', (event) => {
        store.dispatch(myAction());
        // other stuff
    } );
  }
}
```

All good for me now!
