### ISSUE TITLE
crash exception java.lang.NullPointerException

### ISSUE THREAD

**Issue by quocbao1510** [DoubleSymmetry/react-native-track-player#1149]
I found crash in devices samsung, oppo with tracking log:
Crash Location Class: com.guichaguri.trackplayer.module.MusicModule
Crash Location File: MusicModule.java
Crash Location Line Number: 1.
Message crash: Crash, Attempt to invoke virtual method 'com.guichaguri.trackplayer.service.g.a com.guichaguri.trackplayer.service.b.b()' on a null object reference.

Any suggest for me? thanks

**Comment by wanjohiryan** [comment]
Hi, I am new to react native... But I noticed this is called when somewhere in an "async" function you don't wait for the track player to resolve a promise by using "await", I might be wrong, but for me it solved this issue🤷🏾‍♂️

**Comment by mohity777** [comment]
I have used await still it is crashing on Redmi device.

**Comment by bradleyflood** [comment]
Thanks @quocbao1510 - is this still an issue on the latest release v2? If so please let us know. Thank you.

**Comment by medmo7** [comment]
Im getting this issue on version:2.1.2. The app is crashing on start, it was working before.
here is the error I get from my Redmi:
![Screenshot_2022-01-28-10-25-04-158_com miui bugreport](https://user-images.githubusercontent.com/32428883/151522433-cf6525cc-4a75-4a30-b2a8-fa95bc8c3906.jpg)

**Comment by medmo7** [comment]
Just found what was causing the issue I was  setting `TrackPlayer.updateOptions` like this :

```javascript
TrackPlayer.updateOptions({
      // stopWithApp: true,
      capabilities: [
        Capability.CAPABILITY_PLAY,
        Capability.CAPABILITY_PAUSE,
        Capability.CAPABILITY_SKIP_TO_NEXT,
        Capability.CAPABILITY_SKIP_TO_PREVIOUS,
        Capability.CAPABILITY_STOP,
      ],
      compactCapabilities: [
        Capability.CAPABILITY_PLAY,
        Capability.CAPABILITY_PAUSE,
        Capability.CAPABILITY_SKIP_TO_NEXT,
        Capability.CAPABILITY_SKIP_TO_PREVIOUS,
      ],
    });
```

changed to this  and the crash is gone :

```javascript
import TrackPlayer, {State, Capability} from 'react-native-track-player';


TrackPlayer.updateOptions({
      // stopWithApp: true,
      capabilities: [
        Capability.Play,
        Capability.Pause,
        Capability.SkipToNext,
        Capability.SkipToPrevious,
        Capability.Stop,
      ],
      compactCapabilities: [
        Capability.Play,
        Capability.Pause,
        Capability.SkipToNext,
        Capability.SkipToPrevious,
      ],
    });
```
found the answer here: https://github.com/DoubleSymmetry/react-native-track-player/issues/706#issuecomment-560330477
