### ISSUE TITLE
useTrackPlayerProgress hook causes React state update on an unmounted component

### ISSUE THREAD

**Issue by lyswhut** [DoubleSymmetry/react-native-track-player#1150]
**Describe the bug**
`useTrackPlayerProgress` hook causes React state update on an unmounted component

Screenshot:
![image](https://user-images.githubusercontent.com/20365169/112412048-d380bc80-8d58-11eb-981c-4088a218be92.png)

I created a new react native application, but it doesn’t seem to be able to reproduce it 100%

**To Reproduce**
Import and use the useTrackPlayerProgress hook.

**Environment (please complete the following information):**

Versions:
"react": "17.0.1"
"react-native": "0.64.0"
"react-native-track-player": "1.2.7"

OS: Android emulator

**Code**
```js
import React from 'react'
import { Text } from 'react-native'
import { useTrackPlayerProgress } from 'react-native-track-player'
export default () => {
  const { position, bufferedPosition, duration } = useTrackPlayerProgress(250, null)
  return (
    <>
      <Text>hello</Text>
    </>
  )
}
```

**Solution**

I read the source code related to the useTrackPlayerProgress hook,
It is found that the asynchronous function inside the hook sets the state, which leads to this problem in some cases. We should determine whether the component has been uninstalled before the asynchronous function sets the state.

Before:
https://github.com/react-native-kit/react-native-track-player/blob/69a22cd059415c51e473a2f7cb55b7f679672af6/lib/hooks.js#L132-L163

After:
```js
const useTrackPlayerProgress = (
    interval = 1000,
    pollTrackPlayerStates = [
        TrackPlayer.STATE_PLAYING,
        TrackPlayer.STATE_BUFFERING,
    ]
) => {
    const initialState = {
        position: 0,
        bufferedPosition: 0,
        duration: 0,
    };

    const [state, setState] = useState(initialState);
    const isUnmountedRef = useRef(true);

    useEffect(() => {
      isUnmountedRef.current = false;
      return () => { isUnmountedRef.current = true };
    })
  
    const getProgress = () => {
        return Promise.all([
            TrackPlayer.getPosition(),
            TrackPlayer.getBufferedPosition(),
            TrackPlayer.getDuration(),
        ]).then(([position, bufferedPosition, duration]) => {
            if (isUnmountedRef.current) return;
            setState({ position, bufferedPosition, duration });
        })
    };

    let needsPoll = true;
    if (pollTrackPlayerStates) {
        needsPoll = usePlaybackStateIs(...pollTrackPlayerStates);
    }

    useInterval(getProgress, needsPoll ? interval : null);
    return state;
};
```

Relevant information: <https://www.debuggr.io/react-update-unmounted-component/>

**Comment by lyswhut** [comment]
I also found several issues that violated the hook rules: 
1. Dependency must be an array:
https://github.com/react-native-kit/react-native-track-player/blob/69a22cd059415c51e473a2f7cb55b7f679672af6/lib/hooks.js#L70

**Comment by ithustle** [comment]
> https://github.com/react-native-kit/react-native-track-player/blob/69a22cd059415c51e473a2f7cb55b7f679672af6/lib/hooks.js#L132-L163

@lyswhut, did you make a PR?

**Comment by lyswhut** [comment]
I didn't do it, but you can fix it by the way 🙂

**Comment by ithustle** [comment]
Yeah, but it'll fair if you fix it and then you could became a Contributor. You may create a new branch and submit a PR. The community will appreciate that :-)

**Comment by lyswhut** [comment]
The 1.x.x branch has been removed, I don’t know which branch I should submit the PR to.
Should I submit the PR to the v2 branch? I hope you will create this PR 😀

**Comment by dcvz** [comment]
Thanks for reporting this @lyswhut even on the main (v2) branch I think this may be an issue. As @ithustle mentioned it would help a lot of you could submit a PR with your fixes against the main branch!
