### ISSUE TITLE
Using API request to play tracks/songs

### ISSUE THREAD

**Issue by wiredmatrix** [DoubleSymmetry/react-native-track-player#1152]
I have successfully implemented react-native-track-player package to play music in my app with few songs I added in my array of songs. But instead of repeating the same songs over and over again, I want to use API request to fetch songs into the player. Am particular on the API to use, it can  Spotify API, or Napster API or Pandora API or any music streaming API.

How can I achieve that cos I don't seem to see any documentation or tutorial on that online. Thanks so much for your kind responses.

**Comment by WNemencha** [comment]
Just set your track url to a remote mp4/webm/mp3/anything url ? You can even stream the file, track player will handle it for you ;)
