### ISSUE TITLE
Track restarting to begin IOS

### ISSUE THREAD

**Issue by gabrinunes** [DoubleSymmetry/react-native-track-player#1154]
**Describe the bug**
when making a long audio stream, the same goes back to the beginning the same behavior happens in Safari, chrome and other browsers and in Android this problem does not happen, the audio is in the firebase storage.

**To Reproduce**
just add this url to the method: https: //storage.googleapis.com/trusty-slate-244919.appspot.com/dev%2Fpractices%2Faudios%2FPratica%20da%20Visao-1568040288365.mp3? GoogleAccessId = firebase-adminsdk-1xlif% & 40trusty-slate-244919.iam.gserviceaccount.com expire = 7535991600 & Signature = coFZksPpjVMLhpcB1nanDpziAD9eO8FNMu6k2EIuAXyGTi4WWUXC7ugv8ysKwUJY9RDtFP5y2f1Pwrok3Gyvgk5K3ge6hzotYMMvW2u5zox% 2FPNNxHon3hbA9O13hMukIUS3m3J8FYzmcs% 2F% 2B9cv3snGAZvFOmjHhvf% 2BZxzEtggjW0rF 2FQ%%% 2B5Y8fNGhxuZPmkVw4N0r1QNZsAt5LyXYAipiGL59r 2BzfMeYwl% 2F% 2BV1Db5SLgIZnEoVdnVLWaF6KektFO6uQKct7urkaAo55ik9clh 2BcVIR4p2XKnDvNj6cbB1eC97dywPhwLHR%%% 2B1RGt9QlNR8u6wPXcXbhQ1grROHXI6srQ 3D% 3D

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
System:
    OS: Windows 10 10.0.19041
    CPU: (6) x64 AMD FX(tm)-6300 Six-Core Processor
    Memory: 208.30 MB / 7.98 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 21, 23, 25, 27, 28, 29, 30
      Build Tools: 25.0.2, 27.0.3, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3
      System Images: android-21 | Google APIs ARM EABI v7a, android-25 | Google APIs ARM EABI v7a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
    Visual Studio: Not Found
  Languages:
    Java: Not Found
    Python: 2.7.17 - /c/Python27/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ^0.63.3 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
What `react-native-track-player` version are you using?
Are you testing on a real device or in the simulator? Which OS version are you running?
"react-native-track-player": "^2.0.0-rc13"

testing on Emulator Iphone 11Pro(IOS 14)

**Code**

/* eslint-disable react-hooks/exhaustive-deps */
import React, {
  useContext,
  useEffect,
  useState,
  useCallback,
  useRef
} from "react";

import TrackPlayer, {
  PitchAlgorithm,
  useProgress,
  Capability,
  Track,
  State,
  Event
} from "react-native-track-player";

// import Sound from "react-native-sound"
// import { isAndroid } from "../Constants";

interface Context {
  isPlaying: boolean;
  audioPosition: number;
  audioDuration: number;
  onSeek(time: number): void;
  playAudio(id: string): void;
  playSong(data: Track): void;
  stopSong(callback: () => void): void;
  togglePlay(state?: boolean): void;
  addAudiosToQueue(audios: Track[]): void;
}

const AudioContext = React.createContext({} as Context);

export const AudioProvider: React.SFC = props => {
  const [_state, setState] = useState<State>(State.Paused);
  const { duration, position } = useProgress();

  let { current: trackChangeEvent } = useRef<any>();

  const _init = useCallback(async () => {
    await TrackPlayer.setupPlayer();
    await TrackPlayer.updateOptions({
      stopWithApp: false,
      capabilities: _capabilities,
      notificationCapabilities: _capabilities,
      compactCapabilities: _capabilities
    });

    return Promise.resolve();
  }, []);

  useEffect(() => {
    let sub: any = null;

    _init().then(() => {
      sub = TrackPlayer.addEventListener(Event.PlaybackState, data => {
        setState(data.state);
        console.log('terminou o mp3?');
      });

      // TrackPlayer.addEventListener(Event.PlaybackTrackChanged, () => {
      //   TrackPlayer.stop();
      // });
    });

    return () => {
      sub.remove();
      TrackPlayer.destroy();
    };
  }, [_init]);

  if (_state === State.Stopped) {
    console.log("mp3 terminou");
    duration.toFixed(0);
    position.toFixed(0);
  }

  const addAudiosToQueue = async (audios: Track[]) => {
    await TrackPlayer.add(
      audios.map(track => ({
        pitchAlgorithm: PitchAlgorithm.Voice,
        artist: "",
        title: "",
        ...track
      }))
    );

    await TrackPlayer.stop();
  };

  const playAudio = async (id: string) => {
    if (trackChangeEvent) {
      trackChangeEvent.remove();
    }

    if (_state !== State.Playing) {
      await TrackPlayer.skip(id);
      TrackPlayer.pause();
    }

    trackChangeEvent = TrackPlayer.addEventListener(
      Event.PlaybackTrackChanged,
      () => {
        TrackPlayer.pause();
      }
    );
  };

  const playSong = async (data: Track) => {
    await TrackPlayer.stop();
    await TrackPlayer.reset();
    await TrackPlayer.add({
      pitchAlgorithm: PitchAlgorithm.Voice,
      artist: "",
      title: "",
      id: Date.now(),
      ...data
    });
    await TrackPlayer.play();
  };

  const stopSong = useCallback(async (callback: () => void) => {
    await TrackPlayer.pause();
    await TrackPlayer.seekTo(0);
    if (callback) {
      callback();
    }
  }, []);

  const togglePlay = useCallback(
    async (state?: boolean) => {
      if (state !== undefined) {
        state ? TrackPlayer.play() : TrackPlayer.pause();
      } else {
        _state === State.Playing ? TrackPlayer.pause() : TrackPlayer.play();
      }
    },
    [_state]
  );

  const onSeek = useCallback(async (seconds: number) => {
    const currentTrack = await TrackPlayer.getCurrentTrack();
    if (currentTrack !== null) {
      await TrackPlayer.seekTo(seconds);
      TrackPlayer.play();
    }
  }, []);

  const value = {
    isPlaying: _state === State.Playing,
    audioPosition: position,
    audioDuration: duration,
    addAudiosToQueue,
    togglePlay,
    stopSong,
    playSong,
    playAudio,
    onSeek
  };

  return <AudioContext.Provider value={value} {...props} />;
};

export function useAudioContext() {
  const context = useContext(AudioContext);
  if (context === undefined) {
    throw new Error("AudioContext can only be used within <AudionProvider />");
  }
  return context;
}

const _capabilities = [
  Capability.Play,
  Capability.Pause,
  Capability.SeekTo,
  Capability.Stop,
  Capability.JumpForward,
  Capability.JumpBackward
];

playSong({
      id: props.id,
      artwork: props.image,
      title: props.title,
      url: props.url,
    });

**Comment by onepointconsulting** [comment]
Funny enough I am experiencing this too. using "react-native": "0.67.0". You can start playing tracks with around 60 minutes on iOS, but after 2 - 3 minutes the track restarts abruptly. On Android the tracks are played perfectly. This does not happen for tracks with less than 10 minutes.
