### ISSUE TITLE
Live stream play form .m3u8 file with track player and  even when app in Background.

### ISSUE THREAD

**Issue by Depthol93** [DoubleSymmetry/react-native-track-player#1161]
Hello There , 
                 Thank you for this awesome library. I have requirement to play audio from Live stream URL from .m3u8 file. Can anyone please let me know is it supported in Track player? And How I can keep audio playing  in Background mode also in Android and specially IOS . That will be very helpful  thank you.

**Comment by bradleyflood** [comment]
Hi @Depthol93 I'm tidying up some of the older Issues. Let me know if you still need to discuss this. Thank you

**Comment by akhilumapathe** [comment]
Hi. Im having trouble in playing hls on IOS, but not on android. Using the latest version, 4.1 and the code is below.
`    await TrackPlayer.setupPlayer({
        waitForBuffer: true,
        playBuffer: buffer,
        minBuffer: buffer * 2,
        maxBuffer: buffer * 5,
        iosCategory: IOSCategory.Playback, 
        iosCategoryMode: IOSCategoryMode.Default,
      });

      await TrackPlayer.updateOptions({
        capabilities: [Capability.Play, Capability.Pause, Capability.Stop],
        progressUpdateEventInterval: 2,
      });

      await TrackPlayer.add({
        id: "1",
        url: "https://URL/TO/play/audio.m3u8", 
        title: "Test Stream",
        artist: "Beta Devs",
        isLiveStream: true,
        type: TrackType.HLS, // Important for HLS streaming
      });

      const state = await TrackPlayer.getPlaybackState();
      if (state.state !== State.Playing) await TrackPlayer.play();
       if (state.state == State.Playing) await TrackPlayer.pause();`

Working fine on Android, not on iOS
