### ISSUE TITLE
iOS not playing longer audio files

### ISSUE THREAD

**Issue by BjoernRave** [DoubleSymmetry/react-native-track-player#1165]
On android everything is working fine, however on iOS it doesnt finish buffering the audio. It's probably due to the length of the audio I am trying to play. Maybe there is also a correlation between the format (.ogg) and the problem, not sure how common that is.

I created a fork where I use the built-in example as a reproduction: https://github.com/BjoernRave/react-native-track-player

This is an example audio, which doesnt work on iOS: https://speakeroo.s3-eu-west-1.amazonaws.com/audios/.fd077a55-f49e-410a-9a6d-c444deb1b049.ogg

**Comment by dcvz** [comment]
thanks for reporting this @BjoernRave ! As mentioned in the last thread, this is a known issue with (ogg) not being supported on iOS and want to improve this after the v2 release.
