### ISSUE TITLE
The progress is returning negative value after half duration

### ISSUE THREAD

**Issue by akshitrcrm** [DoubleSymmetry/react-native-track-player#1166]
**Describe the bug**
I'm using the hook

`const { position, bufferedPosition, duration } = useTrackPlayerProgress()`

Let's say my audio is of duration 50 seconds
Once it reaches 30 sec, the progress starts reversing, giving values -30, -29, -28 and so on until the end where it is -11.
This is happening on both platforms android and iOS.

**Comment by vivek2dx** [comment]
Hi there,
Any help on this?
