### ISSUE TITLE
Lock screen progress bar always increments at 1x rate even when set to a faster playback rate

### ISSUE THREAD

**Issue by mitchdowney** [doublesymmetry/react-native-track-player#1168]
**Describe the bug**
If the playback rate is faster than 1x, it appears that progress bar on the lock screen continues to updates at only 1x speed.

Is anyone else running into this issue? It's very easy for us to reproduce in podverse/podverse-rn.

**To Reproduce**
1) Add track to react-native-track-player.
2) Play the track.
3) Set the rate to 2x speed.
4) Lock the device.
5) Check the rate of the progress bar on the lock screen.

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.

Since this is only reproducable on an actual device, I don't think I can share the `react-native info` for the device.

What `react-native-track-player` version are you using?
1.2.6

Are you testing on a real device or in the simulator? Which OS version are you running?
Real device
iOS 14.5.1

**Code**
Sorry I don't have a simple demo created. Here's a link to the file where we initialize the react-native-track-player https://github.com/podverse/podverse-rn/blob/develop/src/services/player.ts#L82

**Comment by Senol122** [comment]
Any solutions for this problem? One thing I tried is pausing and playing the content after setting the rate, but for me it seems to be unnatural for the user.

**Comment by uzegonemad** [comment]
This seems to fix the issue for me. Not sure if there's a "better" way to do it or not, though.

```diff
diff --git a/node_modules/react-native-track-player/ios/RNTrackPlayer/RNTrackPlayer.swift b/node_modules/react-native-track-player/ios/RNTrackPlayer/RNTrackPlayer.swift
index ffa6277..c04ced3 100644
--- a/node_modules/react-native-track-player/ios/RNTrackPlayer/RNTrackPlayer.swift
+++ b/node_modules/react-native-track-player/ios/RNTrackPlayer/RNTrackPlayer.swift

@@ -433,6 +450,7 @@ public class RNTrackPlayer: RCTEventEmitter {
     public func setRate(rate: Float, resolve: RCTPromiseResolveBlock, reject: RCTPromiseRejectBlock) {
         print("Setting rate to \(rate)")
         player.rate = rate
+        player.updateNowPlayingPlaybackValues()
         resolve(NSNull())
     }
 
```

**Comment by bradleyflood** [comment]
Thanks everyone. I've added this to our Github Project and will review it again when we have capacity.

@uzegonemad is your fix still working? 

@mitchdowney @Senol122 have you tried the above suggested fix?

**Comment by uzegonemad** [comment]
@bradleyflood This is what we are currently using although I don't recall why we changed it, and the commit message for the change isn't descriptive enough to remind me. It might have been related to updating to RNTP 2.0.3 which occurred at the same time.


```diff
diff --git a/node_modules/react-native-track-player/ios/RNTrackPlayer/RNTrackPlayer.swift b/node_modules/react-native-track-player/ios/RNTrackPlayer/RNTrackPlayer.swift
index ffa6277..c04ced3 100644
--- a/node_modules/react-native-track-player/ios/RNTrackPlayer/RNTrackPlayer.swift
+++ b/node_modules/react-native-track-player/ios/RNTrackPlayer/RNTrackPlayer.swift

@@ -433,6 +450,7 @@ public class RNTrackPlayer: RCTEventEmitter {
     public func setRate(rate: Float, resolve: RCTPromiseResolveBlock, reject: RCTPromiseRejectBlock) {
         print("Setting rate to \(rate)")
         player.rate = rate
+        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
+            self.player.updateNowPlayingPlaybackValues()
+        }
         resolve(NSNull())
     }
```

**Comment by jspizziri** [comment]
It looks like this (at least originally) indicates an issue with v1 which is no longer supported. On those grounds, I'm going to close this issue. However, @uzegonemad if you're (or anyone else's) issue is with v2 please let me know and I'll reopen it.
