### ISSUE TITLE
"Cannot open" error when attempting to load an Opus file in the player (iOS only)

### ISSUE THREAD

**Issue by mitchdowney** [DoubleSymmetry/react-native-track-player#1173]
**Describe the bug**
When I attempt to load a remote Opus file in the player on any iOS device, I receive a playback error "Cannot open".

**To Reproduce**
1) On an iOS device, attempt to load the following media file URL into the react-native-track-player: https://noagendalite.glump.net/media/NA-1349-2021-05-23-Final.opus

The player returns a "Cannot Open" error for me.

Does react-native-track-player support the opus file format? Or is this something we are supposed to handle in our project settings somehow? Any advice would be appreciated!

**Environment (please complete the following information):**
What `react-native-track-player` version are you using? 1.2.6

Are you testing on a real device or in the simulator? Which OS version are you running?
iPhone 12 Pro Max simulator - 14.5
iPhone XR (real device) - 14.5.1

The issue appears to be reproducible on any iOS device. 

**Code**
Please, share the code that is causing the issue
I don't have a simple demo to share, but here is the file where we are initializing the react-native-track-player: https://github.com/podverse/podverse-rn/blob/develop/src/services/player.ts#L76

**Comment by dcvz** [comment]
Hi @mitchdowney -- I'll take a look at the file you linked me opus support soon. In the meantime are you able to use caf as an alternative? https://github.com/DoubleSymmetry/react-native-track-player/issues/809
