### ISSUE TITLE
 TypeError: null is not an object (evaluating 'TrackPlayer.STATE_NONE')

### ISSUE THREAD

**Issue by musangowope** [DoubleSymmetry/react-native-track-player#1182]
Hi community. Hope everyone is well.

Currently experiencing some issues with the package

**Describe the bug**
This error appears on run time when I try register the playback service, using 
```
TrackPlayer.registerPlaybackService(() => require('./service.js'));
```
`index.js` of the project.

**To Reproduce**
1. create project via `expo init` (**Bare workflow!**) (Im aware that this package shouldnt work with the **Managed Workflow ** of expo )
```
npx react-native init Project name
```
2. Create a `service.js` in the root of the project. Example of main
```
import TrackPlayer from 'react-native-track-player';

module.exports = async function() {
    TrackPlayer.addEventListener('remote-play', () => {
        TrackPlayer.play();
    })
};
```
3. Register service `index.js`
```
TrackPlayer.registerPlaybackService(() => require('./service.js'));
```
4. Run application and app breaks with message
```
 TypeError: null is not an object (evaluating 'TrackPlayer.STATE_NONE')
 Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
```

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
```
System:
    OS: macOS 11.2
    CPU: (8) arm64 Apple M1
    Memory: 840.94 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /opt/homebrew/opt/node@14/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 6.14.13 - /opt/homebrew/opt/node@14/bin/npm
    Watchman: 2021.05.31.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

What `react-native-track-player` version are you using?
Are you testing on a real device or in the simulator? Which OS version are you running?
Testing on a real device: OPPO A72

**Code**
Please, share the code that is causing the issue
```
// in index.js
TrackPlayer.registerPlaybackService(() => require('./service.js'));
```
Thanks in advances

**Comment by rewdt** [comment]
I'm currently experiencing the same thing right now

**Comment by erick-hdz-sinergis** [comment]
I'm currently experiencing the same thing right now 😭 HELP!!!

**Comment by rewdt** [comment]
@erick-hdz-sinergis , for me the error happened because the documentation was not updated and some of the parameters have been deprecated in the newer version so just replacing the outdated imports with the newer syntax resolved it for me

**Comment by erick-hdz-sinergis** [comment]
> for me the error happened because the documentation was not updated and some of the parameters have been deprecated in the newer version so just replacing the outdated imports with the newer syntax resolved it for me

Could you be more specific with the parameters that you modified?

**Comment by erick-hdz-sinergis** [comment]
> @erick-hdz-sinergis , for me the error happened because the documentation was not updated and some of the parameters have been deprecated in the newer version so just replacing the outdated imports with the newer syntax resolved it for me

Could you show me yours index.js and service.js please?

**Comment by rewdt** [comment]
My index.js and service.js are pretty much identical to what is above. I'm not on my system at the moment though. Once I'm home I would update them
