### ISSUE TITLE
Can't play audio from local storage

### ISSUE THREAD

**Issue by musabgulfam** [DoubleSymmetry/react-native-track-player#1183]
This library cannot play audios of the local storage, despite giving it all the necessary permissions.

```
await TrackPlayer.add({
        id: 'trackId',
        url: "file:///data/user/0/com.riderguide/files/1.mp3",
        title: 'Track Title',
        artist: 'Track Artist',
    });

    // Start playing it
  await TrackPlayer.play()
```
"react-native-track-player": "^1.2.7"

System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Memory: 158.36 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.13.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.7.6 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found

**Comment by babarbahadur** [comment]
Same here :(

**Comment by babarbahadur** [comment]
1) I downgraded to "react-native-track-player": "^1.2.4",
2) Secondly i was using separate function for android / iOS so i disabled the one for iOS. May be that was causing some issue because one player was registering with the link and other with the local storage link.

**Comment by musabgulfam** [comment]
Solved the issue, the url might be incorrect.
