### ISSUE TITLE
Enum cases with associated values cannot be marked potentially unavailable

### ISSUE THREAD

**Issue by DennisdeWitNL** [DoubleSymmetry/react-native-track-player#1185]
Dear,

With the introduction with iOS 15 and Xcode 13, I have discovered a bug. I can no longer compile an app for iOS 15. The problem is in react-native-track-player/Vendor/SwiftAudio/Classes/NowPlayingInfoController/NowPlayingInfoProperty/NowPlayingInfoProperty

The problem is with the following code:

`public enum NowPlayingInfoProperty: NowPlayingInfoKeyValue {
    
    /**
     The identifier of the collection the now playing item belongs to.
     The identifier can be an album, artist, playlist, etc.
     */
    case collectionIdentifier(String?)
    
    /**
     The available language option groups for the now playing item.
     Value is an array of MPNowPlayingInfoLanguageOptionGroup items. Only one language option in a given group can be played at a time.
     */
    case availableLanguageOptions([MPNowPlayingInfoLanguageOptionGroup]?)
    
    /**
     The URL pointing to the now playing item's underlying asset.
     This constant is used by the system UI when video thumbnails or audio waveform visualizations are applicable.
     */
    @available(iOS 10.3, *)
    case assetUrl(URL?)`

Resulting in: Enum cases with associated values cannot be marked potentially unavailable (@available(iOS 10.3, *))

I use react-native-track-player 1.2.3. Any solutions?

**Comment by DennisdeWitNL** [comment]
Edit: I installed react-native-track-player 1.2.7 and it seems the problem is fixed now.

**Comment by aanalmehta-sa** [comment]
Hey, Did you get any solution?

**Comment by DennisdeWitNL** [comment]
No. I just changed iOS 10.3 to iOS 10 for now.

**Comment by Ogala** [comment]
This solved it for me as well.

**Comment by sierrakn** [comment]
I would like to reopen this issue

**Comment by oliveirasWell** [comment]
Me too, we're getting close to release for iOS 15, so we hope this fixed soon 

> I would like to reopen this issue

**Comment by redbluenat** [comment]
I also have this issue with Xcode 13, would be nice to fix it. Any permanent solutions for it?

**Comment by h3nk42** [comment]
Also having the issue in Xcode 13, trying to build on emulator with ios 11.4 or higher throws this error. Changing Deployment Target doesnt change anything.

**Comment by DennisdeWitNL** [comment]
Did you all try version @2.1.0? That should fix this issue. https://www.npmjs.com/package/react-native-track-player/v/2.1.0

**Comment by h3nk42** [comment]
Im running @1.2.3. Ive fixed the issue by going into xCode Pods / Development Pods / react-native-track-player and changing Deployment Target from ios 10.0 to 11.0

**Comment by praisedavid787** [comment]
> Did you all try version @2.1.0? That should fix this issue. https://www.npmjs.com/package/react-native-track-player/v/2.1.0

Facing same issue with this version, hope there is fix in the works.

**Comment by Nodirbek-Sharipov** [comment]
this error occurred to me when I updated my xCode to 13.2.1, and fixed it by upgrading  react-native-track-player to v:2.1.2. And changed `platform :ios, '11.0'` from `platform :ios, '10.0'`. The rest is linking, pod installing and following react-native-track-player installation docs
