### ISSUE TITLE
Build Error MacOS 

### ISSUE THREAD

**Issue by HP161** [DoubleSymmetry/react-native-track-player#1189]
**Describe the bug**

after install package then build app issue bug:
"event2/event-config.h' file not found".
Please help me!
thank you very much!

![1c7dc58b3ae0cebe97f1](https://user-images.githubusercontent.com/4498007/121837307-71a07500-ccff-11eb-90a1-8f4c994d3f83.jpg)
![881c3d21c64a32146b5b](https://user-images.githubusercontent.com/4498007/121837308-72d1a200-ccff-11eb-916a-b13abfb4a4f3.jpg)

**Environment (please complete the following information):**
I used version 1.2.7
xcode: 12.0
react-native: "0.62.0",
**Code**

**Comment by tinyCoder32** [comment]
That's a very known issue and easy to fix, check this out https://stackoverflow.com/a/66071245
