### ISSUE TITLE
callback fired on "playback-track-changed",gives undefined parameters

### ISSUE THREAD

**Issue by Commaando** [DoubleSymmetry/react-native-track-player#1195]
useTrackPlayerEvents(["playback-track-changed"], async event => {
        console.log('event-----', event)
        if (event.type === TrackPlayer.TrackPlayerEvents.PLAYBACK_TRACK_CHANGED) {
            const track = await TrackPlayer.getTrack(event.nextTrack);
            const { title, artist, artwork } = track || {};
            setTrackTitle(title);
            setArtist(artist);
            // setTrackArtwork(artwork);
        }
    });

this is code from example file ...its doesnt give track info on callback
the event I am getting is undefined..
audio is playing just fine .it switches as soon as button is pressed ,but i want to change song name on ui , for that I need latest track info . and all i am getting is undefined.
point out if I did something wrong in call back fn.

![Screenshot (182)](https://user-images.githubusercontent.com/65127203/123938792-133ced00-d9b5-11eb-80f5-95f1d3cc90d2.png)

**Comment by DamnProxy** [comment]
change your if condition to this  => if (event.type === TrackPlayer.TrackPlayerEvents.PLAYBACK_TRACK_CHANGED && event.nextTrack != null)
and it should set it

**Comment by Commaando** [comment]
Thanks @DamnProxy  , my condition was exactly the same. It was not working .
but I figured out what I was doing wrong . I have tracks locally .while making track objects I did not assigned id keyword,which I realised is a very must field in track objects to have . yet somehow in documentation it is not mentioned.

**Comment by Commaando** [comment]
I like this rn Track Player library . but the documentation is very misleading . I think the the documentation is updated for upcoming version of rn Track player, not for the version which we get from npm install
