### ISSUE TITLE
Player stays in loading state on iOS 

### ISSUE THREAD

**Issue by BjoernRave** [DoubleSymmetry/react-native-track-player#1198]
On android everything works fine.

On iOS however when trying to play an audio (i'ts a stream of a ca. 7 min audio file from aws s3) the player state stays in loading.

I tried it first on 1.2.7 and then on 2.x, same problem.

Some time I also created a fork of the repo, where I added my audio file in the example: https://github.com/BjoernRave/react-native-track-player

This is an example of an audio file, which doesn't work: https://speakeroo.s3-eu-west-1.amazonaws.com/audios/.fd077a55-f49e-410a-9a6d-c444deb1b049.ogg

I already tried `waitForBuffer: true `

**Comment by dcvz** [comment]
@BjoernRave this is an issue with the ogg vorbis format. Which has been reported in #207. I will close this for now and any updates will happen in that issue.
