### ISSUE TITLE
Add support for request headers

### ISSUE THREAD

**Issue by jessypouliot98** [DoubleSymmetry/react-native-track-player#1201]
**Is your feature request related to a problem? Please describe.**
I need an audio player that allows me to get file from network that is "hidden" behind a security layer. In this case, I need the referrer_url to be XYZ to access the content on AWS

**Describe the solution you'd like**
instead of passing only a url, to pass an object with { url, headers }
```
const file = {
    url: 'https://someurl.aws.com/somefile.mp3',
    headers: {
        referrer_url: 'http://localhost:8080',
    },
}
```

```
TrackPlayer.add({
    file: file,
    title: 'Pure (Demo)',
    artist: 'David Chavez',
    artwork: 'https://i.scdn.co/image/e5c7b168be89098eb686e02152aaee9d3a24e5b6',
    duration: 28,
  });
```

**Describe alternatives you've considered**
```
TrackPlayer.add({
    url: 'https://someurl.aws.com/somefile.mp3',
    headers: { // or requestHeaders if it can interfere with the track file headers
        referrer_url: 'http://localhost:8080',
    },
    title: 'Pure (Demo)',
    artist: 'David Chavez',
    artwork: 'https://i.scdn.co/image/e5c7b168be89098eb686e02152aaee9d3a24e5b6',
    duration: 28,
  });
```

**Additional context**
For my use case it's to add a referrer_url to the request, but I could see having to access a POST request with a payload maybe or just have an auth token passed as a payload for real authentication. Url params are not secured, so I think this would be a nice feature

**Comment by jessypouliot98** [comment]
For now I am considering downloading it in memory and setting track url as a blob. But that is not performant and sketchy code.

**Comment by jessypouliot98** [comment]
My bad, just found out it already has support after making my blob work

http://react-native-track-player.js.org/documentation/#track-object

**Comment by martin-richter-uk** [comment]
I doesn't work for me on Android.
