### ISSUE TITLE
SeekTo a position where it's not buffered yet will pause the play, is there any way to avoid that? I still want the track to keep playing. 

### ISSUE THREAD

**Issue by liviavinci** [DoubleSymmetry/react-native-track-player#1203]
SeekTo a position where it's not buffered yet will pause the play, is there any way to avoid that? I still want the track to keep playing.

**Comment by NguyenHoangNhatPhi** [comment]
@liviavinci  You can add waitForBuffer: true in  setupPlayer({ waitForBuffer: true }) to fix this issue

**Comment by dcvz** [comment]
@liviavinci does this sort out your issue?

**Comment by dcvz** [comment]
Will close it now, due to inactivity. Feel free to comment again @liviavinci if this was not solved.
