### ISSUE TITLE
Imprecise seeking with track player when chunking audio

### ISSUE THREAD

**Issue by Sidharth1999** [DoubleSymmetry/react-native-track-player#1205]
**Describe the bug**

We are having issues seeking precisely when implementing audio chunking using the HLS streaming protocol on iOS devices. It seems that the track player seeks correctly if the seek destination is within the same audio chunk, but if we seek to a point outside the current audio chunk, it only and always seeks to the beginning of that audio chunk.

Here is a [sample audio file ](https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8)that suffers from this issue (but the issue is with any audio file)

Would appreciate some help on how to deal with this issue.

**Environment:**
`react-native info`
```
System:
    OS: macOS 11.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 192.47 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.22.0 - ~/.nvm/versions/node/v10.22.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v10.22.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.6 - /Users/sidharthramanan/anaconda3/bin/javac
    Python: 3.7.1 - /Users/sidharthramanan/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
`"react-native-track-player": "^1.2.7"`
Issue exists on any simulator and on a real device

**Code**
TrackPlayer setup:
```

 await TrackPlayer.setupPlayer({
    maxCacheSize: 10000,
    waitForBuffer: true,
  }).then(() =>
    TrackPlayer.updateOptions({
      capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_STOP,
        TrackPlayer.CAPABILITY_SKIP,
        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
        TrackPlayer.CAPABILITY_SEEK_TO,
      ],
    })
  );
```

Track object:
```
const fullTrack: TrackPlayer.Track = {
    id: fullTrackID,
    url: fullSongURL, // Load media from local
    duration: duration / 1000,
    title: title,
    artist: artist?.username ?? "",
    genre: tags?.[0] || "",
    artwork: imageURL, // Load artwork from the network
    pitchAlgorithm: TrackPlayer.PITCH_ALGORITHM_MUSIC,
    type: "hls",
  };
```

**Comment by eli-stewart** [comment]
I am having this issue as well! The seekTo function works perfectly when doing normal streaming but when I use the HLS protocol, I get the same behavior Sidharth described above

**Comment by eli-stewart** [comment]
This bug is still occurring occasionally for me even after updating the library. Is is now very infrequent but i have seen it happen a couple of times
