### ISSUE TITLE
Release 2.0.0-rc18 : Unable to resolve module ./trackPlayer

### ISSUE THREAD

**Issue by bahmandamia6982** [DoubleSymmetry/react-native-track-player#1207]
**Issue**
Unable to resolve module ./trackPlayer @ release v2.0.0-rc18
I was searching for trackPlayer.js in lib folder`(node_modules/react-native-track-player/lib)` but this file wasn't included after install by npm.
i used `npm install react-native-track-player@next` to install.

**Questions**
- How can I fix that?
- When latest release of v2 comes out?  

**Environment**
React native 0.64.2
Windows 11 Build 22000.64
VSCode 1.58.0

**Comment by bahmandamia6982** [comment]
Fixed ♥️

**Comment by limaho** [comment]
@bahmandamia6982  What did you do to make it work?

**Comment by bahmandamia6982** [comment]
> @bahmandamia6982 What did you do to make it work?

*#versions overlap*
I just cleaned the build folder (android) using `.\gradlew clean`.
Hope this helps...
