### ISSUE TITLE
iOS problem with different extensions

### ISSUE THREAD

**Issue by markegor** [DoubleSymmetry/react-native-track-player#1209]
Hey everyone. I have unresolved problem: react-native-track-player works amazing in my app on Android, but on iOS - i cannot play any webm or m4a audio file (maybe other extensions don't work too), for example: https://filesamples.com/samples/audio/m4a/sample3.m4a . iOS device plays only MP3 files (in my case).

I have tried "waitForBuffer" - setUp option. I have tried add contentType to the "Track Object", but any tries do not work  =(

Any ideas?) Thanks)

**Comment by dcvz** [comment]
I clicked on the link and it seems its not a working link
