### ISSUE TITLE
Previous audio keeps playing for a second or 2, after skipping to another audio. 

### ISSUE THREAD

**Issue by musabgulfam** [DoubleSymmetry/react-native-track-player#1215]
After I skip to another audio, previously loaded audio keeps playing for a short time till the new audio is loaded and starts playing. How to stop this behaviour, or at-least show a loading indicator instead of the duration of previously loaded audio.

**Comment by DennisdeWitNL** [comment]
I switch between multiple audio streams and don’t have this issue. What version are you using? I would set waitForBuffer to false. And once you stop the track, you could do TrackPlayer.stop() for iPhone and TrackPlayer.reset() for Android. Then add the new song to the queue.

**Comment by musabgulfam** [comment]
Thanks @DennisdeWitNL, the bug is resolved.
