### ISSUE TITLE
Playlist controls (ie loop/shuffle/repeat)

### ISSUE THREAD

**Issue by Alanz2223** [DoubleSymmetry/react-native-track-player#122]
Does this library come with an API to control how to music plays? I've read through the docs and since I wasn't able to find it, I would appreciate some suggestions as to how to implement this behavior. I am using redux and redux-saga to handle state/effects. I've thought about implementing this logic within the listeners whenever events are triggered. But a lot of the time the app will be in the background or the screen will be locked. Does the JS still execute in those cases? Still a bit new, Thanks.

**Comment by joshmarinacci** [comment]
I've had the same question. I'm building an music player that should still loop even if it's in the background.

**Comment by joshmarinacci** [comment]
I've found this from Apple's iOS docs: 

https://developer.apple.com/documentation/mediaplayer/mpremotecommandcenter/1649694-changerepeatmodecommand

It looks like we could update the `RNTrackPlayer.update` function to set a target for the changeRepeatModeCommand and changeShuffleModeCommand objects.  This should make it repeat and shuffle. However, once we are getting these events, I don't know how to use them (yet).

**Comment by Alanz2223** [comment]
Add an event listener whenever the track ends and then call play with the
songs I'd.. it works even in the bg

**Comment by joshmarinacci** [comment]
It looks like the react native code is wrapping RNTrackPlayer which wraps MediaWrapper which wraps AudioPlayer from the vendor dir. This class calls AVPlayer. Unfortunately this class doesn't have shuffle. It's designed to only manage one media object at a time. There is an AVPlayerQueue class, but I'm guessing it would require updating a lot of code to use this.

https://developer.apple.com/documentation/avfoundation/avplayer

**Comment by iThinker** [comment]
@Alanz2223 can you please share a snippet of code that you use?

**Comment by joshmarinacci** [comment]
Here's what I ended up doing.  I have an event handler to get all of the track changed events. If repeat is turned on then it checks if the next track is the one we are repeating. If so it does nothing. If not, it will pause the player, then do 'skip' to the track to be repeated, then play again.

        TrackPlayer.registerEventHandler((data)=>{
            console.log("got event",data.type,data)
            TrackPlayer.getCurrentTrack().then((track_id)=>{
                this.currentIndex = this.tracks.findIndex(t => t.id === track_id)
            })

            if(data.type === 'playback-track-changed') {
                if(this.repeat) {
                    //don't mess with anything if already on the track to repeat
                    if(data.nextTrack === this.trackToRepeat) return
                    if(!data.track && data.nextTrack && this.trackToRepeat === null) {
                        this.trackToRepeat = data.nextTrack
                    } else {
                        TrackPlayer.pause()
                        TrackPlayer.skip(this.trackToRepeat).then(()=>TrackPlayer.play())
                    }
                }
            }

**Comment by iThinker** [comment]
I maintain queue on js side and feed tracks one by one when queue ended event fires. Not sure about performance yet though.

**Comment by iThinker** [comment]
@joshmarinacci does it work wen application is in background and it is playing last track? I did not try this approach. But with my single item queue I cannot get next/previous controls to work.

**Comment by iThinker** [comment]
There are some issues issue with observing `playback-queue-ended` and feeding items one by one. On lock screen there is a noticeable blink until next item is supplied. And new item does not get current time on lock screen updated. Here is my asset update code:
```if (currentFile && !!currentFile.name) {
      await trackPlayer.remove(currentFile.name)
    }
    await trackPlayer.add(trackPlayerAsset)```
Any ideas how to make it smoother? With native queue there are no such issues. I am testing on iOS only so far.

**Comment by iThinker** [comment]
Moving making track addition and playing track before doing anything else (e.g. updating UI) did the trick.

**Comment by jdrorrer** [comment]
@iThinker how were you able to fix the blinking issue on lock screen? I wasn't sure since the UI is managed by this package

**Comment by iThinker** [comment]
@jdrorrer my code is ugly. But basically the issue was too much code doing unrelated stuff before playing next track.
Here is my current code:

    const shouldRemoveCurrentFile = currentFile && !!currentFile.name
    if (shouldRemoveCurrentFile && isAndroid) {
      await trackPlayer.remove(currentFile.name)
    }

    const trackPlayerAsset = {
      id: file.name,
      url: file.source,
      title: file.name,
      artist: ''
    }
    await trackPlayer.add(trackPlayerAsset)

    if (autoplay) {
      await trackPlayer.play()
    }

    if (shouldRemoveCurrentFile && isAndroid == false) {
      await trackPlayer.remove(currentFile.name)
    }

**Comment by ithustle** [comment]
+1

**Comment by PiyushGaurav** [comment]
I tried this to shuffle queue 
`shuffleArray = (array) => {
		let currentIndex = array.length, temporaryValue, randomIndex;
		// While there remain elements to shuffle...
		while (0 !== currentIndex) {
			// Pick a remaining element...
			randomIndex = Math.floor(Math.random() * currentIndex);
			currentIndex -= 1;
			// And swap it with the current element.
			temporaryValue = array[currentIndex];
			array[currentIndex] = array[randomIndex];
			array[randomIndex] = temporaryValue;
		}
		return array;
	};
	shuffle = async () => {
		const queue = await TrackPlayer.getQueue();
		const shuffledQueue = this.shuffleArray(queue); // any shuffle logic
		await TrackPlayer.destroy();
		await TrackPlayer.setupPlayer();
		await TrackPlayer.add(shuffledQueue);
		await TrackPlayer.play();
	};`

**Comment by PiyushGaurav** [comment]
I tried this to shuffle Queue
```
shuffleArray = (array) => {
		let currentIndex = array.length, temporaryValue, randomIndex;
		// While there remain elements to shuffle...
		while (0 !== currentIndex) {
			// Pick a remaining element...
			randomIndex = Math.floor(Math.random() * currentIndex);
			currentIndex -= 1;
			// And swap it with the current element.
			temporaryValue = array[currentIndex];
			array[currentIndex] = array[randomIndex];
			array[randomIndex] = temporaryValue;
		}
		return array;
	};
	shuffle = async () => {
		const queue = await TrackPlayer.getQueue();
		const shuffledQueue = this.shuffleArray(queue);
		await TrackPlayer.destroy()
		await TrackPlayer.setupPlayer();
		await TrackPlayer.add(shuffledQueue);
		await TrackPlayer.play();
	};
```

**Comment by ashokkumar88** [comment]
@PiyushGaurav it will work if we make the shuffle off again?

**Comment by YajanaRao** [comment]
Currently I am able to add duplicate songs to queue. Is there a possibility to remove duplicates from queue without writing to write JavaScript code ?

**Comment by YajanaRao** [comment]
Is it not better to handle queue functionality from JavaScript ?

**Comment by marksteele** [comment]
+1 on getting loop/shuffle please.

Managing queue in JS means background play stops working (at least it does for me).

**Comment by art1373** [comment]
+1

**Comment by nthtrung09it** [comment]
+1

**Comment by rxng8** [comment]
+1

**Comment by AlanQuadros** [comment]
+1

**Comment by cenaHara** [comment]
+1

**Comment by Rimma-A** [comment]
+1

**Comment by Mangirish-Bhagat** [comment]
+1

**Comment by bradleyflood** [comment]
Added to Project backlog. Obviously this is a highly requested feature. We will review. Thanks all

**Comment by justinhandley** [comment]
I know that this is in progress, but I wanted to chime in with my own request.  I've been playing with the audio player trying to get a seamless loop - i.e. no space between audio file 1 and audio file 2 (or, in my case, trying to reset and play audio file 1 in a seamless loop). Does anyone know if this is possible?  No matter how I configure end of queue actions and loading on a next track I always get a little pause between tracks.
