### ISSUE TITLE
error at importing useProgress

### ISSUE THREAD

**Issue by b-tiwari** [DoubleSymmetry/react-native-track-player#1221]
**Describe the bug**
Error when using [useProgress hook](https://react-native-track-player.js.org/getting-started/#progress-updates)

**To Reproduce**
when importing {useProgress} hook from the library, get error - Module '"react-native-track-player"' has no exported member 'useProgress'.

![4](https://user-images.githubusercontent.com/13605214/127960070-994e6f30-53ec-44d9-9fee-2dcc67bf3ed2.png)

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.

![3](https://user-images.githubusercontent.com/13605214/127728156-f2e9bab9-05b5-40e0-b918-b0146b966f6c.png)

What `react-native-track-player` version are you using?
"react-native-track-player": "^1.2.7",

Are you testing on a real device or in the simulator? Which OS version are you running?
Android - real device
iOS - simulator

**Code**
as in above screenshot

**Comment by edgargrs** [comment]
For version ` "^1.2.7"`

You have to import it like this
`import {useTrackPlayerProgress} from 'react-native-track-player';`

`useProgress` is for the version `2.0`

**Comment by nerdaliciousCH** [comment]
what does your yarn.lock or package-lock.json say?
If you have in your package.json
`"react-native-track-player": "^2.0.0-rc18"`, this will resolve to 2.0.0-rc9 which doesn't have useProgress.
"react-native-track-player": "2.0.0-rc18" without the carret will resolve to 2.0.0-rc18 which works fine.

**Comment by b-tiwari** [comment]
got it, thanks, yeh I see `useTrackPlayerProgress` , didn't know [ this documentation](https://react-native-track-player.js.org/) is for 2.0
