### ISSUE TITLE
[Android] Dismissing Media Controls on Android 11 Breaks Playback

### ISSUE THREAD

**Issue by uzegonemad** [DoubleSymmetry/react-native-track-player#1226]
**Describe the bug**
Android 11 has updated media controls. One of the features of these controls is the ability to swipe to dismiss them from the notification panel. One of my users reports that when doing this on their Pixel 3a, playback stops and is unable to be resumed. The only way to start playback again is to fully close and reopen the app.

**To Reproduce**
I'm not able to reproduce this on an Android 11 emulator (and don't have access to an Android 11 device at the moment), but the steps are as simple as:
1. Launch app
2. Begin playing media
3. Pull down notification panel from the top bar
4. Swipe media controls to the side, dismissing them

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
```info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 768.14 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.13.0 - /var/folders/9v/b24jnwd51ws4y9f21tn9syfm0000gn/T/yarn--1628718462990-0.35822567393144045/node
    Yarn: 1.22.5 - /var/folders/9v/b24jnwd51ws4y9f21tn9syfm0000gn/T/yarn--1628718462990-0.35822567393144045/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2, 31.0.0
      System Images: android-23 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6821437
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_65 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

What `react-native-track-player` version are you using?
2f7ddf0cd68b4682cfbf506c0df6cf8ca1582b40 with some minor modifications and pull requests brought in via patch-package

Are you testing on a real device or in the simulator? Which OS version are you running?
User experiences the issue on a real device, Android 11. I'm unable to recreate on sim and don't have access to a physical Android 11 device.

**Code**
N/A

**Comment by bradleyflood** [comment]
Thanks @uzegonemad and sorry for the late reply on this one.

We are doing a major Android rewrite on #1371 so I expect this to be addressed.

I'm going to close this Issue for now, as I see you also are unable to replicate and have minor changes via patch-package so it's not something we could investigate or troubleshoot ourselves. 

Would love to get your help in testing the Android rewrite though!

Thank you
Brad
