### ISSUE TITLE
Multiple Tracks Playing Same Time

### ISSUE THREAD

**Issue by Haseeba393** [DoubleSymmetry/react-native-track-player#1228]
First of all, really thanks for giving such a nice library to use. I'm here not to discuss on issue. I'm here to request a feature in your library. I got a new use case where I have to play 2 audios at same time. I tried.every possible solution to solve but all in vain. I searched and used almost all the libraries but can't beat your one.

I just want to request, that can you please add this thing in your library where I can play 2 audios same time.

Alternatively, I didn't know I will be able to do it. SO may be I'll drop it.

**Comment by neXorianus** [comment]
as of #172 it seems this is not possible with this plugin

**Comment by Desintegrator** [comment]
were you able to implement such feature with this or another module?

**Comment by Haseeba393** [comment]
@Desintegrator I have used this library and made my own one which is able to play 2 tracks a a time. Just you need to copy and entire code and replicate it for 2nd track.

**Comment by Desintegrator** [comment]
@Haseeba393 unfortunately i need more than 2 players. I don't need to play them at the same time, but i have different audio files (dynamic count, maybe 1, maybe 100+) and user should be able to switch between players. One player with playlist is not an option since app logic/design

**Comment by bradleyflood** [comment]
Thanks all. I've noted this as a feature request, though we are all at full capacity so we are definitely open to PRs! Thank you
