### ISSUE TITLE
Grant Discord access

### ISSUE THREAD

**Issue by DennisdeWitNL** [DoubleSymmetry/react-native-track-player#1230]
Dear,

Could you grant me access to the Discord community? I can’t open the link anymore. I know @dcvz was in a bad mood today, but I didn’t do anything wrong to the community in general. This is the only way to get support for this module. 

I would like to talk to the community. 

Thank you,
Dennis

**Comment by dcvz** [comment]
Hi @DennisdeWitNL -- we're willing to grant you access again but ask that you please be respectful towards the maintainers and the people in the community. The community is also ran and managed by the maintainers who put their effort into this lib and do their best to support the people using it.

Let's start again. I'll grand you access now. Please, keep the above in mind.
