### ISSUE TITLE
 TypeError: null is not an object

### ISSUE THREAD

**Issue by mripqi** [DoubleSymmetry/react-native-track-player#1237]
**Describe the bug**
Hello, i want to add track-player to my project. But when i add 
`import TrackPlayer from 'react-native-track-player'`
my app will crash and the error message is
` TypeError: null is not an object (evaluating 'TrackPlayer.RATING_HEART')`

**To Reproduce**
- npm install react-native-track-player
- add "A basic example of how to play a track code" to project

**Environment**

> System:
>     OS: Linux 5.11 Ubuntu 20.04.2 LTS (Focal Fossa)
>     CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
>     Memory: 1.91 GB / 11.58 GB
>     Shell: 5.0.17 - /bin/bash
>   Binaries:
>     Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
>     Yarn: 1.22.5 - /usr/bin/yarn
>     npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
>     Watchman: Not Found
>   SDKs:
>     Android SDK: Not Found
>   IDEs:
>     Android Studio: Not Found
>   Languages:
>     Java: 1.8.0_292 - /usr/bin/javac
>     Python: Not Found
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 16.13.1 => 16.13.1 
>     react-native: 0.63.4 => 0.63.4 
>   npmGlobalPackages:
>     *react-native*: Not Found

**What react-native-track-player version are you using?**
2.0.3

**Are you testing on a real device or in the simulator?** 
Android Emulator: Galaxy Nexus API 30

**Which OS version are you running?**
 Linux 5.11 Ubuntu 20.04.2 LTS (Focal Fossa)

**Code**
I get the error running the app

tried npm install again and ./gradlew clean, still get the same error

**Comment by dcvz** [comment]
@mripqi the imports have changed in v2 -- please read the migration section of the README for more details :)
https://github.com/DoubleSymmetry/react-native-track-player#%EF%B8%8F-v2-migration-guide
