### ISSUE TITLE
Preloading tracks from queue

### ISSUE THREAD

**Issue by MountBaqer** [DoubleSymmetry/react-native-track-player#1238]
**Is your feature request related to a problem? Please describe.**
Currently when I `skipToNext()` the player pauses for a second before playing the next track.  

**Describe the solution you'd like**
It would be great if we have an option for the track player to check and preload tracks up in the queue so that when we skip, we can play immediately. This would be similar to how Spotify is doing it.

**Additional context**
It seems that this feature was requested before for 1.0 release here #196 but it doesn't seem to have been solved yet for any recent release.

**Comment by klaaz0r** [comment]
Agreed, some options I would love to see is how much should be "pre buffered" and amount of tracks to be loaded

**Comment by bradleyflood** [comment]
Agreed, this would be very nice. I've added this to the roadmap and will review it with the team for a future release. Thanks!

**Comment by GabrieleMazzola** [comment]
> Agreed, this would be very nice. I've added this to the roadmap and will review it with the team for a future release. Thanks!

Hey! 
Has this feature ever been implemented? I am facing an issue which is likely related to this.

Thanks!
