### ISSUE TITLE
Require Cycle Warning

### ISSUE THREAD

**Issue by redbluenat** [doublesymmetry/react-native-track-player#1244]
**Describe the bug**

```
Require cycle warning in terminal:

Require cycle: node_modules/react-native-track-player/lib/index.js -> node_modules/react-native-track-player/lib/hooks.js -> node_modules/react-native-track-player/lib/index.js

```

**To Reproduce**

After yarn start I have a warning 

<img width="591" alt="Screen Shot 2021-08-26 at 11 26 56 am" src="https://user-images.githubusercontent.com/15861135/130885171-948e9acf-8b3f-4e21-8612-b5113553600e.png">

**Environment:**
`react-native` - 0.63.4
`react-native-track-player` - 2.0.1

**Comment by burdisal** [comment]
I am also running into this warning, but with a slightly different environment. It happens right on app launch. I'm using the library on iOS, not sure if the issue exists on other platforms though.

`react-native` - 0.65.1
`react-native-track-player` - 2.0.3

**Comment by dcvz** [comment]
I see this warning as well, something we'll have to look into! Contributions are welcome :)

**Comment by bradleyflood** [comment]
@redbluenat or @burdisal is this something you could help us with? Love to see a PR! thank you :) 😊

**Comment by dcvz** [comment]
I think we may have actually fixed this issue with this commit: https://github.com/DoubleSymmetry/react-native-track-player/commit/4ee2cac155f9f1767cb79bbafe4cd0b78bea2843

**Comment by federicomiralles** [comment]
The require cycle warning is back again, now on version v4.0.1:
![Simulator Screenshot - iPhone 13 - 2023-11-20 at 13 51 17](https://github.com/doublesymmetry/react-native-track-player/assets/53195495/d7472bf3-90b8-4953-ac3e-3198068ebe8b)
