### ISSUE TITLE
Remove track from the queue is not working

### ISSUE THREAD

**Issue by IamDhana** [DoubleSymmetry/react-native-track-player#1245]
**Describe the bug**
Remove track from the queue is not working as expected.
Teackplayer.remove() not throwing any error but if I call getQueue() it returns the old data.

**To Reproduce**

1. Add tracks to playlist 
2. List tracks using getQueue() Result [{id: 'adc'}, {id: 'dbe'}]
3. Remove track abc from playlist 
4. List tracks using getQueue() Result [{id: 'adc'}, {id: 'dbe'}]
5. Expected Result [{id: 'dbe'}]

**Environment (please complete the following information):**

react-native-track-player version - "react-native-track-player": "^1.2.7", 

**Code**
const handleRemoveFromPlaylist = async (id) => {
    const queueList = await TrackPlayer.getQueue();
    console.log(queueList, 'old');
    const track = queueList.find((queue) => queue.id === id);
    console.log(track && track.id, 'track');
    if (track && track.id) await TrackPlayer.remove([track.id]);
    const newww = await TrackPlayer.getQueue();
    console.log(newww, 'new');
  };

**Comment by m-Nightly** [comment]
Just looked into the code, you can't remove current audio from the queue.

**Comment by IamDhana** [comment]
We should mention in the documentation about we can't remove the current track from the queue. So I made the following workaround to remove the track from the queue including the current track.

  ```
const handleRemoveFromPlaylist = async (id) => {
    const queueList = await TrackPlayer.getQueue();
    const track = queueList.find((queue) => queue.id === id);
    const currentTrackId = await TrackPlayer.getCurrentTrack();
    if ((track && track.id) === currentTrackId) {
      if (queueList.length > 1) {
        await TrackPlayer.pause();
        const removeIndex = queueList.findIndex((queue) => queue.id === id);
        if (removeIndex === queueList.length - 1) {
          await TrackPlayer.skipToPrevious();
        } else {
          await TrackPlayer.skipToNext();
        }
        await TrackPlayer.remove([track.id]);
      } else {
        await TrackPlayer.reset();
      }
    } else if (track && track.id) {
      await TrackPlayer.remove([track.id]);
    }
  };
```

**Comment by Lightandlovepeace** [comment]
I made this workaround: 

`const [queue, setQueue] = useState([]);
  const [currentTrack, setCurrentTrack] = useState(0);

  async function loadPlaylist() {
    //console.log('removed!')
    TrackPlayer.reset();
    if (global.frequency == 174) {
      TrackPlayer.add(music174hz);
      const queue = await TrackPlayer.getQueue();
      setQueue(queue);
    }
    if (global.frequency == 285) {
      TrackPlayer.add(music285hz);
      const queue = await TrackPlayer.getQueue();
      setQueue(queue);
    }

  }

  useEffect(() => {
    loadPlaylist();
  }, []);`

reset the trackplayer before adding new tracks to it.
