### ISSUE TITLE
Pod Install has LICENSE warning

### ISSUE THREAD

**Issue by burdisal** [DoubleSymmetry/react-native-track-player#1248]
**Describe the bug**
I am getting a warning when running `pod install`, related to the CocoaPod attached to this package:
```
[!] Unable to read the license file 'LICENSE' for the spec 'SwiftAudioEx (0.13.2)'
```
This shows four times at the very end of the Pod install.
![Screen Shot 2021-08-31 at 11 52 48 AM](https://user-images.githubusercontent.com/89851188/131535379-57167451-2ef5-4de7-99e0-9ad30d6b61f6.png)

**To Reproduce**
run `pod install`

**Environment**
`react-native` - 0.65.1
`react-native-track-player` - 2.0.3
Xcode - 12.4
CocoaPods - 1.10.1

**Comment by Tebrynn** [comment]
I've got same problem

**Comment by reidgarner** [comment]
Same.

**Comment by dimadeveatii** [comment]
Same, v2.1.0

**Comment by etsraphael** [comment]
Same here, and impossible to build the app after this error

**Comment by therealkh** [comment]
I have same error

**Comment by dcvz** [comment]
This is just a warning and does not affect the pod install process. This does not cause build errors.

We'll still aim to fix it in a later release though.

**Comment by nguyenductoan1995** [comment]
how to fix it 
thanks

**Comment by nguyenductoan1995** [comment]
> @nguyenductoan1995 looks like this is a different bug. looks like you're using Xcode 13. Make sure you're on the latest version of react-native-track-player where we a
<img width="1114" alt="Screen Shot 2021-10-13 at 13 36 18" src="https://user-images.githubusercontent.com/24264218/137085386-21956949-a914-4039-99b7-77e62a3211ae.png">
dded support for Xcode 13.
i can't pod install in lastest version

**Comment by nguyenductoan1995** [comment]
> @nguyenductoan1995 you have to set your minimum deployment target to iOS 11. instead of 10. in the Podfile too.
> 
> Take a look at the CHANGELOG here: https://github.com/DoubleSymmetry/react-native-track-player/blob/main/CHANGELOG.md#210-160921

thank you so much, it resloved

**Comment by bradleyflood** [comment]
Thanks @burdisal are you able to create a PR to fix this?

Cheers
