### ISSUE TITLE
Failed to resolve: com.google.android.exoplayer:exoplayer-core:2.11.4

### ISSUE THREAD

**Issue by akashi7** [DoubleSymmetry/react-native-track-player#1257]
Failed to resolve: com.google.android.exoplayer:exoplayer-core:2.11.4

**Comment by marksturm** [comment]
Same Problem

**Comment by Gautham495** [comment]
I am Facing the same problem and tried for several hours. Please Find a solution to this particular problem.

**Comment by MichaBrugger** [comment]
Had a similar issue. Check [this](https://stackoverflow.com/a/69159366/8469518), did the trick for me.

**Comment by Gautham495** [comment]
> Had a similar issue. Check [this](https://stackoverflow.com/a/69159366/8469518), did the trick for me.

Phenomenal! Finally I found the answer. Thanks for helping me out.

**Comment by MichaBrugger** [comment]
Pleasure, glad it helped 🙌🏼

**Comment by alpha0010** [comment]
Unfortunately only a temporary solution.  JCenter is going offline https://github.com/react-native-community/discussions-and-proposals/issues/331 .

**Comment by MichaBrugger** [comment]
@alpha0010, you're right of course.

If you're looking for an alternative: Check out what @austinried did with [subtracks](https://github.com/austinried/subtracks) (a really cool RNTP project btw). This might not be the 'perfect' solution either, but should leave you a little less vulnerable when jcenter goes offline. That being said, I'm not exactly an expert on this, just thought I'd quickly share since I stumbled over it during my own research 👍🏼

**Comment by alpha0010** [comment]
Project lists binaries as [hosted by Google Maven](https://exoplayer.dev/hello-world.html#adding-exoplayer-as-a-dependency), which has pulled older versions of ExoPlayer.  I tried setting `exoPlayerVersion = '2.15.0'` in my `android/build.gradle` (see supported versions: https://maven.google.com/web/index.html#com.google.android.exoplayer:exoplayer) - it fixed the failed to resolve issue, but broke the code.  Even going back to 2.13.3 (oldest version being served) already has incompatibilities with RNTP.  Seems like the long term solution requires updating the api RNTP uses with ExoPlayer to support newer ExoPlayer versions.

**Comment by alpha0010** [comment]
Oh, duplicate of https://github.com/DoubleSymmetry/react-native-track-player/issues/1235 (which appears to have been closed without full resolution?).

**Comment by GrimDev** [comment]
JCenter is now shut off and exoplayer-core:2.11.4 can't be found without.
So currently this library can't work anywore without update.
Is the pull request of @alpha0010 beeing proceed.

**Comment by MichaBrugger** [comment]
Does anyone have a recommendation on what to do in the meantime? Would you recommend to pull in exoplayer as a submodule directly or is there another alternative?

**Comment by GrimDev** [comment]
> Does anyone have a recommendation on what to do in the meantime? Would you recommend to pull in exoplayer as a submodule directly or is there another alternative?

I think using the @alpha0010's fork is the best alternative while it is not proceed by the react-native-track-player's team.

**Comment by huncrew** [comment]
@GrimDev 

When I try and clone this repo, I'm unable to run the project, I get the error: 
error Unrecognized command "run-android".
info Run "react-native --help" to see a list of all available commands.

Maybe I'm missing something fundamental to how to get react-native apps to run from cloning?

**Comment by dcvz** [comment]
Hey all.. this is a duplicate of this which does have a workaround: https://github.com/DoubleSymmetry/react-native-track-player/issues/1235

We're also working on some updates that will use the latest version of exoplayer therefore fixing the issue. But it's not ready yet.

**Comment by dcvz** [comment]
Hey all.. this is a duplicate of this which does have a workaround: https://github.com/DoubleSymmetry/react-native-track-player/issues/1235

We're also working on some updates that will use the latest version of exoplayer therefore fixing the issue. But it's not ready yet.

**Comment by dcvz** [comment]
I will close the issue as it's a duplicate. Let's continue any further issues there.
