### ISSUE TITLE
Optimizing reactivity on track change with Event.PlaybackTrackChanged

### ISSUE THREAD

**Issue by MartinGio** [DoubleSymmetry/react-native-track-player#1258]
Hi everyone, and thanks to the team for the version 2 !

I have an issue concerning the reactivity of react-native-track-player. I want to play very short tracks (around 0.2 seconds) locally and sync the display with each new track, but it has some delay (around 0.05 or 0.1 seconds).

I tried many different ways, using Event.PlaybackTrackChanged, or useProgress with a low number but this latency is always there.

For those who know well (or created) this module, is there a way to lower this latency, for example with some specific buffersize settings ?

Thanks in advance :-)

**Comment by bradleyflood** [comment]
Hi @MartinGio 

I hope you've been able to find a solution for this. It's not a use-case we cater for, and unfortunately I don't know of any way to improve that. 

Best of luck! And let us know if you find anything suitable.

Cheers
