### ISSUE TITLE
Expo support

### ISSUE THREAD

**Issue by japrozs** [DoubleSymmetry/react-native-track-player#1259]
When will support for expo come out as I desperately need this for an expo project which I can't switch to react-native due to my use-case

**Comment by baochungit** [comment]
+1 to have it working with Expo

**Comment by ucheNkadiCode** [comment]
I agree! would be a great addition!

**Comment by bradleyflood** [comment]
Thanks all. It looks like Expo is supported with these Readme updates here: https://github.com/DoubleSymmetry/react-native-track-player/pull/1250

@ucheNkadiCode @baochungit @japrozs 

Would love to see if these instructions are working for any of you?

Thanks.

**Comment by japrozs** [comment]
thanks!

**Comment by baochungit** [comment]
> Thanks all. It looks like Expo is supported with these Readme updates here: https://github.com/DoubleSymmetry/react-native-track-player/pull/1250
> 
> @ucheNkadiCode @baochungit @japrozs 
> 
> Would love to see if these instructions are working for any of you?
> 
> Thanks.

Unfortunately, It's not working for me. I checked it before but got a silly error, kinds of constant not defined. Anyone success with it?
