### ISSUE TITLE
Previous audio keeps playing, after selecting the next audio

### ISSUE THREAD

**Issue by musabgulfam** [DoubleSymmetry/react-native-track-player#1262]
**Describe the bug**
As the user clicks on the next audio, the previous audio keeps playing for about 2 to 3 seconds, .

**Environment (please complete the following information):**
System:
    OS: macOS 11.5.1
    CPU: (8) arm64 Apple M1
    Memory: 107.19 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.2 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.18.1 - /opt/homebrew/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 31.0.0
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
**"react-native-track-player": "^1.2.7"**

**Comment by dcvz** [comment]
@musabgulfam the library can only play one track at a time.. and the example project doesn't present this issue.

It seems to be that this is likely an issue your code. Can you duplicate the issue in the example project?

**Comment by musabgulfam** [comment]
@dcvz  yes you are right, it could be the issue in my code, and as of ye I can't duplicate the issue in the example project. Thanks.
