### ISSUE TITLE
Remote-duck best practise

### ISSUE THREAD

**Issue by neoassyrian** [DoubleSymmetry/react-native-track-player#1263]
Hi guys,
I need some help with the remote-duck event. How is it possible to detect of the player was playing and then resume play after the "paused" is returned with false.

If paused = false
Then I need to check if player was "playing" and only resume play if it was.

Let's say the user paused the player and is still in background (paused), then the user received a phone call, after they hang up, the player starts playing (for the user might be a sudden play because they were not playing a track when they received the call.

If I detect the state before I pause (when we receive true for "paused"), ios will always be false, which means it will never resume playing (when we receive false for "paused"). Android will work in most cases.

**Comment by dcvz** [comment]
You likely want to keep track locally of whether playback was paused because of a duck event.

Something similar to:
```typescript
if (e.permanent === true) {
				TrackPlayer.stop()
			} else {
				if (e.paused === true) {
					this.wasPausedByDuck = this.state !== State.Paused
					TrackPlayer.pause()
				} else {
					if (this.wasPausedByDuck === true) {
						TrackPlayer.play()
						this.wasPausedByDuck = false
					}
				}
			}

```

**Comment by dcvz** [comment]
I will close this as there has been no more comments. Please checkout out the example app :)
