### ISSUE TITLE
Can't play local files on device or emulator

### ISSUE THREAD

**Issue by akashi7** [DoubleSymmetry/react-native-track-player#1267]
Found recent issue related question
But they resolved the issue by just using the dev branch and that issue was 2 years ago
So was wondering if it had been updated in the main branch

But if not where can i find the dev branch and integrate it in my project

I need to play audio from device (emulator) and my approach  is this way
Const tracks =[
{ id:1, url: "file:///storage/emulated/......}]

So how to procceed

Regards

**Comment by tindoescode** [comment]
Same issue😥

**Comment by tindoescode** [comment]
> Found recent issue related question
> But they resolved the issue by just using the dev branch and that issue was 2 years ago
> So was wondering if it had been updated in the main branch
> 
> But if not where can i find the dev branch and integrate it in my project
> 
> I need to play audio from device (emulator) and my approach is this way
> Const tracks =[
> { id:1, url: "file:///storage/emulated/......}]
> 
> So how to procceed
> 
> Regards

The url parameter must be wrong. Recheck this!

**Comment by akashi7** [comment]
> > Found recent issue related question
> > But they resolved the issue by just using the dev branch and that issue was 2 years ago
> > So was wondering if it had been updated in the main branch
> > But if not where can i find the dev branch and integrate it in my project
> > I need to play audio from device (emulator) and my approach is this way
> > Const tracks =[
> > { id:1, url: "file:///storage/emulated/......}]
> > So how to procceed
> > Regards
> 
> The url parameter must be wrong. Recheck this!

I'm using react-native-get-music-files to get the path of the the file so i think it's not the path problem

**Comment by tindoescode** [comment]
> > Found recent issue related question
> > But they resolved the issue by just using the dev branch and that issue was 2 years ago
> > So was wondering if it had been updated in the main branch
> > But if not where can i find the dev branch and integrate it in my project
> > I need to play audio from device (emulator) and my approach is this way
> > Const tracks =[
> > { id:1, url: "file:///storage/emulated/......}]
> > So how to procceed
> > Regards
> 
> The url parameter must be wrong. Recheck this!

I'm using expo-media-library for requesting file permission.

Then get file by using URL like you, you can take a look at my code: https://github.com/tindoescode/react-native-music-player/blob/master/app/context/AudioProvider.js

**Comment by akashi7** [comment]
> > > Found recent issue related question
> > > But they resolved the issue by just using the dev branch and that issue was 2 years ago
> > > So was wondering if it had been updated in the main branch
> > > But if not where can i find the dev branch and integrate it in my project
> > > I need to play audio from device (emulator) and my approach is this way
> > > Const tracks =[
> > > { id:1, url: "file:///storage/emulated/......}]
> > > So how to procceed
> > > Regards
> > 
> > 
> > The url parameter must be wrong. Recheck this!
> 
> I'm using expo-media-library for requesting file permission.
> 
> Then get file by using URL like you, you can take a look at my code: https://github.com/tindoescode/react-native-music-player/blob/master/app/context/AudioProvider.js

I shifted to expo-media-library now 
And every thing works fine
