### ISSUE TITLE
Switching Tracks via Control Center (Lock Screen) Stops Playback on iOS 15

### ISSUE THREAD

**Issue by klaaz0r** [DoubleSymmetry/react-native-track-player#1278]
**Describe the bug**
After updating to the latest version I noticed that remote queue/playing doesn't work anymore, the new track get's loaded but pauses straight away

**To Reproduce**
Add tracks to queue and try to play them from background 

**Environment (please complete the following information):**
```
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 47.45 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/opt/node@14/bin/npm
    Watchman: 2021.09.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_302 - /usr/local/opt/openjdk@8/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
version 2.1.0 
Both Simulator and real device

**Comment by klaaz0r** [comment]
I did notice that this only happens in iOS15

**Comment by klaaz0r** [comment]
@dcvz I noticed you updated https://github.com/DoubleSymmetry/SwiftAudioEx to 1.14.1 would upgrading SwiftAudioEx possibly be a fix?

**Comment by dcvz** [comment]
@klaaz0r does this happen for the example app in the repo as well?

**Comment by klaaz0r** [comment]
> @klaaz0r does this happen for the example app in the repo as well?

It's hard to replicate in the simulator it seems to work, in my own code I removed some of the service worker functionality to make sure I am not making any mistakes. What I see happening in the playstate is: 

1. loading
2. paused
3. ready
4. paused < -- and this should be playing of course

**Comment by klaaz0r** [comment]
@dcvz also an important note, when having the app open everything works correct. Going to next tracks etc. not problem. Only if the app is closed and looking at the media controls it pauses straight after being ready

**Comment by MatthiasDh** [comment]
Having this aswell, iOS 15.

**Comment by klaaz0r** [comment]
@dcvz also an interesting finding is that if I hit play and move the app to the background it will not load, once I open the app again it starts playing. It looks like on iOS15 something is wrong with loading audio in the background

**Comment by dcvz** [comment]
Thanks for the details @klaaz0r! I'll try to take a look when I'm at home in a few hours. 

You should be able to run the example app on your device. I'm curious whether the issue appears there.

**Comment by klaaz0r** [comment]
![photo_2021-09-24 18 13 43](https://user-images.githubusercontent.com/9153800/134707529-1f71b989-08ba-4eed-acff-ad68bb5066ae.jpeg)

@dcvz I can confirm that the bug happens in the example

**Comment by dcvz** [comment]
@klaaz0r background playback works for me.. what doesn't work is controlling playback via the control center. Is that the bug you're trying to file? or is music really not playing for you in the background?

**Comment by klaaz0r** [comment]
@dcvz the music plays in background but "starting" the music doesn't work. So going to next track in background mode does not work. In the example if I play the first song and close the app it keeps playing fine, but it will never start the next track

**Comment by dcvz** [comment]
Alright @klaaz0r I checked it out and background playback works fine in iOS 15. However there two bugs in the example project and one bug in the audio library -- this last bug might've been what you meant:

1. The example app wasn't listening to RemoteNext and RemovePrevious events, so the control center's next and previous buttons didn't do anything.
2. The example app had a bug where the first play press wasn't actually playing audio but instead pausing it. 
3. The internal audio library's control center implementation didn't work on iOS 15, causing that when you switched tracks, the notification would disappear and stop playback. 

These issues are fixed and the example works perfectly even on iOS 15. Please take a look and point your own project to the latest dev branch -- if you can confirm the fix, then I'll release a new version tomorrow.

**Comment by goctruyenaudio** [comment]
@klaaz0r @dcvz please confirm once this issue was resolved and branch is merged.
Thank you very much!

**Comment by klaaz0r** [comment]
@dcvz @goctruyenaudio I can confirm that it now works!

**Comment by dcvz** [comment]
Release 2.1.1 has now been released with this fix! Thank you all for your input here :)
Full (small) changelog here: https://github.com/DoubleSymmetry/react-native-track-player/blob/main/CHANGELOG.md

**Comment by dcvz** [comment]
@klaaz0r I will go ahead and close this issue now!
