### ISSUE TITLE
Not getting duration initially in useEffect.

### ISSUE THREAD

**Issue by ViraliVasa** [DoubleSymmetry/react-native-track-player#1280]
I am not getting total duration of url loaded from remote network initially when mounts.After Playing song I am getting total duration.Please help me ...!!!!!!

useEffect(()=>{
const currentDuration = await TrackPlayer.getDuration()
    console.log(`Duration`,  currentDuration)
},[])

**Comment by bradleyflood** [comment]
Thanks @ViraliVasa can you provide a replicable example code/project?

**Comment by fukemy** [comment]
u need to add currentDuration to useEffectDependency

**Comment by fukemy** [comment]
i have same problem too, it's seem getDUration only work after play audio:
```
await TrackPlayer.play()
let initalDuration = await TrackPlayer.getDuration()
console.log('setDuration', initalDuration) -> work
setDuration(initalDuration)
```

not working in useEffect 
```
useEffect(() => {
        const duration = async() => {
            await TrackPlayer.add({
                id: props.currentMessage._id,
                url: props.currentMessage.voice,
                title: props.currentMessage._id,
                artist: props.currentMessage._id
            })
            let initalDuration = await TrackPlayer.getDuration()
            console.log('setDuration', initalDuration)
            setDuration(initalDuration)
        }
        duration()
    }, [])
```

always return 0, can u help?
