### ISSUE TITLE
Phone storage music isnot playing !!!

### ISSUE THREAD

**Issue by joy-mollick** [DoubleSymmetry/react-native-track-player#1282]
I used this package, it is fine for predefined mp3 files from app storage . But It's not working for the phone's storage like I used as ulr from my phone file:///Internal storage/Music/videoplayback_001.mp3 , but it is not playing ,nothing works . Plz anyone help me to work this problem out ??

**Comment by bradleyflood** [comment]
Hi @joy-mollick if you could provide more info or code we might be able to check it out. Thanks :)
