### ISSUE TITLE
Add support for long press to the control center time jump / skip track buttons

### ISSUE THREAD

**Issue by mitchdowney** [DoubleSymmetry/react-native-track-player#1291]
**Is your feature request related to a problem? Please describe.**
Some apps assign two different functions to the control center time jump / skip track buttons. For example, pressing the skip track button could skip the track, but long pressing the skip track button could begin seeking forward in the track.

In our case, we want the time jump buttons to be time jumps on press, but skip track on long press.

**Describe alternatives you've considered**
No alternatives seem to be possible with react-native-track-player currently.

**Additional context**
To test an app that has long press working (on iOS at least, I haven't tested Android), you can try Spotify.

**Comment by bradleyflood** [comment]
Sounds like a great idea @mitchdowney. I've added this to our Github Project backlog. I'll review it again soon and see if we can prioritise it on our list.

Of course, we are always open to PR's if you can help with this.

Cheers
Brad
