### ISSUE TITLE
skipToNext and skipToPrevious does not work on locked screen controls iOS

### ISSUE THREAD

**Issue by Csutkas** [DoubleSymmetry/react-native-track-player#1296]
**_Description:_**
I can not change track from locked screen on real device iOS.
The player works fine when I am on the locked screen with background playing and I can do play, pause, but when I do a **skipToNext()** or **skipToPrevious()** here, it goes to paused state (and I can not start any track any more from locked screen - but if I open the device I see that the track was changed).

**_Reproduce in real iOS device:_**
Configure up the package.
Add some tracks to the queue.
Start to play a track in the app. 
Lock the screen.
Press home button. 
Click to the next or the previous from the control buttons.

**_Environment:_**
react-native info:
System:
    OS: macOS 11.6
    CPU: (8) x64 Apple M1
    Memory: 20.02 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.16.0 - /usr/local/bin/npm
    Watchman: 2021.09.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

What `react-native-track-player: 2.1.1
Tested two real device: iPhone 6s - iOS 15.0, iPhone 6s Plus - iOS 14.1

**_Code:_**
My service.ts file:
```
import TrackPlayer, {Event} from 'react-native-track-player';
import {tracks} from './tracks';

module.exports = async function () {
  TrackPlayer.addEventListener(Event.RemotePlay, () => TrackPlayer.play());

  TrackPlayer.addEventListener(Event.RemotePause, () => TrackPlayer.pause());

  TrackPlayer.addEventListener(Event.RemoteStop, () => TrackPlayer.destroy());

  TrackPlayer.addEventListener(Event.RemotePrevious, async () => {
    const currentTrackIndex = await TrackPlayer.getCurrentTrack();
    if (currentTrackIndex > 0) {
      await TrackPlayer.skipToPrevious();
    }
  });

  TrackPlayer.addEventListener(Event.RemoteNext, async () => {
    const currentTrackIndex = await TrackPlayer.getCurrentTrack();
    if (currentTrackIndex < tracks.length - 1) {
      await TrackPlayer.skipToNext();
    }
  });

  TrackPlayer.addEventListener('remote-seek' as Event, async (position) =>
    TrackPlayer.seekTo(position.position),
  );
```

Log from xCode:
After next clicked on locked screen the last log from xCode:
```
2021-10-06 16:05:28.447615+0200 [54027:3022229] [javascript] 'New event: ', { state: 'paused', type: 'playback-state' }
```

Screenshot from iPhone:
![IMG_0932](https://user-images.githubusercontent.com/47823190/136219909-2321decd-6f50-4ebb-90c0-f96e534772ac.jpg)

*** UPDATE: ***
I have checked on version: 2.0.0 - it works fine.
I have checked on version: 2.0.3 - does not work.

**Comment by dcvz** [comment]
Please move up to the latest 2.x.x version. There was a bug in iOS 15 which we fixed later.

**Comment by bradleyflood** [comment]
Resolved.
