### ISSUE TITLE
npm ERR: Could not resolve dependency

### ISSUE THREAD

**Issue by besh81** [DoubleSymmetry/react-native-track-player#1301]
Hi all,

just started a new react native app (0.66.0) and trying to install track player:

this is the command I used:
`npm install --save react-native-track-player`

this is the error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: rml@1.7.0
npm ERR! Found: react-native@0.66.0
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.66.0" from the root project
npm ERR!   peer react-native@">=0.60.0-rc.2" from react-native-track-player@2.1.1
npm ERR!   node_modules/react-native-track-player
npm ERR!     react-native-track-player@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.65.0" from react-native-windows@0.65.4
npm ERR! node_modules/react-native-windows
npm ERR!   peer react-native-windows@">=0.63.0" from react-native-track-player@2.1.1
npm ERR!   node_modules/react-native-track-player
npm ERR!     react-native-track-player@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I'm not sure but seems that react-native-windows is missing, isn't it?
If so why should I install it even for android app ???

Here react-native info:
```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19043
    CPU: (20) x64 Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz
    Memory: 21.92 GB / 31.84 GB
  Binaries:
    Node: 16.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.24.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 30.0.2, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    Visual Studio: 16.11.31727.386 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_302
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0 => 0.66.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Ciao

**Comment by besh81** [comment]
Tested agian this morning and now it works !!!

**Comment by jspizziri** [comment]
@dcvz this seems to be an issue because of the newly added [`react-native-windows` peer dependency](https://github.com/DoubleSymmetry/react-native-track-player/blame/main/package.json#L65).

This should probably be an optional peer dependency for higher versions of npm. [I created a PR for this change.](https://github.com/DoubleSymmetry/react-native-track-player/pull/1324)

**Comment by jspizziri** [comment]
@Ogala FYI, you can use the `--legacy-peer-deps` flag to get around this if you're using a higher version of npm. 

Ex:

```sh
npm i --legacy-peer-deps react-native-track-player@^2.1.2
```

**Comment by Ogala** [comment]
I will try this and revert.

**Comment by dcvz** [comment]
@jspizziri thanks for the input and the PR, I'll take a look soon!

**Comment by mSaurabh** [comment]
Hi, @dcvz Any update on this? I am still getting this issue when I try to install 
`npm i react-native-track-player                                                                                  1 ✘ 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: takeoff-web@2.3.9
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!   peer react@">=16.8.6" from react-native-track-player@2.1.2
npm ERR!   node_modules/react-native-track-player
npm ERR!     react-native-track-player@"*" from the root project
npm ERR!   1 more (react-native)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native-windows@0.67.5
npm ERR! node_modules/react-native-windows
npm ERR!   peer react-native-windows@">=0.63.0" from react-native-track-player@2.1.2
npm ERR!   node_modules/react-native-track-player
npm ERR!     react-native-track-player@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/sm/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sm/.npm/_logs/2022-03-22T02_25_13_678Z-debug-0.log`

When I use the --legacy-peer-deps now I am getting this error 

`/node_modules/react-native/Libraries/Image/AssetSourceResolver.js
Module not found: Can't resolve '../Utilities/Platform' in`

Not sure if anyone else has this issue.
