### ISSUE TITLE
Sending cookies on Android [Question]

### ISSUE THREAD

**Issue by sadikyalcin** [DoubleSymmetry/react-native-track-player#1302]
I'm getting a 403 on my remote tracks as no cookies are being sent on Android. On iOS this seems to be the default behaviour on the OS level (I think). I don't really want to make my files public on the server so is there a way of sending / assigning cookies? I couldn't find anything on the docs regarding this.

**Comment by bradleyflood** [comment]
Thanks @sadikyalcin. Can this issue now be closed?

**Comment by SimonChaumet** [comment]
Http only secure cookies are not sent, is there a way to do it with only headers ?

**Comment by bradleyflood** [comment]
@SimonChaumet not that I'm aware of. Thanks
