### ISSUE TITLE
Unable to read the license file `LICENSE` for the spec `SwiftAudioEx (0.13.2)-IOS

### ISSUE THREAD

**Issue by nguyenductoan1995** [DoubleSymmetry/react-native-track-player#1303]
**Describe the bug**
I encountered the above problem when pod install

"react-native": "0.64.1"
"react-native-track-player": "^2.0.3"
<img width="1101" alt="Screen Shot 2021-10-11 at 11 54 24" src="https://user-images.githubusercontent.com/24264218/136735271-3cceb16b-bc46-462d-b8de-9deadfe4bd8f.png">

**Comment by bralandealmeida** [comment]
same here

**Comment by shawnFallon** [comment]
Did anyone come up with a solution for this yet?

**Comment by jr00n** [comment]
Same here

**Comment by thebuddha** [comment]
same here

**Comment by bradleyflood** [comment]
Thanks all. This should be resolved via https://github.com/DoubleSymmetry/react-native-track-player/issues/1248#issuecomment-942025812

Can you test and confirm? @jr00n @thebuddha @shawnFallon @IacoCesar @bralandealmeida
