### ISSUE TITLE
the sound does not stop when opening an sound on another application -» Android only

### ISSUE THREAD

**Issue by RMabroukS** [DoubleSymmetry/react-native-track-player#1304]
the sound does not stop when opening an sound on another application -» Android only

react native version    >>>   "react-native": "0.63.4",
eact-native-track-playe version >>    "react-native-track-player": "^2.1.1",

**Comment by neoassyrian** [comment]
This is also not working for me. I'm listening to the remote-duck event in the service file and handling it according to the documentation, but it is still playing sound when other apps are playing music (eg Spotify, YouTube, etc...)
It used to stop in earlier version 1x

**Comment by dcvz** [comment]
@neoassyrian are you able to tweak the example or give an example project where I can see this happening and can debug?

**Comment by bradleyflood** [comment]
Thanks @RMabroukS if this is still an issue please create another Issue here in Github and fill out the Bug Report template.

Also see #1371 

Cheers :)
