### ISSUE TITLE
playbackState is loading in IOS and 0 or 8 in Android

### ISSUE THREAD

**Issue by edersonfaccin** [doublesymmetry/react-native-track-player#1310]
Hi everyone, i was trying this package in react native application, but after i loaded the list musics, in IOS my playbackState returns loading, and Android return some times 0 and other times 8

Both test made in simulators and only mp3 musics

Is there solution for this issue?

Thanks so much

**Comment by nlabofa** [comment]
i'm Experiencing this @edersonfaccin . Solution ?
