### ISSUE TITLE
[iOS] PlaybackQueueEnded triggers twice on the last track

### ISSUE THREAD

**Issue by rborn** [doublesymmetry/react-native-track-player#1311]
**Describe the bug**

On iOS (at least) PlaybackQueueEnded triggers twice in the last track, once at the start of the track and second at the end of the last track

**To Reproduce**

Using the last commit https://github.com/DoubleSymmetry/react-native-track-player/commit/6aa76e0ee006eb524f3c667fff200a73b5e83b03 make a 3 items playlists and play it. 

At the 3rd track, right after it starts PlaybackQueueEnded will trigger **BUT with the last position from the previous track** then at the end will trigger correctly.

**Environment (please complete the following information):**

- react-native: 0.66.0
- react-native-track-player:  https://github.com/DoubleSymmetry/react-native-track-player/commit/6aa76e0ee006eb524f3c667fff200a73b5e83b03
- testing on device, iOS 15.0.2

**Code**

Somewhere in the app 
```
 await TrackPlayer.add([
                    {
                        id: 'trackId1',
                        url: this.audio,
                        title: '1',
                        artist: 'Emjoy 1',
                        artwork
                    },
                    {
                        id: 'trackId2',
                        url: this.audio,
                        title: '2',
                        artist: 'Emjoy 2',
                        artwork
                    },
                    {
                        id: 'trackId3',
                        url: this.audio,
                        title: '3',
                        artist: 'Emjoy 3',
                        artwork
                    }
                ]);
```

in the service.js file
```
    TrackPlayer.addEventListener(Event.PlaybackQueueEnded, e => {
        console.log({ PlaybackQueueEnded: e });
    });
```

Thank you ❤️

**Comment by skruegs** [comment]
Same issue here

**Comment by ramisalem** [comment]
Hi Any update on this, Thanks very much for such an awesome package

**Comment by bradleyflood** [comment]
Thanks for reporting this.

Any change you could investigate or provide a fix PR?

@rborn @skruegs @ramisalem @VovkViktor

**Comment by drhootch** [comment]
I had the same issue with iOS, managed a workaround for anyone interested : 
1. In _PlaybackQueueEnded_ event listener : if (this.lastIsReady === false) then ignore by early return for example
2. When _PlaybackTrackChanged_ event is fired : In case of ios and the next track is last track in the queue then set _lastIsReady_ flag to false
3. Set _lastIsReady_ flag to true when State.Ready event is fired

the code sample :

```
// PlaybackQueueEnded event listener
TrackPlayer.addEventListener(Event.PlaybackQueueEnded, event => {
    // If lastIsReady === false then the queue didn't end : call for an early return
    if (this.lastIsReady === false) {
        return;
    }
    // Else then it is a legit PlaybackQueueEnded callback
})

// PlaybackTrackChanged event listener
TrackPlayer.addEventListener(Event.PlaybackTrackChanged, event => {
    TrackPlayer.getQueue().then(queue => {
        // In case of ios and the next track is last track in the queue : set lastIsReady to false
        if (Platform.OS === 'ios' && event.nextTrack === queue.length - 1) {
            this.lastIsReady = false;
        }
   })
})

// PlaybackState event listener
TrackPlayer.addEventListener(Event.PlaybackState, event => {
    // Whenever the state is ready : set lastIsReady to true
    if (event.state === State.Ready) {
          this.lastIsReady = true;
    }
})
```

**Comment by jspizziri** [comment]
There has been extensive work done on bot the `PlaybackTrackChanged` & `PlaybackQueueEnded` events [in this PR](https://github.com/doublesymmetry/react-native-track-player/pull/1501)

iOS appears to behaving correctly for both events and there are some small bugs currently in progress for Android.
