### ISSUE TITLE
Set Pitch Algorithm on iOS

### ISSUE THREAD

**Issue by elcitrovmtgrande** [doublesymmetry/react-native-track-player#1315]
Hi there,

Thank you for this amazing work though. Nonetheless, I've got a question. Is it possible to set the Pitch Algorithm on iOS ? I saw constants available. But I do not succeed to use the AVAudioTimePitchAlgorithm spectral so when I start playing around with the rate, pitch correction is encountering latencies and sound issues.

Am I missing something ? Am I doing something wrong ? Or is the feature not available yet ?

Thank you :)

**Comment by jspizziri** [comment]
These are [the algorithms available](https://react-native-track-player.js.org/docs/next/api/constants/pitch-algorithm) and according to the docs you set them via [the `pitchAlgorithm` property on the `Track` object](https://react-native-track-player.js.org/docs/next/api/objects/track).

That is all that's available currently, but if those are not working please submit a reproducible example and we'll investigate it as a bug.
