### ISSUE TITLE
Android 12 crash latest track player version

### ISSUE THREAD

**Issue by KPUbhada** [DoubleSymmetry/react-native-track-player#1318]
After updating app in android 12 and try to run app in android 12 device and simulator facing issue for crashing.

**Here is issue.**
androidx.media.session.MediaButtonReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present'

**Resolve**
With use of **android:exported="true"** fixed issue for run app but service not start once player on in app. so again crash app.

Thanks
ketan

**Comment by nateshmbhat** [comment]
Facing same issue :(

**Comment by JulesPatry** [comment]
Facing same issue as well

**Comment by saka-8** [comment]
facing the same issue, all suggestions are 
welcome here!

**Comment by bradleyflood** [comment]
Hi and thank you. This will be fixed in upcoming Android rewrite - see #1371 

Cheers :)
