### ISSUE TITLE
React/RCTBridgeModule.h file not found

### ISSUE THREAD

**Issue by whobutsb** [DoubleSymmetry/react-native-track-player#132]
So I ran `npm install --save react-native-track-player` then ran `react-native link`.  

When I tried to build the project in XCode I received the error: 
```/Users/whobutsb/Sites/cc-mobile/node_modules/react-native-track-player/ios/RNTrackPlayer/Support/RNTrackPlayer-Bridging-Header.h:5:9: 'React/RCTBridgeModule.h' file not found```

I'am running: 
- react-native: 0.50.3
- react-native-track-player: ^0.2.2

**Comment by peterlazar1993** [comment]
You should be able to get it working by following this comment https://github.com/react-native-kit/react-native-track-player/issues/74#issue-272454799

**Comment by silkyland** [comment]
How you resolved this issue?

**Comment by dcvz** [comment]
Should be resolved as part of v1.0.0

**Comment by rkotcherr** [comment]
I'm still getting this error with 1.2.2

**Comment by neoassyrian** [comment]
I'm getting this issue with 1.2.2

**Comment by davidcort** [comment]
I'm getting this issue with 1.2.3

**Comment by curiousdustin** [comment]
@davidcort what react native version? Are you setting up a new project or upgrading?

**Comment by kaustubh57** [comment]
@davidcort try to unlink "react-native-track-player" and other linked modules if any. There might be some errors to unlink your modules when you start the server.
`
react-native unlink react-native-track-player
`
Run `cd ios && pod update`
