### ISSUE TITLE
Android 12 RuntimeException: Unable to start service com.guichaguri.trackplayer.service.MusicService with Intent

### ISSUE THREAD

**Issue by klokie** [DoubleSymmetry/react-native-track-player#1322]
**Describe the bug**
We've just started seeing crashes reported by Pixel users running the latest Android 12.

**To Reproduce**
1. built react native using Bitrise as I don't have a working Android development environment
2. run app using simulator (browserstack.com)
3. App crashes as soon as soon as library is initialised

(runs without error on iOS)

**Environment (please complete the following information):**
```
$ react-native info
info Fetching system and libraries information...
(node:9921) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 123.13 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.18.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2021.09.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7322048
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/local/opt/openjdk/bin/javac
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: ^5.0.1 => 4.13.0 
    react: 17.0.1 => 16.13.1 
    react-native: 0.64.0 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

using `react-native-track-player` version 2.1.2

testing on a simulator on browserstack.com running Android 12 beta

**Code**
```
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4661)
at android.app.ActivityThread.access$2000(ActivityThread.java:247)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2095)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7842)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by likeaj6** [comment]
Have this issue as well. Have you found a fix?

**Comment by Vashiru** [comment]
@likeaj6 I've just committed a fix for this issue. If you need this fix yourself, but can't wait for upstream to have it pushed, check out the comment on: https://github.com/DoubleSymmetry/react-native-track-player/pull/1269#issuecomment-965085338

(You might also want to check out that pull request in it's entirety for Android 12 compatibility).

**Comment by Vashiru** [comment]
Update (also posted on the PR): The fix causes a crash on Android 12. Currently don't have a solution for that.

**Comment by mayhizi** [comment]
having the same error 😢

**Comment by bradleyflood** [comment]
Thanks everyone. I'll try and get this PR merged. I'm closing this Issue as it is tracked elsewhere too.
https://github.com/DoubleSymmetry/react-native-track-player/pull/1269#pullrequestreview-852478546

**Comment by bradleyflood** [comment]
Also note that we are doing a major rewrite of the Android stuff - see #1371

**Comment by Vashiru** [comment]
> Update (also posted on the PR): The fix causes a crash on Android 5. Currently don't have a solution for that.

I've updated this comment, I meant to say it causes a crash on Android 5, not Android 12. So before it's merged into main / released, somebody might want to have a look at that.
