### ISSUE TITLE
[plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x6000020c18e0> F8BB1C28-BAE8-11D6-9C31-00039315CD46

### ISSUE THREAD

**Issue by srahul9134** [DoubleSymmetry/react-native-track-player#1323]
**Describe the bug**
I am getting log  [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x6000020c18e0> F8BB1C28-BAE8-11D6-9C31-00039315CD46     for iOS 

For android its working fine but on iOS i am getting above log in staging and release build .
on iOS development build is working fine.

**Comment by surhidamatya** [comment]
I was facing the same issue. And the issue was of adding the detail rather than library. After the artist was added to the track the audio started playing and the issue disappered:
```
 if (urlRef) {
      await TrackPlayer.add({
        id: 1,
        title: `${songTitle}`,
        artist: `${songArtist}`,
        artwork: `${songCover}`,
        url: urlRef,
      });
```

**Comment by bradleyflood** [comment]
@surhidamatya Is this an issue with the documentation then?

Could you create a pull request to fix the docs? Or the logic/code?

Please and Thank you :)

CC: @srahul9134
