### ISSUE TITLE
Background mode not working 2.1.2

### ISSUE THREAD

**Issue by nabilhayek** [DoubleSymmetry/react-native-track-player#1325]
**Describe the bug**
Background mode doesn't work when closing the app on iOS. On a real device, the audio fades to 0 when closing, and in the simulator, the sound is jittering/noisy when played in the background. When rolling back to version 2.0.3 everything works fine as it should.

**To Reproduce**
Install react-native-track-player@2.1.2
Play a track with HLS protocol
Close the app

**Environment (please complete the following information):**
```
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 514.71 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7621141
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

What `react-native-track-player` version are you using?
2.1.2
Are you testing on a real device or in the simulator? Which OS version are you running?
Both, iPhone 12 iOS 14.5 on simulator and iPhone 12 Pro iOS 14.4.1 on real device

**Comment by Uriopass** [comment]
I reproduce with ios 15, but it doesn't work on 2.0.3 either :thinking:

**Comment by foush** [comment]
Any update on this? I'm experiencing the same issue on physical iOS devices

**Comment by bradleyflood** [comment]
Hi @foush no update yet - is this something you can help us out with? Investigate and/or create a PR?
Cheers

**Comment by Arnoldnuo** [comment]
It works ok on Android, but on iOS 15, when go to background, `paused` event accepted, and the sound stopped, when reopen iOS app, the sound continued.
I have rewrite my sound-util.ts by `react-native-sound` on iOS, waiting for solution for this bug, so I can reuse react-native-tracker-player on iOS

**Comment by foush** [comment]
I found my issue was a case of the `TrackPlayer.setupPlayer` not always being invoked. After fixing this bug on my end the background player now works using 2.1.2

I'd suggest others encountering an issue with background play ensure they have [completed the steps for background mode](http://react-native-track-player.js.org/background/#ios) and confirm the player is being setup properly

**Comment by garrett-gottlieb** [comment]
I'm having the same issue on my iPhone XS iOS 15. `TrackPlayer.setupPlayer` is being invoked.

**Comment by bradleyflood** [comment]
Thanks @garrett-gottlieb Are you able to replicate this on the example project? If so could you create a new Bug Issue in this repo? Thanks :)

**Comment by garrett-gottlieb** [comment]
@bradleyflood I can, and after some tinkering, it appears to be because of these settings. It's very possible that I was setting this up wrong. After switching to using a blank `{}` for `setupPlayer`, background mode is working! Here is what I was using (commented out to ensure nobody falls down the same rabbit hole):
```ts
      // iosCategory: IOSCategory.Ambient,
      // iosCategoryMode: IOSCategoryMode.SpokenAudio,
      // iosCategoryOptions: [
      //   IOSCategoryOptions.AllowAirPlay,
      //   IOSCategoryOptions.AllowBluetooth,
      //   IOSCategoryOptions.AllowBluetoothA2DP,
      //   IOSCategoryOptions.InterruptSpokenAudioAndMixWithOthers,
      // ],
