### ISSUE TITLE
Audio speed control

### ISSUE THREAD

**Issue by SintoAntony** [DoubleSymmetry/react-native-track-player#1328]
Hi 

Thank you team  for this awesome library

Do you have any plan for adding new feature of audio speed control in this library. 

Could you please update regarding this soon?

**Comment by calebomusic** [comment]
http://react-native-track-player.js.org/documentation/#setraterate

**Comment by SintoAntony** [comment]
Got it thanks
Thanks and Regards,
Sinto Antony
Mob: (+91) 9961669543
