### ISSUE TITLE
Ability load a track at a specified seek position

### ISSUE THREAD

**Issue by doughsay** [DoubleSymmetry/react-native-track-player#1330]
**Is your feature request related to a problem? Please describe.**
When loading a track into the track-player, it always starts at position 0. In my case, this is a streaming track (dash/hls). But I then immediately seek to a position farther into the track.  The problem is: TrackPlayer first starts buffering from 0 and then shortly after starts buffering from the seeked position.  This causes unnecessary bandwidth usage (the buffer from 0 is immediately discarded), and also causes thrashing when using `useProgress` (the position is initially zero and then immediately jumps).

**Describe the solution you'd like**
I'd like a way to specify the initial seek position when loading a track.

**Describe alternatives you've considered**
There is no alternative, the only thing I can do is seek immediately after loading the track.

**Comment by praisedavid787** [comment]
Having same need here please. In dire need of it.

**Comment by DanielGBullido** [comment]
I solved using:

----- PlayerScreen

  const playBackState = usePlaybackState();

  useEffect(() => {
    if (audioPlayerStore.isReadyToPlay(playBackState)) {
      audioPlayerStore.play(elapsedTime); (Call to store and store call to AudioService)
    }
  }, [playBackState]);

----- Store

    isReadyToPlay(playBackState: number | string) {
      return (
        playBackState === State.Ready &&
        self.settings?.episode.id !== '' &&
        self.settings?.playerStatus === false (only set a true after when use .add)
      );
    },

---- AudioService

  play: async (newPositionInSeconds: number) => {
    TrackPlayer.play();
    if (newPositionInSeconds > 0) {
      TrackPlayer.seekTo(Math.floor(newPositionInSeconds));
    }
  },

i hope help you

**Comment by doughsay** [comment]
@DanielGBullido this doesn't solve the stated problem. I know you can immediately seek after the track loads, but track player still causes network requests to fetch portions of the media file starting from the beginning, and still initially reports the position as 0 when using `useProgress`.

**Comment by doughsay** [comment]
> @doughsay I believe this is the same issue as https://github.com/DoubleSymmetry/react-native-track-player/pull/713
> 
> Correct?

It is indeed, thanks! I'll close this and watch the PR.
