### ISSUE TITLE
Background Player not working for iOS or android

### ISSUE THREAD

**Issue by Jaskur117** [DoubleSymmetry/react-native-track-player#1331]
Hello,

I'm having issues getting functionality out of the background player for both iOS and android.  On iOS once the app enters the background the audio stutters quite a bit and I can't find any controls for it despite having followed the setup instructions.  On android I can see the player on the lock screen or in the pull down, but none of the actions (play/pause, seek, stop) seem to work.

I had the same experience with your example app as I had with trying my own implementation.

**Comment by killerham** [comment]
I'm seeing this as well

**Comment by justinlaos** [comment]
I am also seeing this. tried a lot of different things but background playing and remote controls are not working

**Comment by justinlaos** [comment]
I was having similar issues but found on my App.tsx when setting up the playing in a useEffect I had a async function which was causing it not to set up properly. removing that and allowing how they set it up on the example app worked for me. hope that helps

**Comment by charneykaye** [comment]
Experiencing this issue as well, however I suspect (based on @justinlaos comment) I may have had too much fun with async functions. Investigating...

**Comment by Hannes-Endare** [comment]
I set it up just like the example app. But whenever my app goes into the background, the audio begins to stutter. The stuttering ends when I bring the app back to the foreground. Any ideas?

**Comment by justinlaos** [comment]
@Hannes-Endare the stuttering sound more like an environment issue. Possibly change how you are testing your app. Or maybe your computer might be having trouble running the simulator along with other software

**Comment by bradleyflood** [comment]
Thanks all. If this is still an issue could someone raise a new Bug Report (on the new Issue template?).

Thanks everyone :)

**Comment by ducpt2** [comment]
This issue still appear, i try 2.1.2 and 2.2.0-beta13 version of this lib but it is still exist. My ios version is 15.2. Thanks
