### ISSUE TITLE
Pitch shift control

### ISSUE THREAD

**Issue by xbaldiq** [DoubleSymmetry/react-native-track-player#1333]
Hi is there any plan to add pitch shift control? I read the older discussion and I wonder is there any plan to bring it back, because right now I cannot find any package that supports this feature in react-native iOS, thank you!

**Comment by bradleyflood** [comment]
@dcvz How are we handling feature-requests like this? Can we just add it to a backlog/feature-request list somewhere and then close this issue?

Are you using Trello or Github Projects? 

I'm looking to help in any way I can. Cheers.

**Comment by dcvz** [comment]
@bradleyflood @xbaldiq on iOS the Track object supports ‘ pitchAlgorithm’ is that what you’re looking for?

**Comment by xbaldiq** [comment]
@dcvz I was looking for something like this: https://developer.apple.com/documentation/avfaudio/avaudiounittimepitch/1387188-pitch. I'm not sure existing pitchAlgorithm can cover that.

**Comment by bradleyflood** [comment]
Thanks @xbaldiq 

I've added this to our backlog for review.

Perhaps related to this open feature request too. https://github.com/DoubleSymmetry/react-native-track-player/issues/1315

Cheers
