### ISSUE TITLE
Event "remote-duck" not trigger without adding songs to playback queue. How can i do that?

### ISSUE THREAD

**Issue by tackanoway35** [DoubleSymmetry/react-native-track-player#1338]
**Describe the bug**
I set up player / update options and add "remote-duck" event listener
But "remote-duck" event is not trigger when i playing other music app
**Note: I haven't added any songs to the playback queue yet. How can i use "remote-duck" event listener without adding song to playback queue?**
Thanks for watching!
**Environment (please complete the following information):**
react-native: 0.63.2
react-native-track-player: 1.2.5
OS: Android
**Code**
export const setupTrackPlayer = async () => {
  await TrackPlayer.setupPlayer({})
  await TrackPlayer.updateOptions({
    stopWithApp: false,
    // Media controls capabilities
    compactCapabilities: [
      TrackPlayer.CAPABILITY_PLAY,
      TrackPlayer.CAPABILITY_PAUSE,
      TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
      TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
      TrackPlayer.CAPABILITY_SEEK_TO,
      TrackPlayer.CAPABILITY_STOP
    ]
  })
  TrackPlayer.addEventListener(TrackPlayerEvents.REMOTE_DUCK, (event) => {
    console.info("REMOTE DUCK EVENT", event)
  })
}

**Comment by tackanoway35** [comment]
I see "remote-duck" event is only triggered when any song is playing.
How can i know other music app is playing?
Thanks for watching

**Comment by bradleyflood** [comment]
Hi @tackanoway35 this isn't how remote-duck works - it's only for notification sounds and such during the time you are playing. You can't tell what other apps are doing.

Thanks :)
