### ISSUE TITLE
Share cookies with javascript

### ISSUE THREAD

**Issue by SimonChaumet** [DoubleSymmetry/react-native-track-player#1339]
**Describe the bug**
Cookies are not shared between javascript and RNTP so we cannot use cookie based auth.

**To Reproduce**
- auth with OkHttp (like axios) with a backend that uses cookie based authentication (like JWT)
- try to load audio which requires authentication

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 410.58 MB / 11.58 GB
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 14.17.2 - /usr/local/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 3.9.7 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
  npmGlobalPackages:
    *react-native*: Not Found
What `react-native-track-player` version are you using? 1.2.3
Are you testing on a real device or in the simulator? Which OS version are you running? Samsung galaxy S20, android 11

**Comment by bradleyflood** [comment]
Hi and thanks.

Correct, cookies are not shared because the audio file is requested natively. You could try the `headers` option.

Good luck!

Brad

**Comment by SimonChaumet** [comment]
@bradleyflood Could it be possible to use OkHttp to request the file ? If we use an api which you cannot modify you need to create a proxy only to send cookies correctly

**Comment by bradleyflood** [comment]
@SimonChaumet I'm not sure sorry - worth investigating. Anyone else know?
