### ISSUE TITLE
not play with local file.version 2.1.2

### ISSUE THREAD

**Issue by zcsEason** [DoubleSymmetry/react-native-track-player#1341]
I am trying to  play audio while component showing.**It not work with local file url** such as:private/var/mobile/Containers/Data/Application/561D9F2E-6920-4E7D-9593-B1E6B135AC0E/tmp/Audios/4C3D00F6-0F57-4550-832F-291A4CC51250.mp3, **but it works use require** (require('~/assets/1.mp3')).
The component code:
import * as React from 'react';
import { useState, useRef, useEffect } from 'react'
import { observer } from 'mobx-react-lite'
import { Image, Pressable, StyleSheet, Text, Button, View } from 'react-native'
import TrackPlayer from 'react-native-track-player'
import { useStores } from '../../models'
import { useProgress, useTrackPlayerEvents, Event, State } from 'react-native-track-player';
import {useNavigation,NavigationContainer} from '@react-navigation/native'
import { createStackNavigator } from '@react-navigation/stack';
import { Slider } from '@miblanchard/react-native-slider'
import { getTimeStr } from '../../utils/ui-utils'
import { values } from 'mobx';
import { event } from 'react-native-reanimated';

export const PreviewAudioScreen = observer(function EditVideoScreen() {

  const [currentTime, setCurrentTime] = useState(0)
  const [isSliding, setIsSliding] = useState(false)
  const sliderRef = useRef<Slider>(null)
  const { position, buffered, duration } = useProgress(100)
  const { mediaStore } = useStores()
  const [sound, setSound] = React.useState()
  const url = mediaStore.audioPath;
  const [playerState, setPlayerState] = useState(null)
  const events = [Event.PlaybackError, Event.PlaybackState]
  useTrackPlayerEvents(events, (e) => {
    if (e.type == Event.PlaybackError) {

    }
    else if (e.type == Event.PlaybackState) {
      setPlayerState(e.state);
    }
  })

  const start = async () => {
    // Set up the player
    await TrackPlayer.setupPlayer();

    // Add a track to the queue
    await TrackPlayer.add({
      id: 'trackId',

      //url: require('~/assets/1.mp3'),
       url:url,
      title: 'Track Title',
      artist: 'Track Artist',
      artwork: require('~/assets/play.png')
    });
    // Start playing it
    await TrackPlayer.play();
  };
  start();

  const playOrPause = () => {
    console.log('1 to start playerState=' + playerState)
    if (playerState != State.Playing) {
      start()
      return;
    }
    if (playerState == State.Playing) {
      console.log('to pause')
      TrackPlayer.pause()
    }
    else {
      console.log('to play')
      TrackPlayer.play()
    }

  }

  const CustomThumb = () => (
    <View
      style={{
        alignItems: 'center',
        backgroundColor: 'red',
        height: 50,
        justifyContent: 'center',
        width: 11,
      }}
    />
  )
  const sliderChanging = (value: any) => {
    setCurrentTime(Math.round(value))
    setIsSliding(true)
  }
  const sliderChanged = (value: any) => {
    setIsSliding(false)
    TrackPlayer.seekTo(Math.round(value))
  }
  const thumbnailWidth = 84
  const renderAboveThumbComponent = (index: number) => {
    return (
      <View
        // eslint-disable-next-line react-native/no-inline-styles
        style={{
          alignItems: 'center',
          borderWidth: 0,
          height: 50,
          justifyContent: 'center',
          left: -thumbnailWidth / 2,
          width: thumbnailWidth,
        }}>

        <Text>{isSliding ? getTimeStr(currentTime) : getTimeStr(position)}</Text>
      </View>
    )
  }
  return (
    <View>
      <Button title={playerState == State.Playing ? 'Pause' : 'Play'} onPress={playOrPause} />
      <View style={{ height: 30, backgroundColor: 'red' }}>
        <Slider
          ref={sliderRef}
          maximumValue={duration}
          renderThumbComponent={CustomThumb}
          trackStyle={{ borderRadius: 2, height: 40 }}
          onValueChange={sliderChanging}
          value={position}
          onSlidingComplete={sliderChanged}
          renderAboveThumbComponent={renderAboveThumbComponent}
          maximumTrackTintColor="#d3d3d3"
          minimumTrackTintColor="#1fb28a"
          thumbTintColor="#1a9274"
        />
      </View>

    </View>
  )
})

**Comment by bradleyflood** [comment]
Thanks @zcsEason but you'll need to recreate an Issue using the updated Bug Report template. Thanks
