### ISSUE TITLE
No task registered for key TrackPlayer

### ISSUE THREAD

**Issue by liviavinci** [DoubleSymmetry/react-native-track-player#1343]
My current code is:

```
// setup player
TrackPlayer.setupPlayer({
  backBuffer: 60,
  waitForBuffer: true,
}).then(() => {
  // remote controls capabilities
  TrackPlayer.updateOptions({
    capabilities: [
      Capability.Play,
      Capability.Pause,
      Capability.JumpForward,
      Capability.JumpBackward,
      Capability.SeekTo,
    ],
    // Capabilities that will show up when the notification is in the compact form on Android
    compactCapabilities: [Capability.Play, Capability.Pause],
  }).then(() => {
    // register remove listener
    /*TrackPlayer.registerPlaybackService(() =>
      require('./src/utils/servicePlayer.js'),
    );*/
    AppRegistry.registerHeadlessTask('TrackPlayer', () => {
      TrackPlayer.registerPlaybackService(() =>
        require('./src/utils/servicePlayer.js'),
      );
    });
  });
});
```

But it's showing error "No task registered for key TrackPlayer" for Android.

I noticed that in the troubleshooting https://react-native-track-player.js.org/install/#android-comfacebookreactcommonjavascriptexception-no-task-registered-for-key-trackplayer it says The playback service requires a headless task to be registered. You have to register it with registerPlaybackService.

But I don't quite understand what this means. Is there any chance anyone can provide me with some sample code for android setup?

**Comment by bradleyflood** [comment]
Hi @liviavinci - have you tried the Example app?

https://github.com/DoubleSymmetry/react-native-track-player/tree/main/example

If you do find a bug though please open a new issue and fill out the template. Thank you :)

**Comment by George3d6** [comment]
This issue seems to arrise when using the `SetupService` verbatim from the example app.

Unsure if the warning is anything to worry about or just a nuisance that can be ignored but it is rather confusing.
