### ISSUE TITLE
Closing/Killing the app not closing the player from the notification in android. It causing many issues.

### ISSUE THREAD

**Issue by rajivtiwary-cm** [DoubleSymmetry/react-native-track-player#1345]
**Describe the bug**
Closing/Killing the app not closing the player from the notification in android. It causes many issues.

**Environment (please complete the following information):**
    "react-native-track-player": "^2.1.2",
    "react-native": "0.64.2",

**Code**

const playBuffer = 0.5;

const TRACK_PLAYER_CONTROLS_OPTS = {
  playBuffer,
  minBuffer: playBuffer * 2,
  maxBuffer: playBuffer * 2,
  // waitforBuffer: true,
  // maxCacheSize: 100000000, // In kilobytes
  stopWithApp: true,
  alwaysPauseOnInterruption: true,
  forwardJumpInterval: 15,
  backwardJumpInterval: 15,
  capabilities: [
    Capability.Play,
    Capability.Pause,
    Capability.Stop,
    Capability.SeekTo,
    Capability.Skip,
    Capability.SkipToNext,
    Capability.SkipToPrevious,
    Capability.JumpForward,
    Capability.JumpBackward,
  ],
  compactCapabilities: [
    Capability.Play,
    Capability.Pause,
    Capability.Stop,
    Capability.SeekTo,
    // Capability.Skip,
    Capability.SkipToNext,
    Capability.SkipToPrevious,
    Capability.JumpForward,
    Capability.JumpBackward,
  ],
  notificationCapabilities: [
    Capability.Play,
    Capability.Pause,
    Capability.Stop,
    Capability.SeekTo,
    // Capability.Skip,
    Capability.SkipToNext,
    Capability.SkipToPrevious,
    Capability.JumpForward,
    Capability.JumpBackward,
  ],
};

**Comment by bradleyflood** [comment]
Thanks. This should be resolved in upcoming #1371 

If you could help us test this that would be awesome! Please and thank you :)
