### ISSUE TITLE
TrackPlayerEvents are inconsistent between iOS and Android for the final track

### ISSUE THREAD

**Issue by curthipster** [doublesymmetry/react-native-track-player#1349]
**Describe the bug**
TrackPlayerEvents are inconsistent between iOS and Android for the final track. Android appears to be correct, and iOS has two issues:
* The `playback-queue-ended` event is fired twice, once at the beginning of the last track and again at the end (related to or the same as #1243)
* The `playback-track-changed` event does not fire at the end of the last track

**To Reproduce**
Create a TrackPlayer, add an array of Tracks, and call `play()`. Add a simple hook to log the events, e.g., 
```javascript
useTrackPlayerEvents([Event.PlaybackTrackChanged, Event.PlaybackQueueEnded], async (event) => {
  console.log(`TrackPlayerEvent = ${JSON.stringify(event)}}`);
});
```

Run the app and observe the logs. For example, here are the logs for the exact same playlist on Android and iOS.

*Android Logs*
✅  The final track has a `playback-track-changed` event and a `playback-queue-ended` event with matching `position` at the end
```
 TrackPlayerEvent = {"nextTrack":0,"position":-0.001,"type":"playback-track-changed"}}
 TrackPlayerEvent = {"position":4.8,"nextTrack":1,"track":0,"type":"playback-track-changed"}}
 TrackPlayerEvent = {"position":16.088,"nextTrack":2,"track":1,"type":"playback-track-changed"}}
 TrackPlayerEvent = {"position":3.936,"nextTrack":3,"track":2,"type":"playback-track-changed"}}
 TrackPlayerEvent = {"position":135.672,"nextTrack":4,"track":3,"type":"playback-track-changed"}}
 TrackPlayerEvent = {"position":158.51,"track":4,"type":"playback-track-changed"}}
 TrackPlayerEvent = {"position":158.51,"track":4,"type":"playback-queue-ended"}}
```

*iOS Logs*
:bug: The first `playback-queue-ended` event fires at the same time as the `playback-track-changed` event signaling the _start_ of the playback for the final track
:bug: The first `playback-queue-ended` event has a `position` value that matches the track that just finished playing, which is incorrect
✅  The second `playback-queue-ended` event has the correct data
:bug: The final `playback-track-changed` event is missing entirely
```
 TrackPlayerEvent = {"nextTrack":0,"position":0,"type":"playback-track-changed"}}
 TrackPlayerEvent = {"track":0,"nextTrack":1,"position":4.8,"type":"playback-track-changed"}}
 TrackPlayerEvent = {"nextTrack":2,"track":1,"position":15.474894121,"type":"playback-track-changed"}}
 TrackPlayerEvent = {"track":2,"nextTrack":3,"position":3.936,"type":"playback-track-changed"}}
 TrackPlayerEvent = {"position":135.672,"track":4,"type":"playback-queue-ended"}}
 TrackPlayerEvent = {"track":3,"nextTrack":4,"position":135.672,"type":"playback-track-changed"}}
 TrackPlayerEvent = {"position":158.496,"track":4,"type":"playback-queue-ended"}}
```

**Environment (please complete the following information):**
*Run `react-native info` in your project and share the content.*
```
% npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 129.11 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.21.0 - /opt/homebrew/bin/npm
    Watchman: 2021.11.29.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.2, 31.0.0
      System Images: android-29 | Google APIs ARM 64 v8a, android-29 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2/13C90 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.0 => 0.65.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

*What `react-native-track-player` version are you using?*
```
% yarn list --pattern react-native-track-player
yarn list v1.22.10
└─ react-native-track-player@2.1.2
✨  Done in 0.24s.
```

*Are you testing on a real device or in the simulator? Which OS version are you running?*
* iPhone 12 Pro, iOS 15.1.1
* OnePlus 9 Pro 5G, Android 11.2.9.9.LE15AA

**Code**
_See steps to reproduce_

**Comment by bradleyflood** [comment]
Thanks @curthipster Are you able to investigate and/or propose a PR to resolve this? Would love a hand! Thank you

**Comment by mmmoussa** [comment]
The bug described here for `playback-queue-ended` is not fixed by #1300, which closed the linked issue #1243. Tested with v2.2.0-rc2.

**Comment by curthipster** [comment]
> One thing I want to mention is that I cannot reproduce the duplicate playback-queue-ended behavior you're describing. I'm using the example project on v2.2.0-rc3. So perhaps you can submit a repro that demonstrates that particular issue.

@jspizziri I have not tested on v2.2.0-rc3 yet. I'm happy to do that. Are the repro steps like I initially described what you're looking for, or is there something more helpful I can do?

**Comment by jspizziri** [comment]
@curthipster thanks for the response. I looked at the code and it doesn't look like anything relevant for this changed between rc2 and rc3, but testing could be helpful as it could've been fixed by a dependency. If you test it and are still getting the same issue more specific repro steps would be helpful and even better would be a working example (based on the `example` app) that reproduced the issue consistently. Then I could clone it down and fix it there.

Also, if you're interested you can [take a look at this comment](https://github.com/doublesymmetry/react-native-track-player/pull/1482#issuecomment-1104064853) which is attempting to holistically address this issue and another one which is very related. The fix for this will be implemented in that PR.

**Comment by jspizziri** [comment]
@curthipster , one thing that would actually be super helpful is if you could pull down the branch on my PR and run through the documented test scenarios. I believe that the solution I have in place should fix this, but another set of eyes would be helpful.

**Comment by curthipster** [comment]
@jspizziri 👀

**Comment by curthipster** [comment]
@jspizziri I pulled down your PR branch at 4961e12 and can confirm that the `playback-queue-ended` event is only being fired once when the last track completes now. That fixes the first issue here:

> The playback-queue-ended event is fired twice, once at the beginning of the last track and again at the end (related to or the same as https://github.com/doublesymmetry/react-native-track-player/issues/1243)

As you noted in the PR, `playback-track-changed` is not being called at the end. Frankly, I don't know what the *correct* behavior is for this event, but I do think it should be consistent between iOS and Android. You could reasonably infer from the [documentation](https://react-native-track-player.js.org/documentation/#events) that the `playback-track-changed` event should fire at the end, because it says:

> `nextTrack` : The next track index. Might be null

Note the difference at the end of the queue between iOS and Android:

iOS log trace:
```
 LOG  TrackPlayerEvent = {"nextTrack":0,"position":0,"type":"playback-track-changed"}}
 LOG  TrackPlayerEvent = {"track":0,"nextTrack":1,"position":143.42639455782313,"type":"playback-track-changed"}}
 LOG  TrackPlayerEvent = {"nextTrack":2,"track":1,"position":76.76190476190476,"type":"playback-track-changed"}}
 LOG  TrackPlayerEvent = {"position":70.64925170068027,"track":2,"nextTrack":3,"type":"playback-track-changed"}}
 LOG  TrackPlayerEvent = {"track":3,"nextTrack":4,"position":70.58823129251701,"type":"playback-track-changed"}}
 LOG  TrackPlayerEvent = {"position":28.305124716553287,"track":4,"type":"playback-queue-ended"}}
```

Android log trace:
```
 LOG  TrackPlayerEvent = {"nextTrack":0,"position":-0.001,"type":"playback-track-changed"}}
 LOG  TrackPlayerEvent = {"position":143.438,"nextTrack":1,"track":0,"type":"playback-track-changed"}}
 LOG  TrackPlayerEvent = {"position":76.773,"nextTrack":2,"track":1,"type":"playback-track-changed"}}
 LOG  TrackPlayerEvent = {"position":70.661,"nextTrack":3,"track":2,"type":"playback-track-changed"}}
 LOG  TrackPlayerEvent = {"position":105.586,"nextTrack":4,"track":3,"type":"playback-track-changed"}}
 LOG  TrackPlayerEvent = {"position":28.312,"track":4,"type":"playback-track-changed"}}
 LOG  TrackPlayerEvent = {"position":28.312,"track":4,"type":"playback-queue-ended"}}
```

**Comment by curthipster** [comment]
@jspizziri I tested your branch with a focus on multi-track queues and RepeatMode.off. I am seeing two bugs, which I describe in a [Draft PR](https://github.com/5-stones/react-native-track-player/pull/1) I opened on your branch.

Happy to keep chatting on Discord or here if I can be helpful.

**Comment by jspizziri** [comment]
@curthipster thats for taking a look! I'll dig into the other issues tomorrow hopefully.

**Comment by jspizziri** [comment]
@curthipster I've updated my MR to address the issue you reported and a few more. Please take another look.

**Comment by jspizziri** [comment]
fixed via https://github.com/doublesymmetry/react-native-track-player/pull/1501
