### ISSUE TITLE
Build failed on iOS

### ISSUE THREAD

**Issue by algoace123** [doublesymmetry/react-native-track-player#1350]
**Describe the bug**

![Screenshot 2021-12-15 at 4 00 42 PM](https://user-images.githubusercontent.com/94346249/146174863-6ded49ac-6fd9-421b-b8ce-ad3b7795314c.png)

**Environment (please complete the following information):**
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 90.36 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.2 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.18.1 - /opt/homebrew/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

What `react-native-track-player` version are you using?
Testing on physical device, with `react-native-track-player` version: `1.2.7`

**Comment by calvary-tucson** [comment]
Having the same issue.

**Comment by zeejaydev** [comment]
Switch post_install do |installer|
in your pod file 
to this code 
post_install do |installer|
    react_native_post_install(installer)
     # Apple Silicon builds require a library path tweak for Swift library discovery or "symbol not found" for swift things
     installer.aggregate_targets.each do |aggregate_target| 
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)']
        end
      end
      aggregate_target.user_project.save
    end

     # Flipper requires a crude patch to bump up iOS deployment target, or "error: thread-local storage is not supported for the current target"
    # I'm not aware of any other way to fix this one other than bumping iOS deployment target to match react-native (iOS 11 now)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
       end
    end

    # ...but if you bump iOS deployment target, Flipper barfs again "Time.h:52:17: error: typedef redefinition with different types"
    # We need to make one crude patch to RCT-Folly - set `__IPHONE_10_0` to our iOS target + 1
    # https://github.com/facebook/flipper/issues/834 - 84 comments and still going...
    `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_12_0/' #{installer.sandbox.root}/RCT-Folly/folly/portability/Time.h`
  end

then open xcode and click on your project workspace then go to file->Workspace Settings underneth Derived Data there is a path ends with little arrow, click on it then quit xcode "Make sure you quit xcode" then delete DerivedData folder.

then open Xcode (or whatever you are using) delete Pods folder and podfile.lock then in the ios directory 
do run pod deintegrate then pod install then try to build.

if you get error with RCT-folly library click on the library and change the development target to ios 11
then command-k to clean build then build again 
hope that works for you guys

**Comment by bradleyflood** [comment]
Hi @algoace123 and @calvary-tucson  could you please provide an update on this? Is this still an issue for you?

Thank you

**Comment by jspizziri** [comment]
@algoace123 sadly we're not able to provide support for v1 anymore. We encourage you to upgrade to v2 if possible.
