### ISSUE TITLE
Can we use react-native-track-player to perform other background process as well, except for music?

### ISSUE THREAD

**Issue by shivika24** [doublesymmetry/react-native-track-player#1363]
Can we use react-native-track-player to perform other background process as well, except for music?

**Comment by SnifferSixxx** [comment]
Im trying to hit a rest service with fetch after an X amount of seconds of playback in background. For this i use settimeout right after the event PlaybackTrackChanged has been fired. This works fine on iOS but android crashes when the timeout try to execute the call i guess. Also i've lost any trace of logs during the phone (android) is locked, iOS works fine.

**Comment by martinmidtsund** [comment]
@SnifferSixxx You could use the [react-native-background-timer package](https://github.com/ocetnik/react-native-background-timer). It is not well maintained atm, but using regular setTimeout for iOS and BackgroundTimer.setTimeout for Android is working for us via the backgroundservice registered with react-native-track-player.

**Comment by jspizziri** [comment]
This issue is the same as https://github.com/doublesymmetry/react-native-track-player/issues/1414

I'm closing this issue in favor of that one. Please take a look, chime in, and otherwise await the result of that conversation for more updates here!
