### ISSUE TITLE
RCTJSONStringify() encountered the following error: Invalid number value (NaN) in JSON write

### ISSUE THREAD

**Issue by ksielyov** [doublesymmetry/react-native-track-player#1365]
**Describe the bug**
When I call audioRecorderPlayer.startPlayer and audioRecorderPlayer.setVolume it gives error:
RCTJSONStringify() encountered the following error: Invalid number value (NaN) in JSON write

**To Reproduce**
1. Run project
2. `    const currentFile = await audioRecorderPlayer.startPlayer(uri);
    const currentVolume = await audioRecorderPlayer.setVolume(0.5);

    console.log(
      `started file: ${currentFile}; current volume: ${currentVolume}`,
    );`
3. Get "RCTJSONStringify() encountered the following error: Invalid number value (NaN) in JSON write"
4. It gives error only on RN v 0.66.4, and work correctly on 0.63.3

**Environment (please complete the following information):**
Actual on android and ios;

**Code**
`
const play = async () => {
    const currentFile = await audioRecorderPlayer.startPlayer(uri);
    const currentVolume = await audioRecorderPlayer.setVolume(0.5);

    console.log(
      `started file: ${currentFile}; current volume: ${currentVolume}`,
    );

    audioRecorderPlayer.addPlayBackListener((audio) => {
      setCurrentTrack({
        ...currentTrack,
        currentPositionSec: audio.currentPosition,
        currentDurationSec: audio.duration,
        playTime: audioRecorderPlayer.mmssss(Math.floor(audio.currentPosition)),
        paused: false,
        duration: audioRecorderPlayer.mmssss(Math.floor(currentTrack.duration)),
      });

      console.log('position', Math.round(audio.currentPosition));
      console.log('duration', Math.round(duration * 1000));

      setTimeout(() => {
        setCurrentTrack({
          ...currentTrack,
          paused: true,
        });
        audioRecorderPlayer.stopPlayer();
        audioRecorderPlayer.removePlayBackListener();
      }, duration * 1000);
    });
  };
`

**Comment by jspizziri** [comment]
@ksielyov this issue appears to be intended for some other project. I'm closing this, but if I'm crazy please let me know.

**Comment by Faseeh-Abbas-Khan** [comment]
Getting this error for IOS

ExceptionsManager.js:151 RCTJSONStringify() encountered the following error: Invalid number value (NaN) in JSON write
