### ISSUE TITLE
Ambient category not working

### ISSUE THREAD

**Issue by grubicv** [DoubleSymmetry/react-native-track-player#1367]
**Describe the bug**
iOS category .ambient is not working - it's not properly set in the code, code is throwing an exception

**To Reproduce**
Try using .ambient category and it won't be set

**Environment (please complete the following information):**
-

**Code**
-

Fixed in PR:
https://github.com/DoubleSymmetry/react-native-track-player/pull/1366

**Comment by bradleyflood** [comment]
Merged thank you @grubicv
