### ISSUE TITLE
`RemoteDuck` event fires on the interruption, but not when the interruption is over

### ISSUE THREAD

**Issue by dcvz** [DoubleSymmetry/react-native-track-player#1368]
One more thing I found:  The `RemoteDuck` event only fires on the interruption, and not again when the interruption is over. Try these steps in the example app:

1. Start playing
2. Start a 5 second timer
3. Timer goes off and pauses track player (service receives duck event)
4. Stop the timer
5. Service doesn't receive another event, so it can't resume again

_Originally posted by @doughsay in https://github.com/DoubleSymmetry/react-native-track-player/discussions/1264#discussioncomment-1751283_

**Comment by dcvz** [comment]
Additional data:
>It's working for me but only paused is true and it doesn't duck back to continue the stream.
Make sure to put alwaysPauseOnInterruption: true in .updateOptions().

> Also, I'm seeing that if I pause the stream from onDuck event, the position and bufferedPosition are becoming negative, it plays for 10 seconds and stops. After that, hitting play makes it normal.

_Originally posted by @kanzitelli in [#1264 (comment)](https://github.com/DoubleSymmetry/react-native-track-player/discussions/1264#discussioncomment-1810363)_

**Comment by puckey** [comment]
Might this be happening because audio focus is abandoned when you pause the audio after receiving the first event?

In onIsPlayingChanged I see audio focus is abandoned whenever the audio ceases to play.

In the Android guide to managing audio focus, it is not required to release audio focus when the audio has been paused: https://developer.android.com/guide/topics/media-apps/audio-focus#:~:text=Abandoning%20audio%20focus%20is%20not%20required%20if%20the%20user%20pauses%20playback%20but%20may%20resume%20it%20later.

I also just verified that I do receive the follow up event when only muting the audio after receiving the interruption.

**Comment by puckey** [comment]
See https://github.com/DoubleSymmetry/KotlinAudio/pull/12 for an alternative fix by having exoplayer handle audio focus itself. (Potentially allowing us to get rid of the whole REMOTE_DUCK event)

**Comment by dcvz** [comment]
I think you're probably right about the audio focus being at fault here.. I've also thought about automatically handling pausing and resuming (on iOS) for the lib -- but it'd be a breaking change and I've avoided adding breaking changes so far as part of the Android rewrite.

I'm still not sure I want to do this now.. thought I do agree it would make things simpler.

**Comment by puckey** [comment]
Fair enough – perhaps we could reconsider it after the rewrite has been merged in then.

ExoPlayer's AudioFocusManager implementation might be of interest for this issue: https://github.com/google/ExoPlayer/blob/bd54394391b0527893f382c9d641b8a55ffca765/library/core/src/main/java/com/google/android/exoplayer2/AudioFocusManager.java#L184

They only abandon focus if `playbackState == Player.STATE_IDLE`.

**Comment by dcvz** [comment]
Yeah, I'd first try to solve this while keeping the existing functionality.

But I think past the android rewrite release, along with bug fixes we'll work our way up to a 3.0 release.

I think there's a few places that could use some better API's and improvements that would currently require breaking changes. There's also quite a bit of places where the platform's functionality differs a bit.

**Comment by bradleyflood** [comment]
Sounds good. Can we create some additional issues to track these tasks for a v3 release?

**Comment by puckey** [comment]
The following PR should fix this issue: https://github.com/DoubleSymmetry/KotlinAudio/pull/13

**Comment by dcvz** [comment]
Will take a look @puckey ! Thanks :)

**Comment by dcvz** [comment]
The PR was merged in and RNTP updated to use the latest KotlinAudio. Thanks a lot @puckey !

**Comment by bradleyflood** [comment]
Epic work thanks @puckey 

I'll close this for now to help clear the clutter.
