### ISSUE TITLE
App Resumes Playing after App Kill (even with stopWithApp: true)

### ISSUE THREAD

**Issue by bradleyflood** [DoubleSymmetry/react-native-track-player#1370]
Hi,

We have fixed the 3 previous comments we made a mistake on beta version but now in beta 12 cache is released but when we kill the app with a playing song when we restart the app the song start again even with `stopWithApp: true`.

Any advice?

_Originally posted by @malikoum94 in https://github.com/DoubleSymmetry/react-native-track-player/discussions/1264#discussioncomment-1940480_

**Comment by puckey** [comment]
I have tried reproducing this, but things seem to work for me.

@malikoum94 Can you post some example code for us to reproduce the bug? Perhaps using the example app?

**Comment by dcvz** [comment]
@malikoum94 I could also not reproduce this issue. I've tried:
1. setting `stopWithApp: true` in the example app
2. skipping to 3rd track
3. killiing app
4. opening app again

It succesfully starts with the first track again. No issues.

**Comment by bradleyflood** [comment]
@malikoum94 Please see above and let us know if this is still an issue. Cheers.

**Comment by afkcodes** [comment]
I have stopWithApp:true , the player shuts down but the the app instance still lives until i destroy the player @bradleyflood @dcvz

**Comment by bradleyflood** [comment]
@afkcodes as per above we can't seem to replicate this. Can you please post a big report with some simple code that can replicate the issue. Thanks.
