### ISSUE TITLE
Android Rewrite In Progress > Help Us Test!

### ISSUE THREAD

**Issue by bradleyflood** [doublesymmetry/react-native-track-player#1371]
Hi all, thanks for using RNTP!

We are doing a major rewrite of the Android functionality with tonnes of performance and stability improvements. Please join us in testing these out in your app :)

See the discussion on the Android rewrite here https://github.com/DoubleSymmetry/react-native-track-player/discussions/1264

If you run into any issue please raise a Bug Report issue and add the `android-rewite` label.

Thanks!

**Comment by bradleyflood** [comment]
@dcvz Will the Android Rewrite be `v2.1.0` ?

If so I'll create a Milestone for it. Then next we can look at `2.1.x patches`

**Comment by dcvz** [comment]
@bradleyflood android rewrite will be 2.2.0 - we already are past 2.1.0

**Comment by bradleyflood** [comment]
Oh yeah oops my bad 😅

**Comment by bradleyflood** [comment]
beta13 now out - help us test!
https://github.com/DoubleSymmetry/react-native-track-player/discussions/1264#discussioncomment-1974901

**Comment by DennisdeWitNL** [comment]
I already wrote this to David and he confirmed it’s part of a bug, but let’s write it here so the other developers can see it too:

When setting stopWithApp to true, the app crashes when I press the hardware back button on a Samsung smartphone until I am back at the home screen of Android. The player stops and the app crashes. When setting stopWithApp to true, there is no issue. 

It only has this problem on real Android smartphone, not on the Android Studio Emulator.
