### ISSUE TITLE
Drop support for Windows

### ISSUE THREAD

**Issue by bradleyflood** [doublesymmetry/react-native-track-player#1376]
I'd like to propose that we drop support for Windows and focus solely on iOS and Android.

I know this will affect a small percentage of users - but it will allow the project to move faster, be more robust, have less bugs, etc..

Thoughts? @dcvz

**Comment by dcvz** [comment]
Interesting proposal. I think it's a fact that Windows will always lag behind iOS/Android because we don't have the knowledge or setup to develop it effectively.

However, we do have a version (at least right now) that works and is not super far behind the current main. 

I'll give it some more thought over the weekend. But if we drop support I'd still like to have the current or latest working version of Windows available for others.

**Comment by bradleyflood** [comment]
Yeah agreed. Keep Windows for V2 and focus on a V3 next without Windows.

**Comment by jspizziri** [comment]
@dcvz @bradleyflood my vote would be a sort of hybrid approach. We could simply say that Windows is loosely supported by the project and its community. As long as it's stated in the readme I think this is sufficient for users. The code that is there is going to be helpful for folks and hopefully someone who really cares about Windows comes along and pushes it forward periodically.

**Comment by bradleyflood** [comment]
@jspizziri The challenge I see with that keeping Windows even as unsupported is that we will still get Bug Reports and Feature Requests and Pull Requests for Windows, but we are all so time poor so this will just put further burden on an already full team, reducing any availability on the pressing issues. Cutting out Windows will allow us to focus on the important stuff - Android & iOS - without additional distractions.

**Comment by jspizziri** [comment]
@bradleyflood fair points. However, perhaps we could do some things to help manage the load.

Some ideas:

1. Update the issue template to require a strict format (which includes platform)
2. Have a Github action auto label anything that didn't meet the template requirements (and auto close them if they don't get updated after a certain period)
3. Auto label tickets by platform.
4. Auto comment on windows tickets telling them that it requires a community PR and that its not likely that the core team will address it.

If we did the things above it should cut down on overall unhelpful tickets and would automatically label all windows tickets as such so they could get ignored by the team.

**Comment by bradleyflood** [comment]
@jspizziri I agree this would help but I'm not convinced of the benefits. Can you tell me why you think it's worth the time to keep it going? From what I can see Windows Mobile is basically dead and the market share is so so tiny. I just can't see how it's worth us spending our precious time on it.

**Comment by jspizziri** [comment]
@bradleyflood , so I'm pretty ill-informed about in general so I'm completely open to being very incorrect on this; but my understanding is that Windows support isn't for Windows Mobile, but for [a whole host of Windows Devices](https://microsoft.github.io/react-native-windows/) like Xbox, PC's, & Surface tablets. If my understanding is correct, I myself hope to take advantage of it someday.

If I'm correct then I feel it's valuable. If I am wrong then I'm happy to concede & ditch it. But that's just my two cents, not a decision-maker here! 😄

**Comment by dcvz** [comment]
I think it’s a hard choice here.. it’s a fact that we currently have no RN for windows experience + a dev environment for it. I also unfortunately don’t know how much usage there is from RN for windows users..

The current implementation we have was contributed by a Microsoft contractor in their efforts of pushing RN for windows and macOS. So there might be large on increasing interest but we can’t be certain.

It’s very likely that while we don’t have a correctly set up dev environment the windows side will quickly go out of date with new changes and documentation. We already struggle to have contributor’s PR’s address both iOS and Android.

The current approach would’ve been to leave a working 2.X version available in a 2.X branch and from 3.0 drop support for windows. I think that still leaves a working solution for people to use while allowing us to continue innovating and changing the api in 3.0+. 

If we leave it in the main branch it’ll be more of a “it might work but might not work as the documentation indicates” which might not be helpful anyway..

**Comment by dcvz** [comment]
Also @jspizziri your understanding of RN for windows is correct. Here’s more info: https://microsoft.github.io/react-native-windows/

**Comment by jspizziri** [comment]
All, I'm closing this. Lets revisit in the future.
