### ISSUE TITLE
sound does not stop after swiping away notification

### ISSUE THREAD

**Issue by puckey** [doublesymmetry/react-native-track-player#1377]
**Describe the bug**
After I swipe away the notification in the lock-screen, the audio keeps playing

**To Reproduce**
Play some audio, in the lock-screen swipe away the notification

**Environment (please complete the following information):**
System:
    OS: macOS 12.0.1
    CPU: (10) x64 Apple M1 Max
    Memory: 1.26 GB / 64.00 GB
    Shell: 5.1.16 - /opt/homebrew/bin/bash
  Binaries:
    Node: 14.17.4
    Yarn: 3.0.1-rc.1.git.20210805.hash-85bd4f58
    npm: 6.14.14
    Watchman: 2022.01.03.00
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.5 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

What `react-native-track-player` version are you using?
d3ef5b231161a087a48cecd96e87b98609a04d17

Are you testing on a real device or in the simulator? Which OS version are you running?
Real device / Android 12

**Code**
Please, share the code that is causing the issue

**Comment by puckey** [comment]
According to this exoplayer issue `onNotificationCancelled` is no longer called in api version 30 and above: https://github.com/google/ExoPlayer/issues/7964

**Comment by puckey** [comment]
This comment in a related issue seems to point in a possible direction: https://github.com/google/ExoPlayer/issues/7276#issuecomment-617747297

```kotlin
@Override
public void onNotificationPosted(
    int notificationId, Notification notification, boolean ongoing) {
  if (ongoing) {
    startForeground(notificationId, notification);
   } else {
     stopForeground(/* removeNotification= */ false);
   }
}

@Override
public void onNotificationCancelled(int notificationId, boolean dismissedByUser) {
   stopSelf();
}
```

whereas we are doing:

```kotlin
        serviceScope.launch {
            event.notificationStateChange.collect {
                when (it) {
                    is NotificationState.POSTED -> startForeground(it.notificationId, it.notification)
                    is NotificationState.CANCELLED -> stopForeground(true)
                }
            }
        }
```

**Comment by puckey** [comment]
Actually this seems to have been the case with the current version of RNTP also – so not caused by the beta

**Comment by endritbajrami** [comment]
Did you find a solution for this ?

**Comment by afkcodes** [comment]
Yep, this is an existing issue thanks to @mpivchev for acknowledging this. basically the track player should be destroyed once you swipe the notification or remove the app from the recent or BG

**Comment by mpivchev** [comment]
I was not able to reproduce a bug regarding the music service not getting destroyed, or what I did reproduce was working as intended.

- The notification must always be persistent on Android, since that will keep the music service from getting killed by the OS. There is no way to have a dismissible notification when you want your app to play music constantly while in the background.
- Keep in mind that in `App.tsx` there is the flag `stopWithApp` which when set to `true`, will stop the music service AND remove the notification. When set to `false`, the notification will continue showing even if the app is removed from recents, because the music service is still working.
- This can be observed in other music heavy Android apps like Spotify. 

If there are still issues and bugs you still experience that you believe are not intended, please continue to post them here.

**Comment by mpivchev** [comment]
I did some more testing and I did notice that the app process does not get killed when we remove the app from recents, even with `stopWithApp` set to `true`. Is that the issue you are facing @afkcodes? You mentioned that this causes some errors for you. Can you elaborate?

**Comment by afkcodes** [comment]
@mpivchev What I was saying is that when I have `stopWithApp:true` and i remove the app from recent the notification gets removed and the player stops. But the app is not killed which should not be the case. i went into the logs and tried to reproduce it, what i found was that if we remove the app from the recent when the trackplayer is initialized the app stays alive, and if i don't initialize the trackplayer and remove it from recent the app gets killed.

**Comment by mpivchev** [comment]
Update on this [here](https://github.com/DoubleSymmetry/react-native-track-player/discussions/1264#discussioncomment-2429772)

**Comment by afkcodes** [comment]
yeah read this thanks for confirmation @mpivchev this was one of the major issues i am facing in my app. you are really amazing.

**Comment by afkcodes** [comment]
Tested this, one small thing I found is that even if push the app to the background the app restarts when i bring it back to the foreground.

**Comment by mpivchev** [comment]
@afkcodes This bug is still being worked on. It's bigger than originally thought. Please test and report once it's done.

**Comment by afkcodes** [comment]
sure will test have halted my app for this, gonna resume once this is fixed.

**Comment by praisedavid787** [comment]
@afkcodes 
Thought I was the only one facing this issue. Thanks to every one working hard here to bring fixes to these bugs. Love you guys.
@mpivchev
@dcvz 
@jspizziri 
Long live RNTP!!!

**Comment by afkcodes** [comment]
@rpadilla6 yes this issue causes a ripple effect to create some other issues in the app that is actually not related to track player, so we can't do anything except to wait for a fix @mpivchev is trying his level best and im sure he will be back with some great fix. the thing is the library was written earlier in that fashion. i have been facing this for last 2 years so i have pulled my app back from the playstore atleast for now.
