### ISSUE TITLE
Unable to build after changing to mavenCentral

### ISSUE THREAD

**Issue by hafizMDM** [DoubleSymmetry/react-native-track-player#1380]
Since jcenter will not be around after Feb 1, 2022, I was migrating to maven but unfortunatly the library uses 2.11.4 version exoPlayer which is not exist on the maven currently

https://mvnrepository.com/artifact/com.google.android.exoplayer/exoplayer

Can you migrate the library to use the latest version( version that exist on the maven repo)

<img width="592" alt="image" src="https://user-images.githubusercontent.com/2582410/149809079-ca54f346-d368-4c0a-b9d5-e04dc5c9fa58.png">

**Comment by Tucker2015** [comment]
Please try the Android beta version we are testing.

https://github.com/DoubleSymmetry/react-native-track-player/issues/1371

jCenter will still be available as read-only after Feb 1st 2022.

**Comment by bradleyflood** [comment]
Thanks all. Yep this will be addressed in the updated android. 

Also please use the bug Issue template :) Cheers.
