### ISSUE TITLE
Stack in buffering ios 14

### ISSUE THREAD

**Issue by sina3p2p** [DoubleSymmetry/react-native-track-player#1385]
Only in ios 14 stack buffering state when i load local file and audio never play btw it's work as designed in other version of ios 11,12,13 and even 15.

**Comment by kuji2336** [comment]
I have same issue on  IOS 14

**Comment by hfwalter73** [comment]
Same here

**Comment by puckey** [comment]
Do you have any device logs that might help in tracking down this issue?

**Comment by sina3p2p** [comment]
Sir in ios 14 audio stack buffering without any error i use waifForBuffering in setup method but no effect
and when i check player state by usePlaybackState it's shown buffering and there is no error or logs

**Comment by sina3p2p** [comment]
It's very strange problem cause it's work as designed in ios 11-12-13-15

**Comment by kuji2336** [comment]
I have tested on IOS 15 and 12 it's works nice, but problem only occurs on IOS 14.5

**Comment by sina3p2p** [comment]
any news on this problem?

**Comment by sina3p2p** [comment]
i use latest version 2.2.0

**Comment by sina3p2p** [comment]
@puckey any progress?

**Comment by elvenhope** [comment]
Hello, I have a problem making it work on IOS 14. it seems to work on all other ios I have tested 

This is the file. 
[message_3.txt](https://github.com/DoubleSymmetry/react-native-track-player/files/7912881/message_3.txt)

**Comment by sina3p2p** [comment]
@puckey did you check this problem?

**Comment by sina3p2p** [comment]
I tested by demo code and the same issue :(

**Comment by bradleyflood** [comment]
Please use the bug report template next time. Thank you
