### ISSUE TITLE
Unexpected identifier '_reactNativeTrackPlayer'

### ISSUE THREAD

**Issue by SimonGioffredi** [DoubleSymmetry/react-native-track-player#1386]
**Describe the Bug**
After a basic installation, I have this error `Unexpected identifier '_reactNativeTrackPlayer'`.

I tried with and without expo.

**Steps To Reproduce**

1.  Init react-native : `$ npx react-native init TestApp`
2. Add the package : `$ yarn add react-native-track-player` 
3. Create a custom development client : `$ expo install expo-dev-client` then `$ eas build:configure` then `$ eas build --profile development --platform android`
4. Follow first of all [Getting Started](http://react-native-track-player.js.org/getting-started/)

**Code To Reproduce**
```
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
import TrackPlayer from 'react-native-track-player';

await TrackPlayer.setupPlayer({})

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

**Environment Info:**
Paste the results of `npx react-native info`

react-native : `0.64.3`
react-native-track-player : `2.1.2`

Simulator android

**Comment by Kitaps** [comment]
Were you able to solve it? What did you do? I have a similar problem.

"dependencies": {
    "react": "17.0.2",
    "react-native": "0.67.4",
    "react-native-track-player": "^2.1.2"

**Comment by andrewdang17** [comment]
@SimonGioffredi did you ever find out how to fix this?

**Comment by SimonGioffredi** [comment]
@andrewdang17 Yes. 

You need to init setUpPlayer when the App as load, not before.

For me that's, working :

```
const App = () => {
    const [currentTrack, setCurrentTrack] = useState(tracks[0]);
    const playbackState = usePlaybackState();
    const progress = useProgress();

    const setUpTrackPlayer = async () => {
        try {
            await TrackPlayer.setupPlayer();
            await TrackPlayer.updateOptions({
                stopWithApp: true,
                capabilities: [
                    Capability.Play,
                    Capability.Pause,
                    Capability.SeekTo,
                ]
            })
            await TrackPlayer.add(tracks);
        } catch (e) {
            console.log(e);
        }
    };

    const _setCurrentTrack = async () => {
        let trackIndex = await TrackPlayer.getCurrentTrack();
        let trackObject = await TrackPlayer.getTrack(trackIndex);
        setCurrentTrack(trackObject)
    }

    useEffect(() => {
        setUpTrackPlayer();
    }, []);

    ...
}
```

**Comment by andrewdang17** [comment]
@SimonGioffredi that worked for me, thanks!
