### ISSUE TITLE
Event.RemoteDuck: App crash when iPhone receive an incoming call

### ISSUE THREAD

**Issue by ithustle** [doublesymmetry/react-native-track-player#1392]
**Describe the Bug**
My App crash when my iPhone receive an incoming call. 
Even implementing `useTrackPlayerEvents([Event.RemoteDuck], async event => {..}`. 

**Steps To Reproduce**
If added `Even implementing `useTrackPlayerEvents([Event.RemoteDuck], async event => {..}` and `TrackPlayer.addEventListener(Event.RemoteDuck, async e => {}` on `service.js`, only if app were on background it'll works fine.

**Code To Reproduce**
````
useTrackPlayerEvents([Event.RemoteDuck], async event => {
        if (event.paused === true) {
            TrackPlayer.pause();
            wasPausedByDuck = true;
        } else {
            if (wasPausedByDuck === true) {
                TrackPlayer.play();
                wasPausedByDuck = false;
            }
        }
    })
````

**Environment Info:**
````
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 94.34 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /opt/homebrew/opt/node@14/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 6.14.13 - /opt/homebrew/opt/node@14/bin/npm
    Watchman: 2021.08.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
````
Paste the exact `react-native-track-player` version you are using: `2.1.2`
Real device? Or simulator?: `Real Device`
What OS are you running?: 'iOS 15.2.1'

**How I can Help**
I read the documentation. I double check on example project.

**Comment by rajpootathar** [comment]
Exact same issue is happening for me. Any update on this issue?

**Comment by rajpootathar** [comment]
Issue is not related to Track player instead it's an issue with Apple OS 
same issue happening for me 

error received form the event `playback-error` which throws
[RNTrackPlayer.swift:625](https://github.com/DoubleSymmetry/react-native-track-player/blob/main/ios/RNTrackPlayer/RNTrackPlayer.swift#L625)
```
{"error": "Cannot Complete Action"}
```

The same issue is reported over Apple forum as well 
https://developer.apple.com/forums/thread/679862

Issue fixed for me after updating os to latest now I am on 15.3.1

**Comment by jspizziri** [comment]
@rajpootathar glad to see that your issue is solved! I'm going to close this issue in light of that.
