### ISSUE TITLE
Getting stack buffering in ios 14

### ISSUE THREAD

**Issue by sina3p2p** [DoubleSymmetry/react-native-track-player#1394]
**Describe the Bug**
when i load base64 audio in ios 14 it's getting stuck in buffering status and never resolve 
but the same code work at ios 11,12,13,15

**Code To Reproduce**
`{"artist": "თავი 1", "id": 0, "title": "სამგვარი სიყვარული", "url": "data:audio/mp3;base64,SUQzBAAAAAAAVFRDT04AAAAHAAADQ...."}`

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Swift and js

**Comment by bradleyflood** [comment]
Thanks @sina3p2p and sorry to hear about your issue.

If you are able to create a PR for this fix we are keen to see it. Otherwise I'm going to mark this as `Won't Fix` for now as we have limited capacity to move this project forward. Thank you.

**Comment by MaxJadav** [comment]
@sina3p2p  Do you have any solution?
