### ISSUE TITLE
[Feature Request] Event: queue updated

### ISSUE THREAD

**Issue by formula1** [DoubleSymmetry/react-native-track-player#1398]
**What is the need and use case of this feature?**
Whenever the queue is updated, an event is fired. This means for adds and removes

**Describe the ideal solution**
This probably can be done on the javascript side.

**Describe alternatives you've considered**
For my specific situation, I can find the index of the track I need when I need it, I don't have to listen for updates. In addition, all tracks will be removed at once and tracks will probably be added one at a time so indexes should not change. However, others may find it useful.

**Additional context**
For my situation, instead of adding all the tracks at once, I add each track inside of separate components. If a track gets removed or added at an index higher than the track in my component, I then have to keep track of it. For some people it might be useful to be able to listen to an event and update the index of their track within their component's state.

**Some Untested Sample Code**

```javascript

var listeners = [];
var PROMISE_QUEUE_UPDATE_EVENT = Promise.resolve();
async function emitQueueUpdate(){
  if(listeners.length === 0) return;
  // set the promise
  PROMISE_QUEUE_UPDATE_EVENT = TrackPlayer.getQueue();
  // resolve the promise
  const q = await PROMISE_QUEUE_UPDATE_EVENT;
  // run the listeners
  listeners.forEach((l)=(l(q)));
}

function updateWrap(fn){
  // Don't run an update until after the previous update event is finished
  await PROMISE_QUEUE_UPDATE_EVENT;
  const result = await fn();
  // We don't have to wait for the event to return the result. So we emit it right after the update is successful
  emitQueueUpdate();
  return result;
}

// Done this way so they can just return the listenForUpdate(myCallback) right inside of a useEffect hook
export function listenForUpdate(l){
  listeners.push(callback);
  return ()=>{
    listeners = listeners.filter((oL)=>{
      return oL !== l
    })
  }
}

export function add(track, index){
  return updateWrap(()=>{
    return NativeTrackPlayer.add(track, index);
  });
}

export function remove(index){
  return updateWrap(()=>{
    return NativeTrackPlayer.remove(index);
  });
}

```

**Comment by bradleyflood** [comment]
Thanks @formula1 I've added this to the Feature Request list and we will review. Cheers.

**Comment by zackperdue** [comment]
@bradleyflood I'm looking for this feature. Where can we see the feature request list?

**Comment by jspizziri** [comment]
@zackperdue [it's here](https://github.com/doublesymmetry/react-native-track-player/projects/1) in the list "Feature Requests"

Please feel free to contribute!
