### ISSUE TITLE
on iOS, add(track) resolves to null

### ISSUE THREAD

**Issue by formula1** [DoubleSymmetry/react-native-track-player#1399]
**Describe the Bug**
on iOS, the add method on TrackPlayer resolves to null

**Steps To Reproduce**
git clone git@github.com:DoubleSymmetry/react-native-track-player.git
cd react-native-track-player/example
yarn install
cd ios
pod install
cd ..

update ./App.tsx

```diff
diff --git a/example/App.tsx b/example/App.tsx
index b2e9c9d..3c4bb43 100644
--- a/example/App.tsx
+++ b/example/App.tsx
@@ -44,14 +44,16 @@ const setupIfNecessary = async () => {
     compactCapabilities: [Capability.Play, Capability.Pause],
   });
 
-  await TrackPlayer.add(playlistData);
-  await TrackPlayer.add({
+  const i = await TrackPlayer.add(playlistData);
+  console.log("added list:", i);
+  const ii = await TrackPlayer.add({
     url: localTrack,
     title: 'Pure (Demo)',
     artist: 'David Chavez',
     artwork: 'https://i.scdn.co/image/e5c7b168be89098eb686e02152aaee9d3a24e5b6',
     duration: 28,
   });
+  console.log("added single:", ii);
 
   TrackPlayer.setRepeatMode(RepeatMode.Queue);
 };
```

**Environment Info:**

```
react-native-track-player: 2.1.2

System:
    OS: macOS 11.6.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 1.22 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.11.1 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 8.0.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 10.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**How I can Help**

Probably should update the documentation or update iOS. I sent in a pull request

- [The Documentation says it returns a number](https://react-native-track-player.js.org/documentation/#addtracks-insertbeforeindex)
- [Readme.md says it returns undefined](https://github.com/DoubleSymmetry/react-native-track-player#%EF%B8%8F-v2-migration-guide)
- [The iOS code itself resolves null](https://github.com/DoubleSymmetry/react-native-track-player/blob/main/ios/RNTrackPlayer/RNTrackPlayer.swift#L342)
- [The Windows code also resolves null](https://github.com/DoubleSymmetry/react-native-track-player/blob/main/windows/RNTrackPlayer/Players/Playback.cpp#L102)
- For android
  - [The MusicModule uses the MusicBinder handle the callback](https://github.com/DoubleSymmetry/react-native-track-player/blob/main/android/src/main/java/com/guichaguri/trackplayer/module/MusicModule.java#L223)
  - [Which provides a playback to do the actual add](https://github.com/DoubleSymmetry/react-native-track-player/blob/main/android/src/main/java/com/guichaguri/trackplayer/service/MusicBinder.java#L30)
  - [But seems to provide the actual index](https://github.com/DoubleSymmetry/react-native-track-player/blob/main/android/src/main/java/com/guichaguri/trackplayer/service/player/LocalPlayback.java#L89)

**Temporary Solution**

```javascript
async function add(track, index){
  if(Platform.OS !== "ios") return TrackPlayer.add(track, index);
  if(typeof index === "number"){
    await TrackPlayer.add(track, index);
    return index;
  }
  const queue = TrackPlayer.getQueue();
  await TrackPlayer.add(track);
  return queue.length;
}
```

**Comment by bradleyflood** [comment]
Nicely documented Issue. Thank you

**Comment by formula1** [comment]
Pull request merged : )
