### ISSUE TITLE
skipToPrevious() is not worked to make queue in ios (error: only for 1st json tracklist object)

### ISSUE THREAD

**Issue by AshaKaligatla** [doublesymmetry/react-native-track-player#1406]
**Bug Description**
Possible Unhandled Promise Rejection (id: 0):
Error: There is no previous track

**Steps To Reproduce**
skipToPrevious() is not worked to make queue in ios(worked in android) for the first object of json tracklist and skipToNext() is worked as expected (perfectly queued on both env)

**Code To Reproduce**
service.js: 
  TrackPlayer.addEventListener(Event.RemotePrevious, () => {
    TrackPlayer.skipToPrevious();
  });
playlistData.json:
[
    {
      "url": "https://sample-music.netlify.app/Bad%20Liar.mp3",
      "title": "Longing",
      "artist": "user1",
      "id": 1,
      "artwork": "https://images.unsplash.com/photo-1496304841270-2cb66cf766b4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
      "duration": 143
    },
]
player.js:
const setupIfNecessary = async () => {
  const currentTrack = await TrackPlayer.getCurrentTrack();
  if (currentTrack !== null) {
    return;
  }

  await TrackPlayer.setupPlayer({});
  await TrackPlayer.reset();
  await TrackPlayer.updateOptions({
    stopWithApp: false,
    capabilities: [
      Capability.Play,
      Capability.Pause,
      Capability.SkipToNext,
      Capability.SkipToPrevious,
    ],
    compactCapabilities: [
      Capability.Play,
      Capability.Pause,
      Capability.SkipToNext,
      Capability.SkipToPrevious,
    ],
    notificationCapabilities: [
      Capability.Play,
      Capability.Pause,
      Capability.SkipToNext,
      Capability.SkipToPrevious,
    ],
  });

  await TrackPlayer.add({
    url: 'https://sample-music.netlify.app/death%20bed.mp3',
    title: 'Pure (Demo)',
    artist: 'user0',
    id: 0,
    artwork: 'https://images.unsplash.com/photo-1598267410503-d0ef01973f69?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=654&q=80',
    duration: 28,
  });

  await TrackPlayer.add(playlistData);

  TrackPlayer.setRepeatMode(RepeatMode.Queue);
};

const togglePlayback = async playbackState => {
  const currentTrack = await TrackPlayer.getCurrentTrack();
  if (currentTrack == null) {
  } else if (playbackState !== State.Playing) {
    await TrackPlayer.play();
  } else {
    await TrackPlayer.pause();
  }
};

const Player = () => {
  const playbackState = usePlaybackState();
  const progress = useProgress();

  const [trackArtwork, setTrackArtwork] = useState();
  const [trackTitle, setTrackTitle] = useState();
  const [trackArtist, setTrackArtist] = useState();

  useTrackPlayerEvents([Event.PlaybackTrackChanged], async event => {
    if (
      event.type === Event.PlaybackTrackChanged
      && event.nextTrack !== undefined
    ) {
      const track = await TrackPlayer.getTrack(event.nextTrack);
      const { title, artist, artwork } = track || {};
      setTrackTitle(title);
      setTrackArtist(artist);
      setTrackArtwork(artwork);
    }
  });

  useEffect(() => {
    setupIfNecessary();
  }, []);

  return (
    <SafeAreaView style={ styles.screenContainer }>
      <View style={ styles.actionRowContainer }>
        <TouchableWithoutFeedback onPress={ () => TrackPlayer.skipToPrevious() }>
          <Text style={ styles.secondaryActionButton }>Prev</Text>
        </TouchableWithoutFeedback>
        <TouchableWithoutFeedback onPress={ () => togglePlayback(playbackState) }>
          <Text style={ styles.primaryActionButton }>
            { playbackState === State.Playing ? 'Pause' : 'Play' }
          </Text>
        </TouchableWithoutFeedback>
        <TouchableWithoutFeedback onPress={ () => TrackPlayer.skipToNext() }>
          <Text style={ styles.secondaryActionButton }>Next</Text>
        </TouchableWithoutFeedback>
      </View>
    </SafeAreaView>
  );
};
**Environment Info:**
"react-native": "0.66.4",
"react-native-track-player": "^2.1.2",
os: macOS(big sur-11.5.2)
Real Device: iphone 12

could you please help me to fix this as soon as possible...Thanks in Advance

**Comment by jspizziri** [comment]
@AshaKaligatla are you still having this issue? If so can you please create a minimum reproducible example repo?
