### ISSUE TITLE
Expo (Bare & Managed workflow) crashes on the Web platform

### ISSUE THREAD

**Issue by iboxgithub** [doublesymmetry/react-native-track-player#1407]
**Describe the Bug**
Hi, I am following this [tutorial](https://instamobile.io/mobile-development/react-native-music-player/) to try to make your lib work with an Expo Bare workflow (ejected) but I have few open points:

- it works on iOS and Android but is their implementation correct?
- don't know why they use the variable `isCurrentTrack`
- [android warning] No task registered for key TrackPlayer
- it crashes on Web cf [this issue](https://github.com/expo/expo/issues/16227#issuecomment-1032968514) (Can't resolve '../Utilities/Platform'), mentioned [here](https://stackoverflow.com/questions/60746444/utilities-platform-missing-for-react-native) but couldn't find a fix for me

**Steps To Reproduce**
`yarn web`

**Code To Reproduce**
this is the repo to reproduce my project: [test3](https://github.com/iboxgithub/test3)

**Environment Info:**
Paste the results of `npx react-native info`
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 928.38 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 17.4.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: 2022.01.31.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Paste the exact `react-native-track-player` version you are using
"react-native-track-player": "^2.1.2"

Real device? Or simulator? 
Simulator

What OS are you running?
MacOS Monterey

**Comment by iboxgithub** [comment]
anyone?

**Comment by iboxgithub** [comment]
if necessary, I could sponsor this fix btw

**Comment by iboxgithub** [comment]
@dcvz any chance you would take a look at this issue?

**Comment by iboxgithub** [comment]
?

**Comment by iboxgithub** [comment]
> @iboxgithub, sorry for the late response.
> 
> At this time [Web is not supported, as you can see here](https://react-native-track-player.js.org/platform-support/). It's theoretically possible to support Web however it's an extensive effort and would probably be a ways down the road.
> 
> However, if you're interested in sponsoring such an endeavor then I'm all ears. Are you interested in and able to sponsor something that has a pretty large scope?

Hi @jspizziri, thanks for your answer ;)
We are currently in our beta phase but yes we would be up to sponsor that effort. The beta is supposed to last until at least August, is there a way to reach out directly in order to not raise another ticket for this?

**Comment by jspizziri** [comment]
@iboxgithub please email team@doublesymmetry.com and let them know!
