### ISSUE TITLE
Notification controls are flickering after calling TrackPlayer.updateOptions

### ISSUE THREAD

**Issue by mpivchev** [doublesymmetry/react-native-track-player#1419]
### Notification controls are doing weird after TrackPlayer.updateOptions

Faced an issue when I need to hide Controls.
```js
await TrackPlayer.updateOptions({
      capabilities: [],
      compactCapabilities: [],
 })
```

`TrackPlayer.updateOptions` with empty `capabilities` and `compactCapabilities` works and changes can be viewed in the notification but after sliding progress slider icons appeared and disappeared. 
 
 [Bug Video](https://drive.google.com/file/d/1JctVqVRFOSXnqifwhq3Uq5xSfVaKZmzZ/view?usp=sharing)
 
 **Repo** 
 https://github.com/rajpootathar/track-player-beta-testing
 
 **My Code for testing**
 On the playing state it will update the capabilities with options but on the pausing state it will update capabilities with an empty array
 ```js
   const togglePlayback = async _playbackState => {
    const currentTrack = await TrackPlayer.getCurrentTrack();
    if (currentTrack == null) {
      alert('No Track');
    } else {
      if (_playbackState !== State.Playing) {
        await TrackPlayer.updateOptions({
          capabilities: [
            Capability.Play,
            Capability.Pause,
            Capability.JumpForward,
            Capability.JumpBackward,
            Capability.Stop,
          ],
          compactCapabilities: [
            Capability.Play,
            Capability.Pause,
            Capability.JumpBackward,
            Capability.JumpForward,
          ],
        });
        await TrackPlayer.play();
      } else {
        await TrackPlayer.pause();
        await TrackPlayer.updateOptions({
          capabilities: [],
          compactCapabilities: [],
        });
      }
    }
  };
  ```
  [App.js:67](https://github.com/rajpootathar/track-player-beta-testing/blob/main/App.js#L67)

### Thinking

`updateOptions` is calling  `player.notificationManager.createNotification` [MusicService:138](https://github.com/DoubleSymmetry/react-native-track-player/blob/feature/kotlinaudio/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt#L138) every time when we call the `TrackPlayer.updateOptions` but in NotificationManager their is a note 

`**NOTE:** You should only call this once. Subsequent calls will result in an error.`
[KotlinAudio/NotificationManager:172](https://github.com/DoubleSymmetry/KotlinAudio/blob/main/kotlin-audio/src/main/java/com/doublesymmetry/kotlinaudio/notification/NotificationManager.kt#L172)

@dcvz @mpivchev

_Originally posted by @rajpootathar in https://github.com/DoubleSymmetry/react-native-track-player/discussions/1264#discussioncomment-2181043_

**Comment by peymancyb** [comment]
I am also facing this issue +1

**Comment by ViencoC** [comment]
If you go to see the KotlinAudio code above the createNotification function there is the comment where it says that by calling that function several times (and it is the one that is called when updatingOptions is done) you will encounter problems.

A workaround would be to set the player to null like this
internalNotificationManager?.setPlayer(null)
in the createNotification function before all other things

I have tested it summarily and it seems to work, I don't have time for a PR on kotlinaudio

I'll do it as soon as I can.

**Comment by peymancyb** [comment]
@PandaRN94 thank you so much!

It worked! ✅


First time, notification is not appear, I had to resolve it with a delay, but now it works:

```

        if(internalNotificationManager != null){
            // Reset player
            internalNotificationManager?.setPlayer(null)
            delay(500) // Wait for 1 second
        }

```


Thank you so much!

**Comment by peymancyb** [comment]
Hi @jspizziri @PandaRN94 ,

I have tried adding the delay and also the `hideNotification` method, but the issue still exist,
Do you have any suggestion how to fix it?

we are really blocked by this issue, I would highly appreciate if you can help and support us on this issue. 🙏

**Comment by peymancyb** [comment]
Hello 🙌 
Any idea how to fix this issue?

I would highly appreciate your support on this, I have tried a lot of different approaches but still fail to fix this issue

**Comment by puckey** [comment]
I tried to replicate this issue, but was unable to.. things seem to work as expected on my side..

@peymancyb:
- what is broken exactly?
- how can I replicate it?

**Comment by puckey** [comment]
@mvn-hungtruong-dn @kirillzyusko same questions for you

here is the code I am using to test:

```ts
  let count = 0;
  setInterval(() => {
    const divisibleByTwo = count++ % 2 === 0;
    const divisibleByThree = count % 3 === 0;
    TrackPlayer.updateOptions({
      android: {
        appKilledPlaybackBehavior:
          AppKilledPlaybackBehavior.StopPlaybackAndRemoveNotification,
      },
      capabilities: divisibleByTwo ? [] : [
        Capability.Play,
        Capability.Pause,
        divisibleByThree ? Capability.SkipToNext : undefined,
        Capability.SkipToPrevious,
        Capability.SeekTo,
      ].filter(a => a !== undefined),
      compactCapabilities: divisibleByTwo ? [] : [
        Capability.Play,
        Capability.Pause,
        Capability.SkipToNext,
      ]
    });
  }, 2000)
```

Here is a screen capture of what I am seeing on my Android 13 test device: https://github.com/doublesymmetry/react-native-track-player/assets/271885/b8a7ad35-89c0-4239-b5ff-ab16b366a43a

**Comment by kirillzyusko** [comment]
@puckey we were able to replicate it, when we've initialized player and update options with:

```ts
{
  android: {
    appKilledPlaybackBehavior:
      AppKilledPlaybackBehavior.StopPlaybackAndRemoveNotification,
  },
  notificationCapabilities: [],
  capabilities: [
    Capability.Play,
    Capability.Pause,
    Capability.SeekTo,
    Capability.SkipToNext,
    Capability.SkipToPrevious,
  ],
  compactCapabilities: [
    Capability.Play,
    Capability.Pause,
    Capability.SeekTo,
    Capability.SkipToNext,
    Capability.SkipToPrevious,
  ],
};
```

After some time we've changed it to:

```ts
{
  android: {
    appKilledPlaybackBehavior:
      AppKilledPlaybackBehavior.StopPlaybackAndRemoveNotification,
  },
  notificationCapabilities: [],
  capabilities: [
    Capability.Play,
    Capability.Pause,
    Capability.SeekTo,
  ],
  compactCapabilities: [
    Capability.Play,
    Capability.Pause,
    Capability.SeekTo,
  ],
};
```

And if you interact with play/pause button from notification - you'll notice flickering. I'll try to craft reproduction example in next 1-2 hours 👀

**Comment by kirillzyusko** [comment]
@puckey here we go, use the next code and replace it in `App.tsx` in example project:

```tsx
import React, { useEffect, useState } from 'react';
import {
  ActivityIndicator,
  Linking,
  SafeAreaView,
  StatusBar,
  StyleSheet,
  View,
} from 'react-native';
import TrackPlayer, { AppKilledPlaybackBehavior, Capability, UpdateOptions, useActiveTrack } from 'react-native-track-player';

import { Button, PlayerControls, Progress, TrackInfo } from './components';
import { QueueInitialTracksService, SetupService } from './services';

let isDefault = true;
const defaultOptions: Partial<UpdateOptions> = {
  android: {
    appKilledPlaybackBehavior:
      AppKilledPlaybackBehavior.StopPlaybackAndRemoveNotification,
  },
  notificationCapabilities: [],
};
const defaultCapabilities: Capability[] = [
  Capability.Play,
  Capability.Pause,
  Capability.SeekTo,
];
const capabilitiesWithNextAndPrevButtons: Capability[] = [
  ...defaultCapabilities,
  Capability.SkipToNext,
  Capability.SkipToPrevious,
];
export const multipleTrackOptions: UpdateOptions = {
  ...defaultOptions,
  capabilities: capabilitiesWithNextAndPrevButtons,
  compactCapabilities: capabilitiesWithNextAndPrevButtons,
};
export const singleTrackOptions: UpdateOptions = {
  ...defaultOptions,
  capabilities: defaultCapabilities,
  compactCapabilities: defaultCapabilities,
};

const App: React.FC = () => {
  const track = useActiveTrack();
  const isPlayerReady = useSetupPlayer();

  useEffect(() => {
    function deepLinkHandler(data: { url: string }) {
      console.log('deepLinkHandler', data.url);
    }

    // This event will be fired when the app is already open and the notification is clicked
    const subscription = Linking.addEventListener('url', deepLinkHandler);

    // When you launch the closed app from the notification or any other link
    Linking.getInitialURL().then((url) => console.log('getInitialURL', url));

    return () => {
      subscription.remove();
    };
  }, []);

  if (!isPlayerReady) {
    return (
      <SafeAreaView style={styles.screenContainer}>
        <ActivityIndicator />
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.screenContainer}>
      <StatusBar barStyle={'light-content'} />
      <View style={styles.contentContainer}>
        <View style={styles.topBarContainer}>
          <Button
            title="Queue"
            onPress={() => {
              if (isDefault) {
                TrackPlayer.updateOptions(singleTrackOptions);
                isDefault = false;
              } else {
                TrackPlayer.updateOptions(multipleTrackOptions);
                isDefault = true;
              }
            }}
            type="primary"
          />
        </View>
        <TrackInfo track={track} />
        <Progress live={track?.isLiveStream} />
      </View>
      <View style={styles.actionRowContainer}>
        <PlayerControls />
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  screenContainer: {
    flex: 1,
    backgroundColor: '#212121',
    alignItems: 'center',
    justifyContent: 'center',
  },
  contentContainer: {
    flex: 3,
    alignItems: 'center',
  },
  topBarContainer: {
    width: '100%',
    flexDirection: 'row',
    paddingHorizontal: 20,
    justifyContent: 'flex-end',
  },
  actionRowContainer: {
    flex: 1,
    flexDirection: 'row',
  },
});

function useSetupPlayer() {
  const [playerReady, setPlayerReady] = useState<boolean>(false);

  useEffect(() => {
    let unmounted = false;
    (async () => {
      await SetupService();
      if (unmounted) return;
      setPlayerReady(true);
      const queue = await TrackPlayer.getQueue();
      if (unmounted) return;
      if (queue.length <= 0) {
        await QueueInitialTracksService();
      }
    })();
    return () => {
      unmounted = true;
    };
  }, []);
  return playerReady;
}

export default App;
```

Run app on API 28 emulator (for some reasons it works fine on API 33) and do next:
- press play;
- open notification - all controls work as expected;
- press on Queue button (it'll set new options)
- open notification and try to press play/pause button 👀 

I've attached a video too:

https://github.com/doublesymmetry/react-native-track-player/assets/22820318/3e071f80-8ff4-4276-9ac0-b8d2ee785543

**Comment by puckey** [comment]
Thanks – I can reproduce using an Android 9 device.

**Comment by kirillzyusko** [comment]
@dcvz @puckey the issue can be closed because https://github.com/doublesymmetry/KotlinAudio/pull/85 was merged 🙂
