### ISSUE TITLE
The track does not remove when unmounting screen

### ISSUE THREAD

**Issue by meetwithtaha** [DoubleSymmetry/react-native-track-player#1420]
**Describe the Bug**
I'm using Track Player with version ^2.2.0-beta14. I want to stop the Player and remove tracks from the queue when the screen gets unmounted. but it crashing in ios and not removing tracks from the queue.  

**Steps To Reproduce**
add tracks in React.useEffect and in return function of useEffect remove tracks  

**Code To Reproduce**
  const addTrack = async (tracks: TrackModel[]) => {
        await TrackPlayer.add(tracks)
    }

    const removeTracks = async () => {
        const trackIndexs : number[] = [] 
        tracks.map((_, i) => {
            trackIndexs.push(i)
        })
        await TrackPlayer.remove(trackIndexs)
    }

 useEffect(() => {

        setTimeout(() => {
            addTrack(tracks)
        }, 1000)

        return () => {
           removeTracks() // not working still in cache.
        }

    }, [])

**Environment Info:**
"react-native-track-player": "^2.2.0-beta14",

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

**Comment by DennisdeWitNL** [comment]
Are these all the tracks you want to remove? Why not use TrackPlayer.reset()? That’s what works for me.

**Comment by meetwithtaha** [comment]
That was not working for me in  this version "react-native-track-player": "^2.2.0-beta14" so i had to upgrade to "react-native-track-player": "^2.1.2". it is working fine now.
