### ISSUE TITLE
userAgent not working correctly 

### ISSUE THREAD

**Issue by klaaz0r** [doublesymmetry/react-native-track-player#1422]
**Describe the Bug**
When setting the `userAgent ` in the track property I noticed that on iOS that it does not work at all, server side I still receive the default apple core media agent instead of the manually set one

**Steps To Reproduce**
- set a custom userAgent 
- Ping your own server/file

result (on iOS) 

```
AppleCoreMedia/1.0.0.19E5235a (iPhone; U; CPU OS 15_4 like Mac OS X; en_us)
```

**Comment by klaaz0r** [comment]
After some digging it looks like the userAgent property is never actually used in iOS:

```
 func load(from url: URL, playWhenReady: Bool, options: [String: Any]? = nil) {
        reset(soft: true)
        _playWhenReady = playWhenReady

        if currentItem?.status == .failed {
            recreateAVPlayer()
        }
        
        
        self._pendingAsset = AVURLAsset(url: url, options: options)
        ....
```

Options does not seem to contain any custom agents set

**Comment by klaaz0r** [comment]
Should I create a PR and remove this from the readme?

**Comment by dcvz** [comment]
@klaaz0r we separately support setting headers which you could use to set the user agent so we should probably remove the individual property for `userAgent`

**Comment by curthipster** [comment]
> @klaaz0r we separately support setting headers which you could use to set the user agent so we should probably remove the individual property for `userAgent`

@dcvz I noticed today that `headers: { 'User-Agent': 'myagent'}` only works for iOS and `userAgent: 'myagent'` only works for Android. Your comment implies that `headers` should work for both and `userAgent` is deprecated.
