### ISSUE TITLE
Can't use seekTo on live audio streams (audio/mpeg)

### ISSUE THREAD

**Issue by BlackBank** [doublesymmetry/react-native-track-player#1425]
**Describe the Bug**
seekTo doesn't work on live audio streams (audio/mpeg), it restarts/reset the stream when using the function.

**Steps To Reproduce**
Use an audio/stream url (radio channel for example) via the function add() and change the position with seekTo().

**Code To Reproduce**
```javascript
<Button title="Test" onPress={() => {
                            (async () => {
                                let position = await trackPlayer.getPosition();

                                await trackPlayer.seekTo(position - 0.5);
                            })();
                        }}/>
```

**Environment Info:**
Using version 2.2.0-rc2 of react native track player. 
Tested it on Android (simulator), not sure if this happends on iOS, will test!

**Comment by DennisdeWitNL** [comment]
It’s a livestream. What is your goal?

**Comment by BlackBank** [comment]
> It’s a livestream. What is your goal?

I want to use this function, so you can jump forward and backwards some seconds.

**Comment by BlackBank** [comment]
I did some tests on iOS, and there it all works fine, so it's an Android issue.

**Comment by jspizziri** [comment]
@BlackBank can you create a minimum reproducible example repo for this issue?

I think it makes sense that you could scrub within whatever is currently buffered.

**Comment by jspizziri** [comment]
@dcvz is this something we should be concerned about with the Kotlin rewrite?
