### ISSUE TITLE
Progress is not reset when playing audio in track repeat mode when screen is lock on iOS

### ISSUE THREAD

**Issue by Artem2001S** [doublesymmetry/react-native-track-player#1426]
[iOS] When screen locked, progress didn't reset when playing audio in track repeat mode. `TrackPlayer.setRepeatMode(RepeatMode.Track);`

**Steps To Reproduce**
1) Set repeat mode equals to RepeatMode.Track `TrackPlayer.setRepeatMode(RepeatMode.Track);`
2) Add tracks to player and run `TrackPlayer.play()`
3) Lock your phone, wait until the audio is played several times, after which the progress will stop at 100% and will not change, but the song will be played and the `useProgress` hook will give the correct values for position

**Code To Reproduce**
Please provide a simple code example that allows others to replicate the bug.
My service.js file:

<pre>import TrackPlayer, {Capability, RepeatMode} from 'react-native-track-player';

TrackPlayer.updateOptions({
  // Media controls capabilities
  stopWithApp: true,

  alwaysPauseOnInterruption: false,
  capabilities: [
    Capability.Play,
    Capability.SeekTo,
    Capability.Pause,
    Capability.SkipToNext,
    Capability.SkipToPrevious,
    Capability.Stop,
  ],

  // Capabilities that will show up when the notification is in the compact form on Android
  compactCapabilities: [Capability.Play, Capability.Pause],
});

TrackPlayer.setRepeatMode(RepeatMode.Track);

module.exports = async function () {
  TrackPlayer.addEventListener('remote-play', () => TrackPlayer.play());

  TrackPlayer.addEventListener('remote-pause', () => TrackPlayer.pause());

  TrackPlayer.addEventListener('remote-stop', () => TrackPlayer.destroy());
};
</pre>

**Environment Info:**
    "react-native-track-player": "^2.1.2",

System:
    OS: macOS 12.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 563.83 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/node_modules/.bin/yarn
    npm: 8.5.1 - /usr/local/bin/npm
    Watchman: 2021.12.27.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 29.0.2, 30.0.2, 32.0.0
      System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.1 => 0.67.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**How I can Help**
What can you do to help resolve this? - Provide the code
Have you investigated the underlying JS or Swift/Android code causing this bug? - No
Can you create a Pull Request with a fix? - No (

**Comment by jspizziri** [comment]
@Artem2001S question:

Are you saying that the native iOS lockscreen widget stops reporting the correct position but the `useProgress` hook still works?

**Comment by jspizziri** [comment]
Ah, I just tested this and I can confirm that it's the lock screen progress that gets stuck at 100.

**Comment by jspizziri** [comment]
I've [filed an issue with SwiftAudioEx](https://github.com/doublesymmetry/SwiftAudioEx/issues/15)

**Comment by jspizziri** [comment]
There's [a new PR in `SwiftAudioEx` that should address this issue](https://github.com/doublesymmetry/SwiftAudioEx/pull/28). You can [see more detail here](https://github.com/doublesymmetry/SwiftAudioEx/issues/15#issuecomment-1247109590).

**Comment by puckey** [comment]
Verified as fixed with https://github.com/doublesymmetry/react-native-track-player/pull/1713

**Comment by jspizziri** [comment]
Closed by https://github.com/doublesymmetry/react-native-track-player/pull/1713

**Comment by jspizziri** [comment]
Closed by https://github.com/doublesymmetry/react-native-track-player/pull/1713
