### ISSUE TITLE
App instance lives after app removed from recents when track player is intialized.

### ISSUE THREAD

**Issue by afkcodes** [doublesymmetry/react-native-track-player#1428]
**Describe the Bug**
App instance lives even if we remove the app from the background when the Track player is initialized/running

**Steps To Reproduce**
We need to look at logs. the app should be killed when we remove the app from the recent no matter if the trackplayer is running. In this case, the Sounds stops playing but the instance lives and the app also don't get killed and the app resumes instead of restarting on opening the app again. When the trackplayer is not initialized or running the app gets killed properly.

**Code To Reproduce**
reproducible in the example app as well

**Environment Info:**
Paste the results of `npx react-native info`
```
info Fetching system and libraries information...
System:
    OS: macOS 11.6.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 2.64 GB / 20.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/n/bin/node
    Yarn: 1.22.17 - ~/n/bin/yarn
    npm: 8.3.1 - ~/n/bin/npm
    Watchman: 2022.01.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0, 32.0.0, 32.1.0
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.3 => 0.67.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Paste the exact `react-native-track-player` version you are using
2.2.0-rc2

Real device? Or simulator?
Real Device

What OS are you running?
Android 12

**How I can Help**
What can you do to help resolve this?
Currently have no idea of the new implementation

Have you investigated the underlying JS or Swift/Android code causing this bug?
I looked into the logs and confirmed

Can you create a Pull Request with a fix?
Sorry

**Comment by endritbajrami** [comment]
Did you find a solution to this problem because i'm having it too :(

**Comment by afkcodes** [comment]
No i am still living with this issue and this happens in the android rewrite as well.

**Comment by endritbajrami** [comment]
same :/ ... but thank you for the response

**Comment by jspizziri** [comment]
@mpivchev  it looks like this might be a duplicate (or at least addressed by) this issue?

https://github.com/doublesymmetry/react-native-track-player/issues/1377

@afkcodes can you confirm/deny?

**Comment by mpivchev** [comment]
@jspizziri yes. It's related.

**Comment by mpivchev** [comment]
Closed for duplication. Check #1377
