### ISSUE TITLE
Audio does not work when running in an iOS physical device without an earphone

### ISSUE THREAD

**Issue by regishideki** [doublesymmetry/react-native-track-player#1430]
**Describe the Bug**
Audio does not work when running in iOS on a physical device without an earphone. In a simulator and/or with an earphone, it works!

**Steps To Reproduce**
Run the app on iOS mobile, but without an earphone

**Code To Reproduce**
Any code should have the same behavior once it seems to be the integration between the lib and the iOS and not in the code that uses it. But, if necessary, I can provide a snippet.

**Environment Info:**
Paste the results of `npx react-native info`
```
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 124.17 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 8.5.1 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.2 - /Users/regis/.rvm/gems/ruby-2.6.0@mobile/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-S | Google Play ARM 64 v8a, android-Sv2 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Users/regis/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Paste the exact `react-native-track-player` version you are using
2.1.2

Real device? Or simulator?
Only in real device

What OS are you running?
iOS 14.4

**How I can Help**
I can create a Pull Request to fix it if someone could help me with some direction because I am not a very experienced react native developer.

**Comment by dcvz** [comment]
@regishideki this is a weird bug.. I think we might've noticed if this was the case.
Does this also happen to you with the included example project?

**Comment by jspizziri** [comment]
@regishideki please attempt to reproduce this with the example project. If it still happening please submit a repro that consistently demonstrates the issue. I've never seen this happen before nor can I reproduce it with the example project.

I'm happy to reopen if more information or a repo demonstrating the issue is provided.

Thanks!
