### ISSUE TITLE
[Feature Request] updateNowPlayingMetadata elapsedTime

### ISSUE THREAD

**Issue by ZiizouChrist** [doublesymmetry/react-native-track-player#1435]
**Describe the Bug**
updateNowPlayingMetadata elapsedTime doesn't work as expected. Do nothing.

**Steps To Reproduce**
Set elapsedTime from updateNowPlayingMetadata function

**Code To Reproduce**
TrackPlayer.updateNowPlayingMetadata({
            duration: 50,
            elapsedTime: 30,
})

**Environment Info:**
Real device 
Android 11
OnePlus 7T

**How I can Help**
I need to reset progress bar to 0 when I update metas.
I use RNTP for live radio stream and I want to reset progress bar in notification player.
Please help me.

**Comment by jspizziri** [comment]
@ZiizouChrist what version of react-native-track-player are you using?

**Comment by ZiizouChrist** [comment]
@jspizziri thanks for your reply. I use version 2.1.2

**Comment by jspizziri** [comment]
@ZiizouChrist any chance you could see if this is still an issue in [v2.2.0-rc3](https://github.com/doublesymmetry/react-native-track-player/releases/tag/v2.2.0-rc3)?

It's a complete Android overhaul and it's definitely possible that it has been resolved in that version.

Thanks!

**Comment by ZiizouChrist** [comment]
@jspizziri Thank you very much for your help and sorry for the replying delay.
Same issue with v2.2.0-rc3, I can't set a custom elapsedTime.

Maybe is just impossible ? Wanted to manually set the notification progress bar because I use audio live stream.

Thanks again.

**Comment by jspizziri** [comment]
@ZiizouChrist I looked into the code and it doesn't really look like this was ever working on android. Does it work on iOS the way you'd expect? I've also noticed that there's no formal documentation about it (although it is referenced in code).

**Comment by ZiizouChrist** [comment]
@jspizziri It doesn't work on iOS and Android. If no solution exists I have to disable this progress bar. Can you tell me how can I disable it on iOS ? On android it works but on iOS the progress bar is weird, the start of progress bar is 0:00 and the end is -0:00.
Thanks.

**Comment by jspizziri** [comment]
@ZiizouChrist quick question: have you tried the `isLiveStream` property?

**Comment by ZiizouChrist** [comment]
@jspizziri Yes, I've just tried IsLiveStream. No success

**Comment by jspizziri** [comment]
Closing, we'll evaluate new feature requests at some point in the future (unless someone wants to contribute from the community)
