### ISSUE TITLE
Android `TrackPlayer.reset()` resolving too quickly

### ISSUE THREAD

**Issue by JDMathew** [doublesymmetry/react-native-track-player#1445]
**Describe the Bug**
There seems to be an issue with `TrackPlayer.reset()` resolving it's promise too quickly. 

According to documentation `reset()`:
> Resets the player stopping the current track and clearing the queue.

This means the queue should be empty after calling `TrackPlayer.reset()` i.e `getQueue() // should retrun []`

After adding a track to the queue, If I run the following:
``` javascript
const resetTrack = async () => {
    try {
      await TrackPlayer.reset()
      const queue = await TrackPlayer.getQueue()
        console.log('queue', queue)
    } catch (error) {
      console.log('Error from reset', error)
    }
  }
```

No error is thrown, however:

```
console.log('queue', queue) // returns the queue and not an empty array []
```

If I instead, force a delay before calling `getQueue()` then the correct result is returned:

For example:

``` javascript
 const resetTrack = async () => {
    try {
      await resetPlayBack()
      setTimeout(async () => {
        const queue = await TrackPlayer.getQueue()
        console.log('queue', queue)
      }, 100)
    } catch (error) {
      console.log('error', error)
    }
  }
``` 

Then
```
console.log('queue', queue) // returns an empty array []
```

Furthermore it seems strange to me that after resetting `getCurrentTrack()` would be 0 and that the playbackState is left in a paused state (its previous state) and not None. I.e:
``` javascript
const currentTrackIndex = await TrackPlayer.getCurrentTrack() // 0
await TrackPlayer.getTrack(currentTrackIndex ?? 0) // null
const playBackState = usePlaybackState() // 3 (Paused)
```

Surely `playBackState` should be None (i.e enum of 0) and not Paused (3). If it is Paused then it would appear that a track can be played but when running `play()` nothing will happen. `play()` also silently fails even though there is no track for it to run i.e `getTrack()` is null but `await TrackPlayer.play().catch(console.log)`, the promise resolves but nothing is played. instead of being rejected. Is this the desired behaviour?

**Environment Info:**
This issue was found on react-native-track-player `^2.2.0-rc2`. 
```console
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 178.75 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2022.03.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 30, 31, 32
      Build Tools: 30.0.2, 32.0.0, 32.1.0
      System Images: android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
Device:
```
Device name: OnePlus 7T
Android version: 11
Build number: Oxygen OS 11.0.6.1.HD65AA
Model: HD1905
```

**Comment by jspizziri** [comment]
https://github.com/doublesymmetry/react-native-track-player/issues/1371

**Comment by jspizziri** [comment]
@JDMathew i'm actually going to close this ticket in favor of https://github.com/doublesymmetry/react-native-track-player/issues/1522 because it addresses the issue on a broader scale.

**Comment by sadam-hussien** [comment]
I have many playlists, I want to change the current playlist with new playlist which user choose it.
i tried using Trackplayer.reset() but the application stopped and closed.
any help?

**Comment by hitulnayakpara** [comment]
> I have many playlists, I want to change the current playlist with new playlist which user choose it.
> i tried using Trackplayer.reset() but the application stopped and closed.
> any help?

Same Issue
