### ISSUE TITLE
App is closing immediately when i call  TrackPlayer.setupPlayer() in android

### ISSUE THREAD

**Issue by Krish143git** [doublesymmetry/react-native-track-player#1450]
**Describe the Bug**

     When i am initialising the track player app is closing immediately. I am using below packages
     "react-native-video": "^5.2.0",    exo-player version : 2.13.2
      "react-native-track-player": "1.2.7",  exo-player version : 2.11.4
       
     Below code i written : 
        when the below statements will execute app is closing with out warnings and errors.
       const trackPlayerInit = async (audioUrl: string) => {
          await TrackPlayer.setupPlayer() // entry point 
       }
    
   I have done some R& D i came across the the below points : 
        
   
     Because of some video issues i have added this line react-native.config.js  :  
         dependencies: {
          "react-native-video": {
              platforms: {
                  android: {
                      sourceDir: "../node_modules/react-native-video/android-exoplayer",
                  },
              },
          },
      },
     
      1) When i comment the above lines, even though exo-player versions mismatch both players are working. when I uncomment 
    the above lines the app is closing when it come across this line await TrackPlayer.setupPlayer().
     "react-native-video": "^5.2.0",    exo-player version : 2.13.2
      "react-native-track-player": "1.2.7",  exo-player version : 2.11.4

      2) So I have downgraded the video package to 5.1.1  to make exo-player versions match. if  i comment the above lines both are 
     working, but  when i uncomment it  app is not opening by clicking on App icon
       "react-native-video": "^5.1.1",    exo-player version : 2.11.4
      "react-native-track-player": "1.2.7",  exo-player version : 2.11.4
    
     3)Instead of downgrading the video package i upgraded the track player to 2.0.0 & 2.0.1 They are also working on same exo- 
     player version i.e : 2.11.4.  and also same issues as @point2 

      
Finally :  Even though mismatching of exo-player version app is working when we comment the above lines 

output Required : I cant uncomment the below lines.So how to proceed with track player ?
     
       dependencies: {
          "react-native-video": {
              platforms: {
                  android: {
                      sourceDir: "../node_modules/react-native-video/android-exoplayer",
                  },
              },
          },
      },  

 
**Environment Info:**
    
System:
    OS: macOS 11.6.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 32.62 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-29 | Android TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.14.0 => 16.14.0 
    react-native: ^0.63.3 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

   react-native-track-player` : '1.2.7'

What OS are you running? 

1) device : samsung S10
2)version : android 11

  

**How I can Help**
  Pls help me how to fix this issue

**Comment by Krish143git** [comment]
@JDMathew  Can u  please mention the release candidate version. so i will check from my side

**Comment by JDMathew** [comment]
> @JDMathew Can u please mention which release candidate version number . so i will check from my side

I'm on `2.2.0-rc2` but `2.2.0-rc3` has just been released so I would upgrade to that one as it fixes a number of issues picked up in `2.2.0-rc2`
