### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by iphonic** [doublesymmetry/react-native-track-player#1451]
I am receiving the following error when I installed version **2.1.2** and compiled

Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined.

**Steps To Reproduce**
Install the 2.1.2 version supposed to be latest, and compile

**Code To Reproduce**
Please provide a simple code example that allows others to replicate the bug.

**Environment Info:**
System:
    OS: macOS 11.6.1
    CPU: (8) x64 Apple M1
    Memory: 39.56 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0
      System Images: android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.1 => 0.67.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Paste the exact `react-native-track-player` version you are using => 2.1.2

Real device? Or simulator? => Real Device

What OS are you running? => Oxygen OS 11.0.6.1HD65AA

**How I can Help**
What can you do to help resolve this?
=> The following error goes when I changes the AndroidManifest.xml file inside node_modules for `react-native-track-player` with the following changes

OLD (This gives error which comes with the version)
=======
```
<!-- A receiver that will receive media buttons. Required on pre-lollipop devices -->
<receiver android:name="androidx.media.session.MediaButtonReceiver">
    <intent-filter>
        <action android:name="android.intent.action.MEDIA_BUTTON" />
    </intent-filter>
</receiver>
```

NEW(This resolves the error)
========

```
<!-- A receiver that will receive media buttons. Required on pre-lollipop devices -->
  <receiver android:name="androidx.media.session.MediaButtonReceiver" android:exported="true">
      <intent-filter>
          <action android:name="android.intent.action.MEDIA_BUTTON" />
      </intent-filter>
  </receiver>
```

Please fix in the main library.

**Comment by saudahmed** [comment]
I faced the same problem for target Android-12. Apps targeting Android 12 and higher are required to specify an explicit value for android:exported when the corresponding component has an intent filter defined.

I made the similar as stated above and it work for me too. Please fix this as a bug fix in a new release

**Comment by martinmidtsund** [comment]
Hi, Android 12 will be supported in 2.2.0 I guess, take a look at this discussion where you can help test the new version https://github.com/DoubleSymmetry/react-native-track-player/discussions/1264

**Comment by jspizziri** [comment]
@iphonic @saudahmed please upgrade to v2.2.0-rc3, that should solve your problem.
