### ISSUE TITLE
Artist should not be required for TrackPlay functionality on iOS

### ISSUE THREAD

**Issue by JDMathew** [doublesymmetry/react-native-track-player#1469]
**Describe the Bug**
It seems on iOS artist is required when adding a track otherwise `await TrackPlayer.add(tracks)` will not resolve. This is not the case on Android. According to the Type artist is not required. If artist is required this is undocumented. 

We could update the docs to make it required on iOS but in some cases you may not know the artist and so it would be better if the underlying issue is fixed. 

Please see reference to Track Base Type here:
https://github.com/doublesymmetry/react-native-track-player/blob/0af6e2f7b8f4935c0464195d893e61b03d619097/src/interfaces.ts#L202-L213

**Steps To Reproduce**
How can someone else reproduce this bug?
Add a Track without artist on iOS - promise will not resolve

**Environment Info:**
running `react-native-track-player` version `2.1.3`
I this is an issue on `2.2.0-rc2` as well

Linked issue confirming behaviour: #1468

**Comment by jspizziri** [comment]
@JDMathew thanks for the report! Would you be able to take a crack at fixing the issue?

**Comment by jspizziri** [comment]
@JDMathew the fix was pretty easy so I went ahead and implemented it.

**Comment by JDMathew** [comment]
@jspizziri, thanks for adding a PR fixing this. I left a [comment](https://github.com/doublesymmetry/react-native-track-player/pull/1481#issuecomment-1104253728) on your PR just letting you know that title should also not be required according to the Track interface. https://github.com/doublesymmetry/react-native-track-player/blob/90fc0e76b47a741b5fed04846fff3c89913ed66d/src/interfaces.ts#L202-L213

**Comment by jspizziri** [comment]
@JDMathew this fix just got merged. I'm going to close this. It will be available in the next release (likely `2.2.0-rc4`).
