### ISSUE TITLE
Android app crashing when starting playing a mp3 after upgrading from RN 0.60.5 to 0.67.4

### ISSUE THREAD

**Issue by sebpapaechocharliekilo** [doublesymmetry/react-native-track-player#1474]
**Describe the Bug**

We use this plugin since a while with RN 0.60.5 and v 2.0.0-rc13, after upgrading to RN 0.67.4 we started having issues like exoplayer2 missing etc... so we added it as well.

But now right when we start to play a MP3 the app crash.

React code we use to play the MP3:

```
async play(sound: string): Promise<void> {
    if (this.state.playerReady) {
      try {
        await TrackPlayer.reset();
        const track: Track = {
          id: sound,
          url: sound,
          title: 'mp3',
          artist: 'Sounds'
        };
        await TrackPlayer.add(track);
        TrackPlayer.play();
        console.log('added track', track);
      } catch (e) {
        console.log(e);
      }
    }
  }
```

Error:

E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: XXXXX, PID: 11100
    java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
        at com.facebook.react.bridge.ReadableNativeArray.getDouble(ReadableNativeArray.java:92)
        at com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument(JavaMethodWrapper.java:64)
        at com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument(JavaMethodWrapper.java:60)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:356)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:920)

**Environment Info:**

System:
    OS: macOS 12.2.1
    CPU: (8) x64 Apple M1
    Memory: 24.13 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.4 - ~/.nvm/versions/node/v12.22.4/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.24.1 - ~/.nvm/versions/node/v12.22.4/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/seb/.rvm/gems/ruby-2.7.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-25 | Google APIs ARM 64 v8a, android-26 | ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-S | Google APIs ARM 64 v8a, android-S | Google Play ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Any one else managed to make the plugin works with 0.67.4? 
Any help would be appreciated 

Note: on iOS all works like a charm as always

**Comment by jspizziri** [comment]
@sebpapaechocharliekilo , there is no version `v2.0.0-rc13`. Do you mean `v2.0.0-rc3`?

I can verify that the project works with `react-native@0.68.0` so my guess is that it either has something to do with your local RN project or how you're using the package.

Could you please try installing the package in a fresh RN project and see if you still have the issue? If you do then please send a link to the repository so I can take a look.

**Comment by sebpapaechocharliekilo** [comment]
@jspizziri yes there is --> https://github.com/doublesymmetry/react-native-track-player/releases/tag/v2.0.0-rc13

i will re-install the package in a fresh RN and update you

**Comment by sebpapaechocharliekilo** [comment]
@jspizziri I know it's old. Tested latest 2.0.x, 2.1.x, 2.2.x as well.
Will try to reproduce in a bare RN and come back to you
