### ISSUE TITLE
FATAL EXCEPTION: mqt_native_modules using v2.2.0-rc3 in release build

### ISSUE THREAD

**Issue by austinried** [doublesymmetry/react-native-track-player#1475]
**Describe the Bug**
Just trying out `v2.2.0-rc3` and I was able to test in debug mode somewhat fine, but in release mode I'm seeing this crash 100% of the time on app launch, kills the app completely:

```
FATAL EXCEPTION: mqt_native_modules

kotlin.w: lateinit property player has not been initialized

FATAL EXCEPTION: mqt_native_modules
Process: com.subtracks, PID: 3466
kotlin.w: lateinit property player has not been initialized
	at com.doublesymmetry.trackplayer.service.MusicService.L(Unknown Source:6)
	at com.doublesymmetry.trackplayer.module.MusicModule.getQueue(Unknown Source:22)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:148)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:147)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
	at java.lang.Thread.run(Thread.java:920)
```

**Steps To Reproduce**
Not sure where to start but you can build subtracks and see the problem on my branch here if you want: https://github.com/austinried/subtracks/tree/react-native-track-player-next

**Code To Reproduce**
https://github.com/austinried/subtracks/tree/react-native-track-player-next

**Environment Info:**
Paste the results of `npx react-native info`
```
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 158.45 MB / 15.39 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.19.1 - /tmp/yarn--1650003558066-0.14211410378890887/node
    Yarn: 1.22.18 - /tmp/yarn--1650003558066-0.14211410378890887/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.12 - /home/austin/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
  npmGlobalPackages:
    *react-native*: Not Found
```
Paste the exact `react-native-track-player` version you are using
> `2.2.0-rc3`

Real device? Or simulator?
> Two simulated devices (one running Android 12, the other Android 9) one real device (Pixel 4 Android 12)

What OS are you running?
> Ubuntu 20.04

**How I can Help**
What can you do to help resolve this?
> I can test suggested changes

Have you investigated the underlying JS or Swift/Android code causing this bug?
> No, I can try but I have very little Java experience and none in Kotlin

Can you create a Pull Request with a fix?
> Probably not

**Comment by jspizziri** [comment]
@mpivchev this looks relevant to the android rewrite, can you confirm?

**Comment by austinried** [comment]
Some more maybe related info since I don't know what I'm doing with Kotlin really: I am using react-native-async-storage's "next" module as well, which also requires a different version of Kotlin.  I tried to resolve that like this in my `build.gradle`:

```gradle
    dependencies {
...
        // react-native-async-storage next
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.21"

        // react-native-track-player
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.30"
...
    }
```

I used to have a `kotlinVersion` in the `ext` section as well but removed that.  It seems to build fine like this but I'm not actually sure it's the right way to set this up.

**Comment by austinried** [comment]
Actually after looking into the MusicService a bit I'm realizing that the issue here seems to be `getQueue()` is being called before `setupPlayer()`.  This is happening because I register a listener in the playback service to hook into changes in network state (mobile/wifi) and I need to rebuild the queue with new URLs that correspond to new bitrate quality values when this changes.  The problem in this case being that the first time I set the state, it also tries to rebuild the queue and crashes.

It seems I need a way to determine if the player has been setup, but I don't see a method for that?  Although I guess even if I had that check, it kinda seems like I would need to wrap all of my interactions with TrackPlayer with it to avoid this crash, in case any of them happen to get called before the setup is finished (net state changes before setup, maybe a track gets played quickly or on startup, etc, it's a race condition).

Not sure how to proceed here, any thoughts?

**Comment by jspizziri** [comment]
Could you simply set a store value with something like MMKV or LocalStorage once setup has been successful?

Then you could conditionally call the queue build in your service.

**Comment by austinried** [comment]
Yeah I think I can work around the specific issue I'm having now by registering the net event handler later, but I'm a little worried about how to handle waiting on doing anything with TrackPlayer that might interact with the uninitialized `lateinit player` before it's setup, you know?  I can't async delay registering the main component, so things are going to start mounting before that's ready no matter what, and if someone manages to try to start playing a song or I ever have an auto-play feature for example, it's a race to that crash.

I do have a splash screen currently, I guess I could wait in that before mounting the rest of the application.  Is that intended though?  Seems like I need to recreate this safeguard that was there before the rewrite.

**Comment by jspizziri** [comment]
I believe it might be possible to setup the track player in your index and then once it's promise resolves register your app component and service. I haven't tried it though.

**Comment by austinried** [comment]
I tried that, but it throws an error about `AppRegistry.registerComponent` not being called if you delay it behind something async/await.

But you know the more I think about it the more I am realizing that yeah in a media player app like mine it does makes sense to just wait on mounting anything media player related until that setup is done anyway.

I've done some experimenting with setting up the player during the splash screen and waiting there, and it seems like I can try/catch around `setupPlayer` every time to see if the player has been setup already or not (since I can't distinguish in between first launch or subsequent launches that have unmounted/closed the app but the player is still running) in order to see if I need to `updateOptions` and to the net state handler registration.

So I think we can close this issue then, and maybe I'll take a look at the docs for this rewrite and add a sufficient warning about interacting with TrackPlayer before `setupPlayer` is called, if that sounds good to you.
