### ISSUE TITLE
Allow "one shot" tracks

### ISSUE THREAD

**Issue by haswalt** [DoubleSymmetry/react-native-track-player#148]
Brilliant lib so far, just implementing it in our app. Would it be possible to play a track without adding it to the queue?

So essentially pausing the queue, playing given track and resuming the queue afterwards? Obviousl pause and resume could be handled with the existing controls but I don't see a way to play a track without messing with the queue.

**Comment by haswalt** [comment]
Or is it possible to extract the current queue? I'm looking into adding something for iOS but don't really know enough about android to take a stab at it.

**Comment by haswalt** [comment]
For my second option i've added pr #152 as I think it would be useful to get back the current queue anyway.

**Comment by dcvz** [comment]
we've added the ability to get the queue using `getQueue` as for playing one track without offsetting the queue is not in target with what this library hopes to achieve. I'll leave it as a suggestion
