### ISSUE TITLE
[Android] crash with no logs - Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE

### ISSUE THREAD

**Issue by okevino47** [doublesymmetry/react-native-track-player#1484]
**Describe the Bug**
App crash (android only) when starting or reseting a playtrack, i do not have any logs affiliated to this crash and **i only found some indication with flipper debugger**

Before i update my sdk version from 30 to 31 and i was on lib version 2.1.2 i didn't get any crash

error given : 
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

FATAL EXCEPTION: main
Process: com.appname, PID: 15830
java.lang.RuntimeException: Unable to start service com.guichaguri.trackplayer.service.MusicService@8f5629a with Intent { cmp=com.appname/com.guichaguri.trackplayer.service.MusicService }: java.lang.IllegalArgumentException: com.appname: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5110)
	at android.app.ActivityThread.access$2200(ActivityThread.java:310)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.IllegalArgumentException: com.appname: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
	at android.support.v4.media.session.MediaSessionCompat.<init>(MediaSessionCompat.java:559)
	at android.support.v4.media.session.MediaSessionCompat.<init>(MediaSessionCompat.java:530)
	at android.support.v4.media.session.MediaSessionCompat.<init>(MediaSessionCompat.java:494)
	at com.guichaguri.trackplayer.service.metadata.MetadataManager.<init>(MetadataManager.java:62)
	at com.guichaguri.trackplayer.service.MusicManager.<init>(MusicManager.java:68)
	at com.guichaguri.trackplayer.service.MusicService.onStartCommand(MusicService.java:108)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5092)
	... 9 more

**Steps To Reproduce**
Use target and compileSdkVersion = 31 and set lib version to 2.1.3
after this call any function from TrackPlayerInstance

**Code To Reproduce**
Due to some complexe integration in my application (a mix between redux, sagas) i m not able to provide sample of code.

But this occur at any function call of "TrackPlayerInstance"

**Environment Info:**
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Apple M1
    Memory: 24.67 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v14.19.1/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

"react-native-track-player": "2.1.3",
Real device - galaxy s10 + - android version 12

**How I can Help**
Actually i am looking for a solution and it seems to be a recognized error on some others libs with ancient / outdated libraries but i am actually not able to provide a patch

**Comment by jspizziri** [comment]
@okevino47 can you please see if you have this issue with `v2.2.0-rc3`? There's a massive android rewrite underway and unless this is an issue there it likely won't be addressed.

**Comment by jspizziri** [comment]
Actually, after reading this it sounds like you're trying to upgrade to apiVersion 31. This is supported in the RC I mentioned, it's actually the minimum level. You can see this comment for more details

https://github.com/doublesymmetry/react-native-track-player/issues/1193#issuecomment-1098140118

**Comment by okevino47** [comment]
Thank you for you quick answer 🙂 
i tried with the version 2.2.0-rc3 and yeah that work.

Hope it will be release soon, good luck for your job 🙂

**Comment by MaxJadav** [comment]
For quick fix with old version 1.2.7

**Step 1.** Inside react-native-track-player -> build.gradle
   Remove-    implementation "androidx.media:media:1.1.0"
   Add+    implementation "androidx.media:media:1.4.1"
**Step 2.** /node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java

**Update**
_builder.setContentIntent(PendingIntent.getActivity(context, 0, openApp, PendingIntent.FLAG_CANCEL_CURRENT));_
**To**
_if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.S) {
   		 builder.setContentIntent(PendingIntent.getActivity(context, 0, openApp, PendingIntent.FLAG_IMMUTABLE));
	}
	else {
  	  builder.setContentIntent(PendingIntent.getActivity(context, 0, openApp, PendingIntent.FLAG_CANCEL_CURRENT));
	}_

**Comment by gavrichards** [comment]
This issue means we can't update our app to React Native 0.68. Is there likely to be a release soon?

**Comment by jspizziri** [comment]
@gavrichards Please see my comment

https://github.com/doublesymmetry/react-native-track-player/issues/1484#issuecomment-1105508767

**Comment by gavrichards** [comment]
Thanks @jspizziri I've seen all the relevant comments, I just wondered if there's any news of when the next release is likely to be? Thanks

**Comment by jspizziri** [comment]
@gavrichards The next RC? Or a final version of  2.2

**Comment by gavrichards** [comment]
@jspizziri a release that contains a fix for this issue, whatever that happens to be :)

**Comment by jspizziri** [comment]
@gavrichards As I mentioned please install v2.2.0-rc3

**Comment by gavrichards** [comment]
@jspizziri ok I was concerned about using that in production in case it wasn't ready.

**Comment by jspizziri** [comment]
@gavrichards , there are known issues so I don't consider it production ready. Several fixes in the way. It's it's a minor version release meaning there should not be any BC breaks. If there are they would be considered bugs that would be fixed.

**Comment by ProtoJoe** [comment]
> For quick fix with old version 1.2.7
> 
> **Step 1.** Inside react-native-track-player -> build.gradle Remove- implementation "androidx.media:media:1.1.0" Add+ implementation "androidx.media:media:1.4.1" **Step 2.** /node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java
> 
> **Update** _builder.setContentIntent(PendingIntent.getActivity(context, 0, openApp, PendingIntent.FLAG_CANCEL_CURRENT));_ **To** _if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.S) { builder.setContentIntent(PendingIntent.getActivity(context, 0, openApp, PendingIntent.FLAG_IMMUTABLE)); } else { builder.setContentIntent(PendingIntent.getActivity(context, 0, openApp, PendingIntent.FLAG_CANCEL_CURRENT)); }_

For anyone who is not in a position to update to 2.x, and needs to stay on 1.2.7 for a while, I've forked the repo at the 1.2.7 tag and made the changes suggested above. This works for me in my project, and I'm going to keep it live in my company's repo.  Repo is here:

https://github.com/world50/react-native-track-player

Update your `package.json` like so:

`"react-native-track-player": "^1.2.7",` -> `"react-native-track-player": "https://github.com/world50/react-native-track-player.git#8c042c8",`

**Comment by MaxJadav** [comment]
@ProtoJoe 
After fixing this FLAG_IMMUTABLE issue.  Crashing in release mode, do you have any solution?
https://github.com/doublesymmetry/react-native-track-player/issues/1551#issue-1246676844

**Comment by francowanseele** [comment]
Hello! I don't want to update to version 3.x

This issue was solved in version 2.1.4 ??

Thanks :)
