### ISSUE TITLE
[Feature Request] Fade in and out

### ISSUE THREAD

**Issue by KrisLau** [doublesymmetry/react-native-track-player#1486]
**What is the need and use case of this feature?**
I would love to use this package however I'm having trouble trying to figure out how to dynamically fade out the audio. Ideally, I would love to be able to fade out the audio between the tracks I play and also to fade out when the user starts/stops the audio track. Currently I believe I would need to create a timer that gradually reduces the volume using `setVolume`?

**Describe the ideal solution**
My thought is that there could be a `fadeIn`, `fadeOut`, and `fadeStop` props where they would default to 0. So they would all take in a duration which controls how fast the fade happens. `fadeStop` would basically delay the stop and fade out the music in the duration given .

**Describe alternatives you've considered**
N/A (I couldn't find any other packages)

**Additional context**
I'm basically working off the [Howler.js](https://github.com/goldfire/howler.js) structure and simplifying it

**How I can Help**
Not sure? I can help with documentation maybe?

**Comment by jspizziri** [comment]
@KrisLau thanks for the request. I have a clarifying question and then some thoughts.

**Question** 

Are you trying to cross fade tracks or simply fade each one in and out?

**Thoughts**

From my perspective this seems like a valid feature but it falls into the category of "nice-to-have"/non-critical. As such and with the realities of our resources being small and also largely directed at other more critical tasks (see the android rewrite and bugs) the chances of this happening on a short timeline are very slim.

What it's going to require to get it done anytime soon would be a champion willing to do the legwork and put in the time to research and implement.

If you're up for that task then we can: 

1. Open a design discussion and approve something that works.
2. Provide guidance in the implementation journey.

**Comment by KrisLau** [comment]
> **Question**
> Are you trying to cross fade tracks or simply fade each one in and out?
The latter! Although I believe that implementing this might also help with the existing cross fading since I'm thinking that cross fading could just utilize the individual track fading to achieve a cross fade. For example, the first track would just need to set `fadeOut` and the subsequent tracks would set both `fadeIn` and `fadeOut`.

> **Thoughts**
> 
> From my perspective this seems like a valid feature but it falls into the category of "nice-to-have"/non-critical. As such and with the realities of our resources being small and also largely directed at other more critical tasks (see the android rewrite and bugs) the chances of this happening on a short timeline are very slim.
> 
> What it's going to require to get it done anytime soon would be a champion willing to do the legwork and put in the time to research and implement.
> 
> If you're up for that task then we can:
> 
> 1. Open a design discussion and approve something that works.
> 2. Provide guidance in the implementation journey.
I would love to however I've never worked on any JavaScript libraries before, how difficult do you think it would be for me as a new-ish JS dev to implement it? If it's not too difficult, I would be more than willing to try my hand at it.

**Comment by KrisLau** [comment]
@jspizziri Sound good, it sounds a little daunting since I have zero experience in both Swift and Kotlin haha but I'll try and play with it whenever I get some free time and I'll see how it goes!

**Comment by KrisLau** [comment]
@jspizziri That's heartening to hear and I'll try that! I'm definitely not as experienced haha I've only been working for a year in React Native or anything mobile. 😆

**Comment by lovegaoshi** [comment]
While the right way to do this is through volumeshaper as mentioned in https://github.com/z-huang/InnerTune/issues/889 and whatever the ios counterpart , I seem to have [hacked out](https://github.com/lovegaoshi/azusa-player-mobile/pull/142) this feature with JS (Animated.Value).

for the kind soul decided to write up a PR for this, this is simply putting any TrackPlayer playback events (TrackPlayer.play/pause/skipnext/skipprevious) as a callback to Animated.timing, and hooking TrackPlayer.setVolume to Animated.Value as a listener.
