### ISSUE TITLE
TypeError: null is not an object (evaluating 'TrackPlayer.RATING_HEART')

### ISSUE THREAD

**Issue by sjorsroelofs** [doublesymmetry/react-native-track-player#1504]
**Describe the Bug**
When adding react-native-track-player to a new React Native project (without Expo) I get the following error:

> TypeError: null is not an object (evaluating 'TrackPlayer.RATING_HEART')

**Steps To Reproduce**
- `npx react-native init AwesomeProject`
- `cd AwesomeProject`
- `npm install --save react-native-track-player`
- In App.js: `import TrackPlayer from 'react-native-track-player';`
- `npx react-native run-android` (same result on iOS)
- Error appears

**Code To Reproduce**
See steps to reproduce.

**Environment Info:**
**npx react-native info**

> System:
    OS: macOS 12.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 30.03 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 30, 31
      Build Tools: 30.0.2, 30.0.3, 31.0.0
      System Images: android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7621141
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**react-native-track-player version**
> ^2.1.3

**Real device? Or simulator?**
Both

**What OS are you running?**
Android, iOS, iOS Simulator

Thanks a lot!

**Comment by jspizziri** [comment]
@sjorsroelofs did you follow the instructions [here](https://react-native-track-player.js.org/docs/basics/installation) and [here](https://react-native-track-player.js.org/docs/basics/getting-started)? Specifically running `setupPlayer`?

From your report above it's not clear to me that you did.

**Comment by sjorsroelofs** [comment]
Thanks for the reply. I'm now getting a different error.
In index.js I added this:
`TrackPlayer.registerPlaybackService(() => require('./service'));`

And in App.js I added this:
`import TrackPlayer from 'react-native-track-player';
await TrackPlayer.setupPlayer({});`

The error i'm getting right now is:

> Unexpected identifier '_reactNativeTrackPlayer'
no stack

Am I doing something wrong in the setup? I followed the instructions, but it's not clear to me what's going wrong..

**Comment by jspizziri** [comment]
@sjorsroelofs did you also run a `pod install` in your ios directory? Just realized thats not in the docs.

**Comment by jspizziri** [comment]
@sjorsroelofs can you take a look at the setup of the [Example app](https://github.com/doublesymmetry/react-native-track-player/tree/main/example) and mirror what it's doing? Something seems to be wrong with how you've set it up and I'm not entirely sure what it is.

**Comment by jspizziri** [comment]
Also see this issue which might be related https://github.com/doublesymmetry/react-native-track-player/issues/719

**Comment by jspizziri** [comment]
@sjorsroelofs what were the important things missing in the docs? If its the case we should get them updated.

**Comment by sjorsroelofs** [comment]
Sorry, couldn't test on Android yesterday. Tried it now and getting a build error when running on an Android device:

> FAILURE: Build failed with an exception.
What went wrong:
Could not determine the dependencies of task ':react-native-track-player:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-track-player:debugCompileClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer-dash:2.11.4.
     Searched in the following locations:
       - file:/Users/sjors/Desktop/***/node_modules/react-native/android/com/google/android/exoplayer/exoplayer-dash/2.11.4/exoplayer-dash-2.11.4.pom
       - file:/Users/sjors/Desktop/***/node_modules/jsc-android/dist/com/google/android/exoplayer/exoplayer-dash/2.11.4/exoplayer-dash-2.11.4.pom
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer-dash/2.11.4/exoplayer-dash-2.11.4.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-dash/2.11.4/exoplayer-dash-2.11.4.pom
       - https://www.jitpack.io/com/google/android/exoplayer/exoplayer-dash/2.11.4/exoplayer-dash-2.11.4.pom
       - file:/Users/sjors/Desktop/***/node_modules/react-native-track-player/node_modules/react-native/android/com/google/android/exoplayer/exoplayer-dash/2.11.4/exoplayer-dash-2.11.4.pom
     Required by:
         project :react-native-track-player


By using [this issue](https://github.com/react-native-video/react-native-video/issues/2500) I figured out it was solved by adding jcenter() to the Android build.gradle file.

Now I see the media controls in Android, but no music is playing. After a few seconds the controls disapears. Works perfectly on iOS though.. I'm trying to play an HLS (m3u8) stream.

**Comment by topovik** [comment]
Are there any solutions to this problem?

**Comment by PaulCombal** [comment]
I'm fairly sure this is still an issue using expo. It doesn't matter how well I follow the instructions, the error comes from this line in lib/interfaces.js:

```javascript
var TrackPlayer = react_native_1.NativeModules.TrackPlayerModule;
```

NativeModules is:
```
Native Modules written in ObjectiveC/Swift/Java exposed via the RCTBridge Define lazy getters for each module. These will return the module if already loaded, or load it if not. See [https://reactnative.dev/docs/native-modules-ios](vscode-file://vscode-app/snap/code/104/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)
```

```javascript
RatingType[RatingType["Heart"] = TrackPlayer.RATING_HEART] = "Heart";
```

In the code above TrackPlayer is `null`. The variable is not reassigned anywhere else in the file.

[The documentation](https://react-native-track-player.js.org/docs/basics/installation#expo) states that expo is supported. 

I have the default expo setup as stated in the official react native docs, blank project. I can provide minimal code if needed @jspizziri .

Thank you for spending time on the issue.

**Comment by HobaiGuigui** [comment]
Try this on all "Evaluting error" Ex: **'TrackPlayer.RATING_HEART'**  => **'TrackPlayer?.RATING_HEART'**

**Comment by rickyanwar** [comment]
ny solution of this
