### ISSUE TITLE
Docs: Network Caching Guide

### ISSUE THREAD

**Issue by jspizziri** [doublesymmetry/react-native-track-player#1507]
I think a guide that discusses network caching for advanced usage would be very helpful. crating this based on the conversation here (and the points covered in it)

https://discord.com/channels/567636850513018880/600714011318681610/968155680932528220

**Comment by Strate** [comment]
@jspizziri could you paste guide somewhere else pls? I can't access that content for unknown reason :(

**Comment by jspizziri** [comment]
@Strate perhaps there's some confusion. This is just an issue representing the task of creating a guide. There is no guide at this point, but you can join Discord and see the conversation we had about it (see the link in the description).

**Comment by Strate** [comment]
@jspizziri could you please post an invite link?

**Comment by jspizziri** [comment]
https://discordapp.com/invite/ya2XDCR
