### ISSUE TITLE
Could not find com.google.android.exoplayer:exoplayer-core:2.11.4

### ISSUE THREAD

**Issue by sjorsroelofs** [doublesymmetry/react-native-track-player#1510]
**Describe the Bug**
When running the app with react-native-track-player on Android, I get the following error:

> Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer-core:2.11.4.
     Searched in the following locations:
       - file:/Users/sjors/.m2/repository/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/Users/sjors/Desktop/react-native-track-player-main/example/node_modules/react-native/android/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/Users/sjors/Desktop/react-native-track-player-main/example/node_modules/jsc-android/dist/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://www.jitpack.io/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
     Required by:
         project :app > project :react-native-track-player

This also happens with the example project. I commented in [this ticket](https://github.com/doublesymmetry/react-native-track-player/issues/1504), where I said the solution was to add jcenter() to the Android build.gradle file, but I think that only removes the error and doesn't solves the problem, because the player on Android still won't work after that and incidentally crashes the app.

**Steps To Reproduce**
- Install the example app
- run `npm install`
- run `npm run android`

**Code To Reproduce**
Example app

**Environment Info:**
`npx react-native info`

> System:
    OS: macOS 12.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 54.24 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 30, 31
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7621141
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

`react-native-track-player`
> ^2.1.3

**Real device? Or simulator?**
Real Android device

Again, thanks a lot!

**Comment by jspizziri** [comment]
This is a know issue that's resolve in 2.2.0-rc3

https://github.com/doublesymmetry/react-native-track-player/issues/1235#issuecomment-1098086394

**Comment by sjorsroelofs** [comment]
> This is a know issue that's resolve in 2.2.0-rc3
> 
> [#1235 (comment)](https://github.com/doublesymmetry/react-native-track-player/issues/1235#issuecomment-1098086394)

Alright, perfect, 2.2.0-rc3 seems to be working great. Thank you so much for your excellent support! You made my day :)
