### ISSUE TITLE
Playback pauses when track added to Queue

### ISSUE THREAD

**Issue by jspizziri** [doublesymmetry/react-native-track-player#1513]
**Describe the Bug**

If you're actively playing a track and you add another item to the queue playback is paused (Android only).

**Steps To Reproduce**

1. Add tracks to the queue.
2. Begin playing a track.
3. Add another track to the queue.
4. Observe that playback has paused.

**Environment Info:**
Building `main`

**Comment by jspizziri** [comment]
@dcvz this is the issue I chatted you about.

**Comment by fierysolid** [comment]
Does someone have this or should I take a look?

**Comment by jspizziri** [comment]
@fierysolid , I don't think anyone is looking at it yet. Be my guest! LMK if you need any help/guidance.

**Comment by jspizziri** [comment]
I just tested this against [`KotlinAudio#main`](https://github.com/doublesymmetry/KotlinAudio/commit/37671364f67c39e95b95b0c8e9c23f4e38100693) and it's still an issue there.

**Comment by jspizziri** [comment]
I've submitted a PR which addresses this issue: https://github.com/doublesymmetry/KotlinAudio/pull/29

**Comment by lordkyle0** [comment]
Is this  reviewed in the next version ?

**Comment by jspizziri** [comment]
@lordkyle0 I think will land in the next patch version. I spoke with @mpivchev about it this morning, and he needs to do some additional investigation. The fix I put in place is relatively crude (although it does work).

**Comment by jspizziri** [comment]
Closing in favor of https://github.com/doublesymmetry/react-native-track-player/issues/1691 which addresses this on iOS and Android.
