### ISSUE TITLE
An error occurred while playing the current track

### ISSUE THREAD

**Issue by iboxgithub** [doublesymmetry/react-native-track-player#1514]
**Describe the Bug**
My code used to work until yesterda, I could play songs on my iOS simulator without any problem. But since this morning, for whatever reason the warning below keeps on appearing and I can't play music anymore:
```
Object {
  "error": "resource unavailable",
  "type": "playback-error",
}
```

**Steps/code To Reproduce**
this is triggered on the event: `Event.PlaybackError`
the code provoking it is when I add my songs to the TrackPlayer object: `await TrackPlayer.add(tempList);`

**Environment Info:**
Paste the results of `npx react-native info`
```
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 59.30 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 17.4.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: 2022.01.31.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Paste the exact `react-native-track-player` version you are using
`"react-native-track-player": "^2.1.2",`

Real device? Or simulator?
iOS simulator

What OS are you running?
iOS 15.2

**How I can Help**
What can you do to help resolve this? 
_Unfortunately I can't on another simple repo (I have a lot of code), but I also tried to git clone using past commits but even the ones from a week ago don't work anymore..._

Have you investigated the underlying JS or Swift/Android code causing this bug?
_The JS yes, I didn't find anything despite using past versions of the code when everything was working. I also restarted the Simulator and uninstalled the app, the bug remains._

Can you create a Pull Request with a fix?
_I don't have one_

**Comment by iboxgithub** [comment]
I restarted my MacBook and now it works again...any idea what could have caused this behavior?

**Comment by jspizziri** [comment]
Glad it's working again. The short answer is that if you didn't upgrade the package version then the issue has to be with your app code.

**Comment by iboxgithub** [comment]
> Glad it's working again. The short answer is that if you didn't upgrade the package version then the issue has to be with your app code.

Hi @jspizziri , I didn't update my code though, so there is something odd here imo

**Comment by jspizziri** [comment]
It sounds like a classic case of a corrupted memory state to me. Unless it's happening with a high frequency this is something that comes with the territory of using a computer and much more so with heavy usage (like building apps and running simulators etc).
