### ISSUE TITLE
TrackPlayer.add return type is incorrect

### ISSUE THREAD

**Issue by josemiguel-alvarez** [doublesymmetry/react-native-track-player#1515]
**Describe the Bug**
TrackPlayer.add return type is `Promise<void>`.

Link to the TrackPlayer.add function: https://github.com/doublesymmetry/react-native-track-player/blob/3ee71f1d8584a1c33b3fc8a418cb7c1de4423a0e/src/trackPlayer.ts#L82

It should be a number as specified in the documentation.

Link to the documentation: https://react-native-track-player.js.org/docs/api/functions/queue#addtracks-insertbeforeindex

**Comment by jspizziri** [comment]
@josemiguel-alvarez would you like to submit an MR for this?

**Comment by josemiguel-alvarez** [comment]
> @josemiguel-alvarez would you like to submit an MR for this?

Sure! I'll open it today.

**Comment by jspizziri** [comment]
Looking at this a little more deeply it looks like the Kotlin service needs to be updated too.

**Comment by jspizziri** [comment]
@josemiguel-alvarez 

This will need to be updated in the [`MusicModule.kt`](https://github.com/doublesymmetry/react-native-track-player/blob/main/android/src/main/java/com/doublesymmetry/trackplayer/module/MusicModule.kt#L287) on lines `287` & `293`. Please [reference how iOS is behaving](https://github.com/doublesymmetry/react-native-track-player/blob/main/ios/RNTrackPlayer/RNTrackPlayer.swift#L354)

**Comment by jspizziri** [comment]
@josemiguel-alvarez I ended up taking this one on. I noticed [this issue in the process](https://github.com/doublesymmetry/react-native-track-player/issues/1522) which we'll address soon.

**Comment by josemiguel-alvarez** [comment]
> @josemiguel-alvarez I ended up taking this one on. I noticed [this issue in the process](https://github.com/doublesymmetry/react-native-track-player/issues/1522) which we'll address soon.
> 
> [Here's the PR](https://github.com/doublesymmetry/react-native-track-player/pull/1523)

Thank you Jacob, I haven't had time yet to work on this.
