### ISSUE TITLE
useProgress HLS bug on IOS

### ISSUE THREAD

**Issue by praisedavid787** [doublesymmetry/react-native-track-player#1521]
**Describe the Bug**
Duration returned from useProgress while playing HLS live stream is not correct. All is well on android as I have observed.

**Steps To Reproduce**
How can someone else reproduce this bug?
* Add an HLS track to Trackplayer and play.
* Monitor the useProgress output via console.

**Code To Reproduce**
Please provide a simple code example that allows others to replicate the bug.
```javascript
Trackplayer.add({
    ...track,
    type: "hls",
    isLiveStream: true,
    url: file.m3u8,
}).then(() => {
    Trackplayer.play();
});

const info = useProgress();
console.log(info); // normal if live stream is just starting, try joining at a much later time
Trackplayer.seekTo(secs); // triggers the issue
```
```bash
// ios
 LOG  {"buffered": 6700.753022675737, "duration": 17.972244897959182, "position": 6683.826420957}
 LOG  {"buffered": 6700.753022675737, "duration": 17.972244897959182, "position": 6683.826420957}
 LOG  {"buffered": 6700.753022675737, "duration": 17.972244897959182, "position": 6683.826420957}
 LOG  {"buffered": 6712.780959183673, "duration": 30.00018140589569, "position": 6674.442}
 LOG  {"buffered": 6712.780959183673, "duration": 30.00018140589569, "position": 6674.442}
 LOG  {"buffered": 6712.780959183673, "duration": 30.00018140589569, "position": 6674.442}
 LOG  {"buffered": 6712.780959183673, "duration": 30.00018140589569, "position": 6674.442}
 LOG  {"buffered": 6712.780959183673, "duration": 30.00018140589569, "position": 6674.442}
 LOG  {"buffered": 6671.623173922902, "duration": 0.8359183673469388, "position": 6670.85258876}
 LOG  {"buffered": 6671.623173922902, "duration": 0.8359183673469388, "position": 6670.85258876}
 LOG  {"buffered": 6688.782720408163, "duration": 17.99546485260771, "position": 6671.867501169}
 LOG  {"buffered": 6688.782720408163, "duration": 17.99546485260771, "position": 6671.867501169}
 LOG  {"buffered": 6694.773468707483, "duration": 23.986213151927437, "position": 6672.900312556}
 LOG  {"buffered": 6694.773468707483, "duration": 23.986213151927437, "position": 6672.900312556}
```
```bash
// android 
 LOG  {"buffered": 0, "duration": 0, "position": 0}
 LOG  {"buffered": 0, "duration": 0, "position": 0}
 LOG  {"buffered": 30.014, "duration": 42.004, "position": 24.004}
 LOG  {"buffered": 30.014, "duration": 42.004, "position": 24.004}
 LOG  {"buffered": 42.004, "duration": 42.004, "position": 24.004}
 LOG  {"buffered": 42.004, "duration": 42.004, "position": 24.004}
 LOG  {"buffered": 42.004, "duration": 42.004, "position": 24.004}
 LOG  {"buffered": 42.004, "duration": 42.004, "position": 24.004}
 LOG  {"buffered": 48.011, "duration": 48.011, "position": 26.436}
 LOG  {"buffered": 48.011, "duration": 48.011, "position": 26.436}
 LOG  {"buffered": 50.055, "duration": 54.008, "position": 29.905}
 LOG  {"buffered": 50.055, "duration": 54.008, "position": 29.905}
 LOG  {"buffered": 54.008, "duration": 54.008, "position": 33.554}
 LOG  {"buffered": 54.008, "duration": 54.008, "position": 33.554}
 LOG  {"buffered": 54.008, "duration": 54.008, "position": 33.677}
 LOG  {"buffered": 54.008, "duration": 54.008, "position": 33.677}
```
**Environment Info:**
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 28.16 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.2 => 0.66.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

react-native-track-player@2.1.3

**Comment by jspizziri** [comment]
Are you able to provide an HLS stream and playlist for us to test with?

**Comment by praisedavid787** [comment]
@jspizziri  Thanks for the quick reply, and yes I sure do

**Comment by jspizziri** [comment]
@praisedavid787 if its something that we could add to this public repo to test HLS streams that would be super helpful.

**Comment by praisedavid787** [comment]
@jspizziri I sent you an email about the constraints of adding this to the repo. Stream comes up on demand.
https://u-wayserver.herokuapp.com/streams/live/oLJK2eFvDTiOp0_wcfUBGPAa/index.m3u8

**Comment by praisedavid787** [comment]
@jspizziri 
https://pl.streamingvideoprovider.com/mp3-playlist/playlist.m3u8

This is one for a VOD stream that I have also tested with and gives desired behavior as it not a live stream.

**Comment by jspizziri** [comment]
@praisedavid787 Thanks for sending these. I'm currently taking some time but will try to look once back!

**Comment by praisedavid787** [comment]
@jspizziri Anytime man, thank for all the help. Hoping things look up soon. Huge blocker for me this one. It's fine at the start but once I ```seekTo()```, boom! Messed up.

**Comment by praisedavid787** [comment]
Trying to be a hero but not familiar though. Something looks fishy when comparing the last ```else if``` statement in ```var duration``` with ```var bufferedPosition```'s return.  **AvPlayerWrapper.swift in SwiftAudioEx**

```swift
    var duration: TimeInterval {
        if let seconds = currentItem?.asset.duration.seconds, !seconds.isNaN {
            return seconds
        }
        else if let seconds = currentItem?.duration.seconds, !seconds.isNaN {
            return seconds
        }
        else if let seconds = currentItem?.loadedTimeRanges.first?.timeRangeValue.duration.seconds,
                !seconds.isNaN {
            return seconds
        }
        return 0.0
    }
    
    var bufferedPosition: TimeInterval {
        currentItem?.loadedTimeRanges.last?.timeRangeValue.end.seconds ?? 0
    }
```

**Comment by jspizziri** [comment]
@praisedavid787 Thanks for taking the initiative! You can try putting in some print statements or breakpoints and you should be able to debug the lib via Xcode. I can provide pointers there if you like.

@dcvz  any pointers or insight off of the top of your head?

**Comment by praisedavid787** [comment]
@jspizziri Wow great, I wanna debug. Pls do provide pointers.

**Comment by praisedavid787** [comment]
@jspizziri Wow great, I wanna debug. Pls do provide pointers.

**Comment by jspizziri** [comment]
@praisedavid787 another thing I'm wondering is if this is an issue with your HLS playlist metadata (I'm not an expert on HLS). But I did find that you can add the playlist length as a metadata field.

https://stackoverflow.com/questions/38216051/hls-fragment-length-and-playlist-length-with-nginx-rtmp-module

**Comment by praisedavid787** [comment]
@jspizziri Eureka!!! After much research, implementation and testing, I have found what works:
```swift
     var duration: TimeInterval {
        if let seconds = currentItem?.asset.duration.seconds, !seconds.isNaN {
            return seconds
        }
        else if let seconds = currentItem?.duration.seconds, !seconds.isNaN {
            return seconds
        }
        else if let seconds = currentItem?.seekableTimeRanges.last?.timeRangeValue.duration.seconds,
                !seconds.isNaN {
            return seconds
        }
        return 0.0
    }
```

**Comment by jspizziri** [comment]
@praisedavid787 Nice work! The next step would be to open up a PR against the swiftaudioex repo with your changes. Then we'll get the feedback from the team there.

Kudos to you. For taking the initiative on looking into this!

**Comment by praisedavid787** [comment]
@jspizziri Thanks for all the help, much appreciated. 
For the PR, I'll have to fork the repo, is it?

**Comment by jspizziri** [comment]
Correct, you fork the main repo crest a branch off of main implement your change there, then push it up to your fork. Then you creat a PR from your repo to the main repo. Probably some better walkthroughs than that on the internet too haha

**Comment by praisedavid787** [comment]
Makes a whole lot of sense man, thanks. See you at SwiftAudioEx!

**Comment by jspizziri** [comment]
@praisedavid787 Let's leave this issue open, as if it gets merged and released in swiftaudio we'll need to inevitably update this project too by upgrading the dependency version.

**Comment by praisedavid787** [comment]
Ok sir, you're the boss man. Pull request up https://github.com/doublesymmetry/SwiftAudioEx/pull/18.

**Comment by dcvz** [comment]
Great work tracking this down @praisedavid787! and for the help @jspizziri :)

The PR has been merged and I'll make a SwiftAudioEx release later today!

**Comment by jspizziri** [comment]
@praisedavid787 

![nice work](https://i.giphy.com/SWzVtsCPEPggXQsGoT.gif)

**Comment by jspizziri** [comment]
@praisedavid787 warch for the version release on swiftaudioex. Once it's been made you'll need to submit another PR to this repository updating the version number here

https://github.com/doublesymmetry/react-native-track-player/blob/main/react-native-track-player.podspec

**Comment by praisedavid787** [comment]
Thank you @dcvz and @jspizziri for making things easy! Cheers to more collaboration for a better RNTP!

**Comment by jspizziri** [comment]
@praisedavid787 Here's the PR that solves the issue for this repo now that a new version is release for swiftaudioex.

https://github.com/doublesymmetry/react-native-track-player/pull/1534

**Comment by praisedavid787** [comment]
@jspizziri Ok great! Anything you'll have me do?

**Comment by jspizziri** [comment]
No you're good. Just an fyi

**Comment by jspizziri** [comment]
The fix has been merged and will be released in the next RC

**Comment by iivaan** [comment]
> https://pl.streamingvideoprovider.com/mp3-playlist/playlist.m3u8

how did you created this play list. Usually, HLS provide .ts file but you have .mp3 file
