### ISSUE TITLE
[Feature Request]  using .onion domains Tor net

### ISSUE THREAD

**Issue by davoodghaffarilive** [doublesymmetry/react-native-track-player#1524]
hi
i want load tracks from an .onion domain but its not load tracks from .onion domains
what should i do for this ?
could you please help me ?

**Comment by jspizziri** [comment]
@davoodghaffarilive This is certainly an interesting idea, but I'm not sure how practical it is. I think you'd effectively need to embed an onion router in the app itself (not well informed in that area).

My recommendation would be to use a separate package to download the file and then use this package to play the file locally.

I'm going to close this request as I don't realistically see it as something that will get attention from the core team.

Cc @dcvz feel free to disagree,

**Comment by davoodghaffarilive** [comment]
Thank you for your response
i installed react-native-tor
and its can connect to tor network, but if i want to download files in local and then play it, its take long time im searching for a solution, did you know any socks proxy connector package ?
 Thanks again

**Comment by jspizziri** [comment]
@davoodghaffarilive I'm not sure I follow your last question. Is a download slow because the network connection and the onion routing overhead?

If you need a proxy, my suggestion would be to see if the `react-native-tor` package can provide a proxy URL for you.

**Comment by jspizziri** [comment]
@davoodghaffarilive I'd recommend opening an issue in that repository to see if they can provide a proxy, as it's more relevant to their project than to ours. Sorry!
