### ISSUE TITLE
State enum does not contain a value for "buffering" state

### ISSUE THREAD

**Issue by kolking** [doublesymmetry/react-native-track-player#1535]
**Describe the Bug**
The `State` enum does not contain a corresponding value for the `buffering` state which returned by `usePlaybackState()` hook. There are `State.Buffering` which value is `"loading"` and `State.Connecting` which value is `undefined`.

**Steps To Reproduce**
Compare `State` enum value with the values returned by `usePlaybackState()` hook.

**Environment Info:**
```
System:
    OS: macOS 11.6.5
    CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
    Memory: 30.95 MB / 24.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_322 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
I'm using `react-native-track-player` stable version 2.1.3 in iOS simulator with iOS 15.2, testing the player with a live stream.

**How I can Help**
I assume that the `State.Buffering` should be `"buffering"` and `State.Connecting` should be `"loading"`.

**Comment by jspizziri** [comment]
Please take another look. Both of these states are in the enum

https://react-native-track-player.js.org/docs/api/constants/state

**Comment by kolking** [comment]
@jspizziri Yes, the states are present on the RN side, but are not correct in the `RNTrackPlayer.swift`. Also, please note I'm talking about the 2.1.3 stable version: https://github.com/doublesymmetry/react-native-track-player/blob/v2.1.3/ios/RNTrackPlayer/RNTrackPlayer.swift#L46-L51

The fix that works for me:
```diff
            "STATE_NONE": AVPlayerWrapperState.idle.rawValue,
            "STATE_READY": AVPlayerWrapperState.ready.rawValue,
            "STATE_PLAYING": AVPlayerWrapperState.playing.rawValue,
            "STATE_PAUSED": AVPlayerWrapperState.paused.rawValue,
            "STATE_STOPPED": AVPlayerWrapperState.idle.rawValue,
-           "STATE_BUFFERING": AVPlayerWrapperState.loading.rawValue,
+           "STATE_CONNECTING": AVPlayerWrapperState.loading.rawValue,
+           "STATE_BUFFERING": AVPlayerWrapperState.buffering.rawValue,
```

**Comment by jspizziri** [comment]
@kolking I checked and this has already been addressed in the most recent RC. It will not be backported to 2.1. Please upgrade to 2.2.0-rc3
