### ISSUE TITLE
[Feature Request] manage for many voice

### ISSUE THREAD

**Issue by fukemy** [doublesymmetry/react-native-track-player#1537]
Hi, first thanks for useful library

I have flatlist that render multi row as voicePlayerView, I want to pause this row and play other row, but i have only 1 useProgress() to display time, it's make all row display same progress, I dont know how to do next. 

Can u give me some advices? Thanks in advance

**Comment by jspizziri** [comment]
@fukemy I'm closing this as:

- This isn't a feature request but a support request. The library supports what is necessary for you to accomplish your goal.
- I answered your question directly on discord: https://discord.com/channels/567636850513018880/600714011318681610/974593627789615134
