### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by KrisLau** [doublesymmetry/react-native-track-player#1540]
**What is the need and use case of this feature?**
Is there a way to combine two tracks into one so that they overlap? I'm trying to create an walkout music app for baseball

**Describe the ideal solution**
Maybe a method like `addMultitrack()` which takes in an array of Track objects that also have additional params like `startTiming` which controls at which point the track should start playing, `volume` to control the relative volume of the track, and `clipStart` & `clipEnd` which would control trimming the track.

**Describe alternatives you've considered**
I've been searching around and I have not been able to find any other alternatives. All the other alternatives like:

- https://github.com/naomiaro/waveform-playlist
- https://github.com/goldfire/howler.js

seem to be made for the web. I also tried looking for APIs that would support it.

**Additional context**
Apps that do similar things to what I am trying to achieve:

- https://play.google.com/store/apps/details?id=com.bpdj.ballparkdj
- https://play.google.com/store/apps/details?id=com.upallnitesoftware.walkoutsongdj&hl=en_US&gl=US

**How I can Help**
Currently super busy with work but would be more than willing to sponsor to get a feature like this added. I would also be open to any suggestions of a way I can achieve this in either this library, any other library or with an API. Thanks in advance!

**Comment by jspizziri** [comment]
@KrisLau This seems nearly identical to this other feature request you made:

https://github.com/doublesymmetry/react-native-track-player/issues/1486

Effectively it sounds like you're looking for a cross fade. I'm going to close this one so that everything is tracked in one place.

**Comment by KrisLau** [comment]
> @KrisLau This seems nearly identical to this other feature request you made:
> 
> #1486
> 
> Effectively it sounds like you're looking for a cross fade. I'm going to close this one so that everything is tracked in one place.

Would that be similar? I was thinking this one would be more like a audio merge/combine with some way to control the trim of the audio

**Comment by KrisLau** [comment]
@jspizziri It's because the users would be uploading the audio so I wouldn't necessarily know what segments to trim. I might try and do it with ffmpeg though, thanks!

**Comment by KrisLau** [comment]
@jspizziri Ahhh ok that might work, thanks!

**Comment by KrisLau** [comment]
Just realized it probably work since i need two audio clips to play possibly at the same time. Just posting it here for future refence in case anyone is looking for the same thing. I'll probably just give ffmpeg a shot, thanks again for all the help!

**Comment by jspizziri** [comment]
@KrisLau to my knowledge iOS/Android don't have the ability to play multiple tracks simultaneously, so you're going to have to do some fancy audio file editing on the fly.

IMHO, you might consider doing this by creating a live HLS stream serverside with ffmpeg that adjusts itself based on the parameters that are being configured in the app. Effectively, I just recommend pushing the complexity of audio file modification server-side rather than trying to do it in the app.

**Comment by KrisLau** [comment]
@jspizziri I have no idea what a HLS stream is but I'll look into it and see if I'm able to implement it! I'll comment on here again once I figure it out if anyone needs to do something similar

**Comment by marksyzm** [comment]
Thanks to the above, as I'm looking for something that will layer the audio tracks (like in a DAW).

**Comment by marksyzm** [comment]
I use a Date as a start value when someone hits record or play and compare microseconds from that point. It keeps it as accurate as possible, to the microsecond and I'm finding it reliable so far.
