### ISSUE TITLE
Android media player shows 'Unknown' for title and artist on lock screen, but not when 

### ISSUE THREAD

**Issue by sjorsroelofs** [doublesymmetry/react-native-track-player#1544]
**Describe the Bug**
When I add a track to the TrackPlayer and play it, the information provided for the track is shown correctly by the Android media controls. However, when I lock the device, the media controls show 'Unknown' for the title and artist. Is this a known bug or am I missing something?

**Code To Reproduce**
```
const track = {
    url: livestreamUrl,
    title: 'My livestream title',
    artist: 'Hello world!',
    artwork: require('./../../assets/images/artwork.png'),
    type: TrackType.HLS
};

await TrackPlayer.add([track]);
```

**Comment by jspizziri** [comment]
What version are you using?

**Comment by jspizziri** [comment]
@austinried is this a related to the issue that you fixed?

**Comment by sjorsroelofs** [comment]
@jspizziri okay, that seems like the same problem. Any clue on when this will be fixed? :)

**Comment by jspizziri** [comment]
The core issue has been fixed it just needs to be released, I'm not sure when that will happen but hopefully soon,

**Comment by JavoxirNazarov** [comment]
same issue. @sjorsroelofs any solutions?

**Comment by sjorsroelofs** [comment]
> same issue. @sjorsroelofs any solutions?

Nope, i’m waiting for the update. Let me know if you find a quick fix in the meantime :)
