### ISSUE TITLE
Heart/Favorite/Rating in android notification bar is not implemented

### ISSUE THREAD

**Issue by titarenko-alexander** [doublesymmetry/react-native-track-player#1547]
**Describe the Bug**
Cannot set rating/add to favorite track from notification bar. Not much information in documentation.

**Code To Reproduce**
`await TrackPlayer.updateOptions({ capabilities: [Capability.Pause, Capability.Skip, Capability.SkipToNext, Capability.SkipToPrevious, Capability.PlayFromId, Capability.Stop, Capability.JumpForward], stopWithApp: true, ratingType: RatingType.Heart });`
Result: 
![image](https://user-images.githubusercontent.com/75521417/169664444-d4461b28-5738-4277-84dc-3d2c0c8ea101.png)

**Environment Info:**
Android 

According to this issue: https://github.com/doublesymmetry/react-native-track-player/issues/67
This feature was not implemented since then. I cannot see anything about rating in notification in MusicService.kt file:
`notificationCapabilities.forEach {
                when (it) {
                    Capability.PLAY -> {
                        val playIcon = Utils.getIconOrNull(this, options, "playIcon")
                        buttonsList.add(PLAY(icon = playIcon))
                    }
                    Capability.PAUSE -> {
                        val pauseIcon = Utils.getIconOrNull(this, options, "pauseIcon")
                        buttonsList.add(PAUSE(icon = pauseIcon))
                    }
                    Capability.STOP -> {
                        val stopIcon = Utils.getIconOrNull(this, options, "stopIcon")
                        buttonsList.add(STOP(icon = stopIcon, isCompact = isCompact(it)))
                    }
                    Capability.SKIP_TO_NEXT -> {
                        val nextIcon = Utils.getIconOrNull(this, options, "nextIcon")
                        buttonsList.add(NEXT(icon = nextIcon, isCompact = isCompact(it)))
                    }
                    Capability.SKIP_TO_PREVIOUS -> {
                        val previousIcon = Utils.getIconOrNull(this, options, "previousIcon")
                        buttonsList.add(PREVIOUS(icon = previousIcon, isCompact = isCompact(it)))
                    }
                    Capability.JUMP_FORWARD -> {
                        val forwardIcon = Utils.getIcon(
                                this,
                                options,
                                "forwardIcon",
                                R.drawable.forward
                        )
                        buttonsList.add(FORWARD(icon = forwardIcon, isCompact = isCompact(it)))
                    }
                    Capability.JUMP_BACKWARD -> {
                        val backwardIcon = Utils.getIcon(
                                this,
                                options,
                                "rewindIcon",
                                R.drawable.rewind
                        )
                        buttonsList.add(BACKWARD(icon = backwardIcon, isCompact = isCompact(it)))
                    }
                    else -> return@forEach
                }
            }`

**Comment by titarenko-alexander** [comment]
This is what I expect
![image](https://user-images.githubusercontent.com/75521417/169664983-a694fed8-b157-4445-adef-f47c1ba2edf9.png)

**Comment by titarenko-alexander** [comment]
@jspizziri sorrty, wrong example.
Code: 
` await TrackPlayer.updateOptions({ capabilities: [Capability.Pause, Capability.Skip, Capability.SkipToNext, Capability.SkipToPrevious, Capability.SetRating, Capability.Stop], stopWithApp: true, ratingType: RatingType.Heart, icon: require("../../../assets/images/tray.png") });`
Result:
![image](https://user-images.githubusercontent.com/75521417/170318014-06d32b4b-6677-4004-920b-0d4e9395f1ea.png)

**Comment by titarenko-alexander** [comment]
If this possibility really working, then can you give example screenshot?

**Comment by jspizziri** [comment]
@titarenko-alexander I'm not sure what you're asking. You said that the player should wasn't showing the "heart" icon. I identified the reason as being a misconfiguration in the app. You just sent me a screenshot of the player displaying the appropriate controls after you fixed your config. What is your current issue?

**Comment by jspizziri** [comment]
@titarenko-alexander I don't mean to be short, but my time is limited. If you want good help you need to be more helpful. It seems like you're just dumping an issue in the repo and expecting that all your problems will vanish, which is a bit frustrating for me.

So, let's try it this way:

1. What version of RNTP are you using?
2. What _specific_ actions are you taking, and what is the result?
3. What do you _expect_ the result will be in _technical_ terms?
4. Can you provide _cleanly_ formatted code (ideally in a public repo) of how you have things set up currently?

**Comment by titarenko-alexander** [comment]
@jspizziri 
I using last version: 2.2.0-rc3
My question is simple, should Capability.SetRating (with ratingType: RatingType.Heart) add a button to notifications to add a track to favorites? Because that's what I expect by specifying this Capability
