### ISSUE TITLE
Event.RemoteSeek not work on android

### ISSUE THREAD

**Issue by davoodghaffarilive** [doublesymmetry/react-native-track-player#1548]
**Describe the Bug**
hi
i create a service for Track player listeners

```
import TrackPlayer, { Event } from "react-native-track-player";

module.exports = function () {
    TrackPlayer.addEventListener(Event.RemoteSeek, ({position}) => {
      TrackPlayer.seekTo(position);
    });
    TrackPlayer.addEventListener('remote-play', () => TrackPlayer.play());
    TrackPlayer.addEventListener('remote-pause', () => TrackPlayer.pause());
    TrackPlayer.addEventListener('remote-next', () => TrackPlayer.skipToNext());
    TrackPlayer.addEventListener('remote-previous', () => TrackPlayer.skipToPrevious());
  };
```

and its my Capabilitys : 

```
const setupPlayer = async() => {
  await TrackPlayer.setupPlayer();
  await TrackPlayer.updateOptions({
    stopWithApp: true,
    capabilities: [
        Capability.Play,
        Capability.Pause,
        Capability.SkipToNext,
        Capability.SkipToPrevious,
        Capability.SeekTo,
      ],
        compactCapabilities: [
            Capability.Play,
            Capability.Pause,
            Capability.SkipToNext,
            Capability.SkipToPrevious,
        ],
});
}
```

**Environment Info:**
System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.45 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.9.0 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 30
      System Images: android-30 | Google Play ARM 64 v8a, android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Users/user/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

on IOS Seek bar works fine but on android its not working

i use real android device Android Version : 11

**Comment by jspizziri** [comment]
What version are you on?

**Comment by jspizziri** [comment]
@davoodghaffarilive I've confirmed this behavior in `main`. Question for you: when I tested it I wasn't seeing the `RemoteSeek` event being fired, however I _WAS_ seeing the player successfully scrub to that location. Can you confirm?

**Comment by jspizziri** [comment]
@davoodghaffarilive I've implemented the fixes here now we'll need to wait for merge and release of KotlinAudio.
