### ISSUE TITLE
App freezes for sometime when reopen from background to foreground

### ISSUE THREAD

**Issue by haidernayyar** [doublesymmetry/react-native-track-player#1549]
**Describe the Bug**
When music is playing in the background and reopens the app from background to foreground, the app freezes for some time. All the touchables are unresponsive. Then after sometimes all the pending action work one after another like play, pause. 

**Steps To Reproduce**
- Open the app, play any music.
- Send app to the background 
- Reopen app after some time

**Environment Info:**
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 4.32 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v15.14.0/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
    Watchman: 2021.11.15.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.0 => 0.68.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
react-native-track-player:  ^2.1.3
device: Real device ( iPhone 7 )

**Comment by jspizziri** [comment]
What does "some time" mean? Can you give a range? I've never seen this before

**Comment by s123121** [comment]
I don't think this is an issue of the library. Rather, it is a mechanism of react-native. When the app go to background, all the ui rerender (or javascript execution) is delay and then flushed all at once when the app go back to foreground. I don't know what it called, but you should check if there are any heavy javascript task when your app go to background

**Comment by haidernayyar** [comment]
> 

It takes less delay ( few sec ) if I reopen quickly and takes long like 3-4 mins otherwise

**Comment by vanhungoz** [comment]
i was facing the same issue. 
react-native version: 0.68.2 / 0.69-rc6
react-native-track-player: 2.2.0-rc3

produce the issue: 
 - create a queue
 - play track
 - app to background for a while
 - reopen app, all the touchables are unresponsive, can only scroll (track is still play correctly)

**Comment by vanhungoz** [comment]
i tested in simulator ios 15.5

**Comment by vanhungoz** [comment]
@jspizziri  could you reopen it?

**Comment by vanhungoz** [comment]
i tesed in iPhone XS max, ios 15.5 and it also get same error

**Comment by haidernayyar** [comment]
> i tested in iPhone XS max, ios 15.5 and it also get same error

Can you check if you are using setInterval in your code? I fixed my issue by removing the setInterval.

**Comment by vanhungoz** [comment]
unfortunately, i don't use setInterval in my code :(

**Comment by jspizziri** [comment]
@haidernayyar @vanhungoz ,

I've attempted to reproduce this. I followed @vanhungoz 's steps to reproduce. I played the audio in the background for 5min, then reopened my app. Everything was just as responsive as it normally was and I saw no issues. This must be an issue with your implementation.

I'm going to close this again. However, if you can create a reproducible example by forking this repo and updating the `example` project such that it reproduces, then I'll reopen the issue. But as of now, this is non-reproducible and I'm closing it as such.

Thanks!

**Comment by jspizziri** [comment]
Oh... just realized you mentioned testing in the simulator. Background playback mode doesn't work in an iOS simulator. https://react-native-track-player.js.org/docs/next/basics/background-mode#ios-simulator
