### ISSUE TITLE
unable to install main branch via npm

### ISSUE THREAD

**Issue by fatlinesofcode** [doublesymmetry/react-native-track-player#1550]
we're trying to use the latest updates from main

we get this error from **prepareGitDep** when we run 
` npm install https://github.com/react-native-kit/react-native-track-player.git#main --save`

```
npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep > react-native-track-player@2.2.0-rc3 prepare /Users/phil/.npm/_cacache/tmp/git-clone-694eb781
npm ERR! prepareGitDep > yarn build
npm ERR! prepareGitDep 
npm ERR! prepareGitDep yarn run v1.22.17
npm ERR! prepareGitDep $ rimraf lib && tsc
npm ERR! prepareGitDep node_modules/@types/react-native/index.d.ts(365,17): error TS2694: Namespace 'React' has no exported member 'ReactType'.
npm ERR! prepareGitDep info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--also=dev` instead.
npm ERR! prepareGitDep error Command failed with exit code 2.
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 2
npm ERR! prepareGitDep npm ERR! react-native-track-player@2.2.0-rc3 prepare: `yarn build`
npm ERR! prepareGitDep npm ERR! Exit status 2
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the react-native-track-player@2.2.0-rc3 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /Users/phil/.npm/_logs/2022-05-24T12_15_11_853Z-debug.log
npm ERR! prepareGitDep 
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
```

**Comment by jspizziri** [comment]
So, I know we mention being able to install `#dev` (or `#main`) in the docs but we should probably remove it.

The git repo doesn't contain the built version of the library and that's only shipped to NPM currently. The best you can do for now is install `2.2.0-rc3`. It's behind `main`, but more updated than `2.1.3`.

**Comment by fatlinesofcode** [comment]
@jspizziri are we able to get an rc4 build that a bit more updated published to npm?

**Comment by jspizziri** [comment]
@fatlinesofcode I'm working with the DoubleSymmetry team to try and make that happen. Is there something specific you need?

**Comment by fatlinesofcode** [comment]
@jspizziri thanks for that, we are seeing a few issues with scrubbing and buffering on android, we're trying to diagnose if its new if a new issue or something that has already been fixed in `main` or if we need to adjust our app.

our qa team used builds from our ci which is why we need an npm source.

**Comment by jspizziri** [comment]
@fatlinesofcode Gotcha. You could always try to validate in the example app which installs main. I hope to get a new release out soon.
