### ISSUE TITLE
Event.PlaybackState state inconsistent between platforms

### ISSUE THREAD

**Issue by daanvanberkel** [doublesymmetry/react-native-track-player#1559]
**Describe the Bug**
When using the `Event.PlaybackState` event, the state in this event is inconsistent between iOS and Android. On iOS the state contains a string (example: `playing`) on Android the state contains an integer corresponding with the `State` enum.

**Steps To Reproduce**
Attach an event listener to the `Event.PlaybackState` event. And queue/play a track using the track player.

**Code To Reproduce**
```typescript
TrackPlayer.addEventListener(Event.PlaybackState, event => {
   console.log(event.state);
});
```

**Environment Info:**
react-native-track-player@2.1.3
On a real device with iOS 15.4.1 and Android 9

**Comment by jspizziri** [comment]
@daanvanberkel This is why you should be using the `State` enum exported by the library when checking things rather than using strings. That enum is mapped to the corresponding native values.
