### ISSUE TITLE
[Docs] Separate event listeners from components

### ISSUE THREAD

**Issue by pabloromeu** [doublesymmetry/react-native-track-player#1561]
**What is the need and use case of this feature?**
In version 2.0 it is recommended to use React Native Hooks which are tied to a UI Component to listen to events -e.g.: `usePlaybackState`, `useTrackPlayerEvents`, `useProgress` -. See docs here: https://react-native-track-player.js.org/docs/v2-migration

This is not ideal, as it forces the event listener code to be tied to a component. This component, that should only be responsible of drawing and react to screen events, is taking care of something that might not be related to that component.  For example, remote events which have nothing to do with a react component -they are generated outside the app- are dispatched to a hook in the app component. This breaks the single responsibility principle and makes the component more difficult to test and maintain. 

Even more, the current documentation advises to use addEventListener here: https://react-native-track-player.js.org/docs/basics/playback-service , and then discourages to do it here: https://react-native-track-player.js.org/docs/v2-migration

**Describe the ideal solution**
The previous solution with eventListeners was a good one. The library can even provide the hooks to listen for events in a component as it does now, or let the user listen them in an eventListener, but not forcing the user to listen for events in a component.

Hence, in my opinion, using eventListeners solution is the best approach as it will:
- Let the user decouple the events listeners from UI Components.
- Let the user use hooks, if needed. But not being forced to.

**How I can Help**

I can work on it and create a PR, but I think everything you need is already there. As hooks are just a wrapper over the real addEventListener. So I assume that it is just a matter of updating the documentation explaining that hooks are just that, a wrapper over addEventListener and that the user may use addEventListener if needed.

**Comment by jspizziri** [comment]
I haven't looked at the docs in this capacity but I can speak to how thing should be implemented.

Inside any react UI components, hooks should be used. Apart from that the playback service should employ listeners (this is where all headless events and logic should live).

If this doesn't track in the docs I'd happily review a PR rectifying it.

**Comment by jspizziri** [comment]
@pabloromeu I'm going to close this as it seems that this is more of a misunderstanding. I do think it could be clarified in the docs  a bit and if you want to submit a PR I'll happily review it.
