### ISSUE TITLE
How to use MusicService by android native code , Android Widget

### ISSUE THREAD

**Issue by mustafakameldev** [doublesymmetry/react-native-track-player#1562]
I'm trying to add android widget for my app, this widget should connect with track player service 
to play, pause, skip to next, skip to previous song.

here is the onReceive method of the widget 
```
   @Override
    public void onReceive(Context context, Intent intent) {
        if (intent != null) {
            if(intent.getAction().equals(previous)){
                //Here how to invoke remove skip to previous song
            }
            else if (intent.getAction().equals(play)) {
                //Here how to toggle between play or stop song 
            }
            else if (intent.getAction().equals(next)) {
                //Here how to skip to next song
            }

            else {
                super.onReceive(context, intent);
            }
        }
        }
```
please help on this issue or till me if there is any way to use a music player widget with my app

**Comment by jspizziri** [comment]
I don't know much about Android, but I do know that the library ships with a standard Android player widget/notification. I'm not sure if that's what you're after. You should take a look at the `2.2.0-rc3` release.

**Comment by mustafakameldev** [comment]
Yes, thanks that exactly what i want, but could you please till how to implement this widgets or share any documentation for it

**Comment by jspizziri** [comment]
@mustafakameldev This works out of the box without you needing to do anything. All you need to do is implement a playback service as instructed by our docs.

**Comment by mustafakameldev** [comment]
Thanks.

**Comment by mustafakameldev** [comment]
Hi @jspizziri , I reviewed code but nothing about widgets (Home screen widgets) something like that : https://9to5google.com/wp-content/uploads/sites/4/2021/06/Screenshot_20210625-101649.png 
I that have any implementation ?

**Comment by lovegaoshi** [comment]
welp. 2 years late but for anyone interested, [the key is bind to musicService via peekService](https://github.com/lovegaoshi/react-native-track-player/pull/34/files#diff-47348bd650a7a954a669b4c9e2ef4816565810392e185733c3b6e5aaa9fee625R28).

FYI https://github.com/lovegaoshi/react-native-track-player/pull/34

**Comment by lovegaoshi** [comment]
seems there is another [rather convoluted way](https://github.com/maotoumao/MusicFree/compare/dev...feature/widget) of implement widgets, but no need to bind to MusicService. it relies on the context created is a reactContext to emit events.
