### ISSUE TITLE
Events from previous page are still running

### ISSUE THREAD

**Issue by vishangj123** [doublesymmetry/react-native-track-player#1565]
What i am trying to do ?
I have setup two track players, in one page I want the duration of audio to be 10 seconds so I wrote this piece of code

when this page loads by default value of stopMusic.current is set to true 
const stopMusic = useRef(true)

useEffect(() => {
        if (stopMusic.current == true) {
            progress.duration = 10;
            logOnConsole('dur', progress.duration)
        }
        logOnConsole('Progress.duration', progress.duration)
        // progress.duration

        if (progress.position >= progress.duration) {
            TrackPlayer.stop();
            progress.position = 0;
            setPlaying(false)
        }

    }, [progress.position])

The above code runs fine in the first page but when I navigate to next page I set stopMusic.current to false and then navigate . Somehow this piece of code still runs on the next page.

Update when running code in next page , the value of stopMusic is being printed once false and true like
stopMusic.current is false
stopMusic.current is true

**Comment by jspizziri** [comment]
@vishangj123 this isn't a bug but a question about how to use the library. Please ask the community on Discord.

Thanks!
