### ISSUE TITLE
Implementation of expo task manager for expo managed projects

### ISSUE THREAD

**Issue by h110m** [doublesymmetry/react-native-track-player#1572]
**What is the need and use case of this feature?**
Im always frustrated when my expo project doesn't work with this library 😅

**Describe the ideal solution**
As far as i know you can actually use this package in an expo managed project so you don't need to use a bare one. I successfully installed and build this package into my eas dev app for my expo managed project. It seems like the only thing that isn't working is the headless task registration which i think can be fixed by using expos TaskManager package (https://docs.expo.dev/versions/latest/sdk/task-manager/)

**How I can Help**
I would be more then open to at least try to create a PR that fixes the problem i described even though i am not the best in working with react native 😅

Btw i am using the current stable `2.1.3` and not `2.2.0-rc3`

**Comment by jspizziri** [comment]
@h110m we don't currently have any code contributors that work in expo. It would be great if you wanted to take a crack at identifying some of the underlying expo issues you're seeing. I'm happy to provide as much guidance as I'm able. Take a look at the docs here to see how to get started working on the native side of things:

https://github.com/doublesymmetry/react-native-track-player/tree/main/example

**Comment by h110m** [comment]
@jspizziri Thanks a lot i will definetly take a look at it and at least give it a try and btw thanks a lot for making this lib ^-^

**Comment by jspizziri** [comment]
@h110m I appreciate the thanks, but I didn't create the lib. I just work on it.

**Comment by jspizziri** [comment]
I'm going to close this until an interested party opens a PR.
