### ISSUE TITLE
Expo eas build crashes after updating to 2.2.0-rc3

### ISSUE THREAD

**Issue by h110m** [doublesymmetry/react-native-track-player#1573]
**Describe the Bug**
Looks like expo or more specifically gradle doesn't like something about the changes.

**Steps To Reproduce**
1. `expo init` - select typescript + expo managed project
2. `yarn add react-native-track-player@2.2.0-rc3`
3. Implement it like in the example
4. Follow the steps on the guid to setup a eas dev app
5. Build the app on the expo server
6. The build will crash at the gradle task

**Environment Info:**

Paste the results of `npx react-native info`
```
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (10) x64 Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
    Memory: 53.40 GB / 58.87 GB
    Shell: Unknown - /bin/sh
  Binaries:
    Node: 16.11.0 - ~/.nvm/versions/node/v16.11.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.11.0/bin/yarn
    npm: 8.0.0 - ~/.nvm/versions/node/v16.11.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Paste the exact `react-native-track-player` version you are using
`2.2.0-rc3`

Real device? Or simulator?
Neither one since i couldn't build the app

What OS are you running?
Ubuntu 20.04

**How I can Help**
I don't really know how i could help since i also never touched gradle at all
But i would be open to maby learn about it and contribute to this package

**Comment by jspizziri** [comment]
There's a duplicate issue that is referenced here that seems to indicate that this is fixed in RC4. In any case, we really need someone in the community who works with Expo to look into issues like this. I'm closing for now.
