### ISSUE TITLE
add a way to play an audio in Alarm category , for volume control

### ISSUE THREAD

**Issue by meypod** [doublesymmetry/react-native-track-player#1579]
**What is the need and use case of this feature?**
Currently I'm using this library to play my alarms. but It's volume is controlled by system's volume. so I needed to move this into the alarm volume category at least to let user decide the volume of the alarm using system settings.

**Describe the ideal solution**
an option to add some [AudioAttributes](https://developer.android.com/reference/android/media/AudioAttributes) to make it play as alarm ?

**Comment by jspizziri** [comment]
@meypod thanks for your request. I'm moving it to our feature request backlog. We'll review it and consider it for implementation once we have the bandwidth.

Thanks!
