### ISSUE TITLE
Incompatibility exoplayer versions between expo-av in sdk 45 and react-native-track-player

### ISSUE THREAD

**Issue by red-made** [doublesymmetry/react-native-track-player#1584]
Hi, I use track-player with expo, all works fine in sdk 44, now I need to upgrade and I've receive the following error: 
```
java.lang.NoSuchMethodError: No virtual method setAudioAttributes(Lcom/google/android/exoplayer2/audio/AudioAttributes;)V in class Lcom/google/android/exoplayer2/SimpleExoPlayer; or its super classes (declaration of 'com.google.android.exoplayer2.SimpleExoPlayer' 
```

I've tried also to upgrade track-player to rc-4, but when I build my app I receive the error: duplicate class, related always to exoplayer.
Someone may help me to fix that?

**Comment by jspizziri** [comment]
Closing as a duplicate

https://github.com/doublesymmetry/react-native-track-player/issues/1418
