### ISSUE TITLE
2.1.3 crashes on SDK 31 update

### ISSUE THREAD

**Issue by RamProg** [doublesymmetry/react-native-track-player#1606]
**Describe the Bug**
2.1.3 fails on update to SDK 31 (Android 12).

**Steps To Reproduce**
Update app to SDK 31 and get an error.

**Code To Reproduce**

/android/build.gradle

```
compileSdkVersion = 31
targetSdkVersion = 31
```

**Environment Info:**

> OS: macOS 12.4
>     CPU: (8) x64 Apple M1
>     Memory: 40.21 MB / 8.00 GB
>     Shell: 5.8.1 - /bin/zsh
>   Binaries:
>     Node: 14.15.0 - /usr/local/bin/node
>     Yarn: 1.22.19 - /usr/local/bin/yarn
>     npm: 8.11.0 - /usr/local/bin/npm
>     Watchman: 2022.05.16.00 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.11.3 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
>     Android SDK: Not Found
>   IDEs:
>     Android Studio: 2021.2 AI-212.5712.43.2112.8512546
>     Xcode: 13.4/13F17a - /usr/bin/xcodebuild
>   Languages:
>     Java: 11.0.15 - /usr/bin/javac
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 17.0.2 => 17.0.2 
>     react-native: 0.67.4 => 0.67.4 
>     react-native-macos: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found

react-native-track-player 2.1.2
Real Device Android Galaxy S20+
Android 12

**How I can Help**
I want to create patch/PR for v2.1.2 and 2.1.3 to work on SDK 31 until 2.2.0 is a final release to use in production.

Is there any reason why 2.1.3 can't work on SDK 31 with minimal changes?

**Comment by jspizziri** [comment]
https://github.com/doublesymmetry/react-native-track-player/issues/1193#issuecomment-1098140118
