### ISSUE TITLE
Issue with `PlaybackTrackChanged` event on Android with single track queue in `RepeatMode.Queue`

### ISSUE THREAD

**Issue by jspizziri** [doublesymmetry/react-native-track-player#1612]
This issue represents the uncompleted work from https://github.com/doublesymmetry/react-native-track-player/pull/1501#issuecomment-1110096083. A decision was made to merge what we had as it solved a large number of issues and deal with the rest on a dedicated issue.

> Remaining Issue:
> 
> In a single-track queue with RepeatMode.Queue Android on "Skip" no track-changed is fired.
> 
> Should be fired with nextTrack, position, and track (according to iOS).
> Natural track end works correctly.

**Comment by puckey** [comment]
@jspizziri is this still relevant?

**Comment by jspizziri** [comment]
I'll have to retest it. I haven't tested in nightly

**Comment by smn-snkl** [comment]
I can confirm that this happened with nightly yesterday. Would have to double check if it's only with RepeatMode.Queue though
