### ISSUE TITLE
Calling TrackPlayer.Destroy() disables Android Hardware Back Button

### ISSUE THREAD

**Issue by mayank-paryani** [doublesymmetry/react-native-track-player#1626]
**Describe the Bug**
When I call TrackPlayer.Destroy() in ComponentWillUnmount() it disables the Backbutton of Android app.

**Steps To Reproduce**

Once you have the example app set up, put Trackplayer.Destroy() in ComponentWillUnmount() or cleanup function.
Press back to exit the screen (having track player component) and now observe back button functionality is disabled for other screens.

[Environment Info:](url)
This happens on Android actual devices. We are currently testing on RNTP 2.2.0-rc3, but the problem also occurs in 2.2.0-rc4.

Kindly help if anyone has any solution to this problem.

**Comment by ktaeyang** [comment]
same issue.

**Comment by jspizziri** [comment]
I believe this has been fixed, can you please install the latest nightly build and see if it's still happening?

**Comment by jspizziri** [comment]
Closing as this should be fixed and I've gotten no response.
