### ISSUE TITLE
[RFC] Planned (mostly breaking) changes for major version 4.0

### ISSUE THREAD

**Issue by mpivchev** [doublesymmetry/react-native-track-player#1637]
This includes proposals for both this library and the Android audio library we use under the hood: [KotlinAudio](https://github.com/doublesymmetry/KotlinAudio).

This list will be updated over time so nothing is concrete.

**Top priority:**
- Remove the ExoPlayer fork and adjust the events API accordingly.
**Note:** Having a fork of such a big library is a recipe for disaster moving forward. We are planning to remove our fork and modifications and rely solely on the original library.

- Add support for bluetooth and physical button playback controls.

- Rename `QueuedAudioPlayer` to `PlaylistAudioPlayer`. Stop using the term of `queue` and replace it with `playlist` in documentation and function/class names.
**Note:** The term `playlist` is used and understandable by every person. It relates better to an audio player.
**Note 2:** iOS side must also be updated for this.

-----------

- Rename `reset` to `resetPlaylist` to more accurately describe what the function does. Rename `TrackPlayer.stop` to `TrackPlayer.resetPlaylist` as well.
**Note:** More descriptive.

- Rename the `position` property in `BaseAudioPlayer` to `currentPosition`
**Note:** More descriptive.

- `LocalBroadcastManager` in `MusicService` has been deprecated. Replace it with another observable pattern.

- Have the audio players automatically handle loss of audio focus - there's a PR for Android already https://github.com/doublesymmetry/KotlinAudio/pull/12 - 
**Note:** iOS would have to be updated too

- https://github.com/doublesymmetry/react-native-track-player/issues/1708

**Comment by jspizziri** [comment]
I think this one should be considered too

https://github.com/doublesymmetry/react-native-track-player/issues/1293

**Comment by jspizziri** [comment]
Remove the ExoPlayer fork and adjust the events api accordingly.

**Comment by jspizziri** [comment]
@puckey I think your work on Queue's should fall into this category.

**Comment by jspizziri** [comment]
We should move `stoppingAppPausesPlayback` and `compactCapabilities` into the new `android` object on the `MetadataOptions` object (they're android specific config options).

**Comment by jspizziri** [comment]
Split out into discrete issues.
