### ISSUE TITLE
[Feature Request] Pause track at specific position

### ISSUE THREAD

**Issue by CodeOne91** [doublesymmetry/react-native-track-player#1638]
In my project is required to pause audio at specific time position.
So, I tried to force pause through _useTrackPlayerEvents_. Something like this:
```
...
  useTrackPlayerEvents([Event.PlaybackProgressUpdated], async event => {
    if (event.position >= pauseValue) {
      TrackPlayer.pause();
    }
  });

...
```
However, it becomes difficult to check the timing and set pause because the event arrive a few seconds late (i.e event.position 3.5, but pauseValue = 2.5, so TrackPlayer.pause() is called when event position is at 3.5, not at 2.5). 

In this way what I listen to exceeds the threshold value I have set.

Is there a correct solution for this type of problem?

It could be useful provide a func to pause at specific time.

**Comment by jspizziri** [comment]
Another option is to simply set a timer to do the pause, or use the progress updated event. Both of them will have downsides though.

Regarding your feature, my instinct is that it's too niche to formally support in the API so you might need to maintain your own fork if you need it.

@dcvz lmk if you disagree.
