### ISSUE TITLE
Android app crash when calling TrackPlayer.setupPlayer(....);

### ISSUE THREAD

**Issue by suupham2506** [doublesymmetry/react-native-track-player#1641]
**Describe the Bug**
java.lang.NoSuchMethodError: No virtual method setAudioAttributes(Lcom/google/android/exoplayer2/audio/AudioAttributes;)V in class Lcom/google/android/exoplayer2/SimpleExoPlayer; or its super classes (declaration of 'com.google.android.exoplayer2.SimpleExoPlayer' appears in /data/app/~~U1v4qv49pqOzDmAm96RPZg==/com.meetyourgenie-bvivpm4N4Nvti6dmL7pIWw==/base.apk!classes22.dex)

**Steps To Reproduce**
How can someone else reproduce this bug?

**Code To Reproduce**
Please provide a simple code example that allows others to replicate the bug.

**Environment Info:**
Paste the results of `npx react-native info`: 0.68
Paste the exact `react-native-track-player` version you are using latest one
Real device? Or simulator?
What OS are you running?

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

**Comment by jspizziri** [comment]
This looks like an issue with a conflicting version install of exoplayer with another package. If you're on a sub 2.2 version I believe you can configure this.

Apart from that you'll need to specify the version of RNTP and reproduce in the example to help us evaluate the problem.
