### ISSUE TITLE
Docs need update?

### ISSUE THREAD

**Issue by Knufle** [doublesymmetry/react-native-track-player#1642]
So, I'm facing hls issues on android which I'll be addressing in another issue if I can't solve them, but while reading the docs and some issues I found this:

https://react-native-track-player.js.org/docs/basics/build-preferences#hls-android

![image](https://user-images.githubusercontent.com/25941471/184125747-2235918d-ec6e-4ffa-849a-af26119a7656.png)

I believe the description for hls has been mistakenly copied from smoothstreaming, or am I missing something?

**Comment by jspizziri** [comment]
@Knufle thanks for reporting this issue! Just submitted a PR for the fix.
