### ISSUE TITLE
[Feature Request] Loading audio over HTTP Partial Content

### ISSUE THREAD

**Issue by PaulCombal** [doublesymmetry/react-native-track-player#1650]
**What is the need and use case of this feature?**
I want to serve my content over HTTP 206 partial content. Because the audio content I want to stream can be fairly long (audio books, hour long music sets..), it is impractical to serve the content over HTTP 200 since it means the client needs to download a whole file before playing.

**Describe the ideal solution**
Having support for partial content, passing the media URL in the `url` field. A range-size option would be top-notch, being the maximum size of the byte range being fetched every request.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**How I can Help**
This is my test server for streaming content: https://youtubue-server.fly.dev/test

You can use it to try out a few things but please use your own.

**Comment by PaulCombal** [comment]
Thought: VLC seems has support for this in android, maybe an implementation using vlclib would be a great addition? How about a factory pattern to choose between VLC/Exoplayer/something else?

**Comment by jspizziri** [comment]
In theory you could do that. However, implementing another android player would be a substantial amount of work, and it's not something I'd think the core team would be interested in supporting long term. You'd be better off figuring how to accomplish this with exoplayer.

**Comment by jspizziri** [comment]
I'm going to move this to the feature backlog. If you have the ability to move this forward with a concrete implementation plan for ExoPlayer and AVPlayer we can look at it more closely.
