### ISSUE TITLE
[Feature Request] RNTP with expo-av support

### ISSUE THREAD

**Issue by russriser** [doublesymmetry/react-native-track-player#1652]
**What is the need and use case of this feature?**

My company's app needs RNTP and expo-av to be compatible with one another. We use expo-av for playing small audio clips on button-presses. We need this to happen separate from any long-form audio content that's already playing. So...we need multiple audio instances running at the same time. 

The RNTP Queue format would be burdensome for playing the short audio clips. But the RNTP Queue format also makes managing our long-form audio very easy. So ideally, we have RNTP to manage our long-form and expo-av to manage our short clips.

However, after setting up both systems, it doesn't appear possible for RNTP's lockscreen controls to work (they don't appear at all) when expo-av is enabled with background mode. If you keep expo-av background mode disabled, the RNTP lockscreen controls work but background audio does not.

I know that both can coexist because I was previously using expo-ev with react-native-music-control (RNMC), and the RNMC lockscreen controls worked fine when expo-av background mode was enabled. Unfortunately, RNMC is poorly maintained and never made the updates necessary to support Android 12.

**Describe the ideal solution**
So, the ideal scenario is that my company can continue to use expo-av for playing short clips, and RNTP for playing long-form audio, while maintaining the functionality of lockscreen controls and background mode.

**Describe alternatives you've considered**
I've considered trying to patch RNMC, but my company isn't large enough yet to maintain such a project. I've considered using other methods (like react-native-sound) for playing short clip audio, rather than expo-av; and I will be exploring this further.

**How I can Help**
At the moment, I can provide feedback and help debugging. But I can't provide much developer support for another year or so, as we are a very early startup. If all goes well, I can dedicate developer hours to helping maintain RNTP at that time.

**Comment by jamsch** [comment]
Same use case here. We have a lot of short audio clips (1-10 secs) and longer podcast-style audio (10-30 minutes). We currently use expo-av for both, but would like to use this library for our longer form audio (so that we can utilise the lock screen controls). 

Unfortunately both libraries use different versions of ExoPlayer, and this library seems to use a custom build of ExoPlayer -- https://github.com/doublesymmetry/ExoPlayer (com.doublesymmetry.exoplayer) which prevents the Android app from building (due to duplicate classes) and dependency resolution was somewhat challenging beause of custom symbols (`com.google.android.exoplayer2.ui.PlayerNotificationManager. PrimaryActionReceiver`)

The following Android config seems to build and not crash on startup with the following packages:

- react-native-track-player@3.0.0
- expo-av@12.0.4

Can't guarantee stability between packages (because expo-av is using exoplayer 2.13.3 and react-native-track-player is using a custom version of exoplayer 2.17.2)

```gradle
// android/app/build.gradle

configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute(module("com.google.android.exoplayer:exoplayer"))
                .using(module("com.github.doublesymmetry.Exoplayer:exoplayer:r2.17.2")).because("Duplicate dependency")
        substitute(module("com.google.android.exoplayer:exoplayer-core"))
                .using(module("com.github.doublesymmetry.Exoplayer:exoplayer-core:r2.17.2")).because("Duplicate dependency")
         substitute(module("com.google.android.exoplayer:exoplayer-common"))
                .using(module("com.github.doublesymmetry.Exoplayer:exoplayer-common:r2.17.2")).because("Duplicate dependency")
    }
}
```

**Comment by jspizziri** [comment]
@jamsch @russriser as of v3.1.0 we no longer use a custom fork of Exoplayer.

**Comment by russriser** [comment]
Great, thank you. That should resolve the Duplicates problem so I don't need my ConfigPlugin anymore.

I don't think it resolves this issue though. It is still not possible to use expo-av and RNTP while having both background audio and lockscreen controls enabled.

**Comment by jamsch** [comment]
@russriser Try using expo-av's `setAudioModeAsync` to set the audio mode prior to audio playback

```ts
import { Audio, InterruptionModeAndroid, InterruptionModeIOS } from "expo-av";
import TrackPlayer, { Track } from "react-native-track-player";

function setAudioMode() {
  Audio.setAudioModeAsync({
    allowsRecordingIOS: false,
    staysActiveInBackground: true,
    interruptionModeIOS: InterruptionModeIOS.DoNotMix, // Audio.INTERRUPTION_MODE_IOS_MIX_WITH_OTHERS,
    playsInSilentModeIOS: true,
    shouldDuckAndroid: true,
    interruptionModeAndroid: InterruptionModeAndroid.DuckOthers,
    playThroughEarpieceAndroid: false,
  });
}

function play() {
  // Configures audio options (iOS mostly needs this so that media center controls work correctly)
  await configureAudioMode();
  // Add the track
  await TrackPlayer.add(track);
}
```

**Comment by jspizziri** [comment]
@jamsch is the issue resolved for you now?

**Comment by russriser** [comment]
It appears the solution was to add the interuptionModeIOS. Working for me now.

So maybe this could be added to the documentation somewhere? I don't know where since its not really expo-av nor RNTP specific.

**Comment by russriser** [comment]
There does seem to still be a remaining problem on Android. The app crashes when trying to play audio clips with expo-av when RNTP is installed. Seems to maybe be a conflict with exoplayer version or something.

@jamsch do you have the same problem?

here's the log:
```
Your app just crashed. See the error below.

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/Player$EventListener;
at expo.modules.av.player.PlayerData.createUnloadedPlayerData(PlayerData.java:192)
at expo.modules.av.AVManager.lambda$loadForSound$1$expo-modules-av-AVManager(AVManager.java:427)
at expo.modules.av.AVManager$$ExternalSyntheticLambda1.run(Unknown Source:8)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7870)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
at Caused By dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at expo.modules.av.player.PlayerData.createUnloadedPlayerData(PlayerData.java:192)
at expo.modules.av.AVManager.lambda$loadForSound$1$expo-modules-av-AVManager(AVManager.java:427)
at expo.modules.av.AVManager$$ExternalSyntheticLambda1.run(Unknown Source:8)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7870)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by jamsch** [comment]
@russriser Yep, I had the same issue. It looks like expo-av uses an older version of ExoPlayer (v2.13.3) while this lib uses ExoPlayer 2.18.1. ExoPlayer doesn't follow semver and seems to have a lot of breaking changes across minor versions. 

So I've whipped up a patch for expo-av to use the latest ExoPlayer. I have very little Java knowledge, but just briefly tested some short audio and video clips which seems to be working OK.

/patches/expo-av+12.0.4.patch
```diff
diff --git a/node_modules/expo-av/android/build.gradle b/node_modules/expo-av/android/build.gradle
index 767db05..e36aa50 100644
--- a/node_modules/expo-av/android/build.gradle
+++ b/node_modules/expo-av/android/build.gradle
@@ -151,7 +151,7 @@ dependencies {
   extractHeaders 'com.facebook.fbjni:fbjni:0.2.2:headers'
   extractJNI 'com.facebook.fbjni:fbjni:0.2.2'
 
-  api 'com.google.android.exoplayer:exoplayer:2.13.3'
+  api 'com.google.android.exoplayer:exoplayer:2.18.1'
   api 'com.google.android.exoplayer:extension-okhttp:2.13.3'
 
   api "com.squareup.okhttp3:okhttp:3.14.9"
diff --git a/node_modules/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java b/node_modules/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java
index 8f1b9ed..6494d10 100644
--- a/node_modules/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java
+++ b/node_modules/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java
@@ -13,12 +13,12 @@ import androidx.annotation.NonNull;
 import androidx.annotation.Nullable;
 
 import com.google.android.exoplayer2.C;
-import com.google.android.exoplayer2.ExoPlaybackException;
 import com.google.android.exoplayer2.MediaItem;
+import com.google.android.exoplayer2.PlaybackException;
 import com.google.android.exoplayer2.PlaybackParameters;
 import com.google.android.exoplayer2.Player;
 import com.google.android.exoplayer2.SimpleExoPlayer;
-import com.google.android.exoplayer2.source.ExtractorMediaSource;
+import com.google.android.exoplayer2.source.ProgressiveMediaSource;
 import com.google.android.exoplayer2.source.LoadEventInfo;
 import com.google.android.exoplayer2.source.MediaLoadData;
 import com.google.android.exoplayer2.source.MediaSource;
@@ -36,8 +36,8 @@ import com.google.android.exoplayer2.upstream.DataSource;
 import com.google.android.exoplayer2.upstream.DataSpec;
 import com.google.android.exoplayer2.upstream.DefaultBandwidthMeter;
 import com.google.android.exoplayer2.upstream.RawResourceDataSource;
+import com.google.android.exoplayer2.video.VideoSize;
 import com.google.android.exoplayer2.util.Util;
-import com.google.android.exoplayer2.video.VideoListener;
 
 import java.io.IOException;
 import java.util.Map;
@@ -47,7 +47,7 @@ import expo.modules.av.AudioFocusNotAcquiredException;
 import expo.modules.av.player.datasource.DataSourceFactoryProvider;
 
 class SimpleExoPlayerData extends PlayerData
-  implements Player.EventListener, MediaSourceEventListener, VideoListener {
+  implements Player.Listener, MediaSourceEventListener {
 
   private static final String IMPLEMENTATION_NAME = "SimpleExoPlayer";
   private static final String TAG = SimpleExoPlayerData.class.getSimpleName();
@@ -92,7 +92,6 @@ class SimpleExoPlayerData extends PlayerData
         .build();
 
     mSimpleExoPlayer.addListener(this);
-    mSimpleExoPlayer.addVideoListener(this);
 
     // Produces DataSource instances through which media data is loaded.
     final DataSource.Factory dataSourceFactory = mAVModule.getModuleRegistry()
@@ -312,7 +311,7 @@ class SimpleExoPlayerData extends PlayerData
   }
 
   @Override
-  public void onPlayerError(final ExoPlaybackException error) {
+  public void onPlayerError(final PlaybackException error) {
     onFatalError(error.getCause());
   }
 
@@ -325,7 +324,7 @@ class SimpleExoPlayerData extends PlayerData
     // Source: https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/Timeline.Period.html
     // So I guess it's safe to say that when a period transition happens,
     // media file transition happens, so we just finished playing one.
-    if (reason == Player.DISCONTINUITY_REASON_PERIOD_TRANSITION) {
+    if (reason == Player.DISCONTINUITY_REASON_AUTO_TRANSITION) {
       callStatusUpdateListenerWithDidJustFinish();
     }
   }
@@ -366,9 +365,11 @@ class SimpleExoPlayerData extends PlayerData
   // region VideoListener
 
   @Override
-  public void onVideoSizeChanged(final int width, final int height, final int unAppliedRotationDegrees, final float pixelWidthHeightRatio) {
+  public void onVideoSizeChanged(VideoSize videoSize) {
+
+    // final int width, final int height, final int unAppliedRotationDegrees, final float pixelWidthHeightRatio
     // TODO other params?
-    mVideoWidthHeight = new Pair<>(width, height);
+    mVideoWidthHeight = new Pair<>(videoSize.width, videoSize.height);
     if (mFirstFrameRendered && mVideoSizeUpdateListener != null) {
       mVideoSizeUpdateListener.onVideoSizeUpdate(mVideoWidthHeight);
     }
@@ -405,7 +406,7 @@ class SimpleExoPlayerData extends PlayerData
       case C.TYPE_HLS:
         return new HlsMediaSource.Factory(factory).createMediaSource(MediaItem.fromUri(uri));
       case C.TYPE_OTHER:
-        return new ExtractorMediaSource.Factory(factory).createMediaSource(MediaItem.fromUri(uri));
+        return new ProgressiveMediaSource.Factory(factory).createMediaSource(MediaItem.fromUri(uri));
       default: {
         throw new IllegalStateException("Content of this type is unsupported at the moment. Unsupported type: " + type);
       }
diff --git a/node_modules/expo-av/android/src/main/java/expo/modules/av/player/datasource/CustomHeadersOkHttpDataSourceFactory.java b/node_modules/expo-av/android/src/main/java/expo/modules/av/player/datasource/CustomHeadersOkHttpDataSourceFactory.java
index d127b7f..f86e3a6 100644
--- a/node_modules/expo-av/android/src/main/java/expo/modules/av/player/datasource/CustomHeadersOkHttpDataSourceFactory.java
+++ b/node_modules/expo-av/android/src/main/java/expo/modules/av/player/datasource/CustomHeadersOkHttpDataSourceFactory.java
@@ -9,6 +9,7 @@ import com.google.android.exoplayer2.upstream.HttpDataSource;
 import com.google.android.exoplayer2.upstream.TransferListener;
 
 import java.util.Map;
+import java.util.HashMap;
 
 import okhttp3.CacheControl;
 import okhttp3.Call;
@@ -28,16 +29,19 @@ public class CustomHeadersOkHttpDataSourceFactory extends HttpDataSource.BaseFac
     mCallFactory = callFactory;
     mUserAgent = userAgent;
     mCacheControl = null;
-    updateRequestProperties(getDefaultRequestProperties(), requestHeaders);
+    updateRequestProperties(requestHeaders);
   }
 
-  protected void updateRequestProperties(HttpDataSource.RequestProperties requestProperties, @Nullable Map<String, Object> requestHeaders) {
+  protected void updateRequestProperties(@Nullable Map<String, Object> requestHeaders) {
     if (requestHeaders != null) {
-      for (Map.Entry<String, Object> headerEntry : requestHeaders.entrySet()) {
-        if (headerEntry.getValue() instanceof String) {
-          requestProperties.set(headerEntry.getKey(), (String) headerEntry.getValue());
+      Map<String, String> headers = new HashMap<>();
+      for (Map.Entry<String, Object> entry : requestHeaders.entrySet()) {
+        Object value = entry.getValue();
+        if (value instanceof String) {
+          headers.put(entry.getKey(), entry.getValue().toString());
         }
       }
+      setDefaultRequestProperties(headers);
     }
   }
```

Just install `patch-package` and place the above in `/patches/expo-av+12.0.4.patch` and it should apply the changes.

**Comment by jspizziri** [comment]
Closing this issue as it looks like it's resolved by the comment above.

**Comment by nemrosim** [comment]
@jamsch Thank you!

**Comment by AronBe** [comment]
Hey guys, has anyone found a way how to recover lockscreen audio controls that react-native-track-player provides after playing Video via Expo-AV? Expo-AV surely overrides something and the lockscreen audio controls cannot be shown afterwards. Running `setupPlayer` second time won't probably do anything because there is already instance existing, right? I am on nightly.

**Comment by AndyMeagher** [comment]
> @russriser Try using expo-av's `setAudioModeAsync` to set the audio mode prior to audio playback
> 
> ```ts
> import { Audio, InterruptionModeAndroid, InterruptionModeIOS } from "expo-av";
> import TrackPlayer, { Track } from "react-native-track-player";
> 
> function setAudioMode() {
>   return Audio.setAudioModeAsync({
>     allowsRecordingIOS: false,
>     staysActiveInBackground: true,
>     interruptionModeIOS: InterruptionModeIOS.DoNotMix, // Audio.INTERRUPTION_MODE_IOS_MIX_WITH_OTHERS,
>     playsInSilentModeIOS: true,
>     shouldDuckAndroid: true,
>     interruptionModeAndroid: InterruptionModeAndroid.DuckOthers,
>   });
> }
> 
> async function play() {
>   // Configures audio options (iOS mostly needs this so that media center controls work correctly)
>   await setAudioMode();
>   // Add the track
>   await TrackPlayer.add(track);
> }
> ```

This saved me after hours of struggling, thank you!

For future folks the key is the `interruptionModeIOS` value above

**Comment by Saphirah** [comment]
> Hey guys, has anyone found a way how to recover lockscreen audio controls that react-native-track-player provides after playing Video via Expo-AV? Expo-AV surely overrides something and the lockscreen audio controls cannot be shown afterwards. Running `setupPlayer` second time won't probably do anything because there is already instance existing, right? I am on nightly.

I am facing the same issue. When using expo-av audio controls in lock screen are overwritten and gone.
