### ISSUE TITLE
clearNowPlayingMetadata clears metadata, but never comes back

### ISSUE THREAD

**Issue by DennisdeWitNL** [doublesymmetry/react-native-track-player#1653]
**Describe the Bug**
After clearing the now playing metadata by clearNowPlayingMetadata, every new track added, will not show the metadata anymore, unless you fully restart the app after forcing the app to stop. This is an Android issue.

**Steps To Reproduce**
1) Download my example here: https://github.com/DennisdeWitNL/example-clearmetadata
2) Play the song. Check the metadata in the notification control center. It is there.
3) Now pause the song and check the metadata. It is still there.
4) Now click Clear Metadata. The metadata has been cleared.
5) Now click Queue and then click Play. There is still no metadata, unless you fully restart the app and stop the service.

**Code To Reproduce**
Please download my edited example here: https://github.com/DennisdeWitNL/example-clearmetadata

**Environment Info:**
Paste the results of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.93 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/Documents/Apps/node_modules/.bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.0, iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.0/14A5270f - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.3.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found


```
Paste the exact `react-native-track-player` version you are using

``` react-native-track-player@3.0.0 ```
Real device? Or simulator?
Both

What OS are you running?
macOS Ventura with Android Studio, the latest SDK. Also fails on a Samsung Galaxy S10 Ultra

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

There is no log in Logcat, therefore I don't know where to start. Willing to test a PR of course!

**Comment by jspizziri** [comment]
Possibly related to https://github.com/doublesymmetry/react-native-track-player/issues/1719?

**Comment by gavrichards** [comment]
> 5. Now click Queue and then click Play. There is still no metadata, unless you fully restart the app and stop the service.

The code for the Queue button in the example app is:

```
          <Button
            title="Queue"
            onPress={() => console.log('TODO: implement queue interface')}
            type="primary"
          />
```

So I don't think we can expect this to do anything 😉

**Comment by jspizziri** [comment]
@gavrichards ahh... Nice catch!

@DennisdeWitNL , @gavrichards is correct, that button in the example app currently doesn't do anything. Can you update your reproduction steps to outline how to repro?

**Comment by DennisdeWitNL** [comment]
@jspizziri It's over here. 

https://github.com/DennisdeWitNL/example-clearmetadata

**Comment by gavrichards** [comment]
@jspizziri I can confirm the described behaviour is correct - no matter what you do, the metadata doesn't come back once it has been cleared. Even calling `TrackPlayer.updateMetadataForTrack` with the [proposed fix for KotlinAudio](https://github.com/doublesymmetry/KotlinAudio/pull/52) doesn't bring it back.

**Comment by puckey** [comment]
I can fix this, but I am wondering what `TrackPlayer.clearNowPlayingMetadata()` is expected to do exactly. I don't see the method in the docs.. @jspizziri perhaps you know?

@DennisdeWitNL what do you expect from this functionality and why do you need it?

Is it supposed to set all the metadata fields to empty string?

Should it remove the notification? (in which case, why would you want to?)

**Comment by DennisdeWitNL** [comment]
To be fair, I don’t need this function anymore. I have replaced it with the StoppedPlaybackAndRemoveNotification updateOption.

**Comment by puckey** [comment]
Does anyone have a use for this functionality? Otherwise I would probably just nominate it for removal...

**Comment by jspizziri** [comment]
@gavrichards Do you know of a use case for this?

**Comment by gavrichards** [comment]
@jspizziri I don't use it in our codebase. Our app is for live radio stations, and their "on demand" content. For live radio, when a track is playing we show that, and when a track is no longer playing we update the metadata to show the programme/host who is currently on air, or the station name/logo. So we never have a need to clear it completely.

**Comment by puckey** [comment]
Deprecated this functionality in the following pull request: https://github.com/doublesymmetry/react-native-track-player/pull/1909

**Comment by watadarkstar** [comment]
@puckey We are on version 3.2 and use clearNowPlayingMetadata method to remove the track player from the notifications tray. See here for more context:
https://github.com/doublesymmetry/react-native-track-player/issues/1834#issuecomment-1472722508

Are you sure you want to deprecate this method? If so, how will we clear the track player from the notification tray? Since calling reset does not clear it from the tray.

**Comment by puckey** [comment]
@watadarkstar Could you make a feature request for this functionality? I guess the api would need to be something like 'hideNotification()` and `showNotification()`? We will be going ahead with removing this undocumented method in the next major version, since I see no easy way to support it when we upgrade to [media3](https://developer.android.com/media/media3) and the functionality is unclear.

**Comment by watadarkstar** [comment]
> @watadarkstar Could you make a feature request for this functionality? I guess the api would need to be something like `hideNotification()` and `showNotification()`? We will be going ahead with removing this undocumented method in the next major version, since I see no easy way to support it when we upgrade to [media3](https://developer.android.com/media/media3) and the functionality is unclear.

Ok I created the feature request https://github.com/doublesymmetry/react-native-track-player/issues/2415
