### ISSUE TITLE
[Feature Request] Volume change listener

### ISSUE THREAD

**Issue by stereodenis** [doublesymmetry/react-native-track-player#1655]
**What is the need and use case of this feature?**
I have `getVolume` and `setVolume` methods, but no listener for remote volume change: from hardware buttons and notification widgets.

**Describe the ideal solution**
Add such listener to the package. 
// listen the volume changing if you need
```
const volumeListener = TrackPlayer.addVolumeListener((data) => {
    const volume = data.value;
    console.log(volume);
});

//remove listener when you need it no more
TrackPlayer.removeVolumeListener(volumeListener)      
```

**Describe alternatives you've considered**
[You can reffer to react-native-system-setting@alpha](https://github.com/c19354837/react-native-system-setting/issues/134)

**How I can Help**
I can be a beta-tester

**Comment by stereodenis** [comment]
@doublesymmetry-dev @fabiandoublesymmetry what do you think?

**Comment by jspizziri** [comment]
@stereodenis 

We'll see if @dcvz thinks this should make it into the API. One thing I can say however, is that unless you plan on being a champion and doing some implementation, it's probably not going to get implemented by the core team. There are a lot of other feature requests and library needs and I don't see this falling near the top of the core team's priorities.

**Comment by lovegaoshi** [comment]
posting an [android solution](https://github.com/lovegaoshi/azusa-player-mobile/blob/6e1f9974701f7d23fa8c6e6e7f92a226885fff43/android/app/src/main/java/com/noxplay/noxplayer/APMVolumeListener.kt) - just register the listener inside [Activity.onCreate](https://github.com/lovegaoshi/azusa-player-mobile/blob/6e1f9974701f7d23fa8c6e6e7f92a226885fff43/android/app/src/main/java/com/noxplay/noxplayer/MainActivity.kt#L49).
