### ISSUE TITLE
Duration when buffering AAC is inconsistent

### ISSUE THREAD

**Issue by luco** [doublesymmetry/react-native-track-player#1656]
**Describe the Bug**
When using the `aac` codec (which is supported by iOS and Android) and buffering an url, the duration time is inconsistent.

**Steps To Reproduce**
Just use an url with an AAC file.

**Code To Reproduce**

```

const {position, buffered, duration} = useProgress();
const playerState = usePlaybackState();

...

const play = async () => {
		TrackPlayer.reset();
		await TrackPlayer.add([
				{
					url: data, // Load media from the network
					title: 'Audio',
					contentType: 'audio/aac'
				},
		]);
		TrackPlayer.play();
};


...

<Text>
{position}/{duration}
</Text>

```

![image](https://user-images.githubusercontent.com/246373/185693344-87b9fb66-0162-49a3-853d-ae1dcfd6691f.png)
![image](https://user-images.githubusercontent.com/246373/185693638-b2c4319f-3987-481d-9600-b4ded3d23989.png)
![image](https://user-images.githubusercontent.com/246373/185693708-831f0813-b5be-4dcd-a9fe-c0d368579e08.png)

The audio has 03:40 of duration. And every time I buffer it get different duration time.

**Environment Info:**

System:
    OS: macOS 12.0.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 51.85 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.16 - /usr/local/opt/node@14/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/lucasveiga/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.1 => 0.68.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

[react-native-track-player](https://github.com/doublesymmetry/react-native-track-player) @ latest

**Comment by puckey** [comment]
@luco could you give us the .aac file that is causing you issues? or just any old aac file that I can test this with..

are you seeing this on Android? iOS? Both?

**Comment by luco** [comment]
@puckey You can test with any aac file. It gives the same result both on iOS and Android.

**Comment by vishaledkey** [comment]
I am also facing this issue. Is it a problem with the library itself, or is it a metadata issue?
