### ISSUE TITLE
[Feature Request] Progress Updates Lag During Buffering

### ISSUE THREAD

**Issue by MrNapcae** [doublesymmetry/react-native-track-player#1660]
Hi there, I'm trying to implement an interface like Apple Podcasts (when you move the slider, the time changes in real time). When I change the position on the slider, TrackPlayer.seekTo(val)
 does not work instantly, because of this the slider twitches. I am using the @react-native-community/slider library. I tried adjusting the onSlidingStart and onSlidingComplete, and setting setTimeout, it improves the situation, but the twitching still remains. All examples available online also have this problem. Replacing the slider library doesn't solve the problem either. Could you please suggest how this problem is solved? Or maybe there is an example of a correct implementation with a slider? Thanks a lot!

Tested on physical iphone 13 pro max, ios 16.

`
 <Slider
              value={progress.position}
              minimumValue={0}
              maximumValue={progress.duration}
              minimumTrackTintColor={palette.ACTION_PRIMARY}
              maximumTrackTintColor={palette.BORD}
              onSlidingComplete={async (val: number) => {
                await TrackPlayer.seekTo(value)
              }}
            />
`

Version:  "react-native-track-player": "^2.1.3",

System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 115.11 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    
    
 update ->
Answer by gavrichards from the discord. But I didn't manage to solve the bug:
"Hey, I have the same thing in my app. I have a boolean state isDragging, which I use to set the value of the slider, like this:
const showPosition = isDragging ? draggingPosition : trackPosition;

So if it's dragging, the slider shows the dragging position, otherwise it shows the actual track position.
onSlidingStart, I call setIsDragging(true) and set the dragging position.
onSlidingComplete, I seek to the new position, and then set a 1 second timeout before calling setIsDragging(false).
This is the trick. It keeps the slider position in the dragged position for 1 second until the library then reports the correct new track position."

**Comment by jspizziri** [comment]
@MrNapcae , I've not seen this issue before, and it doesn't seem to exist in the example project. When I run the example project on an iPhone SE Gen 2 with iOS 15.5 , the progress slider is very smooth.

**Comment by jspizziri** [comment]
https://user-images.githubusercontent.com/1452066/186220652-990b2cbb-80dc-45d7-943c-e0573913bdf0.MOV

Here's a recording of me scrubbing quickly. I see no issues.

**Comment by jspizziri** [comment]
If you're able to send me a consistent reproduction of this based off of the example app, I'll take another look at it.

**Comment by MrNapcae** [comment]
> If you're able to send me a consistent reproduction of this based off of the example app, I'll take another look at it.

the only change I made was to put in a longer video from the internet, duration: 1066 sec
https://user-images.githubusercontent.com/42024544/186224425-de08d857-0568-44ef-ac48-9b4f979f441a.MP4

**Comment by jspizziri** [comment]
@MrNapcae what you're seeing looks like its the result of your audio file buffering. I don't think it has anything to do with the `.seekTo` being slow like you initially thought. When you scrub to the desired position it takes a few MS to actually buffer the file at that position before playback begins. My recommendation would be to observe the playback state, and if it's loading/buffering pausing the update of your progress bar slider.

Because the progress events are asynchronous between the native code and JS we can't guarantee a progress event won't show up during buffering.

@dcvz it's possible we could solve something like this in the `useProgress` hook?

**Comment by MrNapcae** [comment]
@jspizziri Is it possible to download the full audio before playing it in order to avoid this?

**Comment by jspizziri** [comment]
@MrNapcae yes, you can [download and play offline](https://react-native-track-player.js.org/docs/guides/offline-playback). I'm not 100% sure that will solve your problem, buffering the file from disk should be faster than buffering it from network, it just depends on the speed.

**Comment by MrNapcae** [comment]
@jspizziri then maybe you can find out the status that buffering is in progress?

**Comment by jspizziri** [comment]
@MrNapcae I'm not sure what you mean by that.

**Comment by MrNapcae** [comment]
@jspizziri Is there a way to receive a status that audio file is being loaded and it’s not available for playing yet?

**Comment by jspizziri** [comment]
@MrNapcae yes, [this is what I was mentioning here](https://github.com/doublesymmetry/react-native-track-player/issues/1660#issuecomment-1224414458). Please read the documentation for `PlaybackState` and `usePlaybackState`.

**Comment by MrNapcae** [comment]
@jspizziri 

`export const PlayPauseButton: React.FC = () => {
  const state = usePlaybackState();
  const isPlaying = state === State.Playing;
  const isLoading = state === State.Connecting || state === State.Buffering;
  console.log({state})`
  
  `
 LOG  Running "example" with {"rootTag":1,"initialProps":{}}
 LOG  {"state": "none"}
 LOG  Event.PlaybackTrackChanged {"nextTrack": 0, "position": 0}
 LOG  {"state": "none"}
 WARN  Could not find image file:///private/var/containers/Bundle/Application/514028A6-74FE-4D3F-B1F0-087F3B9A2427/example.app/undefined.png
 LOG  {"state": "connecting"}
 LOG  {"state": "connecting"}
 LOG  {"state": "connecting"}
 WARN  Could not find image file:///private/var/containers/Bundle/Application/514028A6-74FE-4D3F-B1F0-087F3B9A2427/example.app/%5Bobject%20Object%5D.png
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  Event.PlaybackProgressUpdated {"buffered": 1.2277551020408164, "duration": 1066.292244897959, "position": 712.389, "track": 0}
 LOG  {"state": "playing"}
 LOG  {"state": "playing"}
 LOG  Event.PlaybackProgressUpdated {"buffered": 771.6338321995465, "duration": 1066.292244897959, "position": 712.355231446, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 771.6338321995465, "duration": 1066.292244897959, "position": 712.35569703, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 194.01, "duration": 1066.292244897959, "position": 713.846866697, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 194.01, "duration": 1066.292244897959, "position": 194.01, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 181.789, "duration": 1066.292244897959, "position": 193.930829908, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 181.789, "duration": 1066.292244897959, "position": 193.931297608, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 181.789, "duration": 1066.292244897959, "position": 194.831256155, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 181.789, "duration": 1066.292244897959, "position": 181.789, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 181.789, "duration": 1066.292244897959, "position": 753.126, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 779.5339909297052, "duration": 1066.292244897959, "position": 753.044501001, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 779.5339909297052, "duration": 1066.292244897959, "position": 753.045060656, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 779.533061224, "duration": 1066.292244897959, "position": 754.001390154, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 779.533061224, "duration": 1066.292244897959, "position": 754.242950006, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 779.533061224, "duration": 1066.292244897959, "position": 0, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 3.84, "duration": 1066.292244897959, "position": -0.079086517, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 3.84, "duration": 1066.292244897959, "position": -0.078243578, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 3.853061224489796, "duration": 1066.292244897959, "position": 1.140048075, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 3.853061224489796, "duration": 1066.292244897959, "position": 697.112, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 3.853061224489796, "duration": 1066.292244897959, "position": 0, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 3.853061224489796, "duration": 1066.292244897959, "position": -0.078583703, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 3.853061224489796, "duration": 1066.292244897959, "position": -0.07811484, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 807.102, "duration": 1066.292244897959, "position": 1.226960484, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 807.102, "duration": 1066.292244897959, "position": 807.102, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 807.102, "duration": 1066.292244897959, "position": 807.022197193, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 807.102, "duration": 1066.292244897959, "position": 807.023367247, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 807.102, "duration": 1066.292244897959, "position": 807.430368215, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 807.102, "duration": 1066.292244897959, "position": 236.784, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 814.231, "duration": 1066.292244897959, "position": 236.70595202, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 814.231, "duration": 1066.292244897959, "position": 236.707587352, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 814.231, "duration": 1066.292244897959, "position": 236.97648155, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 814.231, "duration": 1066.292244897959, "position": 814.231, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 814.231, "duration": 1066.292244897959, "position": 814.1520755, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 814.231, "duration": 1066.292244897959, "position": 814.152983185, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 814.231, "duration": 1066.292244897959, "position": 814.652905555, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 814.231, "duration": 1066.292244897959, "position": 370.197, "track": 0}
 LOG  {"state": "paused"}
 LOG  {"state": "paused"}
 LOG  Event.PlaybackProgressUpdated {"buffered": 421.9167346938776, "duration": 1066.292244897959, "position": 881.447, "track": 0}
 LOG  {"state": "playing"}
 LOG  {"state": "playing"}
 LOG  Event.PlaybackProgressUpdated {"buffered": 421.9167346938776, "duration": 1066.292244897959, "position": 881.366568924, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 421.9167346938776, "duration": 1066.292244897959, "position": 881.366923665, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 197.065, "duration": 1066.292244897959, "position": 882.001424659, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 197.065, "duration": 1066.292244897959, "position": 882.821191187, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 197.065, "duration": 1066.292244897959, "position": 197.065, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 232.71, "duration": 1066.292244897959, "position": 196.985123817, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 232.71, "duration": 1066.292244897959, "position": 196.985561847, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 232.71, "duration": 1066.292244897959, "position": 197.660182181, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 232.71, "duration": 1066.292244897959, "position": 232.71, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 232.71, "duration": 1066.292244897959, "position": 232.630488903, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 232.71, "duration": 1066.292244897959, "position": 232.630707397, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 232.71, "duration": 1066.292244897959, "position": 233.130180034, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 232.71, "duration": 1066.292244897959, "position": 691.002, "track": 0}
 LOG  {"state": "paused"}
 LOG  {"state": "paused"}
 LOG  Event.PlaybackProgressUpdated {"buffered": 166.512, "duration": 1066.292244897959, "position": 166.512, "track": 0}
 LOG  {"state": "playing"}
 LOG  {"state": "playing"}
 LOG  Event.PlaybackProgressUpdated {"buffered": 166.512, "duration": 1066.292244897959, "position": 166.432661738, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 166.512, "duration": 1066.292244897959, "position": 166.432661738, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 166.512, "duration": 1066.292244897959, "position": 166.432661738, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 166.512, "duration": 1066.292244897959, "position": 868.208, "track": 0}
 LOG  {"state": "paused"}
 LOG  {"state": "paused"}
 LOG  {"state": "playing"}
 LOG  {"state": "playing"}
 LOG  Event.PlaybackProgressUpdated {"buffered": 871.5516780045351, "duration": 1066.292244897959, "position": 868.12855803, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 871.5516780045351, "duration": 1066.292244897959, "position": 868.129897829, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 886.008163265, "duration": 1066.292244897959, "position": 870.001387677, "track": 0}
 LOG  Event.PlaybackProgressUpdated {"buffered": 888.594285714, "duration": 1066.292244897959, "position": 870.361078773, "track": 0}
 LOG  {"state": "paused"}
 LOG  {"state": "paused"}
 LOG  {"state": "paused"}
 LOG  {"state": "paused"}

`

**Comment by jspizziri** [comment]
@MrNapcae I don't want to be rude. But there's no way I'm going to read through that massive text dump and try and interpret what you're asking me.

**Comment by MrNapcae** [comment]
> @MrNapcae I don't want to be rude. But there's no way I'm going to read through that massive text dump and try and interpret what you're asking me.

sorry, updated

**Comment by mekaVR** [comment]
Hi @jspizziri I have the same problem when I go from pause to play the status of the player changes from loading/buffering playing/ready/paused

only on iOS on Android no problems

Thanks

**Comment by izyspania** [comment]
Hi , i have the same issue, i never get State.Buffering,  am i missing something?
It works with TS v2.1.3 but with any higher versions than that it doesnt.

**Comment by jspizziri** [comment]
@mekaVR @MrNapcae @izyspania 

Please try the nightly build which we believe resolves the buffering not being emitted issue.

See here for more detail

https://github.com/doublesymmetry/react-native-track-player/issues/1720#issuecomment-1246485024

**Comment by izyspania** [comment]
Sadly it does exactly the same , no Buffering state. "version": "3.1.0-7b247404c2b54df0550379277949a1cab5ddf47c",
