### ISSUE TITLE
[Feature Request] lessen async js complexity

### ISSUE THREAD

**Issue by puckey** [doublesymmetry/react-native-track-player#1684]
**What is the need and use case of this feature?**

Whenever I find myself writing code using RNTP, I find myself needing to worry about:

- chaining async calls
- making sure they do not cause race conditions
- where to place the setupPlayer code to have it running before I call anything else (and wait for it to complete)
- making sure that if anything throws, I setup the player again because the service is not running and then rerun the function I called to see if that works

**Describe the ideal solution**
By bringing down the async calls to as little as possible, we can reduce async complexity as well as improve performance (less to and fro between js and native).

Here is an example of a new function signature for `TrackPlayer.add`:

```js
await TrackPlayer.add(tracks, {
  /** (optional) Whether the tracks should replace the current (or upcoming when 'upcoming') queue */
  replace: 'upcoming',
  /** (optional) The repeat mode */
  repeat: RepeatMode.Queue,
  /** (optional) the index at which to add the tracks */
  index: 5,
  /** Whether to skip to the first of the added tracks (optional, can also be boolean) */  
  skip: {
    /** (optional) Whether to play after skipping */
    play: true,
    /** (optional) The position at which to start playing */
    position: 10
  }
});
```

Which replaces something like:
```js
await TrackPlayer.removeUpcomingTracks();
const index = await TrackPlayer.add([track]);
await TrackPlayer.setRepeatMode(RepeatMode.Queue);
await TrackPlayer.skip(index, 10);
await TrackPlayer.play();
```

To avoid race conditions, we could setup an internal promise queue in RNTP where we wait for any queue related function call to resolve first before calling the next. We can also catch any errors here and setup the player again and rerun them here. This could happen either on the js side or on the native side.

Also, I believe all of this could be done in a backward compatible way.

Would love to your thoughts on this.

**Comment by mpivchev** [comment]
This is a cool concept of a DSL/Builder pattern and I really like it. It definitely provides the templates for everything a person needs to worry about while setting up a player. We should look into this.

**Comment by jspizziri** [comment]
If we were to move in this direction my feedback would be to provide an even high-level abstraction like:

```ts
await TrackPlayer.dispatchCommands([
  { name: "add", args: {...} ],
  ...
]);
```

**Comment by puckey** [comment]
While `TurboModules` is definitely the future, a downside seems to be that all packages must use them or it won't work. It is going to take quite some time to reach such a grade of adoption. (If you compare it to for example the slow adoption of ESM which has ben a pita on the node.js side)

This chaining of commands is very interesting and is something which internally would probably look like the data structure @jspizziri is speaking of. I wonder however, what return types would then work like. Or perhaps this would be only the queue logic subset of functionality?

How about:
```
TrackPlayer.run(
    Playlist.play().add(track).seek(XX)
)
```

or

```
Playlist.play().add(track).seek(XX).run()
```

On the issue of async issues between dispatch commands, the way I have been ensuring the order of async calls is to use a local promise queue. Something like:

```js
let p = Promise.resolve();

const play = () => {
  return p = p.then(
    () => TrackPlayer.play()
  )
};

const seek = (time) => {
  return p = p.then(
    () => TrackPlayer.seek(time)
  )
};

const add(track) => {
  return p = p.then(
    () => TrackPlayer.add(track)
  )
}
```

That way any async call must resolve first before the next is performed, ensuring async call order. We could have something like this running in the background on the JS side to ensure call order. And you can even add error catching logic in there, which has `setupPlayer` called on failure. Which is then something else that users would not need to worry about.

The (theoretical) downside of this might be that queueing is slow – but I have yet to experience this on my side.

**Comment by puckey** [comment]
The two could even be combined, where you would just have the existing api as is, but internally a buffer is built up and every tick (or x ms) the command list sent to the native side and results are return as an array. Then each promise can resolve individually with the return values. So imagine:

```
TrackPlayer.play()
TrackPlayer.add(track)
TrackPlayer.skip(10)
```

leads to internal buffer:

```
[['play'], ['add', track], ['skip', 10]]
```

Which is sent to the native side (after which the internal buffer is set to [] again and waits for new commands) and the commands are performed and returned back to the js side with the list of return values:

```
[null, 0 , null]
```

Then the js side resolves all the promises with their corresponding return values.

**Comment by qmx** [comment]
@jspizziri is there a PR where those changes landed?

**Comment by jspizziri** [comment]
@qmx, we're now using our project board to manage our workflow. See more on discord.

This feature is going in our backlog, which means we ant to implement it at some point in the future, but it's not on a concrete roadmap. All such features are organized in our project and closed. Once they're on a concrete roadmap we'll reopen them.
