### ISSUE TITLE
useTrackPlayerEvents callback type issue

### ISSUE THREAD

**Issue by RamProg** [doublesymmetry/react-native-track-player#1690]
**Describe the Bug**

When I use useTrackPlayerEvents just as described in the docs, I get a type error: 

> Property 'type' does not exist on type '(PlaybackStateEvent & { event: Event.PlaybackState; }) | (PlaybackErrorEvent & { event: Event.PlaybackError; }) | (PlaybackQueueEndedEvent & { ...; }) | ... 18 more ... | { ...; }'.
  Property 'type' does not exist on type 'PlaybackStateEvent & { event: Event.PlaybackState; }'.ts(2339)

But if I log the event itself I get this object:

`"state": 1, "type": "playback-state"}`

So it seems type is the right property, I think this is just a type issue.

**Steps To Reproduce**

1. Implement the package
2. Try to use useTrackPlayerEvents as described in docs: https://react-native-track-player.js.org/docs/basics/getting-started#controlling-the-queue

**Code To Reproduce**

```
    useTrackPlayerEvents([Event.PlaybackTrackChanged], async event => {
        if (event.type === Event.PlaybackTrackChanged && event.nextTrack != null) {
            const track = await TrackPlayer.getTrack(event.nextTrack);
            const {title} = track || {};
            setTrackTitle(title);
        }
    });
```

**Environment Info:**

```
System:
    OS: macOS 12.2.1
    CPU: (10) x64 Apple M1 Max
    Memory: 122.17 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.15.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
`react-native-track-player v3.1.0`

**How I can Help**

This might be an easy fix, just replacing the property event with type in useTrackPlayerEvents callback.

**Comment by jspizziri** [comment]
This was already fixed here https://github.com/doublesymmetry/react-native-track-player/pull/1662

Please install the nightly build.
