### ISSUE TITLE
Capability.SkipToNext not showing any button on Android

### ISSUE THREAD

**Issue by ghiculescualexandru** [doublesymmetry/react-native-track-player#1698]
**Describe the Bug**
I previously had version 2.1.4 and the remote controls worked great on both iOS and Android. I'm trying to update to 3.1.0 and iOS works pretty much the same, however on Android the remote skip button does not show or is always disabled (depending on the type of android phone/emulator I'm trying).

**Steps To Reproduce**
**Code To Reproduce**
Here are my options:

<img width="324" alt="Screenshot 2022-09-05 at 11 31 58 AM" src="https://user-images.githubusercontent.com/52600189/188429055-eb600f14-6877-4074-9c3b-bd3cacc5e7a6.png">

And this is the result:

<img width="356" alt="Screenshot 2022-09-05 at 11 35 55 AM" src="https://user-images.githubusercontent.com/52600189/188429734-9f13d096-636f-410d-8547-2279887fe16c.png">

**Environment Info:**
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 68.86 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 7.24.0 - /usr/local/bin/npm
    Watchman: 2021.10.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

"react-native-track-player": "3.1.0",

Both real device and simulator for Android.

**Comment by RamProg** [comment]
I think your issue and mine are somehow related: https://github.com/doublesymmetry/react-native-track-player/issues/1701

**Comment by jspizziri** [comment]
All, we've had at least 2 separate reports that have to do with `compactCapabilites`. We're going to address them all at the same time. I'm going to close this issue in favor of the aggregate one:

https://github.com/doublesymmetry/react-native-track-player/issues/1702
