### ISSUE TITLE
MusicService.onDestroy crashing app at startup (Android)

### ISSUE THREAD

**Issue by praisedavid787** [doublesymmetry/react-native-track-player#1699]
**Describe the Bug**
Hi guys, great job going on here. So I noticed these crashes upon using version 3.1.0 recently:
``` sh
Caused by kotlin.UninitializedPropertyAccessException: lateinit property player has not been initialized
       at com.doublesymmetry.trackplayer.service.MusicService.onDestroy (MusicService.kt:471)
       at android.app.ActivityThread.handleStopService (ActivityThread.java:4805)
```
and 
``` sh
Caused by kotlin.UninitializedPropertyAccessException: lateinit property player has not been initialized
       at com.doublesymmetry.trackplayer.service.MusicService.onTaskRemoved(MusicService.kt:459)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4696)
```

**Steps To Reproduce**
Oh so I noticed this at start up sometimes and the second popped up on firebase crashlytics.

**Environment Info:**
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 74.93 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
`react-native-track-player` version `3.1.0`
Real device and simulator

**How I can Help**
Now digging through `MusicService.kt` I believe the faulty lines are:
``` kotlin
    @MainThread
    override fun onDestroy() {
        super.onDestroy()
        if (this::player.isInitialized) { // possible fix applied
            player.stop()
        }
    }
```
and
``` kotlin
    @MainThread
    override fun onTaskRemoved(rootIntent: Intent?) {
        super.onTaskRemoved(rootIntent)

        if (stoppingAppPausesPlayback && this::player.isInitialized) { // possible fix applied
            player.pause()
        }
    }
```
Tested on the example app and its gone well. PR #1700. Hoping these can be released soon as it is being experienced in production. Thanks a lot.

**Comment by arakovskis** [comment]
Even with that fix, I get the app crashed
`15930-15930/com.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mindtalesapp, PID: 15930
    java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /data/user/0/com.app/cache/TrackPlayer`

**Comment by rborn** [comment]
@arakovskis that's a different bug, more here: https://github.com/doublesymmetry/react-native-track-player/issues/1639#issuecomment-1236852241

**Comment by rborn** [comment]
Someone with more kotlink knowledge maybe can fix the SimpleCache issue: https://github.com/doublesymmetry/KotlinAudio/issues/9#issuecomment-1237018054  @praisedavid787 😀

**Comment by rborn** [comment]
I believe was this https://github.com/doublesymmetry/react-native-track-player/pull/1700, same solution  as in my comment, only that @praisedavid787 actually put the work and made the PR 😅

**Comment by jspizziri** [comment]
Oh nice, it already got merged so I missed it. Thanks!

**Comment by ariangel** [comment]
Hey @jspizziri please can you create a new version with this fix? thank you!

**Comment by jspizziri** [comment]
Please install the nightly build
