### ISSUE TITLE
Compact Players not respecting Compact Capabilities

### ISSUE THREAD

**Issue by jspizziri** [doublesymmetry/react-native-track-player#1702]
There are two issues with buttons in Android being displayed based on configured capabilities.

1. https://github.com/doublesymmetry/react-native-track-player/issues/1701
2. https://github.com/doublesymmetry/react-native-track-player/issues/1698
3. https://discord.com/channels/567636850513018880/600714011318681610/1016786934888149082

Capabilities need to be re-evaluated and we should ensure that the proper controls show up corresponding to the options that are configured.

Note: we should be sure to test with both multi-track and single-track queues.

**Comment by ghiculescualexandru** [comment]
I think the problem occurs when having a single track in the queue. If you have at least 2 track at all times, the remote skip button appears correctly.

**Comment by RamProg** [comment]
My app never has more than one track in the queue and always shows the previous track button. Can't get rid of it.

**Comment by mpivchev** [comment]
Currently investigating this. Fixed a few bugs regarding which buttons appear by default. Will continue to work on it.

> I think the problem occurs when having a single track in the queue. If you have at least 2 track at all times, the remote skip button appears correctly.

@ghiculescualexandru This is default player behavior as it makes no sense for this button to exist when there is no other track to skip to.

> My app never has more than one track in the queue and always shows the previous track button. Can't get rid of it.

@RamProg This will always show even if there is only a single track in the player, as skip to previous will then act as a "skip to beginning". This is default ExoPlayer behavior and not sure if it can be changed, will look into it.

**Comment by jspizziri** [comment]
Pleas see the discussion on https://github.com/doublesymmetry/react-native-track-player/issues/1708

**Comment by RamProg** [comment]
> @RamProg This is intended and will always show even if there is only a single track in the player, as skip to previous will then act as a "skip to beginning". As far as I'm aware the internal library we use doesn't allow that to change.

Then we don't have a way of preventing that button from showing up?

This was possible on previous versions. So it's not a bug, but a limitation of the library?

**Comment by mpivchev** [comment]
@RamProg yes, it's a limitation.

**Comment by jspizziri** [comment]
@mpivchev kotlinaudio 1.2.3 contains this fix right?

**Comment by jspizziri** [comment]
This is now fixed in `main` and will be released with `3.2` (and/or `nightly`, whichever comes first).
