### ISSUE TITLE
[Feature Request] Android: Handle Noisy Audio

### ISSUE THREAD

**Issue by dcvz** [doublesymmetry/react-native-track-player#1705]
**What is the need and use case of this feature?**
Automatically handle changing between earphones and speakers

**Describe the ideal solution**
Make use of https://github.com/doublesymmetry/KotlinAudio/pull/26 when that's released

**Comment by mpivchev** [comment]
> Automatically handle changing between earphones and speakers

I don't think it's super clear from this description. As far as I can see the issue is about pausing the app when we switch output in case it's too loud? But in general we DO automatically handle switching between output devices.
