### ISSUE TITLE
[Proposal] Capabilities need to be streamlined

### ISSUE THREAD

**Issue by mpivchev** [doublesymmetry/react-native-track-player#1708]
For reference, here are all the current Capabilities that RNTP has:
```typescript
export declare enum Capability {
    Play,
    PlayFromId,
    PlayFromSearch,
    Pause,
    Stop,
    SeekTo,
    Skip,
    SkipToNext,
    SkipToPrevious,
    JumpForward,
    JumpBackward,
    SetRating,
    Like,
    Dislike,
    Bookmark
}
```

1. Capabilities and compact capabilities only affect how the notification looks and works, and they do not affect that actual capabilities of the player, at least on Android. Some "capabilities" are notification components, and some are just buttons. In that case, they should be renamed to properly reflect what they are. In the points below I will refer to them as buttons and components.

<img width="361" alt="image" src="https://user-images.githubusercontent.com/6960329/189085673-8f289840-2c9e-4e4d-bace-7f9d2d417873.png">  ![#f03c15](https://via.placeholder.com/15/f03c15/f03c15.png) are buttons ![#00FA00](https://via.placeholder.com/15/00FA00/00FA00.png) are components

3. The `Play` and `Pause` buttons should be combined, as they are essentially one button. Depending on player state, Play must always change to Pause and vice versa. Besides, our internal Android audio library regards them as one button anyway.
4. `SeekTo` is technically not a button, but it is a component of a notification. Also, `SeekTo` can't be a compact component, and it should never be allowed to be set as such. It only causes confusion.
5. Some buttons like `PlayFromId`, `PlayFromSearch`, `SetRating` and potentially `Like`, `Dislike`, `Bookmark` are not related to notifications and they should be removed.

These points are related to Android notifications, but I believe iOS notifications work the same way and as such will benefit from these changes. @dcvz can hopefully provide his input on the iOS notification.

**Comment by jspizziri** [comment]
@mpivchev This makes a lot of sense to me provided:

1. We make the change without introducing Breaking Changes, which it seems like we can do if we deprecate them old capabilities and just map them to the new ones.
2. If iOS does in fact behave similarly (which it seems like it would). I know compactCapabilities/notificationCapabilities are only an android thing.
3. Have you thought about how notificationCapabilities fit into the mix?

**Comment by mpivchev** [comment]
@jspizziri 
1. I can't promise no breaking changes, so we can try doing this for 4.0
2. That is correct. This needs to be taken into account when changing the API for this so it's as easy to set up as possible.
3. As I mentioned above, notifications don't really have capabilities.

**Comment by jspizziri** [comment]
@mpivchev is there something we can do prior to 4.0 that will allow us fix the issues that users are reporting?

**Comment by mpivchev** [comment]
@jspizziri What was reported were actually things that are intended with ExoPlayer, so they are not bugs. We can add custom functionality and add the changes people want, but I think currently we have higher priorities of what to work on.
