### ISSUE TITLE
[Feature Request] Shuffle and unshuffle queue

### ISSUE THREAD

**Issue by bradleyflood** [doublesymmetry/react-native-track-player#1711]
**What is the need and use case of this feature?**
As an app user, listening to a playlist (`queue`) of audio files, I want to shuffle the queue so it's not always the same. And if I turn shuffle off I want the original queue order resumed.

**Describe the ideal solution**
1. Activating the `shuffle` feature would randomly shuffle a copy of the current `queue` and queue this new list of shuffled tracks for playback, with the currently playing track (if any) at index 0, and all done without affecting playback of any track currently in progress. 
2. Deactivating the shuffle feature would restore the original queue order, continuing in the queue from the now currently playing track (which may be different from the track which was playing when shuffle was first activated). Again without affecting playback of any currently playing track).
3. Adding or removing tracks to and from the queue would operate as normal. The queue would only be "shuffled" when the feature is first turned on.

**Example queue, shuffle off, default:**

1. Track A
2. Track B <- (currently playing)
3. Track C
4. Track D

**Example queue, shuffle activated:**

1. Track B <- (currently playing)
2. Track D
3. Track C
4. Track A

**Example queue, shuffle deactivated:**

1. Track A
2. Track B <- (currently playing)
3. Track C
4. Track D

**Describe alternatives you've considered**
Coding this logic myself in JS, but would get messy quickly.

**Additional context**
Just like how the shuffle feature works in Apple Music, both from tapping "Shuffle" on the Playlist view (when nothing currently playing), and tapping the shuffle Icon in the Player screen during playback.

**How I can Help**
I can offer a $500 USD bounty for this feature to be fully developed (if the core team consider it a suitable feature for RNTP).

Thoughts??

**Comment by jspizziri** [comment]
I think shuffle is a useful feature to add to the lib. I suppose my question is: Is the best place to implement it in JS or native?

If the KotlinAudio and SwiftAudioEx libraries would also benefit from shuffle, then I suppose it's best to handle it natively and expose an API to RNTP. But it's a question for @dcvz 

Are you able/willing to do any implementation?

**Comment by jspizziri** [comment]
@bradleyflood I don't see this being implemented soon unless you're able to spearhead development. As such I'm going to add it to the feature backlog.

**Comment by puckey** [comment]
For future reference, this task would probably mainly entail porting this to iOS (and windows?): https://github.com/google/ExoPlayer/blob/03569f9e6536e6c60cb585115d6d7352a4deab71/library/core/src/main/java/com/google/android/exoplayer2/source/ShuffleOrder.java

Not trivial to do.. but would be nice to have at some point

**Comment by lovegaoshi** [comment]
I have the same shuffle need, a search of "shuffle" brought me here. I found that at least in android, removing tracks using `trackPlayer.remove()` that are not the `currentTrack` will not interrupt playback; so I put together two functions in `trackPlayer.ts` that are probably not ideal but seems to make shuffling work for me. to shuffle I would call `trackPlayer.shuffle()` and store the returned list, to turn off shuffle I call  `trackPlayer.setQueueUninterrupted()` with the stored list, or whatever your app's playlist management logic.

I'm probably overcomplicating things by not using removePreviousTracks() and removeUpcomingTracks(), but removePreviousTracks seems android exclusive. Though I don't have a mac, can't comment on how `trackPlayer.remove()` behaves on iOS.
```
/**
 * shuffles the current Queue. The method returns a pre-shuffled Queue,
 * to revert shuffling, use setQueueUninterrupted().
 */
export async function shuffle(): Promise<Track[]> {
  const currentQueue = await getQueue();
  const shuffledQueue = [...currentQueue].sort(() => Math.random() - 0.5);
  await setQueueUninterrupted(shuffledQueue);
  return currentQueue;
}

/**
 * This is a combination of removePreviousTracks() and removeUpcomingTracks().
 * To set the player's queue without playback interruption, remove
 * all tracks with remove() that are not the activeTrackIndex. The current
 * track will be automatically shifted to the first element. Then, splice tracks that
 * the currentTrack is at the first element, and add the spliced tracks.
 * @param tracks
 */
export async function setQueueUninterrupted(tracks: Track[]): Promise<void> {
  // if no currentTrack, its a simple setQueue
  const currentTrackIndex = await getActiveTrackIndex();
  console.debug('setQueueUninterrupted: currentTrackIndex is valid? ', currentTrackIndex);
  if (currentTrackIndex === undefined) return await setQueue(tracks);
  // if currentTrack is not in tracks, its a simple setQueue
  const currentQueue = await getQueue();
  const currentTrack = currentQueue[currentTrackIndex];
  const currentTrackNewIndex = tracks.findIndex(
    // define conditions to find the currentTrack in tracks
    (track) => track.url === currentTrack.url
  );
  console.debug(
    'setQueueUninterrupted: currentTrackIndex is present? ',
    currentTrackNewIndex,
    tracks,
    currentTrack
  );
  if (currentTrackNewIndex < 0) return await setQueue(tracks);
  // else, splice that all others are removed, new track list spliced
  // that the currentTrack becomes the first element.
  // eslint-disable-next-line prefer-const
  let removeTrackIndices = [...Array(currentQueue.length).keys()];
  removeTrackIndices.splice(currentTrackIndex, 1);
  await remove(removeTrackIndices);
  const splicedTracks = tracks
    .slice(currentTrackNewIndex + 1)
    .concat(tracks.slice(0, currentTrackNewIndex));
  console.debug('edited tracks', splicedTracks);
  await add(splicedTracks);
}
```
