### ISSUE TITLE
Remote events not triggering on ios

### ISSUE THREAD

**Issue by elirangoshen** [doublesymmetry/react-native-track-player#1712]
**Describe the Bug**
Player doesn't respond to remote events in while in background
e.g when i hit on play or pause from backround player

**Steps To Reproduce**
Run the player while app is in background, and interact and you notice that the remote events not triggered 

**Code To Reproduce**
```
export const PlaybackService = async function () {

  const remotePlay = async () => {
    console.log('remote play')
    await TrackPlayer.play()
  }

  TrackPlayer.addEventListener(Event.RemotePlay, remotePlay)

  TrackPlayer.addEventListener(Event.RemotePause, async () => await TrackPlayer.pause())

  TrackPlayer.addEventListener(Event.RemoteSeek, event =>
    TrackPlayer.seekTo(event.position),
  )
}
```

and then in index.js or main app entry file : 

```
AppRegistry.registerComponent(appName, () => App)
TrackPlayer.registerPlaybackService(() => PlaybackService)
```

the remote events triggered when i'm interacting with the background player - and i validate as the log doesn't output to console.
I also added the capabilities : 

```
const CAPABILITIES: Capability[] = [
  Capability.Pause,
  Capability.Play,
  Capability.SeekTo,
]

export const useVoicePlayer = () => {
  const initPlayer = async () => {
    await TrackPlayer.setupPlayer()
    await TrackPlayer.updateOptions({
      progressUpdateEventInterval: 1,
      capabilities: CAPABILITIES,
      notificationCapabilities: CAPABILITIES,
      compactCapabilities: CAPABILITIES,
    })
  }
```

**Environment Info:**
Paste the results of `npx react-native info`

```
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 122.63 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.1 => 0.69.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Paste the exact `react-native-track-player` version you are using
3.1.0
Real device? Or simulator?
real device
What OS are you running?
ios 15.16.1

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

I tried to debug and check that i did the setup to use it in background mode as in docs, but i don't know what else i can do

**Comment by jspizziri** [comment]
@elirangoshen please read the comment I left you https://github.com/doublesymmetry/react-native-track-player/issues/1657#issuecomment-1240676311

**Comment by elirangoshen** [comment]
its not working on ios, its not related to android and the nightly build have the same bugs in ios 

please reopen
@jspizziri

**Comment by jspizziri** [comment]
@elirangoshen can you reproduce this in the example app? I was working with this recently and they were working as I'd expect. I'm happy to re-pen, but I want to rule out a problem with things outside of our library first.

**Comment by elirangoshen** [comment]
> @elirangoshen can you reproduce this in the example app? I was working with this recently and they were working as I'd expect. I'm happy to re-pen, but I want to rule out a problem with things outside of our library first.

Ill try it , yet i want to add that in example app react native version is 0.68.1 and in my app is 0.69.1 (:

**Comment by jspizziri** [comment]
That's helpful information. It's possible that it's an issue only in 0.69 which would be important to know.

**Comment by elirangoshen** [comment]
I see.. is it possible that you might check the example on rn 0.69 ?

**Comment by jspizziri** [comment]
We've not yet tested the library yet on rn 0.69. But test on the example with version it has. If it works there then you could upgrade the example to 0.69 and see if the problem starts up.

**Comment by elirangoshen** [comment]
thanks ! issue was on my side
I was configured `notificationCapabilities` on `updateOptions` and it was messing up the background player. 


May I know why ?

**Comment by jspizziri** [comment]
Interesting, notificationCapabilities aren't even used in iOS so that seems quite strange. Were you able to reproduce in the example?
