### ISSUE TITLE
iOS queue stops playing in background randomly. 

### ISSUE THREAD

**Issue by fbotalla** [doublesymmetry/react-native-track-player#1722]
On iOS I cannot play a queue on loop through the night in the background (RepeatMode.Queue). The players stops randomly (after about 10 minutes of playing) with this error from Xcode in the `QueueManager.swift`:

<img width="669" alt="Screen Shot 2022-09-12 at 11 22 27 AM" src="https://user-images.githubusercontent.com/56210704/189761956-fbf15619-7c4e-4a3c-9ec1-95cf5eb7c5af.png">

**Environment Info:**
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 123.38 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/Desktop/sp-rn/node_modules/.bin/yarn
    npm: 8.8.0 - /usr/local/bin/npm
    Watchman: 20220331.150235.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^9.0.0 => 9.1.1 
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.5 => 0.69.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    
This is my `package.json`

**"expo-av": "^12.0.4",**
**"react-native-track-player": "^3.1.0",**
**"react-native": "0.69.5",**

The new arch is NOT enabled.
Tested on a real device in prod mode.

@puckey We touched based on Discord about it.. if you need more info I'm happy to share.

**Comment by puckey** [comment]
I am working on a pull-request of the `SwiftAudioEx` iOS dependency that has a bunch of queue related bug fixes: https://github.com/doublesymmetry/SwiftAudioEx/pull/28

**Comment by puckey** [comment]
Could you provide a fork of this repo with an adjusted example app with a playlist of tracks that demonstrates this issue?

Then I can check if my queue related pr fixes this issue.

**Comment by fbotalla** [comment]
I'll get that to you in the next few days.

**Comment by fbotalla** [comment]
I have been trying to make this bug happen again but I was unsuccessful. Even my code is now working. I did do the upgrade to iOS 16 and everything the queue played all through the night last night. I will continue to poke at this to see if something comes up, but for now I will close the issue. Also with your PR I'm sure everything will be even better. Thanks for the hard work.. this is an amazing library.
