### ISSUE TITLE
Audio is like fluctring, bouncing & jumping.

### ISSUE THREAD

**Issue by ErHarinderSingh** [doublesymmetry/react-native-track-player#1733]
Hi there,

I found a strange issue.
I am on latest nightly build with using RN 0.70.0 (Issue is with both new Arch true & false).
For live streaming URL's it's sometimes fine and sometimes it's fast.
For MP3 URL's it's sometimes normal, sometimes fast & sometimes audio cutting or jumping. For example : 00:00 to 00:02, 02:31 to 02:33.
Why it happens?
Please take it seriously as it's fetching from past 10-15 nightly builds. I was waiting that it will be fixed in this or that. But still no luck and I am still facing this issue.
If audio required, I will create one demo video how audio is behaving.
**Note : I have one more observation that issue is happening if app is in foreground & audio is playing. It is working fine if audio is in background and audio is playing.**

Thanks.

**Comment by ErHarinderSingh** [comment]
@jspizziri ,I think it's hard to explain somehow. Can we connect directly so I can share my screen with you and show exact issue?

**Comment by jspizziri** [comment]
@ErHarinderSingh you can make a screen recording and post it here. Ultimately, if you want us to be able to fix it, you need to provide a way for us to reliably reproduce it. It's impossible for us to fix things we can't reproduce.

**Comment by ErHarinderSingh** [comment]
Hi @jspizziri , no worries. I have resolved it.
But I have something to explain that why it was happening.
I have add this in **android/build.gradle** file

**Comment by mpivchev** [comment]
We removed our ExoPlayer fork recently, and you probably don't need this piece code anymore. Good job on resolving it!

**Comment by ErHarinderSingh** [comment]
My pleasure @mpivchev, 😊
