### ISSUE TITLE
[Feature Request] Rename `reset` to `resetPlaylist` to more accurately describe what the function does

### ISSUE THREAD

**Issue by jspizziri** [doublesymmetry/react-native-track-player#1740]
Created from https://github.com/doublesymmetry/react-native-track-player/issues/1637#issue-1333490271

> Rename reset to resetPlaylist to more accurately describe what the function does. Rename TrackPlayer.stop to TrackPlayer.resetPlaylist as well.
> Note: More descriptive.

**Comment by bradleyflood** [comment]
Hmm. And it also stops playback, which isn't explicitly clear in `resetPlaylist`.

Also, this module doesn't use the word `playlist` much does it? Usually Queue and Track , ie `getQueue()` returns `tracks`, so perhaps it should be renamed to `resetQueue()` or `resetQueueAndStop()` hah

Or, just leave it as `reset()` :P

**Comment by anti-duhring** [comment]
> Hmm. And it also stops playback, which isn't explicitly clear in `resetPlaylist`.
> 
> Also, this module doesn't use the word `playlist` much does it? Usually Queue and Track , ie `getQueue()` returns `tracks`, so perhaps it should be renamed to `resetQueue()` or `resetQueueAndStop()` hah
> 
> Or, just leave it as `reset()` :P
> 
> @anti-duhring 

I like `resetQueue()`, it makes more sense. Hahaha
 
So `resetQueue()` has to reset the playlist but keep playing and `resetQueueAndStop()` has to reset and stop, right? 

I will fix it

**Comment by jspizziri** [comment]
@bradleyflood @anti-duhring ,

I think @mpivchev is proposing that we change the word queue to playlist in all contexts. There's a feature request somewhere relating to that.

**Comment by anti-duhring** [comment]
> @bradleyflood @anti-duhring ,
> 
> I think @mpivchev is proposing that we change the word queue to playlist in all contexts. There are a few other features relating to that.

Oh, I got it. So I keep `resetPlaylist()`? 

It will be something like that:
- `resetPlaylist()` reset the queue but not stops playback
- `resetPlaylistAndStop()` reset the queue and stops playback

@jspizziri

**Comment by puckey** [comment]
we have `TrackPlayer.getQueue()` (and soon we will have `TrackPlayer.setQueue()`)

so how about `TrackPlayer.clearQueue()` which does nothing but remove all tracks from the queue

**Comment by puckey** [comment]
(I guess the same could be done using `TrackPlayer.setQueue([])` soon though)

**Comment by puckey** [comment]
I do agree that `TrackPlayer.reset()` is unclear. For example, by its naming you could reasonably expect it to reset player options too.

@jspizziri what do you think about renaming `TrackPlayer.reset()` to `TrackPlayer.clearQueue()` or deprecate and advise users to use `TrackPlayer.setQueue([])`?

**Comment by jspizziri** [comment]
@puckey that makes sense to me. I'm not sure if there are other intentions about what reset _should_ be doing however. @dcvz ?

**Comment by AronBe** [comment]
Is anybody using `TrackPlayer.setQueue([])` to do the reset? 

**Btw** `setQueue` **is actually missing typescript types**
