### ISSUE TITLE
[Feature Request] Have the audio players automatically handle loss of audio focus

### ISSUE THREAD

**Issue by jspizziri** [doublesymmetry/react-native-track-player#1743]
Created from https://github.com/doublesymmetry/react-native-track-player/issues/1637#issue-1333490271

> Have the audio players automatically handle loss of audio focus - there's a PR for Android already https://github.com/doublesymmetry/KotlinAudio/pull/12 -
> Note: iOS would have to be updated too

**Comment by puckey** [comment]
Done in https://github.com/doublesymmetry/react-native-track-player/pull/1713 – specifically https://github.com/doublesymmetry/react-native-track-player/pull/1713/commits/1126f03ff02b0f60c355faf162cf3728d2db9694

**Comment by jspizziri** [comment]
Closed by https://github.com/doublesymmetry/react-native-track-player/pull/1713
