### ISSUE TITLE
Expo updates reload crashes the app on Android

### ISSUE THREAD

**Issue by Johan-dutoit** [doublesymmetry/react-native-track-player#1745]
**Describe the Bug**

I recently setup expo-updates in my app that uses RNTP and when an update is installed, the app attempts to reload and apply the update, however it crashes.  The update is successfully applied (which can be seen on next startup).

The following errors are logged in sentry (can't guarantee the order), if it helps at all

> Unable to stop service com.doublesymmetry.trackplayer.service.MusicService@5dac82: kotlin.UninitializedPropertyAccessException: lateinit property player has not been initialized

and

> Another SimpleCache instance uses the folder: /data/user/0/com.example/cache/TrackPlayer

**Environment Info:**
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 137.48 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 6.3.1 => 6.3.1 
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

RNTP version: 3.1.0
Real device / Android 12 (does **not** happen on iOS)

**How I can Help**
I can help debug this.

Have you investigated the underlying JS or Swift/Android code causing this bug? No
Can you create a Pull Request with a fix? N/A

**Comment by Johan-dutoit** [comment]
Stack trace for the first error

>**RuntimeException**
android.app.ActivityThread in handleStopService at line 5142
android.app.ActivityThread in access$2300 at line 310
android.app.ActivityThread$H in handleMessage at line 2324
android.os.Handler in dispatchMessage at line 106
android.os.Looper in loopOnce at line 226
android.os.Looper in loop at line 313
android.app.ActivityThread in main at line 8669
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 571
com.android.internal.os.ZygoteInit in main at line 1135

> ** UninitializedPropertyAccessException**
com.doublesymmetry.trackplayer.service.MusicService in onDestroy at line 471
android.app.ActivityThread in handleStopService at line 5122
android.app.ActivityThread in access$2300 at line 310
android.app.ActivityThread$H in handleMessage at line 2324
android.os.Handler in dispatchMessage at line 106
android.os.Looper in loopOnce at line 226
android.os.Looper in loop at line 313
android.app.ActivityThread in main at line 8669
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 571
com.android.internal.os.ZygoteInit in main at line 1135

**Comment by Johan-dutoit** [comment]
and the second

> **IllegalStateException**
com.google.android.exoplayer2.upstream.cache.SimpleCache in <init> at line 249
com.google.android.exoplayer2.upstream.cache.SimpleCache in <init> at line 229
com.google.android.exoplayer2.upstream.cache.SimpleCache in <init> at line 194
com.doublesymmetry.kotlinaudio.players.BaseAudioPlayer in <init> at line 140
com.doublesymmetry.kotlinaudio.players.QueuedAudioPlayer in <init> at line 14
com.doublesymmetry.trackplayer.service.MusicService in setupPlayer at line 81
com.doublesymmetry.trackplayer.module.MusicModule$onServiceConnected$1 in invokeSuspend at line 56
kotlin.coroutines.jvm.internal.BaseContinuationImpl in resumeWith at line 33
kotlinx.coroutines.DispatchedTask in run at line 106
android.os.Handler in handleCallback at line 938
android.os.Handler in dispatchMessage at line 99
android.os.Looper in loopOnce at line 226
android.os.Looper in loop at line 313
android.app.ActivityThread in main at line 8669
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 571
com.android.internal.os.ZygoteInit in main at line 1135

**Comment by jspizziri** [comment]
@Johan-dutoit thanks for the report. Just so you know, no one on the core team is proficient in Expo. We'll probably need someone from the community to help you out here, as to my knowledge, we don't really officially support it.

**Comment by Johan-dutoit** [comment]
@jspizziri thanks for the quick response.  Totally fair comment on your behalf.

This started a bare react native project that I recently added expo unimodules/expo updates.  My lack of expo knowledge/experience and the logs above suggest it's not entirely in the expo realm (apart from maybe how they do a soft reload). Which doesn't allow RNTP to properly initialise again.

**Comment by Johan-dutoit** [comment]
I found these two issue (which mention codepush and not expo), that faced the same.  Although on older versions

- https://github.com/doublesymmetry/react-native-track-player/issues/1044
- https://github.com/doublesymmetry/react-native-track-player/issues/793

**Comment by Johan-dutoit** [comment]
Digging deeper into the expo world, the "soft" reload I talk about above calls `ReactInstanceManager. recreateReactContextInBackground()`, which leads me down the rabbit hole of `tearDownReactContext` and eventually creates a new context.

**Comment by wfern** [comment]
If it can help, I'm having this issue on Android on a bare react-native project with version 0.70.1.

Steps:
Just run on Android, setup the player, etc... then press "R" on metro cli to reload the app. The app will close and in logcat will show the exception: 
```java
2022-09-24 15:14:16.542 18063-18063/com.test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test, PID: 18063
    java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /data/user/0/com.test/cache/TrackPlayer
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:249)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:229)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:194)
        at com.doublesymmetry.kotlinaudio.players.BaseAudioPlayer.<init>(BaseAudioPlayer.kt:153)
        at com.doublesymmetry.kotlinaudio.players.QueuedAudioPlayer.<init>(QueuedAudioPlayer.kt:14)
        at com.doublesymmetry.trackplayer.service.MusicService.setupPlayer(MusicService.kt:92)
        at com.doublesymmetry.trackplayer.module.MusicModule$onServiceConnected$1.invokeSuspend(MusicModule.kt:56)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8163)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@21c1f95, Dispatchers.Main]
```

**Comment by martinmidtsund** [comment]
@jspizziri  I have reproduced this in the example application as well, by reloading with 'R' as above, when running latest  [commit](https://github.com/doublesymmetry/react-native-track-player/commit/54a928be7f1aa3857578943fc8c86e94183806c6)

**Comment by Johan-dutoit** [comment]
I'm still not entirely convinced this is a direct expo issue (it just so happens to be that expo contains the trigger, i.e. a reload).   Perhaps the #296 fix will fix this too.

**Comment by Johan-dutoit** [comment]
I'll test with `react-native-track-player@next` to see if it's been solved as per the comments on that thread.

**Comment by jspizziri** [comment]
@Johan-dutoit it's actually `nightly` not `next`. You can also just install `3.2.0` as that was released last friday.

**Comment by jspizziri** [comment]
The simplecache issue has been addressed in a separate ticket.
