### ISSUE TITLE
If the setupPlayer function is called again, app crash on android phone.

### ISSUE THREAD

**Issue by HyopeR** [doublesymmetry/react-native-track-player#1746]
https://user-images.githubusercontent.com/36919703/191781847-6d99f0c6-f993-4a89-a4da-c0f003a564d9.mp4

**Describe the Bug**
If the setupPlayer function is called for the second time, the application will crash on Android phones. The application is crash quietly and no error message is found. Version 2+ This was not a problem. Maybe we need the destroy function?

**Steps To Reproduce**
Just apply this example in an Android Emulator. [Example]( https://github.com/doublesymmetry/react-native-track-Player/tre/main/example)

**Environment Info:**
Simulator: Android API 30 Nexus 5
Os: MacBook Air (M1, 2020)

```
"react-native-track-player": "^3.1.0",
```

**Comment by jspizziri** [comment]
@HyopeR , please see how to properly configure the player here:

https://github.com/doublesymmetry/react-native-track-player/blob/main/example/src/services/SetupService.ts

**Comment by HyopeR** [comment]
I guess these settings come with version 3.2.0? Waiting for the update, thanks.

**Comment by jspizziri** [comment]
No, this is an example of the code you should write on your end

**Comment by HyopeR** [comment]
I think you misunderstood. AppKilledPlaybackBehavior is a enum not available in version release 3.1.0. I meant to say I'm waiting for a release to be able to configure the service properly.

**Comment by HyopeR** [comment]
Hello again. I am testing version 3.2.0. However, after the simulator is refresh on the android side, the crash continues. I would like to reiterate that I used the [this](https://github.com/doublesymmetry/react-native-track-player/blob/main/example/src/services/SetupService.ts) example here.

**Comment by appfr3d** [comment]
Hello, I can confirm this issue affects me as well. The first run is never a problem, but when I refreshes of the app, it crashes on Android. Users are not affected by the problem as they do not refresh in the same way, but the development experience suffers a lot from this issue.

**Comment by jspizziri** [comment]
It's starting to sound like this issue is a duplicate of https://github.com/doublesymmetry/react-native-track-player/issues/296

Please take a look at that ticket and let me know if you agree.

**Comment by HyopeR** [comment]
Yes, I think it's the same problem. The solutions don't work.

**Comment by jspizziri** [comment]
@HyopeR I'm closing this as a duplicate in that case. Please watch the other ticket.
