### ISSUE TITLE
StopPlaybackAndRemoveNotification fails on second app exit

### ISSUE THREAD

**Issue by jspizziri** [doublesymmetry/react-native-track-player#1759]
Origninally reported by @mmmoussa here https://github.com/doublesymmetry/react-native-track-player/pull/1758

Repro steps:

1. Set `appKilledPlaybackBehavior` to `StopPlaybackAndRemoveNotification`
2. Start playing a track
3. Close the app and note that the music stopped playing and the notification disappeared
4. Open the app and start playing a track
5. Close the app and note that the track continued playing and the notification did not disappear

**Comment by jspizziri** [comment]
This bug is fixed in this PR https://github.com/doublesymmetry/react-native-track-player/pull/1762

**Comment by jspizziri** [comment]
For those of you who need this, please install the `nightly` build that will be released tomorrow morning.

**Comment by SyedTayyabUlMazhar** [comment]
I've found a workaround for this. In **App.js**:

 ```
 useEffect(() =>
  {
    return () => {
      try { TrackPlayer.reset() } catch(){};
    };
  }, []);

```

**Comment by nandhinikala** [comment]
Hey all.. We are looking to use this patch in our build. Could you please update when the next version of the track player will get released? Thanks.

**Comment by jspizziri** [comment]
@nandhinikala You can install **nightly**

**Comment by nandhinikala** [comment]
Thanks @jspizziri . We are after a fixed release instead of a nightly build. Wondering when the next version release is planned?

**Comment by jspizziri** [comment]
@nandhinikala The next release will happen when we feel nightly is ready. This is open source, and we're on the schedule of when code contributors have availability. If you want to expedite that process I encourage you to test and contribute PRs, we'd all be happy to receive them.
