### ISSUE TITLE
Cannot choose between the following variants of org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10:

### ISSUE THREAD

**Issue by yrjwcharm** [doublesymmetry/react-native-track-player#1763]

**Comment by jspizziri** [comment]
I'm not sure what this means, or what the question is. Please provide more detail.

**Comment by danicunhac** [comment]
@yrjwcharm did you end up fixing this one? I'm having the same problem and I believe it's due no specification of `org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10` variant

**Comment by danicunhac** [comment]
@jspizziri

> stderr | * What went wrong:
stderr | A problem occurred configuring project ':react-native-track-player'.
stderr | > Could not resolve all artifacts for configuration ':react-native-track-player:classpath'.
stderr |    > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10.
stderr |      Required by:
stderr |          project :react-native-track-player
stderr |       > Cannot choose between the following variants of org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10:
stderr |           - gradle70JavadocElements
stderr |           - gradle70RuntimeElements
stderr |           - gradle70SourcesElements
stderr |           - javadocElements
stderr |           - runtimeElementsWithFixedAttribute
stderr |           - sourcesElements
stderr |         All of them match the consumer attributes:
stderr |           - Variant 'gradle70JavadocElements' capability org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10:

**Comment by harrysayers** [comment]
I'm also having this issue when building android... any help is appreciated. :)

**Comment by JeffPatricio** [comment]
> Got the build issue fixed in project with RN version 0.64.4 by changing `distributionUrl` in `gradle-wrapper.properties` to `https\://services.gradle.org/distributions/gradle-6.7.1-all.zip` and setting 1.7.0 as version in `classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.0"` in android/build.gradle

works for me, thanks!
