### ISSUE TITLE
[Feature Request] Add the ability to identify and recover from an errored player state.

### ISSUE THREAD

**Issue by bradleyflood** [doublesymmetry/react-native-track-player#1764]
I would like to gracefully handle a loss in network connection. For instance if a user on the train travels through a tunnel and momentary loses internet access.

I have an event listener running on `Event.PlaybackError`...

```
TrackPlayer.addEventListener(Event.PlaybackError, handlePlaybackError);
```

Within which I set my local state and update the UI so that my user see a playback error has occurred...
![Screen Shot 2022-09-29 at 13 44 33](https://user-images.githubusercontent.com/1085976/192933886-f7351506-c7ac-44d5-b1de-e552d82968b7.png)

But how do I recover from this? If the user taps Retry what can I do? I've tried calling:
* `await TrackPlayer.play();` or
* `await TrackPlayer.pause();` and then `await TrackPlayer.play();` or even
* `await TrackPlayer.seekTo(0);`
but none of these methods do anything after the PlaybackError state has been triggered, the Player won't budge and it won't attempt to try again.

Is my only option at this point to reset? `await TrackPlayer.reset();`? 

Is there a way to ask TrackPlayer to resume playing or try again without reseting?

**Comment by bradleyflood** [comment]
For now I'm getting the queue and current index, reseting, and adding the queue back again + skipping to the index it was at.
```js
export const handleErrorRetry = async (): Promise<void> => {
	try {
		const tracks = await TrackPlayer.getQueue();
		const index = await TrackPlayer.getCurrentTrack();
		await TrackPlayer.reset();
		await TrackPlayer.add(tracks);
		if (index && index > 0) {
			await TrackPlayer.skip(index);
		}
		await TrackPlayer.play();
	} catch (e) {
		logger.warn(e);
	}
};
```

But this doesn't help if the user was half way through the audio story and they can't resume. But that's not a big deal :)

**Comment by puckey** [comment]
Coincidentally I am currently working on a PR which will introduce this functionality. I will be introducing `State.ERROR` which means a playback error has occurred. To retry (and seek to the last played time) we could have either `TrackPlayer.reload({ startFromCurrentTime = true })` or we could make it so that another call to `TrackPlayer.play()` would reload automatically when in `State.ERROR`.

What would you prefer? Perhaps the team has thoughts?

**Comment by puckey** [comment]
So this is fixed in https://github.com/doublesymmetry/react-native-track-player/pull/1713

> Implement State.Error which denotes that the player experienced a playback error causing the audio to stop playing (or not start playing). In this state, the return value of TrackPlayer.getPlaybackState() and the payload of the playback state event emitter will include an error property with the error that occurred with message and code properties. The code values are strings prefixed with android_ on Android and ios_ on iOS. When in State.Error, calling play() reloads the current track and seeks to its last known time.

**Comment by bradleyflood** [comment]
Thanks @puckey. I've just reviewed the above PR. Great work. It's still in draft state so I'm assuming you have more to do on it?

**Comment by jspizziri** [comment]
Resolved by https://github.com/doublesymmetry/react-native-track-player/pull/1713
