### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by oliuradu** [doublesymmetry/react-native-track-player#1765]
I am using expo eas build and i get this error.
    "react-native-track-player": "^2.1.3",

> Configure project :react-native-google-mobile-ads
:react-native-google-mobile-ads package.json found at /home/expo/workingdir/build/node_modules/react-native-google-mobile-ads/package.json
:react-native-google-mobile-ads package.json found at /home/expo/workingdir/build/node_modules/react-native-google-mobile-ads/package.json
:react-native-google-mobile-ads:version set from package.json: 8.1.1 (8,1,1 - 8001001)
:react-native-google-mobile-ads:android.compileSdk using custom value: 31
:react-native-google-mobile-ads:android.targetSdk using custom value: 31
:react-native-google-mobile-ads:android.minSdk using custom value: 21
:react-native-google-mobile-ads:reactNativeAndroidDir /home/expo/workingdir/build/node_modules/react-native/android
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Could not determine the dependencies of task ':react-native-track-player:compileReleaseJavaWithJavac'.
[stderr] > Could not resolve all task dependencies for configuration ':react-native-track-player:releaseCompileClasspath'.
[stderr]    > Could not find com.google.android.exoplayer:exoplayer-dash:2.11.4.
[stderr]      Searched in the following locations:
[stderr]        - file:/home/expo/.m2/repository/com/google/android/exoplayer/exoplayer-dash/2.11.4/exoplayer-dash-2.11.4.pom
[stderr]        - file:/home/expo/workingdir/build/node_modules/react-native/android/com/google/android/exoplayer/exoplayer-dash/2.11.4/exoplayer-dash-2.11.4.pom
[stderr]        - file:/home/expo/workingdir/build/node_modules/jsc-android/dist/com/google/android/exoplayer/exoplayer-dash/2.11.4/exoplayer-dash-2.11.4.pom
[stderr]        - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-dash/2.11.4/exoplayer-dash-2.11.4.pom
[stderr]        - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer-dash/2.11.4/exoplayer-dash-2.11.4.pom
[stderr]        - https://www.jitpack.io/com/google/android/exoplayer/exoplayer-dash/2.11.4/exoplayer-dash-2.11.4.pom
[stderr]        - file:/home/expo/workingdir/build/node_modules/react-native-track-player/node_modules/react-native/android/com/google/android/exoplayer/exoplayer-dash/2.11.4/exoplayer-dash-2.11.4.pom
[stderr]      Required by:
[stderr]          project :react-native-track-player
[stderr]    > Could not find com.google.android.exoplayer:exoplayer-hls:2.11.4.
[stderr]      Searched in the following locations:
[stderr]        - file:/home/expo/.m2/repository/com/google/android/exoplayer/exoplayer-hls/2.11.4/exoplayer-hls-2.11.4.pom
[stderr]        - file:/home/expo/workingdir/build/node_modules/react-native/android/com/google/android/exoplayer/exoplayer-hls/2.11.4/exoplayer-hls-2.11.4.pom
[stderr]        - file:/home/expo/workingdir/build/node_modules/jsc-android/dist/com/google/android/exoplayer/exoplayer-hls/2.11.4/exoplayer-hls-2.11.4.pom
[stderr]        - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-hls/2.11.4/exoplayer-hls-2.11.4.pom
[stderr]        - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer-hls/2.11.4/exoplayer-hls-2.11.4.pom
[stderr]        - https://www.jitpack.io/com/google/android/exoplayer/exoplayer-hls/2.11.4/exoplayer-hls-2.11.4.pom
[stderr]        - file:/home/expo/workingdir/build/node_modules/react-native-track-player/node_modules/react-native/android/com/google/android/exoplayer/exoplayer-hls/2.11.4/exoplayer-hls-2.11.4.pom
[stderr]      Required by:
[stderr]          project :react-native-track-player
[stderr]    > Could not find com.google.android.exoplayer:exoplayer-smoothstreaming:2.11.4.
[stderr]      Searched in the following locations:
[stderr]        - file:/home/expo/.m2/repository/com/google/android/exoplayer/exoplayer-smoothstreaming/2.11.4/exoplayer-smoothstreaming-2.11.4.pom
[stderr]        - file:/home/expo/workingdir/build/node_modules/react-native/android/com/google/android/exoplayer/exoplayer-smoothstreaming/2.11.4/exoplayer-smoothstreaming-2.11.4.pom
[stderr]        - file:/home/expo/workingdir/build/node_modules/jsc-android/dist/com/google/android/exoplayer/exoplayer-smoothstreaming/2.11.4/exoplayer-smoothstreaming-2.11.4.pom
[stderr]        - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-smoothstreaming/2.11.4/exoplayer-smoothstreaming-2.11.4.pom
[stderr]        - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer-smoothstreaming/2.11.4/exoplayer-smoothstreaming-2.11.4.pom
[stderr]        - https://www.jitpack.io/com/google/android/exoplayer/exoplayer-smoothstreaming/2.11.4/exoplayer-smoothstreaming-2.11.4.pom
[stderr]        - file:/home/expo/workingdir/build/node_modules/react-native-track-player/node_modules/react-native/android/com/google/android/exoplayer/exoplayer-smoothstreaming/2.11.4/exoplayer-smoothstreaming-2.11.4.pom
[stderr] Required by:
[stderr]          project :react-native-track-player
[stderr]    > Could not find com.google.android.exoplayer:exoplayer-core:2.11.4.
[stderr]      Required by:
[stderr]          project :react-native-track-player
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 4m 23s

**Comment by jspizziri** [comment]
@oliuradu please upgrade to the newest version. If that doesn't work please create a reproduction based off of the example project.
