### ISSUE TITLE
Build eas expo ios failed

### ISSUE THREAD

**Issue by oliuradu** [doublesymmetry/react-native-track-player#1766]
version:3.2.0

Using Expo modules
2
Auto-generating `.xcode.env.local` with $NODE_BINARY=/Users/expo/.nvm/versions/node/v16.13.2/bin/node
3
Adding a custom script phase for Pod RNGoogleMobileAds: [RNGoogleMobileAds] Configuration
4
Auto-linking React Native modules for target `iBac`: RNCAsyncStorage, RNGestureHandler, RNGoogleMobileAds, RNImageColors, RNPurchases, RNSVG, RNScreens, RNSentry, lottie-react-native, react-native-fbsdk-next, react-native-pager-view, react-native-render-html, react-native-safe-area-context, react-native-slider, react-native-track-player, and react-native-webview
5
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
6
Analyzing dependencies
7
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
8
[Codegen] Found FBReactNativeSpec
9
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
10
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
11
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
12
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
13
[!] CocoaPods could not find compatible versions for pod "SwiftAudioEx":
14
  In snapshot (Podfile.lock):
15
    SwiftAudioEx (= 0.14.7)
16
  In Podfile:
17
    react-native-track-player (from `../node_modules/react-native-track-player`) was resolved to 3.2.0, which depends on
18
      SwiftAudioEx (= 0.15.3)
19
You have either:
20
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
21
 * changed the constraints of dependency `SwiftAudioEx` inside your development pod `react-native-track-player`.
22
   You should run `pod update SwiftAudioEx` to apply changes you've made.
23
Error: Compatible versions of some pods could not be resolved.
You are seeing this error because either:
  - Versions in the Podfile.lock cached by EAS do not match required values in Podspecs of some of the libraries. To fix that add the "cache.key" field (it can be set to any value) in the build profile in eas.json to invalidate the cache.
  - Some of the pods used in your project depend on different versions of the same pod. See logs for more information.

**Comment by jspizziri** [comment]
This is a problem with your project podfile.lock. Not out library.

**Comment by oliuradu** [comment]
If i uninstall the react-native-track-playe is working.

**Comment by jspizziri** [comment]
Please read the exception. It tells you exactly what's going on.

**Comment by closetothe** [comment]
yeah, I got this too. not sure exactly how to fix this though since maybe there's some incompatibility with expo after upgrading to 3.2.0
