### ISSUE TITLE
Execution failed for task ':app:checkDebugAarMetadata'.

### ISSUE THREAD

**Issue by Minhaj-beep** [doublesymmetry/react-native-track-player#1767]
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction       
   > One or more issues found when checking AAR metadata values:

     Dependency 'androidx.core:core:1.9.0' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':app' is 'android-31'

     Dependency 'androidx.core:core-ktx:1.9.0' requires 'compileSdkVersion' to be set to 33 or higher.        
     Compilation target for module ':app' is 'android-31'

     Dependency 'androidx.annotation:annotation-experimental:1.3.0' requires 'compileSdkVersion' to be set to 
33 or higher.
     Compilation target for module ':app' is 'android-31'

The above error occurs every time I am trying to install react native track player, even on a bare project. I didn't understand why is it happening or neither any of the online available solution helped.  Can anybody help me to solve the issue.

**Comment by jspizziri** [comment]
It says it right in the error message. You need to update your conpileSdk to 33 or higher

**Comment by RamProg** [comment]
I'm getting the same error. It's not described in the README that RNTP 3.2.0 requires compileSdkVersion 33 or higher. So either there's an unknown issue or it needs to be added to the migration steps: https://react-native-track-player.js.org/docs/v3.1.0-migration

**Comment by jspizziri** [comment]
@RamProg if you'd like to submit a PR to the 3.1->3.2 migration docs I'd review it and merge it.

**Comment by rahulMile9** [comment]
why am I getting this error? anyone can help??

![image](https://github.com/user-attachments/assets/06468305-86ff-4a3c-a42b-f72beb328a46)
