### ISSUE TITLE
Event.PlaybackTrackChanged trigger twice or more both platform

### ISSUE THREAD

**Issue by ithustle** [doublesymmetry/react-native-track-player#1769]
**Describe the Bug**
When added a playlist on queue, on first run, its works as expected, after `.reset()` and added a new playlist, the `Event.PlaybackTrackChanged` or `useTrackPlayerEvents` trigger twice.

**Steps To Reproduce**
1. Touch to a new list of track to add on queue with a playlist playing;
2. The queue is reseted and added a new list of tracks;
3. On `TrackPlayer.addEventListener(Event.PlaybackTrackChanged, async event => { console.log() }` the console log will trigger twice or more.

**Code To Reproduce**
```

await TrackPlayer.reset();
await TrackPlayer.add([...tracklist[0]]);
// When state go to `ready`
await TrackPlayer.play();
```

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)?

**Environment Info:**

```
System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 45.95 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.20.0/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
    Watchman: 2022.09.12.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/celiogarcia/.rvm/rubies/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

`RNTP 3.2.0`
Real device ANDROID and emulator

**How I can Help**
- Example project also have the same behavior 
- I've double checked on `MusicService.kt` and I realize that it trigger twice on same behavior as I explain above.

**Comment by JanKhstll** [comment]
For me this issue also appears with Android Emulator and RNTP 3.1.0.

**Comment by puckey** [comment]
just verified this isn't occurring in https://github.com/doublesymmetry/react-native-track-player/pull/1713 – which should be included in the next major release

**Comment by jspizziri** [comment]
Closed by https://github.com/doublesymmetry/react-native-track-player/pull/1713
