### ISSUE TITLE
v3.2 requires us to upgrade the android target & compileSDK

### ISSUE THREAD

**Issue by WrRaThY** [doublesymmetry/react-native-track-player#1772]
**Describe the Bug**
it's all described very well by @trm217 here: https://github.com/doublesymmetry/react-native-track-player/discussions/1761
I just believe it's a bug as opposed to a Q&A question.
the need to upgrade was not described in the migration guide and it's proving to be hard to work with the ecosystem (namely - expo).
Another thing is - even if I downgrade to 3.1 or use 3.2 and remove `expo-dev-client` from my deps - the app still shuts down with no logs, so there is no way for me to know why. It ONLY does it if RNTP is added as a dep.

**Steps To Reproduce**
```
npx create-expo-app rntp-test-app
npx expo install react-native-track-player
expo run:android
```

**Code To Reproduce**
`expo run:android`

**Replicable on Example App?**
not using the example app - it's way simpler to just follow the three steps mentioned above
https://github.com/WrRaThY/rntp-test-app

**Environment Info:**
Paste the results of `npx react-native info`
```
$ npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 9.31 GB / 31.42 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.12 - C:\Users\wooha\.sdkman\candidates\java\current\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.6 => 0.69.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```
Paste the exact `react-native-track-player` version you are using
3.2
Real device? Or simulator?
real device
What OS are you running?
Windows 11

**How I can Help**
What can you do to help resolve this?
not sure, but I'm open to helping ;p

Have you investigated the underlying JS or Swift/Android code causing this bug?
well it's because of the SDK upgrade to version 33. it doesn't really work well with `expo-dev-client` - the result is
```
rntp-test-app\node_modules\expo-dev-menu\vendored\react-native-gesture-handler\android\devmenu\com\swmansion\gesturehandler\PanGestureHandler.kt: (57, 36): Type mismatch: inferred type is Context? but Context was expected
```

Can you create a Pull Request with a fix?
not really. I'm not quite sure why the upgrade was made in the first place. was is mandatory somehow?

**Comment by jspizziri** [comment]
I'm closing this as a duplicate. You can find more information on it here: https://github.com/doublesymmetry/react-native-track-player/issues/1767#issuecomment-1267156549

The short version is that we're aware of it. Bumping the `compileSdk` to `33` is what you'll need to do at least for the time being, but it might be come mandatory. The compileSdk shouldn't affect anything but your build environment.

**Comment by WrRaThY** [comment]
some bonus info:
- after I bumped the sdk to `33` and removed `expo-dev-client` from the project (it will delay me a bit, but oh well...) I was getting a successful build and a random shutdown
- I did some testing and looks like if I don't load sounds through `expo-av` - it works fine

maybe it will help someone

cheers

**Comment by jspizziri** [comment]
@WrRaThY thanks for the additional info. This is strange. I wonder if it has more to do with conflicting versions of ExoPlayer than anything else (in case you're interested in investigating)
