### ISSUE TITLE
Duplicate expoplayer class 2.2.0rc1

### ISSUE THREAD

**Issue by Ellathet** [doublesymmetry/react-native-track-player#1773]
**Describe the Bug**
When using:
```
react-native-video: 5.2.1
react-native-track-player: 2.0.0rc1
```

2.0.01rc1 version, is for Sdk 31 version, in this  [issue](https://github.com/doublesymmetry/react-native-track-player/issues/1526)

**Steps To Reproduce**
Using react-native run-android

**Bug Log**:
![image](https://user-images.githubusercontent.com/76699403/193925299-e3cc5775-16cb-4b20-9b57-a842dbd7fb8f.png)

**Environment Info:**
Using my phone, and this system and libraries information.
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 902.64 MB / 7.83 GB
  Binaries:
    Node: 12.22.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.15 
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: Not Found
  Languages:
    Java: 11.0.15 - /c/Program Files/OpenJDK/openjdk-11.0.15_10/bin/javac
    Python: 3.10.5 - /c/Users/socia/AppData/Local/Programs/Python/Python310/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by jspizziri** [comment]
Please upgrade to 3.2

**Comment by Ellathet** [comment]
When I upgrade to version 3.2 i have problem with kotlin version. My solution is, put kotlin version in `1.6.0` both in my gradlew and `react-native-track-player` builds, like this:

```groovy
// my build.gradlew
buildscript {
    ext {
        kotlinVersion = "1.6.0"
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
```

```groovy
//react-native-track-player build.gradlew
buildscript {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${rootProject.ext.get('kotlinVersion')}"
    }
}
```

The APP install now, but, when start it's close, and return this error in logcat:

![image](https://user-images.githubusercontent.com/76699403/193976548-5850c777-2004-4a88-9ad2-630a574ea0f3.png)

```
10-05 00:39:34.416  5846  6242 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.Player$EventListener" on path: DexPathList[[zip file "/data/app/~~L54cJiHK-6vdMnISsAa4zA==/br.com.forbesplus-OMqy95KKw2EyTizCbMWMgA==/base.apk"],nativeLibraryDirectories=[/data/app/~~L54cJiHK-6vdMnISsAa4zA==/br.com.forbesplus-OMqy95KKw2EyTizCbMWMgA==/lib/arm64, /data/app/~~L54cJiHK-6vdMnISsAa4zA==/br.com.forbesplus-OMqy95KKw2EyTizCbMWMgA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
10-05 00:39:34.526  1254  8133 I vendor.qti.hardware.servicetracker@1.2-service: bindService is called for service : com.google.android.gms/.measurement.service.MeasurementBrokerService and for client br.com.forbesplus
10-05 00:39:34.526  1254  8133 I vendor.qti.hardware.servicetracker@1.2-service: total connections for client : br.com.forbesplusare :2
10-05 00:39:34.554  1949  5315 W ActivityTaskManager:   Force finishing activity br.com.forbesplus/br.com.wideedu.MainActivity
```

**Comment by jspizziri** [comment]
Looks like you might have the issue of conflicting exoplayer versions. In any cases, RC releases aren't supported so you should focus on fixing your upgrade issue.

**Comment by Ellathet** [comment]
For who need the old version (1.2.7) of `react-native-track-player`, I forked it changing needs to run on SDK 31, just add this in your package.json:

```json
"dependencies": {
    "react-native-track-player": "https://github.com/Ellathet/react-native-track-player.git",
}
```
