### ISSUE TITLE
[Feature Request] Remove setupPlayer

### ISSUE THREAD

**Issue by puckey** [doublesymmetry/react-native-track-player#1782]
Looking at the sample code in the example app, the details of the [setup player logic](https://github.com/doublesymmetry/react-native-track-player/blob/main/example/src/services/SetupService.ts) feel like they should probably be handled internally by `RNTP`: It checks if the player was not set up before by calling a random TrackPlayer function and catching when it throws due to not being setup, because calling `TrackPlayer.setupPlayer()` more than once will throw.

What functionality in `setupPlayer` is there that can't be updated after the player has been setup? From a quick glance I think we could implement all of the options there into `TrackPlayer.setOptions()` and remove `TrackPlayer.setupPlayer()`. Then have the native side setup the player automatically whenever it was not set up already.

For end users this would mean:
- less throwing / catching
- not having to keep track of state that denotes whether the player is set up or not
- less async spaghetti

**Comment by jspizziri** [comment]
@puckey I agree with handling some of the implementation details in the lib. One thing to consider is that some users want to control when the player is setup as their app does more than just audio. An example of this is people who don't want a notification player to show up in android until the last moment before the user asks for audio.

**Comment by puckey** [comment]
@jspizziri I might be mistaken, but doesn't it take a track being added to the queue for the notification player to show up?

**Comment by jspizziri** [comment]
@puckey probably needs testing. There was a user who encountered this and they said that not calling `setupPlayer` until they needed it worked for them.
