### ISSUE TITLE
[Feature Request] Allow native level sampling of audio buffer for realtime amplitude

### ISSUE THREAD

**Issue by fogg4444** [doublesymmetry/react-native-track-player#1783]
**What is the need and use case of this feature?**
I'm attempting to create an audio visualizer which renders audio amplitude in realtime during playback.

**Describe the ideal solution**
During playback, RNTP will allow access to the native audio buffer by way of a query function, something like `getAudioAmplitude()`. This would allow custom native code an easy hook to querying audio amplitude at a desired framerate, without excessively complicating RNTP. A simple utility function of this variety would allow all manner of live visualization functionality to be integrated with RNTP.

**Describe alternatives you've considered**
No alternatives that I'm aware of.

**Additional context**

**How I can Help**
I'm interested in implementing the feature on iOS and Android. I have experience with native level development in React Native context.

**Comment by jspizziri** [comment]
@fogg4444 this seems like a great feature to me! I would say if you're interested in doing the implementation we'd be interested in adding it to the library.

@dcvz would need to agree since he has final say on all such decisions.

**Comment by jspizziri** [comment]
@fogg4444 it looks like you're a go for implementation. Are you planning on working on this in the near future? If not I'm going to close it and put it in the feature backlog.

**Comment by bradleyflood** [comment]
@jspizziri Can you please add to feature backlog? (I don't have perms in that project I think)

**Comment by smblee** [comment]
@jspizziri looks like this issue has been resolved 3 years ago – was this actually implemented?

**Comment by jspizziri** [comment]
No, it was not implemented.

**Comment by smblee** [comment]
@jspizziri if you could give guidance, i would love to give it a shot! I should probably mess with the https://github.com/doublesymmetry/SwiftAudioEx for iOS so i could expose and tap into `AVAudioEngine`'s mixer/output nodes?
