### ISSUE TITLE
[Feature Request] Run special track in track list

### ISSUE THREAD

**Issue by hungdev** [doublesymmetry/react-native-track-player#1785]
Can we have a feature: Run a special track in the tracklist?
For example: TrackPlayer.play(3); => run track number 3 in list 5 tracks
If there is a track playing, then it will cancel the current track and play a special track, in this case, track number 3.

**Comment by jspizziri** [comment]
This already exists

https://react-native-track-player.js.org/docs/api/functions/queue#skipindex-initialposition
