### ISSUE TITLE
[Feature Request] add a stop method

### ISSUE THREAD

**Issue by jspizziri** [doublesymmetry/react-native-track-player#1786]
add back the previously removed `stop` function:

> Also, if I could figure out how to wipe the player clean completely of any previous live stream (as mentioned in my post above) then I wouldn’t need to access the buffered value in the listener. Do you know of a better way of doing this at all? Pausing the player and removing the track doesn’t work as when you press play again it just picks up where the stream left off even though you’ve reset the queue. Hope that makes sense

https://discord.com/channels/567636850513018880/600714011318681610/1028278936301482064

**Comment by puckey** [comment]
Implemented in https://github.com/puckey/react-native-track-player/commit/1bc919bc89b435f35ef1896063f9206037632c29

**Comment by jspizziri** [comment]
Closed by https://github.com/doublesymmetry/react-native-track-player/pull/1713
