### ISSUE TITLE
How to disable auto play next track?

### ISSUE THREAD

**Issue by hungdev** [doublesymmetry/react-native-track-player#1787]
Hi, thank the team a lot.
I have a question, how to disable auto-play next track?
I have some tracks on the list. So it seems auto-play the next track, so I want it play only one track and then end up without playing the next track.
Thank you.

**Comment by kaanoner3** [comment]
@hungdev I think you can use the PlaybackTrackChanged event. When it is triggered, you can pause the song. Not sure if it is the best way to handle such a case though

**Comment by puckey** [comment]
In this case, why not have only a single track in the queue at a time?

**Comment by hungdev** [comment]
@puckey  When the file has finished running, or the file is running but paused, I use getState() to get the status, it always returns "paused". And when I want to replay that audio file, I need to re-add that audio. But the problem is that I don't know if its status is finished running or running but paused to decide to add it again.

**Comment by puckey** [comment]
When the following pr is merged we will also have `State.Ended` to denote playback having ended due to reaching the end of the queue: https://github.com/doublesymmetry/react-native-track-player/pull/1713

**Comment by jspizziri** [comment]
closing in favor of this feature request https://github.com/doublesymmetry/react-native-track-player/issues/1801
