### ISSUE TITLE
[Feature Request] Ensure to set AudioSession configuration on iOS.

### ISSUE THREAD

**Issue by Spice-Z** [doublesymmetry/react-native-track-player#1790]
**What is the need and use case of this feature?**

As you know on iOS, background music behavior is defined by [AVAudioSession configuration](https://developer.apple.com/documentation/avfaudio/avaudiosession/category).
In current RNTP(v3.2), this category is set only when `setupPlayer`  is called.
This means when other libraries set category after `setupPlayer` , the music background behavior will be change!

Detail example
- `setupPlayer` is called when app's initialization
- Play music by RNTP (this time expected behavior)
- Play sounds by other libraries (like react-native-sound or react-native-video)
- Play music by RNTP => this time unexpected behavior, if other libraries set other params

**Describe the ideal solution**

~~Set the AudioSesssion's params that was passed when `setupPlayer` was called at every time  when `play` method is called.~~

Enable to set AudioSesssion's params by `updateOptions` method.

**Additional context**
I found this problems in my company's production app code.

**How I can Help**

I made experimental PR!😃

~~https://github.com/doublesymmetry/react-native-track-player/pull/1789~~

I will make PR in a few days.

**Comment by puckey** [comment]
How about adding `iosCategory`, `iosCategoryMode`, `iosCategoryOptions` as options to `TrackPlayer.updateOptions()` instead?

**Comment by Spice-Z** [comment]
> How about adding iosCategory, iosCategoryMode, iosCategoryOptions as options to TrackPlayer.updateOptions() instead?

I didn't think about this.
And that is better!
