### ISSUE TITLE
SimpleCache IllegalStateException when bundle reloading via CodePush

### ISSUE THREAD

**Issue by rossyman** [doublesymmetry/react-native-track-player#1794]
**Describe the Bug**

When a bundle is reloaded on Android devices via [`react-native-code-push`](https://github.com/microsoft/react-native-code-push) (A very popular react-native library created by Microsoft and used by many organisations), TrackPlayer fails to reset the SimpleCache lock.

This occurs because while the app is technically restarted, the underlying native code is not. Since the `.destroy()` functionality is no longer exposed to the application via the native module, we can no longer workaround this problem by manually clearing up resources on Code-Push.

Any attempt to reload Android via Code-Push after calling `setupPlayer` results in the following error:

```bash
FATAL EXCEPTION: main
Process: <PACKAGE_NAME>, PID: 32249
java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /data/user/0/<PACKAGE_NAME>/cache/TrackPlayer
    at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:249)
    at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:229)
    at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:194)
    at com.doublesymmetry.kotlinaudio.players.BaseAudioPlayer.<init>(BaseAudioPlayer.kt:153)
    at com.doublesymmetry.kotlinaudio.players.QueuedAudioPlayer.<init>(QueuedAudioPlayer.kt:14)
    at com.doublesymmetry.trackplayer.service.MusicService.setupPlayer(MusicService.kt:92)
    at com.doublesymmetry.trackplayer.module.MusicModule$onServiceConnected$1.invokeSuspend(MusicModule.kt:56)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6944)
```

**Steps To Reproduce**
- Spin up the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)
- Implement `react-native-code-push`
- Attempt to install an update via Code-Push after `setupPlayer` has been called (Even with the appropriate `try {} catch {}` in place around `await TrackPlayer.getCurrentTrack();`)
- Wait for CodePush to finish installing the new bundle
- App crashes
- Upon restarting the app, it all works fine again with the new bundle, as the native code has released the cache

**Code To Reproduce**
- Spin up [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)
- Perform [Code Push Android Installation](https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md) (Steps 1 to 4)

**Environment Info:**
```
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 535.66 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/lib/ruby/gems/3.1.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 28, 30, 31, 33
      Build Tools: 29.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Electric Eel 2022.1.1 Beta 1 Electric Eel 2022.1.1 Beta 1
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.1 => 0.70.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- Using `react-native-track-player@v3.2.0`
- Using `KotlinAudio@v1.2.4`
- Running on a real Samsung Galaxy s7 (API 26)
- **Device**: Android 8.0 / Samsung Experience 9.0

**How I can help**

Since the `.destroy()` mechanism was removed in a previous release, I don't want to raise a PR here that might directly conflict with the intentions of the library; that being said, we do need some way to resolve this caching issue and exposing this mechanism directly to the consuming developers seems like the least troublesome solution to this issue.

**Relates to**

While the issues listed below are related, they do not correlate 1:1 with this issue:
- https://github.com/doublesymmetry/react-native-track-player/issues/1745
- https://github.com/doublesymmetry/react-native-track-player/issues/1718
- https://github.com/doublesymmetry/react-native-track-player/issues/296

**Comment by appfr3d** [comment]
Im facing the same problem, and from what I can tell, your CodePush problem correlates with the hot reload problem. It seems like it was fixed in [this pr](https://github.com/doublesymmetry/KotlinAudio/pull/53), but seeing that [this comment](https://github.com/doublesymmetry/react-native-track-player/issues/296#issuecomment-1265317946) has not received any updates yet, I guess we just got to wait 🤷‍♂️ Maybe this issue will make some more traction to get an ETA on the next release?

**Comment by jspizziri** [comment]
Closing as a duplicate

https://github.com/doublesymmetry/react-native-track-player/issues/296#issuecomment-1259598282

**Comment by rossyman** [comment]
@jspizziri I mentioned in the issue, that we *ARE* using the most recent version of KotlinAudio (At the time of writing, it's `v1.2.4`) and this issue has still not been resolved -- Makes sense if the fix hasn't been released yet (Merged circa 17 days ago).

If this resolution is still to come in a future release of `KotlinAudio` and `RNTP` could you specify what version of `RNTP` you expect to contain this targeted fix so I can track when to perform the upgrade on my side?

**As of right now**, this is still a breaking change for many applications, and until the release is done, I believe the Issue should remain open for tracking purposes, unless you have a different definition of "Done".

Some information on an ETA would be very useful to those of us who have to report to Business Analysts why we've got regression in our application that requires hacky workarounds on Android that ultimately degrades UX.

**Comment by jspizziri** [comment]
@rossyman this fix will go out in the next patch release. If you need a workaround before then please look at the above comments.

We track work via our GitHub project board. This issue will remain closed based on our process. Thanks.
