### ISSUE TITLE
next() & previous() behave differently on iOS and Android

### ISSUE THREAD

**Issue by puckey** [doublesymmetry/react-native-track-player#1796]
On android the `TrackPlayer.previous()`method will first seek to the start of the current track if its current time is larger than 3 seconds.. only on the second click will it seek to the previous track. This is different from the way the docs state things work and the way iOS works: "Skips to the previous track in the queue."

**Comment by erik-lissen** [comment]
skipToPrevious - this is an issue for us as well.

We're on 3.2 - can't upgrade to 3.3 because of expo and the minSdkVersion issue.

On android, there is no way to tell wether the user has replayed the same track or switched to a new one as it only fires the 'state-changed' event, and the state changes are exactly the same sequence as if they switched to a different track.
state - 3  | progress 0 | state 2

potential fix would be to make sure the track-changed event fires in this case, or better yet, allow us to control the behaviour of this function

**Comment by puckey** [comment]
It seems that before the kotlin rewrite the functionality on android was the same as iOS. On android the skipToPrevious method was:

```java
    public void skipToPrevious(Promise promise) {
        int prev = player.getPreviousWindowIndex();

        if(prev == C.INDEX_UNSET) {
            promise.reject("no_previous_track", "There is no previous track");
            return;
        }

        lastKnownWindow = player.getCurrentWindowIndex();
        lastKnownPosition = player.getCurrentPosition();

        player.seekToDefaultPosition(prev);
        promise.resolve(null);
    }
```

now it is in kotlinaudio:
```
    fun previous() {
        exoPlayer.seekToPrevious()
    }
```

where seekToPrevious according to exoplayer docs:
> Seeks to an earlier position in the current or previous [MediaItem](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.html) (if available). More precisely:
> If the timeline is empty or seeking is not possible, does nothing.
> Otherwise, if the current [MediaItem](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.html) is [Player.isCurrentMediaItemLive()](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#isCurrentMediaItemLive()) live} and [unseekable](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#isCurrentMediaItemSeekable()), then:
> If [a previous media item exists](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#hasPreviousMediaItem()), seeks to the default position of the previous media item.
> Otherwise, does nothing.
> Otherwise, if [a previous media item exists](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#hasPreviousMediaItem()) and the [current position](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#getCurrentPosition()) is less than [Player.getMaxSeekToPreviousPosition()](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#getMaxSeekToPreviousPosition()), seeks to the default position of the previous [MediaItem](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.html).
> Otherwise, seeks to 0 in the current [MediaItem](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.html).

Instead, we should probably be using `exoPlayer.seekToPreviousMediaItem()`, which behaves the same as our iOS implementation.

More on this soon..

**Comment by puckey** [comment]
Will be fixed in https://github.com/doublesymmetry/react-native-track-player/pull/1713 – see underlying changes in KotlinAudio: https://github.com/doublesymmetry/KotlinAudio/pull/50/commits/ab2dfc5d9dbbbf6376fab331b677396e9d1d34c3
