### ISSUE TITLE
Android: react-native-track-player version 3.2.0 is not working.

### ISSUE THREAD

**Issue by bipin-sakariya** [doublesymmetry/react-native-track-player#1799]
**Describe the Bug**
Android configuration :
compileSdkVersion= 33, kotlinVersion= 1.6.0, minSdkVersion= 21
**Steps To Reproduce**
How can someone else reproduce this bug?

**Code To Reproduce**
Please provide a simple code example that allows others to replicate the bug.

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)?

**Environment Info:**
Paste the results of `npx react-native info`
Paste the exact `react-native-track-player` version you are using
Real device? Or simulator?
What OS are you running?

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

**Comment by jspizziri** [comment]
Closing. Doesn't conform to the template.
