### ISSUE TITLE
Can't access duration value for of ProgressComponent 

### ISSUE THREAD

**Issue by hassanbadru** [doublesymmetry/react-native-track-player#180]
The value being returned stays as zero no matter what, either by using this.state.duration or calling Track.getDuration() elsewhere.

Within my render function, I console logged the values of both position and duration after I began playing a track. The track is being loaded from network.

Here is ProgressComponent:

```
 class MyPlayerBar extends TrackPlayer.ProgressComponent {
       render() {

           const position = this.state.position;
           const duration = this.state.duration;

           console.log(position)
           console.log(duration)

        return (
            <View style={{flex: 1}}>
              <ProgressViewIOS
                progress={this.getProgress()}
                progressTintColor={'blue'}
                trackTintColor={'#eee'}
              />
            </View>
              );

          }

      }
```

Here is my output using the debugger:

![image](https://user-images.githubusercontent.com/13846712/38830099-35a1033a-4189-11e8-8b6b-ad0411da0b13.png)

I have done everything right, everything else seems to work perfectly, including other track functions. I just can't access the value of duration, hence the getProgress() always returns zero for the Progress Bar.

This only happens when I load from network, I don't experience when loading from bundle.

I'm still wondering and trying to figure out why this could be happening.

**Comment by mmuil** [comment]
@hassanbadru What was the issue with your bundle? I'm facing similar issue where TrackPlayer.getDuration and this.duration are unusable in ProgressComponent. I'm also using network files.

**Comment by ntk860** [comment]
@hassanbadru how did you solve this problem ?
