### ISSUE TITLE
Android Event.RemoteDuck only called once when permanent is true

### ISSUE THREAD

**Issue by billymatchbox** [doublesymmetry/react-native-track-player#1800]
**Describe the Bug**
On Android, the Event.RemoteDuck is not called again once it has been called with permanent as true. 

**Steps To Reproduce**
Run the Track Player Example on android 

1. Start Listening to audio
2. Switch away leaving the audio playing
3. Run YouTube and start watching a video, Event.RemoteDuck is triggered with permanent set to true, TrackPlayer.pause() executes, audio pauses, and the YouTube video can be heard
4. Pause YouTube video
5. Pull down the notification panel, and press play to to listen to the Track Player Example App again.
6. Return to the YouTube video and resume it.

Result: Both audios can be heard. Event.RemoteDuck is not called again. 

It doesnt have to be YouTube, it can be another Audio Player. Anything that would trigger Event.RemoteDuck  with permanent set to true.

You can also get 2 audio's playing, by following the above steps, skipping step 4. In this case playing the Track Player Example App audio again, doesnt result in the youtube video being paused. 

**Code To Reproduce**
Reproducible in the React Native Track Player Example App

**Replicable on Example App?**
Yes

**Environment Info:**
System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 959.67 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2022.09.19.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/billy/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      Android NDK: 22.0.6917172-beta1
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.0 => 0.68.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Paste the exact `react-native-track-player` version you are using

3.2.0
also tried
^3.2.0-d23c3fb990aaf9d6783881fabe21e059b62b0782

Real device? Or simulator?
Real Device

What OS are you running?
Android 9

**How I can Help**
I have looked at the react-native-track-player library code. I couldn't see any obvious reason this would happen. Looks like it maybe in com.doublesymmetry.kotlinaudio.players.QueuedAudioPlayer library.

**Comment by micmor-9** [comment]
I'm having the same issue, the event is detected only the first time, then on the second remote-duck the audio from my application mixes up with the audio from the application that has generated the duck.

Is there any workaround at the moment?

**Comment by billymatchbox** [comment]
@micmor-9 I worked round this by calling reset, instead of pause if Plaform.os is android. Not ideal but it got passed the issue for now.

**Comment by micmor-9** [comment]
@billymatchbox thanks, and how do you handle it in ios?

**Comment by billymatchbox** [comment]
@micmor-9 Its works OK in ios, so I call pause.

**Comment by micmor-9** [comment]
@billymatchbox it isn't working for me on ios, it isn't detecting the event at all, even if i just put a console log in the listener to RemoteDuck, it won't print on the Metro console. I've tried to listen to the event both from the PlaybackService and also with the useTrackPlayerEvents hook but nothing is triggered

**Comment by mikeleruo** [comment]
@billymatchbox @micmor-9  Are there any updates on this? I'm having the same issue.

**Comment by YDaskaloff** [comment]
are there any updates? Facing the same issue

**Comment by zerobertelprivat** [comment]
Hello, i am facing the same issue on android, Google Pixel 4a

**Comment by akshay3794** [comment]
Is there any update? Facing the same issue on android only
