### ISSUE TITLE
[Feature Request] Pause Between Songs/Autoplay

### ISSUE THREAD

**Issue by KfWelch** [doublesymmetry/react-native-track-player#1801]
**What is the need and use case of this feature?**
The need for this feature is when the user wants the track player to pause after every track finishes playing, while maintaining a full playlist being stored in the queue.  A potential use case for this is to provide a random wait time before playing the next track.

**Describe the ideal solution**
Ideally, there would be a function similar to `setRepeatMode()`, which allows for the user to set an option called pauseBetweenTracks or perhaps autoPlay (courtesy Chris Dosé from discord for this variable name).  Depending on if it is set, the track player will pause after a track reaches completion without starting the next track.

**Describe alternatives you've considered**
An alternative solution that I have had in mind is to have an event, similar to PlaybackTrackChanged, but instead fires when a track has finished playing (likely to have a name such as PlaybackTrackEnded).  However, due to how close in time the two events would be, it could be seen as redundant.

**Additional context**
I have attempted to use `Event.PlaybackTrackChanged` as a solution, however, with this method, the processing that happens before `TrackPlayer.pause();` is called means that some of the next track begins playing.  For some songs which start out loudly, this is very noticeable.

**How I can Help**

While I have experience in both Java and in RN, I do not have much experience in Android Studio development using Java.  Therefore, if I were to assist in development, I would need onboarding assistance.  I also do not have experience in iOS programming, and as such I would not be able to help with that side of this feature.

However, I should be able to assist in testing the feature; having a workflow in my app that would rely on it.

This feature request is seconded by atefyamin#7501 on Discord

**Comment by jspizziri** [comment]
I think having an `autoplay: boolean` property that's passable to `updateOptions` would be a good idea. @dcvz @puckey thoughts?

@KfWelch , @dcvz will have the final say on if this is going to be approved to add to the lib. However, I will say the implementation would largely be on you. We'd be happy to assist where possible and there's some pretty good documentation to help guide you. If that doesn't sound doable we'll probably add this to the feature backlog if it gets approved.

**Comment by rborn** [comment]
I had this conversation on discord and one idea was to insert a silent audio between the tracks. I don't really like the solution but is just another option :)
Would be great if we could have  a  configurable `pauseBetweenTracks` property to be able to set the number of seconds the player would pause for ❤️

**Comment by puckey** [comment]
Agreed that `autoPlay` (although I would make it `playWhenReady: boolean`) in `updateOptions` would be handy to have – another async call saved.

As far as the pausing between tracks is concerned, I get the feeling this is a pretty niche feature.. The broader use case isn't clear to me in any case.

**Comment by puckey** [comment]
Although... what is the `autoPlay` functionality exactly? As far as I am concerned it would be the same as the initial `TrackPlayer.play()` call – but if it would entail that even if the user called `TrackPlayer.pause()` in between, calling next would cause the track to play, I am a little hesitant due to extra implementation complexity.

**Comment by KfWelch** [comment]
Specifically on what you (DCVS) bring up on iOS playback, as I am obviously unfamiliar, I am seeing from what you say that there is a difference between pausing and stopping playback?  It makes me wonder if there are some further intricacies that could impact whether the app is killed between songs from a pause instead of a stop, though I can see that it might not care whether it is pause or stop between tracks.

For Puckey's most recent comment, `autoplay: true` would be exactly how the player currently functions, except for what I would hope is nothing but an if() statement to internally pause that is skipped over.  This would naturally be the default, due to it being a niche feature, as you recognize.  The false setting would do nothing more than pause the playback when a when a track ends, leaving the programmer/user to decide when to next call `TrackPlayer.play()`.  In my mind, this would be the simplest option, and the user would still be able to tell the difference between a manual pause and an internal pause, as the manual pauses can have state variable changes attached to them.

**Comment by puckey** [comment]
My pr at https://github.com/doublesymmetry/react-native-track-player/pull/1713 (https://github.com/doublesymmetry/react-native-track-player/commit/5c9ca2fcbc296f7fd03583b54060f7857ddf5848 specifically) includes `TrackPlayer.sleepWhenActiveTrackReachesEnd()` which will pause the track when it has finished playing. Note that it is cleared after pausing or skipping to another item.

**Comment by jspizziri** [comment]
@KfWelch we just merged https://github.com/doublesymmetry/react-native-track-player/pull/1713 which has a bunch of new functionality. Please take a look at whats possible now and let me know if this ticket should be reopened based on that.

**Comment by smontlouis** [comment]
@jspizziri @puckey Why has this feature been removed?

[`f2dde5e` (#1713)](https://github.com/doublesymmetry/react-native-track-player/pull/1713/commits/f2dde5e49ed507a011e6c8e65ea80a41b3c464a8)

**Comment by Wurushu** [comment]
> My pr at #1713 ([5c9ca2f](https://github.com/doublesymmetry/react-native-track-player/commit/5c9ca2fcbc296f7fd03583b54060f7857ddf5848) specifically) includes `TrackPlayer.sleepWhenActiveTrackReachesEnd()` which will pause the track when it has finished playing. Note that it is cleared after pausing or skipping to another item.

It would useful having this `sleepWhenActiveTrackReachesEnd` feature to me. Now I should update my project's structure to stop track's autoplay.
