### ISSUE TITLE
[ios] react-native-track-player setRate(0.6) method not working as it runs multiple times

### ISSUE THREAD

**Issue by ZishanChouhan** [doublesymmetry/react-native-track-player#1802]
I am working on an app and using react-native-track-player, when I call setRate(0.6) method at 0.6 speed, it is running multiple times. it sounds like voice is echoing. setRate() is not working at a lower speed but works well at 1.

 var track = [];
        for(let i = 0; i < SoundArray.length; i++ ){
          track.push({
            url: SoundArray[i].sound._filename,
            index: SoundArray[i].index,
            duration: SoundArray[i].sound._duration,
            id: SoundArray[i].index.toString(),
            title: SoundArray[i].index.toString(),
          })
        }
        
        await TrackPlayer.add(track);
        await TrackPlayer.setRate(0.6)
        
        await TrackPlayer.play();
   
is anybody have any idea how to solve this issue?

**Comment by jspizziri** [comment]
Closing. please follow the issue template. It's there for a reason.

**Comment by ZishanChouhan** [comment]
> Closing. please follow the issue template. It's there for a reason.

Can you please tell me which issue template, i mean where i can find the proper reason this issue
