### ISSUE TITLE
jest mock is not working for react-native-track-player 

### ISSUE THREAD

**Issue by ghost** [doublesymmetry/react-native-track-player#1803]
I have added below line to mock the trackplayer  mock is failed. I am adding the screenshot can any one know how to fix this  => 
<img width="332" alt="Screenshot 2022-10-19 at 10 45 23 PM" src="https://user-images.githubusercontent.com/92315552/196759863-55580a3d-30c1-44be-93e8-1a92a59bf3f2.png">

Test case is failed with below error => 
<img width="717" alt="Screenshot 2022-10-19 at 10 24 45 PM" src="https://user-images.githubusercontent.com/92315552/196757481-9c2aa705-20a7-4d8b-8dcd-497e4937b7bd.png">

**Environment Info:** 

System:
    OS: macOS 11.6.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 227.82 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.14.0 => 16.14.0 
    react-native: ^0.63.3 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
"react-native-track-player": "^2.2.0-rc4",

**Comment by Carlos-Lopes** [comment]
Try adding NativeEventEmitter to your mocks

`jest.mock('react-native/Libraries/EventEmitter/NativeEventEmitter')`

**Comment by jspizziri** [comment]
Closing issue. User was deleted.
