### ISSUE TITLE
Track status is reset after seekTo (Expo)

### ISSUE THREAD

**Issue by fax1ty** [doublesymmetry/react-native-track-player#1808]
**Describe the Bug**
After calling `seekTo` with any value, the track starts playing again

**Code To Reproduce**
```js
TrackPlayer.seekTo(15);
```

**Environment Info:**
**react-native-track-player version:** `^3.2.0-d23c3fb990aaf9d6783881fabe21e059b62b0782`
**Real device?** Real device
**What OS are you running?** Android 12

**Comment by arekm213** [comment]
Im having same issue on Android in project where we don't use expo - i think this is general issue

**Comment by fax1ty** [comment]
By the way, the notification does not have the ability to seek, could this be a problem?
P.S. The capabilities are set correctly

```ts
    await TrackPlayer.updateOptions({
      progressUpdateEventInterval: 1,
      ratingType: RatingType.Heart,
      capabilities: [0, 3, 5, 9, 10, 12],
      android: {
        appKilledPlaybackBehavior:
          AppKilledPlaybackBehavior.StopPlaybackAndRemoveNotification,
      },
    });
```

**Comment by TristanH** [comment]
+1, having this issue as well on Android

**Comment by bradleyflood** [comment]
I'm using `TrackPlayer.seekTo(15);` in a production app on 3.2 with no issues.

If you can provide a reproducible bug then we can look into it.

Cheers
Brad

**Comment by OmarBennani099** [comment]
Having the same issue

**Comment by mitchdowney** [comment]
I am having an issue that may or may not be related...when I call `seekTo` the playbackState event is fired with `State.Ready`. This seems to be a new behavior since we upgrading from v2 to v3. Just throwing this out there in case it is breaking people's existing setups (ex. having some logic that resets the player to 0 when `State.Ready` event is fired).
