### ISSUE TITLE
playerSetup crashing when I am adding playerOptions in it

### ISSUE THREAD

**Issue by emilioelmurr** [doublesymmetry/react-native-track-player#1810]
PlayerSetup is crashign when I add playerOptions, I am using it to allow jumpBackward on Android so the user can seek back 10 secnds in case he wants to.

# Steps To Reproduce

Run the example app with the following code added to teh setupPlayer function.

```
await TrackPlayer.setupPlayer({
      backBuffer: 10,
      maxBuffer: 30
    });
```

# Replicable on Example App?
Bug can be replicated on the example app and I tried using both the nightly build and the stable build

# Versions being used: 
react-native: 0.68.1
react-native-track-player: 3.2.0-d23c3fb990aaf9d6783881fabe21e059b62b0782 and tried on 3.2.0

Real device? Or simulator?
Real device and simulator

What OS are you running?
Simulator: Android 13
Real Device: Android 10

**Comment by bradleyflood** [comment]
@emilioelmurr Any update on this? Found any causes or solutions? Thanks

**Comment by emilioelmurr** [comment]
Hello, I did not find any solutions to this!

I  removed the seek back from my app and I am using it without the seek backwards function

**Comment by Temitope-Ojo** [comment]
I also have the same issue, I don't know if it has to do with the fact that the audio skips when the app is in tbe foreground, but works well when it's in the background

**Comment by Temitope-Emmanuel** [comment]
Facing the same issue also, don't know if it has to also deal with the fact that audio is skipping while in the foreground, but it is not in the background

**Comment by puckey** [comment]
Not sure what to do about it though – should we automatically set `minBufferMs` to `maxBufferMs` in this case? Or should we throw from RNTP to have the message closer to the developer?

**Comment by puckey** [comment]
Documented this behavior in https://github.com/doublesymmetry/react-native-track-player/pull/1940
