### ISSUE TITLE
Kotlin_Version hard coded

### ISSUE THREAD

**Issue by mohan7373** [doublesymmetry/react-native-track-player#1811]
in build.gradle. 

classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10"

here Kotlin version is hard coded. so revert it to previous version code. 

 as like this https://github.com/doublesymmetry/react-native-track-player/blob/9ed308c2a8f5bbd4ab69df01a7cfb86047960538/android/build.gradle

**Comment by bradleyflood** [comment]
Thoughts @mpivchev ?

**Comment by jeremyspritelyco** [comment]
.

**Comment by jspizziri** [comment]
@mohan7373 happy to review a PR. this should be an easy change.
