### ISSUE TITLE
[Android] Crash Fatal Exception: java.lang.AbstractMethodError: abstract method "void android.media.Spatializer$OnSpatializerStateChangedListener.onSpatializerAvailableChanged(android.media.Spatializer, boolean)"

### ISSUE THREAD

**Issue by RamProg** [doublesymmetry/react-native-track-player#1813]
**Describe the Bug**
Getting consistent crashes on production on Android since updating to 3.0.0

**Steps To Reproduce**
Only happens on Samsung devices with Android 12 and 98% of the times the app is on the background.

**Code To Reproduce**
```
Fatal Exception: java.lang.AbstractMethodError: abstract method "void android.media.Spatializer$OnSpatializerStateChangedListener.onSpatializerAvailableChanged(android.media.Spatializer, boolean)"
       at android.media.Spatializer$SpatializerInfoDispatcherStub.lambda$dispatchSpatializerAvailableChanged$1$Spatializer$SpatializerInfoDispatcherStub(Spatializer.java:529)
       at android.media.Spatializer$SpatializerInfoDispatcherStub$$ExternalSyntheticLambda0.run(Spatializer.java:6)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Replicable on Example App?**
I haven't been able to replicate it yet.

**Environment Info:**
It only happens on real devices on production at the moment
`react-native-track-player 3.2.0-d23c3fb990aaf9d6783881fabe21e059b62b0782`

**How I can Help**
Here to help however I can.

**Comment by puckey** [comment]
Are specific android devices experiencing these crashes?

**Comment by puckey** [comment]
You might want to look at the following exoplayer issue: https://github.com/google/ExoPlayer/issues/10684

(If it helps you to distill the issue, please let us know what you found)

**Comment by RamProg** [comment]
> Are specific android devices experiencing these crashes?

These are the main ones:

13%
Galaxy Z Fold3 5G
12%
Galaxy Z Flip3 5G
10%
Galaxy Z Flip3 5G 

It seems I need to update the compileSDKVersion to at least 32, I'll try it out and let you know.

**Comment by jspizziri** [comment]
@RamProg for `3.2.0` you need at least `33`. Closing for now, let me know if its still an issue.
