### ISSUE TITLE
TypeError: null is not an object (evaluating 'TrackPlayer.RATING_HEART')

### ISSUE THREAD

**Issue by Md-Yousuf-sheikh** [doublesymmetry/react-native-track-player#1815]
**Help me I have this error install  package and import then show this error how to solve that issue **
****TypeError: null is not an object (evaluating 'TrackPlayer.RATING_HEART')****

****TypeError: null is not an object (evaluating 'TrackPlayer.RATING_HEART')
at node_modules\expo\build\environment\react-native-logs.fx.js:27:23 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:95:17 in reportException      
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:141:19 in handleException     
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:39 in ### handleError
at node_modules\@react-native\polyfills\error-guard.js:49:36 in ErrorUtils.reportFatalError    
at node_modules\metro-runtime\src\polyfills\require.js:203:40 in guardedLoadModule
at http://192.168.10.111:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:134790:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.   
at node_modules\expo\build\environment\react-native-logs.fx.js:27:23 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:95:17 in reportException      
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:141:19 in handleException     
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:39 in handleError
at node_modules\@react-native\polyfills\error-guard.js:49:36 in ErrorUtils.reportFatalError    
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:370:35 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:113:16 in callFunctionReturnFlushedQueue****

**Comment by bradleyflood** [comment]
Sorry, please follow the bug report template. Thanks.

**Comment by Md-Yousuf-sheikh** [comment]
i am using expo app

**Comment by malaganator3000** [comment]
I have the same problem, it happens when building on release

**Comment by krmgopi** [comment]
I am also getting the same error, when I import the React Native track player getting this error

**Comment by bradleyflood** [comment]
@Md-Yousuf-sheikh @malaganator3000 @krmgopi @lynkas

If you are having a similar issue please raise a bug report and follow the Issue template so we can investigate.

Thank you :)
