### ISSUE TITLE
undefined is not a function when calling registerPlaybackService

### ISSUE THREAD

**Issue by kierancrown** [doublesymmetry/react-native-track-player#1819]
**Describe the Bug**
When calling registerPlaybackService in index.js with the example provided I'm seeing a undefined is not a function and no events are being handled.

**Steps To Reproduce**
Create a new RN 0.70.6 Typescript project. Install react-native-track-player 3.2.0 and follow the provided service.js events from the docs.

**Code To Reproduce**
**index.js**

`
import {AppRegistry} from 'react-native';
import App from './src/App';
import {name as appName} from './app.json';

import TrackPlayer from 'react-native-track-player';

AppRegistry.registerComponent(appName, () => App);
TrackPlayer.registerPlaybackService(() => require('./service'));
`

**service.js**

`
import TrackPlayer, {Event} from 'react-native-track-player';

export const PlaybackService = async function () {
  TrackPlayer.addEventListener(Event.RemotePlay, () => TrackPlayer.play());
  TrackPlayer.addEventListener(Event.RemotePause, async () => TrackPlayer.pause());
};
`

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)?
No

**Environment Info:**
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 614.97 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.1 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
`react-native-track-player` version 3.2.0

Real device? Or simulator?
Both

What OS are you running?
Android & iOS

Unable to locate underlying issue. Need some guidance...

**Comment by martinmidtsund** [comment]
In service.js you should try to export the service like in the example app:

```
export async function PlaybackService() {
// Event handlers etc
}
```

**Comment by bradleyflood** [comment]
Looks like you didn't export. Cheers.

**Comment by kierancrown** [comment]
I appreciate this has been closed but am I naive or is this

`
export async function PlaybackService() {
// Event handlers etc
}
`

not the same as this?

`
export const PlaybackService  = async() =>  {
// Event handlers etc
}
`

Anyway I changed my `service.js` file to look like this:
```
import TrackPlayer, {Event} from 'react-native-track-player';

export async function PlaybackService() {
  TrackPlayer.addEventListener(Event.RemotePlay, () => TrackPlayer.play());
  TrackPlayer.addEventListener(Event.RemotePause, async () => {
    console.log('PAUSE');
    TrackPlayer.pause();
  });
}
```

Reset metro cache, and reinstalled on device but am still seeing the same issue. I will try with RN 0.68 to see if this is an issue with 70+

**Comment by martinmidtsund** [comment]
Yes, my bad, you should import the service as in the example app:

https://github.com/doublesymmetry/react-native-track-player/blob/main/example/index.js#L5

Else you could export it as a default to make it work with your require-statement, like `module.exports = ...` in the service.js
