### ISSUE TITLE
[Android] Notification play pause toggle gets stuck

### ISSUE THREAD

**Issue by puckey** [doublesymmetry/react-native-track-player#1821]
I am seeing an issue on an Android 9 device where when repeatedly toggling between play and pause in the notification, it seems to get stuck with either a pause button (with the audio paused) or with a play button (with the audio playing). Pressing the button does actually call the corresponding function, but it is the wrong one since playback has already been stopped (or has already continued playing).

**Steps To Reproduce**
- Run the example app on main branch
- Open the notification
- Toggle between play and pause a few times.

I checked the exoplayer repository to see if anyone else is experiencing this kind of issue and was unable to find anything.

A guess would be that some kind of race condition is occurring between RNTP and Exoplayer..

**Comment by puckey** [comment]
I can also reproduce this issue using an Android 12 test phone. And have also been able to reproduce using a production build variant.

**Comment by puckey** [comment]
I can also reproduce this in the KotlinAudio example app, so will continue my search there.

**Comment by puckey** [comment]
In adb logcat you see the following message:
```11-11 10:36:47.803  1858  2157 E NotificationService: Package enqueue rate is 5.0880947. Shedding 0|com.doublesymmetry.kotlin_audio_sample|1|null|10008. package=com.doublesymmetry.kotlin_audio_sample```

The issue that is occurring is that notification updates are being skipped due to too many updates occurring after each other.

According to the following exoplayer issue you can still cause this to happen in any audio app by repeatedly pressing notification buttons very fast: https://github.com/google/ExoPlayer/issues/6657

Interestingly I need to spam the play pause button much faster in the KotlinAudio demo before I see the shedding occur than when I do so in RNTP..

**Comment by puckey** [comment]
With `adb logcat | grep updateNotification\(` I see the following when pressing a button in the notification:

```
11-11 18:21:03.473  2231  2231 D StatusBar: updateNotification(StatusBarNotification(pkg=com.example user=UserHandle{0} id=1 tag=null key=0|com.example|1|null|10188: Notification(channel=kotlin_audio_player pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x6a color=0x00000000 category=transport actions=3 vis=PUBLIC)))
11-11 18:21:03.520  2231  2231 D StatusBar: updateNotification(StatusBarNotification(pkg=com.example user=UserHandle{0} id=1 tag=null key=0|com.example|1|null|10188: Notification(channel=kotlin_audio_player pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x6a color=0x00000000 category=transport actions=3 vis=PUBLIC)))
11-11 18:21:03.583  2231  2231 D StatusBar: updateNotification(StatusBarNotification(pkg=com.example user=UserHandle{0} id=1 tag=null key=0|com.example|1|null|10188: Notification(channel=kotlin_audio_player pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x6a color=0x00000000 category=transport actions=3 vis=PUBLIC)))
11-11 18:21:03.586  2231  2231 D StatusBar: updateNotification(StatusBarNotification(pkg=com.example user=UserHandle{0} id=1 tag=null key=0|com.example|1|null|10188: Notification(channel=kotlin_audio_player pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x6a color=0x00000000 category=transport actions=3 vis=PUBLIC)))
```

And with kotlinaudio I see

```
11-11 18:23:09.528  2231  2231 D StatusBar: updateNotification(StatusBarNotification(pkg=com.doublesymmetry.kotlin_audio_sample user=UserHandle{0} id=1 tag=null key=0|com.doublesymmetry.kotlin_audio_sample|1|null|10189: Notification(channel=kotlin_audio_player pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=transport actions=5 vis=PUBLIC)))
11-11 18:23:09.552  2231  2231 D StatusBar: updateNotification(StatusBarNotification(pkg=com.doublesymmetry.kotlin_audio_sample user=UserHandle{0} id=1 tag=null key=0|com.doublesymmetry.kotlin_audio_sample|1|null|10189: Notification(channel=kotlin_audio_player pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=transport actions=5 vis=PUBLIC)))
```

So it seems that for some reason we are getting double notification updates (see lines starting with `updateNotification`) in the RNTP example app.

**Comment by Derewith** [comment]
Hey guys any updates?

**Comment by puckey** [comment]
This issue should not occur as easily as before – perhaps someone would like to test using nightly?
