### ISSUE TITLE
[Feature Request] Adding events to listen for changes in volume and repeat mode.

### ISSUE THREAD

**Issue by HyopeR** [doublesymmetry/react-native-track-player#1824]
**What is the need and use case of this feature?**
Hello. First of all, thanks for this great package.

I am using your package on a new application. 
With the **useTrackPlayerEvents** hook I am able to view the actively running track in the app.

However, I cannot follow the status of **TrackPlayer.setRepeatMode()** or **TrackPlayer.setVolume()** functions in the application. 
For now I'm solving this by applying a patch to your package, but will we be able to listen to these two events in the future?

**Describe the ideal solution**
Adding events to listen to the change in volume and repeat mode to control the whole status of the Track player configuration with a single hook.

**Events that can be added:**
```
Event.PlaybackVolumeChanged,
Event.PlaybackRepeatModeChanged,
```

**Versions:**
```
"react-native-track-player": "^3.2.0",
```

**My patch file**
[react-native-track-player+3.2.0.txt](https://github.com/doublesymmetry/react-native-track-player/files/10013109/react-native-track-player%2B3.2.0.txt)

**Comment by p4bl1t0** [comment]
Hello, @jspizziri I'm looking for events RemoteVolumeUp and RemoteVolumeDown

Why they are not present?

**Comment by jspizziri** [comment]
@p4bl1t0 , they're not present because no one has implemented them. I also personally am not sure if I see a compelling use case for them, which is maybe why no one has implemented them. If you're interested in doing the implementation, I'd be happy to discuss your use case with you and see if it's a feature set that we'd want to support in the long term.

**Comment by p4bl1t0** [comment]
I'm not very well on Android/Swift but I can help with guidance. Where and how do you suggest to implemented?

I was revieing: 

```
let volumeView = MPVolumeView()
        if let volumeSlider = volumeView.subviews.first as? UISlider {
            volumeSlider.addTarget(self, action: #selector(volumeSliderChanged(_:)), for: .valueChanged)
        }
```

**Comment by jspizziri** [comment]
@p4bl1t0 first I recommend doing a deep dive on AVPlayer, SwiftAudio, KotlinAudio, & Exoplayer to see what you can find, and try a few things. I also recommend you identify your use case for this, as that will be important for the consideration of if this gets merged or not.
