### ISSUE TITLE
[Android] Artist not displayed on lockscreen on Samsung device

### ISSUE THREAD

**Issue by puckey** [doublesymmetry/react-native-track-player#1825]
In the lockscreen on my Galaxy J6 / Android 8 test device, I see 'Unknown' in the place where the artist (subtitle) should be shown.

I also checked to make sure this was not an issue on version 1.2.3

Related issues:
- https://github.com/google/ExoPlayer/issues/5223
- https://stackoverflow.com/questions/50469675/samsung-aod-and-lock-screen-media-metadata-unknown

![IMG_0761](https://user-images.githubusercontent.com/271885/201908459-b62b06d1-8add-4add-978f-227d9cc3bce1.jpg)

**Comment by puckey** [comment]
Fixed in https://github.com/doublesymmetry/react-native-track-player/pull/1713 - specific commit: https://github.com/puckey/KotlinAudio/commit/186d964e1a49b2cfabef9f269c57b5049b8b0a99

**Comment by jspizziri** [comment]
Closed by https://github.com/doublesymmetry/react-native-track-player/pull/1713
