### ISSUE TITLE
PausePlayback and StopPlaybackAndRemoveNotification don't work on Android 9.0

### ISSUE THREAD

**Issue by SalSchein** [doublesymmetry/react-native-track-player#1829]
await TrackPlayer.updateOptions({
  android: {
    // This is the default behavior
    appKilledPlaybackBehavior: AppKilledPlaybackBehavior.StopPlaybackAndRemoveNotification 
  }
});

PausePlayback and StopPlaybackAndRemoveNotification don't work on Android 9.0.

"react-native-track-player": "^2.1.2"

**Comment by puckey** [comment]
You need to be using RNTP 3.2.0

**Comment by cihanbas** [comment]
I am using 3.2.1 and have the same problem
player keeps working when i close the app

**Comment by cihanbas** [comment]
this solution is working for me https://github.com/doublesymmetry/react-native-track-player/issues/1759#issuecomment-1319985067

**Comment by jspizziri** [comment]
@SalSchein please see the comment above.
