### ISSUE TITLE
[Feature Request] Allow track player to run decoupled from audio player, like react-native-music-control

### ISSUE THREAD

**Issue by arthurgeron-work** [doublesymmetry/react-native-track-player#1830]
**What is the need and use case of this feature?**
My project already has a stream player with background mode enabled, I'd like to be able to run the Track Player without having it really stream anything, only use the controls/sliders and provide the data (current position, playing/paused, etc) externally.

**Describe the ideal solution**
Allow the player to work without a url to stream, receiving current data through its api and normally triggering events when the track player buttons are pressed. Load the thumbnail and else normally as it would.

**How I can Help**
I can make the solution if it makes sense to the maintainers.

**Comment by felixroos** [comment]
hah I was about to make the exact same feature request. With [react-native-music-control](https://github.com/tanguyantoine/react-native-music-control) being archived (guiding to RNTP), it seems RNTP is the only maintained package that is able to have lock screen controls. If those were decoupled from the audio player, one could choose which audio backend to use and use RNTP only for the controls.

In my case I want to build a multitrack player, which is [not supported by this lib](https://github.com/doublesymmetry/react-native-track-player/issues/172).

@arthurgeron-work I think adding a meaningful title to this issue would increase the chance of it being noticed / fixed.

**Comment by arthurgeron-work** [comment]
> hah I was about to make the exact same feature request. With [react-native-music-control](https://github.com/tanguyantoine/react-native-music-control) being archived (guiding to RNTP), it seems RNTP is the only maintained package that is able to have lock screen controls. If those were decoupled from the audio player, one could choose which audio backend to use and use RNTP only for the controls.
> 
> In my case I want to build a multitrack player, which is [not supported by this lib](https://github.com/doublesymmetry/react-native-track-player/issues/172).
> 
> @arthurgeron-work I think adding a meaningful title to this issue would increase the chance of it being noticed / fixed.

We also had to migrate to track player from music-controls, in my case it was because Android SDKs (30+) now required by playstore is not properly supported by the deprecated lib, forcing the change.

I've added a more meaningful title, thank you for the suggestion.

**Comment by jspizziri** [comment]
@arthurgeron-work I'm not entirely following the request. You just want to beable to control AVPlayer and Exoplayer headlessly?

It sounds like you might be better off building a lightweight wrapper around AVPlayer. I'm not sure what the path is for Android, but I'm guessing there's some lower-level API that ExoPlayer uses under the hood.

My initial instinct is this isn't something that would be simple to support in this lib without a massive refactor. But feel free to take a deeper look at the source and let me know your thoughts.

**Comment by arthurgeron-work** [comment]
> @arthurgeron-work I'm not entirely following the request. You just want to beable to control AVPlayer and Exoplayer headlessly?

react-native-music-control had that feature, now that Google requires SDK 30+ to be used (which is incompatible with rn music control), the lib is deprecated and it refers to this lib as its successor I imagine a lot of other people will end up doing in this situation (e.g. migrating to track player only to find it doesn't support headless play).

> It sounds like you might be better off building a lightweight wrapper around AVPlayer. I'm not sure what the path is for Android, but I'm guessing there's some lower-level API that ExoPlayer uses under the hood.

I'm not at all saying that this lib necessarily has to support this, but I can see more overhead being generated between having to manage 2 different libs that create a player in the notification center (e.g. avoiding showing both at the same time); That said it'd be nice to have this lib support headless play even if just by letting us use the player UI (event listeners + thumbnail loading), it'd also support all the devs/projects migrating away from rn music control.

**Comment by jspizziri** [comment]
@arthurgeron-work I don't necessarily disagree. But I think this would be pretty complex to implement (just my gut).

My suggestion would be for you to take a look under the hood and propose a concrete API & Implementation plan for something like this. If it seems feasible and maintainable I don't see any reason it wouldn't be considered as a feature set.

With that said, I'm going to add this feature to the feature backlog. If you want to be a champion for it then I'll look forward to more detailed conversations!

**Comment by arthurgeron-work** [comment]
I'd more than glad to that, I appreciate your open mindedness

**Comment by felixroos** [comment]
> I'd more than glad to do that, I appreciate your open mindedness

Have you already started to work on this? If yes, can you give a rough estimate on how long this might take?
I am currently considering looking at this myself, unless you're not already working on it.

**Comment by arthurgeron-work** [comment]
> > I'd more than glad to do that, I appreciate your open mindedness
> 
> Have you already started to work on this? If yes, can you give a rough estimate on how long this might take? I am currently considering looking at this myself, unless you're not already working on it.

I've but turns out you can already use it "decoupled" if you pass the thumbnail (must be valid) in the url field, you just won't be able to see/change the timeline, so this should work while I'm not done.

**Comment by mbpictures** [comment]
@arthurgeron-work do you have a small example of how to do it with the thumbnail as a URL? How do you then play the correct audio files?

**Comment by danielchan303** [comment]
> > > I'd more than glad to do that, I appreciate your open mindedness
> > 
> > 
> > Have you already started to work on this? If yes, can you give a rough estimate on how long this might take? I am currently considering looking at this myself, unless you're not already working on it.
> 
> I've but turns out you can already use it "decoupled" if you pass the thumbnail (must be valid) in the url field, you just won't be able to see/change the timeline, this should work while I'm not done.

Putting a image as url doesn't seems to work for me.
