### ISSUE TITLE
[Android] [v3.2.0] Build Error "Unresolved reference: value"

### ISSUE THREAD

**Issue by garrettg123** [doublesymmetry/react-native-track-player#1831]
**Describe the Bug**
```
> Task :react-native-track-player:compileDebugKotlin FAILED
e: /Users/gsquare567/Sites/blogcast/node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/extensions/AudioPlayerStateExt.kt: (8, 16): 'when' expression must be exhaustive, add necessary 'STOPPED', 'ERROR' branches or 'else' branch instead
e: /Users/gsquare567/Sites/blogcast/node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/module/MusicModule.kt: (505, 61): Unresolved reference: value

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-track-player:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

**Steps To Reproduce**
How can someone else reproduce this bug?

**Code To Reproduce**
Please provide a simple code example that allows others to replicate the bug.

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)?

**Environment Info:**
```
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 27.07 MB / 32.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 16.18.1 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 30, 31, 32, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-30 | Google Play Intel x86 Atom, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

"react": "18.1.0",
"react-native": "0.70.5",

        buildToolsVersion = findProperty('android.buildToolsVersion') ?: '31.0.0'
        minSdkVersion = Integer.parseInt(findProperty('android.minSdkVersion') ?: '21')
        compileSdkVersion = Integer.parseInt(findProperty('android.compileSdkVersion') ?: '33')
        targetSdkVersion = Integer.parseInt(findProperty('android.targetSdkVersion') ?: '31')
        kotlinVersion = findProperty('android.kotlinVersion') ?: '1.6.0'
        frescoVersion = findProperty('expo.frescoVersion') ?: '2.5.0'

        classpath('com.android.tools.build:gradle:7.2.1')
        classpath('com.facebook.react:react-native-gradle-plugin')
        classpath('de.undercouch:gradle-download-task:5.0.1')
```
Android 

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

Downgrading to 3.1.0 works, so this is a regression in the update. I have no experience with Kotlin and my `patch-package` attempt did not work. I am working in Expo v47 (latest) Bare so versioning has been a bit of a nightmare.

**Comment by arthurgeron-work** [comment]
@thanhchuongbmd same issue here, answering your question it resolves to "main-SNAPSHOT"

**Comment by arthurgeron-work** [comment]
correcting myself, we had a patch package to use main because 1.2.4 generated a exception on app reload (e.g. code push or fast reload), other people might've been doing the same

**Comment by SalSchein** [comment]
dependencies {
    implementation 'com.github.DoubleSymmetry:KotlinAudio:main-SNAPSHOT'
    
 I am getting the same errors.
 Any solution?

**Comment by SalSchein** [comment]
@garrettg123 

How do you fix the crash issues in 3.1?

**Comment by AnimusAudax** [comment]
> track-player is using the main version of KotlinAudio instead of a specific tag, KotlinAudio's owner has pushed some code into main in the last 24 hours which resulted in this issue.. setting the dependency to the latest tag (i.e. 1.2.4) in build.gradle fixed the issue ![image](https://user-images.githubusercontent.com/71399856/203566877-eb58887a-da88-49a7-8cef-4427705d2361.png)

can You please explain again?
I tried with "SNAPSHOT" and 

dependencies {
    implementation 'com.github.DoubleSymmetry:KotlinAudio:v1.2.4'
    
I get the same errors still as in this issue description :(

**Comment by SalSchein** [comment]
@garrettg123  okay, thanks

**Comment by Atom54** [comment]
Same problem for me. I used "main-SNAPSHOT" so far but it's not working right now; with "1.2.4" or "v1.2.4" it looks like credentials are required :
> Could not get resource 'https://www.jitpack.io/com/github/doublesymmetry/kotlin-audio/1.2.4/kotlin-audio-1.2.4.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/doublesymmetry/kotlin-audio/1.2.4/kotlin-audio-1.2.4.pom'. Received status code 401 from server: Unauthorized

**Comment by AnimusAudax** [comment]
I switched from "main-SNAPSHOT" to "1.2.4" and created a patch and the build was successful. No problems with the player on my device.

**Comment by acollazomayer** [comment]
I am having the same issue. Tried with a patch but it did not work.

**Comment by arthurgeron-work** [comment]
if you want 1.2.4 fixes but also the crash fix you can refer the implementation to a specific commit instead of a version, in this case the first commit after 1.2.4 which fixes the crash; On `patches/react-native-track-player+3.2.0.patch` set:
```patch
diff --git a/node_modules/react-native-track-player/android/build.gradle b/node_modules/react-native-track-player/android/build.gradle
index ad99343..207e417 100644
--- a/node_modules/react-native-track-player/android/build.gradle
+++ b/node_modules/react-native-track-player/android/build.gradle
@@ -49,7 +49,7 @@ repositories {
 }
 
 dependencies {
-    implementation 'com.github.DoubleSymmetry:KotlinAudio:v1.2.4'
+    implementation 'com.github.DoubleSymmetry:KotlinAudio:dd4bdab147c90fffcff7800790dbfcb41291d29b'
 //    implementation "com.github.doublesymmetry:kotlin-audio:1.2.2"
 
     //noinspection GradleDynamicVersion
```

**Comment by MasterTeus** [comment]
I also have the same problem, it's been 2 days that I'm trying to solve it
