### ISSUE TITLE
how to get metadata on mp3 file not audio stream

### ISSUE THREAD

**Issue by zhuguibiao** [doublesymmetry/react-native-track-player#1832]
- how to get metadata on mp3 file not audio stream
- like "playback-metadata-received" event

**Comment by jspizziri** [comment]
@zhuguibiao you might try calling [`getTrack`](https://react-native-track-player.js.org/docs/api/functions/queue#gettrackindex) and inspecting that data. If that doesn't give you what you need this would be a feature request.
