### ISSUE TITLE
Playback rate reset to 1.0 when `play()` is called again

### ISSUE THREAD

**Issue by fivecar** [doublesymmetry/react-native-track-player#1836]
This started as an issue 3 years ago in #614, but was only partway fixed. It's still an issue even in version 3.2.0, but I've taken an afternoon to isolate a specific [minimal-code repro here](https://github.com/SuperphonicHub/TrackPlayerRateExample).

It turns out the following sequence is problematic:
```typescript
  await TrackPlayer.setRate(2);
  await TrackPlayer.play();
  await TrackPlayer.seekTo(position + 15);
  await TrackPlayer.play();
```
Specifically, if you seek while playing, and then call `play()` in the new position, it'll reset the playback rate. You can check out the repo above, which includes both the code and instructions to get a quick repro.

There's a merged fix for this in SwiftAudioEx at https://github.com/doublesymmetry/SwiftAudioEx/pull/28. When that gets released, it'd be great to update `react-native-track-player` to pull that new release so that this bug can be fixed.

**Comment by fivecar** [comment]
update - my SwiftAudioEx fix only addresses the majority of this issue, but not 100% of the times. Even with that fix, at times playback will still reset to a rate of 1.0 — oddly enough, _mid-playback_ (meaning without you pressing Play or Pause). So my fix will address the majority of this issue, but not all of it... there's still something else going on in either this codebase or SwiftAudioEx that causes playback speeds to revert to 1.0.

**Comment by AronBe** [comment]
yes, I also see this happening, strangely only in release mode, not the dev mode

**Comment by fivecar** [comment]
Now that https://github.com/doublesymmetry/SwiftAudioEx/pull/28 has been merged into SwiftAudioEx, this bug should go away once we integrate whatever SwiftAudioEx that release gets into (cc @dcvz as FYI).

**Comment by fivecar** [comment]
Awesome - great to hear, @dcvz !

**Comment by puckey** [comment]
Closing since this is fixed in `nightly`
