### ISSUE TITLE
[Android] Audio starts auto when I have a phone call (if app is open and track player is stopped)

### ISSUE THREAD

**Issue by pmafpinho** [doublesymmetry/react-native-track-player#1839]
I'm doing a live radio app and I found this issue and I don't know how to fix it! 
I use the last version of React Native Track Player.

How to reproduce: 
Open app > Play > Stop ... Call to someone and Finnish call... audio starts auto.
This only happens when app is on, because if you kill the app or the notification, not happen. 

Can help me to fix this?

**Comment by DennisdeWitNL** [comment]
I have the same problem. I had to completely remote the remoteDucking from my code for now.

**Comment by ziyoshams** [comment]
Experiencing the same issue.

**Comment by puckey** [comment]
By last version do you mean version `3.2.0` or `nightly`?

**Comment by pmafpinho** [comment]
@puckey I tried both! When is playing, if I stop... I get a call... when call is over, app is running the sound again... like auto play...

**Comment by puckey** [comment]
@pmafpinho okay thanks – I will try to reproduce it soon

**Comment by puckey** [comment]
I am unable to reproduce this issue using `nightly` in combination with the example app on a phone with android 13. Am I missing something?

- open the app on test phone
- press play
- press pause
- call the test phone
- hangup call
- expect audio to start playing (which doesn't happen)

**Comment by puckey** [comment]
it also does not happen with the same steps as above, when I place a call to another phone from the test phone instead of receiving one..

**Comment by puckey** [comment]
If I am doing everything correctly, please clone the repo and change the code of the example app to such a degree that we can replicate this issue.

**Comment by pmafpinho** [comment]
@puckey I'm using : "react-native-track-player": "^3.2.0",

I open the app, I click on play / stop... i get a call from a person and when I finnish the call, audio starts! I can do a video to show you. I also can send you APK or the code.

**Comment by puckey** [comment]
Please try the nightly version instead. If it still gives you the same issues, clone the `react-native-track-player` repo and change the code of the example app to such a degree that we can replicate this issue.

**Comment by pmafpinho** [comment]
https://user-images.githubusercontent.com/22176917/217234376-08c1d055-efaa-4937-a1de-f76511c1a786.mp4

**Comment by pmafpinho** [comment]
@puckey I installed the nightly version and not fixed this issue!

**Comment by pmafpinho** [comment]
@puckey the example project not working!
![Screenshot 2023-02-07 at 12 34 14](https://user-images.githubusercontent.com/22176917/217246242-0f02d715-fdb7-45d4-98ab-d29baf4a2777.png)

**Comment by pmafpinho** [comment]
@puckey I tryed on android and work's, no problem! I check your Live Stream example, but not sense the pause button, a Live Stream is a Live Stream, you can't pause (because you want ear something LIVE). That's why a Stop button must be implemented and you guys removed. Live Stream it's for radios, and I made a lot to get the live result. I will try to create APK for this, and test is it's happens...

**Comment by puckey** [comment]
> @puckey I tryed on android and work's, no problem! I check your Live Stream example, but not sense the pause button, a Live Stream is a Live Stream, you can't pause (because you want ear something LIVE). That's why a Stop button must be implemented and you guys removed. Live Stream it's for radios, and I made a lot to get the live result. I will try to create APK for this, and test is it's happens...

`TrackPlayer.stop()` is supported again in `nightly`..

**Comment by puckey** [comment]
In ‘nightly’ you can also use ‘autoHandleInterruptions’ in player options: https://github.com/doublesymmetry/react-native-track-player/blob/211a3fbda0e408a70fc9421bd31fd686fa1a68d0/docs/docs/api/objects/player-options.md

**Comment by pmafpinho** [comment]
It's fixed! Thank's!
