### ISSUE TITLE
Question: is it ok for PlaybackProgressUpdated fire when app is in foreground?

### ISSUE THREAD

**Issue by ziyoshams** [doublesymmetry/react-native-track-player#1841]
I thought playback service is for when the app is the background. But i noticed that PlaybackProgressUpdated keeps firing when the app is in foreground. This is fine for me, but want to make sure its intended.

**Comment by jspizziri** [comment]
This is as designed.

**Comment by aubri61** [comment]
@ziyoshams 

hi, if you don't mind, could you share how did you implemented 'PlaybackProgressUpdated' events? 

cause i can't get it fired... 
i set PlaybackProgressUpdatedInterval at setup, made it clear that track is playing, but PlaybackProgressUpdated this event is not firing at the desired moment. it's called only once at the initial time.
please..

**Comment by grp06** [comment]
@ziyoshams same here... did you find a solution?

**Comment by jspizziri** [comment]
Yes, progress updates is intended to fire regardless of foreground or background state.
