### ISSUE TITLE
[Feature Request] Add change reason to PlaybackTrackChanged event

### ISSUE THREAD

**Issue by maotoumao** [doublesymmetry/react-native-track-player#1844]
**What is the need and use case of this feature?**
I need to do some hooks (which would cause the playing queue changed) when a song reaches its end.
I listen to PlaybackTrackChanged event, and in that special case I received multiple events.
Diving into the source code I saw that there are 4 reasons which would trigger the PlaybackTrackChanged event, and it's really difficult to figure out which event is the "QUEUE_CHANGED" reason I need.

**Describe the ideal solution**
As above, I wonder if there's any possibility to add something like "reason" to the parameter of PlaybackTrackChanged event's callback function, and it's usage might be like
``` typescript
/** declaration */
interface PlaybackTrackChangedEvent {
    /** The index of previously active track. */
    track: number | null;
    /** The previous track position in seconds. */
    position: number;
    /** The next (active) track index. */
    nextTrack: number;
    /** The reason of track change. */
    reason: string; // or enum 
};

/** usage */
import TrackPlayer, {Event} from 'react-native-track-player';
TrackPlayer.addEventListener(Event.PlaybackTrackChanged, async (evt: PlaybackTrackChangedEvent)=> {
    console.log("reason", evt.reason);
}

```

**How I can Help**
There wont be many changes to implement this feature. We just need to change the observeEvents function in MusicService.kt file in android. I'm glad to create a PR if needed.

**Comment by jspizziri** [comment]
@maotoumao this event is about to entirely change

please see the work done by `puckey` here https://github.com/doublesymmetry/react-native-track-player/pull/1713

You can see a concise proposal here https://github.com/doublesymmetry/react-native-track-player/issues/1293#issuecomment-1268238702
