### ISSUE TITLE
[Feature Request] Optimize Android resource usage

### ISSUE THREAD

**Issue by elliotdickison** [doublesymmetry/react-native-track-player#1845]
**What is the need and use case of this feature?**

When loading local files/tracks into the player on Android, the full contents of all files/tracks are loaded into memory immediately. For large track lists this results in rapid memory consumption and can end with Android killing the app.

**Describe the ideal solution**

It would be excellent if only the current track was loaded into memory (or maybe the current + previous + next if that results in a faster user experience).

**Describe alternatives you've considered**

I am currently limiting my app to queueing 5 tracks at a time. I load 5 tracks initially and then when the PlaybackQueueEnded event is fired I clear out those 5 and load 5 more. This isn't ideal for a few reasons:
- It's extra logic in my app that feels like it belongs in RNTP
- Dynamically adjusting the queue has some quirks: the lock screen controls temporarily disappear every 5 tracks while I reset the queue, it takes a bit longer to move on to the next track at those points, and I have to manually restart playback (see #1691)
- If my app's task is put on ice by Android then it isn't around to load up the next 5 tracks and playback will stop prematurely

**Additional context**

The particular track list that brought this issue to my attention was ~160 tracks totaling 2.7GB (a year-long Bible reading plan).

I am using expo-file-system to download files and then I'm passing the fileURIs to RNTP.

**How I can Help**

- I can do a deep dive on resource usage to check for additional things like processing constraints on large track lists
- Loading large lists of tracks from the network doesn't have quite the same effect on device memory, but it's still very slow. I can attempt to diagnose that as well.

**Comment by jspizziri** [comment]
@elliotdickison open to a PR for this. For now I'll move it to the feature backlog.

**Comment by elliotdickison** [comment]
Just noting that this occurs whether loading local files or URLs. Tested on version 4 rc9.

**Comment by elliotdickison** [comment]
PEBKAC: I was inadvertently stuffing insane amounts of extra data into the queued track objects. Slimming that data down solved the problem.
