### ISSUE TITLE
When I import This package (import TrackPlayer from 'react-native-track-player') in my app.js file and restart development server I am getting an error 

### ISSUE THREAD

**Issue by khadeshyam** [doublesymmetry/react-native-track-player#1847]
**Describe the Bug**

**Steps To Reproduce**
How can someone else reproduce this bug?

**Code To Reproduce**
Please provide a simple code example that allows others to replicate the bug.

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)?

**Environment Info:**
Paste the results of `npx react-native info`
Paste the exact `react-native-track-player` version you are using
Real device? Or simulator?
What OS are you running?

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

**Comment by jspizziri** [comment]
incorrect issue template

**Comment by cihanbas** [comment]
[Android] 
same issue @jspizziri when i restart the application with react-native-restart and then when i call this function
`const isSetup = await SetupService()` 
my app is crasshed, pls check this issue Thanks

```
"react-native-track-player": "^3.2.0",
"react-native": "0.61.3",
"react-native-restart": "0.0.17",
```

**Comment by cihanbas** [comment]
> I don't know anything about that restart library, but we don't support it. If you can reproduce the issue in the example app and file a correct issue we'll look at the issue when we're able

okay i will check with your example thanks.
