### ISSUE TITLE
Receiving TypeError  with app crashing when setting up player in android

### ISSUE THREAD

**Issue by jenipharachel** [doublesymmetry/react-native-track-player#1848]
**Describe the Bug**
Receiving type error when the player is being setup
`TypeError: undefined is not an object (evaluating 'taskProvider()(data).then')`

**Steps To Reproduce**
- Call setup player function before either in App.js or any screen where the music will be played.

**Code To Reproduce**
Function that is being called before tracks are added

```
 useEffect(() => {
    setupPlayer();
    () => resetPlayer();
  }, []);
```

Setup Player function.
```
export const setupPlayer = async () => {
  try {
    // this method will only reject if player has not been setup yet
    await TrackPlayer.getCurrentTrack();
  } catch {
    await TrackPlayer.setupPlayer();
  }
};
```

**Replicable on Example App?**
Not able to run example app.

**Environment Info:**
Paste the results of `npx react-native info`

> System:
>     OS: macOS 13.0
>     CPU: (8) x64 Apple M1
>     Memory: 15.50 MB / 8.00 GB
>     Shell: 5.8.1 - /bin/zsh
>   Binaries:
>     Node: 16.5.0 - ~/.nvm/versions/node/v16.5.0/bin/node
>     Yarn: 1.22.15 - ~/.nvm/versions/node/v16.5.0/bin/yarn
>     npm: 7.19.1 - ~/.nvm/versions/node/v16.5.0/bin/npm
>     Watchman: 2022.12.05.00 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.11.3 - /Users/jenipharachel/.rbenv/shims/pod
>   SDKs:
>     iOS SDK:
>       Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
>     Android SDK: Not Found
>   IDEs:
>     Android Studio: Not Found
>     Xcode: 14.1/14B47b - /usr/bin/xcodebuild
>   Languages:
>     Java: 11.0.14 - /usr/bin/javac
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 17.0.2 => 17.0.2 
>     react-native: 0.67.1 => 0.67.1 
>     react-native-macos: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found

Paste the exact `react-native-track-player` version you are using
> 3.2.0
Real device? Or simulator? Android emulator but app crashes at this screen in real device.
What OS are you running?
macOS 13.0

**How I can Help**
What can you do to help resolve this? To tell me if I'm executing the code correctly.
Have you investigated the underlying JS or Swift/Android code causing this bug? No
Can you create a Pull Request with a fix? No

**Comment by jenipharachel** [comment]
I also tried adding async and await similar to the example app like below. But still facing the  `ERROR  TypeError: undefined is not an object (evaluating 'taskProvider()(data).then')`

```
useEffect(() => {
    async function run() {
      await setupPlayer();
    }
    run();
    () => resetPlayer();
 }, []);
```

**Comment by jspizziri** [comment]
@jenipharachel why are you not able to run the example app? What error are you getting?

**Comment by jenipharachel** [comment]
@jspizziri This is the error I'm facing.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-track-player:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-track-player:debugCompileClasspath'.
   > Failed to transform react-native-0.71.0-rc.0-debug.aar (com.facebook.react:react-native:0.71.0-rc.0) to match attributes {artifactType=android-symbol-with-package-name, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find react-native-0.71.0-rc.0-debug.aar (com.facebook.react:react-native:0.71.0-rc.0).
```

**Comment by jenipharachel** [comment]
@jspizziri Would you be able to help me with this error `(TypeError: undefined is not an object (evaluating 'taskProvider()(data).then'))`? It occurs only when the `await TrackPlayer.setupPlayer()` code is run. If I comment it out, then it works fine.

**Comment by jspizziri** [comment]
@jenipharachel The first thing required is to reproduce this in the example. Have you followed the instructions to install and build the root package before installing the packages in the example?

**Comment by jenipharachel** [comment]
@jspizziri I ran the example app and was not able to reproduce this issue. Is there a minimum react-native version for the `RNTP version 3.2.0`?  Also what version of RNTP would be suitable for `react-native version: 0.67.1`? 

The library works perfectly in iOS, so a little desperate to fix this issue to ship this feature in our app. Sorry to be taking your time.

**Comment by jspizziri** [comment]
@jenipharachel I think it should work with that version. However at the minimum you should upgrade to 0.67.5. In general I'd recommend an upgrade to a newer version as 0.67 is no longer supported by the react-native itself.

Closing this as a no-repro.

**Comment by jenipharachel** [comment]
For anyone who might across this, the issue was due to removing async from the service.js file. Fixed it by adding back the async keyword and disabling my eslint error.
