### ISSUE TITLE
[Android maybe iOS] pause on duck support

### ISSUE THREAD

**Issue by GrimDev** [doublesymmetry/react-native-track-player#1849]
Hi there !

**What is the need and use case of this feature?**
Currently, the only available audio focus option is the `alwaysPauseOnInterruption` boolean that behave as following :
- When true => If the audio focus is requested by another app, definitively pause the audio
- When false => If the audio focus is requested by another app, duck the audio till the focus is droppen out by the other application

My users would like the following behavior, that is the default behavior on some popular apps :
- If the audio focus is requested by another app, **pause** the audio and automatically restart when the focus is droppen out by the other application

I think this behavior is managed by `setWillPauseWhenDucked` android option, but not sure.

**Describe the ideal solution**
An option to enable the previously described behavior or access to the `OnAudioFocusChangeListener`
If it could also work on iOS it would be loving.

**Describe alternatives you've considered**
Dunno

**Additional context**
https://developer.android.com/reference/android/media/AudioFocusRequest.Builder#setWillPauseWhenDucked(boolean)

**How I can Help**
What can you do to help get this feature into production? Test
Can you assist by working on this feature and creating a Pull Request? Lack of knowledge to be able to

**Comment by jspizziri** [comment]
@GrimDev thanks for filing the feature request. All features that do not meet the following criteria go into the feature backlog for future consideration:

1. The feature is considered a high priority by the maintainers (examples below)
    - Strong vocal support from a large subset of the community
    - High priority to the maintainers for some other reason
2. There is a member of the community willing to do the implementation.

We'll revisit this once it meets the above criteria. I'd recommend looking into doing the implementation yourself, we'd be happy to review PRs.

Thanks!
