### ISSUE TITLE
Looping a single-track has a different behavior on Android and iOS

### ISSUE THREAD

**Issue by nahuelb** [doublesymmetry/react-native-track-player#1850]
**Describe the Bug**
Using `TrackPlayer.setRepeatMode(RepeatMode.Track)` to loop a track has a very small but noticeable gap on iOS when the audio finishes and starts again.
On Android there is no gap.

**Steps To Reproduce**

```
await TrackPlayer.add({
    url: audioUrl,
    ...metadata,
  });
await TrackPlayer.setRepeatMode(RepeatMode.Track);
await TrackPlayer.play();
```

**Environment Info:**
```
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 227.52 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.10.0/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/nahue/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 26, 27, 29, 30, 31, 33
      Build Tools: 27.0.3, 29.0.3, 30.0.2, 31.0.0
      System Images: android-24 | ARM 64 v8a, android-24 | ARM EABI v7a, android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-27 | Google Play Intel x86 Atom, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.5 => 0.68.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

react-native-track-player@3.2.0

Real device for Android: Pixel 4A
Simulator for iOS: iPhone 13

What OS are you running?

**How I can Help**
I am looking for a gapless experience when looping the audio, I would like to replicate the Android behavior on iOS.

I tried a different approach handling the looping myself this way:
```
// Before the sound finishes we start it again from the beginning with a fade in and fade out
TrackPlayer.addEventListener(Event.PlaybackProgressUpdated, async ({position, duration}) => {
  const shouldLoop = Math.round(position) + 1 === Math.round(duration);
  if (shouldLoop) await TrackPlayer.seekTo(0);
});
```

But the behavior is the same, after using `seekTo`, there is a very small gap before the audio starts again.

**Comment by jspizziri** [comment]
@nahuelb I don't see this as a bug, but rather an enhancement.

The proper solution for this would be a native update in SwiftAudioEx, JS isn't really going to cut it, so I'd recommend you start there.

All features that do not meet the following criteria go into the feature backlog for future consideration:

1. The feature is considered a high priority by the maintainers (examples below)
    - Strong vocal support from a large subset of the community
    - High priority to the maintainers for some other reason
2. There is a member of the community willing to do the implementation.

I'd recommend looking into doing the implementation yourself, we'd be happy to review PRs. If you open a PR for the issue I'll happily re-open it and move it out of the Feature backlog and into a concrete roadmap.

Thanks!

**Comment by robertgonzales** [comment]
@jspizziri I notice this is marked as completed, so does that mean it is implemented in the latest version? 

I have an app that uses v1 and have customers submitting bug reports that albums have a noticeable gap between each track.

**Comment by smachi** [comment]
We are experiencing the same issue with gaps on iOS...

**Comment by j-q-in-berlin** [comment]
We have the same issue.

**Comment by lovegaoshi** [comment]
swiftaudioEx did not choose to implement the repeat functionality natively. whether thats a designer choice or its simply because AVPlayer does not have this feature its beyond me. the way its done now is it listens for playbackEnd then wait for 2 frames and calls player.replay. of course you will hear some delays.

https://github.com/doublesymmetry/SwiftAudioEx/blob/42767039eb8e2a3caef81e39d4c66de26d6b9944/Sources/SwiftAudioEx/QueuedAudioPlayer.swift#L195

the fact nobody implemented this after 3 years shows how little interest this has. u can of course consult chatgpt to get you a solution, flaky or not.
