### ISSUE TITLE
[Feature Request] PlaybackQueueUpdated event

### ISSUE THREAD

**Issue by polsust** [doublesymmetry/react-native-track-player#1856]
**What is the need and use case of this feature?**
Sometimes you need to update the ui when the queue changes

**Describe the ideal solution**
I would add an event called PlaybackQueueUpdated that would fire everytime the queue is modified

**Comment by puckey** [comment]
I agree that this would be nice to have. Then we could make a `useQueue()` hook which would always return the up to date queue – and allow the native side to be the source of truth

**Comment by brightsider** [comment]
is this feature planned?
