### ISSUE TITLE
NativeEventemitter 

### ISSUE THREAD

**Issue by zuby64** [doublesymmetry/react-native-track-player#1858]
**Describe the Bug**
After installation of react-native-track-player it throughs an error of "new NativeEventEmitter requires a non null argument

**Steps To Reproduce**
Just installed react-native-track-player for react-native-tvos
import TrackPlayer from 'react-native-track-player'
Please provide a simple code example that allows others to replicate the bug.

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)?

**Environment Info:**
Paste the results of `npx react-native info`
Paste the exact `react-native-track-player` version you are using
Real device? Or simulator?
What OS are you running?

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

**Comment by taylorkangbeck** [comment]
You probably don't have the pods installed correctly (if on iOS). Are you using an Expo managed workflow? If so, you'll need to create a development build; you can't just use Expo Go because this package requires native Swift modules.

For future issues, the more info you provide the more easily others can help :)

**Comment by zuby64** [comment]
well, I was using it for tvos and I installed pod correctly went through
documentation so many times,seems like it has issue with react-native-tvos,
I am using bare react native cli

**Comment by bradleyflood** [comment]
Closing as stale for now. If still a problem please open a new Issue and follow the bug report template.  Thanks :)
