### ISSUE TITLE
Error while building app [EXPO]

### ISSUE THREAD

**Issue by oliuradu** [doublesymmetry/react-native-track-player#1859]
Verison of package:
 "react-native-track-player": "^3.2.0", (same error with 3.1.0)
Version of EXPO:
"expo": "^47.0.0",

Build properties:
"compileSdkVersion": 33,
"targetSdkVersion": 33,
"buildToolsVersion": "33.0.0"

This is the error:
![image](https://user-images.githubusercontent.com/42614946/209214574-54443e4d-2a20-4507-be97-c6adcb3b0455.png)

Failed to transform KotlinAudio-v1.2.4.aar (com.github.DoubleSymmetry:KotlinAudio:v1.2.4) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}

**Comment by Gnash-Obial** [comment]
Were you able to resolve this issue?

**Comment by bradleyflood** [comment]
Closing as stale for now. If still a problem please open a new Issue and follow the bug report template.  Thanks :)
