### ISSUE TITLE
PlaybackProgressUpdated not fired with useTrackPlayerEvents on andriod release build

### ISSUE THREAD

**Issue by m1heng** [doublesymmetry/react-native-track-player#1860]
**Describe the Bug**
PlaybackProgressUpdated not fired with useTrackPlayerEvents on andriod release build.
debug build works, useProgress works. 

**Steps To Reproduce**
How can someone else reproduce this bug?

**Code To Reproduce**
```ts
useTrackPlayerEvents(
        [Event.PlaybackProgressUpdated, Event.PlaybackTrackChanged, Event.PlaybackState],
        async (event) => {
            switch (event.type) {
                case Event.PlaybackTrackChanged:
                    // triggered
                    break;
                case Event.PlaybackProgressUpdated:
                    // not triggered on release build
                    break;
                case Event.PlaybackState:
                    // triggered
                    break;
            }
        },
    );
```
**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)?
not yet

**Environment Info:**
```
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 90.86 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.5 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.2 => 0.70.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
Paste the exact `react-native-track-player` version you are using - 3.2.0
Real device? Or simulator? - real device
What OS are you running? - Pixel 6a @ andriod 12

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug? In progress
Can you create a Pull Request with a fix? Not yet

**Comment by puckey** [comment]
Please retest this using `nightly` – will reopen if it still an issue for you.

**Comment by smn-snkl** [comment]
Can also confirm I can see the same behavior with nightly, but using the `TrackPlayer.addEventListener` function.

I also found the cause which was that the TrackPlayer.setup returned an error, but somehow still worked for playing content. In my case I wasn’t defining all the buffer props correctly
