### ISSUE TITLE
Error while building App [RN CLI]

### ISSUE THREAD

**Issue by faaiz99** [doublesymmetry/react-native-track-player#1862]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > 3 issues were found when checking AAR metadata:
     
       1.  Dependency 'androidx.core:core:1.9.0' requires libraries and applications that
           depend on it to compile against version 33 or later of the
           Android APIs.

           :app is currently compiled against android-31.

           Recommended action: Update this project to use a newer compileSdkVersion
           of at least 33, for example 33.

           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).

       2.  Dependency 'androidx.core:core-ktx:1.9.0' requires libraries and applications that
           depend on it to compile against version 33 or later of the
           Android APIs.

           :app is currently compiled against android-31.

           Recommended action: Update this project to use a newer compileSdkVersion
           of at least 33, for example 33.

           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).

       3.  Dependency 'androidx.annotation:annotation-experimental:1.3.0' requires libraries and applications that
           depend on it to compile against version 33 or later of the
           Android APIs.

           :app is currently compiled against android-31.

           Recommended action: Update this project to use a newer compileSdkVersion
           of at least 33, for example 33.

           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

Package.json 
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-firebase/app": "^16.5.0",
    "@react-native-firebase/auth": "^16.5.0",
    "@react-native-material/core": "^1.3.7",
    "@react-navigation/bottom-tabs": "^6.5.2",
    "@react-navigation/drawer": "^6.5.6",
    "@react-navigation/native": "^6.1.1",
    "@react-navigation/native-stack": "^6.9.7",
    "axios": "^1.2.1",
    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-reanimated": "^2.13.0",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
"react-native-track-player": "^3.2.0"
    "react-native-vector-icons": "^9.2.0"
},

Once I update my build.grade to 
        buildToolsVersion = "33.0.0"
     minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

I get this error after a successful compilation 

cannot resolve module import { View, Text, TouchableOpacity, StyleSheet, Button } from 'react-native'

**Comment by yaaliuzhipeng** [comment]
same here .....

**Comment by Koxx3** [comment]
same here too

**Comment by Koxx3** [comment]
I revert to version 3.1.0 and no issue.

**Comment by ITESaurabh** [comment]
+1
Same issue

**Comment by naodya** [comment]
@Koxx3 3.1.0 didn't work for me. Anybody else resolved this?

**Comment by naodya** [comment]
Okay, I found one workaround using `expo-build-properties`. Add `compileSdkVersion` and `targetSdkVersion` in "plugins" of `app.json`

```JSON
{
  "expo": {
    ...
    "plugins": [
      ...
      [
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 33,
            "targetSdkVersion": 33
          }
        }
      ]
    ]
    ...
  }
}
```

**Comment by faaiz99** [comment]
> Okay, I found one workaround using `expo-build-properties`. Add `compileSdkVersion` and `targetSdkVersion` in "plugins" of `app.json`
> 
> ```json
> {
>   "expo": {
>     ...
>     "plugins": [
>       ...
>       [
>         "expo-build-properties",
>         {
>           "android": {
>             "compileSdkVersion": 33,
>             "targetSdkVersion": 33
>           }
>         }
>       ]
>     ]
>     ...
>   }
> }
> ```

Maybe this works in expo but this doesn't works in Native CLI

**Comment by puckey** [comment]
Looks unrelated to rntp
