### ISSUE TITLE
[Feature Request] The url is dynamic not fixed

### ISSUE THREAD

**Issue by AIYO77** [doublesymmetry/react-native-track-player#1863]
**What is the need and use case of this feature?**
The url is not fixed and may expire. how to deal with

**Describe the ideal solution**
url can be a Promise method that returns an available url

**Describe alternatives you've considered**
Promises are the optimal solution in my opinion. Maybe you can provide another method to get dynamic url instead of fixed url

**Additional context**
![image](https://user-images.githubusercontent.com/22569270/209497784-717982ba-b0a0-4358-8932-685146abd808.png)

**How I can Help**
I should be able to assist in testing the feature; having a workflow in my app that would rely on it

**Comment by Amitkumarnile** [comment]
I have same issue faced

**Comment by bradleyflood** [comment]
Sounds like a good idea. I can see this being handy for S3 bucket urls and such.

I imagine it would be easy to code? Can you create a PR for this feature @AIYO77 or @ashish2583 or @Amitkumarnile

**Comment by izyspania** [comment]
any updates on this? i am in the same situation.

**Comment by izyspania** [comment]
I was looking for a fix server side  at the moment but ill take a look into this too maybe i can find an workaround as im not that familiar with the rntp code.
