### ISSUE TITLE
Is there a way to show next button if the track is the last on the queue ?

### ISSUE THREAD

**Issue by mustafakameldev** [doublesymmetry/react-native-track-player#1864]
Hi guys,
I recently updated react-native-track-player from 1.x.x to 3.2.0

But I found the next button of android notification disappears if the track is the last one,

Is there is a way to appear it even if it the last one ?

Thank you in advance.

**Comment by emzet93** [comment]
+1 would be nice to still have possibility to do some action on `next` press. Also I'm not even sure in which place in the code I should look for that logic to apply some patch.

**Comment by emzet93** [comment]
any updates here? Any hint about where to look in the code for applying patch package for that would be really appreciated 🙏

**Comment by puckey** [comment]
Could you retest this with the `nightly` version? You may want / need to set the repeat mode to queue

**Comment by puckey** [comment]
Will reopen if this is still deemed to be a problem.

**Comment by emzet93** [comment]
Didn't tried nightly version yet, but imho setting repeat mode is not a solution here.
Let's say I have a playlist and all the tracks are passed to RNTP queue. If queue ends, I want to do some action like play different playlist, so I don't want repeat mode to be enabled. I can do it by listening to queue end event, but I would also like to fire exactly the same action when user press "next" in notification center, while listening to the last track in queue.

So there is a conflict:
- if repeat mode is enabled, queue end event will never be fired
- if repeat mode is disabled, I don't have access to "next" button in notification center

I imagine that this scenario might be pretty common.

On iOS it's not a problem though - next button is always available. And it would be great to have the same behavior on both platforms.

Thanks!

**Comment by emzet93** [comment]
Just checked nightly version btw. Still no 'next' button for last track with repeat mode disabled.

**Comment by puckey** [comment]
Sorry this is the way the underlying exoplayer library handles capabilities and since it covers most use cases I don't think we will be working around it..

That being said, when repeat mode is enabled the next button will just be firing `Event.RemoteNext` and it is up to you what to do at this point.. you can also do something other than calling `next()`. See `PlaybackService.ts` in the example and replace `TrackPlayer.skipToNext();` with whatever you want.

**Comment by emzet93** [comment]
> Sorry this is the way the underlying exoplayer library handles capabilities and since it covers most use cases I don't think we will be working around it..
> 
> 
> 
> That being said, when repeat mode is enabled the next button will just be firing `Event.RemoteNext` and it is up to you what to do at this point.. you can also do something other than calling `next()`. See `PlaybackService.ts` in the example and replace `TrackPlayer.skipToNext();` with whatever you want.

Yep, I'll have next button that way but I'll loose possibility to listening for queue end event.

Anyway, thanks for clarification! 🙏
Now at least I know that I should think about different approach

**Comment by emzet93** [comment]
> Didn't tried nightly version yet, but imho setting repeat mode is not a solution here. Let's say I have a playlist and all the tracks are passed to RNTP queue. If queue ends, I want to do some action like play different playlist, so I don't want repeat mode to be enabled. I can do it by listening to queue end event, but I would also like to fire exactly the same action when user press "next" in notification center, while listening to the last track in queue.
> 
> So there is a conflict:
> 
> * if repeat mode is enabled, queue end event will never be fired and playlist will be looped
> * if repeat mode is disabled, I don't have access to "next" button in notification center
> 
> I imagine that this scenario might be pretty common.
> 
> On iOS it's not a problem though - next button is always available. And it would be great to have the same behavior on both platforms.
> 
> Thanks!

Hi there, I would like to come back with this issue. The scenario I described in quoted comment seems to be actually pretty common and with current API it seems not possible to implement on android.

Maybe fixing that should be worth considering?

Atm the only way I could work that around was to apply following hack to `PlaybackProgressUpdated` event:
- check if the track is last in queue
- if so, set repeat mode to `RepeatMode.Queue`, so the "play next" button is visible in notification center
- then check the progress, and for last 2 seconds change repeat mode to off, so `PlaybackQueueEnded` event is fired properly and queue is not restarted

It works but I imagine that there could be some edge cases leading to unexpected behaviour. Also "play next" button disappears for last 2 seconds when last track in queue is playing, but that's probably not a big deal.
