### ISSUE TITLE
Fixing: java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /data/user/0/com.imaanify/cache/TrackPlayer

### ISSUE THREAD

**Issue by abodsakah** [doublesymmetry/react-native-track-player#1865]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-track-player@3.2.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-track-player/android/build.gradle b/node_modules/react-native-track-player/android/build.gradle
index ad99343..a85a2ff 100644
--- a/node_modules/react-native-track-player/android/build.gradle
+++ b/node_modules/react-native-track-player/android/build.gradle
@@ -49,7 +49,7 @@ repositories {
 }
 
 dependencies {
-    implementation 'com.github.DoubleSymmetry:KotlinAudio:v1.2.4'
+    implementation 'com.github.DoubleSymmetry:KotlinAudio:dd4bdab147c90fffcff7800790dbfcb41291d29b'
 //    implementation "com.github.doublesymmetry:kotlin-audio:1.2.2"
 
     //noinspection GradleDynamicVersion
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by dennis-fritsch** [comment]
Thanks for this thread it solved the issue for us :) 

I've found another related thread with more informations: https://github.com/doublesymmetry/react-native-track-player/issues/296

**Comment by puckey** [comment]
Should be fixed in `nightly`.
