### ISSUE TITLE
fix (android): failing due to duplicated classes

### ISSUE THREAD

**Issue by tonisantosbalbi** [doublesymmetry/react-native-track-player#1867]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Issue:
The command `./gradlew assembleDebug assembleAndroidTest` was failing due to duplicated classes.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-track-player/android/build.gradle b/node_modules/react-native-track-player/android/build.gradle
index b696f69..36db067 100644
--- a/node_modules/react-native-track-player/android/build.gradle
+++ b/node_modules/react-native-track-player/android/build.gradle
@@ -22,6 +22,12 @@ def getExtOrIntegerDefault(name) {
 android {
     compileSdkVersion getExtOrIntegerDefault('compileSdkVersion')
 
+    configurations{
+        all { 
+            exclude group: "androidx.appcompat", module: "appcompat-resources"
+        }
+    }
+
     defaultConfig {
         minSdkVersion getExtOrIntegerDefault('minSdkVersion') // RN's minimum version
         targetSdkVersion getExtOrIntegerDefault('targetSdkVersion')
```

**Comment by Goldlightdrake** [comment]
Any progress on this issue?

**Comment by jspizziri** [comment]
@tonisantosbalbi @Goldlightdrake this seems more like an issue with you having another react-native library installed that uses a conflicting version of the library. For that reason, it would make sense that the patch shown above would resolve the issue.

As a result, this isn't something that is an issue with the library itself, but rather how you're using it. I don't know it's something that could be fixed for all cases.

If anyone disagrees please let me know why and what you think the proper fix is.
