### ISSUE TITLE
ReferenceError: Property 'track' doesn't exist

### ISSUE THREAD

**Issue by gallivangames** [doublesymmetry/react-native-track-player#1873]
**Describe the Bug**
When using  <pre>TrackPlayer.getTrack(index)</pre> it errors out with `ReferenceError: Property 'track' doesn't exist`

**Steps To Reproduce**
The player is playing a track on a component.  You leave the page (unmount) and it continues to play.  when you go back to the same page it is still playing.  In order to get the state of the component back  (playing / paused / id of item playing and so on) you need to get the track from TrackPlayer.   <pre>TrackPlayer.getCurrentTrack()</pre> correctly returns the index of the track.  in my case, 1.  using that index in <pre>TrackPlayer.getTrack(1)</pre> gives the error.

**Code To Reproduce**
<pre>useEffect(() => {
    console.debug('trying to reset narration or start a new one')
    const setup = async () => {
      let isSetup = await setupPlayer()
      setIsPlayerReady(isSetup)
      const index = await TrackPlayer.getCurrentTrack()
      console.debug('index of player', index)
      if (index) {
        const tack = await TrackPlayer.getTrack(index)
        console.debug('got the track', track)
        if (track) {
          const nar = narrations.find(narr => narr.id === track.id)
          console.debug('found a nar', nar)
          setNarration(nar)
          // do i need to set isAd / playing and all that here?
          if (track.advertisement_id) {
            setIsAd(true)
          } else {
            setIsAd(false)
          }
        }
      }
    }
    setup()
  }, [])
</pre>

**Environment Info:**
`System:
    OS: macOS 13.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.79 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.2.0 - /usr/local/bin/npm
    Watchman: 2022.12.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

Paste the exact `react-native-track-player` version you are using `3.2.0`
Real device? Or simulator? `iOS simulator`

**How I can Help**
What can you do to help resolve this? 
Have you investigated the underlying JS or Swift/Android code causing this bug? `this is my next step - to investigate the code`
Can you create a Pull Request with a fix?

**Comment by kaioduarte** [comment]
You have a typo in your code 🙃 

You declared `tack` and use `track` everywhere else. A linter or TypeScript would you help detect this.

```js
const tack = await TrackPlayer.getTrack(index)
console.debug('got the track', track)
```

**Comment by gallivangames** [comment]
dang it!  I have linter and once you pointed it out i could see it, it is extremely subtle in the editor.  maybe i can change it to be more obvious.  looked everywhere, spent hours on that before just removing the code.  now that it's back, i can use it in the background.  thanks for the assistance!
