### ISSUE TITLE
Get file duration before adding it to the track player 

### ISSUE THREAD

**Issue by FouadMagdy01** [doublesymmetry/react-native-track-player#1875]
Is there a way to get the duration from url before add it to the track player in order to enable remote seek, cause as you know remote seek won't work without providing duration property to the track object

**Comment by bradleyflood** [comment]
Not that I'm aware of. Either you have the duration stored somewhere on the remote server (ie as a meta JSON file for your library), or you download the whole file from which then the duration can be calculated.

**Comment by FouadMagdy01** [comment]
> Not that I'm aware of. Either you have the duration stored somewhere on the remote server (ie as a meta JSON file for your library), or you download the `whole` file from which then the duration can be calculated.


What about doing something like this
Const duration=TrackPlayer.getDuration()
And then update the metadata of the track

**Comment by FouadMagdy01** [comment]
`const duration = TrackPlayer.getDuration()`
