### ISSUE TITLE
react-native-track-player stays idle on Android, can't connect on iOS

### ISSUE THREAD

**Issue by YDaskaloff** [doublesymmetry/react-native-track-player#1876]
**Describe the Bug**
We use this library to play a radio stream in our app. The main issue is that on Android, the player won't run at all - the playback state remains 'idle'. 
In our product, the radio works fine on iOS, but in the dummy app I've provided below (which is a replica of our own app in terms of how the track-player is implemented), it doesn't work. It playback state remains 'Connecting'.

**Steps To Reproduce**
1. Following [this guide](https://blog.logrocket.com/react-native-track-player-complete-guide/) start a new react-native project with react-native version 0.68.1 and react-native-track-player version 3.2.0.
2. Implement the track-player as described in the guide.
3. Try to play the radio.
**OR**
Download and run the [dummy app](https://github.com/YDaskaloff/radiotest)

**Code To Reproduce**
```
const App = () => {
  const playbackState = usePlaybackState();
  const isOn = playbackState === State.Playing;

  const setupRadio = async () => {
    const isSetup = await streamSetupService();
    const queue = await TrackPlayer.getQueue();

    if (isSetup && queue.length <= 0) {
      await addRadioTrack();
    }
  };

  const playRadio = () => {
    // after first remote interruption of the stream it is not starting with Trackplayer.play()
    // instead of this it needs TrackPlayer.skipToNext() or TrackPlayer.skipToPrevious() to continue
    TrackPlayer.play();
    // TrackPlayer.skipToNext();
  };

  const toggleRadio = async () => {
    if (isOn) {
      TrackPlayer.pause();
      isAndroid && TrackPlayer.reset();
    } else {
      playRadio();
    }
  };

  useEffect(() => {
    setupRadio();
  }, []);
  
    console.log('+++', {playbackState});

  return (
    <SafeAreaView style={styles.backgroundStyle}>
      <Text>RADIO</Text>
      <TouchableOpacity
        style={[styles.button, isOn ? styles.buttonPause : styles.buttonPlay]}
        onPress={toggleRadio}>
        <Text style={styles.buttonTitle}>{isOn ? 'Pause' : 'Play'}</Text>
      </TouchableOpacity>
    </SafeAreaView>
  );
};
  ```

**Replicable on Example App?**
You can try out the dummy app I created to showcase this. In terms of react-native-track-player implementation, it is an exact replica of what we've implemented in our production app: [radiotest](https://github.com/YDaskaloff/radiotest)?

**Environment Info:**
System:
    OS: macOS 13.0.1
    CPU: (8) x64 Apple M1
    Memory: 20.80 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: Not Found
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
`react-native-track-player` version 3.2.0
Real device? Or simulator? - both
What OS are you running? - macOS 13.0.1

**Comment by kriptonhaz** [comment]
I also got this, with the same code base, it runs smoothly on ios but it keep idle on android and not playing anything

**Comment by Gnash-Obial** [comment]
Were you able to resolve this issue?

**Comment by YDaskaloff** [comment]
No, we're also still facing this issue

**Comment by Aggroid** [comment]
We have the same issue, can anyone give us a hand please ?

**Comment by martinmidtsund** [comment]
@YDaskaloff In your test repo your url is `url: 'http://mediaserv30.live-streams.nl:8086/live',` have you tried with a `httpS` stream to see if the problem persists? If you need to connect to http streams or e.g. podcasts you need to open up for http-traffic in both iOS and Android.

**Comment by YDaskaloff** [comment]
@martinmidtsund Thank you! It's unbelievable how sometimes we miss the smallest pieces

**Comment by harzh307** [comment]
im using https only by google drive but still not updating the player state

**Comment by AmmarKhan21** [comment]
Hi I'm getting this problem too even my url is https can anyone help me out with solutions?
https://cdn.islamic.network/quran/audio/64/ar.abdurrahmaansudais/3.mp3
Here is the url you can try yourself to. Ios is working fine just getting issue on android
