### ISSUE TITLE
The playback state becomes `paused` when firing `reset` on iOS

### ISSUE THREAD

**Issue by Mavludin** [doublesymmetry/react-native-track-player#1881]
**Describe the Bug**
On iOS devices, when I call the `reset()` function, the player's playback state becomes `paused`, while on Android devices it becomes `idle`.

**Steps To Reproduce**
Just run the app on any iOS emulator and fire the `reset()` function while playing an audio. Track the playback state through the `usePlaybackState()` hook and see how it changes.

**Code To Reproduce**
```
const state = usePlaybackState();

console.log({ state })
```

**Replicable on Example App?**
Yes

**Environment Info:**
`react-native:` "0.68.0"
`react-native-track-player:` "3.2.0"

`Simulators:` Android 11 and 12, IPhone 12 and 14
`OS:` Apple M1 Pro. Ventura 13.1 (22C65)

**Comment by puckey** [comment]
This is fixed in `nightly` which will be released as `4.0` in the coming weeks.

**Comment by Julius0505** [comment]
I have the same problem, but don't see 4.0 in public yet.
How can I use this version?
