### ISSUE TITLE
Player status is "stopped" after queue ends.

### ISSUE THREAD

**Issue by Malin88** [doublesymmetry/react-native-track-player#1884]
**Describe the Bug**
The tracking player state is "stopped" after the queue ends and when I click play again nothing happens, I have to press the play button a second time to play the queue again.

**Environment Info:**
react-native: "0.70.6"
react-native-track-player: "3.2.0"

**How I can Help**
Is there a way to reset the player's status to "ready", allowing me to play another loop by a single tap on the play button?

**Comment by bradleyflood** [comment]
Hi @Malin88 yes you will need to add tracks and call play again :)
