### ISSUE TITLE
Some pending callbacks that might have leaked by never being called from native code android only

### ISSUE THREAD

**Issue by tahaAlgoace** [doublesymmetry/react-native-track-player#1890]
**Describe the Bug**
When I play an audio the slider automatically moves and start blinking and screen stuck android onlya and this warning shown on my screen.
Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"3913":{},"3914":{},"3915":{},"3922":{},"3923":{},"3924":{},"3925":{},"3926":{},"3927":{},"3928":{},"3929":{},"3930":{},"3931":{},"3932":{"module":"TrackPlayerModule","method":"getDuration"},"3933":{"module":"TrackPlayerModule","method":"getBufferedPosition"},"3934":{"module":"TrackPlayerModule","method":"getPosition"},"3935":{},"3936":{},"3937":{},"3938":{},"3939":{},"3940":{},"3941":{},"3942":{},"3943":{},"3944":{"module":"TrackPlayerModule","method":"getDuration"},"3945":{"module":"TrackPlayerModule","method":"getBufferedPosition"},"3946":{"module":"TrackPlayerModule","method":"getPosition"},"3947":{},"3948":{},"3952":{},"3953":{},"3954":{},"3955":{},"3956":{},"3957":{},"3958":{},"3959":{"module":"TrackPlayerModule","method":"getDuration"},"3960":{"module":"TrackPlayerModule","method":"getBufferedPosition"},"3961":{"module":"TrackPlayerModule","method":"getPosition"},"3962":{},"3963":{},"3967":{},"3968":{},"3969":{},"3970":{},"3971":{},"3972":{},"3973":{},"3974":{},"...(truncated keys)...":451}

**Steps To Reproduce**
You can delete node modules and install again

**Environment Info:**
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 70.94 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    Watchman: 2022.10.31.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/algoace/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 30, 31, 33
      Build Tools: 21.1.2, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1
      System Images: android-30 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.5 => 0.66.5 
Paste the exact `react-native-track-player` version you are using
Real device
Android

**Comment by jspizziri** [comment]
@tahaAlgoace this sounds like an issue with your project, not the library itself. Please reproduce the issue by forking and creating a reproduction in the `example` project. If you can do that I'll reopen.
