### ISSUE TITLE
[Feature Request] Equalizer support, please!

### ISSUE THREAD

**Issue by 12343954** [doublesymmetry/react-native-track-player#1892]
RNTP, very nice libiary! everything works fine!

## Integrating an Equalizer will be more powerful! very appreciate it.

https://stackoverflow.com/questions/67255796/audio-equalizer-for-audio-notification-in-app-react-native-ios

<img src='https://i.stack.imgur.com/TKdlG.jpg' width=500 />

.

**Comment by puckey** [comment]
I want to add this to Radio Garden, so at some point in the future I will implement this. If you (or anyone) needs it before that time, I would be happy to review a pull request adding this functionality.

**Comment by puckey** [comment]
(you might want to remove the all-caps 'PLEASE' from the subject)

**Comment by 12343954** [comment]
thank you very much. waiting for your code.

**Comment by bradleyflood** [comment]
Thanks @12343954 we have this on our feature request list already. Might come in a future release :)

Thanks
