### ISSUE TITLE
How to call seekTo after track is ready and begin playing?

### ISSUE THREAD

**Issue by mitchdowney** [doublesymmetry/react-native-track-player#1903]
A persistent issue we've had in our app is when the user loads a podcast they previously listened partially to, there is a delay between when the track begins playing and the seekTo finishes and jumps to the correct resume time position. 

There are two different cases here...

1) When the user initiates playing the next item in the playlist (by pressing a play button on screen), we can handle the logic needed to load the track, wait until the track is ready, then call `seekTo`, then call `play`. That seems simple enough...

2) But how do we handle calling `seekTo` when the player automatically plays the next track in the playlist? As far as I understand it, our only option is to listen for the `Event.PlaybackActiveTrackChanged` event, and then call `seekTo` from there. The problem with that is it leads to a delay where the next track starts playing from the beginning, but then takes some time before `seekTo` is called and finishes.

Does anyone have advice on how we can handle 2) seamlessly? Since the seekTo needs to happen immediately, I wonder if it should be a part of the track object? When the track loads, seekTo that time before resuming playback?

Also, while 1) seems simple enough, when I start adding seekTo handling for 2) in the `Event.PlaybackActiveTrackChanged` listener, then the listener handler becomes a problem if the 1) seekTo handling is invoked outside the event listener, because the 2) event listener will also fire, and seekTo will happen twice, causing playback to studder.

**Comment by ouabing** [comment]
[`skip`](https://github.com/doublesymmetry/react-native-track-player/blob/1a5f83e6af0cf8d67a4305a9f4886777e875cf0b/docs/versioned_docs/version-3.2/api/functions/queue.md#skipindex-initialposition) takes an extra params `initialPosition`, hope this will help you.

As far as I know this method works only when the queue is not empty.

**Comment by mitchdowney** [comment]
@ouabing that is helpful and I didn't know that :)

That should be handy for case 1), but I don't think that `TrackPlayer.skip()` will help for case 2) because `skip` is never called, rather the next track in the playlist is "skipped" too by autoplaying after the previous track finishes playing.

**Comment by ouabing** [comment]
I remember I used to use the queue logic of RNTP, and do some patch work to support initial position in Track object. The patch is like [this](https://gist.github.com/gilbertl/82e3043fa5632ef653b274a2b86f59f2). Don't know if it's still working.

Now I'm using single item queue, I maintain the queue logic in my own code, and listen to `PlaybackQueueEnded` event. Once I receive the event, I manually add a new track to the queue and skip to it, then remove the previous track. So here I can control whether I should skip with a `initialPosition`.

**Comment by mitchdowney** [comment]
With the challenges we're dealing with, a single item queue makes a lot of sense. I've run into a few issues with trying to use both PlaybackQueueEnded and PlaybackActiveTrackChanged. 

It seems like a single item queue is a bit of a workaround though. I'm content with using one, but I wonder if there is a better solution for "set initialPosition in queue items." Maybe I could add it 🤔

Thanks so much for your help! I'll close this issue for now.

**Comment by martinmidtsund** [comment]
@mitchdowney We also have this use case, and this was discussed [here](https://github.com/doublesymmetry/react-native-track-player/pull/1413) and [here](https://github.com/DoubleSymmetry/react-native-track-player/pull/713) 

The outcome of those PR's will only cover your case nr 1 as you say. For case nr 2, skipping to a previously listened to position when queue is running in background, we have had to make some adjustments on iOS to make it work, and it seams to work just fine on Android with seeking before starting playback. As you suggest, we add the `initialTime` parameter to the track object, and check if OS === 'Android' and use `seek(initialTime)` before we start playback, or when the PlaybackTrackChanged event occurs.

On iOS we use this patch https://github.com/DoubleSymmetry/react-native-track-player/issues/387#issuecomment-709544925 to make the native player start at the correct position, to avoid the issue of track starting playback in the beginning, before seeking to correct position. This also require the `initialTime` parameter on the track objects of course.

I believe the best solution would be to have parity on Android and iOS with an `initialTime` parameter, but that seemed like it was difficult on ExoPlayer. This will perhaps be easier in the future, see the history in the links above.

**Comment by mitchdowney** [comment]
@martinmidtsund @ouabing thanks so much, this was an enormous help! I was able to get "seek on ready for playback" to work on both iOS and Android with your instructions! 🥳 The lack of this feature has been a very noticeable problem in our app for a long time now, so thanks again!
