### ISSUE TITLE
react native track player not use source mp3, use react native video 

### ISSUE THREAD

**Issue by voquangtin1997** [doublesymmetry/react-native-track-player#1904]
I am facing the same problem: I have a list of videos to play, I want a notification to control the playback.
Currently using react-native-music-control + react-native-video, glued together with redux. But it's currently filled with bugs and tends to desync fairly easily.
Is there a way to use this library manually? I.e. updating manually the progress, without an mp3 file?

**Comment by bradleyflood** [comment]
Hey @voquangtin1997 yep I migrated my app from those same projects, music-control and video. This repo does an excellent job :)

See the docs for more info https://react-native-track-player.js.org

**Comment by voquangtin1997** [comment]
when i use react native video and react native track player it has 2 audio sources, how can i use react native track player to control react native video's audio source @bradleyflood
