### ISSUE TITLE
[Feature Request] Accept float values for progressUpdateEventInterval

### ISSUE THREAD

**Issue by Pingou** [doublesymmetry/react-native-track-player#1916]
It would be nice to be able to have progress updates faster than one time per second. Obviously depending on the load they may not be emitted as accurately as wanted, but I would like to have them twice per second, which should be fine.

**Comment by puckey** [comment]
Passing `0.5` should work.

**Comment by Pingou** [comment]
@puckey Did you try on iOS?
It makes the app crashes.

Exception '*** -[AVPeriodicTimebaseObserver initWithTimebase:interval:queue:block:] invalid parameter not satisfying: ((Boolean)(CMTimeCompare(interval, kCMTimeZero) > 0))' was thrown while invoking updateOptions on target TrackPlayerModule with params

**Comment by jspizziri** [comment]
@Pingou this issue is probably [the result of this line of swift](https://github.com/doublesymmetry/react-native-track-player/blob/main/ios/RNTrackPlayer/RNTrackPlayer.swift#L340). If you're willing to open a PR for this enhancement I'll reopen this ticket.

**Comment by puckey** [comment]
https://github.com/doublesymmetry/react-native-track-player/pull/1939 should do the trick

**Comment by Pingou** [comment]
@puckey Thanks. It seems to me like on Android TrackPlayer.addEventListener(Event.PlaybackProgressUpdated does not work if interval is under 1.
