### ISSUE TITLE
[nightly] updateOptions does not keep previously set options

### ISSUE THREAD

**Issue by gavrichards** [doublesymmetry/react-native-track-player#1918]
**Describe the Bug**
Subsequent call to updateOptions is resetting a previously set option.
I am calling updateOptions and setting `appKilledPlaybackBehavior`, but when I call updateOptions again to set capabilities, the behaviour for `appKilledPlaybackBehavior` is returning to the default.
This is despite [the docs](https://react-native-track-player.js.org/docs/next/api/objects/update-options) stating "You also only need to specify the ones you want to update."

If you pass `appKilledPlaybackBehavior` every time you call updateOptions, the behavior is retained, suggesting there is a problem with merging the options.

**Steps To Reproduce**
1. Call TrackPlayer.updateOptions and set appKilledPlaybackBehavior to StopPlaybackAndRemoveNotification.
2. Call TrackPlayer.updateOptions again but set capabilities.
3. Notice that the behavior when swiping the app away on Android is it does not stop playback as expected.

**Code To Reproduce**
```
await TrackPlayer.updateOptions({
  android: {
    appKilledPlaybackBehavior:
      AppKilledPlaybackBehavior.StopPlaybackAndRemoveNotification,
  },
});

await TrackPlayer.updateOptions({
  capabilities: [
    TrackPlayerCapability.Play,
    TrackPlayerCapability.Stop,
  ],
  compactCapabilities: [
    TrackPlayerCapability.Play,
    TrackPlayerCapability.Stop,
  ],
});
```

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)? Not tested.

**Environment Info:**
Paste the results of `npx react-native info`
```
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 82.08 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 9.4.1 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/gav/.gem/ruby/2.7.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-28 | Google APIs ARM 64 v8a, android-29 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Electric Eel 2022.1.1 Patch 1 Electric Eel 2022.1.1 Patch 1
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Paste the exact `react-native-track-player` version you are using `3.2.0-c88c1cf470f4229dedf39dbb086f05bca60bce4c`
Real device? Or simulator? Real device - Samsung Galaxy S20
What OS are you running? Android 13

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

**Comment by puckey** [comment]
I took the first steps in fixing this here: https://github.com/doublesymmetry/react-native-track-player/pull/1920

Android has been fixed, but still needs to be tested.

iOS remains to be done.

**Comment by puckey** [comment]
I think there are still some issues here.. For example a property like `playIcon` which when set to a resource replaces the standard play icon in the Android notification.. After having set this to a value, how would you unset it again? @dcvz perhaps you have thoughts?

**Comment by puckey** [comment]
@dcvz I remember you wanted to look into this issue.. Have you been able to?

Otherwise we might want to change the docs to state that you need to provide the full options object after all.
