### ISSUE TITLE
[iOS] URL format results in ”Track is missing a required key"

### ISSUE THREAD

**Issue by henrik-funmed** [doublesymmetry/react-native-track-player#1925]
**Describe the Bug**
[A clear and concise description of what the bug is.]
On iOS, adding id, and URL formated like this `https://example.com/s/pAc4RpJbQKprzps/download/Stressad,%203%20min.mp3` to an object in the playlist makes the `TrackPlayer.add()` function throw ”Track is missing a required key”.

Renaming the URL to `'https://example.com/s/pAc4RpJbQKprzps/download/min.mp3’ ` makes it work.

**Code To Reproduce**
```
const url = 'https://example.com/s/pAc4RpJbQKprzps/download/Stressad,%203%20min.mp3’ ;
await TrackPlayer.add([
            {
              id: url,
              title,
              artist: ’Artist',
              genre: ’Genre',
              url,
              artwork: imageUrl,
            },
          ]);
```

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)?

**Environment Info:**
Paste the results of `npx react-native info`
```
System:
    OS: macOS 13.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 635.80 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.19.0/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v14.19.0/bin/npm
    Watchman: 2022.11.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/henrik/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
Paste the exact `react-native-track-player` version you are using
`3.2`

Real device? Or simulator? 
`Simulator`

**Comment by puckey** [comment]
I am not able to replicate this issue in nightly with the url you provided.. But seeing as it is a non-existing url, perhaps you could you give me a working example url to test with?

**Comment by henrik-funmed** [comment]
Sorry for not being able to give you the original file (it is an copy righted file from a third company), but my guess was that it was because the spaces and comma sign in the file name.

Regards, Henrik
________________________________

**Comment by s123121** [comment]
I can echo to this. This happened because of space sign in the file name. However, this is not always the case (some url work okay for me). I am on 3.2.0 so will try nightly to see if it got fix

**Comment by puckey** [comment]
If anyone wants to give me a working broken url, I will look into it : )

**Comment by bradleyflood** [comment]
@puckey here you go [https://evergraceapp.com/Stressad, 3 min.mp3](https://evergraceapp.com/Stressad,%203%20min.mp3)

This is the exact same file name as mentioned above.

But I wonder if the OP is actually passing an invalid URI? Perhaps he needs to be `encodeURI()`ing it?

OR, perhaps RNTP is decoding it and it's failing?

```node
> decodeURI('https://example.com/s/pAc4RpJbQKprzps/download/Stressad,%203%20min.mp3')

'https://example.com/s/pAc4RpJbQKprzps/download/Stressad, 3 min.mp3'
```

**Comment by puckey** [comment]
I was unable to replicate this in nightly using either `https://evergraceapp.com/Stressad, 3 min.mp3` `https://evergraceapp.com/Stressad,%203%20min.mp3`

@s123121 do you have an update from your side on this?

**Comment by puckey** [comment]
Will reopen if someone can provide a way to replicate this
