### ISSUE TITLE
[nightly] No event received in iOS when bluetooth disconnected

### ISSUE THREAD

**Issue by gianpietro1** [doublesymmetry/react-native-track-player#1926]
**Describe the Bug**
When music is playing through a bluetooth device, and suddenly the device is disconnected (powered-off or similar), Android receives a "paused" state as PlaybackState event, but iOS is not receiving an event at all, even though the music/player is actually paused.

**Steps To Reproduce**
1. Use the hook `useTrackPlayerEvents` including `Event.PlaybackState`, and log events.
2. Play music with bluetooth device, then power-off the device.
3. Music will stop and button will be paused at notification center, Android device will show the 'paused' state as PlaybackState event, but iOS will show nothing.

**Code To Reproduce**

```
 const events = [
    Event.PlaybackState,
    ...
  ];

  useTrackPlayerEvents(events, async data => {
    console.log(data);
    ...
  }
```

**Environment Info:**
react-native: 0.70.2
react-native-track-player: 3.2.0-4b83020b465d3e14f418e61e9f6043937d9410d5
Android 9.0 real device (API 28)
iPhone real device iOS 15.6.1

**Comment by puckey** [comment]
I wonder if this might be an underlying iOS bug.. Does it also occur in 3.2.0?

**Comment by puckey** [comment]
What does calling `await TrackPlayer.getPlaybackState()` give after the audio paused due to the bluetooth disconnecting?

**Comment by gianpietro1** [comment]
> I wonder if this might be an underlying iOS bug.. Does it also occur in 3.2.0?

I don't remember having the issue before, but to confirm, I just downgraded to 3.2.0 and tested, bug is not present there, both devices receive the "paused" state.

**Comment by puckey** [comment]
What kind of bluetooth device are you using? Would I be able to replicate using a pair of airpods?

**Comment by gianpietro1** [comment]
> What kind of bluetooth device are you using? Would I be able to replicate using a pair of airpods?

I've seen this with a car bluetooth, and an LG speaker: no event received at all on iOS.
Now I just tested with Airpods (2nd gen) and it's different: when I remove them from my ears, two events are triggered:
(1) RemotePause
(2) PlaybackState is "stopped"

**Comment by gianpietro1** [comment]
> What does calling `await TrackPlayer.getPlaybackState()` give after the audio paused due to the bluetooth disconnecting?

Just tested this, I'm still getting `{"state": "playing"}` in this situation (bluetooth device powered-off, music stops, notification button turned to 'play' icon, but no event received in the app)

**Comment by puckey** [comment]
I am able to replicate this issue using a pair of bluetooth headphones.

**Comment by puckey** [comment]
The following pr should fix this issue: https://github.com/doublesymmetry/SwiftAudioEx/pull/40

Thanks for reporting it!

**Comment by puckey** [comment]
Looks like the pr broke some tests – will need to fix those first before landing this.

**Comment by puckey** [comment]
Fixed in nightly
