### ISSUE TITLE
[Android] help with HLS

### ISSUE THREAD

**Issue by UmarLE** [doublesymmetry/react-native-track-player#1929]
**Describe the Bug**

Hello, I want to play hls file on player, I got a file in examples, it is playing well but when I placed my m3u8 file the player struck on connecting state. I checked both files on the browser the example one and mine. The both behave similar in browser means running smoothly. Kindly guide me what difference can be there.  Examplefile:    https://react-native-track-player.js.org/example/hls/whip/playlist.m3u8       Myfile:     https://ahtpublic.s3.eu-west-3.amazonaws.com/audio/unsecure/index.m3u8

**Steps To Reproduce**
How can someone else reproduce this bug?

**Code To Reproduce**
Please provide a simple code example that allows others to replicate the bug.

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)?

**Environment Info:**
Paste the results of `npx react-native info`
Paste the exact `react-native-track-player` version you are using
Real device? Or simulator?
What OS are you running?

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

**Comment by jspizziri** [comment]
@UmarLE , its generally a good practice to just put a short summary of your question as the title and use the issue body for the lengthy description. Take a look at how I've updated it.

**Comment by DennisdeWitNL** [comment]
I have tried to open your m3u8 in Safari on my iPhone 14 Pro Max. It shows the same problem as RNTP. It is loading forever and it doesn’t play. I saw the artwork, just no sound or whatsoever. 

I will check your m3u8 tomorrow to see if there’s anything wrong with the content of it.

**Comment by puckey** [comment]
Closing this since it doesn't look to be an rntp issue
