### ISSUE TITLE
No Media Control in Android after upgrading from v1 to v3

### ISSUE THREAD

**Issue by high-performance-hery** [doublesymmetry/react-native-track-player#1930]
**Describe the Bug**

We've just upgraded our player from v1 to v3, and when playing a track the media controls in the quick settings in Android are not showing anymore. We've followed the migrations step but there didn't seem to be anything related to the media controls.

The player in the iOS notification center is still showing as expected.

We haven't made any specific change with our implementation, and it worked prior to upgrading.

When upgrading we've had to bump the compile SDK from 31 to 33, so maybe it's a permission issue?

Or could it be related to the Kotlin migration?

**Steps To Reproduce**

Upgrade from v1 to v3 and play a track, if the background media controls were showing before, are they still showing?

**Replicable on Example App?**

No

**Environment Info:**

> System:
>     OS: macOS 12.6.1
>     CPU: (10) x64 Apple M1 Max
>     Memory: 291.66 MB / 64.00 GB
>     Shell: 5.8.1 - /bin/zsh
>   Binaries:
>     Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
>     Yarn: 1.17.3 - /opt/homebrew/bin/yarn
>     npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
>     Watchman: Not Found
>   Managers:
>     CocoaPods: 1.11.3 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
>     Android SDK:
>       API Levels: 28, 29, 30, 31, 33
>       Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0
>       System Images: android-33 | Google APIs ARM 64 v8a
>       Android NDK: Not Found
>   IDEs:
>     Android Studio: 2021.3 AI-213.7172.25.2113.9123335
>     Xcode: 14.2/14C18 - /usr/bin/xcodebuild
>   Languages:
>     Java: Not Found
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 17.0.2 => 17.0.2
>     react-native: 0.68.5 => 0.68.5
>     react-native-macos: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found

>     "react-native-track-player": "3.2.0",

Real device? Or simulator?

> Both

What OS are you running?

> Android 11 and android 13

**Comment by puckey** [comment]
use the nightly version – which is close to becoming the next major version.. see the migration instructions in the docs directory

**Comment by high-performance-hery** [comment]
Thank you @puckey, it didn't work however.

Using nightly set the version to `"react-native-track-player": "^3.2.0-4b83020b465d3e14f418e61e9f6043937d9410d5"`,
but the Media Controls are still not showing.

There's definitely nothing else to set up after migrating from v1? I can try downgrading to the v2 to see if that fixes it.

**Comment by high-performance-hery** [comment]
Media controls do show when downgrading to `2.1.4`.

**Comment by puckey** [comment]
Perhaps take a look at the example app..

**Comment by high-performance-hery** [comment]
I have but I haven't found anything related to this. I think we'll be staying on `2.1.4` for now until this gets more stable.

**Comment by high-performance-hery** [comment]
Hi @puckey, I'm looking into upgrading to the v3 so we can keep getting the latest fixes and wrap up this upgrade.

This is how we're setting up our track player, can you see anything wrong here?

```
TrackPlayer.setupPlayer({
    iosCategoryMode: IOSCategoryMode.SpokenAudio,
})

const capabilities = [Capability.Play, Capability.Pause, Capability.SeekTo]

if (Platform.OS === 'android') {
    // want stop here because it's annoying you can't dismiss the notification
    // e.g. Calm do this
    capabilities.push(Capability.Stop)
}

if (JUMP_CONTROLS_ENABLED) {
    capabilities.push(Capability.JumpBackward, Capability.JumpForward)
}

const options = {
    android: {
        appKilledPlaybackBehavior: AppKilledPlaybackBehavior.ContinuePlayback,
    },
    // this forces the android app (which on android 9 > automatically ducks the volume)
    // to trigger the `remote-duck` event
    alwaysPauseOnInterruption: true,
    // An array of media controls capabilities
    capabilities,

    // An array of capabilities that will show up when the notification is in the compact form
    compactCapabilities: capabilities,
    icon: Images.androidAudioPlayerIcon,
}

if (JUMP_CONTROLS_ENABLED) {
    // eslint-disable-next-line
    options['jumpInterval'] = AUDIO_JUMP_INTERVAL
}

TrackPlayer.updateOptions(options)
```

**Comment by ghiculescualexandru** [comment]
Do you have a single track in the queue?

**Comment by high-performance-hery** [comment]
@ghiculescualexandru it's possible it was the case when I tested, do you think that could be the issue?

**Comment by ghiculescualexandru** [comment]
@high-performance-hery indeed, on android, if you only have a single track in the queue, the skip to next and skip to previous buttons won't occur, because the queue considers it has no other tracks. You can work around by always adding the same track twice
