### ISSUE TITLE
Remove player controls from lock screen / notification

### ISSUE THREAD

**Issue by R0LLeX** [doublesymmetry/react-native-track-player#1933]
Hi guys, thank you very much for your work. The fact is that listening to music is not the main function of my application and I would like to remove the player controller from the phone lock screen /notifications when the user closes the player in the application and switches to another screen. Is it possible to implement this in the RNTP-nightly version?

**Comment by puckey** [comment]
Doesn't calling `TrackPlayer.reset()` do this?

**Comment by R0LLeX** [comment]
In my case, I'm trying to call TrackPlayer.reset() when unmounting the player components, but this has no effect, and I can still turn on the track by clicking on the play.

**Comment by puckey** [comment]
Please create a fork of the example app that demonstrates this issue.

**Comment by puckey** [comment]
A quick test shows me that calling `TrackPlayer.reset()` does indeed close the notification... Please provide other instructions to replicate your issue.

**Comment by R0LLeX** [comment]
I updated the night version, and now reset() works as it should

**Comment by watadarkstar** [comment]
I'm also having the same issue on 3.2. After calling `TrackPlayer.reset()` the controls are still showing up in the notification tray on iOS.

**Comment by kamil-rusin** [comment]
> I'm also having the same issue on 3.2. After calling `TrackPlayer.reset()` the controls are still showing up in the notification tray on iOS.

Did you manage to fix it somehow? I've also encountered the same problem.

**Comment by watadarkstar** [comment]
@kamil-rusin I don't remember exactly if I fixed it but I have this:

```
  useEffect(() => {
    return () => {
      // when the app gets killed we need to reset the player
      // https://github.com/doublesymmetry/react-native-track-player/issues/813#issuecomment-625844883
      MediaPlayerController.reset()
    }
  }, [])
```
