### ISSUE TITLE
Remote Events not working

### ISSUE THREAD

**Issue by appicsol** [doublesymmetry/react-native-track-player#1937]
**Index.js**
import {AppRegistry, Text} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import TrackPlayer from 'react-native-track-player';
import {PlayBackService} from './service';

AppRegistry.registerComponent(appName, () => App);
TrackPlayer.registerPlaybackService(() => PlayBackService)

**Service.ts** 
import TrackPlayer, { Event } from 'react-native-track-player';

export const PlayBackService = async () => {
  TrackPlayer.addEventListener(Event.RemotePlay, () => TrackPlayer.play());
  TrackPlayer.addEventListener(Event.RemotePause, () => TrackPlayer.pause());
  TrackPlayer.addEventListener(Event.RemoteStop, () => TrackPlayer.destroy());
  TrackPlayer.addEventListener(Event.RemoteNext, () => {
    TrackPlayer.skipToNext();
  });
  TrackPlayer.addEventListener(Event.RemotePrevious, () => {
    TrackPlayer.skipToPrevious();
  });
};

Buttons in the notification is not working. Some times it works (only the pause button). Most of the time is does not work.

**Comment by puckey** [comment]
please follow the issue template
