### ISSUE TITLE
Notification controls not working

### ISSUE THREAD

**Issue by appicsol** [doublesymmetry/react-native-track-player#1941]
# Notification controls not working

## Index.js

`import {AppRegistry, Text} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import TrackPlayer from 'react-native-track-player';
import {PlayBackService} from './service';

AppRegistry.registerComponent(appName, () => App);
TrackPlayer.registerPlaybackService(() => PlayBackService)`

## Service.ts (playbackService file)

`import TrackPlayer, { Event } from 'react-native-track-player';

export const PlayBackService = async () => {
TrackPlayer.addEventListener(Event.RemotePlay, () => TrackPlayer.play());
TrackPlayer.addEventListener(Event.RemotePause, () => TrackPlayer.pause());
TrackPlayer.addEventListener(Event.RemoteStop, () => TrackPlayer.destroy());
TrackPlayer.addEventListener(Event.RemoteNext, () => {
TrackPlayer.skipToNext();
});
TrackPlayer.addEventListener(Event.RemotePrevious, () => {
TrackPlayer.skipToPrevious();
});
};`

Following the documentation, I am using this code but not getting the work done

**Comment by puckey** [comment]
You may want to look at the example app for your implementation.

For community support please use our discord: https://discord.com/invite/ya2XDCR

**Comment by appicsol** [comment]
> You may want to look at the example app for your implementation.
> 
> For community support please use our discord: https://discord.com/invite/ya2XDCR
I did but didn't find any reply. Need the solution ASAP.
