### ISSUE TITLE
Issue while trying to build project

### ISSUE THREAD

**Issue by Vincenttbk** [doublesymmetry/react-native-track-player#1942]
**Describe the Bug**
Not sure if this is the right place to enquire about this issue.
Seems when I am trying to build my project I will get this issue

`
Execution failed for task ':react-native-track-player:generateReleaseRFile'.
--
Could not resolve all files for configuration ':react-native-track-player:releaseCompileClasspath'.
Failed to transform KotlinAudio-dd4bdab147c90fffcff7800790dbfcb41291d29b.aar (com.github.DoubleSymmetry:KotlinAudio:dd4bdab147c90fffcff7800790dbfcb41291d29b) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
 Could not find KotlinAudio-dd4bdab147c90fffcff7800790dbfcb41291d29b.aar (com.github.DoubleSymmetry:KotlinAudio:dd4bdab147c90fffcff7800790dbfcb41291d29b).
 Searched in the following locations:
https://www.jitpack.io/com/github/DoubleSymmetry/KotlinAudio/dd4bdab147c90fffcff7800790dbfcb41291d29b/KotlinAudio-dd4bdab147c90fffcff7800790dbfcb41291d29b.aar

`
Previously I followed the steps and ran a patch for the library, not sure if this will cause any issue
https://github.com/doublesymmetry/react-native-track-player/issues/296

**Steps To Reproduce**
just do a gradle assemble

**Code To Reproduce**
N.A

**Replicable on Example App?**
N.A

**Environment Info:**
on the CI environment

**How I can Help**
May need help to see if there is anyway to put back the AAR file

**Comment by oddlyspaced** [comment]
The url for 
https://www.jitpack.io/com/github/DoubleSymmetry/KotlinAudio/dd4bdab147c90fffcff7800790dbfcb41291d29b/

seems to be messed up on their server,

on a separate note, a different version for the seemingly same commit hash is working fine :
https://www.jitpack.io/com/github/DoubleSymmetry/KotlinAudio/dd4bdab147c90fffcff7800790dbfcb41291d29/

[last letter b is different]

could possibly solve your build issues for the time.

**Comment by AronBe** [comment]
Got `Execution failed for task ':react-native-track-player:generateReleaseRFile'.` as well

**Comment by tsheaff** [comment]
Whoah, crazy, super big ups for the solution @oddlyspaced 🙌 

Why is the diff the same for these two commits but the hash is one letter off? This violates all of my priors about how commit hashes work:

* https://github.com/doublesymmetry/KotlinAudio/commit/dd4bdab147c90fffcff7800790dbfcb41291d29
* https://github.com/doublesymmetry/KotlinAudio/commit/dd4bdab147c90fffcff7800790dbfcb41291d29b

**Comment by Vincenttbk** [comment]
Thank you! Seems like it is building correctly after i changed the reference in the patch file :)

**Comment by jspizziri** [comment]
@dcvz this is... quite strange. My guess is that its some problem with jitpack, but want to make sure it's not the build process.

In a nutshell

[dd4bdab147c90fffcff7800790dbfcb41291d29b](https://github.com/doublesymmetry/KotlinAudio/commit/dd4bdab147c90fffcff7800790dbfcb41291d29b) is a real commit, however [it doesn't exist on Jitpack](https://www.jitpack.io/com/github/DoubleSymmetry/KotlinAudio/dd4bdab147c90fffcff7800790dbfcb41291d29b/)

Simultaneoulsy [dd4bdab147c90fffcff7800790dbfcb41291d29](https://github.com/doublesymmetry/KotlinAudio/commit/dd4bdab147c90fffcff7800790dbfcb41291d29) is a valid commit sha too (only different by the missing `b` from the previous commit). This sha however [does exist on jitpack](https://www.jitpack.io/com/github/DoubleSymmetry/KotlinAudio/dd4bdab147c90fffcff7800790dbfcb41291d29/)

Regardless I'm going to close this issue as we're not pointing at that version of KotlinAudio anymore, so it should be resolved in the latest version.

**Comment by AronBe** [comment]
Anyone experiencing an issue again? I see few changes have been made in the last hour, wonder if it invalidated the patch?

```
[stderr] 
Could not determine the dependencies of task ':app:buildReleasePreBundle'.
[stderr] 
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
[stderr] 
   > Could not find com.github.DoubleSymmetry:KotlinAudio:dd4bdab147c90fffcff7800790dbfcb41291d29.
 ```

**Comment by Vincenttbk** [comment]
it is not working for me :(
