### ISSUE TITLE
Android crashes on opening

### ISSUE THREAD

**Issue by aakashr143** [doublesymmetry/react-native-track-player#1943]
**Describe the Bug**
Everything works fine on iOS, but on android the app crashes on opening.

I tried building a new project and install track player. Everything works fine then. 

**package.json dependancies**
  "@miblanchard/react-native-slider": "^2.3.0",
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-firebase/analytics": "^16.7.0",
    "@react-native-firebase/app": "^16.7.0",
    "@react-native-firebase/auth": "^16.7.0",
    "@react-native-firebase/firestore": "^16.7.0",
    "@react-native-firebase/messaging": "^16.7.0",
    "@react-navigation/bottom-tabs": "^6.5.3",
    "@react-navigation/native": "^6.1.2",
    "@react-navigation/stack": "^6.3.11",
    "firebase": "^9.17.1",
    "react": "18.2.0",
    "react-native": "0.71.3",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-image-picker": "^5.0.1",
    "react-native-keep-awake": "^4.0.0",
    "react-native-keyboard-accessory": "^0.1.16",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-media-console": "^2.0.6",
    "react-native-modalize": "^2.1.1",
    "react-native-orientation": "^3.1.3",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.19.0",
    "react-native-shared-element": "^0.8.8",
    "react-native-track-player": "^3.2.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-video": "^5.2.1",
    "react-native-webview": "^11.26.1",
    "react-native-youtube-iframe": "^2.2.2",
    "react-navigation-shared-element": "^3.1.3",
    "shorthash": "^0.0.2"

**npm run android**
> Configure project :react-native-firebase_analytics
:react-native-firebase_analytics package.json found at /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/@react-native-firebase/analytics/package.json
:react-native-firebase_app package.json found at /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_analytics:firebase.bom using default value: 31.1.1
:react-native-firebase_analytics package.json found at /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/@react-native-firebase/analytics/package.json
:react-native-firebase_analytics:version set from package.json: 16.7.0 (16,7,0 - 16007000)
:react-native-firebase_analytics:android.compileSdk using custom value: 33
:react-native-firebase_analytics:android.targetSdk using custom value: 33
:react-native-firebase_analytics:android.minSdk using custom value: 21
:react-native-firebase_analytics:reactNativeAndroidDir /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/react-native/android

> Configure project :react-native-firebase_app
:react-native-firebase_app package.json found at /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:firebase.bom using default value: 31.1.1
:react-native-firebase_app:play.play-services-auth using default value: 20.3.0
:react-native-firebase_app package.json found at /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:version set from package.json: 16.7.0 (16,7,0 - 16007000)
:react-native-firebase_app:android.compileSdk using custom value: 33
:react-native-firebase_app:android.targetSdk using custom value: 33
:react-native-firebase_app:android.minSdk using custom value: 21
:react-native-firebase_app:reactNativeAndroidDir /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/react-native/android

> Configure project :react-native-firebase_auth
:react-native-firebase_auth package.json found at /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/@react-native-firebase/auth/package.json
:react-native-firebase_app package.json found at /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_auth:firebase.bom using default value: 31.1.1
:react-native-firebase_auth package.json found at /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/@react-native-firebase/auth/package.json
:react-native-firebase_auth:version set from package.json: 16.7.0 (16,7,0 - 16007000)
:react-native-firebase_auth:android.compileSdk using custom value: 33
:react-native-firebase_auth:android.targetSdk using custom value: 33
:react-native-firebase_auth:android.minSdk using custom value: 21
:react-native-firebase_auth:reactNativeAndroidDir /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/react-native/android

> Configure project :react-native-firebase_firestore
:react-native-firebase_firestore package.json found at /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/@react-native-firebase/firestore/package.json
:react-native-firebase_app package.json found at /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_firestore:firebase.bom using default value: 31.1.1
:react-native-firebase_firestore package.json found at /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/@react-native-firebase/firestore/package.json
:react-native-firebase_firestore:version set from package.json: 16.7.0 (16,7,0 - 16007000)
:react-native-firebase_firestore:android.compileSdk using custom value: 33
:react-native-firebase_firestore:android.targetSdk using custom value: 33
:react-native-firebase_firestore:android.minSdk using custom value: 21
:react-native-firebase_firestore:reactNativeAndroidDir /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/react-native/android

> Configure project :react-native-firebase_messaging
:react-native-firebase_messaging package.json found at /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/@react-native-firebase/messaging/package.json
:react-native-firebase_app package.json found at /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_messaging:firebase.bom using default value: 31.1.1
:react-native-firebase_messaging package.json found at /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/@react-native-firebase/messaging/package.json
:react-native-firebase_messaging:version set from package.json: 16.7.0 (16,7,0 - 16007000)
:react-native-firebase_messaging:android.compileSdk using custom value: 33
:react-native-firebase_messaging:android.targetSdk using custom value: 33
:react-native-firebase_messaging:android.minSdk using custom value: 21
:react-native-firebase_messaging:reactNativeAndroidDir /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/react-native/android
WARNING:The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (30.0.3) for Android Gradle Plugin 7.3.1.
Android SDK Build Tools 30.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':react-native-gesture-handler', ':react-native-screens'

> Task :react-native-track-player:processDebugManifest
package="com.doublesymmetry.trackplayer" found in source AndroidManifest.xml: /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/react-native-track-player/android/src/main/AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace
This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

> Task :react-native-track-player:compileDebugKotlin
w: /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/module/MusicModule.kt: (7, 47): 'LocalBroadcastManager' is deprecated. Deprecated in Java
w: /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/module/MusicModule.kt: (179, 23): 'LocalBroadcastManager' is deprecated. Deprecated in Java
w: /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt: (11, 47): 'LocalBroadcastManager' is deprecated. Deprecated in Java
w: /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt: (106, 13): 'stoppingAppPausesPlayback: Boolean' is deprecated. This will be removed soon
w: /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt: (107, 17): 'stoppingAppPausesPlayback: Boolean' is deprecated. This will be removed soon
w: /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt: (467, 9): 'LocalBroadcastManager' is deprecated. Deprecated in Java
w: /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/utils/BundleUtils.kt: (16, 19): 'get(String!): Any?' is deprecated. Deprecated in Java
w: /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/utils/BundleUtils.kt: (45, 19): 'get(String!): Any?' is deprecated. Deprecated in Java
w: /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/utils/BundleUtils.kt: (105, 21): 'get(String!): Any?' is deprecated. Deprecated in Java
w: /Users/aakashrathee/Documents/Projects/RavishKumar/RavishKumarApp/node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/utils/BundleUtils.kt: (112, 21): 'get(String!): Any?' is deprecated. Deprecated in Java

> Task :app:installDebug
Installing APK 'app-debug.apk' on 'Pixel_XL_API_33(AVD) - 13' for :app:debug
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings

**Environment Info:**
System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 748.25 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/aakashrathee/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

react-native-track-player: 3.2.0
Real device? Or simulator: Both

**Comment by MasterTeus** [comment]
I also have the same problem, it's been 2 days that I'm trying to solve it

**Comment by jspizziri** [comment]
@aakashr143 @MasterTeus as this issue is written, there is no information about the crash you're reporting is happening at runtime. The only logs you've provided are build-time. On top of that, based on your report it sounds like you have a larger problem with your RN project that is unrelated to this particular library.

Please try to reproduce this in the example app. If you can do so I'll reopen. If you can provide specific and compelling runtime crash reports that indicate an error with the library I'll also reopen.

**Comment by roun512** [comment]
There is actually an issue with the package, the same was happening to us and it worked normally after removing the package. It happens on Android only. Not sure why, but I'll try to lower the package until it works if it does at all

**Comment by anthony23991** [comment]
facing also the same issue showing this error on runtime:
undefined is not an object (evaluating 'i()(o).then')
