### ISSUE TITLE
Audio Equalizer

### ISSUE THREAD

**Issue by puckey** [doublesymmetry/react-native-track-player#1950]
**What is the need and use case of this feature?**
A multiband equalizer is a popular functionality in audio players that allows users to adjust the levels of different frequency ranges (or "bands") within an audio signal independently of one another. This means that users can boost or cut specific frequencies in order to shape the overall tonal balance of the sound.

**Describe the ideal solution**
Offer the ability to equalize the audio by passing an array of frequency values to a function like `AudioPlayer.setEqualizer()`. We could also have `AudioPlayer.enableEqualizer()` and `AudioPlayer.disableEqualizer()`.

On iOS we would use: [AVAudioUnitEQ ](https://developer.apple.com/documentation/avfaudio/avaudiouniteq)

On Android we would probably use [android.media.audiofx.Equalizer ](https://developer.android.com/reference/android/media/audiofx/Equalizer)

**How I can Help**
I can implement it.

**Comment by puckey** [comment]
pr for android implementation is here: https://github.com/doublesymmetry/react-native-track-player/pull/1962

**Comment by SumailaBello** [comment]
Why did this feature not get implemented?
