### ISSUE TITLE
Sleep Timer

### ISSUE THREAD

**Issue by puckey** [doublesymmetry/react-native-track-player#1951]
**What is the need and use case of this feature?**
A sleep timer is a feature that allows the user to set a predetermined amount of time for the audio to play before it automatically stops playing. This feature is often used by people who like to listen to music, audiobooks, or podcasts while falling asleep, as it allows them to do so without having to worry about manually turning off the audio when they fall asleep. (and [waking up only being able to say one thing](https://youtu.be/2kArCRjT29w?t=76), in Dexter's case)

The sleep timer function typically allows the user to select a duration for the timer, ranging from a few minutes to several hours. Once the timer is set, the audio will play for the designated amount of time and then automatically stop playing when the timer runs out. You can also specify that the sleep timer should cause playback to stop at the end of the current track.

This feature is often included in audio apps such as music players, podcast players, and audiobook apps, and can be accessed through the app's settings or playback controls.

**Describe the ideal solution**
We can implement it as:

```ts
export type SleepTimer =
  | { time: number }
  | { sleepWhenPlayedToEnd: boolean }
  | null;

/**
 * Sets a sleep timer to fire after a specified amount of seconds.
 *
 * Note that if a sleep timer was set previously, it will be replaced by the
 * new one.
 */
export async function setSleepTimer(seconds: number): Promise<SleepTimer> {
  if (seconds <= 0) {
    throw new Error('The sleep timer must be greater than 0.');
  }
  return TrackPlayer.setSleepTimer(seconds);
}

/**
 * Pauses playback when the active track ends. Note that this will override any
 * sleep timer that was set previously. To clear call `TrackPlayer.clearSleepTimer()`.
 */
export async function sleepWhenActiveTrackReachesEnd(): Promise<void> {
  return TrackPlayer.sleepWhenActiveTrackReachesEnd();
}

/**
 * Gets information on the current sleep timer. Returns `null` if there is no
 * sleep timer set.
 */
export async function getSleepTimer(): Promise<SleepTimer> {
  return (await TrackPlayer.getSleepTimer()) ?? undefined;
}

/**
 * Clears the sleep timer if it was set previously.
 *
 * Note that it is not necessary to clear the sleep timer before setting a new
 * one.
 */
export async function clearSleepTimer(): Promise<void> {
  return TrackPlayer.clearSleepTimer();
}
```

We might also want to add a `sleepTimer` property to the `TrackPlayer.getProgress()` / `TrackPlayer.useProgress()` functionalities.

**How I can Help**
I already implemented this in my monster queue pr, but we removed it to avoid complexity. I am happy to make a new pr for this functionality, but we should decide whether it only goes into RNTP or if the native implementations should go into `KotlinAudio` and `SwiftAudioEx`

**Comment by s123121** [comment]
FWIW, I have success implement this feature with playback-progress-updated and redux.
```
TrackPlayer.addEventListener('playback-progress-updated', data => {
    const store = getStore()
    if (store) {
      const { trackMeta } = store.getState()
      if (trackMeta.sleep && trackMeta.sleep <= Math.floor(Date.now() / 1000)) {
        TrackPlayer.pause()
        store.dispatch(updateTrackMeta({ sleep: 0 }))
      }
    }
  })
  ```

**Comment by puckey** [comment]
pr for ios/android sleep timer functionality: https://github.com/doublesymmetry/react-native-track-player/pull/1973

**Comment by bradleyflood** [comment]
What if we offered this as a "Recipe" so to speak, instead of making it (yet) another feature of RNTP to maintain.

The slimmer we can keep this module the better.

I honestly wouldn't use this - I have my own sleep timer logic that differs from this. And I don't see this needing to be part of the core RNTP - it's just a recipe that anyone could use if they want.

Thoughts?
