### ISSUE TITLE
Can't run example app with local KotlinAudio. Type com.doublesymmetry.trackplayer.utils.BundleUtils is defined multiple times

### ISSUE THREAD

**Issue by mitchdowney** [doublesymmetry/react-native-track-player#1956]
**Describe the Bug**
I try to follow the steps exactly in the [RNTP example app readme](https://github.com/doublesymmetry/react-native-track-player/tree/main/example), while using local KotlinAudio, but I get the following error every time:

> Type com.doublesymmetry.trackplayer.utils.BundleUtils is defined multiple times: /Users/mitch/Repos/react-native-track-player/android/build/.transforms/3fb4316e0ca8a525992dbdac677a1a97/transformed/debug/com/doublesymmetry/trackplayer/utils/BundleUtils.dex, /Users/mitch/Repos/react-native-track-player/example/node_modules/react-native-track-player/android/build/.transforms/b0d5b25d12d32d2575201fe59834a7bd/transformed/debug/com/doublesymmetry/trackplayer/utils/BundleUtils.dex

full error log: https://gist.github.com/mitchdowney/da147d9915aceaa1cbe36aa514461ede

**Steps To Reproduce**
1) Clone KotlinAudio locally.
2) `cd ./KotlinAudio`
3) `./gradlew -x test build publishToMavenLocal`
4) `cd ..`
5) Clone react-native-track-player locally.
6) Open KotlinAudio/kotlin-audio/build.gradle, and change to the following:
```
dependencies {
    // implementation 'com.github.doublesymmetry:kotlinaudio:v2.0.0-rc4'
    // used when building against local maven
    implementation "com.github.doublesymmetry:kotlin-audio:2.0.0"

    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"

    // Make sure we're using androidx
    implementation "androidx.core:core-ktx:1.9.0"
    implementation "androidx.localbroadcastmanager:localbroadcastmanager:1.1.0"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.3"
}
```
7) The instructions say to "Add mavenLocal() to example/android/build.gradle" but it looks like `mavenLocal()` is already there, so I don't do anything for this step.
8) `cd ./example`
9) `yarn add file:..`
10) `cd ..`
11) `yarn`
12) `yarn build`
13) `cd ./example`
14) `yarn android`

I then get the error I shared the logs with above. 

Those are the last sequence of steps I have used. I have also tried going from top to bottom of the example README (where RNTP modules are installed before local KotlinAudio steps are completed), but I get the same error result.

I also tried `yarn cache clean` before running all steps, but get the same result.

**Code To Reproduce**
N/A since it is the example app itself I'm having problems with.

**Replicable on Example App?**
N/A since it is the example app itself I'm having problems with.

**Environment Info:**
Paste the results of `npx react-native info`
```
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 788.91 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.9 - /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.5 => 0.68.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Paste the exact `react-native-track-player` version you are using
4.0.0-rc01

Real device? Or simulator?
Real device. Pixel 4a.

What OS are you running?
Android 13

**How I can Help**
I'm trying to learn Java so I contribute more to the project, but I've run out of ideas for how I can fix this local env problem.

**Comment by jspizziri** [comment]
@mitchdowney I took some time to look at this, and I wasn't able to reproduce the issues you're having locally. However, I did notice that some of the KotlinAudio steps are outdated, so I'm hoping this might be the issue.

Can you take a look at the updated instructions I created a PR for here and see if the modifications make a difference in your install process?

https://github.com/doublesymmetry/react-native-track-player/pull/1959

**Comment by mitchdowney** [comment]
@jspizziri that fixed it 🥳 I was able to run the example app, add some println's to KotlinAudio, and see them in the console. Thanks for your help!
