### ISSUE TITLE
[Expo] iOS Notification Controls Missing

### ISSUE THREAD

**Issue by jcksncllwy** [doublesymmetry/react-native-track-player#1963]
**Describe the Bug**
Audio plays in the background just fine, but playback controls do not appear on the lock screen.

**Steps To Reproduce**
I only know how to reproduce this with my setup.

**Code To Reproduce**
I don't know if there is a simple way to reproduce this.

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)?
The example app doesn't use Expo, which I think might be part of the problem.

**Environment Info:**
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 3.31 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.5.0 - ~/.nvm/versions/node/v19.5.0/bin/node
    Yarn: Not Found
    npm: 9.3.1 - ~/.nvm/versions/node/v19.5.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Paste the exact `react-native-track-player` version you are using
`react-native-track-player: ^3.2.0`

Real device? Or simulator?
Real device

What OS are you running?
iOS

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

**Comment by jspizziri** [comment]
@jcksncllwy as I've mentioned [here](https://github.com/doublesymmetry/react-native-track-player/issues/1675#issuecomment-1229154827) and a few other places (linked below for additional context). None of the maintainers use Expo and we don't really officially support it given the lack of expertise in it on the team.

I'd recommend you reach out to the community in Discord. I'll leave this open for a bit, but will close it if it doesn't gain any traction.

- https://discord.com/channels/567636850513018880/997063127730495538/1025124965701394452
- https://github.com/doublesymmetry/react-native-track-player/issues/1675#issuecomment-1229154827
- https://github.com/doublesymmetry/react-native-track-player/issues/1444#issuecomment-1232032821
- https://github.com/doublesymmetry/react-native-track-player/issues/1745#issuecomment-1255071864
