### ISSUE TITLE
Track is playing on all components add the same url

### ISSUE THREAD

**Issue by dattv155** [doublesymmetry/react-native-track-player#1967]
**Describe the Bug**
I have a list of audio components, and each component can have the same audio url. When I play sound on one component, all other components with the same url are also play and update the same status.

**Steps To Reproduce**
- I setup like example, and assuming all components share the same url
https://www.dropbox.com/s/7qnogv3d3e6zt01/inspire.mp3?raw=1
- Use hook usePlaybackState, useProgress to tracking each Player state.

**Code To Reproduce**
Code inside each component
```
     const audioURL = 'https://www.dropbox.com/s/7qnogv3d3e6zt01/inspire.mp3?raw=1'
     useEffect(() => {
        let unmounted = false

        async function setup(): Promise<void> {
            const isSetup = await setupPlayer()

            const queue = await TrackPlayer.getQueue()

            if (isSetup && isEmpty(queue) && !isEmpty(audioURL)) {
                await TrackPlayer.add({
                    id: nanoid(),
                    url: audioURL,
                })
            }

            if (unmounted) {
                return
            }
        }

        setup()

        return (): void => {
            unmounted = true
        }
    }, [audioURL])

    const playbackState = usePlaybackState()
    const process = useProgress()

    const trackPosition = useMemo(() => {
        const duration = process.duration - process.position

        return duration
    }, [process])

    const playSound = useCallback(async () => {
        if (playbackState.state === State.Playing) {
            await TrackPlayer.pause()
        } else {
            await TrackPlayer.play()
        }
    }, [playbackState])

```

**Environment Info:**
react-native: 0.71.2
react-native-track-player: 3.2.0
Android 10 real device (Redmi 9T)
iPhone real device iOS 16.3 (Iphone X)

**How I can Help**
How can I play and update the state of each component separately and not relate to another component that declared with the same url?

**Comment by jspizziri** [comment]
This library has nothing to do with the components that you're rendering in your app. This sounds like a problem with your logic on how you're tracking multi-track status on your side.

It sounds like you'd benefit from reading through this guide: https://react-native-track-player.js.org/docs/guides/multitrack-progress

Regardless, this library works as intended with multiple tracks with the same URL.
