### ISSUE TITLE
Android 11 (and possibly 12) add extra capabilities to notification player

### ISSUE THREAD

**Issue by jeroenptrs** [doublesymmetry/react-native-track-player#1970]
**Describe the Bug**
On Android I'm seeing a stop button and an extra skip button added to the notification player.
![IMG_20230321_143529](https://user-images.githubusercontent.com/19305608/226623540-9fabbdc9-8ac3-4af9-94a8-999cdac2994b.jpg)
The following screenshot is from the example app, which stock has Play, skip next skip previous and seek to.

**Steps To Reproduce**
Build the test app

**Code To Reproduce**
Please provide a simple code example that allows others to replicate the bug.

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)? Yes

**Environment Info:**
Real device: I've seen it on a one plus 8t, xiaomi A3 and other xiaomi devices as well.

**How I can Help**
What can you do to help resolve this?  I can continue testing on a real device

**Comment by jeroenptrs** [comment]
Through discord and a discussion with @puckey I also managed to find another user that had the issue. I had it on Android 11 consistently, that user was talking about Android 12.

https://discord.com/channels/567636850513018880/600714011318681610/1086103264929534032

**Comment by puckey** [comment]
@jeroenptrs could you test the following pr on one of the devices that is showing this issue? See https://github.com/doublesymmetry/react-native-track-player/blob/main/example/README.md#kotlinaudio for instructions on how to use a locally built version of KotlinAudio

**Comment by jeroenptrs** [comment]
@puckey Still seeing them present, 😞 
Additionally, I see no title instead of "nope", but that's weird since a title has been passed as metadata (both baked-in as through TrackPlayer.load)

**Comment by jeroenptrs** [comment]
Also seeing this on Android 10 now, too

**Comment by puckey** [comment]
I don't think you tested with the right version of KotlinAudio – the 'nope' bug should be in that fork.. Could you check?

**Comment by puckey** [comment]
Oh wait, my bad - that pr was. merged in already.. Hmm.. Which model phones are you testing on? Maybe I will need to purchase one..

**Comment by jeroenptrs** [comment]
You might be able to find some on SauceLabs, I tested on there as well with a One Plus 8t on Android 10 and was able to have it there as well.

**Comment by jeroenptrs** [comment]
@puckey my apologies, I just realized I **was** in fact testing on KotlinAudio's main branch, not your fix. The example app actually seems to work well on your fix branch! 🙌

**Comment by jeroenptrs** [comment]
@puckey Can we reopen this? I'm still seeing this on Android 10/11/12 with rc3, which is weird because I previously tested it on said OS'es. Did some changes combined with https://github.com/doublesymmetry/KotlinAudio/pull/70 maybe undo something?

The test device I have at home (WFH currently, no access to Android 11-12 devices, but got feedback from testers) is showing this. Apologies for the photo, I can't record the lock screen on this phone 😅 
![IMG_8387](https://user-images.githubusercontent.com/19305608/228586691-df0c6718-df59-4008-abd1-4f2748ad899b.png)

**Comment by puckey** [comment]
Thanks for reporting - will check tomorrow

**Comment by jeroenptrs** [comment]
`Capability.STOP` seems to be duplicating as well, surprisingly that feels like it's all capabilities exposed in
https://github.com/doublesymmetry/KotlinAudio/blob/691fc1f5ef61b654e5d005c46b57364006ccdf84/kotlin-audio/src/main/java/com/doublesymmetry/kotlinaudio/notification/NotificationManager.kt#L264

**Comment by puckey** [comment]
Fixed in nightly / rc4
