### ISSUE TITLE
Android 10: baked-in metadata is prioritized for notification player over queued metadata

### ISSUE THREAD

**Issue by jeroenptrs** [doublesymmetry/react-native-track-player#1971]
**Describe the Bug**
I queue a track with metadata, the notification player uses metadata that is baked into the audio file instead of the metadata RNTP exposes. This was done on a Galaxy Tab A with Android 10

**Steps To Reproduce**
**Code To Reproduce**
In the example app, add this:
```
{
    "url": "https://chrt.fm/track/385A52/rss.art19.com/episodes/49e5c011-e67e-45d4-bfd8-b04a162a982d.mp3",
    "title": "Longing",
    "artist": "David Chavez",
    "artwork": "https://react-native-track-player.js.org/example/Longing.jpeg"
},
```
Your player will look like this:
![Screenshot_20230322-104713_RNTrackPlayerExample](https://user-images.githubusercontent.com/19305608/226866658-28a6ef22-fe82-4379-9225-17a508599a07.jpg)

Your notification will look like this:
![Screenshot_20230322-104700_RNTrackPlayerExample](https://user-images.githubusercontent.com/19305608/226866725-6d05f98d-49c5-407c-804e-3d98fd60944d.jpg)

According to @puckey the 'nope' in title is already fixed in KotlinAudio

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)? yes

**Environment Info:**
Paste the exact `react-native-track-player` version you are using v4.0.0 RC01
Real device? Or simulator? Real device: Galaxy Tab A
What OS are you running? Android 10

**Comment by puckey** [comment]
Could you try the following pull request: https://github.com/doublesymmetry/KotlinAudio/pull/70

**Comment by puckey** [comment]
fixed in nightly
