### ISSUE TITLE
notification bar default icon not changing

### ISSUE THREAD

**Issue by neon010** [doublesymmetry/react-native-track-player#1979]
I am trying to change the default notification icon but its not changing.

```js
export const RntpUpdateOptions=()=>{
  TrackPlayer.updateOptions({
    playIcon: require("./assets/images/play.png"),
    pauseIcon: require("./assets/images/play.png"),
    stopIcon:  require("./assets/images/play.png"),
    previousIcon: require("./assets/images/play.png"),
    nextIcon: require("./assets/images/play.png"),
    icon: require("./assets/images/play.png")
  });
}
```

I am calling this function after setup is completed. This is happening in android.

**Comment by EduardSavchenko** [comment]
Hello. tell me please. did you solved something?

**Comment by puckey** [comment]
please use the issue template, otherwise we are missing crucial information such as the version of the library you are testing with
