### ISSUE TITLE
[4.0.0-rc03] Crash QueuedAudioPlayer.currentItem

### ISSUE THREAD

**Issue by kubatatami** [doublesymmetry/react-native-track-player#1981]
**Describe the Bug**
Using 4.0.0-rc3, app crashes randomly:

```
SIGTRAP 0x00000001009670d0
Crashed: com.apple.root.utility-qos
QueuedAudioPlayer.currentItem.getter + 378376 (<compiler-generated>:378376)
1  0x46c194 specialized RNTrackPlayer.handleAudioPlayerSecondElapse(seconds:) + 941 (RNTrackPlayer.swift:941)
2  0x461570 partial apply for implicit closure #12 in implicit closure #11 in RNTrackPlayer.init() + 813736 (<compiler-generated>:813736)
3  0x461594 partial apply for thunk for @escaping @callee_guaranteed (@unowned Double) -> () + 813772 (<compiler-generated>:813772)
4  0x3f3f40 partial apply for closure #1 in AudioPlayer.Invoker.init<A>(listener:closure:) + 107 (Event.swift:107)
5  0x3e94e4 partial apply for specialized closure #1 in closure #1 in AudioPlayer.Event.emit(data:) + 322076 (<compiler-generated>:322076)
6  0x3e6d54 specialized _ArrayProtocol.filter(_:) + 311948
7  0x3e86d4 specialized closure #1 in AudioPlayer.Event.emit(data:) + 149 (Event.swift:149)
8  0x35734 thunk for @escaping @callee_guaranteed () -> () + 4340356916 (<compiler-generated>:4340356916)
9  0x24b4 _dispatch_call_block_and_release + 32
10 0x3fdc _dispatch_client_callout + 20
```

**Environment Info:**
Version: `4.0.0-rc03`
Real device
iOS only

**Comment by kubatatami** [comment]
I am able to reproduce crash in my project. Steps:

1. Set `progressUpdateEventInterval` to `1`.
2. Add tracks to queue and start playing.
3. Call `TrackPlayer.reset()`.

App will crash randomly in ~10% rate.

**Comment by puckey** [comment]
Looks like this may be a race condition – I will look into it in the coming week.

**Comment by ricardocmj** [comment]
It seems similar to #1997.

Maybe the solution could be changing the line:

https://github.com/doublesymmetry/react-native-track-player/blob/170bb4cbe5938d455406c7293afe1d4824c8c644/ios/RNTrackPlayer/RNTrackPlayer.swift#L941

to

```swift
if !shouldEmitProgressEvent || player == nil || player.currentItem == nil { return }
```

**Comment by jspizziri** [comment]
@puckey this didn't make it into `rc04` did it?

**Comment by AronBe** [comment]
also experienced the crash with `.reset`, currently using this workaround, not sure how much it differs from the actual reset

```ts
 const queueItems = await TrackPlayer.getQueue()
 for (const _track of queueItems) void TrackPlayer.remove(0)
 ```

**Comment by s123121** [comment]
Get multiple crashes on production with this bug. Please merge this

https://github.com/doublesymmetry/SwiftAudioEx/pull/48

I am on rc04

**Comment by fivecar** [comment]
Hitting this as well in v4rc3, which otherwise hasn't had any stability issues.

**Comment by s123121** [comment]
Upgrade to rc5, try all other suggestions on this thread, still happened 2 - 3 times a day / 10k device
Time to learn swift then

**Comment by puckey** [comment]
@s123121 @fivecar Please give the following pr a go: https://github.com/doublesymmetry/SwiftAudioEx/pull/55

You can test it by replacing `yourApp/ios/Pods/SwiftAudioEx/SwiftAudioEx/Classes` with `SwiftAudioEx/SwiftAudioEx/Classes` of the pr branch

**Comment by fivecar** [comment]
@puckey : awesome. Will report back after launching this a few days.

**Comment by s123121** [comment]
After 1 week running on production, I can confirm this work (no more random exception)

**Comment by fivecar** [comment]
@dcvz : I haven't seen it either in the past few days. Thanks for the fix!
