### ISSUE TITLE
Reset crashes the library

### ISSUE THREAD

**Issue by furkannarin** [doublesymmetry/react-native-track-player#1987]
**Describe the Bug**
When reset is used while the player is active it removes all of the tracks, HOWEVER, since there is no track is left in the queue, native code throws an inaccessible array element error somewhere.

For iOS the error is: "TrackPlayerModule.getTrack must not be null.". So, please either provide a method to exit the TrackPlayer process or refactor the reset.

Also, when I pass all the indexes of the tracks, it actually does remove everything in the remove, but it does not set it to the queue. Probably you add it as a security measure after remove? Still, remove does not remove the currentTrackIdx from the queue making it impossible to shut down the process.

**Steps To Reproduce**
Use TrackPlayer.reset() somewhere

**Comment by jspizziri** [comment]
Closing, as you didn't list the version of RNTP that you're using. I'll reopen if it's rc4.

**Comment by ww930912** [comment]
same the issues,For iOS the error is: "TrackPlayerModule.getTrack must not be null.".

**Comment by ww930912** [comment]
@jspizziri try:
await TrackPlayer.pause();
 await TrackPlayer.reset();
