### ISSUE TITLE
Audio Does not buffer completely in android

### ISSUE THREAD

**Issue by AbdulMoeez060** [doublesymmetry/react-native-track-player#1989]
I want to completely buffer the audio but on Android it only buffers to maximum 799 seconds. I am using version 3.1.0
it is working fine on IOS. 

```ts
await TrackPlayer.setupPlayer({
      waitForBuffer: false,
      iosCategory: IOSCategory.Playback,
      iosCategoryMode: IOSCategoryMode.Default,
      minBuffer: 3500,
      maxBuffer: 3600,
});
```
the audios are at most 30 minutes long and are played from libsyn.

**Comment by jspizziri** [comment]
Please create a repro in the `example` project that demonstrates your issue. Specifically include how you're determining the size buffered.

Lastly, I'll just note that this seems to me like a very strange use case. Are you sure you don't just want to download the audio?

**Comment by jspizziri** [comment]
Closing this due to no feedback

**Comment by AbdulMoeez060** [comment]
> Please create a repro in the `example` project that demonstrates your issue. Specifically include how you're determining the size buffered.
> 
> Lastly, I'll just note that this seems to me like a very strange use case. Are you sure you don't just want to download the audio?

I am using the useProgress to determine the buffered length, i know this is very strange use case but client wants what the client want.
