### ISSUE TITLE
how to modify exoplayer gradle dependency 

### ISSUE THREAD

**Issue by jaimecoj** [doublesymmetry/react-native-track-player#1991]
I am trying to adapt [react-native-track-player example](https://github.com/doublesymmetry/react-native-track-player/tree/main/example) for my needs.

I have made modifications to load custom tracks list successfully, however I need to make lower level modification so that playback stops after the audio file is played. I have checked it uses exoplayer gradle dependency for android. (I don't care about iOS).

What would be the steps to follow to download Exoplayer source code and load it from react native?

**Comment by jspizziri** [comment]
@jaimecoj the title of this issue doesn't seem to line up with your description. It sounds like you're trying asking how to build your own version of RNTP? If that's the case I'd just recommend forking the project and the underlying `KotlinAudio` project and modifying it to fit your needs.

I'm going to close this as it doesn't seem there's anything actionable on our side. LMK if you disagree.
