### ISSUE TITLE
event for listening to android top player notification bar click

### ISSUE THREAD

**Issue by mmestiyak** [doublesymmetry/react-native-track-player#1992]
hello, i would like to go to a specific route, when i press the android player notification badge, how can i listen for a event that fires when i click on the notification badge, not the action buttons like play, pause, what i can already achieve with remotePlay event in the useTrackPlayerEvents hook

**Comment by jspizziri** [comment]
@mmestiyak take a look at the documentation: https://react-native-track-player.js.org/docs/next/basics/background-mode#notification

I believe that's what you're asking for.

**Comment by rubensalbukrk** [comment]
If you use expo router, just create a file inside app/[...unmatched].tsx , this file name is exactly: [...unmatched].tsx , now import this: `import {useRouter} from 'expo-router'` ,
and
`const App = () => {
  const router = useRouter();
  const handleNotificationClick = () => {
    router.push('/');
  };
  return handleNotificationClick();
};
export default App;`
