### ISSUE TITLE
Metadata event for stream still sent when in stop state

### ISSUE THREAD

**Issue by pke** [doublesymmetry/react-native-track-player#2001]
**Describe the Bug**
The current `4.0.0-rc03` still emit the `Event.PlaybackMetadataReceived` while the player is in stopped state when it was in play state before.

I tried to check with Flipper if the app is still reading the stream from the network, or just merely knows when to fetch new metadata based on previous markers in the stream? That would be fine with me, however I am afraid the app keeps streaming bytes from the network, just not playing them to emit the PlaybackMetadataReceived.

Maybe thats even an issue for the underlying iOS library?

**Code To Reproduce**

```ts
await TrackPlayer.setupPlayer();
await TrackPlayer.add({
  url: "hi5.streamingsoundtracks.com",
  title: "SST",
  album: "Loading..."
});
await TrackPlayer.play();

const events = [
  Event.PlaybackMetadataReceived,
];

useTrackPlayerEvents(events, (event) => {
  console.log(event);
});
```

**Environment Info:**
Paste the results of `npx react-native info`
Paste the exact `react-native-track-player` version you are using
Real device? Or simulator?
Simulator

What OS are you running?
iOS 16.2

**Comment by jspizziri** [comment]
The code you documented doesn't seem to demonstrate what you're talking about. First of all you never call stop. The next thing to keep in mind is that events are async so the initial event could be emitted after you're calling stop. All in all, I think you need to update this to provide a more concise and compelling case that there is an issue. I'd recommend doing that by submitting an actual repo that reproduces the issue based off of the example.

**Comment by pke** [comment]
The `stop` call can happen any time. The events keep pouring in even minutes after stop was issued. 
I will have my app ready in a repo soon.
