### ISSUE TITLE
Demo app only runs with nightly (due to useActiveTrack)

### ISSUE THREAD

**Issue by heaversm** [doublesymmetry/react-native-track-player#2002]
**Describe the Bug**

In `App.tsx`, the line:

import TrackPlayer, {useActiveTrack} from 'react-native-track-player';

tries to import the `useActiveTrack` dependency which is not defined in the stable release, and requires using nightly, clearing out the Podfile.lock, and doing a new pod install.

**Steps To Reproduce**
try to implement the demo src files into an existing project

**Code To Reproduce**

See above

**Environment Info:**
Paste the results of `npx react-native info`
Paste the exact `react-native-track-player` version you are using

Simulator - IOS on Mac Ventura 13.2.1 (ARM_X64)

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

Fix would be to update the package.json to:

```
"dependencies": {
    "@react-native-community/slider": "^4.4.2",
    "react-native-track-player": "^3.2.0-170bb4cbe5938d455406c7293afe1d4824c8c644"
  },
```

or (better), to merge the `useActiveTrack` export into the release version.

**Comment by jspizziri** [comment]
The example app is designed to work with the main branch. You shouldn't try installing an old version. If you want to do that just checkout an old commit or tag.
