### ISSUE TITLE
The player has already been initialized via setupPlayer

### ISSUE THREAD

**Issue by komalharmale** [doublesymmetry/react-native-track-player#2003]
When i run app for first time and click on player to play audio it's works properly but after finishing playing Audio if i click again on it to play then it's not playing
getting `playbackState ` status as stopped and getting error `player has already been initialized via setupPlayer`

**Environment Info:**
Paste the results of `npx react-native info`:-
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
    Memory: 2.94 GB / 15.74 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: Not Found
  Languages:
    Java: 11.0.16
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.6 => 0.71.6
    react-native-windows: Not Found

 `react-native-track-player` version ^3.2.0
run on simulator
using Windows os

**Comment by jspizziri** [comment]
You should only call setup once, please look at the example app on a good way to properly do this.

**Comment by amitmehtacode** [comment]
Just comment this code 

`await TrackPlayer.setupPlayer();`
