### ISSUE TITLE
Add track object to PlaybackQueueEndedEvent

### ISSUE THREAD

**Issue by curthipster** [doublesymmetry/react-native-track-player#2011]
**What is the need and use case of this feature?**
When subscribing to the `PlaybackQueueEnded` event, I need to use the info about the last track in the queue. The `PlaybackQueueEndedEvent` includes the `track`, which is the index, but it does not have a reference to the Track object.

**Describe the ideal solution**
The new event `PlaybackActiveTrackChanged` includes the Track objects on the event itself, which is a nice improvement to the API. Also, the semantics are more intuitive, wherein `track` refers to the object and `index` refers to the index.

A backwards compatible change would add the Track object to the existing event, but it would mean the semantics are inconsistent across event types. Alternatively, a new event name and type would be non-breaking.

**Describe alternatives you've considered**
It's easy enough to workaround in the code by making an async call to `getTrack` in my event handler. I prefer the ergonomics of the newer event.

**Additional context**
N/A

**How I can Help**
I'm happy to help test.

**Comment by jspizziri** [comment]
@dcvz @puckey what are your thoughts on this feature request?
