### ISSUE TITLE
有没有详细的HLS使用介绍

### ISSUE THREAD

**Issue by zion-li** [doublesymmetry/react-native-track-player#2015]
您好：
    我想播放HLS（M3U8）的文件，请问如何使用。

**Comment by jspizziri** [comment]
@zion-li , I don't speak Chinese, so I translated your message via Google Translate.

Please take a look at [the example app](https://github.com/doublesymmetry/react-native-track-player/blob/main/example/src/assets/data/playlist.json#L31)

If you have an HLS stream you can simply pass it as the `url`. RNTP doesn't support any DRM or decryption methods.
