### ISSUE TITLE
Lock Screen shows outdated controls, positions, and artwork

### ISSUE THREAD

**Issue by fivecar** [doublesymmetry/react-native-track-player#2025]
**Describe the Bug**
The position, controls (JumpForward/JumpBackward vs. SkipToNext/SkipToPrevious), and artwork on the lock screen are sometimes wrong compared to what's live in the app (when unlocked). The position is sometimes fixed on the lock screen simply by pausing/resuming, but the difference in controls (e.g. if you set SkipToNext in the player, yet the lock screen still shows JumpForward from a previous setting) and the difference in artwork (e.g. showing a previous track's artwork) seems to remain even after play/pause.

**Steps To Reproduce**
It happens regularly, but it's not obvious how to reproduce this. Happens to my users in production as well. Seems from other bug filings in this repo that it might be a long-standing issue that's been around for years.

**Replicable on Example App?**
It's not clear what circumstances are required to create the repro, and so I'm unsure whether the example app reproduces it.

**Environment Info:**
Paste the results of `npx react-native info`
```
System:
    OS: macOS 13.3.1
    CPU: (12) x64 Apple M2 Max
    Memory: 136.04 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/philipsu/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.4.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Paste the exact `react-native-track-player` version you are using
    "react-native-track-player": "^3.2.0",

Real device? Or simulator?
  Real devices in production

What OS are you running?
  Various, but typically iOS 16, and down as low as iOS 14.

**How I can Help**
I'm more than happy to try to help fix this if someone can suggest what could even be causing this. Seems like a timing issue of some sort. Why would pausing/playing sometimes fix the position when the displayed position on the lock screen was wrong in the first place? And what does react-native-track-player do when capabilities are updated (e.g. from JumpForward to SkipToNext) such that the lock screen could lag behind that change?

Given the right context to help me look for the issue, I'm more than happy to PR a fix. But when I've submitted some past PRs, there have been concerns around, or a reluctance to take, changes which don't repro consistently (because of the understandable fear that you then couldn't be sure you've actually fixed the bug). Given that history, I'm unsure whether me submitting a PR in this case would actually be net useful, though I'm willing to do so if it'll lead to a fix.

**Comment by puckey** [comment]
Could you try the latest 4.0 rc version to see if you can reproduce these issues there also?

**Comment by fivecar** [comment]
@puckey : How has 4.0RC been holding up so far, according to folks who've been actively using it? I'm a bit hesitant to bump my production app to an RC, unless it's truly pretty stable. The other reason, as you know, is that I've submitted a few PRs to both this project and SwiftAudioEx which haven't been accepted/merged, and so I've patched my local copies of these libraries in order to get past the bugs that I've found and fixed in these libraries. Moving to the RC means potentially regressing/losing those fixes, which I'm a bit hesitant to do, since some of those fixes took me a lot of time to find and implement, and the repros of which are difficult (so it's hard to know when a new version regresses them).

Do you have production projects which have already moved successfully to the RC? I'm willing to take a risk on this if there's already been enough support to reduce the risk of moving production users over to an RC.

**Comment by puckey** [comment]
Join the discord community, check the issues etc etc to get an idea of the state of 4 rc. We will be doing a production release of our apps in the coming month or two. As far as your situation goes, I feel for you. Happy to reopen this issue if you can reproduce on 4.0 rc.

**Comment by fivecar** [comment]
Ok - I've joined the Discord, and will bite the bullet and migrate production over the 4.0 rc4. 🤞
