### ISSUE TITLE
Remote track player does not appear on lock screen/notification randomly in iOS.

### ISSUE THREAD

**Issue by meetp-zluck** [doublesymmetry/react-native-track-player#2027]
**Describe the Bug**
Remote track player does not appear on lock screen/notification randomly in iOS while playing any track.

**Steps To Reproduce**
This happens randomly in iOS.

**Environment Info:**
react-native: "0.64.1"
react-native-track-player: "^3.2.0",
Platform: iOS
This happens in device. Tested device: iPhone 12, iOS: 16.5

**Comment by fbotalla** [comment]
same here

**Comment by fbotalla** [comment]
@puckey  I still cannot see the remote controls on this new version. 
I am on  "react-native": "0.71.8",
and using hermes

**Comment by meetp-zluck** [comment]
@puckey , the issue persists in react-native-track-player 4.0.0-rc04 as well.

**Comment by fbotalla** [comment]
@meetp-zluck Are you using expo in your project?

**Comment by meetp-zluck** [comment]
@fbotalla , Nope. It's CLI.

**Comment by puckey** [comment]
@fbotalla see if you can reproduce the same problem using the example app first – if the example app works, it is probably a problem in your code

**Comment by fbotalla** [comment]
@puckey  I think my issue is related to #1963
