### ISSUE TITLE
SeekTo doesn't work properly on iOS

### ISSUE THREAD

**Issue by Ggayane** [doublesymmetry/react-native-track-player#2032]
**Describe the Bug**
SeekTo doesn't work on iOS if track is long (like more than 20 minutes).

**Steps To Reproduce**
When track is playing and you try to use `seekTo` the player state changes to "buffering", "playing", "ended", "paused" and it's impossible to start playing track again.

**Environment Info:**
 "react-native-track-player": "^3.2.0-9cd6e0e9235f8ed7ae5812ed20220f7d895b510a",

This happens both on real device and on simulator.

**Comment by puckey** [comment]
use react-native-track-player 4.0.0-rc04 instead of 3.2.0: https://www.npmjs.com/package/react-native-track-player/v/4.0.0-rc04

**Comment by Ggayane** [comment]
Thank your @puckey, it turned out the problem was in ".mp3" file.
