### ISSUE TITLE
Q: State.Buffering ambiguity in play state

### ISSUE THREAD

**Issue by fivecar** [doublesymmetry/react-native-track-player#2036]
I couldn't get this answered on Discord despite asking two times, so thought I'd post here...

In v4's move to `getPlaybackState()` over `getState()`, the migration docs say that `State.Buffering` will now be returned regardless of whether it's supposed to be playing or not. In v3, I could use `if (state === State.Playing || state === State.Buffering)` to determine whether the player is in the act of trying to play (e.g. it can be used to dictate whether a play button shows a Pause icon or a Play icon). But it's unclear to me now how to do this in v4, because I can no longer tell between `state === State.Buffering` because you're buffering during playback vs. because you're paused and the player is pre-caching some upcoming audio.

Do I understand this correctly? If not, what is the right way in v4 to determine whether to render a Play or Pause icon by consulting the state of TrackPlayer?

**Comment by puckey** [comment]
You can use ‘TrackPlayer.getPlayWhenReady()’ to find out whether the player will start playing when it had loaded enough data to do so.

**Comment by puckey** [comment]
You may also want to check the example app for implementation reference

**Comment by fivecar** [comment]
Ah, ok. So IIUC, `getPlayWhenReady` is true iff the player is in a "playing" state (regardless of buffer status), and is false iff the player is in a paused or stopped state? The naming of the function had me otherwise thinking that the call is only valid when the player isn't ready to play a track yet.

**Comment by fivecar** [comment]
@puckey: IIUC, this change in the v4 API makes it really tricky to implement even a basic play/pause button. According to the example, all of the following is needed before you can decide whether to render Play or Pause:

```
  const playWhenReady = usePlayWhenReady();
  const isLoading = useDebouncedValue(
    state === State.Loading || state === State.Buffering,
    250
  );

  const isErrored = state === State.Error;
  const isEnded = state === State.Ended;
  const showPause = playWhenReady && !(isErrored || isEnded);
  const showBuffering = playWhenReady && isLoading;
```

Does that sound right? Including subtleties like you can be `playWhenReady` even when the track is errored or has already ended. Seems like it'd be very easy for developers to make a mistake here. Would a hook that encapsulates all this potentially be helpful?

**Comment by fivecar** [comment]
#2040 submitted to make this easier for others. Thanks for clarifying the subtleties, @puckey .

**Comment by tsheaff** [comment]
If anyone finds this issue in the future, here's how I'm using this to render my button (note the useDelayedTruth is distinct from useDebouncedValue provided in the examples, as it'll snap back to `false` as soon as the flag is false, and only has a delay on becoming `true`, which is likely what you want for the purposes of showing your loading icon (without this, the loading state occurs every time for a very brief portion on any internet connection, which just looks janky and doesn't represent an actual delay of any kind for the user. 500ms was the right amount to delay here to get is smooth in most cases, but still show a loader quickly when there's a perceptible delay:

```ts
type PlaybackButtonMode = 'loading' | 'playing' | 'paused';
export const usePlaybackButtonMode = (): PlaybackButtonMode => {
  const { playing, bufferingDuringPlay } = useIsPlaying();
  const hasBeenBuffering = useDelayedTruth(bufferingDuringPlay ?? false, 500);
  if (hasBeenBuffering) return 'loading';
  if (playing) return 'playing';
  return 'paused';
};

// returns true if `value` has been true for at least `delay` milliseconds
const useDelayedTruth = (value: boolean, delay: number): boolean => {
  const [delayedValue, setDelayedValue] = React.useState<boolean>(false);

  React.useEffect(() => {
    let timeoutId: ReturnType<typeof setTimeout> | null = null;
    if (value) {
      timeoutId = setTimeout(() => {
        setDelayedValue(true);
      }, delay);
    } else {
      setDelayedValue(false);
    }

    return () => {
      if (timeoutId) {
        clearTimeout(timeoutId);
      }
    };
  }, [value, delay]);

  return delayedValue;
};
```

I then use `usePlaybackButtonMode` directly in the UI to control the button.
