### ISSUE TITLE
Player slider lags

### ISSUE THREAD

**Issue by Antonasdads** [doublesymmetry/react-native-track-player#2047]
Hi all. I'm doing a slider on react native reanimated and react native track player. And the problem is when I want to show a value when I slide which a person scrolls with his finger and when he releases the value was based on position from react native track player. Now when a person begins to scroll, there is a momentary displacement, then everything is normal, until the moment when the person put down, then immediately return to the original position until  the Track player is displaced. 
![image](https://github.com/doublesymmetry/react-native-track-player/assets/137204790/393e9c04-1a2b-4a40-92b3-bfcba6419c51)
![image](https://github.com/doublesymmetry/react-native-track-player/assets/137204790/62397f6f-661b-4cc5-b40a-2b00eb654005)

https://github.com/doublesymmetry/react-native-track-player/assets/137204790/00cca836-a4b1-442d-8b72-d8117ff6a932

**Comment by puckey** [comment]
Please post support questions for your code in the discord community or github discussions.
