### ISSUE TITLE
[iOS] Bluetooth Media button Event is not trigger while audio is routing through bluetooth peripherals

### ISSUE THREAD

**Issue by ahmedbhesaniya97** [doublesymmetry/react-native-track-player#2051]
I am unable to receive these two notifications if I play any audio through my Bluetooth peripherals.
```js
 TrackPlayer.addEventListener(Event.RemotePlay, () => {
       // randomFunction()
    });

    TrackPlayer.addEventListener(Event.RemotePause, () => {
       // randomFunction()
    });

```

**Comment by puckey** [comment]
Are you able to reproduce this when running the example app in this repo?

**Comment by puckey** [comment]
Actually, could you fill in the issue template? This will provide valuable information for us in order to know where you are experiencing this issue
