### ISSUE TITLE
[4.0.0-rc05] Unexpected and inconsistent PlaybackQueueEnded events

### ISSUE THREAD

**Issue by TobiDevloft** [doublesymmetry/react-native-track-player#2060]
**Describe the Bug**
In 4.0.0-rc05 I observed inconsistent and unexpected behavior with the `PlaybackQueueEnded` event. 

1. On iOS the `PlaybackQueueEnded` is fired twice, once the last track in the queue is started, once when it's finished.
2. On Android the `PlaybackQueueEnded` is fired once the queue is finished.
3. On iOS this is different when `RepeatMode.Track` is enabled, the `PlaybackQueueEnded` event is only fired once the track ends, even though the track restarts again. In this case, the event sometimes gets fired with position set to the duration of the track, sometimes with position set to 0. 
4. On Android, the `PlaybackQueueEnded` is not fired if `RepeatMode.Track` is enabled.

Some of these issue should be part of this issue https://github.com/doublesymmetry/react-native-track-player/issues/2038

See also issue https://github.com/doublesymmetry/react-native-track-player/issues/1995.

**Steps To Reproduce**
Finish the queue both in `RepeatMode.Track` and `RepeatMode.Off` and observe the events on Android and iOS.

**Replicable on Example App?**
Yes

**Environment Info:**
Paste the results of `npx react-native info`

```
System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 255.80 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.10.0/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      Android NDK: 25.2.9519653
  IDEs:
    Android Studio: Not Found
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.7 => 0.71.7
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Paste the exact `react-native-track-player` version you are using

`4.0.0-rc5`

Real device? Or simulator?

Both

What OS are you running?

iOS 16.4.1

**How I can Help**
If you point me in the right direction, I'll try my best but I only have very limited swift experience.

**Comment by puckey** [comment]
> 1. On iOS the `PlaybackQueueEnded` is fired twice, once the last track in the queue is started, once when it's finished.
Should be fixed by https://github.com/doublesymmetry/react-native-track-player/pull/2058
> 2. On Android the `PlaybackQueueEnded` is fired once the queue is finished.
This is as it should be
> 3. On iOS this is different when `RepeatMode.Track` is enabled, the `PlaybackQueueEnded` event is only fired once the track ends, even though the track restarts again. In this case, the event sometimes gets fired with position set to the duration of the track, sometimes with position set to 0.
Should be fixed by https://github.com/doublesymmetry/react-native-track-player/pull/2058
> 4. On Android, the `PlaybackQueueEnded` is not fired if `RepeatMode.Track` is enabled.
As long as `RepeatMode.Track` is enabled, the queue will not end – so it shouldn't fire `PlaybackQueueEnded`.. I think what you are looking for is a `PlaybackQueueRepeated` event?

**Comment by puckey** [comment]
(We really need someone to set up `react-native-track-player` integration tests, so we can make sure the android implementation and ios implementation are exactly equal)

**Comment by TobiDevloft** [comment]
> Does this happen whenever the queue loops also?

No, in that case it does not fire.


> As long as RepeatMode.Track is enabled, the queue will not end – so it shouldn't fire PlaybackQueueEnded.. I think what you are looking for is a PlaybackQueueRepeated event?

I agree, I just noted it because it behaves differently than iOS. Our use case would need a `PlaybackTrackRepeated` event, but a `PlaybackQueueRepeated` would make sense too IMO.

**Comment by puckey** [comment]
> I agree, I just noted it because it behaves differently on iOS. Our use case would need a `PlaybackTrackRepeated` event, but a `PlaybackQueueRepeated` would make sense too IMO.

Yes, so this would be emitted when the track repeats with `RepeatMode.Track`

**Comment by puckey** [comment]
Hmm although I see the inconsistency.. how about `PlaybackRepeated` instead - and it would the queue with `RepeatMode.Queue` and the track with `RepeatMode.Track`

**Comment by puckey** [comment]
How about we close this issue as all inconsistencies should now be fixed by https://github.com/doublesymmetry/react-native-track-player/pull/2058 – and create a feature request for the `PlaybackRepeated` event?

**Comment by TobiDevloft** [comment]
That is a great idea and thank you very much for fixing it! I'll create a feature request :)
