### ISSUE TITLE
[Feature Request] PlaybackRepeated Event

### ISSUE THREAD

**Issue by TobiDevloft** [doublesymmetry/react-native-track-player#2061]
**What is the need and use case of this feature?**
Our app has a feature which allows users to listen to a track once, twice, three or an infinite amount of times. We used to enable this by setting the player to `RepeatMode.Track` and utilizing the `PlaybackTrackChanged` event by keeping track of how many times the track got repeated. As of `4.0.0-rc5.0` this event does not fire anymore if the same track gets repeated - which makes total sense.

But now we have to solve it by keeping track of the player progress, which is error prone and hacky. We'd love an event which tells us when a track or the queue gets repeated.

**Describe the ideal solution**
A `PlaybackRepeated` event which fires when the queue or the track repeats. 

**Describe alternatives you've considered**
Currently we extended our progress state update logic to detect when a track restarts (and it's position goes from finished to 0). We then pretend this case is our `PlaybackRepeated` event.

**Additional context**
This was discussed further here https://github.com/doublesymmetry/react-native-track-player/issues/2060#issuecomment-1634007200

**How I can Help**
Unfortunately I'm not familiar (enough) with swift and kotlin to be of much help, but I'll gladly test it on different devices.

**Comment by shellfly** [comment]
@TobiDevloft Hello, did you get a fix for this?

**Comment by TobiDevloft** [comment]
@shellfly we are now checking on progress update if the track was repeated, it basically comes down to something like this:

```
private playerHasJustRestartedTheSameTrackAutomatically(
    currentPlayerPosition: number,
    currentLesson: ILesson,
    durationOfTrack: number
  ) {
    const timePlayedForLessonAfterLastUpdate =
      UserStoreService.getTimePlayedForLesson(currentLesson);
    const lastProgressUpdate =
      ProgressUpdateInterceptor.getLastProgressUpdate();

    const trackWasFinishedOnLastStateUpdate =
      timePlayedForLessonAfterLastUpdate >= durationOfTrack - 1;
    const currentPositionIsPositive = currentPlayerPosition >= 0; // Check if the current position is 0 or more seconds. Why? Because on iOS it sometimes is negative.
    const currentPositionAtStartOfTrack = this.positionIsBelowStartThreshold(
      currentPlayerPosition
    );
    const sameTrackSinceLastUpdate =
      currentLesson.id === lastProgressUpdate?.lessonID;

    const repeatWasAlreadyHandled =
      lastProgressUpdate &&
      this.positionIsBelowStartThreshold(lastProgressUpdate.position);

    return (
      !repeatWasAlreadyHandled &&
      trackWasFinishedOnLastStateUpdate &&
      currentPositionIsPositive &&
      currentPositionAtStartOfTrack &&
      sameTrackSinceLastUpdate
    );
  }
```

**Comment by shellfly** [comment]
@TobiDevloft Thank you for your response. It's quite inconvenient not to have a built-in event for this. I have found a workaround by dynamically generating tracks based on the desired number of repeats. For example, if a user chooses to repeat twice, I will add two identical tracks to the queue for each track.
