### ISSUE TITLE
iOS OGG stream support

### ISSUE THREAD

**Issue by illestrater** [DoubleSymmetry/react-native-track-player#207]
Firstly, thank you for your work on this library. It's a great solution for most of our needs.

But, we've discovered that OGG icecast streams will not play on iOS (works on Android), and throws an error code 0. I understand that iOS does not natively support OGG, and MP3 is working fine, so we tried to think of a workaround solution to transcode our streams to MP3 server side, but came to the conclusion it would create too much overhead for us.

Do you have any tips on how we could get this to work with OGG audio streams, or if you plan to introduce OGG support?

Much appreciated!

**Comment by deepaksingh16** [comment]
Hi @Guichaguri Any plans to target this?

**Comment by Mahfa** [comment]
hi there, any updates about this issue ?

**Comment by ramazanarslan** [comment]
Any updates?

**Comment by Pandan** [comment]
ping

**Comment by vitorverasm** [comment]
please

**Comment by yanel777** [comment]
Any updates?

**Comment by mathews-p** [comment]
any update?

**Comment by 2neha** [comment]
@mathews-p please help me I have an issue in react-native-video player  #1137 please let me know what is happning

**Comment by gregogalante** [comment]
Any update?

**Comment by dcvz** [comment]
right now we've been focusing on the release of `v2` we hope to add support for ogg on iOS after that!

**Comment by bradleyflood** [comment]
Added to [Project Backlog](https://github.com/DoubleSymmetry/react-native-track-player/projects/1#card-75988735) as a Feature Request. We can then review if this is or will be done in v2.

**Comment by arjunmehta** [comment]
Curious if there are still plans to revisit this at some point.

**Comment by Rohit152002** [comment]
any update on this ? or is there any way to play ogg files. If there plz tell me

**Comment by shehryar-munir** [comment]
Any update on this? @dcvz

**Comment by muhsin-k** [comment]
@illestrater Were you able to tackle this issue?

**Comment by muhsin-k** [comment]
@Rohit152002 @shehryar-munir @arjunmehta @gregogalante Were you able to tackle this issue?

**Comment by muhsin-k** [comment]
Did you use [this](https://github.com/wix-incubator/react-native-opus-decode/) package for conversion, or did you convert to another format?

**Comment by shehryar-munir** [comment]
> Did you use [this](https://github.com/wix-incubator/react-native-opus-decode/) package for conversion, or did you convert to another format?

@muhsin-k This library will convert the audio to .wav file and will give you path to local .wav file. You can then feed that path to sound `react-native-sound-player`

**Comment by myredbean** [comment]
> > Did you use [this](https://github.com/wix-incubator/react-native-opus-decode/) package for conversion, or did you convert to another format?
> 
> [@muhsin-k](https://github.com/muhsin-k) This library will convert the audio to .wav file and will give you path to local .wav file. You can then feed that path to sound `react-native-sound-player`

Can local files be loaded?
