### ISSUE TITLE
Player already initialized is rejecting instead of resolving

### ISSUE THREAD

**Issue by julien-lisub** [doublesymmetry/react-native-track-player#2078]
**Describe the Bug**
I don't really know if it is a bug or if it is intended, but on the official docs it says that if the player is already initialized while calling `setupPlayer` it should `resolve` immediately.

Docs: https://rntp.dev/docs/api/functions/lifecycle

But when looking at the code itself (Swift), it actually `rejects`.

Code: https://github.com/doublesymmetry/react-native-track-player/blob/ba4711bf9bbb2e38ca2eb021750f40748482eefd/ios/RNTrackPlayer/RNTrackPlayer.swift#L159

Is this intended? In which case a change to the docs is needed, otherwise a change to the resolution of the setupPlayer method is needed.
Personally I do believe it should `resolve` and ***not*** `reject`.

Also, is there any appetite to tweak error handling? I feel that having the same code re-used in different contexts is not great and it could lead to unintended cases on the consumer's side. 

Re-used error code: https://github.com/doublesymmetry/react-native-track-player/blob/ba4711bf9bbb2e38ca2eb021750f40748482eefd/ios/RNTrackPlayer/RNTrackPlayer.swift#L137

Personally I have mapped the different errors that I could find in the package's code to be able to let the app behave properly when a failure happens and I think having more flexibility by separating all error cases with a proper error code would be a good thing.

```typescript
/**
 * Possible errors being thrown by the Player package.
 * These were fished from the https://github.com/doublesymmetry/react-native-track-player/ package.
 */
export enum PlayerErrors {
  AlreadyInit = 'player_already_initialized',
  IndexOutOfBounds = 'index_out_of_bounds',
  InvalidTrackObj = 'invalid_track_object',
}
```

**Steps To Reproduce**
An example case would be to setup the player inside a `useEffect` so the code tries to setup the player every time there's a render. See the method reject with the `player_already_initialized` code starting on second try.

**Code To Reproduce**
```typescript
useEffect(() => {
  TrackPlayer.setupPlayer()
    .then(() => {
      debugger; // Stops here on first try    
    })
    .catch(error => {
      if (error === PlayerErrors.AlreadyInit) {
        debugger; // Stops here on second try ++
      }
    });
});
```

**How I can Help**
I could take some time to set different error types and update the code to use them. And potentially fix the rejection if you judge it is an unintended behaviour.

**Comment by adamblvck** [comment]
I can confirm that I'm experiencing an error rejection: `[Error: The player has already been initialized via setupPlayer.]` instead of resolve, which I'd prefer to see.

**Comment by lovegaoshi** [comment]
i remember seeing this part in android and it's also rejecting:
https://github.com/doublesymmetry/react-native-track-player/blob/ba4711bf9bbb2e38ca2eb021750f40748482eefd/android/src/main/java/com/doublesymmetry/trackplayer/module/MusicModule.kt#L165
