### ISSUE TITLE
appKilledPlaybackBehavior not working on some Android phones

### ISSUE THREAD

**Issue by jr00n** [doublesymmetry/react-native-track-player#2080]
**Describe the Bug**
One the Android devices I have I can't get the option to stop the playback when a user kills the application.

**Code To Reproduce**
I'm using this config:
```
android: {
    appKilledPlaybackBehavior:
      AppKilledPlaybackBehavior.StopPlaybackAndRemoveNotification,
  },
```
First time it works, then I start the app again, and then it doesn't stop the audio when I kill the app.
Also when I tab on the remote player (notification screen) then it doesn't go the the app.

**Environment Info:**
```
npx react-native info:
System:
  OS: macOS 13.5
  CPU: (12) arm64 Apple M2 Max
  Memory: 106.66 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /opt/homebrew/bin/zsh
Binaries:
  Node:
    version: 16.18.0
    path: ~/.nvm/versions/node/v16.18.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v16.18.0/bin/yarn
  npm:
    version: 8.19.2
    path: ~/.nvm/versions/node/v16.18.0/bin/npm
  Watchman:
    version: 2023.07.03.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/jr00n/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.12
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/jr00n/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: ^0.72.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

```

react-native-track-player: 3.2.0

On 2.1.2 & 4.0.0-rc6 this is NOT happening!

Real device:
```
Samsung Galaxy S9 - One Ui 2.5 - Android 10
Mii Note 10 Lite - MIUI 13.0.4 Android 12
```

**Comment by puckey** [comment]
So just to make sure, this is not happening on the 4.0 rc releases?

**Comment by jr00n** [comment]
> So just to make sure, this is not happening on the 4.0 rc releases?

Correct.

**Comment by jr00n** [comment]
I've tested it today with a new expo app, and it works as designed. So the problem was somewhere in my code.

**Comment by artpersona** [comment]
> I've tested it today with a new expo app, and it works as designed. So the problem was somewhere in my code.

I'm currently experiencing this issue. How did you solve it ?

**Comment by barghi** [comment]
I am facing this error

Phone: xiaomi Redmi 9 Pro
Android: 10
React-Native: 0.72.0
React-Native-Track-Player: ^3.2.0

**Comment by pheonix5** [comment]
using nightly worked for me

**Comment by pheonix5** [comment]
according to afkcodes, he used the rc06 and it worked

**Comment by barghi** [comment]
yes last rc version (4.0.0-rc07) fixed the issue on my device

**Comment by vietdung97** [comment]
On both the Pixel 7 (Android 14) and Redmi Note 11 (Android 13), playing music continues even after killing the app, despite setting appKilledPlaybackBehavior to PausePlayback. How to fix this?
