### ISSUE TITLE
Problem after build/release

### ISSUE THREAD

**Issue by Saboten758** [doublesymmetry/react-native-track-player#2099]
After releasing the app, the React Native Track Player library does not allow the user to play/pause the audio, and there is an issue with playing audio from an HTTP stream. These problems do not occur while running the app through Metro.

The issue is not replicable in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example).

Environment Inf:

react-native-track-player version: 3.2.0 (replace with your version)
Testing on: Real device
OS: Android (11 & 13)

This is the project I was working on : https://github.com/Saboten758/Lemon_Player

The command I used for building the release apk is :

./gradlew assembleRelase

**Comment by lovegaoshi** [comment]
HTTP (cleartext) is banned by default in android app release. you need 2 manually enable like 
https://stackoverflow.com/questions/51902629/how-to-allow-all-network-connection-types-http-and-https-in-android-9-pie

**Comment by Saboten758** [comment]
Thanks @lovegaoshi 😊  but, it still doesn't allow for user playback from https streams..😪

**Comment by lovegaoshi** [comment]
I just saw you mentioned the example app is fine. if your stream link is fine within the example app then theres little others can do unless you post your repo.

**Comment by Saboten758** [comment]
Actually, the problem is with foreground playback. In the recent project I was working, I had a trackplayer service, to basically fetch songs form the streams and a main music player screen, from where I was playing... It was working fine while running on Metro, but after release, I couldn't manage to play any from the the buttons on screen...

**Comment by lovegaoshi** [comment]
oopsie, i didnt see you posted your repo. from a glance you didnt add `"isLiveStream": true` in your streaming playlist  https://github.com/Saboten758/Lemon_Player/blob/main/Screens/trackplayer.tsx#L71C27-L71C27 but i dont know how it worked in dev. 

you may also look at logcat in android studio and/or keep the <PlaybackError> from the example app. at least you will get teh error message straight in your app
