### ISSUE TITLE
Expose compound position, duration, bufferedDuration compound event in addition to ProgressComponent

### ISSUE THREAD

**Issue by iThinker** [DoubleSymmetry/react-native-track-player#210]
Currently the only way to keep track of player position, duration, bufferedDuration is to update it via timer. This is what ProgressComponent does. But platform players actually have means to notify if there are any changes in these variables more precisely and minimizing js execution overhead.

**Comment by Guichaguri** [comment]
There's actually no other way to do it. Updates are generated in this or in every music module.
The only "real" update is if you start executing code between each audio frame.

The good part about using timers is that you can control the update frequency

**Comment by iThinker** [comment]
@Guichaguri for example on iOS `AVPlayer` has `addPeriodicTimeObserver` which has some logic attached to it. Also `duration` might be good as a separate event only when it changes because it is not expected to change often.

**Comment by Guichaguri** [comment]
Still, `addPeriodicTimeObserver` is just a fancy timer. It probably runs on the audio processing code to trigger updates skipping when it couldn't keep up. This might be better than a regular timer on iOS though
