### ISSUE TITLE
[4.0.0-rc07] updateMetadataForTrack accidentally clears artwork on Android

### ISSUE THREAD

**Issue by DennisdeWitNL** [doublesymmetry/react-native-track-player#2103]
**Describe the Bug**
Since RC07, updateMetadataForTrack correctly keeps the title and artist, but it clears the artwork on Android. The artwork is an empty square. I do not have this problem with RC06, so it seems the bug was introduced with RC07.

**Steps To Reproduce**
Use the `updateMetadataForTrack` function. Even if you use a constant as artwork URL, it still clears the artwork on Android. It retains the title and artist correctly. On iOS, everything works as expected.

**Code To Reproduce**
I used the following code:

```
  const updateMetadata = async () => {

    const artwork = 'https://domain.tld/redacted.jpg';
    let songDataFunction = await fetchNowPlaying();
    console.log("Updating metadata")
    let currentTrack = await TrackPlayer.getActiveTrackIndex();
    if (currentTrack == null) {
      return;
    } else {
      TrackPlayer.updateMetadataForTrack(currentTrack, {
        artist: songDataFunction.song_artist,
        title: songDataFunction.song_title,
        artwork: artwork
      });
    }
  }
```

This code keeps the artist and title, but it doesn't show the artwork, even though it is an constant. It just renders empty. I do not have this issue with RC06 or lower.

**Replicable on Example App?**
I didn't test it against the Example App, as I don't have this issue with RC06 or lower

**Environment Info:**
Paste the results of `npx react-native info`

```
dennisdewit@MacBook-Pro-van-Dennis 40RockTSRelease % npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 14.0
  CPU: (12) arm64 Apple M2 Max
  Memory: 86.25 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 19.8.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.5.1
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.03.27.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.0
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.6
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.2
    wanted: 0.72.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

```

Paste the exact `react-native-track-player` version you are using
```
    "react-native-track-player": "^4.0.0-rc07"

```

Real device? Or simulator?
On a real device. Tested on Samsung S22.

What OS are you running?
Android 13

**Comment by DennisdeWitNL** [comment]
After digging deeper, I used the example code from the example app.

```
  const updateMetadata = async () => {
    let songDataFunction = await fetchNowPlaying();

    const currentTrackIndex = await TrackPlayer.getActiveTrackIndex();
    if (currentTrackIndex !== undefined) {
      await TrackPlayer.updateMetadataForTrack(currentTrackIndex, {
        title: songDataFunction.song_title,
        artist: songDataFunction.song_artist,
        artwork: songDataFunction.song_artwork,
      });
    }
  }
```

That worked. I am sorry for the inconvenience :)

**Comment by KornelKwiatkowski** [comment]
I have the same issue

**Comment by DennisdeWitNL** [comment]
I will check soon today.

**Comment by DennisdeWitNL** [comment]
@dcvz Unfortunately, the problem is still there with rc09.

**Comment by DennisdeWitNL** [comment]
@dcvz I will implement your function tomorrow and show you my code. Today I feel a bit sick as I am on very strong medication right now, so I am off to bed. I appreciate your help and what you do for the community, so I will come back to you as soon as possible tomorrow. :)

**Comment by DennisdeWitNL** [comment]
> @DennisdeWitNL the example app has a button that replaces current track metadata with random values (including a new image) and it seems to work there. Not sure what may be weird with your setup.. you sure you're on the latest?
> 
> https://github.com/doublesymmetry/react-native-track-player/blob/41144036554d3299ccd3c1f5cdba6cc825b6cacd/example/src/components/ActionSheet.tsx#L16

After the first time updating the metadata, the artwork is being empty.

This is the code I am using

`  const onUpdateCurrentTrackMetadata = async () => {
    let songDataFunction = await fetchNowPlaying();
    const currentTrackIndex = await TrackPlayer.getActiveTrackIndex();
    if (currentTrackIndex !== undefined) {
      await TrackPlayer.updateMetadataForTrack(currentTrackIndex, {
        artist: songDataFunction.song_artist,
        title: songDataFunction.song_title,
        artwork: `https://xxx.com/xxx.jpg`,
      });
    }
  };`

and this is the fetchNowPlaying function:

`    const fetchNowPlaying = async () => {

      var Promise = nanoid();
      const resp = await fetch(
       `https://live-streams.nl/40rocknowplaying/nowplaying.txt?promise=${Promise}`,
     );
     const SplitInfo = await resp.text();
     var splittedData = SplitInfo.split(" - ");
     var artist = splittedData[0];
     var title = splittedData[1];
      
      return (
        {
          "show_name": "Show Name",
          "dj_name": "DJ Name",
          "dj_artwork": "https://xxx.com/xxx.jpg,
          "song_artist": artist,
          "song_title": title,
          "song_artwork": "https://xxx.com/xxx.jpg",
          "header_url": ""
      }
      );
    }`

I have no clue what is wrong, but it works fine on rc06.

**Comment by DennisdeWitNL** [comment]
One more thing: I found out that the artwork clears out when the title and the artist didn't change. When I use the random function and regenerate a new title or artist, the artwork keeps standing and works on intended.

```  const onUpdateCurrentTrackMetadata = async () => {
    const currentTrackIndex = await TrackPlayer.getActiveTrackIndex();
    let songDataFunction = await fetchNowPlaying();
    if (currentTrackIndex !== undefined) {
      const randomTitle = Math.random().toString(36).substring(7);
      await TrackPlayer.updateMetadataForTrack(currentTrackIndex, {
        title: songDataFunction.song_title,
        artist: songDataFunction.song_artist,
        artwork: 'https://xxx.com/xxx.jpg'
        // duration: Math.floor(Math.random()),
      });
    }
  };
```

This function runs every 10 seconds. When the artist and songtitle are still the same, the artwork is getting corrupted.

When I change the function like this:

```
  const onUpdateCurrentTrackMetadata = async () => {
    const currentTrackIndex = await TrackPlayer.getActiveTrackIndex();
    let songDataFunction = await fetchNowPlaying();
    if (currentTrackIndex !== undefined) {
      const randomTitle = Math.random().toString(36).substring(7);
      await TrackPlayer.updateMetadataForTrack(currentTrackIndex, {
        title: randomTitle,
        artist: songDataFunction.song_artist,
        artwork: 'https://xxx.com/xxx.jpg'
        // duration: Math.floor(Math.random()),
      });
    }
  };

```

Then the title is being changed every 10 seconds, and the artwork keeps working as intended. It seems this probleem occurs when the title and artist are still the same.

**Comment by DennisdeWitNL** [comment]
@dcvz, I can not test the example project as it is corrupt.

`/Users/dennisdewit/Documents/Apps/react-native-track-player/example/android/app/src/main/java/com/example/MainApplication.java:20: error: cannot find symbol
            return BuildConfig.DEBUG;
                   ^
  symbol: variable BuildConfig`

I have not changed anything on the .java fail, so it seems to be broken out of the box.

**Comment by DennisdeWitNL** [comment]
@dcvz Maybe I am not skilled enough to run an example app (sorry about that), but if you want, I can add you as a contributor to my private repo, so you can use the same app as I have. I have tested the code you provided above, and the artwork still nullifies when the artist and title stay the same.

The app I have built is very small and easy (only one screen), so it shouldn't take to much time to understand the code. Would you be up for that? :)

**Comment by DennisdeWitNL** [comment]
@dcvz I have just tried the example app, and can reproduce the issue on a real smartphone - the Samsung S22 Plus. I don’t have this issue on Android Emulator. 

When I get home I will share the example git, so you can test it too. :)

**Comment by gavrichards** [comment]
I can confirm this is still present in 4.0.1, released today.

- it works in rc05, although the presence of the notification is glitchy and unreliable, but when it's there, it has the artwork I expect
- updating metadata is broken in rc06
- updating metadata was fixed in rc07, but this artwork issue then introduced

**Comment by marcvictorpassarelli** [comment]
I'm not sure if they're related, but I did notice [this](https://github.com/doublesymmetry/react-native-track-player/issues/2188) with local artwork, it did worked until rc05 and it broke after rc06

**Comment by gavrichards** [comment]
Still an issue, not stale.

**Comment by DennisdeWitNL** [comment]
Still open. Not solved.
