### ISSUE TITLE
Cannot read property 'CAPABILITY_PLAY' of null on @next

### ISSUE THREAD

**Issue by albandum** [doublesymmetry/react-native-track-player#2107]
**Describe the Bug**
Getting the error :
 ERROR  TypeError: Cannot read property 'CAPABILITY_PLAY' of null, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:

**Steps To Reproduce**
Install @next version, and set up a service in index.js on an Expo app 

`TrackPlayer.registerPlaybackService(() => require('./services/TrackplayerService'));`

**Code To Reproduce**
The service is simple : 

```
import TrackPlayer from 'react-native-track-player';

module.exports = async function () {

  TrackPlayer.addEventListener('remote-play', () => TrackPlayer.play());
  TrackPlayer.addEventListener('remote-pause', () => TrackPlayer.pause());
  // TrackPlayer.addEventListener('remote-next', () => TrackPlayer.skipToNext());
  // TrackPlayer.addEventListener('remote-previous', () => TrackPlayer.skipToPrevious());

};
```

and the code itself is the regular demo one : 

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)?

**Environment Info:**

info Fetching system and libraries information...
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 528.23 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /Users/alban/.rvm/gems/ruby-3.1.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.8
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.72.4 is now available (your project is running on v0.71.8).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.72.4
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.71.8
info For more info, check out "https://reactnative.dev/docs/upgrading".

Real devices, 2 android devices behave the same (both samsungs)

**How I can Help**
Not sure, but on the stable release I have this issue : https://github.com/doublesymmetry/react-native-track-player/issues/719
And on the @next I have the issue described above. Not sure what to do :)

**Comment by cbaser** [comment]
How did you fix this?

**Comment by albandum** [comment]
> How did you fix this?

Buildt a new dev build of the app, I believe it was mostly a mismatch between libraries

**Comment by viktorzee** [comment]
I have been trying to use this package on an expo app, gives me the same error, and I appear to be stuck, can't find a solution to this problem. Ideas please?
