### ISSUE TITLE
[4.0.0-rc06] [iOS] Media player remote center remains invisible while playing audio after running a Unity game on iOS 16

### ISSUE THREAD

**Issue by mvn-haiphung-dn** [doublesymmetry/react-native-track-player#2110]
**Describe the Bug**
Media player remote center remains invisible while playing audio after running a Unity game 

**Steps To Reproduce**

1. Play audio
2. Stop audio
3. Launch Unity game within the app
4. End the game
5. Play audio

At step 5, Media player remote center is still invisible

**Replicable on Example App?**
No, this issue does not exist in the Example App.

**Environment Info:**
`react-native-track-player` version: v4.0.0-rc06
Device: iPhone 13, iOS 16

**How I can Help**
PR tries to fix the issue https://github.com/doublesymmetry/react-native-track-player/pull/2111

**Comment by puckey** [comment]
@mvn-haiphung-dn I would like to take a second look into this issue. Was this happening with every Unity game? Or a specific one? In which case, which game was it?

**Comment by jspizziri** [comment]
Looks like a fix has been merged
