### ISSUE TITLE
[Feature Request] Allow removing notification in paused state

### ISSUE THREAD

**Issue by pheonix5** [doublesymmetry/react-native-track-player#2113]
Good evening everyone, I would like to suggest a functionality for the react native track player

behavior similar to spotify and some other music/stream apps, when the player is paused it is possible to slide and remove the notification, bringing that freedom of closing the player. Obviously when you press play the notification appears again.

Thank you all for this wonderful library.

**Comment by lovegaoshi** [comment]
it already works this way in android. i take it you mean in iOS?

**Comment by pheonix5** [comment]
não, atualmente aqui pra mim, ela é permanente. Fechando apenas o aplicativo para que a notificação seja removida. por causa do:
appKilledPlaybackBehavior: AppKilledPlaybackBehavior.StopPlaybackAndRemoveNotification

**Comment by lovegaoshi** [comment]
you can slide the notification bar right to dismiss when RNTP is paused. it works just like that in android 13
AppKilledPlaybackBehavior.StopPlaybackAndRemoveNotification you linked if for when you "swipe up" app from recent to kill it

**Comment by pheonix5** [comment]
man I don't know what I did wrong, but I swear that in the paused state i can't remove the notification.

**Comment by pheonix5** [comment]
i found out the reason, poco x3 pro with android 12 and miui 13.0.3. There is a bug with the library. other devices with android 11 such as galaxy a30s worked well the notification slide to close, however the lock screen notification, the stop button did not come, and automatically added the next and previous buttons

**Comment by afkcodes** [comment]
@pheonix5  Please close the issue if your issue is solved or addressed.
