### ISSUE TITLE
MediaSession behaviour Android

### ISSUE THREAD

**Issue by FranzVDB** [doublesymmetry/react-native-track-player#2114]
**Describe the Bug**
RNTP stops other apps from continuing playing music when setupPlayer is run, because it sets the media session to active doing init. This is only a problem on Android in the KotlinAudio lib.

KotlinAudio takes the session when the init function of BaseAudioPlayer runs where SwiftAudioEx takes it on Play.

**Steps To Reproduce**
Android (bug)
1. open spotify or other music app
2. start playing music
3. open app with RNTP
4. music stops when setup function run.

IOS (works)
1. open spotify or other music app
2. start playing music
3. open app with RNTP
4. music continue as expected until play is pressed.

**Code To Reproduce**
Please provide a simple code example that allows others to replicate the bug.

**Replicable on Example App?**
Yes. -> remove "autoHandleInterruptions: true" in the SetupService function.

**Environment Info:**
Paste the results of `npx react-native info`
RNTP v: 4.0.0-rc07 but also on nightly.
Real device - Samsung galaxy s10  
MacOS m2

**How I can Help**
I have looked at the underlying code to find the bug and as far as i can see it's in the init() function in KotlinAudio/BaseAudioPlayer line 228:
https://github.dev/doublesymmetry/KotlinAudio/blob/35446d7ad5e851a01bc237988e27ddb9617ef350/kotlin-audio/src/main/java/com/doublesymmetry/kotlinaudio/players/BaseAudioPlayer.kt#L228-L229

I think it should be changed to follow the SwiftAudioEx way of requesting the session when togglePlayback()/play() is called.

What can you do to help resolve this?
My knowlage of KotlinAudio and Kotlin is not good enough to fix this by myself, but i dont think it's a huge task to fix.

**Comment by FranzVDB** [comment]
We found out that the problem occurs when "autoHandleInterruptions: true" is NOT PRESSENT. Meaning the autohandleInterruption code fixes the issue, but this mean i can't handle it myself or have default behavior, which is a bug to me.

**Comment by lovegaoshi** [comment]
for reference i believe this is due to exoplayer/KA requesting audiofocus every single time when the player becomes "ready" and autohandleinterruptions is off, which makes this behavior very much expected.
https://github.com/doublesymmetry/KotlinAudio/blob/f84fe5e8c5b918026179d37eba82003b6132aed8/kotlin-audio/src/main/java/com/doublesymmetry/kotlinaudio/players/BaseAudioPlayer.kt#L110
