### ISSUE TITLE
[4.0.0-rc08] [iOS] setRate() Value Resets w/ Play + Pause

### ISSUE THREAD

**Issue by brianlenz** [doublesymmetry/react-native-track-player#2122]
**Describe the Bug**
On the latest `4.0.0-rc08` in iOS, the `TrackPlayer.setRate()` value is not retained through `TrackPlayer.play()` or `TrackPlayer.pause()`. This appears to be a regression of #614?

This is _not_ an issue on `4.0.0-rc07`. It's also not an issue in Android.

**Steps To Reproduce**
1. Start playing audio.
2. `setRate()` to any playback speed other than `1`.
3. `TrackPlayer.pause()`.
4. Observe `TrackPlayer.getRate()` returns `0`.
5. `TrackPlayer.play()`.
6. Observe playback speed is normal, and `TrackPlayer.getRate()` returns `1`.

**Code To Reproduce**
Use the `example` app. In `src/components/PlayPauseButton.tsx`, replace `onPress` with this:

```
onPress={async () => {
  if (playing) {
      console.log(`pre-pause: ${await TrackPlayer.getRate()}`);
      await TrackPlayer.pause();
      console.log(`post-pause: ${await TrackPlayer.getRate()}`);
  } else {
      console.log(`pre-setRate: ${await TrackPlayer.getRate()}`);
      await TrackPlayer.setRate(2);
      console.log(`pre-play: ${await TrackPlayer.getRate()}`);
      await TrackPlayer.play();
      console.log(`post-play: ${await TrackPlayer.getRate()}`);
  }
}}
```

The audio will _never_ play at a rate of `2` because both `play()` and `pause()` seem to reset the rate to `0`.

**Replicable on Example App?**
Yes.

**Environment Info:**
**Paste the results of `npx react-native info`**
```
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.34 GB / 64.00 GB
    Shell: 5.2.15 - /opt/homebrew/bin/bash
  Binaries:
    Node: 20.5.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.0 - /opt/homebrew/bin/npm
    Watchman: 2023.08.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/brian/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, visionOS 1.0, watchOS 10.0
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 26.0.2, 26.0.3, 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 31.0.0, 33.0.0
      System Images: android-29 | Google APIs ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10671973
    Xcode: 15.0/15A5229m - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.8.1 - /opt/homebrew/opt/openjdk@17/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.12 => 0.71.12 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Paste the exact `react-native-track-player` version you are using**
`4.0.0-rc08`

**Real device? Or simulator?**
iOS Simulator.

**What OS are you running?**
macOS 13.5.2 / iOS 16.4.

**How I can Help**
Testing possible fixes when available!

**Comment by collinc777** [comment]
I'm having this issue too. Trying to figure out how to fork both packages appropriately and it's proving a bit difficult.

Do I have to get my SwiftAudioEx fork published to the Cocoapods podspec registry to fork it correctly?
