### ISSUE TITLE
[iOS 17] TrackPlayer.pause setting playerState to playing

### ISSUE THREAD

**Issue by Lucile-Peltier** [doublesymmetry/react-native-track-player#2124]
Hello, 

I am testing my app on iOS 17 and the playerState does a weird thing. When I call TrackPlayer.pause, the playerState is paused and immediately becomes playing.
I do not have this issue on iOS 16 or Android.

Here are my logs : 
TrackPlayer.play():
 ``` 
 LOG  Event.PlaybackState {"state": "ready"}
 LOG  Event.PlaybackState {"state": "paused"}
 LOG  Event.PlaybackState {"state": "buffering"}
 LOG  Event.PlaybackState {"state": "ready"}
 LOG  Event.PlaybackState {"state": "playing"}
```

TrackPlayer.pause():
``` 
LOG  Event.PlaybackState {"state": "paused"}
LOG  Event.PlaybackState {"state": "playing"}
```
**Versions**
"react-native": "0.67.5",
"react-native-track-player": "3.2.0",

**Comment by mirkocalce** [comment]
Hello, I'm experiencing the issue you reported. Any news of fix?

**Comment by FranzVDB** [comment]
I'm experiencing the same bug on IOS 17. @dcvz Is this something you could give an insight on if you think this is an issue with SwiftAudio or RNTP?

**Comment by PandaRN94** [comment]
Hi everyone, I am experiencing the same behaviour as described in the issue. The behaviour occurs, in my case, only for live audio streams, while the behaviour remains correct if you try to play onDemand content.

**Comment by Dahvd** [comment]
> Hi everyone, I am experiencing the same behaviour as described in the issue. The behaviour occurs, in my case, only for live audio streams, while the behaviour remains correct if you try to play onDemand content.

In my case, once the live stream has been paused, calling TrackPlayer.play() doesn't play it anymore and it remains paused

**Comment by FranzVDB** [comment]
@Lucile-Peltier @mirkocalce What type of files are you playing? and did you resolve the issue?

**Comment by FranzVDB** [comment]
This issue can be recreated on the example app when playing the song called Whip

https://github.com/doublesymmetry/react-native-track-player/assets/47597992/6a0cdabb-26a4-44d7-809a-f512fc902372

**Comment by Lucile-Peltier** [comment]
I did a hack to check if the playerstate previous value is paused and than switches to play and use a custom state to keep the correct playerstate. But it doesn't work perfectly and I still have some issue with the widget.
I noticed the issue on a live stream audio.

**Comment by FranzVDB** [comment]
You can come join the discussion on discord, they are looking into it right now @Lucile-Peltier

**Comment by FranzVDB** [comment]
@Lucile-Peltier @PandaRN94  @mirkocalce - The bug has been found and can be avoided for now by setting the pitching algorithm to something different than default when adding a track.

`await TrackPlayer.add({
       ....
        pitchAlgorithm: PitchAlgorithm.Voice, //  PitchAlgorithm.Music
      });`
      
Great work @dcvz and @puckey 👏 👏 👏
