### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [DoubleSymmetry/react-native-track-player#215]
Greetings, Im a graphics designer here on Github and I would like to ask for your permission to design for your logo/icon that you maybe used for your future plans in your project. I want to help open source projects by designing logos or banners for there project. Thank you for your time reading this

Best regards
-jbeguna04

**Comment by dcvz** [comment]
Sure 👍 We don't have a problem with this as long as it's free ;)

**Comment by jbeguna04** [comment]
Good day @dcvz , Here are some proposal for your project:
![image](https://user-images.githubusercontent.com/35353768/47297740-93c5c000-d648-11e8-9059-f204ea7f2f20.png)

What do you think?

**Comment by jbeguna04** [comment]
Good Day! Did you see the logos now?

**Comment by ishigamii** [comment]
@jbeguna04 wow very nice 
@dcvz @Guichaguri Not using them yet ? :D

**Comment by Guichaguri** [comment]
@jbeguna Sorry for the long delay
They are very nice indeed! I really like the React inspired one with the pause button on it. Are you still willing to contribute them for free?
Thank you
