### ISSUE TITLE
ContextImpl.startServiceCommon: android.app.StackTrace - Last startServiceCommon() call for this service was made here

### ISSUE THREAD

**Issue by harshil-gosquire** [doublesymmetry/react-native-track-player#2156]
**Describe the Bug**
We have app live in playstore with crashlytics implemented and we are keep getting this crash on crashlytics with live users

Full bug report from crashlytics

```
Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3039c39 u0 com.gosquire/com.doublesymmetry.trackplayer.service.MusicService}
       at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2245)
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2216)
       at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2508)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```
Other crashlytics stats for better understanding

Observed to be happening only on samsung devices + 100% of user are facing when app is in background state
<img width="869" alt="crash2" src="https://github.com/doublesymmetry/react-native-track-player/assets/118244939/62c6d8c1-46db-4b12-ad39-96bc53012867">

**Steps To Reproduce**
We are not able to reproduce at our end but live users are facing it

**Code To Reproduce**
We are not able to reproduce at our end but live users are facing it

**Replicable on Example App?**
We are not able to reproduce at our end but live users are facing it

**Environment Info:**
```
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 202.58 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

`"react-native-track-player": "^3.2.0"`

Real device? Or simulator?
- Real device

What OS are you running?
- Android 13

**How I can Help**
What can you do to help resolve this?
We have tried solutions from existing similar issues on here github but still crash log pops up with same error, Please let us know what we can do to resolve this crash.

**Comment by jorgerojas26** [comment]
Same exact problem, any solution or workaround?

**Comment by ignacioperezmatrix** [comment]
- Probably related to #1812

**Comment by MaxJadav** [comment]
> * Probably related to [[Android] Crash Fatal Exception: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent  #1812](https://github.com/doublesymmetry/react-native-track-player/issues/1812)

It is related but no solution works.

Same problem, any solution or workaround?

**Comment by roganantonys** [comment]
i too facing this, any solution's?
