### ISSUE TITLE
Support for switching the url of currentTrack from remote url  to local file path

### ISSUE THREAD

**Issue by ram-vilash** [doublesymmetry/react-native-track-player#2185]
If any media is downloaded we can easily switch from a remote url to a local filepath. But for now, I do see we have any method to update the URL.

**Comment by lovegaoshi** [comment]
there is TrackPlayer.load (undocumented when I looked for it) you can update whatever you want
fairly sure exoplayer (android) doesnt support changing source without a noticeable stop in playback so it wont ever be seamless though
