### ISSUE TITLE
[Feature Request]  Option to disable notification when playing audio

### ISSUE THREAD

**Issue by nk-hcode** [doublesymmetry/react-native-track-player#2186]
**What is the need and use case of this feature?**
I have an app which is regarding alerts, so whenever alert will be triggered App will play a sound continuously until user checks in but don't want to show player as we want the control to disable the sound based on user response.

**Describe the ideal solution**
When the option is enabled, notification should not come when sound is playing.

**Comment by lovegaoshi** [comment]
imho RNTP's main attractive point against other audio libraries (expo-av, rn-sound, etc) is the notification manager. why not just use other libraries out there if you dont need media control.

**Comment by nk-hcode** [comment]
@lovegaoshi ok, but I have tried multiple libraries and most of them are not providing what I need, can you please let me know, which libraries support background audio with app closed and not showing notification for that, just like alarm works in ios

**Comment by lovegaoshi** [comment]
Didn't I mention expo-av? What did you try
Alarm apps have special permissions and you won't find one reliably plays
somthint when app Is fully closed

**Comment by nk-hcode** [comment]
Can't use expo-av as I am using react-native cli and I have also tried react-native-sound and that too has an issue where it doesn't run when the app is closed, so I am out of options right now

**Comment by lovegaoshi** [comment]
Yes you can use expo in rn cli...  They literally have a doc section on it
in the installation page

**Comment by nk-hcode** [comment]
ok, thanks, let me try it once

**Comment by nk-hcode** [comment]
@lovegaoshi I have used expo-av and it is able to work but not when app is closed, so it is just like react-native-sound, if you know anything else about expo-av which can help me to run the audio even when app is closed, or any other solution then please do let me know, Thanks.

**Comment by nk-hcode** [comment]
ok, Thank you very much for your time. Let me try this solution
