### ISSUE TITLE
Local artwork not loading in the notification tray in release mode in Android

### ISSUE THREAD

**Issue by marcvictorpassarelli** [doublesymmetry/react-native-track-player#2188]
**Describe the Bug**
A local artwork asset is not loading in the notification tray in release mode in Android, despite loading normally in debug mode

**Steps To Reproduce**
Just run the example project in release mode in Android and go to the track Pure (Demo) that loads a local artwork

**Code To Reproduce**
Please provide a simple code example that allows others to replicate the bug.

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)?
**Yes**
I added a text to see how the artwork was being handled and why it was working in debug mode but not in release and found this:

**Debug**
<p float="left">
<img src="https://github.com/doublesymmetry/react-native-track-player/assets/84107477/fe08c3e2-a407-4da4-adb1-debee7f463cd" alt="drawing" width="400"/>
<img src="https://github.com/doublesymmetry/react-native-track-player/assets/84107477/483fb29a-6774-45bf-b29d-29a2bf5885ed" alt="drawing" width="400"/>
</p>

**Release**
<p float="left">
<img src="https://github.com/doublesymmetry/react-native-track-player/assets/84107477/d483a887-5ddd-4f98-a036-a88dd33d4f10" alt="drawing" width="400"/>
<img src="https://github.com/doublesymmetry/react-native-track-player/assets/84107477/524e7df2-2f6b-424c-b72b-66e3ec8c8faa" alt="drawing" width="400"/>
</p>

**Environment Info:**
Real device? Or simulator?
Real Device, Samsung S22 Ultra
What OS are you running?
System:
  OS: macOS 13.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 1.64 GB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 16.14.2
    path: ~/.nvm/versions/node/v16.14.2/bin/node
  Yarn:
    version: 1.22.10
    path: /usr/local/bin/yarn
  npm:
    version: 8.5.0
    path: ~/.nvm/versions/node/v16.14.2/bin/npm
  Watchman:
    version: 2023.06.08.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/marcpassarelli/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 4.2 AI-202.7660.26.42.7351085
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.18
    path: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/marcpassarelli/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
I was able to track down and it seems that until RC05 this was working fine and then it broke after RC06 and looking at the commits from that version my best guess is that it could be related to this [commit](https://github.com/doublesymmetry/react-native-track-player/commit/efecf3e0a1c5bf56dbae85aa1553c1c6f94109af)

Can you create a Pull Request with a fix?
I'll investigate a little further and debug to see if I can find what is wrong.

**Comment by ali03111** [comment]
i am also facing the same issue please help to solve it

**Comment by akshay-managooli** [comment]
yes, i also facing this . Basically any local files (audio or image) both are not working on Release builds
