### ISSUE TITLE
[IOS] SwiftAudioEx error

### ISSUE THREAD

**Issue by witekmikolajczak** [doublesymmetry/react-native-track-player#2196]
**Describe the Bug**
After installing react-native-track-player and creating dummy.swift and creating a bridge, I get the following error:
`/ios/Pods/SwiftAudioEx/Sources/SwiftAudioEx/QueueManager.swift (in target 'SwiftAudioEx' from project 'Pods')`

**Steps To Reproduce**
- Install react-native-track-player
- follow docs and create dummy.swift

**Environment Info:**
```
System:
  OS: macOS 12.5
  CPU: (8) arm64 Apple M1
  Memory: 110.52 MB / 8.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 20.7.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.1.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.09.25.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /Users/witekmikolajczak/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 21.4
      - iOS 15.5
      - macOS 12.3
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 13.4.1/13F100
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.21
    path: /opt/homebrew/opt/openjdk@11/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/witekmikolajczak/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
- Simulator Iphone 8

**Solution**
- works fine with `react-native-track-player@3.2`

**Comment by dcvz** [comment]
@witekmikolajczak could you post the full error? I think there's more missing

**Comment by cappe** [comment]
I am seeing the same error with `react-native-track-player@4.0.1`. I'm very new to React Native so I'm not sure how to help further.

**Comment by dcvz** [comment]
> I am seeing the same error with `react-native-track-player@4.0.1`. I'm very new to React Native so I'm not sure how to help further.

A full error message would help a lot!

**Comment by cappe** [comment]
Logs for a command `npm run ios`: [https://pastebin.com/JZ547efQ](https://pastebin.com/JZ547efQ). Let me know if I can provide something else :)

**Comment by dcvz** [comment]
Ok looks like the issue is this:

```
 error: unable to infer complex closure return type; add explicit type to disambiguate
        let result = try synchronizeThrows {
                                           ^
                                             () -> <#Result#> in 
```

This was also reported in [here](https://github.com/doublesymmetry/react-native-track-player/issues/2193#issuecomment-1794086414) - like this person I see you're also 2 versions behind on Xcode. My guess is their Swift syntax parser was not as advanced then and is throwing issues.

**Comment by dcvz** [comment]
Is updating Xcode versions an option for you?

**Comment by cappe** [comment]
It is. I'll report back to you when I've upgraded the Xcode.

**Comment by witekmikolajczak** [comment]
```
** BUILD FAILED **


The following build commands failed:
        CompileSwift normal arm64 ios/Pods/SwiftAudioEx/Sources/SwiftAudioEx/QueuedAudioPlayer.swift (in target 'SwiftAudioEx' from project 'Pods')
        CompileSwift normal arm64 ios/Pods/SwiftAudioEx/Sources/SwiftAudioEx/QueueManager.swift (in target 'SwiftAudioEx' from project 'Pods')
        CompileSwift normal arm64 ios/Pods/SwiftAudioEx/Sources/SwiftAudioEx/RemoteCommandController/RemoteCommand.swift (in target 'SwiftAudioEx' from project 'Pods')
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'SwiftAudioEx' from project 'Pods')
(4 failures)
```

**Comment by linhkiubo98** [comment]
> ```
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
>         CompileSwift normal arm64 ios/Pods/SwiftAudioEx/Sources/SwiftAudioEx/QueuedAudioPlayer.swift (in target 'SwiftAudioEx' from project 'Pods')
>         CompileSwift normal arm64 ios/Pods/SwiftAudioEx/Sources/SwiftAudioEx/QueueManager.swift (in target 'SwiftAudioEx' from project 'Pods')
>         CompileSwift normal arm64 ios/Pods/SwiftAudioEx/Sources/SwiftAudioEx/RemoteCommandController/RemoteCommand.swift (in target 'SwiftAudioEx' from project 'Pods')
>         CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'SwiftAudioEx' from project 'Pods')
> (4 failures)
> ```



> ```
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
>         CompileSwift normal arm64 ios/Pods/SwiftAudioEx/Sources/SwiftAudioEx/QueuedAudioPlayer.swift (in target 'SwiftAudioEx' from project 'Pods')
>         CompileSwift normal arm64 ios/Pods/SwiftAudioEx/Sources/SwiftAudioEx/QueueManager.swift (in target 'SwiftAudioEx' from project 'Pods')
>         CompileSwift normal arm64 ios/Pods/SwiftAudioEx/Sources/SwiftAudioEx/RemoteCommandController/RemoteCommand.swift (in target 'SwiftAudioEx' from project 'Pods')
>         CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'SwiftAudioEx' from project 'Pods')
> (4 failures)
> ```

Any solution?
