### ISSUE TITLE
Sometimes after releasing an update to our app, a small percent of users report that background playback no longer works (iOS)

### ISSUE THREAD

**Issue by mitchdowney** [doublesymmetry/react-native-track-player#2199]
We have received this bug report occasionally after updating our mobile app, but we have no theories as to what could be going on. I don't know if it is a react-native-track-player issue or not, but I never seem to hear of other non-RNTP apps having this issue, so I'm wondering if it could be related.

> since the latest update to the app yesterday podcasts no longer play in the background.  If I put it in lock mode or swipe up to use another app the podcast stops playing. 

For most cases it appears that background playback begins working again after the user 1) restarts their phone or 2) deletes and reinstalls the app.

Does anyone have theories as to what could cause this? The issue was just reported on iOS today, and I'm not sure if it ever happens for Android.

If the issue definitely can't be related to RNTP then of course feel free to close this.

**Comment by ALamm** [comment]
Hello @mitchdowney.   We are evaluating RNTP for our audio app, and wondering if you still experiencing this issue?

**Comment by mitchdowney** [comment]
@ALamm I'm not sure...we should have a new release out in about a week. I'll try to remember to post an update here if we receive another email reporting the issue.

**Comment by ram-vilash** [comment]
This is happening ios the actual device, when the app comes from the background to the foreground notification disappears, and then the next background mode doesn't work anymore after that.

Please fix this issue as soon as possible

**Comment by mitchdowney** [comment]
Hi @ram-vilash do you have any more information about this issue? Perhaps some information that could help guide developers to a solution? I'm not familiar with what you mean that "notification disappears." What notification are you referring to?

**Comment by dyerai** [comment]
I'm also having this issue. For select users of the app, background audio playback no longer works
