### ISSUE TITLE
Using headset (Airpods) on iPhone devices sometimes causes track player bugs

### ISSUE THREAD

**Issue by ivona314** [doublesymmetry/react-native-track-player#2206]
**Description**
We have gotten various reports from our users that using Airpods on iPhone devices causes track player bugs. 

**Steps To Reproduce**
Specifically, a user reported that when they pause an audio track directly on their headphones, then the audio does stop but the track seemingly "keeps playing" on their app, but without audio. There is no way for them to get the audio back in their headphones (so pressing play on the headphones doesn't work) - they have to completely close down the app. Also, other controls like forwarding the track don't work in this case as well. 

**Code To Reproduce**
We don't really know what could be causing this issue in our code. 

**Environment Info:**

`System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 92.95 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/opt/node@18/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
`

`react-native-track-player` version: 4.0.1
Happening on real devices. 
What OS are you running? iOS 17.1.1

I am unable to replicate this issue on my own devices. What can I do to debug this? Are there any other known issues that could be causing this?

**Comment by mrsrhn** [comment]
I just became feedback from a user who described the same behavior.
