### ISSUE TITLE
SwiftAudioEx

### ISSUE THREAD

**Issue by MTPL0005-AbhishekDubey** [doublesymmetry/react-native-track-player#2208]
**Describe the Bug**
[!] CocoaPods could not find compatible versions for pod "SwiftAudioEx":
  In Podfile:
    react-native-track-player (from `../node_modules/react-native-track-player`) was resolved to 4.0.1, which depends on
      SwiftAudioEx (= 1.0.0)

None of your spec sources contain a spec satisfying the dependency: `SwiftAudioEx (= 1.0.0)`.

**Steps To Reproduce**
When I hit the Pod install got this issue before I was using V3.2.0. 

**Environment Info:**
System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M2
    Memory: 621.55 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - /opt/homebrew/bin/npm
    Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
  Languages:
    Java: 20.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.14 => 0.71.14 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

react-native-track-player : "4.0.1"
Real device : Yes
OS : iOS

After encountering this issue, I uninstalled the previous version and attempted to install both the latest version and version 4.0.0. However, for both versions, I encountered the same problem.

**Comment by lovegaoshi** [comment]
if you see this msg too then you should try whatever its suggesting
`
You have either: * out-of-date source repos which you can update with pod repo update or with pod install --repo-update. * mistyped the name or version. * not added the source repo that hosts the Podspec to your Podfile.`

for example `yarn && cd ios && rm Podfile.lock && pod install --repo-update && cd ..`

**Comment by MTPL0005-AbhishekDubey** [comment]
@lovegaoshi Issue was solved after using `pod update SwiftAudioEx`
