### ISSUE TITLE
Audio loading issues

### ISSUE THREAD

**Issue by AjaySinghPanwar** [doublesymmetry/react-native-track-player#2214]
Hey guys,
I am fetching audio from a remote url. But the audio takes too long to load. Like the audios, we are playing in our application are having duration 1hr and long. So, can we do anything to resolve this thing ?

**Comment by lovegaoshi** [comment]
RNTP or exoplayer/avplayer fetches whatever buffer range u set. how long is ur minBuffer

**Comment by jspizziri** [comment]
No response. Also the solution would be to configure buffer or use something like HLS
