### ISSUE TITLE
[Documentation] "Getting Started" Service is incorrect

### ISSUE THREAD

**Issue by uzegonemad** [doublesymmetry/react-native-track-player#2217]
The Getting Started section of the docs uses the old style of registering the service.

[See here](https://github.com/doublesymmetry/react-native-track-player/blob/a0fdd21f77afb4c11cb7062c6665dfd337cef117/docs/docs/basics/getting-started.md?plain=1#L7-L20)

**Comment by henryteng07** [comment]
How to correctly register the service?

**Comment by uzegonemad** [comment]
This issue is still relevant.
