### ISSUE TITLE
Could not find com.github.doublesymmetry:kotlinaudio:v2.0.0.

### ISSUE THREAD

**Issue by baumanmilosz** [doublesymmetry/react-native-track-player#2223]
BUILD FAILED in 19s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-track-player:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-track-player:debugCompileClasspath'.
   > Could not find com.github.doublesymmetry:kotlinaudio:v2.0.0.
     Required by:
         project :react-native-track-player

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

"react-native": "0.70.1",
"react-native-track-player": "^4.0.1",

Anyone knows reason of above problem?

**Comment by lovegaoshi** [comment]
the KA package is available on jitpack. try the How to
To get a Git project into your build: instructions on the jitpack page: 
https://jitpack.io/#doublesymmetry/KotlinAudio

**Comment by baumanmilosz** [comment]
@lovegaoshi it works, thank you!
