### ISSUE TITLE
Queue duration

### ISSUE THREAD

**Issue by deppaa** [doublesymmetry/react-native-track-player#2225]
Hi, I'm trying to get the queue total duration using this method, but nothing works track.duration returns undefined, ver3.2 the queue consists of web links

```
const getQueueTotalDuration = async () => {
    const queue = await TrackPlayer.getQueue();
    const totalDuration = queue.reduce<number>(
      (acc, track) => acc + track.duration!,
      0
    );
    return totalDuration;
  };

**Comment by lovegaoshi** [comment]
well RNTP is not going to magically get the duration until the resource is loaded and read; the duration value stays as undefined until its loaded to the player, or you can manually set it
you need your own custom logic for this, eg ffprobe
