### ISSUE TITLE
[AVPlayerItem addOutput:] Cannot attach an output that is already attached or nil output

### ISSUE THREAD

**Issue by AjayGol** [doublesymmetry/react-native-track-player#2230]
**Describe the Bug**
*** [AVPlayeritem addOutput:] Cannot attach an output that is already attached or nil output.

**Steps To Reproduce**
TBH it did not happen to me on debug, but it seems that is happening to my users in production. I have reports from Firebase Crashlytics.

![Screenshot 2023-12-29 at 12 25 40 PM](https://github.com/doublesymmetry/react-native-track-player/assets/77920960/d4323259-3d4c-42f6-a91f-b6d5dba5c097)

![Screenshot 2023-12-29 at 12 25 50 PM](https://github.com/doublesymmetry/react-native-track-player/assets/77920960/91eab324-be7a-4ed6-a04d-caf0414d6fc7)

OS: macOS 13.5.2 
CPU: (8) arm64 Apple M1
react-native: ^0.68.0 => ^0.68.0
xCode: 15(15A240d)/usr/bin/xcodebuild

Using react-native-track-player@^4.0.1

This is happen on real devices, most of them iOS 16 and up.

**Comment by milanubhada** [comment]
react native version update please issue resolve

**Comment by fivecar** [comment]
My users are getting this in production off v4.0.1 as well (with an example today on iOS 17.4 using iPhone 15 Pro). @jspizziri : in #1818, you mentioned that the particular issue would be better handled/supported if people got off the RC's... I think it's now been seen by many folks on 4.0.1, so it feels like a legitimate/continued issue.

I'm happy to help make a PR here, but I'm not positive what the actual fix ~should~ be. For instance, should we try to detect an already-attached or nil output, and simply not try to `startObserving` it? Or alternatively, does hitting this code path indicate a deeper problem that we need to fix upstream of this moment?

**Comment by 9mzodiac** [comment]
This issue is also affecting my app, I hope it gets fixed soon

**Comment by fivecar** [comment]
Still an issue in production... feels like this shouldn't be closed...
