### ISSUE TITLE
iOS Notification Center controls still present and empty after reset

### ISSUE THREAD

**Issue by Gregoirevda** [doublesymmetry/react-native-track-player#2240]
**Describe the Bug**
on iOS the Notification Center displays an empty track after the track has been `TrackPlayer.reset()`

**Code To Reproduce**
1. `TrackPlayer.load(track);` (same with `setQueue`)
2. `await TrackPlayer.play();`
3. `TrackPlayer.reset();`

**Environment Info:**
Running on a physical device with `react-native-track-player: 0.72.5`. Both XCode and Metro have no stacktrace

**Comment by lokeshk12510** [comment]
I too have the same issue,

After `TrackPlayer.reset()`, I am trying to play a video with `react-native-video` but still the notification control displays with empty data.

By updating the meta data, we can display data on it, but still I don't need that notification control in my app while playing video.

```
useEffect(() => {
    const updateMetaData = async () => {
      await TrackPlayer.updateNowPlayingMetadata({
        title: media.title,
        description: media.description,
        artist: media.author,
        artwork: media.imageUrl,
        elapsedTime: currentTime,
        duration,
      });
    };

    updateMetaData();
  }, [currentTime, media, duration]);
```

For events:

```
useTrackPlayerEvents(
    [
      Event.RemotePause,
      Event.RemotePlay,
      Event.RemoteJumpForward,
      Event.RemoteJumpBackward,
    ],
    async event => {
      if (event.type === Event.RemotePause) {
        setPlay(false);
      } else if (event.type === Event.RemotePlay) {
        setPlay(true);
      } else if (event.type === Event.RemoteJumpBackward) {
        skipBackward();
      } else if (event.type === Event.RemoteJumpForward) {
        skipForward();
      }
    },
  );
```

Pls share any alternative way for this issue

 Version:  ` react-native-track-player: ^4.1.1`

**Comment by jr00n** [comment]
I have the same issue with iOS and version 3.2.0 On Android no issues with same code using TrackPlayer.reset() on iOS the remote stays and is empty on Anroid it is gone (what i expect)
Any idea how to fix?

**Comment by jr00n** [comment]
@lokeshk12510 Found something....when i do:

` await TrackPlayer.reset();`
 `await TrackPlayer.clearNowPlayingMetadata();`

the empty remote is gone!!
