### ISSUE TITLE
Cannot read properties of undefined (reading 'CAPABILITY_PLAY')

### ISSUE THREAD

**Issue by Adbhutashra** [doublesymmetry/react-native-track-player#2245]
![Screenshot (1)](https://github.com/doublesymmetry/react-native-track-player/assets/85542932/425f34d7-ebd3-4543-b86f-42ed823cb4b9)

       "react": "18.2.0",
    "react-native": "0.73.1",
    "react-native-cli": "^2.0.1",
    "react-native-track-player": "^4.0.1",
    
    I am using these dependencies but getting this error on windows application.
    Can you please help me there.

**Comment by dtembo98** [comment]
Getting the same error ,my project uses expo modules

**Comment by Klebervini49** [comment]
did they resolve it?
