### ISSUE TITLE
Can't not receive url deeplink IOS when click on notification metadata

### ISSUE THREAD

**Issue by vietdung97** [doublesymmetry/react-native-track-player#2260]
**Describe the Bug**
Hi everyone,
I can't get url data from Link on iOS when I click on the metadata notification like Android (Android works perfectly)
So, how do I get the string "trackplayer://notification.click" like Android?
**Code To Reproduce**
```
  useEffect(() => {
    async function deepLinkHandler(data: {url: string | null}) {
      if (data.url === 'trackplayer://notification.click') {
        //
      }
    }

    const listener = Linking.addEventListener('url', deepLinkHandler);

    Linking.getInitialURL().then(url => deepLinkHandler({url}));

    return () => {
      listener.remove();
    };
  }, []);
=> nothing happens on callback function of listener
```

**Environment Info:**
Paste the exact `react-native-track-player` version you are using: 4.0.1
Real device
What OS are you running: IOS 17

**Comment by MarianLudwig** [comment]
@vietdung97 Were you ever able to resolve this issue? I'm still experiencing this, Android works fine but on iOS the callback is never called.
