### ISSUE TITLE
"Require Cycle" warning is back on 4.0.1

### ISSUE THREAD

**Issue by cuchillitos** [doublesymmetry/react-native-track-player#2266]
**Describe the Bug**

When launching the app I get the "Require Cycle" warning that we've had in previous versions.
> Require cycle: index.js -> node_modules/react-native-track-player/src/index.ts -> node_modules/react-native-track-player/src/hooks/index.ts -> node_modules/react-native-track-player/src/hooks/useIsPlaying.ts -> index.js
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
Screen Capture on Android device:
![Foto seleccionada](https://github.com/doublesymmetry/react-native-track-player/assets/113452584/79990293-3236-42cf-b2da-ec9f9fc85c40)

**Steps To Reproduce**
How can someone else reproduce this bug?
Install 4.0.1, build and launch app

**Environment Info:**
Paste the results of `npx react-native info`

> System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 497.20 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v16.19.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.14.2 - /Users/jlopezdominguez/.rvm/rubies/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2023.2 AI-232.10227.8.2321.11479570
    Xcode: 15.3/15E204a - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.8.1 - /opt/homebrew/opt/openjdk@17/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.5 => 0.67.5
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Paste the exact `react-native-track-player` version you are using
4.0.1
Real device? Or simulator?
Both
What OS are you running?
Tested on Android 13 and 14, also iOS 16.4 and 16.5.1

**Comment by lovegaoshi** [comment]
try https://github.com/lovegaoshi/react-native-track-player/commit/de77707abb8d20042dcdfc014524b6bd84bf5f1b
