### ISSUE TITLE
Documentation site not working

### ISSUE THREAD

**Issue by neoassyrian** [doublesymmetry/react-native-track-player#2275]
**Describe the Bug**
Getting an HSTS error on Edge, and Chrome browsers when accessing the documentation site. Tested on multiple devices. Happens on devices that the site was never accessed before. 

**Steps To Reproduce**
Access the documentation site from a new device

**Code To Reproduce**

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

![image](https://github.com/doublesymmetry/react-native-track-player/assets/8149804/825542bc-52b0-4e81-9a9e-5de79e375def)

**Comment by dcvz** [comment]
Hi @neoassyrian are you still having this issue? Webpage is opening fine for me

**Comment by jspizziri** [comment]
Things look fine to me. Closing unless there's a repro.

**Comment by neoassyrian** [comment]
It's still happening to me. I'm surprised that no one else have this issue.
It's something to do with the .dev domain. 

https://shehackspurple.medium.com/hsts-preloading-of-all-dev-domains-troubleshooting-df44e2ad4f3e
