### ISSUE TITLE
RNTP.dev Website is down and no access to any documentation

### ISSUE THREAD

**Issue by nanonorthlabs** [doublesymmetry/react-native-track-player#2283]
**Describe the Bug**
rntp.dev website down

<img width="930" alt="Screenshot 2024-03-31 at 6 19 33 PM" src="https://github.com/doublesymmetry/react-native-track-player/assets/68917311/506ef90e-c675-4106-a953-7c81c489dbde">

**Comment by jspizziri** [comment]
Unable to reproduce. Looks like it's up again.
