### ISSUE TITLE
iOS Chromecast

### ISSUE THREAD

**Issue by colindaly** [doublesymmetry/react-native-track-player#2288]
It seems there have been requests for Chromecast on iOS dating back to 2017. With RTNP being very feature rich, this appears to be a glaring omission. Are there any plans to integrate soon - and if not - why not?

**Comment by lovegaoshi** [comment]
you're very welcome to port castplayer over, eg for chromecast: https://github.com/android/uamp
its a pain in the butt (castplayer is its own thing than exoplayer) and not enough interest.

**Comment by DennisdeWitNL** [comment]
You could always use react-native-google-cast. I use it next to RNTP and it works well.

**Comment by jspizziri** [comment]
@colindaly to echo @DennisdeWitNL , the best option is to use an external RN library that does casting. It's really its own concern and imho is best kept out of this library.
