### ISSUE TITLE
[Feature Request] Channel splitting and merging with volume control.

### ISSUE THREAD

**Issue by 7ammer** [doublesymmetry/react-native-track-player#2297]
**What is the need and use case of this feature?**
I have a scenario where by the audio player needs be able to adjust the audio volume for music and narration separately.

**Describe the ideal solution**
A way to achieve this could be by having one file with two channels. One channel as the audio and the other channel as the narration. Some sort of API could then split those two channels, adjust the gain for each as needed and then merge the split channels to both channels to create, in effect, one mono channel.

The [Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API) allows for this kind of thing and would be ideal.  The [createChannelSplitter](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createChannelSplitter) and [createChannelMerger](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createChannelMerger) are key.

I am not sure what the Android and iOS API's provide and if such a thing is possible with these API's. Is it: KotlinAudio and SwiftAudioEx?

**Describe alternatives you've considered**
The ability to stream two media files at the same time. This is complicated due to trying to keep the to files in sync. It feels very error prone.

**How I can Help**
I'd like to help but I'm not sure how useful I'd be.

**Comment by lovegaoshi** [comment]
i believe your best bet is expo-AV and use 2 instances of them, and update both instances simutaneously on seek/next/previous, etc. 
RNTP wont support playing multiple files (notification will simply not work) and the channel splitting seems not supported by exoplayer at least. if u happen to find code snippets perhaps someone bored enough will migrate over

**Comment by gerwim** [comment]
@7ammer Have you ever found a solution to your problem? This is exactly the feature I need. Have been trying to run multiple instances (but keeping them in sync is hard). My other options are:

1. Mix the audio files with ffmpeg (but I think it will not feel responsive enough, when the user changes the audio for a specific channel or sound)
2. Use the web API's in a browser frame (which is hidden for the user) and use some kind of bridge between the React Native application and the frame.
