### ISSUE TITLE
The buffer plays after waiting 20 seconds.

### ISSUE THREAD

**Issue by whyyuce** [doublesymmetry/react-native-track-player#2298]
Hello friends;
I have streams from 3 URLs in the player.

When I change the broadcast, buffering starts and play starts after 20 seconds.

No matter what I did, I couldn't understand why there was so much waiting.

![1](https://github.com/doublesymmetry/react-native-track-player/assets/47501980/2f61a1ad-9141-499c-9c21-ae64b8bdbb75)

I thought it was relevant here and changed it, but the result is still the same, each broadcast waits for 15-20 seconds of buffer before playing.

![image](https://github.com/doublesymmetry/react-native-track-player/assets/47501980/80d677a9-0e2b-4859-9060-cfa5f3b17d9b)

**Comment by whyyuce** [comment]
![image](https://github.com/doublesymmetry/react-native-track-player/assets/47501980/54b6e679-5537-4a6b-9c48-9c1a1334dcc5)
Additionally, the buffering process continues even though I stopped the broadcast.

**Comment by lovegaoshi** [comment]
wasnt there a template for bug reports?
since buffering is the problem try disabling it first

**Comment by lovegaoshi** [comment]
refer to the docs
https://rntp.dev/docs/api/objects/player-options
