### ISSUE TITLE
How to use in Web?

### ISSUE THREAD

**Issue by andreknieriem** [doublesymmetry/react-native-track-player#2300]
Hi am seeing, that the track player should work in web too, but I cannot get it to run? Is there anywhere an example app or a short tutorial how to use it on the web? Do I need react-native-web plugin too?

Best regards and thanks for your great work!

**Comment by jspizziri** [comment]
@andreknieriem , yes react-native-web is required. In terms of how to set up an app, there are a lot of different ways to do it. You can look at the example app for how to do it with a simple SPA. But using nextjs or other things are also possible. I'd recommend looking at how to get started with react-native-web first (lots of docs online), then fold RNTP into it.
