### ISSUE TITLE
One or more of the events provided to useTrackPlayerEvents is not a valid TrackPlayer event

### ISSUE THREAD

**Issue by DrMickArtisan** [doublesymmetry/react-native-track-player#2303]
**Describe the Bug**
I'm trying to migrate my app from RNTP 3.2 to RNTP 4.1
So, as a good dev (:)) I'm following the doc ("Migrating from v3.2 to v4"). And I read : 
```
General Deprecations
....
The following functions and events have been deprecated:
...
Event.PlaybackMetadataReceived - Please use [Event.AudioChapterMetadataReceived, Event.AudioTimedMetadataReceived, Event.AudioCommonMetadataReceived](https://rntp.dev/docs/api/events#metadata).
```
So  i just modify code with : 
```	
const events = [
		Event.AudioCommonMetadataReceived,
		Event.AudioTimedMetadataReceived
];
useTrackPlayerEvents(events, async (event) => {
	console.log(event)
	await _getCurrent()
})
```
instead of 
```
const events = [
		Event.PlaybackMetadataReceived	
];
useTrackPlayerEvents(events, async (event) => {
	console.log(event)
	await _getCurrent()
})
```
And after building my app, I got a warn : 
One or more of the events provided to useTrackPlayerEvents is not a valid TrackPlayer event: ', '. A list of available events can be found at https://rntp.dev/docs/api/events

So i'm like .. "Wait .. what ??"

**Comment by lovegaoshi** [comment]
welp, docs should be improved better. pls refer to the src code...
https://github.com/doublesymmetry/react-native-track-player/blob/6c4a3bd7d47c6ba8c85db4c1d031dc904bb0cd1a/src/constants/Event.ts#L123
basicsally there is no audio in the event namwe

**Comment by DrMickArtisan** [comment]
ha ok, got it, thanks !
