### ISSUE TITLE
HSL audio playing issue in android

### ISSUE THREAD

**Issue by AbinashBasak** [doublesymmetry/react-native-track-player#2304]
hi,
I am trying to play .m3u8 audio. In IOS it running perfectly. But in android getting {"code": "android-parsing-container-unsupported", "message": "Source error"}

this is the service file

```
import TrackPlayer, {Event, RepeatMode} from 'react-native-track-player';

export async function setupPlayer() {
  let isSetup = false;
  try {
    await TrackPlayer.getCurrentTrack();
    isSetup = true;
  } catch (error) {
    await TrackPlayer.setupPlayer();
    isSetup = true;
  } finally {
    return isSetup;
  }
}

export async function addTrack(playListData) {
  await TrackPlayer.add(playListData);
  await TrackPlayer.setRepeatMode(RepeatMode.Off);
}

export async function playbackService() {
  TrackPlayer.addEventListener(Event.RemotePause, () => {
    TrackPlayer.pause();
  });

  TrackPlayer.addEventListener(Event.RemotePlay, () => {
    TrackPlayer.play();
  });
  TrackPlayer.addEventListener(Event.RemoteNext, () => {
    TrackPlayer.skipToNext();
  });
  TrackPlayer.addEventListener(Event.RemotePrevious, () => {
    TrackPlayer.skipToPrevious();
  });
  TrackPlayer.addEventListener(Event.PlaybackError, err => {
    console.log(err);
  });
}

```

play.js

```
async function setup(url: string) {
    let isSetup = await setupPlayer();

    if (isSetup) {
      const track: Track = {
        url,
      };

      await addTrack([track]);
    }

    setIsLoaded(true);
  }

```

**Comment by lovegaoshi** [comment]
pls provide the source url to google's media3 repository and ask them there; RNTP doesnt do any media parsing, everything is handled natively.

**Comment by AbinashBasak** [comment]
Thanks. Got working solution.

**Comment by fizhy37** [comment]
> Thanks. Got working solution.

What was your solution? I'm having this same issue.

**Comment by AbinashBasak** [comment]
I'm using react-native-audio for android. And for iOS react-native-track-player working fine. Please note previously I am working with react-native-audio with other audio formate. And just rollback for android only.

**Comment by DongGukMon** [comment]
This is the part I was struggling with as well, so I'd like to leave a comment.

If you add type: TrackType.HLS to TrackPlayer.addTrack, it works.

```ts
trackPlayerService.addTrack({
    type: TrackType.HLS,
    ...
});
```

**Comment by MitoMonkey** [comment]
Just to make @DongGukMon s helpful comment a bit more clear/easy:
For me the crucial change was in
`const track: Track = { url: 'https://myURL.m3u8', title: 'myAudioFile', type: TrackType.HLS} /* other params */`

**Comment by PrajaRavi** [comment]
@MitoMonkey 
const track: Track = { url: 'https://myURL.m3u8', title: 'myAudioFile', type: TrackType.HLS /* other params */} This code is not working properly
