### ISSUE TITLE
[Feature Request] How to embed ads in a song

### ISSUE THREAD

**Issue by 03k09i** [doublesymmetry/react-native-track-player#2317]
I am using "react-native-track-player": "^4.1.1"
How to embed ads in a song

**Comment by tranminhnhat1005** [comment]
You can use the Queue for your case, ex: 
`const tracks = [SOUND, AD, SOUND, AD, SOUND, AD...];
  await TrackPlayer.add(tracks);`
  
  In the progress, you can use event listener with type Event.PlaybackProgressUpdated to update the TrackPlay:
`TrackPlayer.addEventListener(Event.PlaybackProgressUpdated, event => {
    // do something with event info, can use TrackPlayer event here
  });`
  
  Hope it useful 😂
