### ISSUE TITLE
Audio stopped playing after 17.5.1 IOS update

### ISSUE THREAD

**Issue by Levi-Teixeira** [doublesymmetry/react-native-track-player#2334]
**Describe the Bug**
I have an audio reproduction app and the tracks suddently stoped playing on Ios after the last 17.5.1 update.
There are no immediate logs of error concerning the reproduction, but a long time after hitting the play button tho, 
I get this log on the console: `tcp_input [C69.1.1:3] flags=[R] seq=2659539961, ack=0, win=0 state=LAST_ACK rcv_nxt=2659539961, snd_una=2641334348`

Is anyone experiencing anything like this? Android works fine.

**Steps To Reproduce**
1. Open the app
2. Reproduce any kind of audio

**Environment Info:**
"react-native-track-player": "^4.1.1",
Error occurs both on the real device and simulator, but sometimes the Iphone 15 Pro Max simulator works fine.
IOS 17.5.1

**Comment by gmach** [comment]
This is a real blocker for our project release. Bumping this up.

**Comment by jyeharry** [comment]
My workplace is experiencing similar issues with our audio app.
- Audio stops after roughly an hour.
- Only seems to affect iOS.
- Doesn't seem to affect a colleague who's on iOS 17.4.1.

**Comment by anthonyhienvu-nine** [comment]
I am also experiencing this issue on iPhone SE iOS v17.5.1. Live stream audio automatically stops after roughly an hour. Doesn't seem to affect android or iOS versions less than 17.5.1.

**Comment by puckey** [comment]
Have any of you made sure this issue is specific to `react-native-track-player`?

**Comment by jyeharry** [comment]
I haven’t been able to confirm, I’m still in the process of narrowing it down. But in that process we saw this issue and considering my colleague is on iOS 17.4.1 and is unaffected by the issue we’re experiencing I thought I’d add weight to this theory.


On 28 Jun 2024, at 5:21 PM, Jonathan Puckey ***@***.***> wrote:

﻿

Have any of you made sure this issue is specific to react-native-track-player?

**Comment by Levi-Teixeira** [comment]
> Have any of you made sure this issue is specific to `react-native-track-player`?

Trust, me. I've done several hours of debbuging and recently I was able to actualy get an error message;
![image](https://github.com/doublesymmetry/react-native-track-player/assets/69545312/48ed502e-a83a-4283-93a8-4a19c906201c)

// {"error": {"code": "ios_track_unplayable", "message": "The track could not be played"}, "state": "error"}

**Comment by Levi-Teixeira** [comment]
Now, what i've noticed is that although it does works sometimes, the error always happens when the `State` of the player gets stuck on {"state": "loading"} or {"state": "buffering"} never being {"state": "ready"} unlikely what happens when running the android version of our app.

**Comment by gmach** [comment]
@Levi-Teixeira  Are you playing a HLS livestream ending in .m3u8 also?

**Comment by Levi-Teixeira** [comment]
@gmach No. Good old .mp3 tracks.

**Comment by lovegaoshi** [comment]
can u monitor network activity at when error happened? i mean if the audio stops ~1hr it sounds like a background problem? does ios 17.5.1 introduce some kind of background limitation or resource optimization patch in their logs?
or if a track consistently stops/errors can u post the link?
disclaimer tho i dont use mac/ios at all.

**Comment by prabhav-mehra** [comment]
@Levi-Teixeira Were you able to repro the issue consistently (if yes, how). I get few error reports from users but I can't repro it on my end
