### ISSUE TITLE
Remove currentTrack

### ISSUE THREAD

**Issue by HoseinAsadi** [doublesymmetry/react-native-track-player#2336]
hi
how i can currentTrack removed?????????

when remove currentTrack  app crashed

**Comment by lovegaoshi** [comment]
im going to assume ur looking for tp.reset(). otherwise u have to learn to use the issue template.

**Comment by HoseinAsadi** [comment]
@lovegaoshi 
hi 
When I use the reset method for the currently playing song, the app crashes!!!!!!!!!!!!!!!!

**Comment by lovegaoshi** [comment]
dude i dont have a crystal ball. u have to learn to use the bug template.
