### ISSUE TITLE
Unable to play and load from url

### ISSUE THREAD

**Issue by saiaryan** [doublesymmetry/react-native-track-player#2353]
**Describe the Bug**
I am unable to load and play the .wav from url

**Steps To Reproduce**
add a "https://www2.cs.uic.edu/~i101/SoundFiles/BabyElephantWalk60.wav" in TrackPlayer.add();
and do TrackPlayer.play()

**Code To Reproduce**
const track = {
          url: `https://www2.cs.uic.edu/~i101/SoundFiles/BabyElephantWalk60.wav`,
        };
await TrackPlayer.add();

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)?

**Environment Info:**
Paste the results of `npx react-native info`
Paste the exact `react-native-track-player` version you are using
Real device? Or simulator?
What OS are you running?

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

**Comment by lovegaoshi** [comment]
no crap u cant play anything **if u dont actually add the track and just pass no args in TP.add**

`await TrackPlayer.add();`

**Comment by saiaryan** [comment]
@lovegaoshi added the track to await TrackPlayer.add([track]) but unable to play this url "https://www2.cs.uic.edu/~i101/SoundFiles/BabyElephantWalk60.wav"

**Comment by lovegaoshi** [comment]
you need to **try on the example app first** bc it works on mine
![image](https://github.com/user-attachments/assets/506aa03f-c1a7-43fa-bf6d-a5c14de641a8)

**Comment by bradfloodx** [comment]
Sorted then. Works on example app. Thanks :)
