### ISSUE TITLE
I face this issue can not play url audio, please help me

### ISSUE THREAD

**Issue by mzduc01** [doublesymmetry/react-native-track-player#2354]
I face this issue can not play url audio in ios but in android it working fine, please help me 

Here is the link:
https://rr7---sn-42u-i5old.googlevideo.com/videoplayback?expire=1723624921&ei=eRm8ZrHoMoKKvcAPlcn2sAE&ip=118.70.127.59&id=o-AIxtjljVMTj0iBWsEj3Vt_WzGni5sDE_QARQKVGHknM0&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=f5&mm=31%2C26&mn=sn-42u-i5old%2Csn-un57ene6&ms=au%2Conr&mv=m&mvi=7&pcm2cms=yes&pl=20&initcwndbps=2336250&bui=AQmm2ewfXYlWYRCbQECD0a1MSlxDNMDBpX7dcWjnQBiRZJNHCQ4w9NUuw1A-iqlJAP_IFcO7bUnVrx6i&spc=Mv1m9oVz0Ht42-qlEeRV_k_SzkR_5jgInLbs_iik_3LwaX4niP1H&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=xF59VChR9G_rNzGzICfT0YYQ&rqh=1&gir=yes&clen=5847793&dur=366.841&lmt=1714681945030851&mt=1723602777&fvip=4&keepalive=yes&c=WEB_CREATOR&sefc=1&txp=4502434&n=WoGWddh2dRmeFw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRQIgNrV0mr1LXRpSdgGBfrsTxSZlt8udBNfVoNqIOqGvGvkCIQCD2TbXMGACE2yD82-rr77_firWCzqOf9HaA0NBuqnt7g%3D%3D&sig=AJfQdSswRgIhAL24riSz02EzE0OrcIB7VimS-CecuzVUrygY_Gh_hhf3AiEA5V9PbZTSxfflDdd_u9abeXHQL6KWCApmgawPZm0fTuQ%3D

_Originally posted by @mzduc01 in https://github.com/doublesymmetry/react-native-track-player/issues/689#issuecomment-2287764291_

**Comment by lovegaoshi** [comment]
do NOT skip the issue template??? wtf?
with that said i do know the answer to your ridiculously vague question. the link u post is a google/ytb streamable link. and its likely in the DASH format. iOS does NOT support DASH. u have to use HLS. 
a simple solution is to filter the formats to only include mp4a formats.
https://github.com/lovegaoshi/azusa-player-mobile/blob/3c93fb1e8f5274919560716218a0974476648a31/src/utils/mediafetch/ytbvideo.node.ts#L8

**Comment by bradfloodx** [comment]
Please use the issue template. Thanks :)
