### ISSUE TITLE
v3.2.0 missing foreground service type

### ISSUE THREAD

**Issue by pjly458** [doublesymmetry/react-native-track-player#2375]
**Describe the Bug**
the current highest v3 release (3.2.0) is missing the foreground service type in the Android manifest. This has been fixed in the v3.2 branch a year ago but no new release tag has been made. Are there plans to release v3.2.1 with this fix in it?

thanks!

**Comment by lovegaoshi** [comment]
v3 is long deprecated. its not going anywhere unless u maintain it urself.
