### ISSUE TITLE
Android Audio Notification is swipeable, but doesn't stop audio when swiped.

### ISSUE THREAD

**Issue by ConnerPC88** [doublesymmetry/react-native-track-player#2379]
**Describe the Bug**
After starting audio through the track player and then locking the device screen, an audio notification pops up at the top with controls and metadata. This notification is swipe-able (dismissible), but when it is dismissed the audio continues to play. The expected behavior is that it should either not be dismissible, or it should stop audio playback when dismissed.

**Steps To Reproduce**
1. Start audio using the track player
2. Lock the device
3. Swipe/dismiss the audio controls notification
4. Hear the audio still playing

**Code To Reproduce**
Just the general track player setup, no extras needed.
Make sure appKilledPlaybackBehavior is set to StopPlaybackAndRemoveNotification

**Replicable on Example App?**
Yes

**Environment Info:**
```
System:
  OS: Windows 11 10.0.22631
  CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
  Memory: 1.84 GB / 15.70 GB
Binaries:
  Node:
    version: 20.15.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 4.3.1
    path: C:\Program Files\nodejs\yarn.CMD
  npm:
    version: 10.7.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.10.34928.147 (Visual Studio Community 2022)
Languages:
  Java: 17.0.11
  Ruby:
    version: 3.3.2
    path: C:\Ruby33-x64\bin\ruby.EXE
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.2
    wanted: 0.74.2
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

react-native-track-player: "npm:^4.1.1"

Google Pixel 6 running Android 14

**Comment by lovegaoshi** [comment]
you are NOT able to dismiss the notification player control while there is playback from RNTP. also see https://github.com/androidx/media/issues/211#issuecomment-1325014567. 

pixel has a "shortcut" notification before you swipe down to show the full notification panel. you may be able to dismiss playback control on the shortcut panel, but you cannot on the full panel. This is a pixel specific behavior. you need to consult google/pixel on whatever events emitted from that.
