### ISSUE TITLE
Mute or Pause Audio on screen recording 

### ISSUE THREAD

**Issue by pro-softs** [doublesymmetry/react-native-track-player#2380]
**Describe the Bug**
Even if we disable the screen recording with expo , the audio playback gets recorded. I want to disable recording of audio during screen record. 

**Steps To Reproduce**
Play any audio with this module. Then start screen recording. Audio is captured in the screen recording video

**Environment Info:**
Paste the results of `npx react-native info` -
System:
  OS: macOS 14.4.1
  CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Memory: 47.28 MB / 8.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 20.1.0
    path: ~/.nvm/versions/node/v20.1.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/Documents/projects/fanfliq/fanfliq-app/fanfliq-fan-app/node_modules/.bin/yarn
  npm:
    version: 9.6.4
    path: ~/.nvm/versions/node/v20.1.0/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/progupta/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11668458
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/local/opt/openjdk@17/bin/javac
  Ruby:
    version: 2.6.3
    path: /Users/progupta/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

`react-native-track-player` version - 4.1.1
Using on Real device
Both Android and ios.

**How I can Help**
There is an option in Android using AudioManager.setAllowedCapturePolicy in android to disable system or third-party app to disable the audio capture. Any possibility to use this in the code. I tried adding this in the MusicService.kt file but couldn't get it working. Can anyone help out with this.

**Comment by lovegaoshi** [comment]
this should be implemented by YOU. organize AudioManager.setAllowedCapturePolicy calls in your own module/activity.

**Comment by pro-softs** [comment]
Yeh As mentioned I did but it was not working. Is there any solution for this in Android?

**Comment by lovegaoshi** [comment]
look up in the android dev documentation..?

to help you ask a better question next time, you posted no information that
nobody knows what you did. and you would have a better chance asking in the
native android community, as this has nothing to do with rn or rntp.

**Comment by pro-softs** [comment]
It's fine if you can't help. Asking this question here is appropriate as this library uses the underlying kotlin audio player which has the AudioAtributes implementation which according to Android documentation should support the playback capture blocking.

I have created my own build and used in my app. Closing this now.
