### ISSUE TITLE
Having version 0.76.0 or 0.76.1 with new Architecture.

### ISSUE THREAD

**Issue by MoamberRaza** [doublesymmetry/react-native-track-player#2391]
**Describe the Bug**

**Steps To Reproduce**
How can someone else reproduce this bug?

**Code To Reproduce**
Please provide a simple code example that allows others to replicate the bug.

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)?

**Environment Info:**
Paste the results of `npx react-native info`
Paste the exact `react-native-track-player` version you are using
Real device? Or simulator?
What OS are you running?

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

**Comment by MoamberRaza** [comment]
Error: Exception in HostObject::get for prop 'TrackPlayerModule': com.facebook.react.internal.turbomodule.core.TurboModuleInteropUtils$ParsingException: Unable to parse @ReactMethod annotation from native module method: TrackPlayerModule.add(). Details: Unable to parse JNI signature. Detected unsupported return class: kotlinx.coroutines.Job [Component Stack]

**Comment by lovegaoshi** [comment]
seriously, learn to fill in the issue template, and also google. there are at least 2 issues describing the exact same thing, which is RNTP does NOT support the new arch, in this repository.

https://github.com/doublesymmetry/react-native-track-player/issues/2293
https://github.com/doublesymmetry/react-native-track-player/issues/2389

and 2 PRs that are actively tracking the new arch support.
![image](https://github.com/user-attachments/assets/fe5c6736-291c-469b-9a2c-38e8b51a6a5d)

**Comment by Praveenesarla** [comment]
is the issue resolved???, iam still facing it

**Comment by shahedzaman-web** [comment]
I'm also struck on the same issue.

**Comment by SurajTopal** [comment]
I am still face this issue.
