### ISSUE TITLE
.m4a File Format Not Supported for Playback

### ISSUE THREAD

**Issue by vargheshpanadem** [doublesymmetry/react-native-track-player#2397]
Does not support .m4a audio file playback, resulting in errors or undefined behavior when attempting to load and play files with this format. This issue impacts users who rely on .m4a files for audio content and prefer not to convert them due to timing inconsistencies that conversions often introduce.
 
**Request**: Please add support for .m4a format to ensure seamless playback. .m4a is widely used, and native support on both iOS and Android should make this addition feasible.

@dcvz

**Comment by puckey** [comment]
fill in the issue template
