### ISSUE TITLE
Can not build app when apply and link this library (iOS)

### ISSUE THREAD

**Issue by ducchungtx** [DoubleSymmetry/react-native-track-player#272]
`Installing build/Build/Products/Debug-iphonesimulator/truyenaudio.app
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Underlying error (domain=MIInstallerErrorDomain, code=4):
        Failed to chmod /Users/chungnguyen/Library/Developer/CoreSimulator/Devices/3B60952C-CCA9-4052-8FD6-031DA62A9202/data/Library/Caches/com.apple.containermanagerd/Bundle/Application/3566ABD2-BA45-45AB-B3ED-CAE15CC3C241/truyenaudio.app/truyenaudio : No such file or directory`

I tried many ways but  it not work. 
Has anyone ever encountered this problem yet?

**Comment by dcvz** [comment]
Looks like it's an issue with your simulator. You can also try to use the latest version of the lib

**Comment by imansal** [comment]
Same Error :(

**Comment by bgwaltney** [comment]
I get the same thing. Any update on this?

**Comment by dcvz** [comment]
This definitely seems to be an issue with your machine. Want to share your repo with me? I can then have a look.

**Comment by cylwin** [comment]
+1

**Comment by curiousdustin** [comment]
Anyone still facing this? If so what version?
