### ISSUE TITLE
Earphone eject not getting pause event in IOS with version "0.2.5"

### ISSUE THREAD

**Issue by hsparihar-systango** [DoubleSymmetry/react-native-track-player#323]
Issue is with version " 0.2.5" while i eject earphone from ios device player didn't get 'remote-pause' event but audio stoped so my custom play/pause buttons behaves abnormally, while in Android it is working fine.
When i re-pluged earphone in IOS then suddenly it got pause event.

**Comment by hsparihar-systango** [comment]
@egorkhmelev @puckey @frenkie 
need functionality like:

// on iOS this event will also be triggered by audio router change events
// happening when headphones are unplugged or a bluetooth audio peripheral disconnects from the device
`    MusicControl.on('pause', ()=> {
      this.props.dispatch(pauseRemoteControl());
    })`


this is available on 
> react-native-music-control

**Comment by radiospiritsapp** [comment]
@egorkhmelev  @puckey  @frenkie  @Guichaguri 
I have fixed this issue for my project, so i would suggest if you can add this changes to actual lib so other can use this as well.
please let me know what you suggest.

**Comment by moonstruck** [comment]
@radiospiritsapp it seems you have moved back to 0.2.5 on your forked [version.](https://github.com/radiospiritsapp/react-native-track-player)

**Comment by Guichaguri** [comment]
@radiospiritsapp please, feel free to open a pull request with the fix.

**Comment by curiousdustin** [comment]
I initially had this issue as well.

I'm not certain exactly which version addressed this, probably 1.1.0 with the re-vamped iOS player.

It still does not fire `remote-pause`, but I don't believe it should.

Instead, the audio is automatically paused, as the iOS docs specify it should, and the corresponding `playback-state` event is fired so you can update UI.

I would consider this resolved.
