### ISSUE TITLE
Android - Disconnect from Bluetooth/Aux doesn't pause

### ISSUE THREAD

**Issue by jasongrishkoff** [DoubleSymmetry/react-native-track-player#337]
If I'm driving my car listening to my app via Bluetooth and turn off the car, my phone keeps playing music through its speaker and doesn't seem to fire any events related to the audio input being removed.  Similarly, if I unplug my headphones, the music keeps playing and doesn't fire any events.

**Comment by Guichaguri** [comment]
It's one of those little things we missed in the recode. Let me know if 25c422dcfee3be061a46b48af6bb398ce38cd04c fixes it for you.

**Comment by jasongrishkoff** [comment]
I'm not actually sure this is closed -- the new version of the notification you pushed out doesn't seem to always stop playing when disconnecting bluetooth.

**Comment by Guichaguri** [comment]
I just tested with a regular headphone and it seems to be working in 1.0.2. Can you try it out, please?

The Android docs clarify a bit when it's triggered:
> Broadcast intent, a hint for applications that audio is about to become 'noisy' due to a change in audio outputs. For example, this intent may be sent when a wired headset is unplugged, or when an A2DP audio sink is disconnected, and the audio system is about to automatically switch audio route to the speaker. Applications that are controlling audio streams may consider pausing, reducing volume or some other action on receipt of this intent so as not to surprise the user with audio from the speaker.
> 
> https://developer.android.com/reference/android/media/AudioManager.html#ACTION_AUDIO_BECOMING_NOISY

**Comment by jasongrishkoff** [comment]
This has happened a few more times for me in the last couple days -- I'll park my car, turn it off, and walk away, but the music keeps playing. Hard to replicate though because it doesn't happen every time.

**Comment by Guichaguri** [comment]
I see this is going to be pretty hard to reproduce. I'll leave this issue open though, let me know if you find any patterns on that.
