### ISSUE TITLE
More than 20 seconds delay to play after Player in Ready State

### ISSUE THREAD

**Issue by vbspace** [DoubleSymmetry/react-native-track-player#342]
Hi All, I am adding the song one by one, the song is being played from a url, but the problem is that after a call play(), the song takes between 3 to 20 seconds on even more sometimes. Can someone help me solve this problem pls ?

**Comment by ntk860** [comment]
@guichaguri IOS
I'm using version 1.0.0

**Comment by ntk860** [comment]
@Guichaguri any suggestions ?

**Comment by ntk860** [comment]
@Guichaguri it is working well on the simulator, but when I test on a real device it does not work as expected, sometimes I have to wait forever.

**Comment by ntk860** [comment]
@dcvz any suggestions about this issue ?

**Comment by ishigamii** [comment]
Experimenting the same with a little delay at the beginning of the reading.

**Comment by CapitanRedBeard** [comment]
@ntk860 	@ishigamii 	I haven't seen this on iOS or Android and I'm using 1.0.0 and loading pretty large mp3s over the network. Maybe mess around with the `track-player.json` settings

Mine look like:

**Comment by ntk860** [comment]
@CapitanRedBeard  let me try this. Also it varies from device to device. On iPhone 5 the delay is less than on iPhone X

**Comment by Guichaguri** [comment]
The `track-player.json` config is only used in Android, and only defines which addons will be bundled with the app.

**Comment by ntk860** [comment]
@dcvz any updates ?

**Comment by dcvz** [comment]
Is this issue still appearing in the release from today? (1.1.0)

**Comment by ntk860** [comment]
I am using the #dev version, let change to 1.1.0 and see what happens. Thank you!

**Comment by ntk860** [comment]
@dcvz it worse, but this time its happening on the simulator and device. The status says the its playing but it takes a long time to calculate the duration and play the audio.

**Comment by ataravati** [comment]
@dcvz I'm having the same issue. Changing the buffer settings doesn't help. It looks like the entire file is loaded before being played.

**Comment by ataravati** [comment]
@dcvz By the way, it looks like `getBufferedPosition` always returns 0.

**Comment by ntk860** [comment]
Something I am noticing about this issue is that, in version 1.1.1 its playing after the first couple of bytes are received, the problem is that sometimes its taking very long to receive the first bytes.

**Comment by ntk860** [comment]
I think there is an improvement on this issue for version 1.1.1, after I call play the song starts buffering, and plays when its finish buffering. The problem now is that its taking so much time buffering, my guess is that its waiting until the all song gets buffered and them play it.

**Comment by dcvz** [comment]
Looking into this now, will keep ya'll posted

**Comment by dcvz** [comment]
Could someone who is getting this issue please try this commit? 73cf52bd2135d2c7ff472c97a4ab92809b6c47a8

**Comment by ntk860** [comment]
@dcvz I think its working now, some songs that I am playing are still taking a considerable amount of time buffering, and I think it has to do with kbps of the songs I am playing. What do you think is the best format to use ? WAV, MP3 or OGG ?

**Comment by ataravati** [comment]
@dcvz @ntk860 No, it's still not working. `getBufferedPosition()` always returns 0. Also, changing the `setupOptions` (`minBuffer`, `playBuffer`,...) doesn't have any impact.

**Comment by ntk860** [comment]
@ataravati minBuffer, platBuffer is only for android. getBufferedPosition() is returning 0 after the song starts playing ?

**Comment by ataravati** [comment]
@ntk860 It doesn't say that in the documentation. Are you sure you're not confusing with the build preferences (https://github.com/react-native-kit/react-native-track-player/wiki/Build-Preferences)?

Yes, it returns 0 before and after the song starts playing.

**Comment by ntk860** [comment]
@ataravati I am sorry, in my use case I don't need to use getBufferredPosition(). When I said its working I was saying that the delay disappeared and the buffering is considerable short.

@dcvz I tried playing a wav file and the buffering is much less compared with a mp3. Thank God I am still beta testing, and that was the issue that was holding me back to release to production.

**Comment by ataravati** [comment]
@dcvz any updates on this?

**Comment by markgoodyear** [comment]
I'm also experiencing this issue on iOS, and using 1.1.3.

I've tried many things, but ultimately, it appears there are a few issues here. Firstly, when a track is added to the queue, it begins to buffer immediately, even without attempting to play. Secondly, It looks like it waits for the entire file to be buffered/downloaded before it is able to play. I've added a download for offline feature in my app, and the download time is the same as Track Player's buffer time.

Thirdly, this becomes a problem when in a queue, because if one track is buffering, skipping to another has to wait until the previous one finished buffering, before it then adds and buffers the next one. Put two large tracks next to each other and skip between them and player state can get stuck in the loading state. There is also no caching, so skipping back and forth will repeat this process too.

Right now it would appear, for iOS at least, it looks like it'd be best to just download the track, then use the downloaded file rather than a remote one, and do a clean up of the files on reset or something. At least that way, skipping between tracks in a queue will already have them ready to play without buffering/loading the tracks that are in the queue each time.

Hopefully that info can help with being able to resolve the issues, I'm happy to test anything.

**Comment by dcvz** [comment]
thanks for the detailed report @markgoodyear :) this should help pin down what's going on

**Comment by jariwalabhavesh** [comment]
@dcvz : I am facing the same issue with version 1.1.4 which @markgoodyear mention. Is there any solution out there.

**Comment by FrankGoortani** [comment]
V 1.1.8 still the same. the delay got worse.

**Comment by FrankGoortani** [comment]
@dcvz If you give me an idea where to look I might be able to help fix this issue. This is hindering our iOS experience! ( you can try this on our app maktub.app )

**Comment by deepaksingh16** [comment]
Any updates on this? Player is taking too long to play tracks.Same goes when skip to next and previous song.

**Comment by jariwalabhavesh** [comment]
@deepaksingh16 : Have you tried latest version 1.2.3. I think i had updated to latest version and doesn't seems to be issue there.

**Comment by deepaksingh16** [comment]
@jariwalabhavesh I'am using v1.2.3 and the issue still persists. Let me know if you've made any changes while setting up player.

**Comment by deepaksingh16** [comment]
@dcvz Can you please look into this issue as this is still happening in v1.2.3?

**Comment by curiousdustin** [comment]
@deepaksingh16 do you experience the issue in the example app? If so, are you able to share some URLs to test with?

**Comment by deepaksingh16** [comment]
@curiousdustin I was able to play song in app. Thank you for directing me to demo app.
However I would like to share the reason for this issue.

The issue arises when i try to use code as follows:
```
await TrackPlayer.skipToPrevious().then(() => {
// Code after skipping            
})
```

However without using _**then**_ , it works completely fine. Like code below
**await TrackPlayer.skipToPrevious()**
`// Code after skipping
`

Hope it helps anyone having same problem and there could be something that we can fix for next versions.

**Comment by curiousdustin** [comment]
In you first example, you don't need to use `await` if you are using `.then()`. Does it also resolve your issue if you remove `await`?

**Comment by deepaksingh16** [comment]
@curiousdustin No that didn't solve the problem. Actually it was without await in my code for first example. I mistakenly put it here.
But the solution was not to use **then** in this case.

**Comment by curiousdustin** [comment]
Would you be able to share a more detailed example of what code you were trying to run within `.then()`?

It _should_ be able to be used this way.

**Comment by deepaksingh16** [comment]
I was just logging analytics event inside `.then()`

e.g. `await analytics().logEvent(EVENT_NEXT_SONG, {})`

**Comment by akapoordeqode** [comment]
I am also facing the same issue, 
When I click on the play button then it takes 10-15 seconds to update the timecode and the time code is not increasing continuously. I don't know what's wrong is happening.

**Comment by komelabbbas** [comment]
any updates on this?

**Comment by Ogala** [comment]
I have recently seen this problem with HLS files in `v3.2.0`. While it plays `.mp3`s relatively quickly, there's a delay of `>=8secs` when playing HLS files.

**Comment by whyyuce** [comment]
@fmalbacete Is there any progress on this issue?

**Comment by Qurat-ul-ainn** [comment]
> Hey guys!!
> 
> Me and the team are having this issue too.
> 
> Starting from local or network the audio starts after ≃ 15s
> 
> Do you guys have some configs that can help us ?
> 
> If not we will try on our side and post here.
> 
> Thanks!!

do you find any solution?
