### ISSUE TITLE
Audio stop playing for no reason

### ISSUE THREAD

**Issue by rgagnon** [DoubleSymmetry/react-native-track-player#374]
On android on release mode for no reason, sometime the mp3 stops playing.

Is there a way to know if I'm running on exoplayer?  Do you have any suggestions on how to debug it and or getting any logs when this happen?

**Comment by Guichaguri** [comment]
In your `AndroidManifest.xml` file, add the property `android:debuggable="true"` into the `<application>` tag, that should make the app visible from logcat.

**Comment by rgagnon** [comment]
Thank you,

I was already there.

I meant when the player stops nothing is nothing in logcat.  It just
stops.  I added the event playback-error, nothing is triggered

**Comment by Guichaguri** [comment]
Can you send the mp3 url/file you're trying to play?

**Comment by ntk860** [comment]
I am experiencing the same thing. I add the songs one by one. The first song on my array plays fine until the end, the second stops for no reason or prior event. Its only happening in android.

**Comment by Guichaguri** [comment]
I'll try to reproduce the problem and will get back to you soon.

**Comment by Guichaguri** [comment]
Thanks, that helped me reproduce the issue.

Here is a fix: 05b8725e7a82ccbfe5d8b92e33db9281d0ff7d73. Let me know if it solves the problem for you.

**Comment by rgagnon** [comment]
Hi,

Does not seem to fix the issue.  I would say, its worst.  As soon I add a new mp3s in the list when the queue is ended, the player stops without log

**Comment by Guichaguri** [comment]
Can you send your code so we can try to reproduce the problem?

**Comment by rgagnon** [comment]
@Guichaguri well, you want the entire project or snippet?  I'm adding to playlist 3 mp3 at the time, when its all played I call an api to get me 3 others.  Its not music, its podcast. This happen after a call from my backend to get mp3.  It does not happen on iOs though.  Looks like it stops buffering...

Podcast duration is around 25 minutes.

**Comment by Guichaguri** [comment]
I'll try what you've described, but a snippet that allows me to reproduce the issue is more than enough.

**Comment by chrise86** [comment]
I'm facing a similar situation on iOS with a network stream. It'll just stop randomly in the background on release mode. Opening the app shows that it is "buffering", but it just seems to hang there until you close the app completely and re-open. It then starts playing imediately, as expected.
