### ISSUE TITLE
Upgrading the event handler, some events not triggering

### ISSUE THREAD

**Issue by Alanz2223** [DoubleSymmetry/react-native-track-player#379]
Using the latest dev version as of this moment. I am trying to refactor my code to use the new event handling mechanism since registering events with
 `AppRegistry.registerHeadlessTask('TrackPlayer', () => require('./app/modules/player/player-handler.js')(store));`  is not working anymore.  I am using the example as a guide and have replaced that statement with
 `TrackPlayer.registerPlaybackService(() => require('./app/modules/player/player-handler.js')(store));`. 
The store variable is my redux store since I trigger side effects within the handlers. 

Now within `player-handler.js` I have the following code

`module.exports = (store) => {

    return async (evt) => {

        TrackPlayer.addEventListener('playback-track-changed',(evt) => {
            console.log('playback changed');
            if(evt.nextTrack && evt.track)
            {
                store.dispatch(playerActions.playerTrackChanged(evt.track, evt.nextTrack));
            }
           
        } );

        TrackPlayer.addEventListener('playback-queue-ended',(evt) => {
            console.log('queue end');
            store.dispatch(playerActions.playerQueueEnded());
            
        } );

        TrackPlayer.addEventListener('remote-play',(evt) => {
            console.log('remote play');
            store.dispatch(playerActions.togglePlay());
        } );

 }
}
`

Now whenever my application starts up and I setup the player. It dispatches the 'player-queue-ended' event which it did not previously fire.. However the bigger issue is that whenever I press the play button in the notification the 'remote-play' event is not firing. Any thoughts? Thanks

**Comment by Guichaguri** [comment]
For an easier update on your side, you can replace `registerHeadlessTask` with the `registerEventHandler` function instead.

This issue seems to be related to #343
