### ISSUE TITLE
1.0.2 - Trackplayer JavaSocketTimeout permanently kills service

### ISSUE THREAD

**Issue by ghost** [DoubleSymmetry/react-native-track-player#389]
As mentioned here #386, but I think it deserves it's own separate issue.

When the device loses internet connection for a remote url after a short period of time the service is killed with a JavaSocketTimeoutExecption. 

- It does not restart when connection is regained
- Loading a new track will also not work (it seems the service is completely dead)

A few things to think about here; extending the socket timeout to something >60 seconds, and letting the service restart on the same track where it left off.

**Comment by visagegod** [comment]
Hi @Guichaguri, this is becoming a release blocker for me, I'm happy to dive into the Java code to build a fixing PR, do you have any advice on where to start? 
Thanks
