### ISSUE TITLE
[ios] Incorrect progress after seek and some time end event never fire

### ISSUE THREAD

**Issue by hoang-rio** [DoubleSymmetry/react-native-track-player#393]
I currently use version af342677352a1564c591f4fde240f0b7bef41724 in my project.
I think Trackplayer have issue with seek feature. After seek progress and current time is incorrect. Current play time can creater than duration.

Another issue is some time `playback-queue-ended` nerver fire. Queue ended but event not fire. I think this issue related with progress and current playing time feature.

**Comment by hoang-rio** [comment]
Yes, it seen related to #310 and `playback-queue-end` event not fire is new issue

**Comment by alburdette619** [comment]
I am working off of a fork but have updated commits from July 18th and am still seeing this issue.  I know this is suspect of course.  We cannot upgrade to RN 0.6x yet and so we're keeping up without AndroidX currently.
