### ISSUE TITLE
Building 1.1.0 for IOS swift 4.1 is failing

### ISSUE THREAD

**Issue by vbnospace** [doublesymmetry/react-native-track-player#400]
@dcvz I updated to 1.1.0 but I am having problems building the project. The Image below shows the the Xcode complains.

<img width="1680" alt="screen shot 2019-01-20 at 4 25 18 am" src="https://user-images.githubusercontent.com/17445149/51437981-977ada00-1c6b-11e9-9c27-02fb046a97e4.png">

**Comment by dcvz** [comment]
Do you also see this issue with Swfit 4.2?
