### ISSUE TITLE
playback-error not work

### ISSUE THREAD

**Issue by GH974** [DoubleSymmetry/react-native-track-player#421]
Hi, i have tested last version of plugin 1.1.2
and event playback-error is not called if network connection stopped.

APP => IOS
and if app played and i have refresh app with cmd - R, plugin don't stop music.

And i receive paused event playback-state, while this music is playing

**Comment by holospeed** [comment]
I noticed the same at version 1.1.4 
I had no error message when the internet connection has been stoped or when the source file missed, pointed to wrong place or was a not supported format.
