### ISSUE TITLE
updateOptions breaks down event system

### ISSUE THREAD

**Issue by alexolefirenko** [DoubleSymmetry/react-native-track-player#424]
Hello. Tested on iOS simulator and iPhone X.
The problem is when I call `updateOptions` fn and put there an object that consists a `capabilities` property (I need to disable or enable arrows it depends on queue) the handlers for remote events when I click from notification center fires multiple time and it depends on how much times I call `updateOptions` and updated properties use this one fn... It seems to me that you subscribe again to listen to events when I call `updateOptions`
I went through swift code, but I could not understood why it happens (

Also, I found that typings for a `notificationCapabilities` field  is wrong. The field should be optional

**Comment by dnish** [comment]
@alexolefirenko Could you try my solution in #423 . If it also works for you I can create a PR.

**Comment by HessiPard** [comment]
> @alexolefirenko Could you try my solution in #423 . If it also works for you I can create a PR.

It is fixed for IOS. how about Android?
Problem exists in Android with track-player `1.1.8`

**Comment by farshed** [comment]
Check out my solution for android: https://github.com/react-native-kit/react-native-track-player/issues/423#issuecomment-616746501
