### ISSUE TITLE
[iOS] Notification widget closes and changes buttons

### ISSUE THREAD

**Issue by dnish** [DoubleSymmetry/react-native-track-player#426]
Hey,
just recognized a new issue when using our app in production mode. If I click the next and previous button several times, the notification widget closes and reopens after a second again. After that, I can control the music playback normally, but sometimes it happens, that some buttons are not available anymore. So for example, this track is on position number 6 within the playlist, but the previous button is suddenly not available anymore:

![img_0795](https://user-images.githubusercontent.com/7636313/52122674-08cf6b00-2624-11e9-8509-6906d716c956.PNG)

If I now click on the next button and then on previous again, the previous button gets available again and I can switch back to all songs before position number 6.

![img_0796](https://user-images.githubusercontent.com/7636313/52122712-24d30c80-2624-11e9-9654-a21837ea1bba.PNG)

The bug doesn't happen all the time. The notification closes and reopens, if I click "very fast" on next while I'm loading remote mp3 files. Our event handler looks like this:

```
    TrackPlayer.addEventListener('remote-next', () => TrackPlayer.skipToNext());
```

Device: iPhone X
iOS: 12
RNTP version: 1.1.2

**Comment by dnish** [comment]
If I reset the player several times and load new tracks into the player, this happens:

![img_0800](https://user-images.githubusercontent.com/7636313/52123447-682e7a80-2626-11e9-894f-aee3380fd908.PNG)

After loading the same playlist again, all buttons are available again.

**Comment by curiousdustin** [comment]
https://github.com/react-native-kit/react-native-track-player/commit/d3400a475d8be146aa25696b5f014dd538e2dd86 May have fixed this.

**Comment by fernando-pascoal** [comment]
I solved this by updating the capabilities whenever the app goes to the background
