### ISSUE TITLE
[Android] Infinite Loading - AAC

### ISSUE THREAD

**Issue by xgustavoh** [DoubleSymmetry/react-native-track-player#429]
During a test I came across an infinite loading error.
The same did not report error through existing events. But when you look at the Android Log (**_adb logcat -d_**), the following error is encountered:

` 2324 16587 W SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4002`
` 2324 16587 W SoftAAC2: AAC decoder returned error 0x4002, substituting silence`

Note: When you "Stop" and "Play" again, it will pick up again.

**Comment by Guichaguri** [comment]
This looks like an ExoPlayer issue. Can you send the track that you're trying to play?

**Comment by xgustavoh** [comment]
Track 1: https://live.hunter.fm/live
Track 2: https://live.hunter.fm/mobile
