### ISSUE TITLE
Caching doesn't work on android

### ISSUE THREAD

**Issue by gazedash** [DoubleSymmetry/react-native-track-player#431]
I run example application, play audio file (mp3), wait until it is buffered to 100%, switch to next track and back and it loads again.

Also, it doesn't work if I buffer track completely, close app, run app again without Wi-FI or mobile access.

How to make caching work?

**Comment by ithustle** [comment]
+1

**Comment by songoten28** [comment]
@ithustle no it not working . Im using react-native-track-player#dev

**Comment by ashokkumar88** [comment]
@songoten28 Did you find any workaround?

**Comment by songoten28** [comment]
@ashokkumar88 no, we changed to using m3u8 to speed up user experience
