### ISSUE TITLE
[iOS]Headset control not working

### ISSUE THREAD

**Issue by ouabing** [DoubleSymmetry/react-native-track-player#454]
After upgrading to 1.1.2, headset control will not trigger remote-play, remote-pause events.

The wireless Airpods work but the old lined one don't.

My setup code:

```
export const configurePlayer = (store) =>
  TrackPlayer.registerPlaybackService(() => async () => {
    TrackPlayer.addEventListener('remote-play', async () => {
      TrackPlayer.play()
    })

    TrackPlayer.addEventListener('remote-seek', async (data) => {
      TrackPlayer.seekTo(data.position)
    })

    TrackPlayer.addEventListener('remote-pause', async () => {
      TrackPlayer.pause()
    })

    TrackPlayer.addEventListener('remote-stop', async () => {
      TrackPlayer.destroy()
    })
  })

export const setupPlayer = async () => {
    await TrackPlayer.setupPlayer()
    await TrackPlayer.updateOptions({
      capabilities: [
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_SEEK_TO,
        TrackPlayer.CAPABILITY_STOP,
      ],
      compactCapabilities: [
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_SEEK_TO,
        TrackPlayer.CAPABILITY_STOP,
      ],
      notificationCapabilities: [
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_SEEK_TO,
        TrackPlayer.CAPABILITY_STOP,
      ],
      stopWithApp: true,
    })
}
```

Configuration
--------------
- react-native: 0.57.8
- react-native-track-player: 1.1.2

System Info
------------
- System Version: 12.1.4
- Model: iPhone SE

**Comment by ouabing** [comment]
Still exist in 1.1.3.

**Comment by ouabing** [comment]
Seems like there are no other issues mention about this problem. Am I doing something wrong in my setup code? Or is there any clue I can debug this problem?

**Comment by appinteractive** [comment]
I Have the same issue and I dont know what that's happening. Had you any luck so far?

**Comment by ouabing** [comment]
@appinteractive not yet, I have a backup solution using react-native-video + react-native-music-control to stream audio, so I don't go into this problem further (I'm not familiar with Swift/Obj-C).

**Comment by appinteractive** [comment]
@ouabing seems like @anderslemke is working on the issue: https://github.com/react-native-kit/react-native-track-player/pull/531

**Comment by ouabing** [comment]
Wow thanks!
