### ISSUE TITLE
Url from udp server

### ISSUE THREAD

**Issue by murat-mehmet** [DoubleSymmetry/react-native-track-player#455]
This lib is great and working perfect with http protocol. However our audio will be streamed over multicast udp stream. And I could not play udp stream. I tried passing 'udp://host:post' to url but it just can't play it. Is there any workaround for it?

**Comment by Guichaguri** [comment]
UDP is not supported at the moment. I'll consider this issue as a feature request.

**Comment by murat-mehmet** [comment]
Well I managed to implement it in android, because exoplayer already supports udp streams. I will open a PR if I can also implement the ios part. Great lib, thanks.

**Comment by murat-mehmet** [comment]
Hey again, here is the progress about this feature. 

I could manage to make it work in both platforms after hours of work.
### Android
This was the easy part, ExoPlayer supports udp links out of the box.
In Track.java:
```
public MediaSource toMediaSource(Context ctx, LocalPlayback playback) {
...
 else if ("udp".equals(uri.getScheme().toLowerCase()) {
			ds = new DefaultUdpDataSourceFactory(null, 1350, UdpDataSource.DEFAULT_SOCKET_TIMEOUT_MILLIS);
		}
...
}
```
DefaultUdpDataSourceFactory is a very simple implementation of DataSource.Factory
```
public final class DefaultUdpDataSourceFactory implements DataSource.Factory {

    private final @Nullable
    TransferListener listener;
    private final int maxPacketSize;
    private final int socketTimeoutMillis;

    public DefaultUdpDataSourceFactory(@Nullable TransferListener listener, int maxPacketSize, int socketTimeoutMillis) {
        this.listener = listener;
        this.maxPacketSize = maxPacketSize;
        this.socketTimeoutMillis = socketTimeoutMillis;
    }

    public DefaultUdpDataSourceFactory(){
        this(null, UdpDataSource.DEFAULT_MAX_PACKET_SIZE, UdpDataSource.DEFAULT_SOCKET_TIMEOUT_MILLIS);
    }

    @Override
    public UdpDataSource createDataSource() {
        return new UdpDataSource(listener, maxPacketSize, socketTimeoutMillis);
    }
}
```
Or just:
```
new UdpDataSource.Factory() { @Override public DataSource createDataSource() { return new UdpDataSource(UdpDataSource.DEFAULT_MAX_PACKET_SIZE, UdpDataSource.DEFAULT_SOCKET_TIMEOUT_MILLIS); } }; 
```

And tadaa, android now can play udp links.

### Ios
This is where we pull out our hair. The great great native AVPlayer could not work with udp links no matter what we tried. So instead we imported VLCPlayer.
Steps to import the MobileVLCKit framework are described in these links:
https://github.com/xuyuanzhou/react-native-yz-vlcplayer
https://forum.videolan.org/viewtopic.php?t=137065

So finally, we had no time to write whole wrapper for VLCPlayer. Instead, we modified AVPlayerWrapper.swift:
```

class AVPlayerWrapper: AVPlayerWrapperProtocol {
...
    var vlcMediaPlayer: VLCMediaPlayer = VLCMediaPlayer()
    var udpUrl = String()
    ...

    func play() {
        let url = NSURL(string: udpUrl)
        let media = VLCMedia(url: url! as URL)
        
        vlcMediaPlayer.media = media
        vlcMediaPlayer.play()
    }
...
    func pause() {
        vlcMediaPlayer.pause()
    }
...
    func load(from url: URL, playWhenReady: Bool) {
        ...        
        udpUrl = String(url.description)
        ...
    }
}
```
We only need to work with udp streams so this was enough to save the day. I can't send this PR as it is not a clear implementation but maybe it saves someone's hours.
Thanks
