### ISSUE TITLE
Calling setupPlayer() from the background causes error in iOS

### ISSUE THREAD

**Issue by Jlexyc** [DoubleSymmetry/react-native-track-player#467]
setupPlayer() works fine from foreground, but when application in background (app receives silent push so handler is in there) i'm getting this error:

> The callback setupPlayer() exists in module TrackPlayerModule, but only one callback may be registered to a function in a native module.

Don't know what to do. I need to start play music from the background.

WORKAROUND:
I setup player from iOS native code on didreceivenotification. Not calling setupPlayer from JS code fixes the issue.

**Comment by fidelsam1992** [comment]
@Jlexyc Could you please explain more how the workaround is applied ?
