### ISSUE TITLE
Problem playing the next song on Background IOS

### ISSUE THREAD

**Issue by brunoscigliano** [DoubleSymmetry/react-native-track-player#468]
Hi, I'm having a problem when I try play the next track after the queue has ended.
What i have is a listener with playback-queue-ended that ask the server for another track, after that I reset the queue and add the new track.

The issue that i have is that sometimes when the track is too long 20~ minutes and the screen is off, the queue ends, the next track is retrieved but the player don't start. if i turn the screen on or open the app the player starts automatically.

**Comment by hmaamoun** [comment]
We are currently facing the same issue. Did you have any luck finding a fix for it?

**Comment by Sathyanarayan09** [comment]
@brenwell Can you please confirm if this fix helped player to play at background for long hours like 5+ hours?

**Comment by brenwell** [comment]
Sorry @Sathyanarayan09 I havn't been on that project for 6 months. No idea. Good luck
