### ISSUE TITLE
[iOS] Stop or Reset player when going to background?

### ISSUE THREAD

**Issue by curiousdustin** [DoubleSymmetry/react-native-track-player#478]
Most of the time I want my app to play music in the background.

But, there is a specific track that I want to only play while in the foreground on a certain screen.

I am stopping (or resetting) the player when `AppState` reports that the app is going to the background.

This works fine, except that the lock screen player controls persist. Not only are they there, but the have incorrect duration, and the play button doesn't work. (even though I don't actually want it to be there at all)

What steps do I need to take to make sure the iOS lock screen controls do NOT show up?

**Comment by curiousdustin** [comment]
`AppState.addEventListener('change', this.onAppStateChange);`

**Comment by Guichaguri** [comment]
I'm pretty sure you can `destroy()` it, but you'll have to implement logic to set it up again.

**Comment by curiousdustin** [comment]
I still need to do more testing to narrow this down further but, here is some more info. I intend to do some testing in the example app, but this info is from my app. 

The trouble I’m having is specifically when leaving the app via device sleep button. 

```
Playing audio 
Device home button
Stop audio (triggered by AppState change)
Device sleep button
Device sleep button (wake to lock screen)
```
This scenario works as expected. Audio is stopped. Lock screen shows no controls. 

```
Playing audio
Device sleep button 
Audio stops (triggered by AppState change)
Device sleep button (wake to lock screen)
```
This scenario behaves differently. The audio still stops as intended. However, now the lock screen shows the controls when it should not because nothing is playing. 

I did try `destroy()`. Interestingly, it didn’t even stop the audio. I tried stop AND destroy, and it behaves just like stop. 

I didn’t dig as deep as I would like to yet. But, I couldn’t easily find a place in the native code that toggles the lock screen controls on/off. Perhaps this is mostly controlling automatically by iOS, and we just need to do something specific to “trick” it into hiding the controls.

**Comment by Guichaguri** [comment]
Does #485 fixed it for you?

**Comment by curiousdustin** [comment]
Yes, this is definitely an improvement.

However, this only fixes the case of use `reset()`. This works for my specific case, but I feel it could still be improved.

If I do `stop()` when the app goes to the background via the device sleep button, The audio stops, but the info center lock screen still shows the info, but the buttons don't work at all.

Perhaps a similar fix should be applied to the `stop()` method? Along with `beginReceivingRemoteControlEvents` whenever a track is started?

**Comment by roberto-buratti** [comment]
I noted that (on iOS) the player works well in background... until you call reset().
After that it doesn't work anymore.
May this be of any help?
