### ISSUE TITLE
RNTrackPlayer not working on Android

### ISSUE THREAD

**Issue by zedissime** [DoubleSymmetry/react-native-track-player#482]
Hello,
I'm building an app with RNTP, everything is fine on iOS, but on Android it doesn't seems to work at all.
On application start I see in AndroidStudio a logging loop of this :
```D/RNTrackPlayer: onStateChange
D/RNTrackPlayer: onPositionDiscontinuity: 1
    onTimelineChanged: 1
D/RNTrackPlayer: onTrackUpdate
    onTimelineChanged: 0
    onStateChange
D/RNTrackPlayer: onEnd
```
When a want to add a track in the playlist nothing happens.
I can't see what I'm doing wrong as everything is ok on iOS.
Can someone give me a hand here?

**Comment by ithustle** [comment]
@zedissime , can you share your code?

**Comment by zedissime** [comment]
> @zedissime , can you share your code?

First of all thank your for your attention,
I've got a component containing the player, which will add event listeners when the component did mount.

```componentDidMount() {
    TrackPlayer.setupPlayer({}).then(() => {
      TrackPlayer.getState().then(this.onStateChange); //Initialize
      this.getCurrentTrack(); //Initialize
      TrackPlayer.updateOptions({
        capabilities:        [
          TrackPlayer.CAPABILITY_PLAY,
          TrackPlayer.CAPABILITY_PAUSE,
          TrackPlayer.CAPABILITY_STOP,
        ],
        compactCapabilities: [
          TrackPlayer.CAPABILITY_PLAY,
          TrackPlayer.CAPABILITY_PAUSE,
          TrackPlayer.CAPABILITY_STOP,
        ],
      });
      this.listeners.state = TrackPlayer.addEventListener('playback-state', this.onStateChange);
      this.listeners.trackChange = TrackPlayer.addEventListener('playback-track-changed', this.onTrackChanged);
      this.listeners.queueEnded = TrackPlayer.addEventListener('playback-queue-ended', this.onQueueEnded);
    });
  }```

In my main index.js, I register the playback service as described in the docs 

```AppRegistry.registerComponent('<app-name>', () => App);
TrackPlayer.registerPlaybackService(() => TrackPlayerService);```

And my service looks like this :
```
import TrackPlayer from 'react-native-track-player';

const TrackPlayerService = async () => {
  TrackPlayer.addEventListener('remote-play', () => {
    console.log('remote-play');
    TrackPlayer.play();
  });

  TrackPlayer.addEventListener('remote-pause', () => {
    console.log('remote-pause');
    TrackPlayer.pause();
  });

  TrackPlayer.addEventListener('remote-next', () => {
    console.log('remote-next');
    TrackPlayer.skipToNext();
  });

  TrackPlayer.addEventListener('remote-previous', () => {
    console.log('remote-previous');
    TrackPlayer.skipToPrevious();
  });

  TrackPlayer.addEventListener('remote-stop', () => {
    console.log('remote-stop');
    TrackPlayer.destroy();
  });

};

export default TrackPlayerService;
```

I don't know if it's what you was looking for.

**Comment by ithustle** [comment]
> I don't know if it's what you was looking for.

No. Sorry I should be more specific .. Can you share your code for play a track?
Your configuration code seems to be well configured.

**Comment by zedissime** [comment]
It's really a simple code, in fact the logs I did mention on my first post are appearing on application start. So I think it's not related to the code for adding tracks.

```
addTracks(parts, date) {
    console.log('___________________ADDTRACKS___________________');
    const tracks = parts.map((part) => {
      return {
        id:      part.id,
        artwork: part.poster_url,
        url:     part.audio_file_url,
        title:   part.display_name,
        artist:  date,
      };
    });
    TrackPlayer.add(tracks).then(() => {
      TrackPlayer.play();
    });
  }
```

**Comment by ithustle** [comment]
Did you trace the `playback-state` events ?

**Comment by zedissime** [comment]
Yes on application start, it's constantly switching from 1 to 0 [see this screeshot](https://take.ms/LQwSz)

**Comment by ithustle** [comment]
I had the same. 

First of all, like I said https://github.com/react-native-kit/react-native-track-player/issues/482#issuecomment-471310671, I had to change this line https://github.com/react-native-kit/react-native-track-player/blob/108a6ed0094770aaac878cd2b7fdfb3a1a0bc2e4/android/src/main/java/com/guichaguri/trackplayer/service/player/ExoPlayback.java#L180 to `return PlaybackStateCompat.STATE_BUFFERING;`

And then, I did it:

```
const STATE_ANDROID = ["none", "stopped", "paused", "playing", "", "", "loading"]

...

if (status === TrackPlayer.STATE_PAUSED) {
            this.setState({ status_buffer: Platform.OS === "ios" ? TrackPlayer.STATE_PAUSED : STATE_ANDROID[data.state] });

            const currentTrack = await TrackPlayer.getCurrentTrack();
            const position = await TrackPlayer.getPosition();
            
            if (currentTrack !== undefined && position === 0) {
                if ( Platform.OS === "android" ) {
                    this._play();
                    this.setState({ status_buffer: STATE_ANDROID[3] });
                }
            }
}

```

Well, I know is not the best approach but this is the way I found to play songs on android on app that I'm building...

I hope that help

**Comment by zedissime** [comment]
Thanks a lot, I'll try this asap.

**Comment by zedissime** [comment]
So a few days later,
As the example provided in this repo was correctly working, I did not wanted to changes the package code as @ithustle suggested.
In fact, I did setup the TrackPlayer in his component did mount `TrackPlayer.setupPlayer()`. If I remove this everything is fine (both Android & iOS).

**Comment by ithustle** [comment]
Humm. I see. Maybe as soon as possible there will be a new version release with this change because I made a PR with it.

Thats curious ... I tested right now (Android) removing `TrackPlayer.setupPlayer()` and works fine. Inclusive on app start `playback-queue-ended` event isn't fired.

CC: @Guichaguri

**Comment by zedissime** [comment]
After some tests, I think that `TrackPlayer.reset()` also makes the loop log described on my first post.
I was using it (probably wrongly) when the user kills the player.
So in order I did : 
`
TrackPlayer.stop(); // to eventually stop the current playing track
TrackPlayer.reset(): // to reset the player
`
But when I do that (still for Android), the `reset()` method makes RNTrackPlayer logging and it not longer respond to any method.

**Comment by CRivlaldo** [comment]
In my case, the reset() method caused the same issue too.
Removing of a setup() method call didn't help.
