### ISSUE TITLE
[iOS] Player stay in "loading" state if track can not be found

### ISSUE THREAD

**Issue by jensneuber** [DoubleSymmetry/react-native-track-player#488]
OS version: iOS 12.1
RN version: 0.57.0
track-player: 1.1.3

----

The player is working as intended as long as all item in a playlist are loadable. Once a track with a non reachable URL (404) should start playing the player stays in "loading" state. No error is thrown and the player state does not change.

I tried to solve it by adding this piece of code in the AVPlayerWrapper.swift:162
```
if !currentAsset.isPlayable {
  let error = APError.LoadError.invalidSourceUrl("Item is not playable")
  self.delegate?.AVWrapper(failedWithError: error)
}
```

Since I am not a Swift developer I am asking you how you would solve this issue?

**Comment by jensneuber** [comment]
@Guichaguri Would you like me to create a PR with the suggested changes? Or is there another way to support you?

**Comment by curiousdustin** [comment]
@jensneuber does this problem still exist for you in `v1.2.3`?

**Comment by maxckelly** [comment]
@curiousdustin I'm still getting this in `v1.2.3`
