### ISSUE TITLE
changing order of tracks

### ISSUE THREAD

**Issue by puckey** [DoubleSymmetry/react-native-track-player#494]
I have been trying to figure out if there a way to change the position of a track in the queue.. I tried resetting the TrackPlayer and rebuilding the queue, but that stops the current track from playing.

And around about way to do this would be to remove all the tracks of the queue one by one, without the current playing track and then add them back, taking into account the `beforeId` parameter in `TrackPlayer.add`.

But some dedicated functionality for this would be great.. something like `TrackPlayer.moveBefore(track, beforeId)` / `TrackPlayer.moveAfter(track, afterId)`?

**Comment by CapitanRedBeard** [comment]
I also agree this would be nice. The current way to do it by removing everything aside from the current track and reordering them in the correct order feels error prone

**Comment by bradleyflood** [comment]
Agreed, I have the same need. Will add to Project for review. Thanks :)
