### ISSUE TITLE
[IOS] Doesn't resume after call ended

### ISSUE THREAD

**Issue by SteponasIvasovas** [DoubleSymmetry/react-native-track-player#497]
Hello, i have problem where when i make a call the audio app is playing, is paused, but when the call is ended or canceled the audio is not resumed, any ideas what i am doing wrong? i tried console logging playback-state event, when making calls, but it only fires when i make the call and state changes to paused, but nothing happens when call is ended.

Android is working fine with remote-duck event implemented

**Comment by minhtc** [comment]
Seem like responding to audio session interruptions wasn't implemented yet.

**Comment by geek-ibrar** [comment]
Facing same issue

**Comment by jeffmon** [comment]
Any updates on this?

**Comment by fidelsam1992** [comment]
Any updates on this issue ?

**Comment by fidelsam1992** [comment]
I found a temporary workaround to solve this : 
RNTrackPlayer.swift

Change this
```
@objc(stop:rejecter:)
    public func stop(resolve: RCTPromiseResolveBlock, reject: RCTPromiseRejectBlock) {
        print("Stopping playback")
        player.stop()
        resolve(NSNull())
    }
```

to this
```
@objc(stop:rejecter:)
    public func stop(resolve: RCTPromiseResolveBlock, reject: RCTPromiseRejectBlock) {
        print("Stopping playback")
        player.pause()
        resolve(NSNull())
    }
```

**Comment by maulikvora** [comment]
Any update here? facing same issue

**Comment by moonstruck** [comment]
> I found a temporary workaround to solve this :
> RNTrackPlayer.swift
> 
> Change this
> 
> ```
> @objc(stop:rejecter:)
>     public func stop(resolve: RCTPromiseResolveBlock, reject: RCTPromiseRejectBlock) {
>         print("Stopping playback")
>         player.stop()
>         resolve(NSNull())
>     }
> ```
> 
> to this
> 
> ```
> @objc(stop:rejecter:)
>     public func stop(resolve: RCTPromiseResolveBlock, reject: RCTPromiseRejectBlock) {
>         print("Stopping playback")
>         player.pause()
>         resolve(NSNull())
>     }
> ```

@maulikvora Have you tried this?

**Comment by maulikvora** [comment]
@moonstruck Yes I tried this, It didn't work, we are atually playing HLS url and it seems many of the player functionality is not working with HLS.

**Comment by maulikvora** [comment]
@dcvz is this closed because of fix applied OR closed as a part of a cleaning process?

**Comment by chrise86** [comment]
@maulikvora given the amount of closures yesterday, I'd assume the latter.
