### ISSUE TITLE
Add wrap option to skipToNext / skipToPrevious

### ISSUE THREAD

**Issue by puckey** [DoubleSymmetry/react-native-track-player#511]
In my app I want the next and previous buttons to wrap around. I.e. when you are on the last track in the queue, I want the notification screen next button to play the first track.

`TrackPlayer.skipToNext({ wrap: true })`

Another option could be `TrackPlayer.loop = 1` which would loop the queue also while playing.

**Comment by puckey** [comment]
Right now I am wrapping by doing the following:

```javascript
  TrackPlayer.addEventListener('remote-next', async () => {
    const [queue, currentId] = await Promise.all([
      TrackPlayer.getQueue(),
      TrackPlayer.getCurrentTrack()
    ]);
    const index = queue.findIndex(({ id }) => id === currentId);
    TrackPlayer.skip((index + 1) % queue.length);
  });

  TrackPlayer.addEventListener('remote-previous', async () => {
    const [queue, currentId] = await Promise.all([
      TrackPlayer.getQueue(),
      TrackPlayer.getCurrentTrack()
    ]);
    const index = queue.findIndex(({ id }) => id === currentId);
    TrackPlayer.skip((index - 1 + queue.length) % queue.length);
  });
```

**Comment by curiousdustin** [comment]
@Guichaguri if I understand correctly https://github.com/react-native-kit/react-native-track-player/pull/688 would satisfy this feature request?

Should we link this issue to the PR?
