### ISSUE TITLE
reset() and playback-queue-ended [ANDROID]

### ISSUE THREAD

**Issue by vbspace** [DoubleSymmetry/react-native-track-player#519]
The documentation says that playback-queue-ended fires when the queue ended, why does it fires when we call reset() ?

**Comment by ntk860** [comment]
I tried reset() with playback-track-changed, but it also triggers when reset() gets called.

**Comment by curiousdustin** [comment]
@Guichaguri I agree it seems odd to have these events triggered as a result of `reset()`. We should either resolve this on Android, or define why they happen and make sure iOS behaves the same.
