### ISSUE TITLE
Background mode not working

### ISSUE THREAD

**Issue by hrag** [DoubleSymmetry/react-native-track-player#525]
I’ve been having this issue since I started using this library. In the simulator, when I leave the app, the audio also stops playing. Sometimes it skips like a CD. When I get back to the app in both cases, it resumes immediately.

I’ve enabled the “Audio, AirPlay, and Picture in Picture” In background modes in Xcode, but no dice. Is there another step I’m missing?

The audio I’m playing is locally stored already (using rn-fetch-blob), and otherwise playback works as expected.

I’ve combed through the docs and issues but can’t seem to find anything. Any ideas?

**Comment by dcvz** [comment]
Do you also see this issue when using a device?

**Comment by budet-b** [comment]
> Do you also see this issue when using a device?

For me too, on my iPhone it doesn't work in background mode. I enabled background modes in Xcode as well. (using Swift 4.2, Xcode 10.1, iOS 12.2 and the last release of `react-native-track-player`)

**Comment by hrag** [comment]
I eventually made the discovery that the audio doesn't **stop** when I leave the app, it's just muting.

**Comment by hrag** [comment]
@dcvz I haven't gotten that far in my development quite yet heh, but I'll try to see what happens on the device tonight.

**Comment by hrag** [comment]
@dcvz I couldn't wait, had to try it now. It plays in the background as expected on actual device, so we're good there 👍 

I think it would be nice to get this patched up for the simulator so we can test the lock screen controls etc.

**Comment by dcvz** [comment]
ok to summarise.. @hrag with the latest version, it works for you on a device. Just not on the simulator?

**Comment by hrag** [comment]
@dcvz Yep, that is correct. In the simulator it just seems to mute. Happy to share logs or whatever if you want to dig into this.

**Comment by curiousdustin** [comment]
@hrag what version of `react-native-track-player`, and what version of the simulator are you using?

**Comment by jspizziri** [comment]
@curiousdustin I'm having the same issue:

I'm using `react-native-track-player#dev`, the specific commit is `8ae5808340c435b450c71dbe4da5e75101c7b720`.

Simulator details:

```
Version 11.6 (921.9.1)
SimulatorKit 581.9.1
CoreSimulator 704.12.2

iOS 13.6 on iPhone 11
```

**Comment by ztowne13** [comment]
I had all of that stuff added too and it wasn't working. All I had forgotten was
`TrackPlayer.setupPlayer();`
so make sure the track player is initialized (even if the audio is already working!) because my audio worked, just not in the background, even though I forgot to initialize the track player.
