### ISSUE TITLE
[Android] - Buffering when playing from file system

### ISSUE THREAD

**Issue by ataravati** [DoubleSymmetry/react-native-track-player#527]
When playing from the file system on Android, it still buffers. The path is prefixed with `file:///`. 

It's interesting, because on iOS it's exactly the opposite. It never buffers. Even when playing from the network, it downloads the whole file and then plays it.

**Comment by Guichaguri** [comment]
Can you upload the file that you're playing?

**Comment by ataravati** [comment]
Here's the file: 

https://podcast-a.akamaihd.net/mp3/podcasts/current-SWPiO5qy-20190404.mp3

I download it using `rn-fetch-blob` and then play it. The local file path will be something like this:

`file:///data/user/0/com.myReactNativeApp/current-SWPiO5qy-20190404.mp3`

**Comment by ataravati** [comment]
@Guichaguri, did you have a chance to have a look at this issue? Thanks!

**Comment by MasterTeus** [comment]
Some solution to this problem, as I am trying to make the player work by taking files from the android file system

**Comment by breadface** [comment]
@ataravati have you found a solution for this?
