### ISSUE TITLE
Android issue on Windows

### ISSUE THREAD

**Issue by tungmt** [DoubleSymmetry/react-native-track-player#529]
My project build success in Mac machine, but in Windows with Android Studio it got issue like this

OS: Windows 10
React-Native: 0.59.3
Android Studio: 3.3.2

**error: cannot find symbol method metafactory(Lookup,String,MethodType,MethodType,MethodHandle,MethodType)**

![image](https://user-images.githubusercontent.com/7497751/55850075-156cc400-5b7d-11e9-8798-5e09c980875d.png)

**Comment by Guichaguri** [comment]
Does [enabling Java 8 support](https://react-native-kit.github.io/react-native-track-player/install/#android-circular-referencecomandroidtoolsr8apilevelexception-default-interface-methods-are-only-supported-starting-with-android-n---min-api-24) in Gradle fix the problem?

**Comment by tungmt** [comment]
> Does [enabling Java 8 support](https://react-native-kit.github.io/react-native-track-player/install/#android-circular-referencecomandroidtoolsr8apilevelexception-default-interface-methods-are-only-supported-starting-with-android-n---min-api-24) in Gradle fix the problem?

It doesnt work
