### ISSUE TITLE
TrackPlayer.stop different behavior ios vs android

### ISSUE THREAD

**Issue by cylwin** [DoubleSymmetry/react-native-track-player#555]
Hello,

```js
_initPlayer = async (filePath) => {
    TrackPlayer.reset();
    const track = {
      id: this.state.audioItemIndex,
      url: filePath,
      title: this.state.audioItem.title,
      artist: this.state.audioItem.author,
      genre: this.state.audioItem.type,      
      artwork: this.state.audioItem.img,
    };
    TrackPlayer.add([track]).then(function() {
      console.log("TrackPlayer.add([track]) done")
    });
  }
  _stop = async () => {
    console.log(await TrackPlayer.getQueue());
    await TrackPlayer.stop();
    console.log(await TrackPlayer.getQueue());
  }
```

When I call _Init, then _stop.
The result on android (work well): 
![image](https://user-images.githubusercontent.com/6231358/56474520-49988c80-647b-11e9-9b62-b8456f346c63.png)
The result on Ios :
![image](https://user-images.githubusercontent.com/6231358/56474543-a98f3300-647b-11e9-8aca-5df0a493ad96.png)
The behavior on IOS is the same as the reset() function and shouldn't.

Also I discovered that there is the "STATE : ready" on IOS just after my init functon is called, and there is no mention about this in the documentation.

**Comment by tungmt** [comment]
I have same issue too, it take few seconds to add list on ios after reset the playlist

**Comment by mynameisguy** [comment]
have the same issue.
