### ISSUE TITLE
TrackPlayer.destroy() does not work on iOS

### ISSUE THREAD

**Issue by LaurenceRolandJames** [DoubleSymmetry/react-native-track-player#566]
# Configuration

Run `react-native info` in your project and share the content.

```
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 116.47 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.15.1 - ~/.nvm/versions/node/v8.15.1/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 28.0.2, 28.0.3
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.4 => 0.59.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

What `react-native-track-player` version are you using?

```react-native-track-player@1.1.3```

# Issue

(My audio player only ever plays a single track.)

TrackPlayer.destroy() has no effect on iOS.

I can work around this in the app by calling TrackPlayer.reset() in componentWillUnmount to stop audio playing when a user navigates away from the audio player screen, but when the screen is locked and the track finishes, and the user is viewing the iOS media player, the media player should be destroyed in the same way that it gets destroyed on android devices.

**Comment by dengue8830** [comment]
i'm trying to fix this, but i know almost anything about ios. Also i think this `do nothing` could be the problem

https://github.com/react-native-kit/react-native-track-player/blob/dev/ios/RNTrackPlayer/RNTrackPlayer.swift#L153

and this could be the fix?

https://stackoverflow.com/a/32994222/3744400

i could try a pull request if i'm in the right way

**Comment by dengue8830** [comment]
please @Guichaguri  give me some clue on this

**Comment by curiousdustin** [comment]
I’m not sure I understand specifically what the issue is. 

Is it the same as, or related to, this: https://github.com/react-native-kit/react-native-track-player/issues/825

**Comment by LaurenceRolandJames** [comment]
@curiousdustin Yes, its the same issue as [#825](https://github.com/react-native-kit/react-native-track-player/issues/825)

**Comment by waheedakhtar694** [comment]
I was trying to use the destroy method for removing controls from the notification screen but this method only logs a message, here is the destroy function in swift.

I was only resetting the player but controls were still appearing in that case so resting the player and after that updating the 
options work for me

```
@objc(destroy)
    public func destroy() {
        print("Destroying player")     // swift implementation for destroy 
    }
 ```
    await RNTrackPlayer.reset()
    await RNTrackPlayer.updateOptions({ stopWithApp: true,
      capabilities: [
        Capability.Play,
        Capability.Stop,
        Capability.SkipToNext,
        Capability.SkipToPrevious,
        Capability.Pause
      ]})
