### ISSUE TITLE
Usage of setRate on Android causes playback to stop.

### ISSUE THREAD

**Issue by zzorba** [DoubleSymmetry/react-native-track-player#569]
# Configuration

Run `react-native info` in your project and share the content.

  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
      Memory: 866.96 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 23.0.1, 25.0.1, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        API Levels: 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: 16.8.8 => 16.8.8 
      @types/react-native: 0.57.41 => 0.57.41 
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.6 => 0.58.6 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-instagram-embed: 0.0.6
      react-native-log-ios: 1.0.1

What `react-native-track-player` version are you using?
1.1.3

# Issue
On iOS I am seeing no issues with the usage of `setRate`.  Provided that setupPlayer has been previously called, it seems like it can be executed either while a track is playing or before a track is playing.  

On android however, the feature seems to (silently) cause playback to stop.  If setRate is called before the track is played, it does not seem to change the behavior.  If it is called while the track is playing, playback stops and the progress resets to the start of the track.

As far as I can tell, no native exceptions or 'error' events are produced by this, the track just stops playing.

# Code
```
TrackPlayer.setupPlayer()
      .then(() => {
        return TrackPlayer.updateOptions({
          jumpInterval: 30,
          capabilities: [
            CAPABILITY_PLAY,
            CAPABILITY_PAUSE,
            CAPABILITY_JUMP_FORWARD,
            CAPABILITY_JUMP_BACKWARD,
            CAPABILITY_SEEK_TO,
          ],
          notificationCapabilities: [
            CAPABILITY_PLAY,
            CAPABILITY_PAUSE,
            CAPABILITY_JUMP_FORWARD,
            CAPABILITY_JUMP_BACKWARD,
            CAPABILITY_SEEK_TO,
          ],
        });
      })
      .then(() => {
        const track: Track = {
          id: article.id,
          url: audioUrl,
          title: article.title,
          artist: (article.authors || []).join(', '),
          date: article.publishDate
            ? DatetimeService.toISODateString(
                new Date(article.publishDate * 1000)
              )
            : undefined,
          artwork: Audio.imageUrl(article),
          pitchAlgorithm: PITCH_ALGORITHM_VOICE,
        };
        return TrackPlayer.add(track).then(() => {
          return TrackPlayer.getDuration().then(duration => {
            return { duration };
          });
        });
      }).then(() => TrackPlayer.play())
      .then(() => TrackPlayer.setRate(1.5));
```

**Comment by Guichaguri** [comment]
Does seeking works for the track you're testing?

**Comment by zzorba** [comment]
Interesting, seeking is working just fine on these tracks, but we have had some problems with these MP3s before (they are generated by amazon polly, and we had to add a transcode step to make their duration work correctly).

As far as you know, there shouldn't be any issue calling setRate while the track is playing right?

**Comment by zzorba** [comment]
Here's a link to a sample MP3 that is exhibiting the issue on Android: https://audio.scroll.com/5cbe0874f100740008e3bd94.mp3
