### ISSUE TITLE
Support for react-native-web?

### ISSUE THREAD

**Issue by shrirambalaji** [DoubleSymmetry/react-native-track-player#572]
Hey,

Found this library to be really helpful, are there any plans of porting this to react-native-web now?

**Comment by Guichaguri** [comment]
I have worked on a port for react-native-web a long time ago, but I've never published. I might update it and push it.

**Comment by Shriram-Balaji** [comment]
@Guichaguri That's great! Waiting for this :smile:

**Comment by Shriram-Balaji** [comment]
Hey, @Guichaguri Did you get a chance to publish the react-native-web port?

**Comment by Guichaguri** [comment]
Before publishing, I think we should discuss about implementation details:

* Although it shares the same API, it is another module, separated from `react-native-track-player`, which means it would work pretty similar to `react-router-dom` and `react-router-native`.
* I've built three media button extensions: (which can be selected through imports, e.g. `import TrackPlayer from 'react-track-player/electron';`)
    * DOM (default, uses window keydown event for media shortcuts)
    * Electron (global media shortcuts, thumbar media buttons on Windows)
    * NW.js (global media shortcuts)
* Metadata is done through [MediaSession](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession), which only seem to be supported by Chrome and Firefox on Android at the moment.
* The player is built on top of [HTML5 Audio](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement). It doesn't support adaptive streaming (DASH, HLS and SmoothStreaming), although it could through libraries such as [shaka-player](https://github.com/google/shaka-player).
* I've created an implementation for [Google Cast](https://developers.google.com/cast/docs/chrome_sender/integrate) (that would only work on Chrome), but I've never tested it. There's also the support for [AirPlay](https://developer.apple.com/documentation/webkitjs/adding_an_airplay_button_to_your_safari_media_controls) (that would only work on Safari).
* The code is unfinished. There is a lot of stuff that needs to be implemented, I'm also not really sure about browser compatibility.

Let me know what do you think

**Comment by Shriram-Balaji** [comment]
Most cross platform libraries, that support react-native-web have a necessity to add a separate module with the same API, so I believe that's what suits us as well.

It seems to me that HTML5 Audio is the way to go for web, because of obvious reasons. Although it doesn't support adaptive streaming immediately, I see it as a feature that's implemented after we have identified that rn-track-player works well enough on HTML5 Audio in Web.

I have limited understanding of the MediaSession API, but it looks like a way to let the browser know of what audio it is playing, along with some extra info. Afaik, this also doesnt feel like a huge priority for RN-Web in the start.

Cast and Airplay do seem like important features, although not the top most in the priority list imho.

If there are any parts that may need some contributions, please do let me know, and I will try to see if I can also contribute in some way, especially in adding support for web.  I'm building an [open-source, cross-platform podcast app for developers](https://github.com/cast-bucket/cast-bucket), and I'm keen on using react-native-track-player for all the platforms :smile:

**Comment by alburdette619** [comment]
Hey, my team is heavily using this library and we're going to be adding support for RN Web to our project soon.  Has this gone anywhere?  Do y'all need some help?

**Comment by shamoons** [comment]
> Before publishing, I think we should discuss about implementation details:
> 
> * Although it shares the same API, it is another module, separated from `react-native-track-player`, which means it would work pretty similar to `react-router-dom` and `react-router-native`.
> * I've built three media button extensions: (which can be selected through imports, e.g. `import TrackPlayer from 'react-track-player/electron';`)
>   
>   * DOM (default, uses window keydown event for media shortcuts)
>   * Electron (global media shortcuts, thumbar media buttons on Windows)
>   * NW.js (global media shortcuts)
> * Metadata is done through [MediaSession](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession), which only seem to be supported by Chrome and Firefox on Android at the moment.
> * The player is built on top of [HTML5 Audio](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement). It doesn't support adaptive streaming (DASH, HLS and SmoothStreaming), although it could through libraries such as [shaka-player](https://github.com/google/shaka-player).
> * I've created an implementation for [Google Cast](https://developers.google.com/cast/docs/chrome_sender/integrate) (that would only work on Chrome), but I've never tested it. There's also the support for [AirPlay](https://developer.apple.com/documentation/webkitjs/adding_an_airplay_button_to_your_safari_media_controls) (that would only work on Safari).
> * The code is unfinished. There is a lot of stuff that needs to be implemented, I'm also not really sure about browser compatibility.
> 
> Let me know what do you think

Can we publish as a beta or another package for now? Then the community can aid in testing and development.

**Comment by santiripper** [comment]
@Guichaguri it would be nice if you can push your work so we can contribute and move forward :)

**Comment by santiripper** [comment]
Hola @Guichaguri sorry to be insistent on this, i've start to work on a web version of the project, but it would be nice if you can share what you've done before and the discus what the next steps are as you asked :) please let us know if you have some time for this, thank you :)

**Comment by rdhox** [comment]
@Guichaguri A little update to this post! Also interested to see a possibility of integration with RN-web, especially that the V2 of react-native-track-player is on!

**Comment by andordavoti** [comment]
@jspizziri Thanks for the quick reply! Will definitely take a look at it, would be awesome for simplifying migration of my native app to web:)
