### ISSUE TITLE
Rework example app

### ISSUE THREAD

**Issue by puckey** [DoubleSymmetry/react-native-track-player#599]
While working some more on the docs, I took a look at the example app and was thinking about some improvements:

- Make it work with the current dev version of the library
- Replace `MobX` with `useEffect` & `useTrackPlayerEvents`
- Use `useTrackPlayerProgress` for progress bar
- Show the playlist screen straight away
- Remove the react navigation dependency?
- Include audio ducking
- Fix bugs where next and previous buttons throw when there is no next / previous track
- Extract controls to `Controls` component
- Put some touch padding around the buttons

I have had an initial rough stab at this, for which I will make a WIP pull request. Happy for any comments!

**Comment by nisheetsun** [comment]
Also for me, Player does not work after I stop it from the push notification and it throws the following warning. 

> Possible Unhandled Promise Rejection(id: 1): Error: You attempted to set the key '()' with value "{id:"1111", "url":"https://drive.google.com/uc?...", title:"Longing", "artist":"David", artwork:"https://..."}" on an object that is meant to be immutable and has been frozen

 I also tried calling setupPlayer after destroy has been called, but that did not help either.
Please help. Thanks.

**Comment by puckey** [comment]
@Guichaguri & @dcvz: what do you think of these steps? Does it make sense for me to work on this?

https://github.com/puckey/react-native-track-player/tree/rework-example

I went a step further and started implementing various useEffect functions, which could perhaps end up in the core:

- `useQueue`: when you pass it a value, it sets the queue: `useQueue(tracks)`, or pass it nothing to and just get the current queue: `const queue = useQueue()`..
- `const track = useCurrentTrack()` - handy for previous button functionality
- `const nextTrack = useNextTrack()` / `const previousTrack = usePreviousTrack()` - handy for showing the next/previous buttons.. but also for example to show coming up tracks
- `const playbackState = usePlaybackState()`
- `const isPlaying = usePlaybackStateIs(TrackPlayer.STATE_PLAYING);`

(In the code above tracks are always the full javascript track objects instead of track ids..)

Hooks code: https://github.com/puckey/react-native-track-player/blob/rework-example/example/react/hooks.js

Usage examples:
https://github.com/puckey/react-native-track-player/blob/rework-example/example/react/components/Player.js
https://github.com/puckey/react-native-track-player/blob/rework-example/example/react/components/Controls.js

Would it make sense to work these out to a more complete set? Perhaps in such a way that users don't even need to worry about TrackPlayer.setup()?

Others we could add:
- `useOptions({ ... })`
- `const nextTracks = useComingUp()`
- `useVolume`
- `useRate`

**Comment by dcvz** [comment]
I'd be careful with creating too many hooks and doing overkill.

I think we should keep it to items that update on their own.. i.e. state, current track..

But i'm not sure we should use them to update items.. i.e. `useOptions`, `useVolume` and `useRate`.

For `useQueue` that might be useful, if it only returns the upcoming queue and not allow you to set/append items.

**Comment by dcvz** [comment]
also `usePlaybackState` was already added in the latest `master` ;)

**Comment by puckey** [comment]
Okay cool – yeah it is a little unclear what the conventions are for libraries and `useEffect`.

In general the idea of reworking the example app was to allow for easier bug reports.. If we were to move it to a separate repo and add `react-native-track-player` to its `package.json` as the git repo, users could easily fork the repo and rework it to show any bugs they are experiencing.

**Comment by dcvz** [comment]
I think it's a great idea to extend the example app to showcase more functionality while making it easier to make bug reports. I'm not sure it's required to make it it's own repo.. it already uses the local package from root, so it should be as simple.

**Comment by Guichaguri** [comment]
@puckey I agree with that. Should we replace [react-native-track-player-demo](https://github.com/react-native-kit/react-native-track-player-demo) with the new example app?
