### ISSUE TITLE
Feature request: More control over audio focus

### ISSUE THREAD

**Issue by zetorama** [DoubleSymmetry/react-native-track-player#604]
_First of all: What an awesome library, very convenient API, huge thanks to all contributors! 👏_

Currently, when TrackPlayer deals with platform's audio focus, it behaves just like a music player would do. For example, when requesting focus on Android it specifies `USAGE_MEDIA/CONTENT_TYPE_MUSIC`. Though, there are much more options, especially if you wish to "share focus" with other apps. _(As explained in "Step 1. Make the focus request" of [Understanding Audio Focus 3/3](https://medium.com/androiddevelopers/audio-focus-3-cdc09da9c122#bf3f) article.)_

So, to make this great library even more adjustable for different scenarios, there might be added more controls to audio focus behaviour, like: 
- `TrackPlayer.setupPlayer()` should accept options to configure request focus properties. 
- Either explicit `TrackPlayer.abandonAudioFocus()` or something similar to `TrackPlayer.pause(shouldAbandonAudioFocus?: boolean)` might be provided. Both variants would also allow to just pause playback, when getting a `remote-duck` event with `ducking: true`.

For example, I'm currently playing with some kinda voice-oriented app, and here's basically what I need: [forked react-native-track-player/commit/bac027d](https://github.com/zetorama/react-native-track-player/commit/bac027d5a4a03c5326246b52251e72650f731418). Of course, I wish I could setup these via API instead of hacking them permanently.

I'm pretty new to mobile development and just researched this about Android only, but I assume, that iOS might have similar functionality. 

What do you think?

**Comment by Guichaguri** [comment]
A transient audio focus means it will be playing a short audio, is that really what you app needs?

**Comment by zetorama** [comment]
Well, it might, yes. My app just plays short voice messages, and if there's some music playing in the background — i don't want to pause it, just to "duck" it, until the message is over.

**Comment by Guichaguri** [comment]
I think `react-native-sound` is a better option for you.

`react-native-track-player` is designed for music and podcast apps that need features such as external media buttons, background playback and long-running streaming. Setting all of that up takes a lot of resources.
`react-native-sound` is a simple audio player, it doesn't have any of those features, but it also uses up less resources.

I still want to explore the idea of supporting other types of audio though.

**Comment by zetorama** [comment]
Thanks! I'll give another look at `react-native-sound`.

As another use case I can think of, maybe you make a podcast oriented player app. And as an option to choose own background music, you use this transient audio focus, so user can play music in her/his main music player (eg, spotify) and then start a podcast in your app. It might be just a user-controlled setting to specify what kind of audio focus to use. There are [some music player apps, that have such option in their settings.](https://android.stackexchange.com/q/125250).

**Comment by dcvz** [comment]
Transient audio is not something we wish to pursue at the moment, will close this for now
