### ISSUE TITLE
[ios] playing streams does not work without undocumented waitForBuffer parameter

### ISSUE THREAD

**Issue by puckey** [DoubleSymmetry/react-native-track-player#616]
After releasing the Android version of my app, I went over to iOS mode. I was unable to play any streams until I set the undocumented `waitForBuffer` parameter to `true` in `TrackPlayer.setupPlayer`:

```
  const buffer = 0.5;
  await TrackPlayer.setupPlayer({
    playBuffer: buffer,
    minBuffer: buffer * 2,
    maxBuffer: buffer * 2,
    waitForBuffer: true
  });
```

If I do not set this parameter, the stream plays almost directly and then stops again.

**Comment by maartenvandillen** [comment]
On my device it did not play at all without the waitForBuffer parameter. Android is working fine but I had never heard any audio on iOS until I added that.

**Comment by sebacaccaro** [comment]
> On my device it did not play at all without the waitForBuffer parameter. Android is working fine but I had never heard any audio on iOS until I added that.

Same here

**Comment by puckey** [comment]
I was about to add this parameter to the docs, but reading the [docs](https://developer.apple.com/documentation/avfoundation/avplayer/1643482-automaticallywaitstominimizestal) of the underlying `automaticallyWaitsToMinimizeStalling ` option leads me to think we should just default it to true and not have it be configurable at all.

When set to true:

> When this property is true and the player changes from a paused state (rate of 0.0) to a played state (rate > 0.0), the player will try to determine if the current item can play to its end at the currently specified rate. If it determines that it’s likely to encounter a stall, the value of the player’s timeControlStatus will change to AVPlayer.TimeControlStatus.waitingToPlayAtSpecifiedRate and playback will automatically start when the likelihood of stalling has been minimized. A similar condition will occur during playback if the current player item’s playback buffer is exhausted and playback stalls. Playback will automatically resume when the likelihood of stalling has been minimized.

When set to false:

> If the value of this property is false, playback will start immediately when requested as long as the playback buffer is not empty. If the playback buffer becomes empty and playback stalls, the player’s timeControlStatus will switch to AVPlayer.TimeControlStatus.paused and the playback rate will change to 0.0.

Maybe I am missing something, but I can't think of a situation in the context of `rntp` where having the playback stop when the playback buffer is empty makes sense.

@curiousdustin perhaps you have some thoughts on this? Do you set this option to true in your app?

**Comment by curiousdustin** [comment]
I have not used `waitForBuffer` in my app. 

I'm not sure why I haven't experienced the issues described. But I agree with your assessment. Perhaps we should just default to true.

**Comment by puckey** [comment]
Interesting that you have not experienced this. Come to think of it, I have also not noticed it in the example app.

Perhaps it is because in both situations the audio files are hosted with enough bandwidth, causing us to never encounter a buffering phase after the initial buffer?

**Comment by curiousdustin** [comment]
Yes, that is possible. It is also possible that I have experienced the issue without realizing or attributing it to this.

**Comment by puckey** [comment]
I will test the example app using a slow internet connection to make sure I can reproduce this in the example app also and that it is not just a streaming audio issue.. Just need to figure out how to slow down the internet speed of an iOS device.

**Comment by curiousdustin** [comment]
You could also try one of the URLs you have experienced this with, but in the example app.

**Comment by marcpope** [comment]
please add this in the docs! lost an entire day trying to figure out what I did wrong. fixed my problem immediately.
