### ISSUE TITLE
Android:com.github.bumptech.glide:glide

### ISSUE THREAD

**Issue by qinAI** [DoubleSymmetry/react-native-track-player#625]
Android dependency 'com.github.bumptech.glide:glide' has different version for the compile (4.5.0) and runtime (4.7.1) classpath. You should manually set the same version via DependencyResolution

**Comment by Guichaguri** [comment]
Which React Native version are you using? Are you using any other native modules, which ones and what are their versions? What react-native-track-player version are you using?

**Comment by curiousdustin** [comment]
@qinAI, can you provide any further details?
