### ISSUE TITLE
TypeError: resolveAssetSource_1. Default is not a function

### ISSUE THREAD

**Issue by duducv** [DoubleSymmetry/react-native-track-player#656]
Configuration
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 239.21 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    npm: 6.5.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1

Issue
Had an issue probably in the function TrackPlayer.add().
the issue is:
TypeError: resolveAssetSource_1.default is not a function (In resolveAssetSource_1.default(path)
resolveAssetSource_1.default is undefined)

 Code

const Track1 = {
  id:'Educadora',
  url:'http://audio.flaresoft.com.br:9988/;stream.mp3'
}

const Track2 = {
  id:'Teste',
  url: require('./pure.mp4')
}

TrackPlayer.setupPlayer().then(async () => {
  await TrackPlayer.add([Track1, Track2]).then(() => {
  }).catch((e) => {
    alert(e)
  });

  TrackPlayer.play();
});

**Comment by Fghurayri** [comment]
I had the same issue. Here is how I solved it (but I don't know what is the impact)

Go to `node_modules/react-native-track-player/lib/index.js`
Instead of `return resolveAssetSource_1.default(path) || path;` at line `61`
Make it `return path;`

**Comment by duducv** [comment]
Thank you @Fghurayri

**Comment by curiousdustin** [comment]
Based on @Fghurayri 's fix, I'm assuming you encountered this issue in `v2`?
