### ISSUE TITLE
Music file not played from app bundle

### ISSUE THREAD

**Issue by mayankmittal242** [DoubleSymmetry/react-native-track-player#660]
I have a music file in public folder in react native, when I try to play that, the music is playing comfortably in debug mode in IOS,  But not playing music file in the Production build.
React native 0.59.2
platform: IOS production build

**Comment by UmangSarkari** [comment]
i am facing the same issue too. Assets in app bundle not playing in ios release build. The playback-error listener calls back with the following error message »» "The file "xyz.mp3" could not be opened because you don't have permission to view it"

**Comment by UmangSarkari** [comment]
i am facing the same issue too. Assets in app bundle not playing in ios release build. The playback-error listener calls back with the following error message »» "The file 'xyz.mp3' could not be opened because you don't have permission to view it"

**Comment by curiousdustin** [comment]
Can you provide an example of the track object you are using in `TrackPlayer.add()`?
