### ISSUE TITLE
1.1.6 uses ExoPlayer features only available with AndroidX

### ISSUE THREAD

**Issue by Frank1234** [DoubleSymmetry/react-native-track-player#663]
The 1.1.6 version of the lib uses features from ExoPlayer 2.10+, ExoPlayer versions that use AndroidX.

Problem: Using react-native-track-player 1.1.6 with ExoPlayer 2.9.6 gives errors on missing classes like IcyHeaders and IcyInfo in ExoPlayback.java.

Problem: Using a newer ExoPlayer version is not possible, because these ExoPlayer versions reference AndroidX.

**Comment by curiousdustin** [comment]
@Guichaguri should we close this?
