### ISSUE TITLE
Rating not working on android

### ISSUE THREAD

**Issue by moduval** [DoubleSymmetry/react-native-track-player#67]
When I do this on Android:

```javascript
    TrackPlayer.updateOptions({
      ratingType: RATING_HEART,
      capabilities: [CAPABILITY_PLAY, CAPABILITY_PAUSE, CAPABILITY_STOP, CAPABILITY_SET_RATING],
      compactCapabilities: [CAPABILITY_PLAY, CAPABILITY_PAUSE, CAPABILITY_STOP, CAPABILITY_SET_RATING],
      stopWithApp: true
    });
```

The rating does not appear on the status bas and I dont know why.

Also, for now I dont see the difference between compactCapabilities and capabilities. It seems that the compactCapabilities doesn't appear.

**Comment by Guichaguri** [comment]
Rating does not show up in the notification at all. It's currently only accessible through external devices, such as smartwatches, cars, etc. Do you think rating buttons should be added?

**Comment by moduval** [comment]
I think it should be added to the notification. It would be nice to have a heart button to favorite a track for example. Thats what I was thinking when adding this capability. It should at least be specified in the doc when it doesn't appear in notification.

**Comment by visagegod** [comment]
+1 to this feature request

**Comment by titarenko-alexander** [comment]
Is this was implemented or not?

**Comment by jspizziri** [comment]
@titarenko-alexander I'm not sure as this was before my tone and I've never used it. The docs make me think it works though.

**Comment by titarenko-alexander** [comment]
Ok, thanks for reply.
This seems doesn't work
`Capability.SetRating`
And 
`ratingType: RatingType.Heart`
And nothing appears on notification bar
https://github.com/doublesymmetry/react-native-track-player/issues/67#issuecomment-340134450

**Comment by jspizziri** [comment]
@titarenko-alexander What version are you on?

**Comment by titarenko-alexander** [comment]
> @titarenko-alexander What version are you on?
Version: 2.1.3

Code: 
`await TrackPlayer.add(track);
 await TrackPlayer.updateOptions({ capabilities: [Capability.Play, Capability.Pause, Capability.SetRating, Capability.SeekTo, Capability.SkipToNext, Capability.SkipToPrevious], stopWithApp: true, ratingType: RatingType.Heart });`

**Comment by jspizziri** [comment]
@titarenko-alexander Please try it in 2.2.0-rc3. If it doesn't work there as documented then please create an issue documenting your findings. Thanks!
