### ISSUE TITLE
does it support real time playing encrypted media?

### ISSUE THREAD

**Issue by VicoErv** [DoubleSymmetry/react-native-track-player#671]
I have encrypted audio service that will decrypt every 131071 byte and push it into audio buffer, if in web i can use AudioContext, is this thing supported using this library?

**Comment by Guichaguri** [comment]
No, not at the moment.

**Comment by idjitjohn** [comment]
Really need this feature. I got to play and decrypt on the fly an audio too.
Have you got any solution @Guichaguri

**Comment by MaxJadav** [comment]
@VicoErv  @Guichaguri  @idjitjohn 
Do you have any updated solution for this?
