### ISSUE TITLE
Feature-Request: Equalizer support

### ISSUE THREAD

**Issue by thecodrr** [DoubleSymmetry/react-native-track-player#679]
Great work on this library!

So I have been using this library in one of my apps and so far so great. However, I have requirement of an equalizer and I looked through ExoPlayer docs and found out that it does support full equalizer functionality. I found [this](https://medium.com/@sherazahmed93/android-equalizer-411fe8e8ef97) and [this](https://www.javatips.net/api/Jockey-master/app/src/main/java/com/marverenic/music/player/EqualizedExoPlayer.java) for reference.

I would be willing to help in any way I can but I would need a little guidance. EQ implementation shouldn't be that hard, the hard part is connecting the EQ to the react-native side (at least for me) so that it is seamless.

Having an EQ would make the feature-set of this library much more appealing.

**Comment by Tiamatmate** [comment]
Would love to see this be implemented as well.

**Comment by Guichaguri** [comment]
I'd love to implement that, but I'd need someone to help me out with the iOS side too.

**Comment by Tiamatmate** [comment]
I might be wrong here, but the library [https://github.com/jorgenhenrichsen/SwiftAudio](url) that is used for the iOS part is built upon `AVPlayer` which doesn't support an equalizer (AFAIK). That might be a problem.

**Comment by Guichaguri** [comment]
That's unfortunate. It's also a good reason to not implement it just yet, as one of the goals of this module is to have a single API that works equally on both platforms.
I'll leave this issue open, I'm definitely willing to look into this again in the future.

**Comment by SandyAdel** [comment]
Hello,
I had deep investigation in how to implement Equalizer (like Spotify) in both Android & IOS inside react-native-track-player;
In Android, I found it easy to add this feature.
But in IOS; As AVPlayer is not supporting the EQ effects, I should use AVAudioPlayer instead.

Does anyone know a workaround  that I can do to support EQ in IOS without this huge refactor?

**Comment by bradleyflood** [comment]
Thanks all. I've added this to the Project Backlog as a Feature Request. We will review. Thanks :)
