### ISSUE TITLE
[iOS] TrackPlayer.setRate() changes the voice, almost like an echo.

### ISSUE THREAD

**Issue by gtovar333** [DoubleSymmetry/react-native-track-player#682]
# Configuration

Run `react-native info` in your project and share the content.
What `react-native-track-player` version are you using?
  "version": "1.1.6"

# Issue
setRate works 'properly' the audio is been played either faster or slower when given a certain rate, however the voice in the cast seems to be altered with some sort of ECHO which doesn't seems to happen with other players when setting a faster or slower rate.

# Code

  toggleSpeed = async (speed) => {
    const { speed } = this.props
    await TrackPlayer.setRate(PLAYER_SPEED[newSpeed])
  }

Code is pretty straight forward.

**Comment by ryan-rokusek** [comment]
I'm having the same issues

`System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 35.29 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 24.0.2, 25.0.0, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-19 | Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2`

Version: 2.0.0-rc13

**Comment by sslash** [comment]
Same here!

**Comment by ryan-rokusek** [comment]
Setting `pitchAlgorithm: PitchAlgorithm.Music` on your tracks seems to make that issues much better.

**Comment by jvandenaardweg** [comment]
> Setting pitchAlgorithm: PitchAlgorithm.Music on your tracks seems to make that issues much better.

Confirming this also works with `pitchAlgorithm: TrackPlayer.PITCH_ALGORITHM_VOICE`. Thanks!
