### ISSUE TITLE
Loosing connection changing WIFI to 4G on online streams

### ISSUE THREAD

**Issue by maendamedia** [DoubleSymmetry/react-native-track-player#686]
# Configuration

 "react-native-track-player": "1.2.0",

# Issue
When changing the internet connection from WIFI to 4G (or vice-versa), the player looses connection and not resuming the stream anymore. I need to hard restart the app to restart the playing state.

Is there an event handler with example i can use to fix this or is there a way to prevent this?

**Comment by maendamedia** [comment]
Anyone? ☺️

**Comment by Xammie** [comment]
Hey @maendamedia, You could use the [`plackback-error`](https://react-native-kit.github.io/react-native-track-player/documentation/#playback-error) event to retry playing when an connection error occurs. Or maby something like [`@react-native-community/netinfo`](https://github.com/react-native-community/react-native-netinfo) to know if you are connected to WiFi or 4G.

**Comment by mhabegger** [comment]
@maendamedia this is a normal iOS behavior. We solved this by storing the playing state (i.e. `shouldBePlaying`) separately. 
When the state of the player changes to `State.Stopped` while `shouldBePlaying` is still true we force a `TrackPlayer.play()` and assume there was an unintentional interruption thus restarting the stream. 

But I think it's technically impossible to handle this without interruption on online live streams as the TCP connection itself disconnects when the network interface changes.

**Comment by sslash** [comment]
@mhabegger how do you know if the player-changed event happened because a user hit stop, or something else?
