### ISSUE TITLE
react-native run-android --variant=release

### ISSUE THREAD

**Issue by lucked** [DoubleSymmetry/react-native-track-player#691]
HI when i use
react-native run-android --variant=release
the audio dont play, if only use react-native run-android works fine
, how can i deploy to google play my app?

**Comment by farman05** [comment]
Facing the same issue, is your issue get resolved ?

**Comment by maendamedia** [comment]
Does this have a solution yet? Android seems to have issues lately :(

**Comment by lucked** [comment]
$ cd android
$ ./gradlew assembleRelease
my solution

**Comment by vayter2** [comment]
Maybe you have Android 9 - then it is due to security policy - please read here how to solve it: https://developer.android.com/training/articles/security-config
