### ISSUE TITLE
Example app that works?

### ISSUE THREAD

**Issue by lucked** [DoubleSymmetry/react-native-track-player#693]
someone have a exemple app that works on variant=release?
share the github please , audio dont works on release for me , only debug

**Comment by maendamedia** [comment]
On which os you have no sound? I guess on Android?

**Comment by vayter2** [comment]
Same issue - Player runs for a second (I can see "play" triangle icon in the tray then it disappears).
Works fine only with react-native run-android debug mode.

**Comment by vayter2** [comment]
Maybe you have Android 9 - then it is due to security policy - please read here how to solve it: https://developer.android.com/training/articles/security-config

**Comment by curiousdustin** [comment]
Have either of you tried the example app included in this library? 

Please try version 1.2.3.
