### ISSUE TITLE
playback-error event inconsistent parameters

### ISSUE THREAD

**Issue by Xammie** [DoubleSymmetry/react-native-track-player#694]
The `playback-error` event callback is documented to have two values in the parameter object `code` and `message`. [For android this is correct](https://github.com/react-native-kit/react-native-track-player/blob/dev/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java#L247). On [iOS the return object only contains a key named `error`](https://github.com/react-native-kit/react-native-track-player/blob/dev/ios/RNTrackPlayer/RNTrackPlayer.swift#L182). This seems illogical to me and I can't find a reason or explanation anywhere.

Is this intended behaviour? if so where can I find the documentation of this? If this is not intended I'll happily create a pull request to fix this inconsistency.

**Comment by jcurlier** [comment]
+1

**Comment by Sandeep155Vibhuti** [comment]
I got the Same Error on the PlayList
![playbackError](https://user-images.githubusercontent.com/75908175/102743618-d0eb8100-437d-11eb-8c8a-3122addd23fd.png)

**Comment by ramisalem** [comment]
I agree and To be honest we do not know what we should do if this event fires?
