### ISSUE TITLE
IOS dont show notification

### ISSUE THREAD

**Issue by lucked** [DoubleSymmetry/react-native-track-player#695]
My ios build dont show notification , the audio works perfectly but dont show notification,
what can i do?
im using this config
TrackPlayer.updateOptions({
        // An array of media controls capabilities
        capabilities: [
            TrackPlayer.CAPABILITY_PLAY,
            TrackPlayer.CAPABILITY_STOP
        ],
        
        // An array of capabilities that will show up when the notification is in the compact form on Android
        compactCapabilities: [
            TrackPlayer.CAPABILITY_PLAY,
            TrackPlayer.CAPABILITY_STOP
        ]
      });

**Comment by khalidos32** [comment]
same issue her, did you figure ou a solution?

**Comment by moonstruck** [comment]
Real device or simulator?

**Comment by khalidos32** [comment]
@moonstruck real device, on my iphone 6 (ios 11 ) it works but on iphone8(ios 12.1...) it doesn't show the player on the notification.

**Comment by moonstruck** [comment]
Which version of track player you are using?

**Comment by khalidos32** [comment]
@moonstruck  i'm using:
    "react-native-track-player": "^1.1.4",
    "react": "^16.8.3",
    "react-native": "^0.59.5",

**Comment by moonstruck** [comment]
In our case, iOS lock screen notification works fine. I'll cross check versions.

**Comment by khalidos32** [comment]
as i told you it works on ios 11 and on 1é it doesn't work

**Comment by khalidos32** [comment]
@lucked did you fix the issue?

**Comment by khalidos32** [comment]
any one here?

**Comment by mhabegger** [comment]
Not sure it works in 0.59. Did you try on RN-60 ?
Does it work when you explicitly update the metadata with for example:
```
const track = {
      artist: 'My Artist',
      title: 'Foo',
      artwork: 'https://someurl/picture',
      duration: 450,
    }
TrackPlayer.updateMetadataForTrack(someTrackId, track)
```
