### ISSUE TITLE
Sometimes before the end of the track and the beginning of a new player pause

### ISSUE THREAD

**Issue by Mikhail1992** [DoubleSymmetry/react-native-track-player#697]
> Environment:
>   OS: macOS 10.14.3
>   Node: 9.11.2
>   Yarn: 1.12.1
>   npm: 5.6.0
>   Watchman: 4.9.0
>   Xcode: Xcode 10.1 Build version 10B61
>   Android Studio: 3.3 AI-182.5107.16.33.5314842
> 
> Packages: (wanted => installed)
>   react: 16.3.1 => 16.3.1
>   react-native: 0.55.3 => 0.55.3

react-native-track-player: 1.1.3
OS - IOS

# Issue
For example, I have a session of 6 hours and after playing the first or second track in the session, the player may pause. I did't call additional handlers in the code to pause.

**Comment by Mikhail1992** [comment]
Maybe this will help solve the problem
At the moment when the player pauses I get this information in the logs
`
 <APP>[32541:4197011] [Symptoms] {
  "transportType" : "HTTP Progressive Download",
  "mediaType" : "HTTP Progressive Download",
  "BundleID" : "<APP>",
  "name" : "MEDIA_PLAYBACK_STALL",
  "interfaceType" : "Wifi"
}
`

**Comment by nishanBende** [comment]
@Guichaguri Could this be related to https://github.com/react-native-kit/react-native-track-player/issues/745
I get the same logs and i have also created a repo where you can reproduce it easily. Let me know if any more detail is needed.
Repo link: https://github.com/nishanBende/react-native-track-player-seekTo-issue/blob/master/App.js

Thanks
