### ISSUE TITLE
How to play hls on iOS

### ISSUE THREAD

**Issue by Sathyanarayan09** [DoubleSymmetry/react-native-track-player#712]
In reference to this issues https://github.com/react-native-kit/react-native-track-player/issues/64 
can any one give an example config?

**Comment by moonstruck** [comment]
https://github.com/react-native-kit/react-native-track-player/issues/64#issuecomment-392650045

**Comment by Sathyanarayan09** [comment]
@moonstruck  I tried but was not working, was it working for you?

**Comment by mhabegger** [comment]
@Sathyanarayan09 what HLS stream URL where you using? What did the HLS manifest contain?

**Comment by brunoserra** [comment]
@mhabegger I couldn't get it working as well. I've tried with these URL:
https://servidor26.brlogic.com:8034/live
https://servidor27.brlogic.com:8034/live
https://servidor28.brlogic.com:8034/live

They are from the same provider, but with slightly different config.
I've tried adding the "type" parameter to the TrackPlayer track config, but i guess the player detects the type by itself?

Thanks in advance  :)

**Comment by moonstruck** [comment]
@brunoserra  It seems you are trying to play aac stream.
I have tested mp3 stream, works fine.
Not sure aac is supported or not.

**Comment by brunoserra** [comment]
Thank you, that was it @moonstruck  🎉
One more thing, do you know if this lib manages internet connection interruptions, so if the player pauses, it start playing again when internet is available?

**Comment by appify-waheed** [comment]
I have tried to play HLS but it's not working.
here is the example url.
https://d1rwbc680ljllj.cloudfront.net/api/serve/5e708789b160de5d37ec0bdc/media

**Comment by daviosoo** [comment]
@brunoserrar, did you get it to play the stream: https://servidor27.brlogic.com:8034/live on iOS?
If yes, can you tell me please what did you do?
