### ISSUE TITLE
Using cocoapods instead of gitmodule for SwiftAudio

### ISSUE THREAD

**Issue by biomancer** [DoubleSymmetry/react-native-track-player#724]
The main issue on that subject is currently https://github.com/react-native-kit/react-native-track-player/issues/703, but I'd also would like to suggest that we get rid of submodules at all, as it's extremely inconvenient to work with and error-prone. Could we maybe make use of cocoapods to include that lib? Like firebase and other libs are doing when there is a required native dependency.

**Comment by curiousdustin** [comment]
I agree. The missing commit submodule thing caused me a couple days of headache because it only partially failed to work and I assumed it had resolved itself.

**Comment by curiousdustin** [comment]
@Guichaguri what do you think of this suggestion to fix #703 ?

**Comment by Guichaguri** [comment]
Just got a fix on that one, but we should definitely look into cocoapods, I think @dcvz started using gitmodules to allow quick customization on SwiftAudio, I don't know whether that is still the case.

**Comment by jeffmon** [comment]
The latest stable version of React Native `0.61.5` won't allow any libraries to work without [Cocoapods](https://github.com/facebook/react-native/issues/26615).
