### ISSUE TITLE
playback-track-changed is not working on android (working on ios)

### ISSUE THREAD

**Issue by vibdheeraj** [DoubleSymmetry/react-native-track-player#740]
TrackPlayer.registerEventHandler((data)=>{
        console.log("got event",data.type,data)
        TrackPlayer.getCurrentTrack().then((track_id)=>{
            this.currentIndex = this.tracks.findIndex(t => t.id === track_id)
        })

        if(data.type === 'playback-track-changed') {
            if(this.repeat) {
                //don't mess with anything if already on the track to repeat
                if(data.nextTrack === this.trackToRepeat) return
                if(!data.track && data.nextTrack && this.trackToRepeat === null) {
                    this.trackToRepeat = data.nextTrack
                } else {
                    TrackPlayer.pause()
                    TrackPlayer.skip(this.trackToRepeat).then(()=>TrackPlayer.play())
                }
            }
        }

**Comment by curiousdustin** [comment]
What version of `react-native-track-player`?

Can you try on `v1.2.3`?

Can you provide more explanation? Do you receive other events on Android?
