### ISSUE TITLE
Notification onClick event for IOS

### ISSUE THREAD

**Issue by HessiPard** [DoubleSymmetry/react-native-track-player#751]
It would be great if IOS supports notification click event just like android:
`trackplayer://notification.click`

**Comment by curiousdustin** [comment]
Can you explain a bit more?

iOS should automatically reopen your app when tapping on the notification / controls.

**Comment by HessiPard** [comment]
Yes it opens the app, no problem there.
But I mean [trackplayer://notification.click](https://react-native-kit.github.io/react-native-track-player/background/#notification) should be added to IOS too.
in IOS it doesnt provide specific URL to handle notification open action.

**Comment by curiousdustin** [comment]
From what I can tell, this is not possible on iOS.

Does anyone else have an idea for how to accomplish this?
