### ISSUE TITLE
Player service and timers

### ISSUE THREAD

**Issue by neoassyrian** [DoubleSymmetry/react-native-track-player#760]
Hi, 
I have a question more than an issue. Is it possible to use the player service (runs in the background) to make GET http requests to pull data and update the playing track details? 
In my case I'm playing a radio stream (shoutcast) and would like to update the track meta data every 5 seconds for example. Is that possible? If so, what so I need to do. 
Thanks in advance.

**Comment by laugre** [comment]
Hi !
Yes, you can use updateMetadataForTrack to update your player datas :
TrackPlayer.updateMetadataForTrack(currentTrack, {
          title: source.title,
          artist: source.artist,
        });

**Comment by laugre** [comment]
#636

**Comment by Guichaguri** [comment]
Let me know if #636 didn't work for you.
