### ISSUE TITLE
Notification controls are not working.

### ISSUE THREAD

**Issue by cjassu** [DoubleSymmetry/react-native-track-player#775]
# Configuration

Run `react-native info` in your project and share the content.
What `react-native-track-player` version are you using?

# Issue

 Player is working fine but the notification button is not firing any action.

# Code

TrackPlayer.setupPlayer();
    TrackPlayer.updateOptions({
      stopWithApp: true,
      capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_STOP,
        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS
      ],
      compactCapabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_STOP
      ]
    });
    // this.togglePlayback();
  }

**Comment by boypanjaitan16** [comment]
I experinced this issue too, can someone help ?

### Here is my setup
`"@react-native-community/async-storage": "^1.6.3",
    "date-fns": "^2.8.1",
    "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-cardview": "^2.0.5",
    "react-native-device-info": "^5.3.1",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "^1.5.0",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-modals": "^0.19.9",
    "react-native-raw-bottom-sheet": "^2.0.6",
    "react-native-segmented-control-tab": "^3.4.1",
    "react-native-simple-toast": "^1.0.0",
    "react-native-super-grid": "^3.1.1",
    "react-native-swift": "^1.2.2",
    "react-native-touchable-scale": "^2.1.0",
    "react-native-track-player": "^1.1.8",
    "react-native-tts": "^3.1.0",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.6.0"`

And here is my code
`setUpPlayer = async (tmpTrack) => {
        let state   = await TrackPlayer.getState();

        if (state === TrackPlayer.STATE_NONE) {
            TrackPlayer.setupPlayer().then(() => {
                TrackPlayer.updateOptions({
                    // One of RATING_HEART, RATING_THUMBS_UP_DOWN, RATING_3_STARS, RATING_4_STARS, RATING_5_STARS, RATING_PERCENTAGE
                    ratingType: TrackPlayer.RATING_5_STARS,

                    // Whether the player should stop running when the app is closed on Android
                    stopWithApp: true,
                    alwaysPauseOnInterruption: true,
                    capabilities: [
                        TrackPlayer.CAPABILITY_PLAY,
                        TrackPlayer.CAPABILITY_PAUSE,
                        TrackPlayer.CAPABILITY_STOP,
                        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
                        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS
                    ],

                    // An array of capabilities that will show up when the notification is in the compact form on Android
                    compactCapabilities: [
                        TrackPlayer.CAPABILITY_PLAY,
                        TrackPlayer.CAPABILITY_PAUSE,
                        TrackPlayer.CAPABILITY_STOP,
                        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
                        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS
                    ],
                    notificationCapabilities : [
                        TrackPlayer.CAPABILITY_PLAY,
                        TrackPlayer.CAPABILITY_PAUSE,
                        TrackPlayer.CAPABILITY_STOP,
                        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
                        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS
                    ],
                    icon    : require('../img/icon.png')
                });
            });
        }

        TrackPlayer.add(tmpTrack)
            .then(() => {
                if(state !== TrackPlayer.STATE_PLAYING){
                    TrackPlayer.stop();
                }
            })
            .catch(err => {
                Alert.alert('Player Error', err.toString());
            });

        console.log('NOW : '+state);

    };`

**Comment by R3DST0RM** [comment]
Were you able to solve the issue?

**Comment by jakovB777** [comment]
I was having the same issue but for some weird reason I needed to rebuilt the code:

Try commenting the notificationCapabilities and compactCapabilities. Then i had it working (partly, but yeah) It works with this code:

```

TrackPlayer.setupPlayer().then(() => {
	TrackPlayer.updateOptions({
		alwaysPauseOnInterruption: true,
		waitForBuffer: true,
		stopWithApp: true,
		capabilities: [
			TrackPlayer.CAPABILITY_PLAY,
			TrackPlayer.CAPABILITY_PAUSE,
			TrackPlayer.CAPABILITY_SEEK_TO,
			TrackPlayer.CAPABILITY_JUMP_FORWARD,
			TrackPlayer.CAPABILITY_JUMP_BACKWARD,
		],
		// compactCapabilities: [
		// 	TrackPlayer.CAPABPLILITY_PLAY,
		// 	TrackPlayer.CAPABILITY_PAUSE,
		// 	TrackPlayer.CAPABILITY_SEEK_TO,
		// 	TrackPlayer.CAPABILITY_JUMP_FORWARD,
		// 	TrackPlayer.CAPABILITY_JUMP_BACKWARD,
		// ],
		// notificationCapabilities: [
		// 	TrackPlayer.CAPABPLILITY_PLAY,
		// 	TrackPlayer.CAPABILITY_PAUSE,
		// 	TrackPlayer.CAPABILITY_SEEK_TO,
		// 	TrackPlayer.CAPABILITY_JUMP_FORWARD,
		// 	TrackPlayer.CAPABILITY_JUMP_BACKWARD,
		// ],
	});
});
```

**Comment by R3DST0RM** [comment]
@jakovB777 thanks for sharing your insights. After trying different things out, I've managed to get things running **using version 1.1.2** of `react-native-track-player`

**Comment by Guichaguri** [comment]
Can you please specify what is not working?
Are they not showing up? Is pressing them not triggering any events?

**Comment by zacharywenner** [comment]
I'm having this issue on V2 as well. I only want to show play/pause, seek forward 15, and seek backward 15.

On v2.0.0-rc13 notification controls show play/pause, skip forward, skip backwards but none work.

I rolled back to v2.0.0-rc12 and now the controls work until another track is added to the queue. Then it goes back to play/pause, skip forward, skip backward.

**First Track**
![IMG_0272](https://user-images.githubusercontent.com/10377501/71490843-fa60e380-27e1-11ea-8b52-32385a4eadda.PNG)

**Another track added to queue and playing in the app**
![IMG_0274](https://user-images.githubusercontent.com/10377501/71490842-f6cd5c80-27e1-11ea-95c5-4d6bc40d3128.PNG)

**Comment by zacharywenner** [comment]
I rolled back to 1.1.8, and similar issues. The play/pause, skip forward, skip backward show up, however only the play/pause work.

```
"react": "16.12.0",
"react-native": "0.61.5",
"react-native-track-player": "1.1.8",
```

```
module.exports = async function() {
  TrackPlayer.addEventListener('remote-play', () => {
    TrackPlayer.play();
  });

  TrackPlayer.addEventListener('remote-pause', () => {
    TrackPlayer.pause();
  });

  TrackPlayer.addEventListener('remote-jump-forward', () => {
    jumpPlayback(15, true); // seek forward 15 seconds
  });

  TrackPlayer.addEventListener('remote-jump-backward', () => {
    jumpPlayback(15); // seek backward 15 seconds
  });
};
```

```
export async function setupAudio() {
  TrackPlayer.setupPlayer({
    waitForBuffer: true
  }).then(async () => {
    TrackPlayer.updateOptions({
      stopWithApp: true,
      capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_JUMP_FORWARD,
        TrackPlayer.CAPABILITY_JUMP_BACKWARD,
        TrackPlayer.CAPABILITY_STOP,
      ],
      compactCapabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE
      ],
      jumpInterval: 15
    });
  });
}
```
Controls show up incorrectly. Play/pause works however.
![IMG_0276](https://user-images.githubusercontent.com/10377501/71492915-c2f93380-27ef-11ea-90ef-e4222abd25a5.PNG)
![IMG_0275](https://user-images.githubusercontent.com/10377501/71492919-c8567e00-27ef-11ea-8c01-fad9b995cdb6.PNG)

**Comment by feedcast-me** [comment]
same issue here

**Comment by muganwas** [comment]
I'm using "react-native-track-player": "^1.1.7" and I have the same problem, non of my notification buttons work.

**Comment by alanhabib** [comment]
I have exactly the same issue, for me the jump-forward and backward button appears at first track when getting out from the component and setup new player the buttons disappears and are replaced with "<<" ">>" or it is only one of them appearing. 

tried upgrading between versions but no success. 

Version: 1.1.8
"react": "^16.9.0",
"react-native": "0.61.5",

**Comment by alanhabib** [comment]
@Guichaguri 
what do you think of below? It works perfectly now, remote-controls always shows up...
Before, as I wrote above, 2 buttons showed up and the last ones could disappear. 
I changed my above code to this: 

 upDateOptionsHandler = async () => {
        await TrackPlayer.updateOptions({
            jumpInterval: 10,
            capabilities: [
                await TrackPlayer.CAPABILITY_JUMP_FORWARD,
                await TrackPlayer.CAPABILITY_JUMP_BACKWARD,
                await TrackPlayer.CAPABILITY_SEEK_TO,
                await TrackPlayer.CAPABILITY_PLAY,
                await TrackPlayer.CAPABILITY_PAUSE,
                await TrackPlayer.CAPABILITY_STOP
            ]
        });
    };

**Comment by fernando-pascoal** [comment]
version react-native-track-player": "^2.0.0-rc13 not show external controls in ios, only Android. Someone can help me?

**Comment by ainar** [comment]
I confirm that notification controls are not working on Android (10). I made a test app with only a music playing with react-native-track-player and the notifications buttons are not working.

However, controls are working on lock screen and music correctly pauses when removing headphone jack. Its look like notification buttons do not trigger events.

**Comment by ainar** [comment]
Bump again: I found that notifications button work correctly on Android 7.

**Comment by ainar** [comment]
So, I found how to fix this problem in my case:
in `/android/build.gradle`, change `compileSdkVersion` and `targetSdkVersion` to `29`. May be related to #859.

**Comment by curiousdustin** [comment]
https://github.com/react-native-kit/react-native-track-player/commit/d3400a475d8be146aa25696b5f014dd538e2dd86 should resolve the iOS issues mentioned here. Will get this into v2 soon.

**Comment by MuhammadAbdullah54321** [comment]
> Can you please specify what is not working?
> Are they not showing up? Is pressing them not triggering any events?

They are showing up but are not responding to any events.

**Comment by MuhammadAbdullah54321** [comment]
> I rolled back to 1.1.8, and similar issues. The play/pause, skip forward, skip backward show up, however only the play/pause work.
> 
> ```
> "react": "16.12.0",
> "react-native": "0.61.5",
> "react-native-track-player": "1.1.8",
> ```
> 
> ```
> module.exports = async function() {
>   TrackPlayer.addEventListener('remote-play', () => {
>     TrackPlayer.play();
>   });
> 
>   TrackPlayer.addEventListener('remote-pause', () => {
>     TrackPlayer.pause();
>   });
> 
>   TrackPlayer.addEventListener('remote-jump-forward', () => {
>     jumpPlayback(15, true); // seek forward 15 seconds
>   });
> 
>   TrackPlayer.addEventListener('remote-jump-backward', () => {
>     jumpPlayback(15); // seek backward 15 seconds
>   });
> };
> ```
> 
> ```
> export async function setupAudio() {
>   TrackPlayer.setupPlayer({
>     waitForBuffer: true
>   }).then(async () => {
>     TrackPlayer.updateOptions({
>       stopWithApp: true,
>       capabilities: [
>         TrackPlayer.CAPABILITY_PLAY,
>         TrackPlayer.CAPABILITY_PAUSE,
>         TrackPlayer.CAPABILITY_JUMP_FORWARD,
>         TrackPlayer.CAPABILITY_JUMP_BACKWARD,
>         TrackPlayer.CAPABILITY_STOP,
>       ],
>       compactCapabilities: [
>         TrackPlayer.CAPABILITY_PLAY,
>         TrackPlayer.CAPABILITY_PAUSE
>       ],
>       jumpInterval: 15
>     });
>   });
> }
> ```
> 
> Controls show up incorrectly. Play/pause works however.
> ![IMG_0276](https://user-images.githubusercontent.com/10377501/71492915-c2f93380-27ef-11ea-90ef-e4222abd25a5.PNG)
> ![IMG_0275](https://user-images.githubusercontent.com/10377501/71492919-c8567e00-27ef-11ea-8c01-fad9b995cdb6.PNG)

Probably because you only have included these 2 options of pause and play in compactCapabilities here:
>  compactCapabilities: [
>         TrackPlayer.CAPABILITY_PLAY,
>         TrackPlayer.CAPABILITY_PAUSE
>       ],

**Comment by ZiyaDogramaci** [comment]
Not working on my Sony Xperia Z5 Compact (Android 7.1.1)
I am using 1.2.7.
Here is my react-native-info output:

```
  System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 2.09 GB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.12.0 - ~/.nvm/versions/node/v15.12.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v15.12.0/bin/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v15.12.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.3, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

This is my implementation of both updateOptions and service.js. I tried all combinations of commenting out compactCapabilities and notificationCapabilities but nothing changes.

```
    RNTrackPlayer.updateOptions({
      capabilities: [
        RNTrackPlayer.CAPABILITY_PLAY,
        RNTrackPlayer.CAPABILITY_PAUSE,
        RNTrackPlayer.CAPABILITY_STOP
      ],
/*      compactCapabilities: [
        RNTrackPlayer.CAPABILITY_PLAY,
        RNTrackPlayer.CAPABILITY_PAUSE,
        RNTrackPlayer.CAPABILITY_STOP
      ],
      notificationCapabilities: [
        RNTrackPlayer.CAPABILITY_PLAY,
        RNTrackPlayer.CAPABILITY_PAUSE,
        RNTrackPlayer.CAPABILITY_STOP
      ],*/
      stopWithApp: true
    });
```

```
module.exports = async function() {
  TrackPlayer.addEventListener('remote-play', () => TrackPlayer.play());

  TrackPlayer.addEventListener('remote-pause', () => TrackPlayer.pause());

  TrackPlayer.addEventListener('remote-stop', () => TrackPlayer.destroy());
};
```

**Comment by kilimchoi** [comment]
I'm using 1.2.7 and the notification controls do not trigger any `remote-*` events. anyone facing the same issue?

**Comment by aliraza96** [comment]
I have tried all the options above, but I am still not able to control play/pause from Lock Screen/Notification Bar etc. I am using 

"react-native-track-player": "^2.1.3",

**Comment by ABHAY-SAKARIYA** [comment]
i am facing the same issue

"react-native-track-player": "^4.1.1",

exactly what im facing is im testing my app in development build in android and ios both the notification controls works best for both the platforms, 
now when i build and preview version of my app using eas build in android it still works best but for ios devices i use testflight to distribute and install the app, so the notification controls not work in ios app why it is happening im not getting exactly,
it works in development build but not in preview version 

the content show in notification correctly but just not works is there any solution so that i can solve this issue?
