### ISSUE TITLE
Is there anyways I can disable Media Controls?

### ISSUE THREAD

**Issue by tuandinh0801** [DoubleSymmetry/react-native-track-player#777]
# Configuration

React native version: 0.60.5
What `react-native-track-player` version are you using? v1.1.8

# Issue
I barely can use Media Controls on both iOS and Android, Android just crashed when I click on the notification. Before the fix comes up, is there anyways I disable the Media Controls temporarily?

**Comment by Guichaguri** [comment]
Just remove the capabilities, the buttons won't show up.

**Comment by mapokapo** [comment]
`TrackPlayer.updateOptions({
    stopWithApp: true
});`

**Comment by creativeedge** [comment]
is there a way to not hide App status from notification screen, not just media controls?

We are electing to use a dedicated media control library so that we can incorporate Spotify and other services as well into one player.

React Native Track Player currently does now support Spotify SDK.
