### ISSUE TITLE
On iOS player fetches the whole track from server before it starts to play

### ISSUE THREAD

**Issue by casper1149** [DoubleSymmetry/react-native-track-player#783]
# Configuration

  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
      Memory: 436.88 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      npm: 6.12.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
      Android SDK:
        API Levels: 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-rename: 2.4.1

react-native-track-player v1.1.6

# Issue
I have a custom backend server logic, that streams audio files. It supports range requests.
What I noticed is, when I run my mobile app and start playing a track on iOS I see next log in my server output
```
GET 
range-header: bytes=0-1
```

And nothing else. Seems like the initial non-range request is missing in order to get the total length of the content. Cause the above range request returns Content-Length: (end - start) + 1, that's why no further requests are executed and no audio is played.

At the same time if I run it on Android I see a correct output on server
```
GET
no-range request
```

So client gets a correct initial Content-Length: totalLength.

And then when I execute seekTo a correct request is being send to the server
```
GET
range-header: bytes=10189217-
```

# Code

```
TrackPlayer.setupPlayer({
            waitForBuffer: true
        }).then(async () => {
            TrackPlayer.updateOptions({
                capabilities: [
                    TrackPlayer.CAPABILITY_PLAY,
                    TrackPlayer.CAPABILITY_PAUSE,
                    TrackPlayer.CAPABILITY_SEEK_TO,
                    TrackPlayer.CAPABILITY_JUMP_FORWARD,
                    TrackPlayer.CAPABILITY_JUMP_BACKWARD,
                ],
                compactCapabilities: [
                    TrackPlayer.CAPABILITY_PLAY,
                    TrackPlayer.CAPABILITY_PAUSE,
                    TrackPlayer.CAPABILITY_SEEK_TO,
                    TrackPlayer.CAPABILITY_JUMP_FORWARD,
                    TrackPlayer.CAPABILITY_JUMP_BACKWARD,
                ]
            });
            TrackPlayer.setVolume(1);
        });
```

Since the client and server logic is the same when executed on iOS and Android it seems like something is wrong with the iOS implementation. Or maybe I am missing some configuration option for iOS, but I did not notice anything in documentation, that could be causing this.

Can someone please take a look and advice?

**Comment by casper1149** [comment]
The only workaround I found is not to set the Content-Length header, in this case the Android client keeps working as expected and iOS client starts working, however since no Content-Length header is specified the iOS client fires a number of requests at the same time and only after that with a short pause it starts to play the audio
```
bytes=0-1
bytes=0-65535
bytes=65536-24005483
bytes=15944-65535
bytes=65536-24005483
bytes=65535-24005483
```

**Comment by casper1149** [comment]
More details about the server logic.

non-range response:
```
code: 200
Accept-Ranges: "bytes"
Content-Length: totalFileLength
Content-Type: "audio/mpeg"
```

range response:
```
code: 206
Accept-Ranges: "bytes"
Content-Length: (rangeEnd - rangeStart) + 1
Content-Type: "audio/mpeg"
```

**Comment by casper1149** [comment]
Another workaround I found is to handle the "bytes 0-1" case for iOS and treat it as a non-range request and returns
```
code: 200
Accept-Ranges: "bytes"
Content-Length: totalFileLength
Content-Type: "audio/mpeg"
```

This makes the player send another request which is an non-range request, but again, in this case it downloads the track completely and if you seek it does not fire any range request.

**Comment by casper1149** [comment]
Is it a problem of the underlying SwiftAudio library?

Cause Android implementation works fine and also if I paste my url to the browser it works just fine and as expected uses the range request approach similar to the Android impl.

**Comment by Bang9** [comment]
use hls

**Comment by casper1149** [comment]
@Bang9 thanks, but changing the "type" to "hls" did not help, the behavior remained the same.

**Comment by Bang9** [comment]
@casper1149 what is your media file extension?(encoding)

**Comment by casper1149** [comment]
@Bang9 My audio file (mp3) is stored in MongoDB' GridFS. When requested the web server specifies Content-Type: "audio/mpeg" in the response header.

**Comment by leosouza28** [comment]
@casper1149 any solution?

**Comment by casper1149** [comment]
@leosouza28 nope :(

**Comment by LudoLamerre** [comment]
Why this issue was closed, I don't find solution in responses ?
It is possible to read audio file before all file are fetched ?
