### ISSUE TITLE
Retrieve live audio data for spectrum analysis

### ISSUE THREAD

**Issue by besh81** [DoubleSymmetry/react-native-track-player#784]
Hi all,

is there any way to retrieve the live audio data in order to create a spectrum analysis visualizer?

Thanks
Besh

**Comment by mngyuan** [comment]
Wondering if this is planned to be worked on, I think it'd be a really cool feature but it does feel a bit non-critical. An app I'm developing could benefit from knowing the current amplitude a lot.

**Comment by Guichaguri** [comment]
It's definitely not our priority at this moment, but it's open for discussion
