### ISSUE TITLE
[iOS] Status Bar Network Activity Indicator

### ISSUE THREAD

**Issue by skizzo** [DoubleSymmetry/react-native-track-player#789]
I'm using version `1.1.8` and noticed that my [`StatusBar`](https://facebook.github.io/react-native/docs/statusbar)'s [network indicator visibility](https://facebook.github.io/react-native/docs/0.60/statusbar#networkactivityindicatorvisible) is influenced by the Track Player's caching status.

My problem is that I can't override this behaviour using my own StatusBar in the project any more. Any solutions for this? Thanks!

**Comment by curiousdustin** [comment]
@skizzo can you explain a little bit more? What were you doing before that no longer works?
