### ISSUE TITLE
cannot NPM install dev version

### ISSUE THREAD

**Issue by vladp** [DoubleSymmetry/react-native-track-player#791]
# Configuration

I am trying to install dev version of the package. Our android project is using androidX, but the release version of this package relies on older undroid libraries (like annotation) and others.

So wanted to try the release version, however getting NPM installation error

> 
> pm ERR! code 1
> npm ERR! Command failed: git submodule update -q --init --recursive
> npm ERR! warning: templates not found in /tmp/pacote-git-template-tmp/git-clone-b596bfd6
> npm ERR! error: Server does not allow request for unadvertised object 81ca1ae6413c1c301dfedc590a8a70ca2997c129
> npm ERR! Fetched in submodule path 'ios/RNTrackPlayer/Vendor/AudioPlayer', but it did not contain 81ca1ae6413c1c301dfedc590a8a70ca2997c129. Direct fetching of that commit failed.
> npm ERR! 
> 

Linux Fedora 31
RN 0.60.4
npm 6.12

**Comment by curiousdustin** [comment]
#703
