### ISSUE TITLE
Not able to play song from document directory

### ISSUE THREAD

**Issue by astha-shah005** [DoubleSymmetry/react-native-track-player#805]
# Configuration

Run `react-native info` in your project and share the content.
What `react-native-track-player` version are you using?
I am using version 1.1.8
# Issue
I have song on path "file:///data/user/0/com.cavary/files/144Maranamunundipranamunu.mp3"
but its not playing or not throwing any error

# Code
componentDidMount()  {
        RNFS.readDir(RNFS.DocumentDirectoryPath,'utf8').then((obj) => {
            if(obj.length > 0){
                this.setState({songs:obj})
            }
        })
    }

var file_uri = "file://" + item.path;
                    TrackPlayer.setupPlayer().then(() => {
                        let track = { id:'try', url:file_uri,title:"try artist",artist:"artist"}
                        TrackPlayer.add([track]).then(function() {
                            console.log("Track Added Created")
                            TrackPlayer.play()
                        });
                    })

**Comment by DrEdwardPCB** [comment]
having the same issue here would like to see if there are any workaround or resolve to this issue

**Comment by curiousdustin** [comment]
Which platform(s) are you testing on?

**Comment by DrEdwardPCB** [comment]
@astha-shah005 
 I think I may have a resolution to this issue
the track object url instead of passing a string, you should try to pass an object
```
 await PlayerManager.getInstance().addSong({
           id: uuid.v4(),
           url: {uri:"file://"+RNFS.DocumentDirectoryPath+"/songs/test.mp3"},
          })
 PlayerManager.getInstance().playSong()
```
the PlayerManager is just a wrapping to the track player library which is still in progress for my use, below is my current version of PlayerManager, still got lots of things to improve but at least it worked

```
import TrackPlayer from 'react-native-track-player'
import uuid from 'react-native-uuid'

export default class PlayerManager {
    static instance = null
    static getInstance() {
        if (PlayerManager.instance == null) {
            PlayerManager.instance = new PlayerManager()
        }
        return PlayerManager.instance
    }

    constructor() {
        this.ready = false
        TrackPlayer.setupPlayer().then(
            () => {
                this.ready = true
            }
        )
    }
    isReady() {
        return this.ready
    }

    //queueManagement

    async addSong(songs) {
        /*{
            id: 'trackId',
            url: require('track.mp3'),
            title: 'Track Title',
            artist: 'Track Artist',
            artwork: require('track.png')
        }*/
        console.log(songs)
        await TrackPlayer.add({
            id: songs.trackId?songs.trackId:uuid.v4(),
            url: songs.url,
            title: songs.title?songs.title:'unnamed',
            artist: songs.artist?songs.artist:'noname',
            //artwork: songs.artwork?require(songs.artwork):null
        })
    }
    getQueue(){
        return new Promise(async (resolve,reject)=>{
            var queue=await TrackPlayer.getQueue()
            resolve(queue)
        })
    }

    //PlayManagement
    playSong(){
        TrackPlayer.play()
    }
    pauseSong(){
        TrackPlayer.pause()
    }

} 
```
at least this works for me
@curiousdustin  thank you of your quick reply and btw this is a very nice library
I am using 
RN 0.62.2
react native track player 2.0.0-rc13
IOS 13.1
Xcode 11.3.1
MacOS Mojave 10.14.6

**Comment by curiousdustin** [comment]
I know it's not the same version either of you have reported using.

However, on iOS, RNTP `1.2.2`, I just tested the 3 ways of defining url's listed in the [docs](https://react-native-kit.github.io/react-native-track-player/api/#initializing-a-track):

```
url: 'http://example.com/avaritia.mp3', // Load media from the network
url: require('./avaritia.ogg'), // Load media from the app bundle
url: 'file:///storage/sdcard0/Music/avaritia.wav' // Load media from the file system 
```

All of these work for me in both debug and release builds.
