### ISSUE TITLE
Android Player Service in compact mode by default

### ISSUE THREAD

**Issue by dmathewwws** [DoubleSymmetry/react-native-track-player#806]
By default, the player service on android is in compact mode (with the play button hidden unless you press the toggle button on the top right)

Actual
![Screenshot_20191207-221408](https://user-images.githubusercontent.com/2018931/70385070-f9553880-193e-11ea-87a1-17e3a2610f42.png)

Would love it if by default it would be in expanded mode.

Expected
![Screenshot_20191207-220120](https://user-images.githubusercontent.com/2018931/70385064-db87d380-193e-11ea-8401-87409dd38d40.png)

is there a setting I'm missing?

**Comment by Guichaguri** [comment]
We can't simply control that. Android auto-expands notifications based on whether they're the top one and based on other user preferences. If you want to always show the media buttons, you can add the capabilities to the `compactCapabilities` property, which will show the buttons even in compact mode.
