### ISSUE TITLE
iOS: TrackPlayer.getState does not match current state

### ISSUE THREAD

**Issue by turnipdabeets** [DoubleSymmetry/react-native-track-player#816]
# Configuration

System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 334.72 MB / 16.00 GB
    Shell: 5.0.2 - /usr/local/bin/bash
  Binaries:
    Node: 13.3.0 - ~/.nvm/versions/node/v13.3.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v13.3.0/bin/npm
    Watchman: 4.6.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 25, 26
      Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 26.0.2
      System Images: android-24 | Intel x86 Atom, android-24 | Intel x86 Atom_64, android-24 | Google APIs ARM 64 v8a, android-24 | Google APIs ARM EABI v7a, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-25 | Android TV Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.0 AI-171.4443003
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
    `react-native-track-player: ^2.0.0-rc13`

# Issue
I've only tested this on iOS so it may be on Android too, but I don't know.

The state returned from `TrackPlayer.getState` does not match the actual state of the player
When the event `"playback-state"` is sent, the state does not change. Usually it starts on `idle` and then stays on `paused` no matter if the player is actually playing.

`let state = await TrackPlayer.getState();`

Meanwhile the code block below `state.rawValue` looks more accurate to what I hear but still off. Sometimes it sends paused when its actually playing
```
player.event.stateChange.addListener(self) { [weak self] state in
   self?.sendEvent(withName: "playback-state", body: ["state": state.rawValue])
 }
```

I did notice that I have a warning ```Sending `playback-state` with no listeners```. That goes away if I use the hook, but my component is stateful so I can't use a hook. What do I need to do to sync `TrackPlayer.getState();` to match the new state change?

The code below expects to play a track if no track is currently playing otherwise it should stop playing the current track and start playing the new track if the state is Playing

```
play = async (location: Feature) => {
    const {name, trackId} = location.properties;
    let track = tracks[trackId];
    if (track) {
      let state = await TrackPlayer.getState();
      if (state === State.Playing) {
        await TrackPlayer.add(track);
        await TrackPlayer.skip(trackId);
        await TrackPlayer.play();
      } else {
        await TrackPlayer.add(track);
        await TrackPlayer.play();
      }
    }
  };
```

To test the hook `usePlaybackState` I used the code below and added a `<StateTest />` to my component.

```
const StateTest = () => {
  const playbackState = usePlaybackState();
  console.log('playbackState', playbackState);
  return null;
};
```

Here are some logs:

```
FIRST TEST
Play song w/ code below:
await TrackPlayer.add(track);
await TrackPlayer.play();

 LOG  playbackState idle
 LOG  playbackState loading
 LOG  playbackState ready
 LOG  playbackState buffering
 LOG  playbackState playing -> `Song is actually playing`
 LOG  playbackState paused -> `Song did actually stop playing`
TrackPlayer.getState -> also paused

Play song w/ code below:
await TrackPlayer.add(track);
await TrackPlayer.play();

 LOG  playbackState playing
 LOG  playbackState paused
 LOG  playbackState loading
 LOG  playbackState paused -> `Song is actually still playing... this is incorrect`
TrackPlayer.getState -> also paused 


SECOND TEST

 LOG  playbackState idle
 LOG  TrackPlayer.getState idle

Play song w/ code below:
await TrackPlayer.add(track);
await TrackPlayer.play();

 LOG  playbackState loading
 LOG  playbackState ready
 LOG  playbackState buffering
 LOG  playbackState playing -> `Song is still playing`
 LOG  TrackPlayer.getState playing

While song is playing, play a new song w/ code below:
await TrackPlayer.add(track);
await TrackPlayer.skip(trackId);
await TrackPlayer.play();

 LOG  playbackState paused
 LOG  playbackState loading
 LOG  playbackState playing
 LOG  playbackState paused
 LOG  playbackState playing
 LOG  playbackState paused ->`Song did end`
 LOG  TrackPlayer.getState paused

Play song w/ code below:
await TrackPlayer.add(track);
await TrackPlayer.play();

 LOG  playbackState playing
 LOG  playbackState paused
 LOG  playbackState loading
 LOG  playbackState paused -> `Song is actually still playing...`
 LOG  TrackPlayer.getState paused

While song is playing (even though it says paused), play a new song w/ code below:
Play song w/ code below:
await TrackPlayer.add(track);
await TrackPlayer.play();

 LOG  playbackState paused -> `New song doesn't play but previous song continues`
 LOG  TrackPlayer.getState paused
 LOG  playbackState playing

 LOG  playbackState paused
 LOG  playbackState loading
 LOG  playbackState paused
 LOG  playbackState playing -> `Song that I expected to play while the other song was playing now plays`
 LOG  playbackState paused -> Song did end`
```

**Comment by komalharmale** [comment]
what is the solution?

**Comment by oneeb-asad** [comment]
Any solution?
