### ISSUE TITLE
Create template project for beginners

### ISSUE THREAD

**Issue by Guichaguri** [DoubleSymmetry/react-native-track-player#817]
We should create a template project (that can be used with the react-native cli, pretty much like [react-native-template-typescript](https://github.com/react-native-community/react-native-template-typescript)) that contains:
* The module linked on both Android and iOS
* The majority of the events being handled
* Background mode enabled
* A few action buttons to add/remove tracks from the playlist and play/pause

We should leave more complex examples to the example app.

**Comment by zacharywenner** [comment]
Would this be created starting with v2.0? This would be super helpful!

**Comment by ashishfeels** [comment]
This would be very helpful for beginners, I faced some issues while starting. Great Idea
