### ISSUE TITLE
It doesn't play on real device on Android.

### ISSUE THREAD

**Issue by emrepirnaz** [DoubleSymmetry/react-native-track-player#823]
# Configuration

`System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 403.74 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4
`
`react-native-track-player: 1.1.8`

# Issue

It runs smoothly on Android Simulator, but does not play on the device. I have tried solutions to known problems like register and http. It runs smoothly on iOS. usesCleartextTraffic not working.

# Code

            this.player.setupPlayer().then(async () => {
			await this.player.add({
				id: "trackId",
				url: "https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_700KB.mp3",
				title: this.state.programTitle,
				artist: this.state.programAnchor,
				artwork: require("@assets/images/placeholder.jpg"),
			});
		});

		this.player.updateOptions({
			stopWithApp: false,
			capabilities: [TrackPlayer.CAPABILITY_PLAY, TrackPlayer.CAPABILITY_PAUSE, TrackPlayer.CAPABILITY_SKIP_TO_NEXT, TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS, TrackPlayer.CAPABILITY_STOP],
			compactCapabilities: [TrackPlayer.CAPABILITY_PLAY, TrackPlayer.CAPABILITY_PAUSE],
		});

		TrackPlayer.addEventListener("remote-play", () => TrackPlayer.play());

		TrackPlayer.addEventListener("remote-pause", () => TrackPlayer.pause());

		TrackPlayer.addEventListener("remote-stop", () => TrackPlayer.destroy());

**Comment by Guichaguri** [comment]
Does any warnings or errors show up in logcat?

**Comment by strawberry-code** [comment]
Same issue here. I am running:

- react-native 0.62.0
- react-native-track-player 2.0.0-rc13
- device Samsung J5 Android 9

No errors, library imported and linked manually. Using example code: add track and play it, no sounds.

But is working on iOS.

**Comment by curiousdustin** [comment]
No further info in logcat?

**Comment by c0d3m3nt0r** [comment]
Same issue over here, with the following trace:
```
07-01 12:57:18.333 31547   518 E ExoPlayerImplInternal: Source error.
07-01 12:57:18.333 31547   518 E ExoPlayerImplInternal: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
07-01 12:57:18.333 31547   518 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:306)
07-01 12:57:18.333 31547   518 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
07-01 12:57:18.333 31547   518 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:934)
07-01 12:57:18.333 31547   518 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
07-01 12:57:18.333 31547   518 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-01 12:57:18.333 31547   518 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-01 12:57:18.333 31547   518 E ExoPlayerImplInternal: 	at java.lang.Thread.run(Thread.java:764)
07-01 12:57:18.336 31547 31547 D RNTrackPlayer: onError
07-01 12:57:18.337 31547 31547 E RNTrackPlayer: Playback error: playback-source - Response code: 403
07-01 12:57:18.341 13625 13625 I SKBD    : and isTosAccept false
07-01 12:57:18.350 31547 31547 D RNTrackPlayer: onStop
07-01 12:57:18.358  3872 13494 I WifiService: releaseWifiLock uid=10444
07-01 12:57:18.359 31547 31547 D RNTrackPlayer: Abandoning audio focus...
07-01 12:57:18.361  3872 13494 I MediaFocusControl: abandonAudioFocus() from uid/pid 10444/31547 clientId=android.media.AudioManager@37103b1com.guichaguri.trackplayer.service.MusicManager@224b096
```
It happens when serving either remote or local file.
Any clue about what might be wrong?, as @strawberry-code mentioned, it works in the emulator, but in the real device (Samsung S8+, Android 9).

**Comment by Guichaguri** [comment]
That's really odd, it looks like the server is rejecting the HTTP request with a status code of 403 Forbidden. Can you try another URL like `https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3` to see if it works?

**Comment by uojiaku** [comment]
I have this same issue. Any updates?

**Comment by abdulahia** [comment]
The easy way to implement this is to use this attribute to your **AndroidManifest.xml** where you allow all http for all requests:
**<application android:usesCleartextTraffic="true">
</application>**
