### ISSUE TITLE
v2.0.0-rc13 remote events doesn't work on iOS

### ISSUE THREAD

**Issue by dimaportenko** [DoubleSymmetry/react-native-track-player#831]
I did upgrade from (yarn.lock) 
```
react-native-track-player@^1.1.3:
  version "1.1.8"
  resolved "https://registry.yarnpkg.com/react-native-track-player/-/react-native-track-player-1.1.8.tgz#4827d46a14320c405d19f34593c3f999c2424b0f"
  integrity sha512-pAGMgEHtnrnHQYI53qxeZ/dNbw5CNiCTMjj6L09CQrWvZ6cJwjOQeyz4/6aOs7HfUDJc3HLntzKwTHYT7ges0g==
```
to 
```
react-native-track-player@^2.0.0-rc13:
  version "2.0.0-rc9"
  resolved "https://registry.yarnpkg.com/react-native-track-player/-/react-native-track-player-2.0.0-rc9.tgz#ac2036bcb8844d1e05b9367849abd0c90c6e11ea"
  integrity sha512-NAQyvAuU86VGPR45VFZLpsigNaxWZOAyigs7BxJfO8gknX22o/4408o2KDi+BbewsjL09g/Z52yg90KIhsj0PQ==
```

and I stopped to receive remote events on iOS. 

after debugging I found following difference inside `node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/AudioPlayer/SwiftAudio/Classes/AudioPlayer.swift` 
working version 
```
    public func load(item: AudioItem, playWhenReady: Bool = true) throws {        
        ...
        
        if (item is RemoteCommandable) {
            enableRemoteCommands(forItem: item)
        }
    }
```
new (not working)
```
    public func load(item: AudioItem, playWhenReady: Bool = true) throws {
        ...

        enableRemoteCommands(forItem: item)
    }
```

So if I add ` if (item is RemoteCommandable) {` check back, it works fine as before. 

Any ideas where and why this check was removed? And what is the best way to deal with this issue?

**Comment by nicoeg** [comment]
Hm adding the `if` didn't seem to help for me. 
Did you do anything besides adding it?

**Comment by troublediehard** [comment]
@nicoeg nope, only this change.

**Comment by Saehanseul** [comment]
1.1.8 work fine.
v2 has bug.
I didn't test dev yet.

**Comment by bdcorps** [comment]
Added the above-mentioned fix to v2.0.0-rc10. Remote commands from Control Center and Lock Screen started working.

**Comment by curiousdustin** [comment]
This is an issues with changes to the SwiftAudio sub module. My PR above resolves this without touching the sub module, but it has only been tested on v1.2.2 so far. Anyone have time to test it on v2?

**Comment by curiousdustin** [comment]
https://github.com/react-native-kit/react-native-track-player/commit/d3400a475d8be146aa25696b5f014dd538e2dd86 should resolve this. Will get this into v2 soon.
