### ISSUE TITLE
Player state is going to STATE_NONE and notification is disappearing while network interruption.

### ISSUE THREAD

**Issue by Sathyanarayan09** [DoubleSymmetry/react-native-track-player#844]
Notification is disappearing when there is a network interruption, how to make the notification widget stay at interruptions?    

react-native-track-player: 1.1.8 v
react-native: 0.60.4

occurrence: When track is played for 10 min, notification widget disappears and players stops playing.
platform: iOS and android.

**Comment by octodhruv** [comment]
@Guichaguri Any thoughts on the first issue? The state seems super unreliable lately. We're using this in production, and we've had many reports of users complaining that the audio keeps randomly stopping, pausing, or restarting. 

We think this could potentially be tied into losing and reconnecting network state.

**Comment by stokesbga** [comment]
Any updates on this?

**Comment by stokesbga** [comment]
Ok, maybe lets try to get a bit more detail into reproduction steps.

Are you guys using several instances of the player? (Like a mini player/ full player or just a player that mounts and unmounts often)
Displaying a progress bar?
Using hooks or class components?

**Comment by octodhruv** [comment]
@stokesbga Thanks for getting back to us!

We initialize the player when we initialize our app, and then we don't initialize it again. We have a mini player / full screen player, and we display a progress bar. We're trying to use the hooks `useTrackPlayerEvents` and `useProgress`. We wrapped the state functionality in our own hook where we store the state, as we found the state updates in general very unreliable.

If you'd like some more information, please don't hesitate to get in touch.

currently on version 1.2.2

**Comment by kenshinman** [comment]
Any luck with this? App stops immediately initialised in production
