### ISSUE TITLE
Remote/Media Controls not responding even though the console.log is responding.

### ISSUE THREAD

**Issue by alanhabib** [DoubleSymmetry/react-native-track-player#847]
react: ^16.9.0
react-native: 0.61.5
react-native-track-player: 1.1.8

When I go into a component with an audio playing from the trackplayer and later press lock everything works fine with the remote controls. The problem arises if I go out from the component and directly go back. Then suddenly the remote controls does not work except play/pause button. The remote-jump-forward and remote-jump-backward completely stops working. 

Here is the code in the service.js file: 

import TrackPlayer from "react-native-track-player";

module.exports = () => {
    TrackPlayer.addEventListener("remote-play",  (event) => {
        console.log("#DEBUG remote play #", event);
        TrackPlayer.play();
    });

    TrackPlayer.addEventListener("remote-pause",  (event) => {
        console.log("#DEBUG remote pause #", event);
        TrackPlayer.pause();
    });

    TrackPlayer.addEventListener('remote-seek', async (event) => {
        await TrackPlayer.seekTo(event.position);
        console.log("#DEBUG REMOTE-SEEK #", event);
    });

    TrackPlayer.addEventListener("remote-jump-forward", async (event) => {
        console.log("#FORWARD #", event);
    });

    TrackPlayer.addEventListener("remote-jump-backward", async (event) => {
        console.log("#DEBUG remote skipPrevious #",event);
    });

    TrackPlayer.addEventListener("remote-stop", () => {
        console.log("#DEBUG remote stop #");
        TrackPlayer.destroy();
    });
};

**Comment by Sathyanarayan09** [comment]
@alanhabib did you register the registerPlaybackService at root file?
TrackPlayer.registerPlaybackService(() => require('./src/playerService'));

**Comment by usamamoinakhter** [comment]
@Sathyanarayan09 if he didn't do that the play and pause wouldn't work either.

**Comment by curiousdustin** [comment]
This sound like it might be related to the remote commands issues, which should be resolved by https://github.com/react-native-kit/react-native-track-player/commit/d3400a475d8be146aa25696b5f014dd538e2dd86

**Comment by curiousdustin** [comment]
Is your issue only on iOS?

**Comment by wnr** [comment]
@curiousdustin I'm having the exact same issue as well. My console log prints when clicking on the remote buttons, but the playback does not pause/resume.

I've tested v 1.2.3, v2.0.0-rc13 and the dev branch (includes https://github.com/react-native-kit/react-native-track-player/commit/d3400a475d8be146aa25696b5f014dd538e2dd86) but none of them work.

**Comment by shivamjjha** [comment]
remove `async-await` just use normally, like `TrackPlayer.skipToNext();`

**Comment by closetothe** [comment]
@shivamjjha thank you SO MUCH for this. I just spent 2 days trying to get remote events working with expo-dev-client and after trying everything I thought it was just impossible. Nope! Just needed to configure track player exactly as described in your comment.

**Comment by KhanMRiaz** [comment]
can you mention the file names? 
which code should I put in which file?
and how to call it

**Comment by shivamjjha** [comment]
There is an [example folder](https://github.com/doublesymmetry/react-native-track-player/tree/main/example) contaiing just this
