### ISSUE TITLE
react_native_track_player.modulemap not found

### ISSUE THREAD

**Issue by bdcorps** [DoubleSymmetry/react-native-track-player#848]
Project build fails on iOS.

# Configuration

System:
```
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 699.51 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.15.0 - /usr/local/bin/node
    npm: 6.13.0 - ~/Desktop/newseon-mobile-2/node_modules/.bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild`
```

What react-native-track-player version are you using?
```
    `"react-native-track-player": "^1.2.2",
    "react": "16.9.0",
    "react-native": "0.61.5"
```

# Issue
The build causes a fatal error on XCode 11.

1. npm install react-native-track-player@latest
2. Go through the installation steps. Add `dummy.swift` and `Add Bridging Headers`. `pod install`.
3. Open project in XCode. `Clean` and `Build Project`.
4. Build errors (3):

```
<unknown>:0: error: module map file '/Users/user1/Library/Developer/Xcode/DerivedData/Project-bnzdcopbruyivsdaauxzjpvegrpz/Build/Products/Debug-iphonesimulator/react-native-track-player/react_native_track_player.modulemap' not found
```

```
<unknown>:0: error: module map file '/Users/user1/Library/Developer/Xcode/DerivedData/Project-bnzdcopbruyivsdaauxzjpvegrpz/Build/Products/Debug-iphonesimulator/react-native-track-player/react_native_track_player.modulemap' not found
2 errors generated.

```
```
<unknown>:0: error: failed to emit precompiled header '/Users/user1/Library/Developer/Xcode/DerivedData/Project-bnzdcopbruyivsdaauxzjpvegrpz/Build/Intermediates.noindex/PrecompiledHeaders/Project-Bridging-Header-swift_LHNBFA3GJ5S1-clang_17BDNQU27OW11.pch' for bridging header '/Users/user1/Desktop/project-mobile-2/ios/Project-Bridging-Header.h'
```

**Comment by kaustubh57** [comment]
same for me! :-|

**Comment by neoassyrian** [comment]
Same here

**Comment by charconstpointer** [comment]
and here

**Comment by plell** [comment]
same here

**Comment by budet-b** [comment]
Same issue with:

``` 
"react-native": "0.61.5",
"react-native-track-player": "2.0.0-rc10",
```

works with simulators but impossible to create a build. Clean node_module, Pods, DerivedData but same result.

**Comment by curiousdustin** [comment]
Is anyone having this issue on `v1.2.3`?

**Comment by budet-b** [comment]
I fixed this issue by upgrading supported iOS version to iOS 12.1 in XCode, hope it help

**Comment by marioot** [comment]
Same here, upgrading supported version doesn't help.

**Comment by kreonjr** [comment]
```
react-native-track-player 1.2.3
XCode 11.6
react-native 0.61.5
```

Only solution that worked for me was to switch to the Legacy Build System in XCode.

**Comment by Hexa-IT** [comment]
Same here

**Comment by Fr33maan** [comment]
https://github.com/react-native-kit/react-native-track-player/issues/785
same here, none of the solutions worked for me.

Issue only happen when trying to build in Debug

**Comment by Fr33maan** [comment]
@curiousdustin please help us, we are many stuck on this issue

**Comment by Fr33maan** [comment]
To add some details, I encounter the issue only in Debug scheme with a simulator.
Debug scheme with a real device works as expected

**Comment by Fr33maan** [comment]
Apparently, letting XCode indexing and processing files is the solution to get rid of the issue.

**Comment by itsmasabdi** [comment]
Andy update on this? I tried all of the above options and none worked

**Comment by marinne** [comment]
On my system (MacBook M1, Xcode 14.2) this "module map file not found" suddenly occurred after one day I performed the "Product > Clean Build Folder" action. I tried many solutions and building from VS Code terminal solved the problem. The build went fine and after a successful build in VS Code terminal, building in Xcode also began working again.

**Comment by KamranBarlas111** [comment]
It's not working and still facing the same issue

```
react-native: 0.63.2
node version: v20.6.0
react-native-track-player: ^1.2.3
```
