### ISSUE TITLE
Opus stream doesn't work

### ISSUE THREAD

**Issue by kirankuyate** [DoubleSymmetry/react-native-track-player#849]
# Configuration

React Native Environment Info:
    System:
      OS: macOS 10.15.3
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 687.11 MB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.3 
      react-native: ^0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

`react-native-track-player` version: 1.1.4

# Issue

- Cannot play opus stream. Is opus decoder extension included or is there a plan to include that soon?

# Code

Show us the code you are using

**Comment by felix-voicehub** [comment]
I don't think this has much to do with this package, but rather the underlying native Android/iOS players this package wraps around. I use opus and it works on both Android and iOS. What containers are you using?

**Comment by dcvz** [comment]
This is being tracked in #207
