### ISSUE TITLE
Play another audio before track change

### ISSUE THREAD

**Issue by damanpreetsinghds** [DoubleSymmetry/react-native-track-player#850]
I am currently working on an audio project that play tracks each of 30minutes duration. My requirement is that 5 minutes before current track ends, I want to play another audio informing user that track is about to end and then resume the track.
Found this helpful [comment](https://github.com/react-native-kit/react-native-track-player/issues/670#issuecomment-513416827). Can you help me in understanding how can I create two instances of TrackPlayer or any better approach that you can suggest to achieve this.
@Guichaguri

**Comment by damanpreetsinghds** [comment]
@Guichaguri , Can you suggest me with an approach to solve this?

**Comment by bepehr** [comment]
+1

**Comment by Himanshusngh93** [comment]
@Guichaguri @dcvz, Please can you help me with some solution to accomplish this feature.
