### ISSUE TITLE
Can't restore player UI

### ISSUE THREAD

**Issue by axebelk** [DoubleSymmetry/react-native-track-player#852]
# Configuration

info Fetching system and libraries information...
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 17.56 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.5.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.10.1 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 16, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.1
      System Images: android-16 | Google APIs ARM EABI v7a, android-16 | Google APIs Intel x86 Atom, android-19 | ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-22 | Intel x86 Atom, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-P | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-module: 0.11.1
    react-native-cli: 2.0.1

What `react-native-track-player` version are you using?
"react-native-track-player": "^1.2.2",

# Issue
While background audio is playing, If opening the app can't restore the player state / ui.

# Code

Show us the code you are using

**Comment by curiousdustin** [comment]
@axebelk can you explain your issue a little more?
