### ISSUE TITLE
Empty notification on Android devices

### ISSUE THREAD

**Issue by ghost** [DoubleSymmetry/react-native-track-player#859]
# Configuration
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 131.38 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
    npm: 6.13.7 - ~/.nvm/versions/node/v11.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

react-native-track-player: 2.0.0-rc13

# Issue
Device: Pixel 3a
Android version: 10
Issue: When registering the PlaybackService, as described in the documentation, it appears an empty notification (with no content) which is auto-dismissed after 1-2 seconds. 
 I think the reason of this behaviour are these lines of code
(From service/MusicService.java):

```
        if(!serviceForeground) {
            ReactInstanceManager reactInstanceManager = getReactNativeHost().getReactInstanceManager();
            ReactContext reactContext = reactInstanceManager.getCurrentReactContext();

            // Checks whether there is a React activity
            if(reactContext == null || !reactContext.hasCurrentActivity()) {
                String channel = Utils.getNotificationChannel((Context) this);

                // Sets the service to foreground with an empty notification
                startForeground(1, new NotificationCompat.Builder(this, channel).build());
                // Stops the service right after
                stopSelf();
            }
        }
```

This issue occurs on much more Android devices, not only on Pixel 3a.

Here is a screenshot:

![Screenshot_20200219-133220](https://user-images.githubusercontent.com/26306971/74832366-cb697880-531f-11ea-830e-fdf227a05537.png)

**Comment by ovy9086** [comment]
@Guichaguri if you can explain us the reasoning for that code to start the service and immediately stop it ... we can try and help you.

**Comment by kenneth-endare** [comment]
That's probably to prevent these exceptions:

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
```

**Comment by ainar** [comment]
I resolved a problem also about notifications on Android 10:
> in /android/build.gradle, change compileSdkVersion and targetSdkVersion to 29.

Solution may be the same here.
