### ISSUE TITLE
Issues in installing the library. (Native module cannot be null)

### ISSUE THREAD

**Issue by ajanmot** [DoubleSymmetry/react-native-track-player#866]
# Configuration

`System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 108.64 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-maps: 0.25.0
    react-native-splash-screen: 3.2.0
    react-native-vector-icons: 6.6.0`

I'm using the last version of react-native-track-player

# Issue
I've tried to install react-native-track-player following the installation guide. When I'm trying to import the react-native-track-player in my code I have the error : 

> Invariant Violation : Native module cannot be null

What can I do to avoid this bug please ? I've tried a lot of other solutions but without any success.

**Comment by ajanmot** [comment]
When I'm adding RNTrackPlayer.xcodeproject and libRNTrackPlayer.a like written in the installation guide I have the following error : 
`RNTrackPlayer-Bridging-Header.h:5:9: 'React/RCTBridgeModule.h' file not found`

**Comment by vaidis** [comment]
same problem here on linux mint 19.3

**Comment by lucasfnicolau** [comment]
Hello! I was having the exactly same problem. Luckily I found out this approach and FINALLY my problem is over: [https://github.com/joltup/rn-fetch-blob/issues/461#issuecomment-570497006].

**Comment by lucasfnicolau** [comment]
> same problem here on linux mint 19.3



> When I'm adding RNTrackPlayer.xcodeproject and libRNTrackPlayer.a like written in the installation guide I have the following error :
> `RNTrackPlayer-Bridging-Header.h:5:9: 'React/RCTBridgeModule.h' file not found`

Hello! I was having the exactly same problem. Luckily I found out this approach and FINALLY my problem is over: https://github.com/joltup/rn-fetch-blob/issues/461#issuecomment-570497006

**Comment by curiousdustin** [comment]
@ajanmot did you get this resolved?

https://github.com/react-native-kit/react-native-track-player/issues/503#issuecomment-513427501 May help.
