### ISSUE TITLE
Caching in iOS

### ISSUE THREAD

**Issue by Saehanseul** [DoubleSymmetry/react-native-track-player#883]
It's okay for streaming android music when network status changed like lte to wifi or wifi to anothor wifi because of caching.
but ios has problem when network changed.
Ios streaming stopped when network changed

Do you have plan for ios caching?
Or can you recommend alternative way for streaming music well when network changing?

**Comment by smn-snkl** [comment]
Any update on this? That would be an awesome feature. Any ideas on how to easily implement this?

**Comment by objectiveSee** [comment]
Following :)

**Comment by gpawlik** [comment]
Hi @curiousdustin , is this feature something that you are looking into? Are you aware of any blocker or an outstanding issue that makes it difficult to implement on iOS?

**Comment by bradleyflood** [comment]
Thanks all. I've just added this to the Project Backlog, so we can review it and see where it fits in the timeline or plans (or if this is already done or planned?). Cheers!

**Comment by gpawlik** [comment]
Hi @bradleyflood , could you please give us some insights on the priority for this feature? Thanks!
