### ISSUE TITLE
audio/aacp

### ISSUE THREAD

**Issue by dmozar** [DoubleSymmetry/react-native-track-player#888]
# Configuration

Version 1.2.2

Unable to play audio/aacp stream.

Example stream url: https://sradio1.ipradio.rs:9000/;

# Issue

Player on start buffering 3 seconds, then stop. Unable to play. Please advice.

# Code

**Comment by curiousdustin** [comment]
Which mobile platform(s) are you testing on?

**Comment by dmozar** [comment]
Android.
