### ISSUE TITLE
library not found for -lPods-trackplayer-tvOS

### ISSUE THREAD

**Issue by EhteshamAnwar** [DoubleSymmetry/react-native-track-player#893]
# Configuration

Run `react-native info` in your project and share the content.

> System:
>     OS: macOS Mojave 10.14.6
>     CPU: (2) x64 Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz
>     Memory: 852.63 MB / 8.00 GB
>     Shell: 3.2.57 - /bin/bash
>   Binaries:
>     Node: 12.16.1 - /usr/local/bin/node
>     Yarn: Not Found
>     npm: 6.13.4 - /usr/local/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.8.4 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
>     Android SDK: Not Found
>   IDEs:
>     Android Studio: Not Found
>     Xcode: 11.3/11C29 - /usr/bin/xcodebuild
>   Languages:
>     Java: Not Found
>     Python: 2.7.16 - /usr/bin/python
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 16.11.0 => 16.11.0 
>     react-native: 0.62.0 => 0.62.0 
>   npmGlobalPackages:
>     *react-native*: Not Found
> 

What `react-native-track-player` version are you using?
9.0.2

# Issue
I am trying to build for Ios, after installing pods and all other steps required,  I get this error. 

![image](https://user-images.githubusercontent.com/16754151/79036143-b651ed00-7bde-11ea-8c14-27d9695672f1.png)

Show us the code you are using

**Comment by curiousdustin** [comment]
Are you trying to build for iOS or tvOS?

**Comment by curiousdustin** [comment]
@EhteshamAnwar did you get this figured out? 

It looks like something is wrong with your xcode project. You need to make sure you are building for iOS only.

Also what version of `react-native-track-player` are you using? The version you mentioned, `9.0.2` is not an existing version.
