### ISSUE TITLE
Time unit for getPosition [ANDROID]

### ISSUE THREAD

**Issue by vbspace** [DoubleSymmetry/react-native-track-player#898]
Calling getPosition() in IOS returns the value in seconds, but in Android it is looking like its in hours. Can someone confirm if this is true ? Please.

EDITED - Its showing the right value for the last song on the queue but from the first song until before the last it is not returning the right value.

Note: I am calling it inside of PlaybackTrackChanged

Version : 2.0.0-rc13

**Comment by Guichaguri** [comment]
Can you elaborate, please?

**Comment by ntk860** [comment]
Hi @guichaguri I am just trying to get the amount of time that the track played inside of PlaybackTrackChanged. In IOS it returns the right valeu but in Android it’s not returning the same value.

**Comment by Guichaguri** [comment]
What do you mean? Can you provide examples or step-by-step instructions so we can try to reproduce the issue?

Also, the [playback-track-changed](https://react-native-track-player.js.org/documentation/#playback-track-changed) event gives you the position of the previous track in its payload if you're looking for that
