### ISSUE TITLE
Is there any timeout setup?

### ISSUE THREAD

**Issue by rochapablo** [DoubleSymmetry/react-native-track-player#906]
**Is your feature request related to a problem?**

Sometimes the stream takes too long to respond causing the react-native-track-player to cancel the request and throw the error (Unable to connect to... _(the stream url)_).

**Describe the solution you'd like**
Be able to maximize the timeout of the request. 

**Describe alternatives you've considered**
I do have two urls to the same streaming so... when one goes off I try another, but this still don't solve the problem for some users.

```
"react": "16.12.0",
"react-native": "0.61.5",
"react-native-track-player": "^1.2.2",
```

**Comment by komelabbbas** [comment]
same problem any solution ?
