### ISSUE TITLE
Add `reason` key to PlaybackTrackChanged event to tell why track changed

### ISSUE THREAD

**Issue by ds8k** [DoubleSymmetry/react-native-track-player#916]
**Is your feature request related to a problem? Please describe.**
As a developer I need to be able to quickly and consistently determine when a track has changed based on various reasons (track ended, skipped to next/prev, etc.)

**Describe the solution you'd like**
I'd like to be able to check the event data for a `reason` key in order to tell when a track has ended due playing throughout

**Describe alternatives you've considered**
I could check the position provided in the event data and check it against the tracks duration when available

**Additional context**
Similar code has already been implemented in a separate fork here: https://github.com/mgonzalezs/react-native-track-player/commit/91b2dce67f18809923587977852ea8e965c71aa6

**Comment by vaukalak** [comment]
This might be very useful in case you need to mark a track as `already listened`.
