### ISSUE TITLE
Enable caching and storing live streams data to a mp3 file.

### ISSUE THREAD

**Issue by afkcodes** [DoubleSymmetry/react-native-track-player#945]
It will be awesome if we can store the streams cache in a mp3 file that can be played at a later time.

**Comment by objectiveSee** [comment]
I’m also interested in that

**Comment by ashishfeels** [comment]
@Guichaguri  Have a look at this

**Comment by Guichaguri** [comment]
I'm pretty sure it is on Android, I don't know about iOS though

**Comment by ashishfeels** [comment]
yes @Guichaguri it's there in Android. and has been implemented in one of the forks i guess

**Comment by gilbertl** [comment]
> yes @Guichaguri it's there in Android. and has been implemented in one of the forks i guess

Which fork ?

**Comment by objectiveSee** [comment]
Curious if this is planned to be implemented on iOS 👼
