### ISSUE TITLE
[iOS]: queue is not repeated/played after the `PLAYBACK_QUEUE_ENDED` event is fired

### ISSUE THREAD

**Issue by z4o4z** [DoubleSymmetry/react-native-track-player#948]
**Describe the bug**
I'm trying to implement the queue repeat functionality via skipping to the first track in the `PLAYBACK_QUEUE_ENDED` callback and playing the queue, this hack is working on android, but do not work on iOS(no errors, the queue is just not playing). Also, I've tried to  `reset` and even `destroy` and `setup` the library in the `PLAYBACK_QUEUE_ENDED` callback, nothing is help

**To Reproduce**
- Add tracks to the queue
- Implement the repeat hack with the code below
- Play the queue

**Environment (please complete the following information):**
- **react-native info:**
  ```text
  System:
      OS: macOS 10.15.3
      CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
      Memory: 37.19 MB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK: Not Found
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    Languages:
      Python: 2.7.16 - /usr/bin/python
    npmPackages:
      @react-native-community/cli: Not Found
      react: 16.13.1 => 16.13.1
      react-native: 0.62.2 => 0.62.2
    npmGlobalPackages:
      *react-native*: Not Found
  ```
- **react-native-track-player version:** `1.2.3`
- tested in the simulator and real devices: iPhone 11/10

**Code**
```typescript
// player.ts
class Player {
  // ...
  public onQueueEnded = async ({ track }: { track: TrackID }) => {
    const { shuffledTracks } = this.getState();
    const firstTrack = shuffledTracks[0];

    if (firstTrack) {
      await TrackPlayer.skip(firstTrack.id);

      await TrackPlayer.play();
    }
  };
}

// playback-service.ts
module.exports = async function () {
  const player = new Player();

  // subscribe to other events

  TrackPlayer.addEventListener(TrackPlayerEvents.PLAYBACK_QUEUE_ENDED, player.onQueueEnded);
};

```

**Comment by curiousdustin** [comment]
The example app does not present this behavior for me.

If I add the following to service.js, the queue starts playing the first track as expected after the last track ends.

```js
  TrackPlayer.addEventListener('playback-queue-ended', async () => {
    await TrackPlayer.skip('1111');
    await TrackPlayer.play();
  });
```

Is it possible that you are not receiving the expected result from your `getstate()`?

**Comment by devpascoe** [comment]
> The example app does not present this behavior for me.
> 
> If I add the following to service.js, the queue starts playing the first track as expected after the last track ends.
> 
> ```js
>   TrackPlayer.addEventListener('playback-queue-ended', async () => {
>     await TrackPlayer.skip('1111');
>     await TrackPlayer.play();
>   });
> ```
> 
> Is it possible that you are not receiving the expected result from your `getstate()`?

is await TrackPlayer.skip('1111'); referencing an actual track id of 1111 or is it the case the current code when skipping to a not found track id jumps to the start of the queue?
