### ISSUE TITLE
Mixed tabs and spaces in iOS source code

### ISSUE THREAD

**Issue by puckey** [DoubleSymmetry/react-native-track-player#949]
The whitespace of the iOS source code is a mix of tabs and spaces. I would suggest to switch to an indent of 4 spaces to match the java side. Happy to take care of a PR for this.

**Comment by curiousdustin** [comment]
@puckey Would this affect the SwiftAudio code? Would it be best to leave that as undisturbed as possible to make it easier to include any future updates from the main repo?

As far as the RNTP iOS code, I would say yes, it would be great to make sure it is cleaned up.

**Comment by puckey** [comment]
Yes, good point on the SwiftAudio code - that should stay untouched.
