### ISSUE TITLE
Add playback-track-loading callback to update metadata including url for the about to load track

### ISSUE THREAD

**Issue by JunWangMaster** [DoubleSymmetry/react-native-track-player#951]
Feature request:
This is related to #818, I also need a lazy url fetching player, that issue suggests we should manage our own queue, but that seems a hack and not an ideal solution.
If RNTP can provide a "playback-track-loading" callback, to update the metadata like url and duration for the about to load track, it will solve this problem altogether, and we can still use the built-in queue and features like notification.
Wait playback-track-loading event return (maybe with a configurable timeout) before starting loading media, this can happen when pre-loading next track or loading current track, whenever the track media is about to load.

An alternative (maybe simpler) of allowing lazy fetching url is to make TrackObject.url support callback function, the callback function can do internal state management as not to fetching url every time it's called, maybe also update the metadata.

Related #818

**Comment by ser-emejia** [comment]
@JunWangMaster did you find a solution?
