### ISSUE TITLE
compatibility with react-native-video

### ISSUE THREAD

**Issue by neoassyrian** [DoubleSymmetry/react-native-track-player#965]
I'm having an issue with installing react-native-track-player and react-native-video together on the same application, mainly related to the version of exo player.
Does anyone have a fix for this or managed to integrate the 2 together? 
I'm not sure what the requirements are for each plugin. 
I'm planning to post the same topic on the react-native-video github.

**Comment by santiripper** [comment]
It's posible, not very elegant but it works, you have to change the version of the exoplayer on the `build.gradle` of the `react-native-video` package.

If are you using the track-player v1.x branch change this on the video package:

```
    implementation('com.google.android.exoplayer:exoplayer:2.9.3') {
        exclude group: 'com.android.support'
    }
```

with:

```
    def exoPlayerVersion = safeExtGet("exoPlayerVersion", '2.10.1')

    implementation("com.google.android.exoplayer:exoplayer:${exoPlayerVersion}") {
        exclude group: 'com.android.support'
    }
```

Also, maybe you'll have to comment the lines 417 & 417 in `ReactExoplayerView.java`

```
//                return new HlsMediaSource(uri, mediaDataSourceFactory,
//                        minLoadRetryCount, mainHandler, null);
```

**Comment by santiripper** [comment]
Here's a patch: https://gist.github.com/santiripper/1b9e210c5e307e736631138d148d84f7

**Comment by neoassyrian** [comment]
> It's posible, not very elegant but it works, you have to change the version of the exoplayer on the `build.gradle` of the `react-native-video` package.
> 
> If are you using the track-player v1.x branch change this on the video package:
> 
> ```
>     implementation('com.google.android.exoplayer:exoplayer:2.9.3') {
>         exclude group: 'com.android.support'
>     }
> ```
> 
> with:
> 
> ```
>     def exoPlayerVersion = safeExtGet("exoPlayerVersion", '2.10.1')
> 
>     implementation("com.google.android.exoplayer:exoplayer:${exoPlayerVersion}") {
>         exclude group: 'com.android.support'
>     }
> ```
> 
> Also, maybe you'll have to comment the lines 417 & 417 in `ReactExoplayerView.java`
> 
> ```
> //                return new HlsMediaSource(uri, mediaDataSourceFactory,
> //                        minLoadRetryCount, mainHandler, null);
> ```

I'm using the latest version of track-player. Is that the same?

**Comment by santiripper** [comment]
This works with the latest stable versions `react-native-track-player@v1.3.2` (not 2x) and `react-native-video@v5.0.2` 

Note: this will remove HLS support for video

**Comment by neoassyrian** [comment]
> Note: this will remove HLS support for video

Thats the only reason why I want to use react-native-video, for HLS videos.

**Comment by andrekovac** [comment]
May I ask another related question: What is the video player to use alongside `react-native-track-player`? 


I'm using [expo-av](https://docs.expo.io/versions/latest/sdk/video/) but have an issue with sound not playing in iOS release builds. Still not sure whether this issue is related to `react-native-track-player` though.

Thought of trying `react-native-video` instead.

**Comment by curiousdustin** [comment]
I have `react-native-video` alongside `react-native-track-player` in my project. It seems to work fine.

However, I am only playing a single intro type video in my project, so I have not really explored the full use cases of `react-native-video`...

Others have reported crashing issues when the version of ExoPlayer used in these libraries varies too much. You just need to pay attention to what version each is depending on and try to align them.

**Comment by neoassyrian** [comment]
> I have `react-native-video` alongside `react-native-track-player` in my project. It seems to work fine.
> 
> However, I am only playing a single intro type video in my project, so I have not really explored the full use cases of `react-native-video`...
> 
> Others have reported crashing issues when the version of ExoPlayer used in these libraries varies too much. You just need to pay attention to what version each is depending on and try to align them.

Which version of exo player are they using? Also which versions of the plugins are you using? 
I tried adding the latest of the plugins, and the project stopped building (after introducing react-native-video)

**Comment by curiousdustin** [comment]
My current production app is using 

```"react-native-video": "^5.0.2",```

Alongside at forked version of `react-native-track-player` that is based on `v1.1.8`.

Sorry I know this is not recent. But, still wanted to share my experience.

**Comment by andrekovac** [comment]
I got it working with the changes suggested by @santiripper - it runs everywhere but on Android release builds. It's this issue which I'm dealing with: https://github.com/react-native-community/react-native-video/issues/2021

@santiripper You didn't face this issue?

**Comment by neoassyrian** [comment]
I got them to work using the latest track-player plugin and the video plugin. Make sure version 5x of the react-native-video, which is NOT the default branch in npm. 
You will nee need to run
npm install - - save react-native-video@5.0.2

**Comment by pedromarta** [comment]
None of the aforementioned fixes were working up for, so I'll try to help any others that might have been in the same situation as I did to keep it working:

- yarn add react-native-video@5.0.2 --save
- yarn add react-native-track-player@1.1.4 --save

Now open node_modules/react-native-track-player/android/build.gradle and replace every '2.9.2' version substring with '2.9.3' to match the same version as react-native-video for the exoplayer dependencies.

It worked for me, hope it works with anyone else that is still looking for a solution!

**Comment by infinitbility** [comment]
> My current production app is using
> 
> `"react-native-video": "^5.0.2",`
> 
> Alongside at forked version of `react-native-track-player` that is based on `v1.1.8`. (The fork does not change the ExoPlayer version)
> 
> Sorry I know this is not recent. But, still wanted to share my experience.

Thanks, it's work for me

**Comment by stereodenis** [comment]
Still not compatible. No audio on react-native-video videos in android
