### ISSUE TITLE
Some tracks repeats last seconds once the track has ended

### ISSUE THREAD

**Issue by alfredvaa** [DoubleSymmetry/react-native-track-player#968]
**Describe the bug**
This library is used in a project to play tracks in m3u8 format (HLS). For some reason some tracks is repeating the last seconds once more after the track has ended. In most cases it is the 10 last seconds, which would also be the chunk size of the HLS-chunks. 

**To Reproduce**
Play a track in HLS format. The problem seems to occur most often when a track is not seeked in, it should be played from start to finish for this to occur.

**Environment (please complete the following information):**
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 211.06 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.6.0 - ~/.nvm/versions/node/v10.6.0/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v10.6.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmGlobalPackages:
    react-native-yunolink: 2.0.2

Using react-native-track-player latest master.

Occurs only on iOS devices and the iOS simulator.

**Comment by alfredvaa** [comment]
Updated the issue and removed Android as this seems to only be an issue on iOS devices.

**Comment by ninacoder-info** [comment]
Same here, sometimes its stop for a second then start again
