### ISSUE TITLE
[iOS] Buffer is not working as expected

### ISSUE THREAD

**Issue by robinalexandre** [DoubleSymmetry/react-native-track-player#970]
**Describe the bug**
In RNTrackPlayer.swift I added in the setupPlayer method: 
`
let minBuffer: TimeInterval = config["minBuffer"] as? TimeInterval ?? 15
player.bufferDuration = minBuffer
`

`player.bufferDuration` is then passed to `AVPlayerItem -> preferredForwardBufferDuration` which should control the buffer size. However, it seems like the buffer is controlled automatically and I can't do anything about it.

**To Reproduce**
Add in RNTrackPlayer.swift in the setupPlayer method:
`
let minBuffer: TimeInterval = config["minBuffer"] as? TimeInterval ?? 15
player.bufferDuration = minBuffer
`

Add then the minBuffer options to the TrackPlayer.setupPlayer method.

**Environment (please complete the following information):**
react-native info:
`
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 1.78 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.1 - /usr/bin/javac
    Python: 3.7.3 - /Users/alexandrerobin/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: ^4.5.1 => 4.5.1 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0-rc.1 => 0.63.0-rc.1 
`
react-native-track-player: V2 branch
Tested on real device using iOS 13.5

**Note**
The default behaviour could be enough for me but the aim of that is mainly to debug my app because of another problem. When my app is in background mode (phone on lock screen for example), and I reach the buffered size, the mp3 is not loaded (buffered) anymore and so the playing is stopped. If someone know how I could fix this issue ?
PS: my mp3 is 1 hour long

Thanks for this amazing library!

**Comment by robinalexandre** [comment]
Any news about it ?

**Comment by puckey** [comment]
Please try setting the `waitForBuffer` option to `true` as described in https://github.com/react-native-kit/react-native-track-player/issues/616

**Comment by robinalexandre** [comment]
After trying to set `waitForBuffer` option to `true`, it does not change anything for me.
Moreover, if you look at line 87 in AudioPlayer.swift, you can see :

 ```
/**
     The amount of seconds to be buffered by the player. Default value is 0 seconds, this means the AVPlayer will choose an appropriate level of buffering.
     
     [Read more from Apple Documentation](https://developer.apple.com/documentation/avfoundation/avplayeritem/1643630-preferredforwardbufferduration)
     
     - Important: This setting will have no effect if `automaticallyWaitsToMinimizeStalling` is set to `true` in the AVPlayer
     */
    public var bufferDuration: TimeInterval {
        get { return wrapper.bufferDuration }
        set { _wrapper.bufferDuration = newValue }
    }
```

I still can't understand why `preferredforwardbufferduration` is not working in my app.
