### ISSUE TITLE
Catch Expired Auth Token to modify headers

### ISSUE THREAD

**Issue by robinalexandre** [DoubleSymmetry/react-native-track-player#977]
**Describe the bug**
When you query a network file with auth token headers, the firsts queries are OK. However, if your token is expired after an amount of time, the app can't download the other parts of the file and you don't get any error.

**Environment (please complete the following information):**
`System: OS: macOS 10.15.5 CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz Memory: 1.78 GB / 16.00 GB Shell: 5.7.1 - /bin/zsh Binaries: Node: 12.12.0 - /usr/local/bin/node Yarn: 1.22.4 - /usr/local/bin/yarn npm: 6.13.1 - /usr/local/bin/npm Watchman: 4.9.0 - /usr/local/bin/watchman Managers: CocoaPods: 1.8.4 - /usr/local/bin/pod SDKs: iOS SDK: Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2 Android SDK: Not Found IDEs: Android Studio: 3.6 AI-192.7142.36.36.6241897 Xcode: 11.5/11E608c - /usr/bin/xcodebuild Languages: Java: 13.0.1 - /usr/bin/javac Python: 3.7.3 - /Users/alexandrerobin/anaconda3/bin/python npmPackages: @react-native-community/cli: ^4.5.1 => 4.5.1 react: 16.13.1 => 16.13.1 react-native: 0.63.0-rc.1 => 0.63.0-rc.1 `
react-native-track-player: V2 branch
Tested on real device using iOS 13.5

It could be good to have a kind of callback to allow us to modify the headers if a query fail. I tried some things with resourceLoader on AVUrlAsset but none is working for now.

Not tested yet on Android but I presume the problem should be the same.

UPDATE: Created an issue in SwiftAudio repo because the resolution should come from there for iOS [#119](https://github.com/jorgenhenrichsen/SwiftAudio/issues/119)

**Comment by puckey** [comment]
Do you have a way for us to easily reproduce this issue?

**Comment by robinalexandre** [comment]
Yes sure. 

Just query a file which is protected with an auth token. Set an expired time for your token of 2 minutes and you'll get a 401 error within approximately the 2 min. To see the error on the query, I use a proxy like Charles because we don't have log about this in the library.

Is it clear enough ?

Thanks

**Comment by KochMario** [comment]
I'm not quite sure why this was closed, since it appears that it's still not possible to update headers of a track once it's in the queue.

Was there any progress on this? @robinalexandre did you find a solution for your case?
