### ISSUE TITLE
Play audio from memory stream

### ISSUE THREAD

**Issue by copang** [DoubleSymmetry/react-native-track-player#979]
Hi,
I want to ask if there is any way to play an audio from memory stream?
I want to load encrypted audio file from local and decrypt to byte array, then play it.
Thanks!

**Comment by MasterTeus** [comment]
I'm also having the same problem, I'm using rn-fetch-blod to download an .mp3 file in the Download folder on my local storage (android).
I cannot play the mp3 file stored locally.
Any solution?

**Comment by sirakoff** [comment]
@MasterTeus have you tried using `file://` prefix in the url?

Check out #947 for more info

**Comment by sirakoff** [comment]
@copang I don't think its possible with this library yet. Have you looked into encrypted Http Live Streaming (HLS)?
