### ISSUE TITLE
Including speaker management to control the output source for an Audio file

### ISSUE THREAD

**Issue by Jasbir23** [DoubleSymmetry/react-native-track-player#99]
This is not an issue, could possibly be a good enhancement. The ability to control the output source of sound. Sometimes I might require the sound to be played through the Earpiece of the phone instead of the primary speaker. I have a similar requirement and I have to use a different Library just for speaker modes.
Thanks in advance, great job with the repo guys. 👍

**Comment by Guichaguri** [comment]
Can you give examples on use cases that this might be useful?

**Comment by Jasbir23** [comment]
@Guichaguri Lets consider a user who wants to listen to a private Audio message. User would just use a button to switch to earpiece mode and listen to the message without anyone else knowing about it, no need to attach earphones.

**Comment by CmerCy132** [comment]
Is the speaker management available on the latest build?

if yes, how can I use it?
