### ISSUE TITLE
Adding a single local audio file into the queue won't play

### ISSUE THREAD

**Issue by danielbogomazov** [DoubleSymmetry/react-native-track-player#991]
**Describe the bug**
The `play` function would not play the audio of a local file added to the queue with `add`.

**To Reproduce**
(See code below)

**Environment (please complete the following information):**

- react-native info
````
System:
    OS: macOS 10.15.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 165.96 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.2.0 - /usr/local/bin/node
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
````
- react-native-track-player version: 1.2.3
- Testing using a simulator for iOS

**Code**
````
await TrackPlayer.add({
    id: '...',
    url: 'file://' + pathToFile,
    title: '...',
    artist: '...',
});
await TrackPlayer.play();
`````

**Workarounds**
I previously used `TrackPlayer.reset()` before adding/playing a new audio file but I noticed that it would cause a crash if there was audio already playing (I'm assuming that using `reset` to fix this issue was also just a workaround and not the intended purpose of the function).

The way that I got around this was by wrapping it in a 0ms setTimeout:
````
setTimeout(async () => {
    await TrackPlayer.add({
        id: '...',
        url: 'file://' + pathToFile,
        title: '...',
        artist: '...',
    });
    await TrackPlayer.play();
}, 0);
````
(This also worked by adding `await getCurrentTrack()` before the add/play). I'm not really sure why these methods work, but I'm just sharing my quick hack here in case anyone else has a similar problem or would like to look into it.

**Edit:** The workaround doesn't actually prevent the crash. It just seems to be crashing less than when I used `reset`.

**Comment by maxckelly** [comment]
@danielbogomazov  Any solution here? I'm getting the same issue. On component load I'm adding a track which plays fine, can be paused, stopped etc... However when I add another track to the queue I can't play any audio. I can see its being added to the queue but doesn't play any sound. 

I've noticed though that this only occurs on an iOS device works fine in a simulator.

**Comment by elburu** [comment]
@danielbogomazov  @maxckelly I have a similar issue here, do you find any solution?

**Comment by maxckelly** [comment]
Hi @elburu, 

Unsure if this will be of help but what I'm doing is the below. I'm calling track reset before playing. This is a workaround but with the nature of our app its working fine. 

Hope it helps

```
export const miniPlayerPlay = (track, storyData) => {
  return async (dispatch, getState) => {
    const { currentTrack } = getState().miniPlayerReducer;
    const isTracks = Array.isArray(track);
    const currentQueue = await TrackPlayer.getQueue();
    const isTrackInQueue = currentQueue.some((queue) =>
      queue.id === track.id ? true : false
    );

    // If user clicks on a new story and its not the current track then stop player
    if (currentTrack && track.id !== currentTrack.id) {
      await TrackPlayer.reset();
    }

    if (isTracks) {
      await TrackPlayer.reset();
      await TrackPlayer.add([...track]);
    } else if (isTrackInQueue) {
      await TrackPlayer.play();
      return;
    } else {
      await TrackPlayer.add([track]);
    }

    await TrackPlayer.play();
    dispatch({
      type: MINI_PLAYER_PLAY,
      payload: { track, storyData },
    });
  };
};
```
