### ISSUE TITLE
Invalid channel for service notification: null

### ISSUE THREAD

**Issue by 24dev** [DoubleSymmetry/react-native-track-player#994]
**Describe the bug**
Full error and stack trace:
```
android.app.ActivityThread$H.handleMessage
ActivityThread.java, line 2137
android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: null
```
```
android.app.ActivityThread$H.handleMessage ActivityThread.java:2137
android.os.Handler.dispatchMessage Handler.java:107
android.os.Looper.loop Looper.java:237
android.app.ActivityThread.main ActivityThread.java:7948
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:493
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1075
```

**To Reproduce**
Only on Android 10 real devices, specifically Galaxy A20e & Galaxy A40. Exact repro steps unknown, but appears similar to the fixed issue https://github.com/react-native-kit/react-native-track-player/issues/534

**Environment (please complete the following information):**
Not related to local environment. Issue was caught by our AppCenter logs.
_What `react-native-track-player` version are you using?_
v 2.0.0-rc13

**Code**
Unknown

**Comment by aknad** [comment]
I've the same issue
on AppCenter crash logs the only devices involved are Galaxy running Android 10
Galaxy A51
Galaxy S10+
Galaxy S9
Galaxy A6
Galaxy A20e
....
