### ISSUE TITLE
Import error in react-native-web app.

### ISSUE THREAD

**Issue by Danil-Dorokhin** [DoubleSymmetry/react-native-track-player#996]
**Describe the bug**
Got error when tried  to import TrackPlayer in my react-native-web app. Works normaly when i start it on android device or emulator with npx react-native run-android but throwing error when i trying to open it in web with npx react-scripts start.  

**To Reproduce**
Just init any react-native-web project, put a rn-trackplayer import in it and run 'npx react-scrpits start'

**Environment (please complete the following information):**
React version 16.13.1
React-native version 0.63.1
React-native-web version 0.13.4
React-native-trackplayer version 1.2.3
OS: Windows.
**Code**
Error: 
`Attempted import error: 'STATE_BUFFERING' is not exported from './index' (imported as 'TrackPlayer').
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'`

**Comment by VelislavP** [comment]
I have the absolutely same bug. Have you figured out by now how to fix it?

**Comment by nickmcmillan** [comment]
I solved this by creating a wrapping component which uses [platform specific extensions](https://reactnative.dev/docs/platform-specific-code#platform-specific-extensions), and anytime I need to import TrackPlayer I'd import it from this file, not from the package.

Obviously additional work would be required to port the functionality over to web, and I haven't gotten that far yet, this is just to get passed those errors you identified.

```
// TrackPlayerWrapper/index.js

import TrackPlayer from 'react-native-track-player'
export default TrackPlayer
```

```
// TrackPlayerWrapper/index.web.js

const TrackPlayer = {
  seekTo: () => {
  },
  registerPlaybackService: () => {
  },
  // etc
}

export default TrackPlayer
```
