### ISSUE TITLE
Crash when playing URL with whitespaces

### ISSUE THREAD

**Issue by kazzkiq** [DoubleSymmetry/react-native-track-player#997]
**Describe the bug**
When adding a track with `url` property containing a value with whitespaces, the component (and subsequently the entire app) crashes.

**To Reproduce**

Simply add a track with whitespaces such as:
[https://sevn.dev/static/sample audio.mp3](https://sevn.dev/static/sample%20audio.mp3)

And see the app crash.

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
```
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.60 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.2 - ~/.npm-global/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
      System Images: android-25 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.1 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.60.3
```
What `react-native-track-player` version are you using?
```
1.2.3
```
**Are you testing on a real device or in the simulator? Which OS version are you running?**

Both simulator and real device (in production) can reproduce the error.

**Code**

```js
// where track.url is an URL with spaces
TrackPlayer.add([track]).then(async () => {     
  TrackPlayer.play();
  emitter.emit('TRACK_STARTED', track);
});
```

**Comment by curiousdustin** [comment]
Can you try the latest (unreleased) on dev? 

https://github.com/react-native-kit/react-native-track-player/pull/950

**Comment by kazzkiq** [comment]
@curiousdustin it worked! When do you guys think there will be a new release on npm?
