### ISSUE TITLE
`useProgress` hook not working

### ISSUE THREAD

**Issue by PaulExina** [DoubleSymmetry/react-native-track-player#999]
Hi, I am using `"react-native-track-player": "^2.0.0-rc13"` and I have the following error when using the `useProgress` hook : 
![image](https://user-images.githubusercontent.com/14274731/87337563-ebeed500-c543-11ea-939a-ef473c41279e.png)

I didn't have this problem three weeks ago. Can you bring some light on this ?

I have this issue on both ios Simulator and Android Studio and I am using `"react-native": "0.62.2"`.

**Comment by rdgoutiyama** [comment]
Same here, in React native 0.63.0

In 0.60 works, but i don't make downgrade.

**Comment by edscaylart** [comment]
Same here, it was working until yesterday.

**Comment by edscaylart** [comment]
@PaulExina @rdgoutiyama  Run `yarn add react-native-track-player@next` again. For some reason yarn made a downgrade on react-native-track-player

**Comment by rdgoutiyama** [comment]
> @PaulExina @rdgoutiyama Run `yarn add react-native-track-player@next` again. For some reason yarn made a downgrade on react-native-track-player

It works! Thanksss

**Comment by PaulExina** [comment]
Bug fixed ! Thanks a lot 🙏

**Comment by nerdaliciousCH** [comment]
Can confirm this. Bug exists on 1.2.7, is fixed when using a 2.0.0-rc15 release candidate.

**Comment by bradmurphy** [comment]
Yeah, this is coming back as undefined on 1.2.7

TrackPlayerEvents doesn't work on 2.0.0-rc15

**Comment by nerdaliciousCH** [comment]
> Yeah, this is coming back as undefined on 1.2.7
> 
> TrackPlayerEvents doesn't work on 2.0.0-rc15

Did you use `useTrackPlayerEvents` hook and `Event` enum?
